apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:Cm8+o7wbiX+Asyb1Kds0Jw==,iv:xklMhOU0a91IuEchm+DhKulG8+sZ4eAQxM8pe6lVMYA=,tag:yPXI4gNZL8A+w9mN/SsD2A==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:J1jjWMB/aA9ZDkf9R7sHlA==,iv:rzAOUeAb4e+bTQlIieDLIu4kDDYA1tEQh9qb8QNHi3A=,tag:MpMRElGbn/5aCI9FGLhqdQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-admin
    namespace: monitoring
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsalh0c3F2L0xUeXQ4cS9L
            VVRlWFNLUUxUQmRZVlhhRlhpbnF6MjFMelUwCmJ1cmliNkliUGRMZkdnZFUwOWV1
            UUhyVDNFMUJObEhwOW5HM1g5MkZSUTgKLS0tIGhOMkNPelJYQ2xxQnJHQ0xDR2lJ
            SXJsN2lpbkx4dy9qd3Z1anJERkd6ZzAKbeBxYBZ2LRuAc4kBiwGUbMEiNrKtzhbV
            5Fj0D5apmH+ZPdW4+Pyqh7gPKAWdMFy7W8+E6r4oApje7YHR6j8QVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bmg0ZnNTV1BqekhtelJS
            ZVFFMTNXQWQrME9pODh5RlpHaFlFbTQwdERrCjFDZnFXQ0pqZ3hLZi9HamFhS01B
            SjlRaWRtczZNZlFtUEJLYUNiUzNRYXMKLS0tIDJkMk5WcWhvUTViR2NNZENwcGdk
            Y3RKSjVFajNBZWpoTHFlc1BEUmJXVmcKtawcEcnBxWOZRlmNEAOhjOI1ANpsv8rW
            /GFJhdx/NqjzXQT2t1BzQcknkDulphL0vmeKTxxg/YOek1BbERQeIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M3dDdVczUXRsTytsbFJo
            TlJqNi9sMldhTERSajgrc0FxRVROY0d0eEFjCk85RDF3QWVqWXhwYXFpL0RZUlpy
            Zjd5ODNXU3ZnVEJZNVhiTGcweG1tSjQKLS0tIDhYYnFzSFlKOEl2TkZKRkZ1ZnNI
            WUZHWjFVOFlUSFE0ZlZwV2VvenpYekkK4CC4tW5dvKDg4BoG8z+IMArnF1ILeXPD
            +v6aE+T7gc/dSLnE4Y4LsRE1hW3xP6ASwoumA2lCaEW7B0xEvPSRrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:25:39Z"
    mac: ENC[AES256_GCM,data:iSKQGRLYEVspHpKVulFi5EyfF9diSPe4XKSBgkQ/nEqgYJclCmh6V6tM6bSLHkBuO2O1kUQkJ6oIccmKq3AYsiH0Qr582zEgbG/nE+OlscwFtgjLaBHiBEaWjAqkCh2qiagECzoKBMHPv+6Ha6cWgGNMw/pJ9DSql7oJYgqBtSA=,iv:dxKWNI8KAQf3fqdjtSMTGYafeaDqHEX9aNT1HupFbSY=,tag:ZqNKEQarEh3f0VdvGdiESw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
