apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:l8o5ZWz5Q22D7/AI20jfCA==,iv:JDtAIuUI+Fwcfmu0ZzxOStxd+WPYQZluTPO6/Wh/HoE=,tag:N6CmLQ1AkuqO/SDi+yFNVQ==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:rcEb9scm9eBDIQRyqCH4XQ==,iv:sv8nI567iA+qjNS6UQCShBK+DIr5sbCaVEP02Oh/Fxw=,tag:T6wIhUUELBYXCjKCHtRIbQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-admin
    namespace: monitoring
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcFhXTzkrbWJxY2twLzFi
            S3lKcThkbnN2RDZhM3BUZnJlL0I3VHhqbmlrCnJta3dQZjNmZ3VvYWg2dHJVbnM0
            MVlOV3ROb0RjWFJqWWhOa0lWWXhRSUkKLS0tIHZhbFV0T2dsQzhzb216a2NYTWNC
            dzhyWDRBTjNiSERNZmVvSW52cjZwYUUKUSQAV4VVXb+vzcg0KcUBaXpEUC28MexZ
            rtFBFQxqV8xutXqxRNlDkUHulyAAjqkCGKgCrEDfJe4EOTP58VS1QA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZWdJQTFMbnVaS2pseXMy
            UDdoeHJLMTNiMmVzSXdnMUYvMzllWDZiTUEwCjZqUm5nVmwra1ZQdWV6MU91dlZN
            T2gwcy9SSE9EWjM5eWZBZlN5cksxU2sKLS0tIHBxSUFpOFErMDZGRGQ4SDVzTFFn
            T05mVTFjVHlmM2RCWlBqTVUweDJmTFkKvmJchQcwbBEZ5KMS7HRcMA8PhD0TXgay
            OrGQjEiGBD8KrTB8a6cGTkftIbaSdmJruA/GA9jIIw5ARXQn0B7/HQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MmRPUWE3NEZYWnYxeGNw
            MkZ5bzFCMElTSzFvYnpxcllYVzdvRUtZenl3CmVNRHFMdExWRGdvY0VSMFZ3V3Rr
            akdHa2wvSnNnRlFuSVVjaWNDSlBXR00KLS0tIHhLK3dLTXZhSmpYVnViVG1jUWxl
            ak8xSEpJR2YxRDQ4RHRscE5GYm1IYWcKkJEPqfPO/FctkW9oGYQw0JjmlZo9iZeL
            YxVFEhIbn8VWbwR678yiOG0WWSKhQcmwgwnOZXtpMAfjcuRa+/bSoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-21T14:31:48Z"
    mac: ENC[AES256_GCM,data:x36YG1viev1L2O5fyRSVEn3HAyn5F+9r6u8/URp+zTTGLTr0yz+JaSmuzu70ALAZ6Q+FYyyaLYLwSjeCF+WkAd9sEm2zSB9kcf4YUbOS3aKr/eNhf36YXsR5JDEGpycGl6CtoVtX5XqLtXIm1tNz0e4NoV6JvwZQ7L/6v4Vo6dE=,iv:tiYexI9asiyrDk20qm5sq2DPWxE8MmCvPGOGO74rAPM=,tag:3zfoGZRtbm0FfSmlQb4+TA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
