apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:zzqkTu0Xe4cw6hFGlMugqQ==,iv:qDW3iK6beohWVohanj4AmAzS5TUx9n9zUGriybpCCz0=,tag:r2QDVSZh5X2Uf91W0Hvj4w==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:qCGBnBhyzJ2MGPb21luWkw==,iv:mj848jRH6M5K8ML110x6jCPoR5tWHxEMWSkv7rQXzs8=,tag:VTtiBw4lJRsigESUZypC5g==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-admin
    namespace: monitoring
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcTR0TkVNdGl4R0psdWNK
            VUQ0K21XRkxra2hadEU5MmhodE1pcEwyMTBNCklaUGtEQ0dDZmdtWFRHWGVETG1z
            bkxSeXpPTmVvZHZwT2l1ZHN5ZUx5ancKLS0tIHZraGh1M3dRbHp1TEpZTnZyQStD
            c1NxTDhRdnZyUkpqcXh4KzY2U0hNYmsKmgoJhzbv8qgsrh8kK+/d89gLfTphBgn3
            2hQr4rP96f842r+eIp6Dzy+MSDxVPEGiG/sF7D+Ap/WOH5TcqssA9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeGVqc2RaRGhWSEVlZnpC
            aVgyZlpQNVkzSEY2ZE1IQVRjSk5xck5DdXdzCmMzNEFmMHdOZng0NWljSmM4Y3ZV
            NFZoV2RoTEJwSWZWQ3o4MkhFZVdqVmsKLS0tIC85RHcrbnVjSHZjY3A0U0Z0MlQ1
            M2FiNS90alR6SDBOLzdxK0UvZDRxRUEKlQO+PiIowMe9ONUjusgSlaLet+qTZDMA
            Id/4byS9pTWRLh7Zv5VljvMD/SYO2BSrE8AAsPc4NfAL2zCCrWXPFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWERmL25JdFp6MDc4V3JR
            K1Vrdmk5aHZHS2V4czVQZmM2NXdnMXptMUZzCktIdFAwWEYzYzk4cnF2YWpkbExI
            RFY1UkMyTnJjdk1Cd3JBMWhmYmxoT0kKLS0tIGhXY0IxQU8zNzJvSjAwQUVhQnhZ
            Yk9IZytMaXk5ajhEZzdkQ3ZwaEx4TUUKRtXl/65UZQa9r6ooGWSQXUw1G/KOQrgo
            aX7nvH8K9Q+qomAeQb5+4lnukLRuD+5pj6d03HWGPgW2isiUtKMlsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T16:11:13Z"
    mac: ENC[AES256_GCM,data:bFblbRnfs9s9QOkWmw5LH/QDYQ8Mzn/nNyTW2TwjCaDqtYycYO5cubnSnVJM9Vsfxa1h4ithAqv97Eqvyh+6/Amin2nBJ9LYriRV/YwV7tymnpYDcqyvxJ35Hiq5PGrtfBakFUfqSz3FcSHRsUPdJFBKO95TneTxFGklSBn67m0=,iv:0TSiPCkk1tmLtxnUC/zgpASkYYOub/agiw3dnnkkvd8=,tag:pSOUVGgFXksyeJttXBax7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
