apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:c0ZhgO+rQz1bZryrdrvX2g==,iv:aCmwNIqrkbcpywceRQXsK+XNN1oKzCBNYECPBzOeTPs=,tag:MGEsQJ5OmW2evqFVIaPTiQ==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:8Uj/OH8u5ph8I4DmHnn+BQ==,iv:lDS32xmrpHDSV3L36Okw1jpgS3bVBWr8CYwL3c1wkmI=,tag:J608ZCWr+d/7618dLoEUCw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-admin
    namespace: monitoring
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dElnSTJSeEZsd3pZRFVL
            dFBGcWdRcEMwRE1mdjRWN3FLTkVaSXI2M1RJCkljMEhUTWlBdHJsaG1DaHozUWdt
            WkZFUUlrM3V3STVBblNLM1p3cG5HL28KLS0tIGVVT3lGUzNSWVkxcVdhUXFGa21q
            OUZQK3JKUGxCVm1iLzluS3FiVnRWazQKXGsZFo59tJq6fIsujVFXrjDsCKncfcUY
            rIfYUbXil7KsCQHfk/IFoMivGdx8gVq6q0loRHWGrNMwNLuACStKGQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbEVURzZBUVpkZ1JPOUl2
            T2luRUI4V3d2OG41SjRVcnZrWE9TUHp6eUdnCjBGTzJubmswdzBpY0JDWTZzYWV3
            SDh1QzVteW5ZbTFUUEcyeUUweHd2eHcKLS0tIEVjZHlibU4vRmlPcWxPRmI3VE11
            UXR2Nnh2VjQxSDEybkE5U2lPWitOdTAK6FRxc2JgqD0NL/TKQY7fWL7aag5t/0av
            hBXZo//NJEAq/4g1ul3mwkaPVP6Wnu1TR9FrQ/3VhFq9NQr7V7LO8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVDR4WWdFSzVlZnlxWjhO
            YW9UMWI2TVpDRk91R0FRa2FrZHRsbHJPRTFJClhmKytKOVkrZEVVem5sYjlWd2Z2
            eDlEZkVPWmNiWWN1VHBpTUduci9DR1UKLS0tIDRZS2VHdUtwY1I0a084K3hmZzM2
            Q0x1Mk5lVmVNa3RxWmRVS3FRUktNVkUKR7Yy7tgn5bJbt796PqNPG+avRV/wY0dn
            Ai0HL0IdM9lLIg8izal0yaYu4bjUCCir7ttR7d5CHpXfCC0+Mjq8TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T15:50:38Z"
    mac: ENC[AES256_GCM,data:kjIuvngeSrGTlGaYgXOsYQehDDag+RruDtl5WKDTa0Y78R3ZZw/FdW03zcDnZWsWy3oWO5kj2FnEQZ9gjPD9z22eW0hJ7g3/18ldcTKxTJ7fOuBzeBAOjWf8BpXvrDEqMgd0Thdzmcr6B38qmGXnF67KpijG+UYoBOXJMDH0r+Q=,iv:QBM2rAo5AeIFq0SdXtuqCkGOjec0Ki6yQj0G2gTDccY=,tag:kE4Hw4+IcxXRADJ2XKozXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
