apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:inW8DRJNHrChBXLfxlhj+w==,iv:MCAXBjDMqjelfyh70Uy/PtnNNEB9LK6EZRJCs47twxk=,tag:VfT7MN5wRWYU49boeGDSZA==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:Gf+KVgBCoJT9U+uJscwEAQ==,iv:iw5TZ5g33PtheW3i+hlSa6J4M8svjPOmha/ozJsuMck=,tag:lcxZ7nPPNDfWxCLYfpljbg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-admin
    namespace: monitoring
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MHAzVVpXR1lYenV4UzQy
            UzlLYzYzZitjV1JpdVREVGlrQUNQaU5WaTF3CmVqcTJlanBtWHZnQ1dnOHpta0x5
            aDRtWmpKOTlhT0hDTE82ck9TcDAxb0kKLS0tIENHa210ajNPcXpzcjUzc282NG1D
            b0E0YlVqcmxXemtDdW5jWFRHZExEelEKbETPtdLMUX3dXDxdtlToFQo2cwhYcJrC
            eg/DFSQayJe8op1Ge0rM0ZEcJZGyKdw8nhXf8nRL1bYdUXRHv2HIGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dzZ1cWllb2lDL2FtU0Va
            Z3JnYnJHeHN2eGlHeXFOMWNqYjJuc2dydDFzCmlqd1dCbENHbG9JM1VWUDNVZlll
            eTdjV1BpMjVxUWNpUXBjQm5WVTdWV3MKLS0tIENrQkxocUdaemNaMUFjNGMyNmdH
            cThzYWxvZ2NXNUZsVmZQeWpqVnF6a2sKGutQ+0DDspHZahrDG03lVY9Awrp1um0T
            2KBCIFXZCfgVztfFtg9r++BSj94HPcfJCC2WDISezmVe2ntWfiWdyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWjFJdmRFL2dnQnJRenFU
            L25weVZDb1RSbWhqd2NoKytCM3AxR0hOcTBNCkJFNCs2Y2ZkMFJaL0tEdXBSeTVL
            bmtQanYvc1ZRSUpPb2lqQklHbGVEeWcKLS0tIGVGYllndzF2TWF6bmx4ODgxdSs0
            MTNSZGhJWFNtQkdFOFJzWGd4a3J4THcKuisQBaLXOQm4UsYTwdE+o1CSY8yW42qR
            McMcFqSuFXrCRpzbqGC8dE5LbuwDBYwVE3Q7e9HvEfVqOprX8K4KnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:37:19Z"
    mac: ENC[AES256_GCM,data:sGvFsQ2vhulC2VEh0+vmX7N40c8fOmL4YAEpjP3hF+4rWMnPe7maIhPLYtvQlfXc5nJGOtCQMpkNkxf9OkB511uD1jk9vBoXMdAOjCgVESqfR01uEpyAzjiWHrRhuE1gcibTGtmN37VknSGFJzOYert96eAHDXRlaCdKGdiigV4=,iv:JF35LxiROOKsCAtk1AbPshn2aqZ6wRcedo0feaW3KHE=,tag:GN9+nwcWjHhE4GBxcUaAnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
