apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:CZFFjFbx2SwuPJZh6klcmQ==,iv:QgHB70ag7f+qLDqx/SRO7wSB5lua7j8BuCVXNiM2lbY=,tag:KFVOmCC1/uS7fgyHxkb96g==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:H1tMzbCJBNHsO4eKI58Q3w==,iv:dupMBZDb8QrKy5+FMIk2VSYC3BfweXtuMKAjiSUTOG0=,tag:uZ7tdYvG3bCo1NbKoVVndA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-admin
    namespace: monitoring
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5em9yeUYvNHFiMjRRc2cy
            VzdaOE9vQTlMK1ZjS2pqa3V2Vk5UOVBMRm5JCjBpWW5XQ0txMmRLTnZwYk85b3Bx
            bjd6d0VEYmRHdjVsSEhIWTdLT2czc1kKLS0tIFB6VktZb0gwb043UmJVYkI0N2kw
            elhMTmNXNVVOTE85QmNLWC8vYmYweWsKt+e5md6mq/V55pieDQODe6fcuTf42NCs
            S1P9TETequxsxRrpQ7hxRJucnpK+zibVj+CrCbT/S5FPBVe2CTxZWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISlZkZGprWlpOUVJNbjZU
            R0JKalpiVzQ1RmZ3ZXBTTEhkazE5RnkwQnprCllQMXR4dnhOQmthSTI5aXUrWWJl
            TG40cjhQVGFmNlBrT0xIbWU1bjNkK1EKLS0tIG1sZjE2MEpuR091c0Y1aFBqT0lC
            endtNFhzdEZ0VU1wYWxNTU1udG0zcXMKzE6+J4EcyKWz+UJuxhSLg1Sl80x40X50
            4DjA3csounWYLRgS8sleXXZPViCFDpzE09wDsQI1HN/MN5BVvyhd/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdXAyMHZKMGNvdWxsVko5
            VlByU1NBRE1JdzJ0aWRRZ2VWQkdqRmhhUUFBCitvVVl2RmR4YUxSc3FaQTYvU1VY
            NlA1Z25ucysyb0d1L2JiZ1hrV2VXMUEKLS0tIExSRkpVUmxYNCtYVHBpeURwR0lS
            V0hHbVhsQ29iQW1SL0liT2tqbkluQXMK0kxGtklNcsgiv9gZbgkbWkSg7oYwJjZ+
            9hcOQAIL3g9bv+Clm7FsFvNCVHx24y+QcxN4G/YAD57//aD3d+kwDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:46:16Z"
    mac: ENC[AES256_GCM,data:zYMAmKvoIIHTK9irJ21wgS+ziYkrG1rFxhqVhfywM0bzYlmNk/SaF8EzyqdXIGhXCRPpNtUy70vtm85mFfHd959vDqu5bhBK8vz56RbnUA2oxn0cgC758jb8AzPY7ToNh8db3B4WJ9GeiF7tM8/cdCfOGvqo9/uKAkKWs+IbHYk=,iv:HJLn7Nzq9pRRld5NqwF7OnQKnQLtwNnHj9cViYzQXJo=,tag:bF80KP4XFAFPjelasuYGRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
