apiVersion: v1
data:
    contact-points.yaml: ENC[AES256_GCM,data:eyaUANqNfB18ONkYfgITMILPrlQ/ux8GsB/e6EobB9/k/jGotiD6T5YVn1ie1z6dKfEsrOXJqiH1HxyqB04fujxAQQjCS4DdRZMxFiGKKj8k/QKa0Xmftw1W0z8U5HXiDzUf0zzMXrXxlXocJ6aCsyQRvifBSq66HnvlydSkx76HB6VR1riYY4qtc7tVyryZCaTHDSc99PHMD5aqC5iWk74cz4jSAII7prI5xzBabyZ5PBU8H49nYnpa95WUNFeNCIxB4I+QU/6zVfuQk885+x1iPALwPLdsQcn69V1tV7egyq7sRAwo35aMPRS4+Zziozf3eHzb04MspDVVnKEcewfecPAUcQaX3IA7zFwiNl9x328=,iv:aFBKIMQ63XjWU6kPDvSVT/tav7JZTF4X/ukYZxNf/J0=,tag:gOMYB5UYvNUNlBt0VDhXlg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        grafana_alert: "1"
    name: grafana-alerting-contactpoints
    namespace: monitoring
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSldQTHpDdjRFMnowS3Vw
            RXI3TXFSRTZURDE2WGxDbVk0dXo5UEkyUXlnCmwxRmM5N2FYMXVDQmNrVEJDREVL
            aXB3TWk1NE42YzBUNTljNzhYZXJZbEUKLS0tIHRINkdMamUxMWoxTkNwVTNJTWg0
            U01CSFpSZ29XYmRtSG5WOUdWMEc3VmcKxrEpbKRSAV+qxCaWBMmidvncLA8BalMB
            4cI8JZHauoo+R2pN1HbxJ0nDPiyUftD60HvGLgb501N8+zYa9wEUKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUblIyeHlLUitDOHhTaXZl
            VzdSMlRUcnpNYnR2UEhodGY1VlY0NDQwaXlZCnlXQXhVTHR5SndwcEJaR25pSnJ4
            S2w5UmV4ekNhWkR6c01wbHRaWFpyZDAKLS0tIE40eUlVVjYyRGkvaXdUM09zVGdo
            L1diUi9RVER3cWRUelBYNVBxcHh2YWcKuvPJcSimhdiW3j8Su9NpQbZrOgW5P7tW
            m5cqA9L4oLLEOWhUJudrfPiC8P9gIcChqr/oy8x611C/F1d4xSMFIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY3hlZ05DN25xYytNaW1H
            U3NKMW9RZXFrdXVlaVF4VEtzUUtwa2tkR2hFCjNwdXBWSmY2Y2kzOE9vcTNwaEor
            VC9TVlFVTUlRam53QTFqbHJXR3FIbXMKLS0tIENoRCtOWmFiVXFkR2tDL3Y5bnJL
            ZEgzUTZhV1VwZko3amRESXVyaVBCMUEK8Mh72tXIzF5YselCaRYxudNFFJhRqKkK
            g77IYUUejlP/1cOYRO98mW0PcABU4y6DLvGQBex1h5Yewy8q4yLqgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T15:25:18Z"
    mac: ENC[AES256_GCM,data:W1CPa76uDR/iKNR1p2gpGRnsKox+qYzxeYVAvkq6SeLuuR4S8FkwJZs42cgUvwbnPK1wHOBhmFGVkPdkP4K3B+wEBOqkXfYmXJfMKGihnuuBkkC1YOUG9zctW+6S1IkeB73sVt1kAieEBY0AT+mwL9/f6iF1Z/+o7mtwzB+dh2A=,iv:qYeYBrPWBztA+Wic9SaPQRomgGqS7UMs6jrNKDXxNBs=,tag:ZS8KXUA8BOO/7nXiHAbFxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:YSSpQX0NMrsHIqNUqVZfjg==,iv:SfNJD9D1o9qqPJu9nLzT/n3HtVSo+27GOsCi6VGLLic=,tag:J0v55WYUwyqXk7wNBnSLOA==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:wlwe7k1l6m/kLL86RKD3OA==,iv:6/SfZOxU3zDLRKbbbag30+dB/twNYpC7B6j7BVu4uU4=,tag:cktkHexWpkrMxJSpmBetkg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-admin
    namespace: monitoring
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSldQTHpDdjRFMnowS3Vw
            RXI3TXFSRTZURDE2WGxDbVk0dXo5UEkyUXlnCmwxRmM5N2FYMXVDQmNrVEJDREVL
            aXB3TWk1NE42YzBUNTljNzhYZXJZbEUKLS0tIHRINkdMamUxMWoxTkNwVTNJTWg0
            U01CSFpSZ29XYmRtSG5WOUdWMEc3VmcKxrEpbKRSAV+qxCaWBMmidvncLA8BalMB
            4cI8JZHauoo+R2pN1HbxJ0nDPiyUftD60HvGLgb501N8+zYa9wEUKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUblIyeHlLUitDOHhTaXZl
            VzdSMlRUcnpNYnR2UEhodGY1VlY0NDQwaXlZCnlXQXhVTHR5SndwcEJaR25pSnJ4
            S2w5UmV4ekNhWkR6c01wbHRaWFpyZDAKLS0tIE40eUlVVjYyRGkvaXdUM09zVGdo
            L1diUi9RVER3cWRUelBYNVBxcHh2YWcKuvPJcSimhdiW3j8Su9NpQbZrOgW5P7tW
            m5cqA9L4oLLEOWhUJudrfPiC8P9gIcChqr/oy8x611C/F1d4xSMFIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY3hlZ05DN25xYytNaW1H
            U3NKMW9RZXFrdXVlaVF4VEtzUUtwa2tkR2hFCjNwdXBWSmY2Y2kzOE9vcTNwaEor
            VC9TVlFVTUlRam53QTFqbHJXR3FIbXMKLS0tIENoRCtOWmFiVXFkR2tDL3Y5bnJL
            ZEgzUTZhV1VwZko3amRESXVyaVBCMUEK8Mh72tXIzF5YselCaRYxudNFFJhRqKkK
            g77IYUUejlP/1cOYRO98mW0PcABU4y6DLvGQBex1h5Yewy8q4yLqgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T15:25:18Z"
    mac: ENC[AES256_GCM,data:W1CPa76uDR/iKNR1p2gpGRnsKox+qYzxeYVAvkq6SeLuuR4S8FkwJZs42cgUvwbnPK1wHOBhmFGVkPdkP4K3B+wEBOqkXfYmXJfMKGihnuuBkkC1YOUG9zctW+6S1IkeB73sVt1kAieEBY0AT+mwL9/f6iF1Z/+o7mtwzB+dh2A=,iv:qYeYBrPWBztA+Wic9SaPQRomgGqS7UMs6jrNKDXxNBs=,tag:ZS8KXUA8BOO/7nXiHAbFxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
