apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:DvfU9SXRYuHBKA==,iv:Uj2Lc2TkV1Jx3aN6VhTRAwPPDhw2Iank482k/Gomews=,tag:SMOSowriK04hfY5H0eGEAQ==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:CFF4t7hwDe5uAA==,iv:vu8KLvvvAo8Wh7NUPeVjaYVaepOGazchTuXEeMqg5sk=,tag:blkZZ8wsZi8U+GGSeRrM9g==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-admin
    namespace: monitoring
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxemJ4c0lTV3RDNVlkdGxY
            VzlMZjhPWi9SSDZ4eTMxQXRPL0lKSDN3ZVd3CmhEQ0hPY2JhMVhWb3lIQ01rK1lz
            ZE9yT1owckRnVndqNittQVJ5ZnVIUDgKLS0tIEdnU3dJbXNMYk1VeDBaMGRZS3NT
            QUxwYkZITFU4ZCtRZDdUNXNXOUFQaWcKLaJ/nC7efjm91p7tNNDVgJ9s9gkYu1Mr
            gM4ob64E4WHpJ2lQdzAfSR9dTe1COmgLl75EaGDfOJBoiFRdhwA3IQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc3JFeFJzVmNSTVJXS0pC
            THRqaDM5ejYvSzBISmduN3BBTlh3Nm9KaGtJCmtTVGJkNVRkV2JiM0VNbzRoaHdR
            T2hxUCtzUHRwd1hTSk45akc4Nk9YemMKLS0tIFFRK0EweTIyd29VRTlVQnl4d293
            aWVndE54RUxGcUpPZ1VzMDBuZkNXbEkKBfw5NVMg8pxxd4h57cIPvmA1GbtulRi5
            D4vPs8APPkq9Mj80xC7qXxWw5tcmNQRvhihmX1Nc9IwMin3MrrWHfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbWtBdmsxblcyK0tVVEZF
            QUVUWEVyWEI3RWoxdi9qWlhMZGhSUzY2a0NZCm11SkIxN2xlL2hGek5xcktZbHpX
            ejdGWUE4TW8rWm03Z3hPblFINnFUcDAKLS0tIG5Wc2FiTzBUdHhUNlJ5Uk1BUHB1
            eFI1anhoeUpSRjErVzdxNG11MW9MVVUKrfoOEDdL8/+oJ4dJhy6/KzEhgwXTZMgR
            kTFvbfOFSsmF68BIgdExqbrJuhKoSWvdYeG9mELvm8v1bTyFLnUHrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:22:34Z"
    mac: ENC[AES256_GCM,data:YGuJW57+J5nCbnzftVjMWmLhG3IFKKGuVoRYfD4C5xdhmDO6O+2qKwUx88hnGWi7Nt8aqEsuzpIGLyNmrjRl/n72JD1O1phlWXJAwbhwOSGfxxLYOCIYgt8rSk3M4ETZ8erqvcepSYPJ/oMtWwipxSa6CYhVmWuynGk3mUDdzSw=,iv:PAH7ihrB0azdKER0882WetDMo4qgejTjvvpC1zw8daY=,tag:1VqCsggAq1hiH8HRPWHjyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
