apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  name: monitoring
  namespace: monitoring
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    cert-manager.io/issue-temporary-certificate: 'true'
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  name: wildcard-certificate
  namespace: monitoring
spec:
  dnsNames:
    - josevictor.me
    - '*.josevictor.me'
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-issuer
  secretName: wildcard-tls
