apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    cloudflare-api-token: ENC[AES256_GCM,data:oi3CkH4MHYczLBupinYdrUpiUQxEggzhuNQ5RvakrXQ5ramqD7dtkqioU/c7LUTRrB3hQuSKDsU=,iv:LSi3IvSRgGfz/g9FW0jVbm78k5h4Ba5cROo19YKfRes=,tag:esAjqII5pPA77jWsxdTr/g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMmFHVjhadUp3ZEVBbDR3
            bkM0eGtuRFFxbzh2RjA2ZzRZUEU2TEJYUFVrCkdKeEVLT25VQytJbU43SWNVbDdl
            Q1loR0tnSWpnaFRLMmNQKzhjN1JTOEkKLS0tIDBtZlNMdEhmeFdNTkVQRUUwa1Na
            STVVMzZvYW4xdUFaaHFoS0tybHp6QmMKcYNZj9xSKHDWPfqgo7LR1s5vFDBpH7os
            y0nVo9u1wZBNhoPq9zdRqy18xBcuVIvKjNjH6BGja09F+jKTOq8KGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVVhGL0ZlcXBTZU1BVzNE
            VjVKcURNNmI2YUFZUC9qeXczb0c3YVZEb0VvCmt5RSt2M0ZSNEJPdGt5NnhLN1hZ
            Nlc4YTkxc2lNTmlEK25jYmRrR3laNlUKLS0tIG54STNzSG5mdUpJV0JJcmlrQUVq
            T3hRWHBSWFREYU1oRGVOeTBCcFFXYU0K19sbzV6HyWEOd9V4f3K1cfX9wgUlLjTR
            Y8UP+F6gcUs2y52zBiA6P4rhBNJCmLfW5YhN8IuXS2xB09WfiFtMow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOTJnOXVEUkVsbWdOWks3
            V0phYWhnWWc4N3hFdU9KclhpM1J5cDlCc21rClR3T3Q2a1VNd2hDSGlQVW90ejNF
            S1dGSDhkY3NZNVoxQW03QldRMmJIMG8KLS0tIEZvVWdwdmFYcVh5R0tKcW1LQ0lH
            VTVNMEVBUC9xdjhMcGI0R0dqL1QvUWcKM371apWps7nk0TQQAI2A0hxQUPWApfPZ
            8LPPdCRIBFOkJdTeQ6et+mfrRK+9oxs3Den0BogEE5H8m4VITiEPzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-10T19:50:45Z"
    mac: ENC[AES256_GCM,data:0kO7za1QWpR+DKQXZNQhoFYD4Yh9uipM/aVDMijOMjkXzQYNIkd5dkzKNa1uTfrSF/jhaBVU+bjiCReDyyR8WMiTwzGyAH+2TX+VBU4WRcK6NaJhvIgMk0ZpFTZZfV8EbL0J82j/hFqDNmlV1HZoYdz/jK0t3hITDIDcN8YAv78=,iv:XSrPoMYqJY16BC2JcW4jexABiUT/YgAxcdOAahUkr6M=,tag:8AeP1Mhux72ymkxvGAb9Sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
