apiVersion: v1
kind: Secret
metadata:
    name: sops-test
    namespace: kube-system
type: Opaque
data:
    message: ENC[AES256_GCM,data:X+DVd72Sow0Mb7oNPDdm,iv:r0uJTq6MhGHnFQWG87/Yyt/7n0+SlWe/ZdcsnD+sPbc=,tag:+bSqtLGDOtyogN/WO/9uvw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSmZsM29pdFBlMEJqL1JR
            aWVuck5TbFF0S3dQeTdtZkpvTXdIQ1lyV3pvCjZHcWFXdkxDMjduck9IZzd2WDN6
            QWhCZDZHVFkzeHB6S2IrNSs1c0tycmsKLS0tIE5IMTZ0OTI1S3BmTURJMVUvQUg2
            ZTZvZitRclc3RXEwUlNGV3RoQWg4eU0KbG7Te6P7YLaMUQO7lxH78ZNFUZBuDFKk
            pGKXRCIl2Gm6RKys6w7+lzWOJlTmwtXQ8nNf8FWd9QcVLoSrWa9mDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbEdPdEV1bTJTWnVBT3g0
            NlRiajJ6YnhjcUhCSnh4Y0ZLR2NXZ3JlTHgwCjc0VXlaQldFeDBrM0c3L3Q5M3hL
            eG5tS1YxUE5leTZCaVRNaTI2QlBBYmcKLS0tIFZISUhFOEEzZUM5WSswMGsyRlFT
            OFQ4N1N6dGY0NU02bjRjeSs2SXlVWGMKJFCV7JyQC/KrHZl4vLVPVR6F2qrRmHcQ
            ZGYtteB+VtEyPVHiRM186JwOzfgiceMYyvgYiDpW0HSDSAdsxZX6lg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNUFrU3oreVQyRWtlM1Vi
            TzdxT2luYWIyWTlqZTR1OWVJRTd5SStZY1VnCk50bVZ5QnByQzRkVytnY09QdFdx
            NVdaMzNNR0YyRGE5NCtNSnUzNTFYc2sKLS0tIFhLVm5vNTRlNk1qdXZHOGU4Skl6
            OTVneTV1b25iOHM4NWpNWE90WFM1T2cKhaaAHxa10uViAZv+4c9ZDUzmARY7Vh3H
            8+4X6u8tTkAHrLU4NBPo/IjxxZoRAzvHTM22mVwLOF+NMDMTbFrQ3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-09T16:34:45Z"
    mac: ENC[AES256_GCM,data:BnzmmgwaqUbvdqqRw4LCdQ9rxSgXAeby2nxGwcXi93gItWAzn2Q/Jru4lRsE/TmBWL61GdypQAPtjxawDn3tPvm5hndOA0p+d7srybqrsApQUZt7o5+aNe3wQleSnzkq3Jpyk6V4vZgCfxGRdQl/N5sLnJyThXqhS6DzXeWm/dw=,iv:HYcZbnTSZLX6XcSA+JpzSkjYEIS0XR4NWvW9u4YxDuU=,tag:G9alXxJoYCazKRWmzhMI9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
