apiVersion: v1
kind: Secret
metadata:
    name: sops-test-new
    namespace: kube-system
type: Opaque
data:
    message: ENC[AES256_GCM,data:xnR4FN29GJ52EP3f,iv:gzWiRWRYjJbXbfe3bpHp2gFaXQQhJ2Wque+bvNupZno=,tag:af+dGsWkOwEzVJEc1MC7lg==,type:str]
sops:
    age:
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VW5LZDlvbGF6ZE11a2Nh
            YTVNcStEZnd4UUlxbEE1SkgyOFVZdmlWY2lNCnJDdVJZWUxMeVZIWWg0REorbVB6
            RXc2MHJZa2tnTTBOcUJJb0l5dnpreDgKLS0tIDh2eTNCQ2dPbFdUZGxkREVyNWEz
            UUlIR2k2MkJ4UjgzTmgzSFhFNHFlNkEK1R0W6+6j/uIibU1rLZNDTY82mOIzrmqx
            PvmIw9q4A98GUG2qlziQIoJmxd0JdPSJRwri9ojUaLxQoy0y7XgLoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-09T17:06:31Z"
    mac: ENC[AES256_GCM,data:N2SNjUMJYU/ABpD2fXueYtE3KV0ZooCWwZaR9KsCC18cqUEscyMhQX3jGQ+yfQrXAF2kJoz/N1rYYKoTWY39nx8j99dCPURG/CtTF32+PUjZYzblEkNA8IgFvBY9Q1B6yMF4wLL9MsYi7TqUfLwoxEWxumiQm2kYs1SJ5F213Vg=,iv:RcIBeaNKbkGLyjurxQG+OQKRHKShzVFo7AmtNyyN6SY=,tag:ayXGlOccoMREhLMlwMD4OA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
