apiVersion: v1
data:
    message: ENC[AES256_GCM,data:0J16/NQ1pnhynfCqxIEY0A4rVBc=,iv:243vCU/qzDeFAOoEEfvxdmiPEuNMzDz2UKYeqOOglu8=,tag:yjiG6dxUthVNCtCBW3WkaQ==,type:str]
kind: Secret
metadata:
    name: test-secret
    namespace: kube-system
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZklnTGRBZHBoMmR3VXlW
            aXZGQklFWXZpRFZSRml3MjcrdFhHYWdBMTJvCkZhcWdKOGZVMzA4SUdlazZ3THhT
            V2s3UmZJS054NjhQR0dnZ2ZlemtQZmsKLS0tICtoWjhNRVZnM0VOcHcrOE9URTlr
            dWl2elBpOHpJcFk2QnhNMzBMZDJaK00KOSrd42qDrjSz+PRnAHMCUre5aZZ3Y75i
            bIUkfKTSWeU+Qrgsm1mJaez/e3feu0mrPkNFdrAc+SiZzCoN18wIQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSUlxWU9COFZvNzJScXp6
            R3lMM3VMOWdmV0lSRzhOd0VhMnhJYnloNmowCnNRREViSUZldFZzM2hiT2V5SGd0
            cE15TXJTUytXdkltenFLYkNqd1Z6TGsKLS0tIHJRTVFDUENSOU9TeURZUTIxM3VN
            ZXlKbnJOUWZ5WEVHTUxJQlpCTExmVHMKy7gWlvYz6xpsFsElh6W1n/wklU7JXxoa
            SFdrRfoK1iPK/iXFwzNnxLTx/IsKLfio0OAyLubXOgvMBnQXcQ1zNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJY1pWNWM4SXZmZHJQaDV4
            NGRiYUxvaGgvaVBPT2h5UlJia2loQU5JbndRCk9XSW9wZnplTnJxVGtRa21PWGk3
            Q01hTHJ4YjlZZnlCTFpRdHFlbkptencKLS0tIFd0TWtXb0JMbytWMzNmc2RWVWli
            aGU3eUZwSUtWM3A2dithU3pEZWhicWsKzhEh3Kd9lEtA5Jcc4zgnbeppaeUqq2YA
            RfascX9MtiyKPoL5AOjlZNbObj3Tk3QaM0VvzIwSsxKGPw/lEArf3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-09T18:26:05Z"
    mac: ENC[AES256_GCM,data:SRQUBPiyea82Nws3NAd5RIetOaudO4CXG5DAouifddXf/ytR2PHA4dmD/emy2mAlgTd8OI40dFRkjA+D6fDCUi/bkf4Grp2WqMKAhy5F7Acvjx2MwyX/wEN39qNMTNBtK3CFnWhvRNbsR+SoH/goAFCQ52E+oF+/GnLJQGJK4bk=,iv:cbmMpxzP8DzpQzOF8DJfOpYCUM/PfKRQMtEMqzrKvFc=,tag:LiVoOgeDTDrQXDj2lRU3/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
