apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:4euqsuuHMtrBulpgmWmj96msHH/GZkMEYlS59o9tCWKKYaeZf5JA8mWc9RauTgUEV294zJSB521cwnxKwymRk88GKeKqj8+3pj4QPHcRbTkFsI70d/g4/9n0lpxbnPGcZR2PB8i+Weo16/DYgH7qo8ry26yyN4s4Qj1dldZZUgPh/1oWMkunxywM50HBslYcHTGXha5KYckkNYWYY2Lk3Zp7aLcVBX1a2fWB1a9NgEuFXOfMhmvRnqpQ1fOQAw588Hd14MRHvv9UJCcHkdqB0tGCUt4G2aNipIUWEBfFjUSLFmYBRehMMIfweQbn9VKxM2OUts39uJBiev2akqs+/pF8a0NpIZ7/1Kia/4ONqzL6saaZQGnIdsA2PmKl4IEqBkAHK/7wAS/P5sZsoRRbrFiBtnehTnXpmmK43eEVYqgCwrtZRsBPn0uGC8rLw8xyVd3LVq/X1bgnUpH13VJvsH950zh2AXO41uygwXgc7fQjWKB/ef9KSYUpzgWEtUOwVn33OOaLEMqnXLd9cQxKiau+/N/+jfT1sLlPFaNX0uMTM2lJXWcC/Cw7i+whB7I9J/J6EWq6T60+dy7x+ZrevuWGzXOIT/pbqp3fFR7FnKvtU2sdUSwHsBuBc8vh0j3Cl9BuZSuTk5q2zbAOpe2QCmBYjj85VtK2iHzt5I9b0l9xgMyWWARJnVflEzaApDuSeJL+V8SG1QHcKTvTr+/4wTnrZfBMjYJ8SdQzQ4SU+5xUfAwk4lToB8PtgkooTYVJNVVlL6UIHc/uopO/K8T8YAe8QbmpSU1cqUWKL7/FTiTqmHXfNPrFJqm5Tl1cNJ9pYJ8hMwQpb5L2gMnIQR+QqeDH1Cmg9k8bt//m3NiOfB1N1t6c2YPjUtNgcIc5KfINmPKe1TQVhBMNWO6FD6PZr7rekEM3VJiig29Pm1tA48bIgwjxDyU+hEwpSxPJH3L3IOn62SH6QeRMsGb/UBADXlx9OppF9fUZwc8UEpuF5oxT79YIXRfb6LuAJvhXD3T3cViSuuBez+uf7W8QW8Yw/6c/xyY1LvbzixOqtlgQBLuwqcheLxQjo+Xf5SFxo55b/VghBXWlS8+7FUWVZ5KB8rceOur3pe4OTz7KmZYWT1LF90Ga9mb4i5QZw1oSWMtuQyG4aBGj6qjTH5JRYDMN0AyLXi+KVJ1u742do84/Eqtu1ELkPVlguBUwQF6XY2xrbX4z2uqwWuUF3gI0F8UtwuLVWyeic9vdt1c/+BUDfTi0WNVz2I08pzBdu3JpkZSXnuExl5+3LalqhFxCPLG3D9KcCRB1Cs3Ube4zESvjGP0KtdVaERP0+KvVc7/56XK0S/xoGcXu+4zsh9umtrC5f0DlV5rkdGD8YvlrjnRGz9ZppdJuEVoE2DK14MjFveEiZMm2PETrZ4eCWR16MUFfW3lzKScwwWXczhgOlElZLOJyRfdYKgKTRD54eD6DgnqsW3Nk5I7p+mMotkxlaoX4pgdtFRXuzZnh3SfqpAFRhJQU7445nWtqtCAoTOtkVFEzx5Exh6ye35Qf9l+OR2ZyqdJlIrpfHiMr3gkS7AObdoSu1qAOuaO4QkZi49amxIhGPGAEEswFaD6JHIAHs+ZtVIbdTWOnES67ZEX8xNrq/Howxn9nU4N1C/+H0DYxNSfMM4Kp8Y0T7VV29Fdbz4nDlpGSKcGuZFXRFSDJqkC9XgliWxah1e4ReyOIttSSqb04OLGTuohpUF1OJ1D/GcZgI39ITj7DcqO15nRFcbRBVa7esKYtywBeMHYK4822AHaHQ3yIpmCEPLUnzyl4AwEexmE+/RTeN1onsYs903/Ym+syB69tM7xsuKV0YFxHcMsmPioW2e+jQSjzUvemSUUCr3Y69YbUpc4Ea6VIzxhivJGkktx3N9O0fIR2K6Mfm047DGiTaPe7u7d54ZJ1ccU0KQhFrG03jpMqvsjh7priQ5TIES4DP4jCZTEW3zQvrVRtYzQZEdNA+0mnETWD0hw0tjtRtzba02G4PI3EImaoLuSMfzoQf57oe6+FxDCCu1d2rpnewOwH/hpDyGI13w/Wyg7pc3TpbR5ygr2sszw+pu+grwbYg6jlhR1BznZjwNNiwKFW55qDi1D92aB7mV2U48yY3vAI/QQHlJ617x6V+UDtI68r1uNLqC5t/xkkLrzqFH30k28d35wFHIBbMiyY1yC6KYYU6eAOUXfa4Dgew8F3qg0cGC7zMsUzs2vBltOux4xkd2kvJDTxBwUGeUi0/hP8mrqg0omQ9Xdjgfn1sW1Yl9s3odASMPGmduAOJW4k86ltTtRQ9XJstsAleBWeUm2B2KTrCya88qvO6Vdml8I3QCO4sM++4xh+Nr6qFH6c+bzkUtc6c8T1/MXEel7rzJ/Nl/1DB+PwEz5N6MmGQQKFMwPhUMTx9agZXIfukneKq8nNaQ39Q89mn1fGJRY3te7P0IUS66g/q7g79pg9AEvtL3SmTJYcaiwYEXIk7Z3QuDv6UrdCOPvV/EgSX74i1OPXO86Z2376vO301xlwGzQWOiL5QiwCl286yKi6e0exdXFt6N7UyxAB8oY+Fcl81ncBsIhDamsLO4fvpZS3sNaPSohvGUX3zHhjIJTqvaVXZvAYS/bMnEnSmgUAOenW2QN7G6WhSpx52bIAf/u5Mi3q79kyIbIlvIgPdJWC70VXKr8PMj8yVcAcnLulnRBqtOfeMvtawDuzB8XJA4vx8Phebv7J8qVSig0Res6Yof7lQA/ho9+mG5iTwB1YQOIhFrTqI472zHPa+nDTK/Q=,iv:fjcI3g+OBvt/sOCjvjRXsih1L3DLOGxe1BxuJLB1g1E=,tag:WBlsQC9Ouf0agxU7mWiF4g==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSndlSTdQWWozelJNV3Q3
            aUxaY2VVQzVxM1Rwb29QUHpES25oNk55aUZ3Cm9lNjNGUVM5SGNJUURxcGFXT3Vj
            NnJOc3pxYjVkZVRZVmIwMUxSYkF4eWMKLS0tIG9zeXZnRjU3ZEt1YlNZSzlWa1lN
            V3JYSnhvNVlZUnNQOUtBbEV6SGJsZkkKM2uVq5GBeqzEC4ThTg8oU8SiWyMlEniC
            vglrlf1LB2JGDmqK+WElNaUk6i7akjRc2IaZgp9TmHLL55CHIsvH7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VmlKYitGRDJKKzVaME5F
            SHRodkpGOThRcVBkK01Pb3pVaTdlSUtWcmprCmxTaXpUMUtHbkJqRzRKSlFBRnRF
            dEM4MUlqUXh1bHJ5K05lWVFPTTVJTDgKLS0tIFBabXNOcHNEZXpPM1czMlFkalFW
            ZkhCSEFQRC9uU0Y4UUxFbWl5SWRHWkkKSbcoxy0nNjhrABTJ57nWfQSpEYoQk/cY
            h9znlresgeHF6v+IZWotlXgzpwU89+F8j6JlQ6DqxFZEUt32gFxrAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYjRGdzU1OFlJMmNjYU1W
            aVFuWVBQWFlqSEdlaTQ3NFNOeG1EaHdpRVFNCkpXZWZxUkhYc0p4VlNwZ2p6VGZa
            RlJWcmFxYUZBdkhjZ0d1aHJyRkxVenMKLS0tIHU2TjA2SFFvZnRLT0NTeVVjazRY
            WHI2dURJUThNY1FlQWtNcGVndVRhWXcKzziqFDftZrzD6IZOwXni4LjDu7dCzRnN
            Rzc3YqigCb9xYJ39lQymSUQBq72XbSr4WOUfGGGRk+Qk+rDk+hNxyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T23:36:58Z"
    mac: ENC[AES256_GCM,data:Zy9oHFIF+BAfboc0ddqHfy7pZs5B1txflMwboN8FCGV8VvlFcy6BkblicUTSwc3TImGV+urRZ4IraNGLoF0kc0oKNPFrdVipKZDScnSyp5o8Z7FVTLenogKx9HnJVpVtMMWiWtfEgWkI3OJEwaHzHNhQ6xRLvJWz0Romo+pOFR4=,iv:+WXfNAIS7M9Dd7Jm04+AJFZkhVA0HjWJztg51ukrgs8=,tag:hZEpYXoy8pZevOykP70/5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
