apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:+pHD/NctteOhIBcLvJ2hbtgO81QbCzZTJTE51uPZpSSRa8Bdf0bJVIYCrWlY64gAt8m8D3vCLn81ug5JXWROvrKu1zATkjBw7mWst4HnGUInUvv/FgsaAEbTeM6PHZs6CWO9N8YgcMR9CjZ4830I2prmdrYp8kUZTbOUQVj6osjP5CeJE/A+BOv+eqFMEuHJI1ymqtQQdc0jXwWfAFQ9voIFy9qDsAPCg08yScZ/50OkKSyYpvIZFRoRPcU3v+zu/gQCfHq7uKg3HyvHiWBuMaBAzQSc+/0mXVG/exBDVIILmPatICi//qv/GrhWukCfRQsM77nPh4y9rvzWvVttXjeuOxxaKtltSgK3JCimARE0yYKexwp6zsHuV1fa29PJubrNbxz0RZS1oBAni7zWy6K57IQT4wBIr0nx0nWd+BBcZJ/IOj9VzuT3Vov0zLZFZqIqEAWIfKWZtBvGYncHHvW7jEfPb6wF5vYKlyg9FuHNzum46v/8Nyv26ZoUA0gVnF2NlTrJ1MeibYbSjNyTBfIRuqCqOybTLINzl9QZ51F6/5y4rUTgheBusjdisYZ2hSUiefPKPQTatxD8+1mah5sFf9v9I+3tD3iA+YyHsJQpdOEY8i/fvFOF2kD732hZLfZcNP5xKEue6EkyRmGt0v3iifY7gI+bXFi2EISd3o0ld86xI+0e+v2KEusrKbpLqddkdFBweGTgnT96XhS334rNgiSONJlAMOO6qQf350sS1IrD9aRNFN34QnYkBBeAsu2muJeT4SyUnNSgju+SVC0X0ntgfa3dgLJ1sB1yBvRbNAz/l1CwcF5I8w5VINsd/vhZ1EBVgatF8d04etHp4XHnutxaQnoh3bxmdoI2mQmQ+ddNIZTWdjVOX/92yyq4tQb7fPivWUoR3mxWTktdexcci0Y06eEXyZrd/xG4ZEdZXGxKg/HsFjrd423qPaJMq4eiBDf0eyzBiFrF4dI+za8mq+T2Mu9H5nt08nnIlsRvfYXLHwNujIZOfrnvCXIC+p2QqpTBFYzzaqX8j4IZAOqWMECHg4VxcO14RhHcdV2MVKLNCrp+vfgTY/NoirPbunHPy1cY7H549524Oqt7fQ7x5u0GzRiQ86XlbFFX4+yh9D6oATbdCpqyNFugU5VFeEjUV0dBkiR0fYf/nVwy7t45+W60G7lnO9p/xpVNpYPdbI1smybs4AJNN5A3SnQzN+7CIcBrqZrWSDTbz7m4UX+ZViTBNEXJ7brzUmgyE3Tk2t/tgkd03QMz8mKJy6wwZSeKUD85fmd6Toi0pGX1JpEZXtgVTHabaIhJCA2rDn8nU9niIZKXRUhVnvDgjtPVMLOHCzPF7x523h/uwHG+938+5s/JyU6l5X669HkDMd7Rqh6Ewxe2y8WHmKfX9faiYHS8N6x5TQ3hz0rVsZBF5IARjnFpqJiQOPu6D1RCJgy7pMvs5pfMle3W7shzhNyoF8gaNP3LSgygRgbS00BfZ5BL6h53cg0vrvUErWVaFAS06tSrwOrJhG49iYoiyT5oP/LoZNk5xNWxo6t9Xeocr451lwdJBI3lJh/BZ1GkM/+mbBqepN0d+DXBZfhd31xpsqKEg2ShcWV/we1UZ5kc0TvG1yhp7RfAuVXCopFMvPuU5dQmVKdahQlUxkHs1f0peZ3cD29z39ueIxR4FooT0kA5mLG3OfR0agnd8MTCMM0mJj/fvifXti4CAuvvb9FjGU1FU+v5uJNkdzJuQ+lzeRaeghEobW3usjuHLh92cED+YE1N8PuHn4J/n3xQO5cwayDVEjBfuA6zifOQNaTTBRiwszteu9YyPm4QQjRk2+7RHiVx1PuskR+8W+3b4DvN+PA8E2EiMWDj1wModzO7CLNs/h4j9kAv6cgNaRHP0no0L4Aak+oRgdPEkLvBW+1zgVpaYgZRP+oxhGM1gkfy35tY/2oi7XcRDFVCUGPwQwRPLwwT8vLD95DwfSKZj9SnBPtU6dsrDlmOUI9jNdgpVGylSBRh3bmpa6UZYfqhdzyzw+Yz2/ozX4olRhLochSf73wa7uMQPSrKYE8NrCmBlZyHW1tCaAMZrIQ0xt1lCLpG/Yg7GjGyiP5KPSIzn8oE/NF3kmHiE7eEp/v/yJvjwLHxgBF2/NA2ZaIPfq4X5BKwDvex15eHMmWTK706z5dSRW66tva/OxnX/ZbeceYbJbCMp1gUSgGoubOLWv/qzLPF+pf85jtOTbguueDbSVD8Q6/0UOHP5qyurYccUYnX8vrAGY1irvSljVgK/OQwKiFRm5sWyqK7cOtI2QZthnIWaYpmg14PhMYxh67AcY0pKHk5Ian8XdrhSMQvn4QHZh/IfIrcRqY4qKZ5PMRxIwm1Kx+RX48kScgfG9M5KjzjfRi9ZT4Br9tE7TSmtahIWSgiDbXJtsnk75cmITOZ3zhRBdIAxJiGcyhEqIpUN7yxklsDwlrcyeVdtxmkapdtsfLIYV4z3RJZgSRW3AUMXNGTUrJgfs7383rbT3Q5Q08kpOovnseIx/b9GBkdH9JqEFkj3ofN+HWesiu6+w/jbAwTTCiQ7Qs9mmpaflNRoDWKmqARWQoCRqgJtyVT3ADoW6tq0i/SYlBtDuHXa39TDI3ClevQfrzWhEt35uFccUH57tPQscUsIErgD1Muuv3cRhycjlYYiK1D8mTt/X+6YYyWHB0DlNxPiPHG4aPZ8xZg3J27WTYl20qx1hRFJ3tLFRIZ0STZdnbzKQTQ6X8dQuPX+6CstQYJR/VKDYSmc/p+JMoct3AapjtushBsMA8+zeAZQXE+1PmBTxDOvwmv2cXgNJ+TtAcxRDdK6I5o2hrYuQ8=,iv:ljt8RF2CLZZGMrGMmLdWU7rw/rMRZ9sTcooJRI0SrJ0=,tag:55O81yqzobRvyDWC1iSLjQ==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4THp2WE9WUzZjdzZUUElY
            SXRZR3ZWVktQQ1Jubmd0VG1DZzU0RVJQTHdBClI1OEpuN3FxdmsxendzdExKR0JJ
            S2tyU3EyQzMyb3VDU005WHJKeXZEeDQKLS0tIGFEUmIvakFPcW45S1RyUVF4ZDRX
            cmZwcFpkQXA1TG9XbVdHYUI0dHl3MmsKBuYFxXfcjzcCZD1i+vrHbhfX8tQpF/NA
            q9S9iFy/xNI+si4JHg9FEg+n4oiWdm64YYnhmMZ+Oie0ATrDmJL5Ag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYW10ZURpajJTTVRUdVdr
            NHQ3Q1JDbWc4eHhkNTRmN1hzT25zZ3NiNkE0CkphZjBjZnoyYnEwT0FydmU3UFQ0
            ZTJ1REllUllIVmptL04vREt5RU83K28KLS0tIHBWR1ZlKzFob1FpL3FZOXFuZXpY
            NXh2eXRTZEpEUVdWUGlZaG5aS1ZLQ0UKxn5ulK1NNxbn7Gv9wHrz80JX8VmeHrVY
            Wqaq03to1twPnHrwsgD7aVgiaUBmk1buftDE5x3AFLEdpNIS/rQWag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSFU2QlFBenBRZjV3b2lH
            MUlGdXZzUnkxek10N3FCeHBRN3RHV2RlQ0ZBCmJJVkxGcFRvblFFRnR3ZjlNc0w2
            UkxqQ3V6WjRsYlBkUU55b21wV1A3WGMKLS0tIDRSTFNLV3lvTWR0RUg1SVQzSHVS
            US8wRW1uK0ZXeTlQVXVhVXd4UXBRN2cK6oZ1i48sQkW/Tn651hLE+8KQsJle5Bgi
            RI/DiwqaXxL6T8uWdq1fZyMx+1cJehNf+Nm4atvlPbvf+Qv2M/p5qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T14:50:17Z"
    mac: ENC[AES256_GCM,data:zdhJp+4OZsAWFtSw1JrePAWqMUlofsmvsBLbD+wOJtBe/6PkQXzuMwjXc+kZvVPXk/bATNiRiPp8ftRYkPT41sukQLRWu/1SwmGdnT2gqsAQJQK383PS7odbTDdx2lBZlU4D99Po6ivpNxLSJYNoE3CfEJiT/FPd6SdhGJmj95g=,iv:5OKU6evYvFLr0xw0VAunhegV6UqeKFgJe1rTHeOmYj4=,tag:jGxZWiFNDLxsA+vXbjHj6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
