apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:mvN1Tup7Vq6sl8Q/w+EnmabdC93BPp4Ed+SJ/RBLQKOi8Qup8pGASlUv19rWPTIbE/ozpQXYGHiG9O4fUA7SNbRqCEb3lU5vmuy2DpAHubmJsF9UKCEeau/hc+tWc81tTUccQicD3PFkFOP11TjB6l9vDxRVA7PRKAXSLc3ofvBRAhix4lEqMQEs/N0bz3FyelNpx9gt2iVKAIKxdl9Y6oQhxgsj4KHRmwlm94q04PhItSDmiAYFnhcvnPaqTXufbr/NSxR9zkNY+31ezT7AwDyF+7LaBGD5FbloEHOl28S/e/RTbCOE9IHXBUrLnD4TvoXjLfj8xsiy+VbfdAPf9SR8htp1yUY5AHOVNlR37O59tlFYctDf0/TcLG3MBYMgAHS7O9SMXzUgxRdimfGhiheoBegXyLnOQSS7JVFhTy8F79zHRhjgF0AdmDTjazAq1ZlXAAgF76M3xVehzMgcuXvm/t4z69Uk9Jb1EEWRtwlXqfAKGP48L7+COJisVqoCP7q/smsE7AGXVX3FdHT7VCZil1H9jKgns24R48WgkaozlLe5Jbxx7WCgLHJpahGozha0wqU8NtGo/3qLeEMA45OMrFmizEMsTlUykj315dvJQSq93zBMpR0LYncXTuH7xCPTCddmrXcBiLyGOXXnDhIzGXQ1aQUfi5sxhYllI0db6nZ0u8C9JEbJXcsn6xyS4FNeWlJKw/AOKuMnCJs8VwleUmpCMX0dCHs/t4eyW0fgov1xDwWjrr6lN9JS0IyV/SMqdtInu5M5N4WxB4Ui/iSbvHHwhyw+fG+C6zlAE4RgGnf3Bqb1OUsBHIap4pqyVWe6cWxBJ7FR1IRMIY8igekok8P53nmPpOoKqzSLu5Mcj2j8MKIIooKVX91KEW28JZdv6Ga4bxS8WjgVswpGRTH9tROtDq8j2eGpe7XdEZ3eFuawnAqqbKE3a40IMwLP/uNW18Lwjw0Rdj2+Bdc0vS/04rK/EfX+D14rECAzMushSG3klKsmv+PBg7o9aHqMoyu9CtyzU1T6zRY+ExrJK5e+EeOTj4RdnFL93Q11W2zadaC4KT8dtMwhCoX7TNFoZRzmf0wNh8Ylk1MeVLOSQpaI5NzcczSA4ae10DOfGBeYmBQx/eMvv2XiSpGZvLx47ow0QowsU+DoahcxSskCC5RMX1HzHUSGErYrwikikf+BYa/qwMo1oT2ZQTk0cps+YscgvHp2CC7yhWa4iMmY7HPJ7KW1G+pAY/BZhGKX2qsU+cPX7Uj8oGjFuqrqacMLGRtxVZN5AXPvLUEL2G6tjGeK+MZVQ8X41SxjMTodNBEomDn6LaaE/s46j+2/KaMYDRFmD9SpIxQbIk+6Fq/a0WXCWScEBI9rBXCFfrqkoJ+BtbrOQPG5y900TmKLVSiluG2X7p1x+c48GvOinCUEBolJQnMAG2ahOGvADtdze0PCSPWFquSFLwsNXTLpqgQoyJz4rpZPMDLhDoPIijHbMktHGhtyP6XCLo59pGFfDH5M2j4H5aiErPJXBiZAU6s6MB+1ki+H3/tlB7vPSIcKTOj08ji44W7r4D1m/qB5MZmm83lo5EZK+WjXHPzRTcPxTAMKmowiqQrYvL37ljVh3OynBSAK8rIYjqolNwNH0Y1MBs40Ii1o6Ud9MMJrA2tPFPrXAIdbCnco/eA8k3118OYqZzRx+uv6DqJhKfR8Wl1/SOQW+Nse8XV3qqEiytZ2sEAyijwqT+hmRtil9SpKhtyejECKK6I/Xdm3VnS/LEL/Cb+vcjXmCwILmdhc8OozmJ6A42qmDIjvVuUtJfElDxfkWqc5NCKIvPx1VypESwgGa+AQMb3Qzcu+HI/Yi7u3twn8oeNQJoIt2K5wZYXa0gp8qGy+fKtBeaBCowju7fUHihfAxjzPsr9Z85J9Hd1IMy/yXI9NFbYCgzvthjstJIPbP1DqaIUcXkkSiVPg0eXZO1bS7ugtj+TNMyScj6kgKA8PiM6Lxh1E1i4l9SeEV8cdhX52WhAltSYLnRf8SR49a4HBSn+uT48FkddrVcBhyZ5vCUSnYbNaEsOu1ENGCuRorH/XmMMMzZukaRfTc4eyIF6J7dWi2mX2zFMk5PZ+V9p1PwkXhEQLldQ1fURP/NKhIenRy8W9mH8wAyFZbpYVshau9Q7G78Mywhu31LH4mjcb8nyDbPn6zHo3eVG2GufIeFE87jSfpwdUpqL/t/Z/shH7+2PA97dYjRpPKBGseS2Zw+UrzXhhXvWPnTjLq30P4FcZck1ZB3oY31cLViMlFhAVkU4jIesWTdUE3nFwYQiOz4Dne4+FAVS+viBPjy5vtKXlWYr9sf+D0tjbWVtU+G0NQCasWRp01j/jB2EVri46NCZ734jUoioOIXj2OFJNcIDkxU18vrFmf4DKpx+F/+fgsGdcpB2j5CD8M7qFxZBRTfOuzP9/ae/YVO4Humk2m9mpABy7Nk6pqmKY5FIIj7byNdeWg/aQnrPANICKblQN/QL4tGs0Rhz4TCfAgRjKFuHmeijy8Q1rTy5jllMeK7Yg6KIn4aQK1kFcKMelypI4llT0fGCjEEmM4NPYVZUjpabSysLanb+g3305H8AIOQj0MypECFAdMXcSdtudCOTzeu3bjoNuz2FOzyTXL/2pEOH7zA/NRwb7Rf/tVF+3p7L1mMEiwR2BEDhT7UGRbqYIlhj1AINYyA+9YXVHlrjBx/XUb20BRLaAQjT+K6G8vsgk,iv:YDfSOrUkOgPYj+LJGBAUWzZYEY96Nqzux8HIOuRyqs0=,tag:IM7XbNuMHbNMBe+Pp/l/Bw==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcTVWU09NdkJGait6WGVi
            ek5JZEVRcUt3NDFQUnhkZ0RieTdPd3M5YUNJCmE2NzNqUFFCRXYwazVIOGVLTzVX
            MGZPY1pReUd1ZzkxQUVwZzZPVEtrbVEKLS0tIHo0dUY5TFhtWWtiQmdGaTluZHlG
            YUFZYVh0azBWNDR4WCtndXZIQTdhRGsKwGLcxDY1BNRRRdqA8sbwKM/iUHEsS4FD
            RFLOlLOQquR2TpoYNVGwDGYIKWACtDtGO5Oh/oBX3JMSo1yQ/eA9+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3amJOaWZTaVVHcThIMVJo
            U2d4VkhacngyMFR6V0FDSEVWNWJvZzVLTVZrCjJBWnI4d2x3V3dpVUJmSTA1WHZ0
            R0UvbGxLWDBrUjY2NzIyZUVzbVYvWDAKLS0tIGh5elNDS21BaGlOOEdIa3RqOVVU
            d04veHQ5NUR2WmlKWTVXNWdnQXBJQjgKbzjN89g0NugH8x0kwYiz+uxfoOlm39hp
            ZV10o3Q+e0xPWMGtdj8VgV0+j5JGrG3LNSfPQBmgSouJDdCEd+cxzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkU1o1K1ZRYm55Zkp1cHJ6
            bno4cUdSakszUWYvN1ozcm9MNmY4L3ZQTGdBCkxVTFc1SHZ2ei9BVUZHZ2dFSkJ3
            MVcvQTNxMGRiWGovUHhPUTd2R3laYUUKLS0tIDFOL0dGSHNYUWlnNzJKL0pSVmVl
            ZkV6UU0yWDh3Ny9kQktTM3hMb09QcFUKU5rmT1/2nd76/XDrD3DwwYECIY8b5Rst
            ue2bRokNz/52OS2A7XxkwJkFjA8O/boseGW6Yielu7WsZ12wxhlJ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T14:51:54Z"
    mac: ENC[AES256_GCM,data:pywqIGNx/zNbVtJ2xiLh2izg7noZLLYe2HSgq+DA7V9lkjme+TIEnyrbBq/eFJJELR+LaFxpdkoQUodQ2OmBIyti5O9/BEUkFrmber+9O9tezgMvqghMw2EleIOxOLUEfR5x+mER9QGJDqs011BV7Wo7KkodUoH8xcLIi5C9yp4=,iv:BMABMEthDk2hInJG+rkPtbeoy+JZYHMHWm91rqX1xGE=,tag:S2ts9JlVlxU3uyWn5//X7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
