apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:z3xtjo/QU5GsLAkUQQ6tPJjIrQ9uaPaJFRGNyMlImWRiBLbHcObz/O4g+OxmucUjTc2nsYWFE/LsntAIa7lDtWMnI4q83z3Cap+grLd82KuZeY1SWmgMU80kqYkqOg5ktVaTyqO/n4rVvsc/HjlLjnEC12Z2dPNN/NBM5U+RSagF5dJAagpP3GmdMXlB7EJxMO+r1bpeEtfycIKQbOkDuMtINZuCOEaU+ygK1KxC8F9IMeyu3PxYVS/HXvb8gdm/NR4dJT3rwjlLneLA2X6L7AfVT78pjeTaNCN0htse15ujr9Ggsmyf5xcXLssc8OwL2NJGMDlb7HhDveq7C8VD6YUdGaDYrlUsltsftOvQkB4l6aRX4zvL481Mwii965tWQl6vqS8kJ7sQ4xU9yFLBqONNitbb4O71dNwMpKxtAnYmOXbzAJdZfepUrmUaqvS2QP/XYEk8tp4mGexEPEAHpoccxYzMaow5j01saQYPhnYbnWwviPaY1R9WtW2r9kuLu3UwMymnIIZcpobLIht96fBfk9ZJ7ojjzzPh7T7TMaXMvFBj9oVBlo3l0iPg/H7OzobixncKqXfkuQr814w3n2vIw8vK+432Lt0sR3KD8Oo7v4RsHZH0vtT9wuYitlzpXPdXtA9YlChEWFQ6w6n7mv4gvIWFG/kc2tSoVejtAx0NmaJEQwO8+VbpVN9HyK9rWjaD+A2Tw70WsmOECROX/LAmKyecelPrPLc77knFWh8dR4EpOlaKxoujvZO3YdeICO/V4tCEsVQpJ7VnAhacVjOrvlx3Sv5u/9+SIllY6l6V7vQpTbTxVPSq0rMRoiz0rUdmPca2vSyewotfzWMpnLLowGPtK2RK121afHVFIx1T7MgtPkyDHOPnuXj5ACDynOw8OWVA7ExoccilFrcxGbOnrs7nEI0BB6NsZEuxgFcj//h8Cm1pXNPUrT1KIV11re+cimV0NWQ2eq5T+UBYO5WzKRqIXwNEfoWQTyeUYyn6i67wInv1kOUDZUlRCOn+DtMPvnqTP/o9f77I7amtXuUwWl9nTKtdg3ULs+0njwoigJQwep/TlWE+gt9fBCztbSCxK2h7m0wPQfu898LhH2n7b8iJmWG1f/kl9RW89wz4aGK2/gh5F6Ew+C5Q7McRrVKZ2SPg6WLkkT20ppYRbTR+vuN5gxVz6ZqbVsdIDbHI1j+HiZUCJ2sNp1v1xpMkJvwUBalpuFFkxbAyGCV7lPcJGoKnGrIxh7k4drtwRxHAAbHR6olrunHPpLjKJUveHf3CHi8JmcQBn7PFttaW3QEsHn+FhxKEnCkDoO6bjmwasWu8Lt1VpK8Ke3i9L+UI1JbvidOdByccah2O7/S3pd2WQa0xs8lb6G2klQfcSkPzTVC+7V/DsSaciwJiFtpT900xiOJ2LuRYPi72cJO7N+TRY7hhJbf739kNy2FAXaWbUBNRVOO5EWJnE3/rL/oEe/XedIDXJRYOELCe5GSCnTasI7HbtuRWAGX/dliHDbu781ySUuHkLvAoWihuNbW61mz/zkoWPPp9QfKi9MvZx8CRZWHJkaonNqhka/qwvDPe7geeU0HzLwwB+zSRAzLoAP99xGy3qX/qOnfscBiMp2qDanhgIS5v4si0UADMxqLX3KsxTrGqkZm3MlaMe28VdSexXJXfyoqwiQnZdX4tb48wnzxV4zrGfprYKjNd8X46l/RmVUlrePj0+ucL/N261MeKbnOpLXXIIZ8UiAHhdzJpKafzqm2UTjRwXbBSbvCLzLZo+vAIjULGfiHiESU8xaZVNHFy0brhb2TO4VxlS7iVPurKdOJFRsmvOsOTH7zt5XJ6o1gEyiWbAyBguihXnsDyjzFlmcAx7eJSS0HVWxaLk2CHAZ2C4ktxE3K73E+w0NulyrNDGfIBHmLg54+6xNrPd2VScr7A4McFEWqh3/C558NK6bWq4ulcH8bswDKqzH/sc5asb2/2QWkmoit3W1PCN8Ppz864Wp4NQmXmdjJlnFRrS/Hm1TGTz0Zp88gsxC5hDbELnsOF+d5H2DZUZtlv+3EptkcuN1ut97rV4U4Iwf2mlIGbpQ580oKe3m60ckW7puyyEK7BvuwEETDIq/FH7YZyljl/pcxuL20xQQElYVYqIpwZkfD9Ekgrql0IrtVcfnn6jbYIo+JmnJQV+u85feaNjVd0JLfxSp/eVX9EQZZwB/SeVbfV/LkCxZFRll2PZoUqJ/Wh7WxG7x82zABlrc7cjrzcciRdsHd0X1nWtJ8UKBjUEVem0/OpJzqVpOQIsboyN56FXGfxg3gmMWhz6bz3X9Mdk2YpQkldXTJLFDcTYHU3Cx9JMz8Zv4ULiyttGerfKyGtKTESo4u/ww3jl/Txb6eiRTJZSIxspidM0LutUlZ3TkjF2Fe587/lSx8balgoGkxwmSdySI6Zue7pkLIAyKNyco3KLBwOTtilDhIVOvdeU8yAOr79Y84kDeTdisDPwdPVjDFc2Ttdyik+F6g3EB8iBye6/QZjzpsNq9TgbUJOr5it7VsJHkUa6KJ9TgIS9A+JOQzaEjQ7HVNVn5UBotEpiAZZZiVHeIy48lpw8/XD0x7TB/VvnE1+0YBJa07SLKHo0H+Ej/J0cmaOscEJRA1Zm92hnTOuDTrvsDqvExvfsGy438S29FPZzNCpzgnZeYggkOFHaHyc95IlFO3ylRqY/okqrwBvLDsEGLCzU+siGVBEl+B1DoFFFfT/pLF+BUTU4v52,iv:iQII42oQSEHFJpkK+mcYX4rxlnRAt/EfKBm79zWP4+s=,tag:maTSdSZhgMYvCsDCc1b8mA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMHlaQzlHL3BPU3ZjRzQ2
            YldQVUR5QUNDMUsvNnUzM3hrZUl2cDlzbUQwCk9PSUdXcDFTa1BnS1hSeWRBYjBS
            dDFERUlGVFhHbjVkcXBJMWF5S0JGQ00KLS0tIDN6RFNUUnJHVWdOL3d4U2Z4dlhW
            OEZ6S25TYVQ2blBINHg3dm9YdWVQemMKjqCb8KJRfgAjeIoqd3IIxkvY78dxhYxK
            7itpk3mws8hblUapVP4xmfchboo8ngGYQA+/IcxXIO7B6ipnRM78GQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTnVNdGZ4Q0sya2VvL3J3
            QVVHRmFMblQwTlhOa2lCZ0dXUjdEVXUvTVFFClEyYkJHZE5JclRJTGI2cVpmZStj
            cHdmRUdmZjdXeGRKWnV3QVFxWitaS28KLS0tIGhNanRISHVLcGRuaTJqMDRYbk00
            cVFTN3VCZHBEY0ZJTXR4WUNnZHVxTnMKSoAU+dMNP0xqqyYnKFLpJT6n661dX0wT
            scyTObOtqwsKnT6P3bvyC63M+R4Jc7KP4B2b8vrX7+y2F9qjtvaA9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUXE4TWw5Y3pRL0ZJRGZp
            WlBZKytvTkpEMkl0bnR2ZnN1L0M4eXRZVWo0CkRPUFNUNXV3R2wzbDdSTlZMY0wz
            ZW5QOStLYmxPbUlOd0FmZkliczZyancKLS0tIFlXUnhsWWNXVFUvcXh6R3cxU0ZN
            WTd3MDFsNm5LY0Erd0lYOS96dlUzc2MKa1rAy7pQSIY0v8OpgDaKPvZbyp5X7bae
            0hK3XI+AEr+1WgzhvSCpmURCP+olx1QRIVnUEnkQduybMt8VGZKkHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T15:00:07Z"
    mac: ENC[AES256_GCM,data:XYY2gD1sZxqrvoBZAyqpxyuPNCyZuoR/Z2yZl1dL+OFIMrCYXm/X6iH4xrMFSWnWfmNafMKyZS95U2TAG+NqbYPjHzGmX5PV3WeGtfc4G8UN9ILM2Zo124UYftmYSfzs5VSzXIxXlRkujZQOq+eW5qxpdquet9C+j89xR55b12I=,iv:CIYXqBINRe3c+H2oHSwAq+ipHRQ3eLIyX414Fb9dbW8=,tag:JhadFQRKFpDXw9Dgth3KbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
