apiVersion: v1
data:
    IMGPROXY_KEY: ENC[AES256_GCM,data:bGWrpkuCqcTkhdD/GAUrudLcQ8IrolfEpLv7XlEPzhUZygYbOoDd+EEt/g9Y5oBiuPWGmjoUPVRbI1PH/EO41anM4O0xBP6PSF68yWqAYs9QYswjGtHdrQ==,iv:NPlqwCW5J8OmyjKB4Bks6ucLRxrJEIjyxx/ZRePi/es=,tag:bMvRjAdXMKokw4Tw7PCfLg==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:YzIdOhO+ajbcXAGH2AUAEr2El6IXGZ1xg3yph8r8et3kFomHiHcDAgXrJOmREEVYhcDSIRnKAMjn2Q4rrDeTgQFqNvvA27jREV7rK7+FNKRQ2Ep7+/jF/g==,iv:t5ip9DCd5E7Ez3kTUl2hI3+4S2WsBFvk/r+lbMvTOPs=,tag:J/LTI6vpLmPgwm9tTdN0rQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: imgproxy-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHem1JS0o3Z1dZamRXMUgv
            dlB2cFlHakgreXJsUTd4clVCTWlTbVNmckhJCkxaNXBPbTc4RlNHYXpEdXVoU2pa
            bkV3UWVhWEJONW5CWGpoTWMwRjJuaVUKLS0tIHhndGVOdll2RnZERFJ2cVRuUnpp
            MlY2ZWFpaTlNblEwSm1UOVlkRXgyZzAK8fb9+GRAaxAZEIqX1yNxi84VZTYLqM8/
            K61bW/VIdXoeuLQyNhcmc60C1zjJqU3ilUpRVF/8x6+Tt5Tmjex43w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU1JvdG9wM2c4TXE3cFow
            Vk1lR1Awc3RTa2pqSUpiMDl3WnJCdE14NWpBCkQxZVduc0xDWmV4dURnazJsR0dZ
            K3ZrRis1NWVJWmtidWhmbDhJWFpjL2cKLS0tIGJJdlpUaERucXk2R3FvM3BjM1dm
            RW5WekhRTTB1UlVhVTg4Qjd6aG0vYjgK7veJbl5oT14LPzqZ9nmSrPhxOcJKFztF
            UVJaMj9JJY38eg2WJwzxdWuIleyypz7XWgOCGGt5Lqm7wtg8vTYpfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbG9TdVFFcHV3ZmQ5VU1H
            eWFFM0JaZmhnbzVNdjFoOTJiTEF6bk1tRkh3CmxrUlRaWVJqd3FTMTZmTUsyMllJ
            bkl6NlMwenRJWHY0aEZKUnd5UzhrK2cKLS0tIG5CVFhvVWNGb0tFK0lOU2JJbnVR
            Lzl0a2dNOHFDZHI5Q01LSlUxUkg2WTAK1jr38YgL9k4z0BZPiHpTW6DDbGyjYu+3
            BcSZvgiIbIwZiSPt0hdE8DwbS5TMNH4x1GmoCRhGVH0dvEShE7fQzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T13:46:15Z"
    mac: ENC[AES256_GCM,data:4WdsbcKaWYVHHbgSL4QgQ51O4hn3eAyszk4VT/PJ7HHEpKchTD+WNDZRYQhxHHlnvKt4/OWQjwcnwHaSQZAkQTJJdO13R6iSBjVb1Xo2ZhvbqLwQ1r9DNCVenPKOx9eZX/VHC8qVcrDmFKaPLdiT3aXG6/QYDb6fuOftoKt2bA0=,iv:WTU1VdGBKbsMjB9A9mnUJMGusEMoSGS/hAxPeuStbo8=,tag:PbMX9qDM7UNvIlWuAeG75A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
