apiVersion: v1
data:
    IMGPROXY_KEY: ENC[AES256_GCM,data:10j/BclrHAsB1Pe5k7gn31EEbKh+U/OKFuQ5ho167NnQAqQ02zE6PbgQje9dro3GsmXPF15xAfhPEQejJyyHg/BrjgD9go6HDplKXsGaQcoOf5sAcSjhcg==,iv:R1siGqeoaaQV+xi7YCis//qgh0eDWXvRBCIGEiHN1Ds=,tag:DhVvze3wSotVmtWsO7fvNA==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:vLyvSorf8eT5EYoMQSW6tMwcYWDGY1O9jbZUOcOHOpsZMJiEiSiZM1aFRQodft+gqjitikQrieZZf/1KNLB1mzySKIZnsFU1kZPVlm900MaRhlW1devyAg==,iv:jgai0j2BzlaJKT6vhP3m8vFI9SvUMASvIjeUy1PUcqc=,tag:oda/4cEclNlwuSa7RZaBYg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: imgproxy-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QTZxaDhKS1hnZ3pmNExH
            dXZLZTN6djNiSUNtSHA5OU83ZUI2QVJwNG04CkRuNEVKMTF2N2VsQ254YTNSTUVx
            VnpTdXB4aVJxNm1Zckp4Y3RwNTQ3UGMKLS0tIGt1S3RCbzZ3bG9mc0dzTzJZOHZz
            NEhMaVQzWXZyUzBaYjg3QUovUWcrUDAKtJ5NqkWkR0Fv0Gp4Yx4ToxwY29fPpEc7
            EMZaZywtCqI8DF5Z26ULaxgsMPhXswPlnSXnL9TKLUOB5GaHa5BBQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVXB4R2FNZUpabEdrUE42
            aFlpVldocDVsNFoydmVBVHIxcXZWVXV5ajNvCkdlM21VRkpwM0FIbW04ckNHRXRn
            LzFJb1FKWDNuYkgyYlh1Y01SVUtEZUUKLS0tIDkwY29VY2hiNk1xbUszZ2lSZGdU
            TFRoZ1RmSldrb3piZzRFNGo1V24rTWcK+8ZV/Vl/x0afYy5N0q/y7153lZmUPCwB
            TJM40E8gZEzqJQssrZ2IZNJWWE8xEdjYBTsIuHrKFIRqor1Wna8Zyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNVlidk1oU0c2TytabGhz
            WlVzZXA3RmhiL2MwNmxDMjNYaU1ORE1WRmprCjZpaGZDSWhBMVJHWXJJVVdYNEZP
            UWtCM1RJaFlvdEgxbEJrTEd1cG5OWkEKLS0tIEQvVGNPajdlK0lBUEhiRzJEaDBv
            U3UvZFhNZzBvRStBaC9pSndjdWpTQlkKa2ZOn2I1unK0xpCQXlJ+vLBTh7AMBN58
            3xRVp9dIV2O8wpnv0OEOSLsbOBZj8gEZf5+VjPUloKqDvqVXSa86nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:10:47Z"
    mac: ENC[AES256_GCM,data:4VPpzZlnXkP1/0x4VLE9Gw8TjgBJvVgnE4LxOM6vpGsh82Wa+Wuxli6cM84oZ8vXuKe07pAlq0Y0oNdDVfnjtJtRsdGv+d4uvFwRadYVuRsG/MN+ApzN6aGn8hPT3mDDHwIfLtxTAsrt99CEHQ94oq/QnqL/ladlj4AfANli5ug=,iv:O2xNF63kimhKdpAPaFG0gXs9bilx6tPuPsbY1S3A+g8=,tag:lS20ZZbcP2kldvaexzo/Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
