apiVersion: v1
data:
    IMGPROXY_KEY: ENC[AES256_GCM,data:LhNbtI6iYIoy29e482QcsL/YEXPifs5U8taWSLVXCNIujUsPGDq5poxYZWNeSsD9/+rsRHF5oyNKOe3WgOeLZEHniUqVmlGr/27CiUT6wcn8fuPOMkNj0g==,iv:9ZXckmSdj5nxfWZFkEEEC0o7G9lPJrYYOmRFKI0zcto=,tag:UygelHarMJLlT1wbg5SYZg==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:ClvrP+p0+yJmiVNAHDwYzuM0XHVzSEkAnf7pVs375qZdK4VOZFXfINAPxgOFu4APcMTx5eFjRtmOptrJx9KK0CzWU9wtZuqRxOUkvse2oueS1I5xmrnR2g==,iv:nKVLYwQce6C2nkxyP1Vn/4ZNJ9HJgGgYuwmsOg6Bqqw=,tag:/9S/dYYOz8dlTMoZijIDUw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: imgproxy-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQ0xvMy9RRjk0RlZpS3RH
            M3VUUmJaaWlMRFlKSXZXRDVKWlZsN0k0TlgwCkluckJmaWtYenpTcVNoSFlmRWRv
            ajNaM3l6U09mQkNmZ3h4VytZODVoYlEKLS0tIGNuVk1kM3JRS1ZWcURNYStYMS8x
            SGhacGVjeGk2bDZjTjRIaG1kQndMNHcKtODfjjxaixG4CsL0uajyjHluGcQTZlhS
            jSnxN+2Jz3H5rwcGWRjN3r5XzFjt6svfTv/cTTJhma4qlvb2HjEVOg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZGNvT3RjUnJsS1ZhaGpL
            L0g5aDNMUjdkc0hHSjFwcmprRGJRcTcrd3pvCndFcWhBU1ZsK2FkSnN0TkxRc3NB
            VnFFbU43NTljTGhrUFpmRG01dDJ6MDAKLS0tIHc4RnphanhVUFBvTWRkUHFKTlFY
            NnFyZGhOMmY2Mi9oTXNnUFNtSEdJekEK9Vi085UCU5FRj1/COXNhaUViZoQLS6Er
            eAKw3apbghiZWtxlDCaKi0dnnDjav+hzmvrjr35npqeOFRSrDfBt1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrajE2dy9ublZubkN0RTdv
            cGNnVXI2YzIvQkl6c1pHQjFPUzVvdndrNzBjCmtQcWFoQlpqTHFPMGtHNGdTaDRx
            MWt6Q2k5emtkNER5ZlZ0b1hwQk5pNnMKLS0tIDUxY2NRN2dYOVB5T3FKeFhyd1FW
            WWxuYlYxWlBaMkh1WTFnQVNLVjZBbUEKVSHu5d/5D/k+zJB6UWBm41+737bQsnBv
            WHst9ydkYVQDc5kohWzr5N45m/kQ/Bye8XslbqO6BDxKfKLcVzjbJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:05:51Z"
    mac: ENC[AES256_GCM,data:Bntyfuu92ylSCjzM2mfemBfp65VGIP6JDbsiQFmY6Q2+XVLWFHwa2Be1kEqC1RMOhMW9sMow8OlrHu+fFUGlJav36/yp/BHWBKWBhGb7QsiDicNinhBY4FeZ8O7V49xODbibvs85Y5D6zYO39J4zfHQh6ieTPKaUS7FESrEMafc=,iv:jSs2NSbOGmoBXRwKblhtvwzsWOldoRoGiTT9lZY2xZA=,tag:JMR2J6yTa5ySy3TeNPMsKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
