apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:x16ofisp,iv:cU339AIdr4e2x76mDSlLZQRZBSZFqBvV6jwV1Y2l5Sk=,tag:s0VsYby2AjbJTjtz3x8vjA==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:wI+6KmHVDE8go6WF4nsLfA==,iv:8YyCN/iFqn4rfPlP0hZu7omk/YxIZe2Y+Y/nnqg2HVs=,tag:JRzsE627ahe3XvKx+NnGzw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:vgBS64uNoC/8cR04/Rci+3CuLA==,iv:bz77ghQVOZU4L/ISHfn7YLCQ317mDJ6xGPC5fabUur8=,tag:+K4J/BbGWWoKTLGpp47Ixg==,type:str]
    DB_URL: ENC[AES256_GCM,data:u8SZ7lj2XMBQg1F/REakEO1/khrn8/t2n8TizHluTpssDjzglbFm7MB9Tk3OMOSTL/pHS97IqciVLTSbnr/z007EubiBnw==,iv:igTCJyThXcd0V0UzbIuYh9HhC2E+eeEjvq9h5zu0Df8=,tag:WSzdPOI9O1b7GD9LyXeTrw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:078+tKHvlIQ=,iv:bFMEdJ/Y2v4+s0DGEqP7mCMheDgSGiN+uGZzJsa+GOU=,tag:G2zXKcjeh8RpPJGYWDp/nA==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:SqZDM0KeOtrqJihsRgfpvbqSMP2o/wGegMEj6nR2XDjQl2Y=,iv:YYwCX9djMc3mPmeSICAc7a3OHc77ZcYEv+Ma8pwW6SM=,tag:HAkDRymoS8CW1e4rHoPdLg==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:1Q4=,iv:AFiUMNKFOE44pSDSKbL2nCWK57RkWcVajhqNQHGzj7E=,tag:g4Dyxqk9NIanx+/ZRTkyOQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:U+j5gC2Emd38cHq3FuCSvdxSSBfBMbwc6Q8AO3XaIDIt7xRqmqu84vqwRGraO2mqlYKRQHRTpC66/VsBgBZjISnHZS2zTkwUIUZzsJppdtSMU2sdFf2w29g2uQ++8zbnaDtDJMeDtIuLNrGJE8XHoaT3+IJeerZSIV2SykD9NScaE1HcBoNiHaVvkDcnkDqJPKs=,iv:5NQHsbHi2NRkgsn/XS4g6zrAdyHTJ5pdNy/Kxe/WtxE=,tag:VDTxgD7K439xDdQ9FU3uPw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N01qWDZ3MEp4TGRaWkxV
            eGwvVDZUNjFqaDdMamkwb2YrSkNvbDNHMTNVCmFHOWZuWVFDd3QycGRSOXRaeEQ1
            UlN0OEdzUWc0RzFZV2ZCWmVHNk5WUmMKLS0tIGVxdU95clMwS2grTzJxYVJLcGRB
            ZTVKcGhvcHE3cFVZcStxNHVtRFg4VGsKXWFrxeOlhha1Hk6pBrCcDwZJtzDibDzC
            nZbBLPyWwconAezUp7t9kt1nO/HU+gr1VaHpFqy+5OAtPyUqKxDF2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubThKQmhML005a0J0bjdl
            NUVrYm9iblUyL0tjVjhSdzdWUXZ6d1hvT3o0CnJkK3FlSG9wRndXTXlqckppRkxm
            VHFodHdQWXpyQmNnK0xObHk1VjN0SVUKLS0tIHN6THNaU01ZTUh5VmpOL3c4OE8y
            TksvY2l3Vjh3MUkyY2gvWDJ0NFJzZjQKWx6UU58fZXQnjyJTyuR6dqDdgIe0543W
            fY5RiwzM8qhjA6nJkYC/gJxcdYZ2SMVZ8RF/pKipYM1tnneB1Ra8ag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL1ZYcXl1WlFUeFJXS2Jx
            TzZXdGhwVW1lLzN6b2JLVVZuT1RONk5WWWdRCmVTNFBzckovTndKSXUrWW1lOTF0
            Mng0SVZ5cEVmWGNpN21TTXFSU1ZIM1kKLS0tIHcwQlNrQ01CNlBMYzZoOWpydGh4
            d1NvejE0SVp5WlNHZUw0VWcxZXVLQmsKJvQFq0Md0fp9CqURbNuxNj8k2Yr+AyKO
            lZayViATGKxYoYMwe+eqo0rmDCXlupK/ppztKuGwCCoobqEp296dHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T13:27:36Z"
    mac: ENC[AES256_GCM,data:GyxmbqKKBBZJsrWepSRdK5cPbKT0/dhyWxEkVlbNNUuW7d7/X0KAxgzfI+Sh3wa/fJ+YU/Bol7IBDGOcPTOpfVE94INlAhccDqFF1uxyDz5f/r2xWiOn+hLPzfs+uSIlIVA42W2Dj66uOjurwMk8pI5HOcEns1mEzUeqTRrETSg=,iv:ne2oUXig2aztOqrGZzL7vbecsLm5EOIO1jouYly6fRY=,tag:0O1kttm4kPHhXK2lE3/y4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
