apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:uziD5tBO,iv:shUXuejcTNoE3PZx+DE/mDfeeenD0ZbbxxqqFYJXmJs=,tag:SyOeSXtEzCarTreqtANyRA==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:qOt+ratPt6M6+oXH3f7ABw==,iv:3p9PKhP/DA0SSVTXxFUac93Wp3ocf5vbOYe0wktXy64=,tag:kgNwrbIF97W1ybACklFUBw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:JGQISLx0i7403EBSEbLQwzlAsw==,iv:aSAPTATNFMFHLXcHJvOnCKr0SBFYT2x7q5PgaAuA5O4=,tag:jYc75Jae3ut4cfvwi5+iSA==,type:str]
    DB_URL: ENC[AES256_GCM,data:hGDkZk8KOQdrvPM+d6DUnFw6yz9WMh9xMPB4ZKUJW3VGqmHCZUN4GB0tSYO4lQb8Q5iH/58ulfMAHEcYbHgUwV1kpFMqmQ==,iv:EVGhL+CdSjRpg+kAIIjyAl2hOWvV7l6ic2JkPUFMnas=,tag:o3N7BO0AopBA3DKnedoMPw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:cslMaZWCIAc=,iv:RWFJxWOlIqmNbEEjF5i+eNlxYuX+BUABDw1Qc0Z7oyU=,tag:S/oF7KEjv6atfUQPv0rSjA==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:AKqYVwkjk5G/USlsRab6D84UBgNZQE3UVNqBpLazCNR2Q0g=,iv:mpOgvuCw/94wpcNEeu/+yeUTelCvKVy4vuNXv6mRVOc=,tag:B5GLiaO3gAfYJRAu11jJZg==,type:str]
    IMMICH_MEDIA_LOCATION: ENC[AES256_GCM,data:f5ibN9NBaJyQkUVdyH90i3e2ew==,iv:0Zn9115Ar8fceCJ4aMgie+d7uJOjLJHD5y4+Rgc2kLc=,tag:SHxNXd7PXkwfKAZ4WF+mkw==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:Fko=,iv:HDrnoe8pjAoglNtbusXALvyaXyBMZ3y6WbO96ll60F0=,tag:Sjc1cY4kcKCo8YToEu/lYg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:QvQbT6AkyF/PC+jspiGVTsHGKHdLoeImeNE/hGxatwvCxBkQwe72xXtmEVBUhp4PfNIGQUAlWvlO5Qfn61ziWxx+u4dthY0LkwZbav58+PIOiUFs37We0POS1kj1Sr1L04KtBv2B1hgC8GFtVoRto/N2xTLoHb57tVnkjCIA6FlJC6rI8WlhzGyQfdryudRROsc=,iv:5YDmvlYZgCmYUPNB0Z3m50UQ5YpHnbjLXEmFTTcCO34=,tag:dQ3gLcAZAaRQD7tp8Mlouw==,type:str]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:IRjVRXW3V0zwIOIvC65rM23otQ==,iv:uU99YAmblDp7kqoV7wKuiQJGiMIx+9JZ6Onf4zQAhDQ=,tag:IJWxYWbJtuxDSu7AtR2fGA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeEJ2Rk9nWGs4aEVjZUxL
            NjkvQkw3U3JwdGd5dW1uOUdBQlZsbnhMd0FzCmNhS2dkd3hxU1Y1ZmY0WlpsaWVO
            UXpZWjlSaFIySlJDRHA4SHdNR1YrTEkKLS0tIDIrZ0Q3ai85L1VxMXduYUFTcit4
            MG83SkpPQmRNVjVNMm00a1ZZUitGMFEKpHq9oIwkYVePYrr/FT3+9B2DUVyn/thn
            gnR1bvxW0xu5f/IffxOBK9OcY7Hf7QponPtRHvJltGsK5pkfdMgT4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtellHZEVDVFgzQ0VGNFNK
            ZDZrZUZmME5DT29lMWxOMjhTOGtvZzRFbEZrClJvelFEdDRaVjJiVk1SaHJkN21x
            YjNNT0tibGo4Y0sxZ09HaFJiODlwUGsKLS0tIGtBd20yck10dkpOWnhKbXJRaEtO
            YjkzUUZCRUczdlNTdUpFenQ0anVLMVUKVaqXJYbcHT3EkkTt6kM8D5/D0kPqgBnn
            N9UBYeB6vBXOGk6hICh7tWCehB+TRniah6uRm+7TZJcmZVnawES/9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxek9tRDY5d0VGWnRLaVB3
            ZGZrcFdyeDJYRklDN1dCQWhjS1c5SWN4ejBFCjQ1UXgvNkEvTXMxTTd2bE84NzNs
            MHczRE9sTllOZXRjUUxua2JZdHh0NXcKLS0tIHZpOUFxeEZ4dkcwQVdwZWl2RWhV
            NmNsYWo0V0FCM3FyOXBJbnZGTXVjeDQKx5JW8nF9iewRavRdXr0yx3GIhVZyecR/
            bTjofRwoSTfTCYn3wWvEmQnSMWrFEcSv/vL7c6TpSkZSnX1KBRAr+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:05:51Z"
    mac: ENC[AES256_GCM,data:tylrgxphS8yzX/hYbVUHdSLkV7H5fZJ0eg0VOsjzCrQ6UCwW7xU+x/Ok+hSxd+QhgZYcABEVNJ/7at3TW16tM482tcx1ml8rZWzoQStZl+EqRhAexTFvrED5v0xFAggwAD57/Ng3dCVRo2YJscvOIbDpYNF0lIQUlYLpXC5kevQ=,iv:kozcgUlQl5VASUIs2ROxaDrDIY0PextF8QRiGgeSDq0=,tag:bJokt1/hQ9m6co0SaHvkfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
