apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:LN4LbRMn,iv:qt+4YOK+eq7ASpn9hsUPDoRIjiXC0lg8PbPrq0RK1N8=,tag:JbYcPwNVpdk1IbROXhK8YQ==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:RTR7ofaGZwOhJBBTFQ2fjw==,iv:1SF2cWDRiBr5EVzV7bftzgbPy6sRyn9H3ap/kuZ9BOU=,tag:vCCOOvur6IO27GdgefK1kw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:rciEPOCACBYZ2qQmP9novkwtzQ==,iv:XKuixhvDd9FBOBCL74dInWCZweimlweb/S1VpbbZxyY=,tag:1xZtQ/VCMgfofQ1NupB6Qg==,type:str]
    DB_URL: ENC[AES256_GCM,data:zcU709m+Rc/lGTCcJXhPSO0TYEL8W5MAhcSovk3IX3zqwijuoKhNJiLaeYGdxISjf+oOG0YUiMg/zZo8B4V5q9dpR35oEw==,iv:9p6he3dNyX5Wizqdk01sbJPM3Oir8cbBY2oGbByDTK8=,tag:p/eHGu0R74UHGkst3n1UeQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:HUC1d19tWUI=,iv:5AkuXBovxZ8zo03d/FmCfBe7K1TIZN3z1bWbU6qm+eA=,tag:QAtbNKIsXsxFqbiD+UVdyg==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:A/eWrUuI7QxS/AapAIFK8i6S3hbRxFmMqI7ND4w8T333tiY=,iv:QNYb/Ru68GzCFDR/NkN93AZCMyfp8KvowJ+ZQwHJHAM=,tag:uP6M1LHfD3Nq/MekvD5i9A==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:FFLNz6PKNYixtSeybIawKS/HLkMSgDgqrACrCpEToJ3oGoFbZDGTcUVsr2taqcncpJZl090+ht0RnFUvTA+99cwh00iga+iO8kmp1fZhW59amKMmrYkzFYpp33REPZZGtmOn5ykgFwn5m0TwzliPRgW4dP+7tQIx75NK41/+GQ0oya0f/8NM+OcrGv35mvRA+lA=,iv:j0V5GQQU0GrCydcfpvoPkZRVHsm3YdZtCC8STJ+viiw=,tag:V7zekjY6vfOJ7pFd8AfRnQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Rk5xSEV1ejJ1UENHZjhD
            YnY3K2l3TVc2TEoxTmY1RXZVQnRBT3I5Zm5ZCjY4MUtNSkFhRFFISE5VeGxZN1NX
            dTFtRWdWNFRWSmkwb2hkbnhWeFVwb3cKLS0tIGR3Z0laaFNESXRldncvenkxTHM4
            VTd0N1p2YkMzK3VRWjgvNG4ya0dUWEkKHuqCq4esCK1LQxB3m7rwCtiyzVQ7OtKY
            3v44sr4aYgieR9Ni3nPFjS2O7HQz2teRHJo2VU3xIT485cbkFqLfKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaHN1U0IzcDM2bFN3RGZX
            RTExSWQ5S1Vjd21VbExyU1FnWlpvSEo0d0FZCmJwVmx0bTVCTk5hVEQyNDZlNDc2
            MkIwa3ZFdUpGUEtUdDRzRnlqNWM4WnMKLS0tIHI0RmRFQkdzYWljY3Rrakl3U3RL
            Rk1zZERtSUtBMWhVSDkvSFRmT0FEYzQKLMrAGRQXXH4eo9sYxh0O7t0OVVSlZIMI
            4vR8SSKaTfJ1qAmXlrtwYEAt9zv69wZnnjmiU4/JJkwvl2pQ0+WxZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL2VmQWZRanV4ZDMwRVB5
            Z01ueTJsbGhZa3RoeWcrUmxSWkQybFU4RWhZCkFlUk4yUWJydURad3NjR0U3Q0Ix
            SFdvNlgrLzEwTDVLSVVYMVBZeVlNMTQKLS0tIFhmN0o3eFdrcTRzS2tWU2RUR2hC
            ZkI4QTlkQW9YK0J0RldqWmZDUDltaEkKugdAqGYLhadH9EEQkvtYgrvhIjSsFLDQ
            GPgCRW3/L+vrLbePWlGMpZrOGPB4RA97cD9uG4gOcp9PYC9dTbyBzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T15:46:30Z"
    mac: ENC[AES256_GCM,data:QxjrNQTAW+31R6N2J07em2lSNP4eq+buO3xCQaHkdyjCvbzoNZy9jZZQL/7iJS8DMtss43wvpX/LmzbpXs4mTzNaJU7DfU4VPbdn9qNgpsqCI1wxJuAew1bj9oKxX2Bnwta4labobO6/2y5Trp42JYR9ckejDemIToCKhdjZ9vw=,iv:YrOV+Y9o7Ulum/C25McchXWd4iEAj6hun/PSLxGbwtI=,tag:cWtyyBXPfJ/uOjdWmsOi7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
