apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:/OzEfAvQ,iv:TByFInqI7CMVa1vxIQBDoVh3/fhrfQ3XV6piGgjJEwk=,tag:LMRNSFh/Dx7jtkRCkOUarA==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:SS27cEhHu7Xl9pY/0Hv+UA==,iv:oOpZskIt4HsvgSHNVP6W0u18i1QqEPs3I1QhXMbZKGA=,tag:NUEFBfJJfAf/+f5WFcLVxw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:8IxcTgnR+Q0nBx4mJt1+I1sQsw==,iv:Vr6ZemlT06HSEDwNHjq3zQiabN2J9VpOoIhC98Ov+Vo=,tag:p+h7eGeM9xGD81hlxzwOYg==,type:str]
    DB_URL: ENC[AES256_GCM,data:O69dolGUSwxIawL0PZw4+1T3p88EAA5gUHKXV0Nvhhro6ZQOYc2xq9XenN2EI96tWUyW1ER+q0Taj9A9aqctXWwndfc09A==,iv:dgShtcRUmkjpRG5e7LhuSlN2rntIYshqKVF/gokKULo=,tag:wrjSOX2BH8K5rwsqtaIFFA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:9cE4RBB1gWg=,iv:3M7KEaILPKV41Zu7+lbMRfZJbKyVHMQqtXIYxjlt+Pc=,tag:iTuA6XaG6jApSbE9pREy0A==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:OEnIfNSqb6uX+YlBlgLW2X8qzVO/fct1KhaDRoPvMnIaRg0=,iv:RkX6kHEwXWPs9Wa9RkB/TAC8/Vkmo2DWIIj19VvfAUs=,tag:IzYiA39t8EDZIY+ZKRpOcg==,type:str]
    IMMICH_MEDIA_LOCATION: ENC[AES256_GCM,data:5CIgUHVzQ0YZOAZpIOGS+vayzQ==,iv:Xn+x4MabYIf4mYMK6lGEJ2a9EL5fh+atB88QsK0vBaU=,tag:ENjYjgj6bvmb4Ztf76L+Dg==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:MFQ=,iv:0pGuPlJ8qCExV2u2Ldx/ssyoh13CaNXHhIrk55LVT/o=,tag:HoHFI63Rn2dtcJXkWNcqnw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:rKSKaGSxW7pnVP2QuG+BGU7f8bjAAJl/iBOFdg++hkesUa8XSASmbPQqbpJqAZGYtzhj9rQmfx3PXABFCyisFytXeHoi6nfYW76EqMHknmDFzX9Eld2aFeo52HtIrUeIcdputlij4cu/kwoSFMyAvgWSLO04Fp0ycUMDGSspnSOZEROn+Dwc8lSxRywXbWSTeZY=,iv:qaGE/PoOkT69pW7AuF6Ox+8Q07cwGZh/IUwzHVc3qKw=,tag:/0M9UzKEGN7hBC2OwifjUg==,type:str]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:Y5f+7rL2rYLbYR3dwCAdzrSOFg==,iv:NFUBFjBfiFSwX5Wjvp0a1I74OjMGclWYyU95hHNZkpM=,tag:6FAEgsDd010/uj91+CyXHA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieDV5K2ducVFINGNqNCtv
            bklVSUhpallyY2xGUGpjMzBEeSsvdjYyK1Q4CllZUjV5UFVtOFNYWFRqUy8vdW1k
            MnNERXdUc1RaU0JFVTJYRldDNmV6UlkKLS0tIGJYYUEvQUdXM0xSdzM1aUtsZjdr
            WWgrRWxyYmFyVXExaU5iU1VzMXBLUW8KbJA6qbjtoIkjumB60C8odFylZL5fDkq6
            za+mZP9vRASnMljk+3ycy3TL8tyExu8Flawyq3+YI21VVAUXxHrgUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWGtuS0QrZk9jYmFHanBU
            QWtPek1xZVlSTlpQbmVKdTZWL2R6b0ZkMVNFClJqK3VTWHBWMFN1VlQ0MUVrVHRQ
            bDRhNkRnUE13ckphV0tObzVDVjNDUU0KLS0tIGtyN1NIZnV5SGtwNGkvaWcveVd6
            aVViZERBR3Z4WkZxWFhweWh0SnNjdjAKnOLH46Ex/UG52u3pUwjouQVnwuiNxGeK
            O62kyo7VVLr6dVqGLttU9PbRsZ/ifVEWGFIet38vzbSo4FBrJD5yeg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOFFrVDl1TGV4UUNZTjJ2
            OFp4SFYvcnVoM0NGeVFiY1hSbmxYSVFYWFNZCm5JQWFUbFRiWERPL3I2SEk2Q3hv
            MXBWdUJ2NXRieCtMR2ovWVlsRzBEUnMKLS0tIDdVdEZhaFFocFZlVEhiZlpFTi9y
            UGhMWUNmbXlTdm5ubTlHT3BLNnYvV00KZaCQHAAnc1we51vd9Sx5Sz1cihere3tZ
            +GoQtJ/J5QG44BZ45w4rfYarvbjGv56nRhiTQTLSUA1JN5jT7vtrhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:02:34Z"
    mac: ENC[AES256_GCM,data:Ho1ArfI9EOX70tfZLfANI4uiwNEhJo+4fUOFnnMOWaIfPJph7BjIPXaHc81y5DekwiPZJQj8SAMU6lZt9fmafEuQEOlXVKiY5zJgRpVhpmwxHOj1UmnUnt3iJr8UPRu1vVshUJAyqD2h0ighnjrInsFlekUxMsDm6qlZlDs83A4=,iv:AclMzKe9Fx9np5un+E7WfEqnyPJeFrk9eh2ERSJHY8c=,tag:1eXBPKYRv35BWrZ8rBqAIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
