apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:DTCIoxhx,iv:YO436vfqu/yuWkH/AqJ+zMonI0jaj1L4Byxf1FdENCY=,tag:e9lzmBzH/jnSAR2gKv5krA==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:fMrdPJMBm+e7vEi3NC+trg==,iv:aUAKXFNWWb2Zx2N0JoJRqEOD3ziwBx2DBsxOcU/kZzk=,tag:x3R6J2EuWZKlddguL8ltjQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:B7lfA4SEs0W1R+VXFWR+vzPX5Q==,iv:LpcxszM4Hfu+qX0+cc1FWiG2/zQGE3bHuxqsm3bffmM=,tag:c+gi/j0fC9UREzdlzfD+Mg==,type:str]
    DB_URL: ENC[AES256_GCM,data:BpeGIvUqykivsHlM05UvDUm0gFKoIrUmgu1aOZNJ7eCSl02Y9MgpevWcZ2gJRUaSRBqrkyD/WzvG5y/jZVKuz+D8WsFl7A==,iv:xOjJu8bLDKt4w1eYsSEXeuqa3Ks8FR03T52076Iap44=,tag:+KZTObI368iFzWyKj28TTA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:qhn61fMGLdk=,iv:g46KJyw/+BHDVvXzKlFgW37vVqU2GlbnA5YjGna5NDY=,tag:a46wZLo53kreYa+S9nOguw==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:d8hb9Az3xRD+thmwm6/3cHHZ149+R7T1I+CXc7oBqtkdtS4=,iv:T+nrmySX4L1RUYeI6JQ9tfgm3FUasRNdFP46LFEf23k=,tag:0QAi1AJZcC/L1K/e4e2+1A==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:y4o=,iv:AMrdz6h8lrxoc4bvufr/Qn0EbwH3s/s6zBSGnA89GOo=,tag:BNePVr+Jf9i3LDYgYJC2+A==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:76MDb60O+J44KReYg/9xOUQkJ9/S88JDP0toDgXCacUdy7WIWKvS9LWCuT/wfpBORPJzlIXB1UGaEVJZ+LoxrDOvB83iRpmFSVSwO5zq+ONbqHReqkGcxnxNUi7uLWkXqhaPCuYL2glcEIcLgLZLkrLgoK7ffLd/XEQRgd0w13rynTuSgn+MGHSHXgsw/IK+W58=,iv:biqAuRo4opRPdx7EKyDeTomcdASEAJCaCsHe5RZbAO0=,tag:Th1ulMqVgCLxEdaJwIOADQ==,type:str]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:1hcR325PMCurZ1ZOaBIsN1/lyQ==,iv:gFPjVusOQnPDY22R8RltJGTbBzwknY7g0vFL910CMXc=,tag:L/BOyLSm1LrcwBd/uIhJOg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNDRRdDN3RlBYM2NKTXBZ
            WFRDbXo5bm5VbWtHOGlCNzdLeVdEZ3drdXd3Ck5jbnhURWFXckJ2bHBhZGNKekRP
            Ui9vaE1oNUdPRlV4MjV0UU9GR2RVTWMKLS0tIE9mUk0rR3ppUVNDVEdXOFZ2azFO
            bzE1SnhhSzd1d1ZTcTNoOHYxVEtBZm8KTte23+3pL1RyepPdJ+0LLNDmTGp0B1Gs
            bEchs7ETGV0w/xOi8MVXh2Chzj+13JkvmnW2gsaNfzGbDkWB1KaEEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSUVUZzRia2JXd2pWd1BU
            TFhlZFZ0RU5EZDBkYSszNFpFU1BaM0pXeFJnCnZHTGVURXJkNHJaY1E3R3RJSGNw
            ajJWZkgwUGpmWnJOZ2NRR0dhZEQ1WG8KLS0tIEpldldVdnIwMWd5T2RyeTBBSDRn
            cWsrQ2NtQ3VLa0xrOU42RTRiaFRZSG8KqlnWmunWsFqPAG6hCrjFORRKQYQCkEFE
            /YfMYeMcFCZNz0s4frrEoKBQvdesRde6mFg6mcN1hgSrLSReD03FNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOFZNVmZpNzk4dlN2K202
            QWRBQkhyR3lNakpkQm5ldk8vT3R1WWhPZEVnCjFkdHNoTktoTExFaEduZGVNeitk
            WWdZQ1hWdlBMVTVLOWpuOTJ6blROekkKLS0tIGhxZHFlTGwwN0czL3R1VDdINnZo
            RTJ5Q2VQT3UzY3pzKzhpeVdNdXhFS2cKWuf7m++05/OyqFHoYWpIPG2eUUD4GHaE
            D4mVtOaVoW6KhsykYnrdAcfQZgywtzK05dnKdTazYY1QRXXHNQ9WUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T13:35:09Z"
    mac: ENC[AES256_GCM,data:YKtcnWAxkJJ7qJ8Bb5mpWEe+JhL/+F+x/EnPUPFlX43vBguFKDOZdRi3o8PgN/eqYhDHuKE2g5oHxcQo1YTrlBuvOXG7hjjj59tJ7iJ/f34t9cE9kBdEEoytCYness+0+W/jUBrR2Lq/fM4BiHC3x09D9dimz6Wmc4C86ByI4io=,iv:yb8HW4hjFkmNlC975vy83Muz0nITxZcNrBhApr9YyXA=,tag:qxjNuitJVYQJyey2kSjXAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
