apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:w4yBQ2+p,iv:WmDZi0My0GQMDxyHSkTsXTsvwTUmX+o5+u8yM3lONls=,tag:Jvg7Ljix9GQ44H3G+p139w==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:C2/egAMTc2nCFKtWaFePvQ==,iv:CY/rgnKceS3W+vop6RHXU5VqQoXndShWt4sidouXrao=,tag:vAGifxzu9ywzxfi+JNcowQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:QUWx/wcr1DdLu2aEgpRZlUnVcQ==,iv:aXz6HOi+x8hkBp2tpD3353izFvLZwlsIL63RoelVtL0=,tag:LddfpDiTOqsRFk2xxX+2Eg==,type:str]
    DB_URL: ENC[AES256_GCM,data:6VQ5ha5zb23yxSBeFfCTYCZns7x/GYeC4rNn1hrz1IiaoAEGBN/lLRFw5G3FNhU51j/aD9mbj6OEEh+QdWbQIGVt/otDSw==,iv:qMLS1czax9syOr+7l/HVB4ILjNgp0HXccj/CKhWtXiQ=,tag:Yq+1z2XwzjT77eGJ1f/Qlw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:ykIhQRzXwoM=,iv:xX0Xjbt606bLL3sxZzmQGGdzNdQitcU/HMgWdgNgwzw=,tag:aWyJH5nxY4L+5D1/Yvre4A==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:AtzAH9mBW+yqklCk/ssP+IId912gZyYv35N35tv4C+rZAns=,iv:8ajzKJZzqfBpcE38Yo5mKRp3kKxpEDfLxN4YUGmOGyE=,tag:QdI+HHthCHJVuqp/DEBCSw==,type:str]
    IMMICH_MEDIA_LOCATION: ENC[AES256_GCM,data:Si4Gpk/Sa+tkIW2q1rB7iowpjQ==,iv:DpGBTy9s++N+sUoNjD+0F6BL72AmkNT0TtgVbzUfYwM=,tag:ywTMKw1nUGzsDxN0xKUMEg==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:jGY=,iv:+wrvvP90ClwpsvE+a8uHat9XIqYttWEJ7g5t+ef8LZY=,tag:eGdyvctBcEX1FWl7DLfAzw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:qiP7zSv4mOrlHDX5yPSNp0rp90IVPZlp80hVcl6LptZ1Ndl7u5JrSznNilp0t8FjhBQl8gvJfAly96gDNRu52/LhDytSkCjRdaS7eVbofkKKuIhwCotKn2zTgXOBrg+3TbKAOaHEqjMQfnvcpH7YFGUoxiXqXroYB5vDb8+3TfZaGe7HyVqAP1Vpe0xRgadUkNw=,iv:fzq7ITHFhHtzSgt53GU4bXoFoHKEB7uDvax1NbL7qsI=,tag:NbJgLQcmpc5plSNQMg9e5w==,type:str]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:iHIdaV9fGxaseko72U4LwuqdYw==,iv:TSlst+BqzEzOEN7j23ROaxT64AzEbHXnQ/TA4Cjbze8=,tag:bH490SDB6A/qYrJ6nP4Jgw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeCtLcnZSRXl2RmpaWG1t
            LzF0SnlrSlpXZjJFb1BoTlRoNWRHT2FteERzCk05QzQzcGJkdnBNamNqbVpmMWRB
            bVNBY0lwOXRMRUxyWGR5N0IrTDlRUGsKLS0tIGRtZzZzcVpOZ29HY3RTRHFOcE9p
            K0lhKzNhR0owaW53UStmaE01bFYvRUUKZn16zMJ8/+oD3km5/98JkUg7in3Kz4aa
            zouN1Au7f0oZ9Yb87al5p2kfZX8oXOk4luZAtXn00Iy2pbCCB/59UQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TDVJbWUvU0s3WXJRRDEw
            M25JV21OSndqanRKcStsMm12WFVVbHNMTlRzClJOWlBhREFSa3FqeDYzS25uUFRu
            STNKNDFwTVlIT2hBWHh4bXU4MnlxTmcKLS0tIFVlWU1MYjRzbmtveTBxc2E3VGxE
            N2E0RHRIYVNHeVdkVVBYMkhPeXdmeFkKclqiXIfx3HdkyADE0StimbIbX+4xKSGT
            LZM5xZs26Kb2OYrdPDbmtkvvSkfPMfndw3/4V37MMDdBy4d37s6+fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeS9Ram84cDk1aWhQSytp
            TVlpd0JTU242L25rRi9qZFlLTGtjeUp0SG5RClpYZ0FPNGxMRVBKR05vOTFEaHpt
            dXcxWWJTRVIrZ0hLL0lHN1dOVW1Vc3MKLS0tIGwrOURUUXJxN05nUFlhLzhVV2ox
            ZTJBZWRRa3BqQVlpL2taWXdQQ3Y5bzAKBN0UcOJ6qMSNFv7qukqOUtMgR93hhMo5
            akIKEvW2gZLSZe9BkiSFiOU73nPMAgSZYYsQ65jalBlUi27WaGxFnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T15:06:38Z"
    mac: ENC[AES256_GCM,data:UieBWksJI5KEvqWZOB6K02JciwECE9tju7f2uwrtYo8zEkZR0sC9eN2XjOTY9ffaGPzxJeinuPnPqdHOPy7rVn2lmUXzN0/Lh9HIkk6BsGKTe5GvmMc/S13yywHYoJmumF+u42aGuU0ITz+uatRPtgSB1gmU85g7jbiX6ng5f3o=,iv:9BJj+YRERgDL9ftZU9Qi5F+K41WezGDXczurok7+XDw=,tag:GMnD3Ls9I81STt5dLpPfRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
