apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:FOm7rpLR,iv:kJgE9pXy2254XoygZWMBmDBFcjI0YMnQpTguk+o3qic=,tag:mxCo/BsB+mhtYIkfITR/tw==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:RjgDnpm4AVBgQ8WrvXVlJQ==,iv:Jw1unarku2CRO+vo0b/Hp+lvQQfpYzrCZjLQkZCVnxQ=,tag:nbAGh/dM/NqdNqAs79IpPA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:jIIsLx5grWjPEAULONqO1r3qJQ==,iv:lRAloI5T9v2HvPj1Tb928QanTfvFa2Zv0Mzt6rsSko0=,tag:PqMjSjOz43KPo1W334B4Fw==,type:str]
    DB_URL: ENC[AES256_GCM,data:hduq9j9H+PzPxV42923uZO0Pg987k6gHZMSKx6z+NE7xG8zg0XoNeoKrWgKKIXGTIe0y3HO90uW33x+/m9hQAF2BzYizYw==,iv:k/BDtGbPJRBN7+ZOIGWvG/CJTkMwYbhUo1XYIwFEfq8=,tag:yocpQK5+aPnFgTFJc6fdeA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:lowBl8uWXZY=,iv:mQjsR3Wh/8TF8JH7gm4hzGsm90egyzoDzbcMrqopJBA=,tag:Nhz96ivTobJd5EN1W+dHew==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:U5gMh5S9vzd7GPmzOVd9SHC2q1QWnDyt/tizLLRJit/q4Ok=,iv:01VySE79/my5ZrKAyhPx2dTFCYTegXhSglLbU6Xt/8M=,tag:xWIT0fpwN1Cf8bXcKD6Qfw==,type:str]
    IMMICH_MEDIA_LOCATION: ENC[AES256_GCM,data:h/6JMMpsJP1ZgDt/qkSdh2ggBw==,iv:nOoKwf4sJy+wxe3AOPEVbcgaHZp5WKPO8mfbFpLF/DQ=,tag:cmT73lc+Lit8nNQLTJwIpA==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:IA8=,iv:0iOddGNwbItIRbr/VyON6BpMB14hog85k6CexrBdLBQ=,tag:+kvICbzavyQ/Jh3MKiyR7Q==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:LHxBQF3IwF+Q+tH4LBwCaY8hjyyQuXDl8JHZ10ko8y8M1Ul1h6xGcttgV3FLHGdgfAm6HW801iqa/+BRuv+uBGbsogtyyQ0gp1R+kS34RVFzrIXDx/eVbThKp252s1eNKrRoSgF2g0rk4W3tE276KsIqAkonOjr2kbM4DDo/PLRHwQKB2dA4z5yrnVnJg3d6eaE=,iv:V4wOiJYSJEHXW0ji0W+SN/keBD5OtgR4iZbxgZgxGTs=,tag:2rq6pu5bXr9fcOYP1krBPg==,type:str]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:89+9tLaqWHOgPTdRR7dK0uhUaw==,iv:LqrN7y1a+cBynQl8gilpaXRVheWSEoQ1bxFA08hO+Tc=,tag:4Z3aU65qvB3hSIXuA1jwdg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc0N3eEZjRlRBUlMwR1hF
            TCtPcmo4a1ZmS1NtM3J3QTlLNUYzeVhMQmdzCnhIdnM2U3p6cTRqYnVXV1B3ZDZC
            SWFlWVFGYllYQW9xbkFVUkFhS0tNMVUKLS0tIFhZb294V28zYXZaVU85d3hrNmhK
            L0s0QitnVVlXMmp4enMvVlY1TWdyZzAKIbvYN+txK/G2mKIpsEvgyT1GERIi9uFk
            g0zNxfi6RLin9NQhG2c5mUiGOr0tljnziGH36x9gaUSs8STCNffDLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRXdzSGMwUDFYZnZmS3pi
            RHowcU16R1B4MHZaTkpFL1J2RFdvRWwzLzMwCldYN05xWDhYd2pPR1lBeGUrMllU
            QUVoRS82TEtHb2k2b0Z6V3dlbjd1REEKLS0tIExUY2FXN0xtQ3BaTS8zWkZRV3My
            RTRNeFd5NDlSUmd0bWlycDFjZTlxRDQKHKpDEwdn+mesP/dQCN+lrLvSVMbDekZa
            MOrVJtqLeQBXn0H2jfMrNXInEiv1ME9w2embFhqpkZmyWZSl/YVK0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbXhoY20wcmxoNjZSdlk3
            OVhhdWVFYkxBODJ1NmUwVUs2YldSWTZjdnk0CkpXbkRwSnp0L05xMk12UktmcENF
            Z3V1KzQxSW5HNEVMQ2dTOUtId1JDcUUKLS0tIGxtcXJjeXRIbE45bFRnRTF5Y09w
            KzZ3WEZrS05zVjY2M2haVkRWT0hOMEkK0s8oz3dPSJE+ljKN6VHY70nSmFjxFsBd
            ajy17itNFoDFdi09JCZjX1WXCjq7OxmRG0Ae6nXp4hFnHoGpJVncHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:10:47Z"
    mac: ENC[AES256_GCM,data:f12iO+OENvQ7yrEo8htC85rkZxOU6WiY4Es1q6Gqd+ycjBhBjGfzRz5FwWYS3cE8yXyy20MQuzSIOHrUB2k9KXM4xZSDesv9KvpMRenVcbXdUC5yld3yBz0ln97RvCw2ZxZY3SsrqafU01BfNBeIQePhucqF9SvVo9r1bOTvFC8=,iv:enkZA62c7AK7mdYGGV4dlB3uqvwJ5QUtmCOzy4OvziE=,tag:D5lHOt4rPKJd3CYqUbrSEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
