apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:S8gQWcln,iv:4O3EDgB/8K/DvNzPs5RzJ096kGDzAxwHZeKt0+UrL/U=,tag:IgJyzXwgbn5ARPn61yWPjA==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:Kmj6vtQf9ekChDiOZhEoTQ==,iv:xidNCO2Y/VkWkeP5BeWNcA2qS26oHOV/37M2mu1sJJU=,tag:dF/6O29oxi1dzhCfMRWFNA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:9W5cv+j6bEc2/rfftPBFZoPzzw==,iv:BNyEJIrOLSEUH0rUWzI00g+6xwUSuk17pyHA2bZB7K0=,tag:7Mkx32xgeEaaaYeXuF2nhQ==,type:str]
    DB_URL: ENC[AES256_GCM,data:DPm9LQTSMmZsH6saezg28oB+RYFaNS2UHLMxlTQc8HcCluhZWSYrrqUYalNMeoQ2T/wLC4rjYHir+TjBWNQkCd8ysh4kDQ==,iv:VZdwoUwC4Zgb5iJozyVfCTwSQTq3EMh1N4W8y03z7v8=,tag:lobdOQocXI9JXbv3NH6ptA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:aWRJXa/8GqI=,iv:0l9YTPHa5RPcYtblpDsZ0jIPofz7n7del43IS5UB1N0=,tag:SDMzBaop1sZua/5qQ2wY3g==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:wROHPDDxeG5f8Hb3wCDNpGQ70T5ipShjxIiPmFBQh0fWgL4=,iv:rTDV1RvXMi6RrqJiAzRIMzdTwQWHhBi3DXIuLle/PS0=,tag:cCGH3Mz7XLUrORCGHd24ww==,type:str]
    IMMICH_MEDIA_LOCATION: ENC[AES256_GCM,data:72k5ynXwWa6uTubS7YqFGPuvAQ==,iv:qsFXr7LnV2obzXp0mBIX7ioV2cCqzp1XVxXpjHFYixI=,tag:LF5a1G1gNvn0PMSeC+zsIA==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:MB8=,iv:hgTCR60K1DnxZaB/RV6oA/W5lYIn5+2l9mDhZut5CWk=,tag:o6NjN62s5RbP4GGopGpOUQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:uNczSi6W3vG/3TnIpZWG1pCIgy3nAXKynBFLV5gJT65nQR0DZt5umJI2kYoj1ggoacwpcsw9Gj4r+NgqT7ZujUUoydaUGNLxm5jGT9CqDqnLIQFsjchIHyK0OzFyDiugUHzgXkb7zciFSYJyRa5CF+dD+Egn+e17/oVNlc/2jQDN+c8z5plJ9fzguHbb1stxWC8=,iv:KwClnoGPWYZ+bY4QUqEyArK7sAQNF559pZhDyP7Bb+w=,tag:XAWOlvsQVaFz0hzPZyYV0w==,type:str]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:a60c2QvTB4lZjU2a93HjuJE5IQ==,iv:VJjUrzrHVuOYmORz7zE+NHSu1RmvtfzgBVRC1aeTSf0=,tag:f/HsXmhqeSADx03iyzw7jw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNFJEWW1mN0EzSzhjSTdD
            L2lramRrbEc3bnV4bk5CdnJjbFIrSDJHRzFFCnROcGRydm1sTjhWVURhMm9STkcr
            QWFDVDU0cU9TWSs2TXU4R3NEdGdiTmcKLS0tIHVoRHlDWmhQdVQvR2RPb0xoY3BS
            NWpwR1JrdGpuZ0xVbmtHbmZSR2xVQTAK04jTzLE/zL4a2cAc3NjX0pLi4bnBzGWW
            Z72gyRDxm2T8mSxoulVTyWz8El1tNc9MeVKiBsaYDDiqt5Wrr/fVbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0VRWGxCczAxZjF5Y3lH
            anU4TDR5K281Vzg4U29GWlhPT1RlaDBCNnpJCnlBb09YM0UvaC9hbXBvQmtEVGNw
            VzcxaGg5UDc0WFBLdFQ4RXkrejYxVkEKLS0tIEZkRUdRWVp4SGdUS2M4M3U1dVJJ
            OTFmalBONzRpcFArSnI0VVUyNTlUajgKubs8w+atdbl9gASZKboPSbcsJYQXrAf7
            1q9idtzJj2f1rjDtVy7M94WupkBAsgUP5ianh9Z3zLvxpQlkO58Lyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZXpPWEw3WUZXY3ZGTlNr
            UkkySzlMWkdVQkV3dW1lT080eFplcWd6OW5rCjZhRmJvYVhlQ0NzN2lrSGJzc29p
            RDJwditoYTBoenB1dFhEV3MvY1RaNU0KLS0tIHFlOU5UU2hNVWd4U2Z6OEZjZGpz
            Y2R3VitiNkVyOW14b2dQTmJ0UmRaQTgKYES+ntMBet7ewh9HPV7PeeLf14NMYVkt
            luiGG0FbmSGn7N0Hi60Cf9EenJA3WQnfj8pPKjjUSa0blsZghFK0HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T13:46:15Z"
    mac: ENC[AES256_GCM,data:mFdd+q4SAZPBdc2Wj9kWeDV3uauTMlskqZMScFNPsiBl5hnzR6EsP0pKmRLJ5c9GsF9FYVzaRln7SSJfJfaDJVW1FttF31+u9LUbnaFvcWnhs3G1ibU2gKDpwkk1fwd00q5aL6kRutsnNXVOEktLXKN+kT6YUokt7wZWTplg+ig=,iv:6lSwKKHfFCwfM1W0nWaVshsQqL2Z5Tmjo/M1xftEX64=,tag:M0VPRz6DcdizLKw9v1Z0zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
