apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:uczriRwK,iv:tXwkwUwNTFt1mIgdsIratPVzyQ70HMHnVM8ubJZaVgM=,tag:sUUbTH2EzbBjsORqqMyFxw==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:TNF9WlVjdoLrO761wQRgdA==,iv:M0luBhpZ4N0ecPg5bgumvuEtKhjVmV5ZY+dOELlb+XA=,tag:4GxKlyqRP67OE2B/zXtlDw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:P5QbTw5evbdN61kJYuMZ+CXYhw==,iv:7Aw+GqsAKwS4xXLoO3nI0zkJWLuUqcPz3KuiUFrOmk8=,tag:GuChaWaZzkh1kpo1kuFW7A==,type:str]
    DB_URL: ENC[AES256_GCM,data:/N7lvI+937kZB80vvl1JLEH28BuDaNqsUKbeY8p/ehHAkTjI/WFNJ6J3MgRgj4DT6v+Zt3n2RzPy4LA8wW/DrQ/kqF0Zew==,iv:OaVTqzeTk+gP3ZkDmbXzx82gjlOB1P/skjqwyWJx72k=,tag:BCtjJWAK72OvAi3vGqsIGg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:N3OaaI27i78=,iv:J4NhIBqn+YFYasgjfpxzVo6bRSzVWlLx6fJbmpRFrls=,tag:VqbudF66tyk4EnhKy4QAOw==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:9kHS/a0hTKD4UrsQnOaBBjSio39orX4GY5nVWZL4qGAs2Kg=,iv:cOCA29mjqypqCiDmQqXrOqKQNrQrLSCeFhf66V3IicQ=,tag:8mD3kq1wiTZCeFX42XIgRw==,type:str]
    IMMICH_MEDIA_LOCATION: ENC[AES256_GCM,data:b2OVPYjbsMbI7vlKuZBi9SVpvA==,iv:Wcn6o2Ui3VADoMo7pe9uUJxpPk3vtSLEQwS7ukWWzxE=,tag:cZc4djbOX1BPaMo2BOEvDw==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:OLk=,iv:VYquKLkn3mfOYz/jbMgQiocf2pE6goB6hD5xR3P4NlQ=,tag:HXMbUnwa/ZAM7Ys+JSCdOQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:h0bfSHeo+jcXTHnMk5OjvC3ArjJIBQTf7kskgKRCwTOJIN58MUIWBCqZQuBXVd9/fbLA3BNxccm9J/nVnFnpvUcXBI27+Cqr6AlwfVpkdXpakA31osj4J1Gb1ZqWGfRaBbNjHe+k7lj5+HAz0Abg1Sn1n97n9dh6Z5rzEhHrMhmPXou/4Hfh5167jzCGw5l8CHk=,iv:ScYvFpT6HcW0KSZkXxCU3KnZEzDehvyec8OfPIQy+zc=,tag:CtwcgFRw/hT+6wszeZqnSQ==,type:str]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:ctV88GAAmZCFOje0gAKMkHhHJQ==,iv:XzuVURbERjyGrKjsgeYjlxQV9VTAvurwVR9vuy8OAys=,tag:JqhV7v58hU9LkPuvY3DQaw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTzIwK2xsSFExUko4TERT
            eHVXUHNBWUpYTXk5d3llMm41ZFJlZVNoYnpzCkVSMmFzSXdwUzhncDhKRjNnNzBa
            bEMyRGtPbURSakRKV1htaHBCSzFVdncKLS0tIGdoN2JrU2ZjeXYwUk1UMkorSDRt
            bEt6ZElmOG80U2Y2OEoyN1RhZTg2cHMKVX5x2xE62adw6UoMJmp6Fy5wQTaeioOY
            XjPlh4JZS4ClGlyrggmdezjRozH62nPOnnEQQ4MM/2U+Dh3nBRxxJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ejdScGNheHN2d3pya3Bk
            R2tWL2RVNEpaUmMreUl0SjhDSXhCdW5jSFFZCjl5OVVzamJITFhkMDNoYkRzc1BX
            TVowZG5WSEtFZkw1V3MxQkg0SmpJZzQKLS0tIElieVZhUWg1QXVlVnJhYU1uZzJN
            MndyWVo5bDVvVnpPN0lleHZSb2lLd0UKpLBdYWQC8zr/Wki7P/S6hzwVWHOeeu+G
            ZiTYrWVZxh+tCH4XZPWvz1MJN2eAsCdDBJIIRFvVuF/VhYMVMmDITA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYVo0Uk5EWWllejhNL1Ns
            OU9OTTJmVjg4VVlqSEthQm1Rd3F2UTlmaG1jCmJGWVFqeUprKys3RVROd0JnaTkw
            S3RpU2x6VjBNcXJyTWVESW9hRnloemMKLS0tIDhlWGh6UlpSNUhOMFhqRWNta0tp
            dStjMDRpL05OVDlIVEIyQjZ5NzViTzAKZ6Ec5Z6FJ16j2bGlJwOFymNR8n4C3ny1
            5CM5yjKNwtXifU2BEwwd+fcwqMZAkc9OqISI/YTW3ZD5bUjtu/0tZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T01:15:22Z"
    mac: ENC[AES256_GCM,data:hcy5KrDlEzSi2iMohTNA1BDvI10bB5PKp4pBsgwFtmtR/Is7EChDOZPrUTvfDYPfs8OampHy2E94GwYdXFncYUDOdSm2gAEb5SC3KRrVXOF+Mx1O+p4+pspwE/ambtsPitEwJHMbRBDtNOMplSfOQv27v5fpzPoMTHTehzPlbOU=,iv:RHFy4zkUiAKdKRlgo8tgXxB8MkN4Ft9wo21OMAOxGMk=,tag:ivj0Y7v4ni2Jz+EJlSr6kQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
