apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:WBKt4s9A,iv:RKd/VlSdmWNikAJj8fqZhos1M0y4RJ0i//EzGLEaPJg=,tag:OksmzJa8pKVo2Kxov6CUsg==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:5TNSaFGSxkQCWwo3UK3HHg==,iv:L9LQEpzHXx5qYRiFb8hh56ajqHcJ4UJubFHRidO1j5g=,tag:MVOVWTcSrFiG4ZRdrQK+Kw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:f7MdOMkHmyR0TulkioiXJXRmpw==,iv:fNzF7BT25b9cNqRTcU1vrumuRWplNGSULc4hsSusc3A=,tag:3cTZIWXHSi4fnqiapGzesw==,type:str]
    DB_URL: ENC[AES256_GCM,data:wkbw6/MjqM9c9T4CIaiZS/24kXmzzufY1jvkaUiysI3tSOvef4DSUddEwq9WVqdmPLqQBXCXycyhSerb1n/E+X8qIfN/Uw==,iv:PLF0SG9pZVKLQUjM0pxpuhn5Z8jZRZnICDX69eEFVAc=,tag:l2zQXd/i7ad6MqqDRlUONg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:ekCULIx1ok0=,iv:8P9YIDl2Wj/QmJgh4VL9xlnkT3tugvJVtqGNCbVrc8I=,tag:ajM4pFYG/mxYWwIC6Cdcyg==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:jZNvOPsJGxiuTmxVNXnstPe3hwIOyBO4I+13ib5wELTJVog=,iv:1A9J5FmoY1VF6uk/Wjlq05M4O6tyMYG3PnQuPSiS/MM=,tag:kPD/a+P290e/kZdLgF0CYA==,type:str]
    IMMICH_MEDIA_LOCATION: ENC[AES256_GCM,data:PVXWOZSKmaSyeTmq6PfKK1tdHg==,iv:4SYRYP1c7t/OC8eQYQFoswn/JXESyVMb0IIeupw4vxQ=,tag:ShlOsjx5fVbKbBF9MJjZ/A==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:WeE=,iv:etbv5z42NM5SIhMGVrsl3VOsskq+otnKTsQgHKnx5EA=,tag:y+tUriCqenhFTRhTbH7haA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:U8n5QhbyigNrm+z6dTK8Zc7t6vESWV7WSFWD0ChYIjblfP1BJMujPk9/FoIt0AFGdHchuokfYZYw9ug/xVXOHdvUzaFVYtxVuwVUpqLQQvZwFOXlmU9axM7L+Dc3ODHd6njfTCwnklmh2EqpPNQUKynKccBp3KX8dYzjEdxCmog2LcJM8Eyb9pMAgOfped6tMa0=,iv:GdXz27MHzc+BtvxIO7txnEWM8T+mzdxOq+BJyxO3S8E=,tag:Wzrlbzu29bVRtYEUsTovlw==,type:str]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:SnyNCvGGeVJPgoF6m0lXOEDeTA==,iv:8h8OsJU8Sx1F7W3wfkj35rial0PirEDezB+SsIu12+U=,tag:AYs6ovRchE3YDSR5lZjlJw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNHpQS2dId2JWV0x3a000
            Sk15VXdCcU5VZmNSR2doTEdqOHhEOTRyUWdRCmlhbjI1NEFrdzNyVGFKcDZqMzBY
            WFd0VkdDd0xUd0k5RzY2Tjc2S09CdVUKLS0tIEx0VVFyWTZmclpNclQ5bTZqVytQ
            dlJoYjI1UWlKN1dVQU9qME9JRXA1OHMK23vtKZC0maYKSIwcdi7wR5QZeQivwEP7
            0fVs4Dbb91Rvx9MUhq/06WW+o1EAPvQE/OrbNJGvWcl7LyxYV47j7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbzFWSFNFWG5ELzFsaW8y
            QjJIbUFsanlNbEticFBFWDdJd2JxUmc2d213CnpRNEt4dUpEQVFEUTd6MjgrcmF4
            a3dZejFNUE02MGErb1JXVW90Y04rbVkKLS0tIDBxNWpHdWVVSFZpZFA0WG5EVktv
            WTJ2b013bnk2V3BwNVY1THFaYWFUeHcKQvUeP+1ESPMAToNW5F+QqpBWwY+FNBuX
            IXFXBfXjat463xAHFHWRIwW4OApqEO/A0ZJMS+AH/OFDuO75K9AMfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRnFOZ3JOUUFBNXpTU21C
            SUtKZy9DbzM3alFjalpXQUpRa0NTMUFIb3dzCjg0OGlsSjZjcHd3TmZ0cVpPUWoy
            U2VqNHV1dlpOT3lFa3lWVWRqTmZYRmMKLS0tIEZsS0swY1dJbjZvemdKMUJzWEcz
            STNUVkFRN1RZcndtbTlZTFJzdjhMcGsKXKp5Xa7ygjc7+6nLrut2AoSWGBg5b8A7
            DG1Ou5Fi7xWVMzah1ZOCir+0W7fjnG5IYOH9orTUBokpZ/JeMgy3eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:48:55Z"
    mac: ENC[AES256_GCM,data:p06kxBkMyjI2GR8FYl0yckMff7faReB2JFgzRwgTo7iwTTZxzrkEU348RE6mYBMnIQoyh6UTVX2UQkqjCQjir6LSFtFaA6W/cN0b8ZUJDMyX3B4rwDDbpOR4GH6sVpQOiSMN2MydrZcIpIbXpEuXNlWyuIicDKVZ07MW4eDlIfA=,iv:F2PZPZTlKF5/+GBQVw726UiWOBsBclUWlpE5nZouHTg=,tag:fyi4gXJNd8LoCqswyi79Jw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
