apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: keycloak-env
    namespace: apps
stringData:
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:jCUsEWisDKA=,iv:gLJI82lwi+U5I5neWky4kqitnZVyaoLrlc+gMORoXo4=,tag:zhd47LlswaCIgyxbvL9BRw==,type:str]
    db-password: ENC[AES256_GCM,data:6nMQvo1wcRSEc+NF4xN/yQHWUg==,iv:FBJEE+AodEc9eHHCztqnlPpsAnqU/GZe4Jo56VcLAJk=,tag:muaXV8r99qVIqM6nCL0Fpw==,type:str]
    db-username: ENC[AES256_GCM,data:1CIJz5I2OfI=,iv:91cEH/l/kGRPRF9JlcgHveBedgKB9yq7Dt2G+Xo6k6g=,tag:1Pi3M7g3A16r76RL4e1GoA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTXVyTW1mNnFIVkVJVSs1
            dE10U1lBaFZ1ZWljVUQzcXFTWXBTbzBGSVdBCjhpbXFVM2hKNE9QTWVMNklCeDMx
            VkNVUWduYjRuTDNjSnVPcmJZdlNLZ2MKLS0tIE9JV0tyQ09kTHF0bURZWS9QQlVH
            ZmIyZDBBaHhKSmlTWFJ0dGcwN1NXODgKXMMXE8zJWNoXdlvtYAKo9RK56cu9xk6N
            PB0IbM9WRRLm4BgVYHn/nJzb/VTJwjzJfAXEPxZ3lA9y6qx+Xczk7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaTdpdFJEUndPV2F6ZFZh
            eE5iQ0xIdURUWVVIRzZNQVl6MklzeDRwOENNCjIzc21uOE1jNUdtK2RiRTdRUDc4
            MGdnbSt6bFFDTkhKbm5GS3UzTENUWm8KLS0tIDlVNTFhcmVGMC9DcW9TYmo0cEFI
            UG1oTlRxWlV6YXdqMVVteHA2UytVemsKTB9Sl1fFxWbdDG1WV2WB2ebMI1UAaErr
            x6p2x+W2CKFvLERQKfyImUEfZYIacADpsEL4dnMWMZFAJEUK/LAPTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaFgwNUR0MzJYNTFtYWJm
            UTBBWjdGcnM1eExvMnNiY1pZeHNBbVBaRWlnCkdwZVVhVWRqNmhSOVVjOVU3aE8x
            THNvVHI3ZTRCRTdxVXdESWxyQ1BhTzgKLS0tIFFkRHRDWkljZjc2NzdlSG5ndzF1
            V0xIbjRoWi90MnVTLzFEaURWN3RLaGsKzxvVL0RG0dCqgDTWawq36PjDRmCItfoX
            Qs/DLCyBjPF5rrYGbpOcVFquOZKARlvcQCTXanoRkaqrAWi0ygmB3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T01:29:35Z"
    mac: ENC[AES256_GCM,data:hVTYCVo0mz8ak+j0brCcnaci3ASH4kGwLAUfOZVKFKYox74aBPas0pWrw4ZkcI1wo9zTvjdHJO/FTr0Iam3jOQCzo3ltL3x4V7bCBR3Q4KPqWZ3t4kap/rFP3AL8tSkxaAdYPAOCiAF2aa/BaimGODNDKNJP0Mk0yqPYPn8PLZQ=,iv:po8R3hDGxiKMkQCqrosY3j3QLUbpVDjqIcB05p5eD3o=,tag:/nZNu/ZGtv39g2bcwbSzaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
