apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-config
    namespace: apps
stringData:
    config.yaml: ENC[AES256_GCM,data:yFLqDAEqa7zlP+LvHd7G4dTdd3Oz+M0wtelyuIm6XJu3F4qY2tiL9G6LwsrNaNGkpzwoPcFPU7ktmCqoZwn0aY0aAmhdQyppi0e3tmI6Vd6Dd5ICkeAtD0dxzNpYnEp8lHm4f15u7FCv6hvejPovwd1+6p8ST0HBZHCzjOQqWq61cbZtE99zz6C+C4lu4d/Tjdl2oq0UOj4M4nqK/MJvLJmcbYxlU3nLKjHyB61Z0OHD5BeHKmGc29LPHBDprrsUB+qV0JQIB94Fl0S5riXBv0nxBgPWU1NgmbZiBV4LwiYrQynb3+dYxEj+afIr1NIc8TFMJLhyVn9CmkRFFhbrTPWjQ3xEiEgF2p7p/3A3CoF3+auf/rz6lqmFrqfFLWgC4t1liE3hpytOoR7NTMHxcH5OEd3mI5d6jhIw8oUlcNgR6mtaL2QdW7IET1T+KryUMm5yiFj+NDCsKYDoz/fZrNaqaEUIZ0NGOJ2Omg1BNmyQxz1b04ABMGN5x6V6a05BluEEysFguDkhxn/Ba8k41EhV35856ZjoWq7NSiWDgb8se275MtbGFgDfL5MeKM6wn1S7WGjOLYAz2QRutu73GLr1VzVcwIv10IiTLfCTAkq/OBmc3DEU+2nU+tczbBTl/+Xbb4kZvD0HcScDJgr0SFhU3vYY3qYVHmqT+LNObNcUYsNluNFq97PPaJ3YQ+rL6Qs+dVlDVXn3dDK2/oSyU+kVWcWYQzeVwDUX4aUfwsNaU51H1CvnGpxbFAaNNCAfp6i3wVlUuHSyowsmUZJW4LNzmK9xOTJrtCvzh/Vwv1DcWNQMydAopml1AfaEmjVdMHDxQPwXsahSJR1Flhx+1ixNuFyPMNFsaxTS76uT/mdsQZfKT/fJnRA9lCfzvxmbQ6oeg+q6wUF6WrNmRZ7wuYKkn1ZPwvMjt0atTnj7ncV2EeUNyN1AfqyYBSiU3unnNtW2JDjxCp3LGAYVQ7NDg9HIqS4BJdT7VzQg+QYx5AkapFIVc8ddLq32G7ji3X3siFT4a7875dEgI1vruCG6mhU2OM94BRD2GrR+N0SbbbxajRAv9jPzV6m7l9OqEbufu9nxT8bfa7ErZKpr6kLRy/jOyH8YHvKbybCQl85VayVpk6cWlad71a4NtXbZW4c95gNBSb89ZoDPFPZKARj9kU9fHlclWpn9agfcRxoK0i46iny1fEXCZoso7RwHHaNVOjekc7JZsDh+qJkG8wCUXM05TDnNOymXFRZ+89pxhCGUT3Fdpg173WNCHIYPFw==,iv:UuqjorJDKYV9HmqE+qZXilISKTT5R4XiGXLr2fRjaF0=,tag:CYrl/M0Tk6BA7HovyTxBIA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdHVzOXRxMlRIME5IYVpJ
            R3RsaVhyNHEvN0ZNSElIVVlzb2Y2RkJzbEZRCm13R1VhU1JEV2NweVRTc3hTQmJB
            bHFnS2pReUd3Zk11aUFqYXlLT0VVVjgKLS0tIEEvWUhrclcxNEZ3RW55T1czV1lY
            RnZCaFhlQjUwUUZJQUJXS01Mb3YwdTQKsQVSfbgKEDM7k/+d/5aOYXw/mAKZ2g8A
            xi6+Vme0sE9WTKGoOm4ssrXHVM5TnrX+1JPcIWd5Aw3p5q+iRErXMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WHphWGtBQTV2T09pd2ZB
            c2FuT3hVcnk1eEFOM1lmYUpjR0tEdDZ0NFRBCmo0cUNnemZ0ME1VMG1rbHV4UDhG
            K2tMWC9sYWRpUzR1QWFuaE5FaEFISlUKLS0tIDY0QlRLL3ZLN2J2K1dBMmxjS2dB
            UVgwUEc4VjdEMEdNN29wcS8vWm1yWmMK7Yzjd1XnY1Yh1rzCisvCX4xupdpufqWQ
            AW0H4RPQBOqU30DLI3loNrZdLLIibOUtO1kbuHQrLGqZLldI4RawDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaEI2OWpGZXpIVVcvRS93
            RkFGazY1ZkRHVHo0anl3a25iSEJqS1dsN1VFCmhKU25kTnI4S3VMUlJ4V0Rtc1VZ
            RlZXQmoxRU0ybTEya0NiNTYxRFJWaG8KLS0tIExKZ01ONFVkRXduamtTSkFIbk5I
            Z3plUjFxTTlQbDYxazhENklwSkEwZ2sKkXcLDR8m8JWeu+2TPRiEh0y2fehrpK2Q
            pLNOTZK2DfsV36qIdYaQNerfIQK4YSkbQd7cqaHeIWkxvgoXXYjJ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:13:08Z"
    mac: ENC[AES256_GCM,data:9apMcu0Gt4IZEJrsw0f3GAVq+Xe2d0uRwRCFgPXAQT0M8q8/gEmMvvu5OPuPPH0yGIPgt+RO0R859ksOfdYejuYg/9+rD668ya/b5QrBvwMXULuGgLIrnBPT/djxtFW4omEgEh4kDgc8VXQnZC8/DP45ZGDRxE6w/zjjor3GfxA=,iv:i4wcRVr+0cdiMPhmt9KqtIrjwlCfKhOrnPrbdWw9zTY=,tag:4kc2O+iaTTu/uX8AFEVWqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-registration
    namespace: apps
stringData:
    registration.yaml: ENC[AES256_GCM,data:0zgOKf6S3msYKplcupJGAccSkC5YEZfAp/gJufpmVMEm+5JR1y+2t5OFev8mdalvcfYN9I87IeJTSwIIFWSrRClinHAJw55yNdxMLLyz32BybrQU+4KEsePqV9wV9n1OFU+CFg9O97EDq5tvBMtsJMWjWIRmQO9wPnAQUl9rimIDKmXGdBp2SeyrZHgOBrIENqQ9ZY94eizL/BNEfSS0UJEkpXO3IAcbn8VPlkPO7UfgAkX2xEXnBAEzNu42QE1o5muWC4qxTsVp7g1SPbAhW7hQl5YvI6dxfDfogHawOSb4NJ3SPh+9QXAtPrBZz8UQijo4UZ/A44S2XKHH5Ut2LcxOjXpLRZvwiqCPBprRP+xKcL1W8aXc74V0/glqEDfPdlGNcSMimtfjgPO7KwD14hqy/+8ZOZyE+OSnnOJbAF6q384Hu4VFW5M1/cuU1D13LsVklkMBXC+FtOR6pRbqgur1j22QGd4TVbDT4Z5jODOoQTnSx2MC4WG9B8sqCc0cn3u5sN0SwSPfo+QkI34erRI3+tUWdl/R7HpTdW86WLQXnYrp,iv:Jqd6P5iOqjZHYcdYMGUNU4x8AakyEdAvfXK/kLl9dAU=,tag:q0JKyyJour9sgpywgfWL+A==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdHVzOXRxMlRIME5IYVpJ
            R3RsaVhyNHEvN0ZNSElIVVlzb2Y2RkJzbEZRCm13R1VhU1JEV2NweVRTc3hTQmJB
            bHFnS2pReUd3Zk11aUFqYXlLT0VVVjgKLS0tIEEvWUhrclcxNEZ3RW55T1czV1lY
            RnZCaFhlQjUwUUZJQUJXS01Mb3YwdTQKsQVSfbgKEDM7k/+d/5aOYXw/mAKZ2g8A
            xi6+Vme0sE9WTKGoOm4ssrXHVM5TnrX+1JPcIWd5Aw3p5q+iRErXMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WHphWGtBQTV2T09pd2ZB
            c2FuT3hVcnk1eEFOM1lmYUpjR0tEdDZ0NFRBCmo0cUNnemZ0ME1VMG1rbHV4UDhG
            K2tMWC9sYWRpUzR1QWFuaE5FaEFISlUKLS0tIDY0QlRLL3ZLN2J2K1dBMmxjS2dB
            UVgwUEc4VjdEMEdNN29wcS8vWm1yWmMK7Yzjd1XnY1Yh1rzCisvCX4xupdpufqWQ
            AW0H4RPQBOqU30DLI3loNrZdLLIibOUtO1kbuHQrLGqZLldI4RawDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaEI2OWpGZXpIVVcvRS93
            RkFGazY1ZkRHVHo0anl3a25iSEJqS1dsN1VFCmhKU25kTnI4S3VMUlJ4V0Rtc1VZ
            RlZXQmoxRU0ybTEya0NiNTYxRFJWaG8KLS0tIExKZ01ONFVkRXduamtTSkFIbk5I
            Z3plUjFxTTlQbDYxazhENklwSkEwZ2sKkXcLDR8m8JWeu+2TPRiEh0y2fehrpK2Q
            pLNOTZK2DfsV36qIdYaQNerfIQK4YSkbQd7cqaHeIWkxvgoXXYjJ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:13:08Z"
    mac: ENC[AES256_GCM,data:9apMcu0Gt4IZEJrsw0f3GAVq+Xe2d0uRwRCFgPXAQT0M8q8/gEmMvvu5OPuPPH0yGIPgt+RO0R859ksOfdYejuYg/9+rD668ya/b5QrBvwMXULuGgLIrnBPT/djxtFW4omEgEh4kDgc8VXQnZC8/DP45ZGDRxE6w/zjjor3GfxA=,iv:i4wcRVr+0cdiMPhmt9KqtIrjwlCfKhOrnPrbdWw9zTY=,tag:4kc2O+iaTTu/uX8AFEVWqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-env
    namespace: apps
stringData:
    form-secret: ENC[AES256_GCM,data:1D8oRruWXYgVHnaGx/2hpZB/QVweC+h76Ih7YTO4UCOMvJnaIqBSHP2knk0=,iv:DTy2lfkIcjixUY3kSXEsA6RsKFHaDWhInyWQsbSpsxo=,tag:QaXHBRskRkF493kQT/Z9NQ==,type:str]
    macaroon-secret-key: ENC[AES256_GCM,data:I/Zu1JmWnEOYRxuquipytx9oQSfcJLAzojq5jMlJTCq9y1PGEpFnGqrFEog=,iv:SN/1KbmybU2xhGcDlRlXMkWLjEtuJ/xPFriAOuTWV1o=,tag:vFhUgrjvlT/isKaL1DVWrA==,type:str]
    postgres-password: ENC[AES256_GCM,data:TCo1Wo/xWcfZjSMcYdrfR73MMg==,iv:F67KwfReWhkDxmJaPe6MIuWiTHEXeMBSOTKq4gJ5X4A=,tag:5r5FBgQlWxrVJ0xyywQ3Ug==,type:str]
    registration-shared-secret: ENC[AES256_GCM,data:IP8IYjJde+Se92JwnxX1lURuNnK3Ix/ImpPTn8Njl6F4zoEaFXrqLwOhZtQ=,iv:vt0Bd6JtRCYMDTx6h9RipVZztUSPJeXFQOcaIc7zUQ8=,tag:yl+fz/KczTSDtO/qpzyu7g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdHVzOXRxMlRIME5IYVpJ
            R3RsaVhyNHEvN0ZNSElIVVlzb2Y2RkJzbEZRCm13R1VhU1JEV2NweVRTc3hTQmJB
            bHFnS2pReUd3Zk11aUFqYXlLT0VVVjgKLS0tIEEvWUhrclcxNEZ3RW55T1czV1lY
            RnZCaFhlQjUwUUZJQUJXS01Mb3YwdTQKsQVSfbgKEDM7k/+d/5aOYXw/mAKZ2g8A
            xi6+Vme0sE9WTKGoOm4ssrXHVM5TnrX+1JPcIWd5Aw3p5q+iRErXMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WHphWGtBQTV2T09pd2ZB
            c2FuT3hVcnk1eEFOM1lmYUpjR0tEdDZ0NFRBCmo0cUNnemZ0ME1VMG1rbHV4UDhG
            K2tMWC9sYWRpUzR1QWFuaE5FaEFISlUKLS0tIDY0QlRLL3ZLN2J2K1dBMmxjS2dB
            UVgwUEc4VjdEMEdNN29wcS8vWm1yWmMK7Yzjd1XnY1Yh1rzCisvCX4xupdpufqWQ
            AW0H4RPQBOqU30DLI3loNrZdLLIibOUtO1kbuHQrLGqZLldI4RawDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaEI2OWpGZXpIVVcvRS93
            RkFGazY1ZkRHVHo0anl3a25iSEJqS1dsN1VFCmhKU25kTnI4S3VMUlJ4V0Rtc1VZ
            RlZXQmoxRU0ybTEya0NiNTYxRFJWaG8KLS0tIExKZ01ONFVkRXduamtTSkFIbk5I
            Z3plUjFxTTlQbDYxazhENklwSkEwZ2sKkXcLDR8m8JWeu+2TPRiEh0y2fehrpK2Q
            pLNOTZK2DfsV36qIdYaQNerfIQK4YSkbQd7cqaHeIWkxvgoXXYjJ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:13:08Z"
    mac: ENC[AES256_GCM,data:9apMcu0Gt4IZEJrsw0f3GAVq+Xe2d0uRwRCFgPXAQT0M8q8/gEmMvvu5OPuPPH0yGIPgt+RO0R859ksOfdYejuYg/9+rD668ya/b5QrBvwMXULuGgLIrnBPT/djxtFW4omEgEh4kDgc8VXQnZC8/DP45ZGDRxE6w/zjjor3GfxA=,iv:i4wcRVr+0cdiMPhmt9KqtIrjwlCfKhOrnPrbdWw9zTY=,tag:4kc2O+iaTTu/uX8AFEVWqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-signing-key
    namespace: apps
stringData:
    matrix.josevictor.me.key: ENC[AES256_GCM,data:RUNfrgIhF/LlDDkBoMMHdPYZsN5ZMbhmSae0bXiR+GXYY+TpmcUVTieZEm/nVyIdb4OPtO+RASMcXnqPv7vA9V9BjXPU+/My0lr/Qh38WPQwTBKLJOarTxwq2dAoupW2/DFuC/c0rr409YJXr3uonFdDXg4b1jFvc91sFRmuKkp3G3rzGNpazGI0iSlSpuwJ4b3Zd7jG3NYy95y00CAIXSTCAVmYGpTu0XYFSDoKosbBi03KVyZaDXNCqJkqQrUz7TBCXkUrRTKVeBLDrNbGa3DjFOUYiCvNQiaqcGgHlTbIgSX894tJ0nN3nq7ij7c36Y9v8VVrbxdLV0ZwzqsQms0iCxHTutCOskaX7KEPvB8bLDGlEV5Ms7GT5/j5r3Tkw2aKrKrJNDCr3dOw/4FJgF+3P5TSQ5wPWrWJfeQCxPo8V8H5qUB8pMG+Ga4IFwNiACWm3D9rbQ==,iv:YebWlL3RhNDWnHtJf5LkuMxpXieqBJNQX0RiMwEitlY=,tag:5Jxacfw2mugUj5J0C7QnJQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdHVzOXRxMlRIME5IYVpJ
            R3RsaVhyNHEvN0ZNSElIVVlzb2Y2RkJzbEZRCm13R1VhU1JEV2NweVRTc3hTQmJB
            bHFnS2pReUd3Zk11aUFqYXlLT0VVVjgKLS0tIEEvWUhrclcxNEZ3RW55T1czV1lY
            RnZCaFhlQjUwUUZJQUJXS01Mb3YwdTQKsQVSfbgKEDM7k/+d/5aOYXw/mAKZ2g8A
            xi6+Vme0sE9WTKGoOm4ssrXHVM5TnrX+1JPcIWd5Aw3p5q+iRErXMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WHphWGtBQTV2T09pd2ZB
            c2FuT3hVcnk1eEFOM1lmYUpjR0tEdDZ0NFRBCmo0cUNnemZ0ME1VMG1rbHV4UDhG
            K2tMWC9sYWRpUzR1QWFuaE5FaEFISlUKLS0tIDY0QlRLL3ZLN2J2K1dBMmxjS2dB
            UVgwUEc4VjdEMEdNN29wcS8vWm1yWmMK7Yzjd1XnY1Yh1rzCisvCX4xupdpufqWQ
            AW0H4RPQBOqU30DLI3loNrZdLLIibOUtO1kbuHQrLGqZLldI4RawDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaEI2OWpGZXpIVVcvRS93
            RkFGazY1ZkRHVHo0anl3a25iSEJqS1dsN1VFCmhKU25kTnI4S3VMUlJ4V0Rtc1VZ
            RlZXQmoxRU0ybTEya0NiNTYxRFJWaG8KLS0tIExKZ01ONFVkRXduamtTSkFIbk5I
            Z3plUjFxTTlQbDYxazhENklwSkEwZ2sKkXcLDR8m8JWeu+2TPRiEh0y2fehrpK2Q
            pLNOTZK2DfsV36qIdYaQNerfIQK4YSkbQd7cqaHeIWkxvgoXXYjJ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:13:08Z"
    mac: ENC[AES256_GCM,data:9apMcu0Gt4IZEJrsw0f3GAVq+Xe2d0uRwRCFgPXAQT0M8q8/gEmMvvu5OPuPPH0yGIPgt+RO0R859ksOfdYejuYg/9+rD668ya/b5QrBvwMXULuGgLIrnBPT/djxtFW4omEgEh4kDgc8VXQnZC8/DP45ZGDRxE6w/zjjor3GfxA=,iv:i4wcRVr+0cdiMPhmt9KqtIrjwlCfKhOrnPrbdWw9zTY=,tag:4kc2O+iaTTu/uX8AFEVWqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
