apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-config
    namespace: apps
stringData:
    config.yaml: ENC[AES256_GCM,data:A4TVN9Ys3XDJksRs4JctDa8UXSQnQ2ty1NHCnXNX3+mebFTCNzRCTUusIWQfny7bBakllxrnHloAZ051E+IW+e87FP46UEj/inwpDb9nfvGrssDAoO9xHUZtE15WExKLSe9CiTcTGFjAOZRP/obLm/LwbivPIc4jyqahxEeXpGWl2LdxnU0L8BWWs/8b77QoHJ1cV9g7OaX49/X8jETG4yjF2Wqub1pH5+RmCYMx5hO4IqWQwA3YXE8GZanbANuSStnuG7esaSOZryzeBGMjn5InAsCaKnbwilBb45Fsh6P94ETH526IuHIrusFwtvOHr1o992uax2ymis8jNuk+q7mb2ol12AxYvgxNm8R3+gfAVqo2bVmAXKB5yAZzYWudXfuzufzyZ6p+9pFMnydoRBWGiLfzk4Q1mq0k79GXYDavWp4hPc3BdCSp5uYhompwC0UEGfOIhfwYLI1y2Odth/V7pSfiC2BmXONp6yOeVGuBx8k7Awqa3qfwPvOuhyQvASNI3g/8H5zGkSqv0moHG00JkD7sadV6CINFGpo2WSly45C2SVLXT51k6KlLRANQwCoqcICHVZHLCq8F4ZH9jLTzSbHKzUtnyoKoKuY1KyaO88wxef2LvuX4JZnkRY+CH7koqgS/tlCEZV3nx/kaqvwxWaragTaalOlSvodUb2Zio0frEo3M57l4ISckqVIm205fomyLTN7KE5WMoFUniKURUXLE3PJcdy8BlPeuCjn0BpktoH1ZE1y4MnmdZoi7pIOaxUC+j6B27m4GqDdgWTwHgokiTFG22IHd2HtJ6Me0Jrfi9WqDaO5d7a8tGtHaZ9Y+Om1IIJjRs/FtfBF9rTXEjEFEsa0PYmXg1Fj7uegRIQtcky7yKaNGMaJMqjreZ3i1IdZ3Rr7Eltf9hhX2WGybwroZChLgJMDha8t+uRpecQKfkEvhLoz6rXWCOynQkPm8imsHho5ItiUPjQvD9le2nL+TyRCs6Rtr6TaVGzEUMIO58b2FlKNeSp6ec7oAdgJzP/D6jx9sQfRh1WwEhwVjSmrxc58i4M6YpzDaIW1i3xc5J08kKY+vp1x4urNXEzQ7XDkcqd8X0AZgUnVbTz1dcJ29645IPZ7Hd89/hmoTigJAmYRaNWFOptsEtyfbTzjrCDLHnRLewIZH+DiWDko4DAYEqCTxkmSGHmC+AlFMKW3yQOU7JMWiwliErzOzMZkC8H4L+dJZtdnUbzqoJGSqJXo7wp50m72KLpO0S4LGvCgp,iv:jwVyGseJYiIhqCLzDVZxqNyc+X22lVWDFzLJJOg8dWs=,tag:F+AIjAWlN3HF34EKYi2t4A==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RjZZVUJJRERNSFhIKzk0
            SmNTblBtL0dKbEJNTlFZU2FId0lYTkRtTWxJCm9vVjk1WGl4OGJoREhJajJtN3hl
            cWpoVGhSNjZCekJwZGhhdU1aWisreG8KLS0tIG53eFhHUGhsRVdUUVVnLzNGMXVT
            cUc2VlRRbmhnS2hxdzNZOUJYV2FSZGMKieABNCx9qoNqdsKLaA1luZwrHt+LWwz0
            xnEFY28Aat3eHaNjvNkXTBXUL0TVnLcPXrUPTYvUo6JvBeRPyyXhPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSEQ5cmZreGlhUVJrRits
            b1pQOWhxUS8wZ2FCam5wRVNCMTdjaFBxdjNvCnhkL3JEYlY3cExzQkF6cGN0bkM2
            OStBT2FiYzlySTMzRHBZa0ZQN2hXVDgKLS0tIHdLYllCUExibUlUdndEV0NSc0VM
            Y2ZpWitCZ1Q1Z1FyWWZManRCQzFJZHcKqcbAVtvQMDHiiamSe/WyVNqMnKrHYMZi
            PjysZKhoaQ73XTzQ/5zb+KVLfkwUubhg+jcU4CHAUkFjyf80TUGPSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdFJvWkNkQVF0azM5M0k3
            Rlc3dEZUeUM2ME12aEk4QituTGVaMmdFOGdrCkJxMXlpdmdwRHp2TDQwYi9RZWtB
            ZnpWZGxSOTdlL3NVMkhtK1lkcVlERzQKLS0tIG9kZXhoSSt5QkJGaHIydzVVQng1
            bmdkaGpiaUhSb3gyanE4YWRnQThLdzgKP5zHTQN64sNcuOLNbQQX2AvsAoUn6Vat
            wTu6HcE2lFmQ7TR8a4igM/eqeIvON+wmXmIr2ckXDbSO4UHkJDA5fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:02:35Z"
    mac: ENC[AES256_GCM,data:rwTRvyuNZ9Mbgou6qGdQlhfFIo9DBUPce02qAu+X5VaX9ptMcqWXkETGbxjffPz+sx9rbAlVg3KiqWZeijDgNvmRATV/nUQ+LAjLriQUrNo6lLBUE5g49XUEcznm52Omn6t4OM5cgcgBjL7d/TqenndhjNIaZvyA6/sVMPUsbiI=,iv:shOed8LEPjA+4Aw4w4xDpQLTBcmaO51khL0wVOh/cX0=,tag:7vDLgQmt88k68EHPmnmy6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-registration
    namespace: apps
stringData:
    registration.yaml: ENC[AES256_GCM,data:q5EmrlWbj1oUoq4q1bs3LjSlxmaB7k6av+cygC3ysgzO2X/5mQizLe7X1GmEesppRK4eip6C8MiZ3jJk7j3gH6WEO4olM8QjEvy/tUXf7+jncce8srrl/Vh0yiFELYj+FKUl56BCWTH8hqmjiBSq5ujNXZpVkJoUB+iyS1SbBq8x1W9/b/qWma2emM1ePYj7vdYt7FkQTPs0O8Bj9zWAV5WTEg65ui/TQKrZtEanbni1HlqLNpdzEaLZFnNoyoOhEHZ5+dVV1dAHrTnrr3IJxj2Q0BBHdKllgb745+QE8v92z/BVlmDE0YlgJ6yH/FoHvGsxYS5BONAJNpHFX05SUobAKWkilqGwRI6kbq0tVAFNPA/nNUrlu0fDmfcYp1kEPBt/uhm6I8uNW37DcANheLsLRm+Mg9vMGROzByOzQMgLf2fDEp6TbUhqiEV9ItNBNc7Gh9A=,iv:K4p5W126fsOTQjx2U6KBRfbOgMclH4JVq3ZS8Icj3Uk=,tag:idS01nlecIuC6ZU/ax1nmA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RjZZVUJJRERNSFhIKzk0
            SmNTblBtL0dKbEJNTlFZU2FId0lYTkRtTWxJCm9vVjk1WGl4OGJoREhJajJtN3hl
            cWpoVGhSNjZCekJwZGhhdU1aWisreG8KLS0tIG53eFhHUGhsRVdUUVVnLzNGMXVT
            cUc2VlRRbmhnS2hxdzNZOUJYV2FSZGMKieABNCx9qoNqdsKLaA1luZwrHt+LWwz0
            xnEFY28Aat3eHaNjvNkXTBXUL0TVnLcPXrUPTYvUo6JvBeRPyyXhPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSEQ5cmZreGlhUVJrRits
            b1pQOWhxUS8wZ2FCam5wRVNCMTdjaFBxdjNvCnhkL3JEYlY3cExzQkF6cGN0bkM2
            OStBT2FiYzlySTMzRHBZa0ZQN2hXVDgKLS0tIHdLYllCUExibUlUdndEV0NSc0VM
            Y2ZpWitCZ1Q1Z1FyWWZManRCQzFJZHcKqcbAVtvQMDHiiamSe/WyVNqMnKrHYMZi
            PjysZKhoaQ73XTzQ/5zb+KVLfkwUubhg+jcU4CHAUkFjyf80TUGPSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdFJvWkNkQVF0azM5M0k3
            Rlc3dEZUeUM2ME12aEk4QituTGVaMmdFOGdrCkJxMXlpdmdwRHp2TDQwYi9RZWtB
            ZnpWZGxSOTdlL3NVMkhtK1lkcVlERzQKLS0tIG9kZXhoSSt5QkJGaHIydzVVQng1
            bmdkaGpiaUhSb3gyanE4YWRnQThLdzgKP5zHTQN64sNcuOLNbQQX2AvsAoUn6Vat
            wTu6HcE2lFmQ7TR8a4igM/eqeIvON+wmXmIr2ckXDbSO4UHkJDA5fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:02:35Z"
    mac: ENC[AES256_GCM,data:rwTRvyuNZ9Mbgou6qGdQlhfFIo9DBUPce02qAu+X5VaX9ptMcqWXkETGbxjffPz+sx9rbAlVg3KiqWZeijDgNvmRATV/nUQ+LAjLriQUrNo6lLBUE5g49XUEcznm52Omn6t4OM5cgcgBjL7d/TqenndhjNIaZvyA6/sVMPUsbiI=,iv:shOed8LEPjA+4Aw4w4xDpQLTBcmaO51khL0wVOh/cX0=,tag:7vDLgQmt88k68EHPmnmy6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-env
    namespace: apps
stringData:
    form-secret: ENC[AES256_GCM,data:MVI0Yn9fGJ+WKN0c9pXidUTjZRxWP/sikflzRA9vU0WLbHQNRn6q+aX2sL0=,iv:+8/DoreXcAAigZB/hgfE8A4ZablpMczJHJ10MSklE5k=,tag:4r/lxA/lOHn3KsGg6bDjUw==,type:str]
    macaroon-secret-key: ENC[AES256_GCM,data:pbpjnY7QKi+T1UzeLiaIpv2jrC71SZxr0F54QV8gDEteOuWaJAnZQWF0uoU=,iv:de7v4XPO1VYvLyrivs3Irv9ByZN068q7i8LM9RiqYkE=,tag:H6buNTRzhSvHxwUrCxoRvQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:KNygKIvBx8MTRkw+i8ToxOk1qg==,iv:lKB9xkNvo+iIl+6EF/8KTnhYMBQFURgdnHtH+iaRKhI=,tag:E3L9SpGCgbR8ArC9u+a7ow==,type:str]
    registration-shared-secret: ENC[AES256_GCM,data:v4dTfzvZBoILsAjroj3I+LMD++CRkwz/vzHORdXGihHzJQFZ0edSsYVaDyQ=,iv:mg6giScrDAOo7iuwLSl/nyCqeV1Ga/b/NdKC3WSmd3E=,tag:Lq44pHmDGIf+sMltZVpatg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RjZZVUJJRERNSFhIKzk0
            SmNTblBtL0dKbEJNTlFZU2FId0lYTkRtTWxJCm9vVjk1WGl4OGJoREhJajJtN3hl
            cWpoVGhSNjZCekJwZGhhdU1aWisreG8KLS0tIG53eFhHUGhsRVdUUVVnLzNGMXVT
            cUc2VlRRbmhnS2hxdzNZOUJYV2FSZGMKieABNCx9qoNqdsKLaA1luZwrHt+LWwz0
            xnEFY28Aat3eHaNjvNkXTBXUL0TVnLcPXrUPTYvUo6JvBeRPyyXhPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSEQ5cmZreGlhUVJrRits
            b1pQOWhxUS8wZ2FCam5wRVNCMTdjaFBxdjNvCnhkL3JEYlY3cExzQkF6cGN0bkM2
            OStBT2FiYzlySTMzRHBZa0ZQN2hXVDgKLS0tIHdLYllCUExibUlUdndEV0NSc0VM
            Y2ZpWitCZ1Q1Z1FyWWZManRCQzFJZHcKqcbAVtvQMDHiiamSe/WyVNqMnKrHYMZi
            PjysZKhoaQ73XTzQ/5zb+KVLfkwUubhg+jcU4CHAUkFjyf80TUGPSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdFJvWkNkQVF0azM5M0k3
            Rlc3dEZUeUM2ME12aEk4QituTGVaMmdFOGdrCkJxMXlpdmdwRHp2TDQwYi9RZWtB
            ZnpWZGxSOTdlL3NVMkhtK1lkcVlERzQKLS0tIG9kZXhoSSt5QkJGaHIydzVVQng1
            bmdkaGpiaUhSb3gyanE4YWRnQThLdzgKP5zHTQN64sNcuOLNbQQX2AvsAoUn6Vat
            wTu6HcE2lFmQ7TR8a4igM/eqeIvON+wmXmIr2ckXDbSO4UHkJDA5fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:02:35Z"
    mac: ENC[AES256_GCM,data:rwTRvyuNZ9Mbgou6qGdQlhfFIo9DBUPce02qAu+X5VaX9ptMcqWXkETGbxjffPz+sx9rbAlVg3KiqWZeijDgNvmRATV/nUQ+LAjLriQUrNo6lLBUE5g49XUEcznm52Omn6t4OM5cgcgBjL7d/TqenndhjNIaZvyA6/sVMPUsbiI=,iv:shOed8LEPjA+4Aw4w4xDpQLTBcmaO51khL0wVOh/cX0=,tag:7vDLgQmt88k68EHPmnmy6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-signing-key
    namespace: apps
stringData:
    matrix.josevictor.me.key: ENC[AES256_GCM,data:OfBImXqO6SSerKjoiuiYNxyIoj8yLRh8pxDr8g88mwftDeKbhQq9n4DKR4Do4pqLXK4x1FLyp9jQhi5I3mORe5I2lSHOxIxsfpd+iQg2jycU0jx3edG+/2rYuV6gVWVwWJN+I5W7edzRcPgZZdpRiU7uka1lNvaS/qzrCMijRpxJIkoWOiDuGIz25gmswGaDq2MS+HaIi5E/0Z4CWdpjJcQyZSSXvHjWGiXdlW460kESpCfi/Zojca4f7e4z+u/Y6xCr1+zHYj9A9e7K7iQhzbAggcrsMBwEcu+JIHp5ocYUkmd+QyKeDXF+3pZPzRSjiWC1kM96rqyns5Z3vA9T/ZdTX7y19gwGm/TX6mblQtTDhMiZZ/dQEwm6RyOXltfeSVZ/bnV+AMimtpt/4PUIWpKdyqz0S/N5EL4iJgg/8nOf0pa1YGpD0IO2iWGhR6fHrbGqRUWk3A==,iv:EIhVwl1E1KrVRCiViyYrBz0YOSUkVxsQKbrFJ+ByX9k=,tag:ghCoW8bjWextCAJQG70zZA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RjZZVUJJRERNSFhIKzk0
            SmNTblBtL0dKbEJNTlFZU2FId0lYTkRtTWxJCm9vVjk1WGl4OGJoREhJajJtN3hl
            cWpoVGhSNjZCekJwZGhhdU1aWisreG8KLS0tIG53eFhHUGhsRVdUUVVnLzNGMXVT
            cUc2VlRRbmhnS2hxdzNZOUJYV2FSZGMKieABNCx9qoNqdsKLaA1luZwrHt+LWwz0
            xnEFY28Aat3eHaNjvNkXTBXUL0TVnLcPXrUPTYvUo6JvBeRPyyXhPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSEQ5cmZreGlhUVJrRits
            b1pQOWhxUS8wZ2FCam5wRVNCMTdjaFBxdjNvCnhkL3JEYlY3cExzQkF6cGN0bkM2
            OStBT2FiYzlySTMzRHBZa0ZQN2hXVDgKLS0tIHdLYllCUExibUlUdndEV0NSc0VM
            Y2ZpWitCZ1Q1Z1FyWWZManRCQzFJZHcKqcbAVtvQMDHiiamSe/WyVNqMnKrHYMZi
            PjysZKhoaQ73XTzQ/5zb+KVLfkwUubhg+jcU4CHAUkFjyf80TUGPSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdFJvWkNkQVF0azM5M0k3
            Rlc3dEZUeUM2ME12aEk4QituTGVaMmdFOGdrCkJxMXlpdmdwRHp2TDQwYi9RZWtB
            ZnpWZGxSOTdlL3NVMkhtK1lkcVlERzQKLS0tIG9kZXhoSSt5QkJGaHIydzVVQng1
            bmdkaGpiaUhSb3gyanE4YWRnQThLdzgKP5zHTQN64sNcuOLNbQQX2AvsAoUn6Vat
            wTu6HcE2lFmQ7TR8a4igM/eqeIvON+wmXmIr2ckXDbSO4UHkJDA5fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:02:35Z"
    mac: ENC[AES256_GCM,data:rwTRvyuNZ9Mbgou6qGdQlhfFIo9DBUPce02qAu+X5VaX9ptMcqWXkETGbxjffPz+sx9rbAlVg3KiqWZeijDgNvmRATV/nUQ+LAjLriQUrNo6lLBUE5g49XUEcznm52Omn6t4OM5cgcgBjL7d/TqenndhjNIaZvyA6/sVMPUsbiI=,iv:shOed8LEPjA+4Aw4w4xDpQLTBcmaO51khL0wVOh/cX0=,tag:7vDLgQmt88k68EHPmnmy6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
