apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-config
    namespace: apps
stringData:
    config.yaml: ENC[AES256_GCM,data:IZHdyfnCwAD+aPEylHYAG8m2aNg4sVmMsmPr3m9jTMDsaUTNuIbBtNiy1peQdeW1G+6Nf5LQoaZlAeCqUA5/7eT+RcYXDnpLxmbd1kE3MoDTLhoCybHnwZpeawpJym8UC7i8XIs680NKEkNlwVo6wIEtqzvqcyR5FrD08WAr09tBZUVWjpgqSTYFMTbZTfYaMzlc5nnZkpPH9h4w6o9WgkYfcSIY9vvnU7aoulDmaIZXkzTWwhnlU61SttKYdC/U0V/6vASgjHgMqLMJ+xQMgqP+IgKRmXPErEGMUQaMzGN+pmoyqLQLsgNS31AwVJx0/9liCpDPFM0CjUXHg1MwgXu5dFq52moa3cqyeYUtOx4C4nw7XEME8Cg1hoF2Q2MMwImxiWcClhOblSxJF+bT5R6la3DwsGfrhldf2owELHqyUx0wp36yLo007aq2mN5SEBN2eTLuEpw00hhzpyAo9HYvrZkuzEekqt+EDWb2uO3PUYz4F3HS6IRnPwJB04NhxgfabBLlehJUcF/csqWOFu8fBsAWVxqsUKRwytodXKA/4FQ+NO3oYZ1wlRAok6Fc2HndMH39YqA1+v0QLTEs2h7AeuI+SkChDy9ZXKNTS/T2avVy750y7LFTmh08Rq05NT2cAtAS8WD5Zlz7CLvY5B2fJJtrXIOAn8A2STuZCJ4ExTX/nlspdCOc5ZMM/IDV0kYMW/CScb0+yf02Mu2Y9dk4zrf7kRRP9FP4mVet/9h4HmwPEpwz0w8jDWW+QFN+4GSwz1hLIACB7j0GkSKVOwB0IqCAHWo2+KxVUK7f0epsJzt93gmKOtbtF2cxtMUR/i6/LoKci5AQ1BiSWXE2h8bLKssjcR/Nz0gWQd37I16ZnGWMdyVxOe8UUGZsVHMp29wX31M9wUZP+9rbMQhHnlYbrBQKAmWox/4qUwJdG6M/4+XJajBIZqUFKlQymIxN2PBZkQeMFgo8E5ubju1AXx1klC8n0hBnse7nvZXWtTw7Pqn6vkWdvEtI1KL7J0lN7MNMRl5MWMIfAeUopWzZ4yrTvL1viKkYq1ugj8JcJKmyjQDWf2ljVYKgZvWrdjRJZTT5ZDbtPJpqLjSxtQlD+R+LWw4eCCHsmlPdAS0gmocxigKU/cRdvEgknZuG1z9JE4HC+Q9DgTDRiTXY+Tw6mYVzqSBLOKqynX5wfqRCplsQoRFxmMfCjbeoMAQwB0B03vIrlwFSG59WPH+EWxlwbBTOLuBiug4BjUmMa8/oM7405IHl5AF1TwW5vmNWao/836EQwPDk25lNXU1BNo2Trc88cMbih1JqNDRR5I+9cW8=,iv:9YhqKoLkpU5cEGjRJfS9jTTsJQkExQ+WsroH92s6sAM=,tag:zyhuhfikvDwdrNERDV6CwQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYVpKYVljUzZYSXI5MFdY
            alQwUFgxRGFGSkZUSEVHdFNuR2JRV2prQlZNCkZUakYxc2tTN0lXWXNkTCtaVUlW
            b3F0S01MbWFSNHVlUnIzRHRwOGxaNlUKLS0tIFh0cTZkQjVScXRSVXl4K0pzVVpO
            QjdoaTFBN0UzR1Q2UHNqVWRkRTlRSDgKoKaou9EA6oA4igLwhTUCgb6j0YcCtJGt
            EyP0ETSuQayMhgpaN5huvUJe2uO/tn9KOiDxEB0B1E1X5obqYjn8ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN3NyU1lvdHNEVjdIcDlI
            Sm0yc0QwdUl3SFNrK2VvMEJpTldCMFlxNG5NCmUvTC9zcGhLb0dBSmgrVmVjUFl4
            RDhuNEdIKzZrYkcrRDlvd1ZuWGNDSzAKLS0tIGcybzlCdkdFb1ZlR2F2QmFPVTF4
            YlE1OHpWMXo1V2VZZytMVGw2WUJIUncKCkrzY2jcyZXp7fCvvyyf0C4gNinz6oOc
            pyP/FjWP7OcF+GVqxAkTq5htnOLoJYlknaKrcOYOqNVbo60jGYd2lA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRXNyYUo0MDlUWDdMSGRT
            TGZKL01keXpYby9lbm1RcjVPOWhuQ2lxZm44CnBoM0xWVzNIVXBIc2wyY2dSVE96
            cTd2Z1hMWThyZUlCbWZYVkw3MVBoc1UKLS0tIFRUUldjc1VISFVURHM3YjJ4aXlB
            cVFrLzlGa0xWUU1CaUwydTRTT0VxMDgKVwAYFaA3h27Fc54ewkggWGOoFXnEphAR
            oxE6ouBJaTihG+yUtbyyzzagff3IE2rpmkmse4JxJC7ivA8Dzdh93Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T01:27:13Z"
    mac: ENC[AES256_GCM,data:DYDRfO8HPlUhemzGhb4vLhTreKZ62SoRufJv5tKSMbVm2g8Qp3MGchZM1+KCo16/qC5xCF5Weh3VRrjphozQ74moiTerWS3L5ZCXqqAQYnXNQ23CZIir8PIo4GTUdI6rZvvg3uw+CGvnT5BRpQuJoDgHkfQwuqEmg4AOGk5UBKE=,iv:p+T4n1O4hd+muUwncd1VHyyeJiiGIbJsnUrKTHj7m0M=,tag:iojTRGCrDcewh4YQQuqLZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-registration
    namespace: apps
stringData:
    registration.yaml: ENC[AES256_GCM,data:IsL1P1259VYMQJY1/6ubyxhI8BCNV6XdjBeabNEpWPFS6aOXzpv3ediE1vOqAGy4oeJQFlfYnQjfbFwSkDfXVh6HH1xujtMu/nXb7S2wS9UTHGO4LT76d3qAg5yfhGxAndMCp/6QLELtC0lEdoV8scPo33eI4fAJ7ajRmKWwkn7kRpdGV+CCh9AomshBK1vlZ915Mf7G9sWAfxqfouAiNiYj813bedSulo5NipcIRgCUmTBSd4FokEZhOUHZdZDh/8KMKWOg37wwS6/YGj8XBxdQeLt/jQLhWwnAQ4zaeNRql7bq3UYXp0rcb3QKUiJxUj7rpNIHZ19bknMZq+jkZPnUXy1I7O9EjjEghLdG4hxNOuSq/rq+f98mcZffg6ym096BFm5MKHDgJ4QH8dSBAJL1n2BFlV50wR1huOc3sjsYlps9RVmo4qlWvlHCvNC3+wLOeOC0cKm4yLYl5Ni1Ab9jUJbvXUbB6M8FYvRR1xunebo6Dbo3ciJ47CZAlMgkxq2QTUdSBhTsbwxyMtd7olQ0qImNQ69PasrLIhoS0Ax4QvCs,iv:p4p8tBYT40QY4CzaU1xLlwqpT+WYoSdnhtPm4FrrOw8=,tag:/M2dPySgz5Z2osSgQ3BXAg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYVpKYVljUzZYSXI5MFdY
            alQwUFgxRGFGSkZUSEVHdFNuR2JRV2prQlZNCkZUakYxc2tTN0lXWXNkTCtaVUlW
            b3F0S01MbWFSNHVlUnIzRHRwOGxaNlUKLS0tIFh0cTZkQjVScXRSVXl4K0pzVVpO
            QjdoaTFBN0UzR1Q2UHNqVWRkRTlRSDgKoKaou9EA6oA4igLwhTUCgb6j0YcCtJGt
            EyP0ETSuQayMhgpaN5huvUJe2uO/tn9KOiDxEB0B1E1X5obqYjn8ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN3NyU1lvdHNEVjdIcDlI
            Sm0yc0QwdUl3SFNrK2VvMEJpTldCMFlxNG5NCmUvTC9zcGhLb0dBSmgrVmVjUFl4
            RDhuNEdIKzZrYkcrRDlvd1ZuWGNDSzAKLS0tIGcybzlCdkdFb1ZlR2F2QmFPVTF4
            YlE1OHpWMXo1V2VZZytMVGw2WUJIUncKCkrzY2jcyZXp7fCvvyyf0C4gNinz6oOc
            pyP/FjWP7OcF+GVqxAkTq5htnOLoJYlknaKrcOYOqNVbo60jGYd2lA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRXNyYUo0MDlUWDdMSGRT
            TGZKL01keXpYby9lbm1RcjVPOWhuQ2lxZm44CnBoM0xWVzNIVXBIc2wyY2dSVE96
            cTd2Z1hMWThyZUlCbWZYVkw3MVBoc1UKLS0tIFRUUldjc1VISFVURHM3YjJ4aXlB
            cVFrLzlGa0xWUU1CaUwydTRTT0VxMDgKVwAYFaA3h27Fc54ewkggWGOoFXnEphAR
            oxE6ouBJaTihG+yUtbyyzzagff3IE2rpmkmse4JxJC7ivA8Dzdh93Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T01:27:13Z"
    mac: ENC[AES256_GCM,data:DYDRfO8HPlUhemzGhb4vLhTreKZ62SoRufJv5tKSMbVm2g8Qp3MGchZM1+KCo16/qC5xCF5Weh3VRrjphozQ74moiTerWS3L5ZCXqqAQYnXNQ23CZIir8PIo4GTUdI6rZvvg3uw+CGvnT5BRpQuJoDgHkfQwuqEmg4AOGk5UBKE=,iv:p+T4n1O4hd+muUwncd1VHyyeJiiGIbJsnUrKTHj7m0M=,tag:iojTRGCrDcewh4YQQuqLZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-env
    namespace: apps
stringData:
    form-secret: ENC[AES256_GCM,data:o1654FfXG4uelNDw3IITmHpX2DP1DUyOJxI+zYsfcfOPJfHbQvR2WXKiYiQ=,iv:atGm9ws0jkefbIRjAyMkyRp7whiYEZ+P0C/3ZQQY7wg=,tag:Y3PS7Eb7en5tAYtkSqvfyA==,type:str]
    macaroon-secret-key: ENC[AES256_GCM,data:mz3Xzo71VqL7UHyl/ifoms/CvFaDn/wFQS+NxBCo29P1mU2Yotq7VmQ/LMQ=,iv:NGbXaddvKUN8/HF6hxFZVDo8kAy3dUn6YIvL7gsJt+M=,tag:lwe2/gdx2csaxa1kGJyGow==,type:str]
    postgres-password: ENC[AES256_GCM,data:tghTYdC3D3yueq1DG34/AWPwcA==,iv:0QH+VEnZdgzAIXQLsKXD/PdJ6qxFZD2cV1VzDfSdvsM=,tag:teHB/8AQRXQyz678f8tFmQ==,type:str]
    registration-shared-secret: ENC[AES256_GCM,data:wp/v+/+ZRm4+AQBRt9PyKW9Sg/bdx74vwS9oRA/pgh/eOAzA4Azy5JBa/ts=,iv:LRflkRA251T4gqw8qK9g9fJ99GB8fEsKFq0PlIDVFlI=,tag:5++HKtQKdsizJ0AHMAIkDA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYVpKYVljUzZYSXI5MFdY
            alQwUFgxRGFGSkZUSEVHdFNuR2JRV2prQlZNCkZUakYxc2tTN0lXWXNkTCtaVUlW
            b3F0S01MbWFSNHVlUnIzRHRwOGxaNlUKLS0tIFh0cTZkQjVScXRSVXl4K0pzVVpO
            QjdoaTFBN0UzR1Q2UHNqVWRkRTlRSDgKoKaou9EA6oA4igLwhTUCgb6j0YcCtJGt
            EyP0ETSuQayMhgpaN5huvUJe2uO/tn9KOiDxEB0B1E1X5obqYjn8ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN3NyU1lvdHNEVjdIcDlI
            Sm0yc0QwdUl3SFNrK2VvMEJpTldCMFlxNG5NCmUvTC9zcGhLb0dBSmgrVmVjUFl4
            RDhuNEdIKzZrYkcrRDlvd1ZuWGNDSzAKLS0tIGcybzlCdkdFb1ZlR2F2QmFPVTF4
            YlE1OHpWMXo1V2VZZytMVGw2WUJIUncKCkrzY2jcyZXp7fCvvyyf0C4gNinz6oOc
            pyP/FjWP7OcF+GVqxAkTq5htnOLoJYlknaKrcOYOqNVbo60jGYd2lA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRXNyYUo0MDlUWDdMSGRT
            TGZKL01keXpYby9lbm1RcjVPOWhuQ2lxZm44CnBoM0xWVzNIVXBIc2wyY2dSVE96
            cTd2Z1hMWThyZUlCbWZYVkw3MVBoc1UKLS0tIFRUUldjc1VISFVURHM3YjJ4aXlB
            cVFrLzlGa0xWUU1CaUwydTRTT0VxMDgKVwAYFaA3h27Fc54ewkggWGOoFXnEphAR
            oxE6ouBJaTihG+yUtbyyzzagff3IE2rpmkmse4JxJC7ivA8Dzdh93Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T01:27:13Z"
    mac: ENC[AES256_GCM,data:DYDRfO8HPlUhemzGhb4vLhTreKZ62SoRufJv5tKSMbVm2g8Qp3MGchZM1+KCo16/qC5xCF5Weh3VRrjphozQ74moiTerWS3L5ZCXqqAQYnXNQ23CZIir8PIo4GTUdI6rZvvg3uw+CGvnT5BRpQuJoDgHkfQwuqEmg4AOGk5UBKE=,iv:p+T4n1O4hd+muUwncd1VHyyeJiiGIbJsnUrKTHj7m0M=,tag:iojTRGCrDcewh4YQQuqLZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-signing-key
    namespace: apps
stringData:
    matrix.josevictor.me.key: ENC[AES256_GCM,data:WL/O104tdRj+qol2/MpDpxez2DAssx4mEi3mnM1c9LThU41tG1Ef8MlV5ZKS7jwm1lX3Rq65//ESzZWugJMXvqYXTWtUjyepLrovdxU+cufIL+okLUwru36ZxM15cgh+a1tB1Oh5VV37B4621AWWc8IS/YFem291dYEsaaxgybqBxOTICWAXoTtKm52fzEacLbD3rs9FfPrLGSocL67D+S3rdrv3RL53edvpCpqvDmKA5xH8ULTs8CEIZ/csacTkZmjKGkUrkiyY+CZ9au/Be+Agynh7vkSr1lEMn8fV7z2asJ/CkIBKrIme02+i+F+YwP8bKRlgXni5ehgVef21bHfCO40hnJfoIJ2QWHWXxEh9SDzUX5wrCkGl1NPZ4/CFD3oLEiT79++FpbWLWFm7S5mo6A6qOKnWEyA9IFn3jZuQ/MjIj2RLOqhW+ThDsIyaEoRmY70YOA==,iv:nVTd4+ihivFdswHxEWD40Y2ApG/sM0O54TP9ms6Rl2c=,tag:YyQNY6DGhBtxKQZ0GztYtQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYVpKYVljUzZYSXI5MFdY
            alQwUFgxRGFGSkZUSEVHdFNuR2JRV2prQlZNCkZUakYxc2tTN0lXWXNkTCtaVUlW
            b3F0S01MbWFSNHVlUnIzRHRwOGxaNlUKLS0tIFh0cTZkQjVScXRSVXl4K0pzVVpO
            QjdoaTFBN0UzR1Q2UHNqVWRkRTlRSDgKoKaou9EA6oA4igLwhTUCgb6j0YcCtJGt
            EyP0ETSuQayMhgpaN5huvUJe2uO/tn9KOiDxEB0B1E1X5obqYjn8ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN3NyU1lvdHNEVjdIcDlI
            Sm0yc0QwdUl3SFNrK2VvMEJpTldCMFlxNG5NCmUvTC9zcGhLb0dBSmgrVmVjUFl4
            RDhuNEdIKzZrYkcrRDlvd1ZuWGNDSzAKLS0tIGcybzlCdkdFb1ZlR2F2QmFPVTF4
            YlE1OHpWMXo1V2VZZytMVGw2WUJIUncKCkrzY2jcyZXp7fCvvyyf0C4gNinz6oOc
            pyP/FjWP7OcF+GVqxAkTq5htnOLoJYlknaKrcOYOqNVbo60jGYd2lA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRXNyYUo0MDlUWDdMSGRT
            TGZKL01keXpYby9lbm1RcjVPOWhuQ2lxZm44CnBoM0xWVzNIVXBIc2wyY2dSVE96
            cTd2Z1hMWThyZUlCbWZYVkw3MVBoc1UKLS0tIFRUUldjc1VISFVURHM3YjJ4aXlB
            cVFrLzlGa0xWUU1CaUwydTRTT0VxMDgKVwAYFaA3h27Fc54ewkggWGOoFXnEphAR
            oxE6ouBJaTihG+yUtbyyzzagff3IE2rpmkmse4JxJC7ivA8Dzdh93Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T01:27:13Z"
    mac: ENC[AES256_GCM,data:DYDRfO8HPlUhemzGhb4vLhTreKZ62SoRufJv5tKSMbVm2g8Qp3MGchZM1+KCo16/qC5xCF5Weh3VRrjphozQ74moiTerWS3L5ZCXqqAQYnXNQ23CZIir8PIo4GTUdI6rZvvg3uw+CGvnT5BRpQuJoDgHkfQwuqEmg4AOGk5UBKE=,iv:p+T4n1O4hd+muUwncd1VHyyeJiiGIbJsnUrKTHj7m0M=,tag:iojTRGCrDcewh4YQQuqLZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
