apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-config
    namespace: apps
stringData:
    config.yaml: ENC[AES256_GCM,data:C+//UkE0Uqfr3Z6vWnnMxuRyP49IOcxcu0PzFW1LfzBeFabMA8qWKxknoiTRLFSOP9tfyUytZpdPvmuXpL3DeGAmF4wqefCSPfjSBWS2SeE12UVSTErU9nI+PX95yCr/pnbsJYb4vHhtf43KYSieSp0k1ieacrl0lGIdNsfmC/wv+051d774Pmdh5qKL2XV4IMtySak3gySTqoHPJz2s4EPoEIW4bf7jfIrw9vXn9bKCAGqqUKTW+hBmlHepSunQ/vm5FDTiqbU06Mp+w8fvQt0bdqbA0HRh3Ph4xKVbXKAkAIi/r/3tJyryo4wssMehY6deDeSCwEyqM8Z8entWCGR4ixpafpppG4sFRjAFnQcCh5kXa2rOdX9NaonilGDf6H7SJ6sJ4qA+6F+NgJ2s09S91Fa7aXMjKWboybJ3hVxWQj+gvSjKp2tJTplARmUSMNPr0dBC9aFkbLAure0G4ibScw1LzoQrg1Bj2fvQW6P0vgzy8Q1tICMasPnDjAtDiNwLPINR1EB/cd66Sh5+9ECRnP+udn6GbPN6DhgVHKh9gqOfvdXF2euEmxf/YRpPjOwbQAEOJXQimpBr66k3FGn8SUh3/JSUmVUuL+XDa+8OYbTbJYSzdZevQbWsxfTBow3d1O7hTtjAyFLFwI9uJHoWMH2KzsgG72LPJIB+ZwGUIT5cGA6FhteRMfIVCvpu/DkwtaxnDoekhBh0Tz6WMlQPORdeE45YfQi2xhcsainGKtQy4XxxYftyQS2DTatol3E9XM0GPenMCAZYTzf7SfjJpbaUaA3TDO49lObli5SBOkoCwss28AQ/RjqoVKF/WHS2aVF9ylpydtiWaKBTULOf9eShbH8HyNVayzl5Pf+KJRMtkWNBxE69WSBZFbep1kVdn+QunARe1MU8XhDYDaS70+OY19D6SokAup+919qO+3C/LsVp15yQ83NWTHyXsROcpvLKQBo5hf7ctKMCizS5uBQT3EMCmkqBAeo4E4kn5f/UcWsPKwjG84ObjuXNM251mphBHljClZiUO3yMmxKKNJBNHNJyA+AWVXdiDrntysBPcAcyHzXrwblNiJeCyfpNgcAvJs4dri713ZNep/RGX3p+yYX0/4eFWZeGU4dxZqApJtD5viBAo9dDzqG5TFtOImFT9wM2mCQEFsIAbZHIIpVSNwsslfQ9DHd06EpEoFw+lms1/DfMNjCuR8MG3g3ShxNcADq2p4TuD0i3DUAbox74x/+373L64axWObuvnferXisPtgbtu9GrTGBDKbhYoE7/B15E4GkK/8BV4f0GHPmf948HLAdM/vi7kSYED+45jcIMYroZY1PwKBZrQchtZcJDgUvzf1zx0hKPl9HAJbF7ChAX0x4ZoFjgcTA+eECuOudhjmHllZczsXV1oXHdsFzB7J4dReuVr66w7FA6ncHGtpcbe3Y9DeO0vOlcFlu91iJ1rrp39ywuNksl6Ulzzau5JuXMqZqRQA3iCJ1GOZdRLaBRJmDKKBsxk2ogHQWRzSoboHevQ60crqkNjZBRsvDEVDfPXqtGjwqAG+v+O9pHc/CCW5gc04E5xQOYoH/oCdSU3pqVDZpO24ojoUF6tNubkG1NwC72a8eEGQjakBXoiv9tp+N/xd0MMCz9c5DWSBeTUHRzHs1MQCy1CG4LVnEh9cBnGZ42EGhh8EWXvKM85gZiazUjn3SaupUbgTLewHquD25JAVYBjzTCHlRPKMcak7yH4SMWHzMSja7Ih5OJWnSnE/bQOIZUGAuVjnYo2ngvcg3FNXE/L2Mxsgt8wCktE/jQlogmJtJI8FB7cCdQl8L06RDLO3gK5DS2pCDPtPYqZEfiFL86iV3HE8XQvmMdZqKb2m8KNT64Q1au4c2E/ncvcbGzdMOuCXLPwslrCwYYfR+4biY551qA3jMVPYi5htXrdWczxCrdzI01eMPIn1reREHordL+zlBZ/YXfXz5cZraZ01SimOvdUzzTYApGsW9OmqkIJgvJR2JGC9UhpcKDzaw5exbwMdLRRNNEtyx9t+50pbqSmayzulauo16iyy5qlSor1Xy3OrBoRZCGTe+D4Xk54TmZRsCgXdGsme+tnIsUXl/YWY6xk2J8YjRB5aCKfFKWQ7ZuTOt9d3NcxueSCoRnUdiAJud8FPP8mkPc/wHpPrLOpFTqWOpJJoUQMFRTv1uvBrClreKI0CxygYHFn9pmUdhaz9ZZpla+fwB5wQguiGEW2f17ld99lUta2gNqWCteTYklAiBUKorvPaGBmrR3HuJM7HZwDDTySjIkpxTEo0M4A6tNWZjZIFxBAxAYHtYdNIjyAdaqpOT0NlUc5iFzg/pjeu9Tk3CrZP+YtZWZ55/RItNd2fsjBoYt6A7qdKEkUXWcRP5keJKkmX4A1aOycpAp9d2T6aZhfXcXrsDBeQ18poXpXg8hmttJogzziX1R3M+KtVQEGu7mGfqORwJYR6O04mqkvATSMZmySzD4eT+6EwuKBGt5CMwDElrMwFcu3twg/eQov1FomZhCANhr6BfidAn2kR9hYoerpIJFHq7tE9ZuD7TlJeTdIx/3serbsj5XfQk2rAT6VycGPI5OQznAjeFQPlJ1G6zozT6AZ30ZsCq2Hmy0ZIC1HDta/YFbmRaj9FK6Clebhhnk7YeGp0wbE+MJL0CbCz5V6QmpCLK7nVZ8HRxY2IdwzPaNVBpMx18Arjj4WVuPd6nUIfNbAwwsSkOCRUXEn6NZyGDUS+7ZyNllW9Y/AsfsMUa/MVClta1DKUSMSsEWvvVzSXAIZBls,iv:sBfk+HuTKEu/CzRHzDHjP324IYl2FKAF0nH+ggJohPo=,tag:DPMdiBoEJ1RYXzfI7dYmNw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbUEvYjl2WlowUENtbGxR
            M21adVAxbVMvclJwZG9rdGViRldwbDA3TUVFCkU5K1lnWUtueGYyQVRFdXRiWThC
            QmxKS0ttM01wY0ExNm9QT2dDYUU1NE0KLS0tIHFpb3kyZUNqejB4L25jMENLZXFY
            ckdVV0xGVEo2Q2p5eEVLNHJUdG1abG8KelQ3KNQkbwH6s+pooxvUetGBBVw5L0Kc
            ZyKNKuuXnYm9zyU5fe4PyORWNi+IcI74r7OOrV72kBUogyFUwksA8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGREhLYm5vWFhtUnNNczho
            d25JekNBb1NKQTduQTcyemdmVVpqT1N1bFZrCk5NMDlScUlKb0VySjhqZlRxRURO
            b2VOdFQ2dUYzaWFTS0JCREZ1am9YRUkKLS0tIHpJa002WFZ5K0pRTXVyVVZpbHU5
            eUNvVnFYVUVtT0krT0dWNkZ4SUd4YzAKDGGcjQA6QCvb3BvwZmArkcfzn3v1CZJI
            oHdeNtUWGOKl1creVclziDYQmSCa5vkKCyt2/Xub9IOb7+l1cB2JwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBazBleTVHR3dJd2xHUERw
            SnVSSEhIMDgwcWJtOHZpYjRGOGgxemdSOWpJCkJLUHBoM28yZitVbkkwUUxvYm1D
            R3Z6eFZQZ2tubEVKR0pqczNGRWdzQnMKLS0tIDl1bWg3R0RMbFd6WFprZWdDZjhv
            Smg3VEM5dE0zZjEzMVF1U3BZK296U28Ks9SL3WlaPBqdCnBedPbtq+KI1OYvOV6h
            UyEwK4/MVnhXbDSDBQTUbdyx4KjkaOUcN3mgRIKYIEkPHl/nRtxnBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:45:40Z"
    mac: ENC[AES256_GCM,data:h2J7keObA5jOMWiPRlRftd0Ate4ZRrH/eSjVyL2DiF7ogrXtmoXgVw+bTxMZJU8AFUFnMwKCCzLt0yONLFVDmykMhG31zMWqHEhGnp0mNyLEkIQUvsLFDaRtTnykj7olxHAWHRmPmQctyVHcJq4vN+3gNgpfCGtAQdWD1tWEZKs=,iv:I7dubb5oAMH5djKMDQE3WWZqClxOxq0PcCv9RtB7+ws=,tag:VK2vMas3gRd3lsxgTv9vQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-registration
    namespace: apps
stringData:
    registration.yaml: ENC[AES256_GCM,data:GJUuuh0SEXUddGLYhtSPmWSNggbUMPW5ndnIuWNOq/+QkfsO2rjBhg4rKVQiDW4H5s9hNGbVOpqdgz3kzHW0iq7gxXmE+v2V/78zqTUDArmwGvmHfa/INvPQwQW2gDrNyEJZnK9o3HWdsQ5BenyxKhXfZclvTBCcZ1ay1GNLCmS29+bwxvZeSo/2j5jt1hFl+mniBTZCU/33xNI5NJ5Gg4D5E0GrukaDtCv79vzFKhLtmEn/CBC4A6tjY/iX/fN0/4UtwjR7VbvPxZXcHGs8h2wZI7ey8+XzdR2iR1fCfAZgij0/iaiG/GXtBhbI3x5XGvQewZldgXJgtDeTRHqYFOLe5tqGBXKBhxm0q77EmigL8HdmNJsrMk5SGMFB/xRBnM3QR6TDVqD3QV1i9QplEDOyXfyk4Lp1vC3DraoYAQFQ7RODQAppLroxwOnjWIGb/SVRj/KKkL+oOKlo+74O4hTCTLZYoRjzInTEDSe3kZt0pO6C2Rp4R41pumxamLmHmYaP06roHoiexg6FihAtSNaKmgemZ8tXEYMmmv+J6POriYyE,iv:MEUIQalwUqAOTgntkfSt0zVN+dyHRbhZsNTXxWGgNTc=,tag:MhqGfabOM/oVZK2VOrcUeg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbUEvYjl2WlowUENtbGxR
            M21adVAxbVMvclJwZG9rdGViRldwbDA3TUVFCkU5K1lnWUtueGYyQVRFdXRiWThC
            QmxKS0ttM01wY0ExNm9QT2dDYUU1NE0KLS0tIHFpb3kyZUNqejB4L25jMENLZXFY
            ckdVV0xGVEo2Q2p5eEVLNHJUdG1abG8KelQ3KNQkbwH6s+pooxvUetGBBVw5L0Kc
            ZyKNKuuXnYm9zyU5fe4PyORWNi+IcI74r7OOrV72kBUogyFUwksA8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGREhLYm5vWFhtUnNNczho
            d25JekNBb1NKQTduQTcyemdmVVpqT1N1bFZrCk5NMDlScUlKb0VySjhqZlRxRURO
            b2VOdFQ2dUYzaWFTS0JCREZ1am9YRUkKLS0tIHpJa002WFZ5K0pRTXVyVVZpbHU5
            eUNvVnFYVUVtT0krT0dWNkZ4SUd4YzAKDGGcjQA6QCvb3BvwZmArkcfzn3v1CZJI
            oHdeNtUWGOKl1creVclziDYQmSCa5vkKCyt2/Xub9IOb7+l1cB2JwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBazBleTVHR3dJd2xHUERw
            SnVSSEhIMDgwcWJtOHZpYjRGOGgxemdSOWpJCkJLUHBoM28yZitVbkkwUUxvYm1D
            R3Z6eFZQZ2tubEVKR0pqczNGRWdzQnMKLS0tIDl1bWg3R0RMbFd6WFprZWdDZjhv
            Smg3VEM5dE0zZjEzMVF1U3BZK296U28Ks9SL3WlaPBqdCnBedPbtq+KI1OYvOV6h
            UyEwK4/MVnhXbDSDBQTUbdyx4KjkaOUcN3mgRIKYIEkPHl/nRtxnBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:45:40Z"
    mac: ENC[AES256_GCM,data:h2J7keObA5jOMWiPRlRftd0Ate4ZRrH/eSjVyL2DiF7ogrXtmoXgVw+bTxMZJU8AFUFnMwKCCzLt0yONLFVDmykMhG31zMWqHEhGnp0mNyLEkIQUvsLFDaRtTnykj7olxHAWHRmPmQctyVHcJq4vN+3gNgpfCGtAQdWD1tWEZKs=,iv:I7dubb5oAMH5djKMDQE3WWZqClxOxq0PcCv9RtB7+ws=,tag:VK2vMas3gRd3lsxgTv9vQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-env
    namespace: apps
stringData:
    form-secret: ENC[AES256_GCM,data:o2Dec1VNuGb5SgmFhkX5bG61b6pJ7I9pp732E/ZoI7+ZqZP34yImygsk0BU=,iv:XSmgzK3ckXyMDMZQ/rLuf86SJ5jB1p9xs40Ton2SJDI=,tag:T5etLMj7+vJIKHFKL7F5Ew==,type:str]
    macaroon-secret-key: ENC[AES256_GCM,data:bV02BUrWDqqU75oQIiVeVZg2AQCNvwrlWB9MIOD34tDlD3+LbU9JaJ18gjQ=,iv:fI/nsmQgnJzrBbn5HdopWqFRsNCAX7BisrkUUOBEqZ0=,tag:jrPo//ZodiO2mN4dVJwoWw==,type:str]
    postgres-password: ENC[AES256_GCM,data:jHDb3YTARYXWMv4JM5SBKkoT6Q==,iv:DpvGFManHW2hJbprQw92fBriS0KEJ+iCoK46bVoLWfE=,tag:1cWC8F/GniSfcpGzTMxPEg==,type:str]
    registration-shared-secret: ENC[AES256_GCM,data:a31YqOWuUV2B8j7RaZVOVLPBcBSpClVLGeFt6Z1t+HElMNb9GHtTgnb2he8=,iv:ZqAuQ0THfSvcF9f8wCiM/XJ4rorLtXWc1S/ktg10ZVI=,tag:AJM75PkkiCxWl8KFRSZy8w==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbUEvYjl2WlowUENtbGxR
            M21adVAxbVMvclJwZG9rdGViRldwbDA3TUVFCkU5K1lnWUtueGYyQVRFdXRiWThC
            QmxKS0ttM01wY0ExNm9QT2dDYUU1NE0KLS0tIHFpb3kyZUNqejB4L25jMENLZXFY
            ckdVV0xGVEo2Q2p5eEVLNHJUdG1abG8KelQ3KNQkbwH6s+pooxvUetGBBVw5L0Kc
            ZyKNKuuXnYm9zyU5fe4PyORWNi+IcI74r7OOrV72kBUogyFUwksA8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGREhLYm5vWFhtUnNNczho
            d25JekNBb1NKQTduQTcyemdmVVpqT1N1bFZrCk5NMDlScUlKb0VySjhqZlRxRURO
            b2VOdFQ2dUYzaWFTS0JCREZ1am9YRUkKLS0tIHpJa002WFZ5K0pRTXVyVVZpbHU5
            eUNvVnFYVUVtT0krT0dWNkZ4SUd4YzAKDGGcjQA6QCvb3BvwZmArkcfzn3v1CZJI
            oHdeNtUWGOKl1creVclziDYQmSCa5vkKCyt2/Xub9IOb7+l1cB2JwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBazBleTVHR3dJd2xHUERw
            SnVSSEhIMDgwcWJtOHZpYjRGOGgxemdSOWpJCkJLUHBoM28yZitVbkkwUUxvYm1D
            R3Z6eFZQZ2tubEVKR0pqczNGRWdzQnMKLS0tIDl1bWg3R0RMbFd6WFprZWdDZjhv
            Smg3VEM5dE0zZjEzMVF1U3BZK296U28Ks9SL3WlaPBqdCnBedPbtq+KI1OYvOV6h
            UyEwK4/MVnhXbDSDBQTUbdyx4KjkaOUcN3mgRIKYIEkPHl/nRtxnBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:45:40Z"
    mac: ENC[AES256_GCM,data:h2J7keObA5jOMWiPRlRftd0Ate4ZRrH/eSjVyL2DiF7ogrXtmoXgVw+bTxMZJU8AFUFnMwKCCzLt0yONLFVDmykMhG31zMWqHEhGnp0mNyLEkIQUvsLFDaRtTnykj7olxHAWHRmPmQctyVHcJq4vN+3gNgpfCGtAQdWD1tWEZKs=,iv:I7dubb5oAMH5djKMDQE3WWZqClxOxq0PcCv9RtB7+ws=,tag:VK2vMas3gRd3lsxgTv9vQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-signing-key
    namespace: apps
stringData:
    matrix.josevictor.me.key: ENC[AES256_GCM,data:y0sFZamMXIskTG0XeDb/99Q11z43O+8LAFMzDh4CPN25viCaEnkmVtQzS6iYujqqkzo9RgScpnnorjMhTqla8R6nzIrXMwqZ8zhB0O3YH5/4j3rv8zbwo336flEEIa3D0XTvYs/0sY0MUW0qeihsCVJBh9jyHYZXOAowFX4xj3hYhoX7NodiyKP3Gd2Y1CsQ/jORD4q2dnxr6e+cQhrYoEER4R2YyV0RYIqBTs0Bd9uIDjGihqjlcpzMHe8+Q8TTQ4GMbCWPHJb4et4Lrsib39TyzBxVkPH2XyZqWajnLw1qCTzD74Un9XczZVvzkhejH6o7sIHmedGZu5X4FG6WnRTmpl5NbD6AFnZW47P5iRCLKiI+cwUOow6SeHHj1yOnrtMveYhT5Kdwoj/lY6vPY02M7zER2OIQbjCokZ4pmsSrh0f5fZApALDYvjkEEIDpu9/mGEsx0g==,iv:gWdOCKNQDeBTw2NIdf1NRjw5bOYvifQomQQuLXYD3mY=,tag:oHiNNTllKQz3R50Kuhm4qw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbUEvYjl2WlowUENtbGxR
            M21adVAxbVMvclJwZG9rdGViRldwbDA3TUVFCkU5K1lnWUtueGYyQVRFdXRiWThC
            QmxKS0ttM01wY0ExNm9QT2dDYUU1NE0KLS0tIHFpb3kyZUNqejB4L25jMENLZXFY
            ckdVV0xGVEo2Q2p5eEVLNHJUdG1abG8KelQ3KNQkbwH6s+pooxvUetGBBVw5L0Kc
            ZyKNKuuXnYm9zyU5fe4PyORWNi+IcI74r7OOrV72kBUogyFUwksA8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGREhLYm5vWFhtUnNNczho
            d25JekNBb1NKQTduQTcyemdmVVpqT1N1bFZrCk5NMDlScUlKb0VySjhqZlRxRURO
            b2VOdFQ2dUYzaWFTS0JCREZ1am9YRUkKLS0tIHpJa002WFZ5K0pRTXVyVVZpbHU5
            eUNvVnFYVUVtT0krT0dWNkZ4SUd4YzAKDGGcjQA6QCvb3BvwZmArkcfzn3v1CZJI
            oHdeNtUWGOKl1creVclziDYQmSCa5vkKCyt2/Xub9IOb7+l1cB2JwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBazBleTVHR3dJd2xHUERw
            SnVSSEhIMDgwcWJtOHZpYjRGOGgxemdSOWpJCkJLUHBoM28yZitVbkkwUUxvYm1D
            R3Z6eFZQZ2tubEVKR0pqczNGRWdzQnMKLS0tIDl1bWg3R0RMbFd6WFprZWdDZjhv
            Smg3VEM5dE0zZjEzMVF1U3BZK296U28Ks9SL3WlaPBqdCnBedPbtq+KI1OYvOV6h
            UyEwK4/MVnhXbDSDBQTUbdyx4KjkaOUcN3mgRIKYIEkPHl/nRtxnBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:45:40Z"
    mac: ENC[AES256_GCM,data:h2J7keObA5jOMWiPRlRftd0Ate4ZRrH/eSjVyL2DiF7ogrXtmoXgVw+bTxMZJU8AFUFnMwKCCzLt0yONLFVDmykMhG31zMWqHEhGnp0mNyLEkIQUvsLFDaRtTnykj7olxHAWHRmPmQctyVHcJq4vN+3gNgpfCGtAQdWD1tWEZKs=,iv:I7dubb5oAMH5djKMDQE3WWZqClxOxq0PcCv9RtB7+ws=,tag:VK2vMas3gRd3lsxgTv9vQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
