apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-config
    namespace: apps
stringData:
    config.yaml: ENC[AES256_GCM,data:8L0b9mxkJ9S001CXq33yeSl30veZzAcQtTw4Ctun/3BjdZ5oU/rgCYWz3G4krePJBLVASVz+bscvkv4c9wySqmJ6Rks0Qr9f+mJdQpU/1TtjUZgMQBqUOFrHqgDKIY7ccbktbF90sgN8aWK+/s8WW4IlpXc97VAig6e7cw0Mw3oJNmusxxmV4HdNmeBsWvNHejcyh3O5lTt6TIDs/aNx0ujAXwIYKvBARyXYF9Ze54H3lOGtVfgE7Yxxjxb2xEi9n0ktHYIZwBqUO021qu3GFUwysxPgZ4ED/Fh0fTYSmTD8LQzZkBuLFbdAsAywUEjv2rH8AMIVMT7uaoy/RguwCF1VBezTmzmSJWObT4bPa/rDU+inTMItp0SBENmo5w032YB4WN86rs7+ruWRx6TkRYFvgdGR1mWtEreI1gtIO6dMv7fC9fyI+Dz7KiiFFR/VL/R3obQlmYLT5XAQC5pNcZ7i1X+kwTtum8GNseJYx6fcYIDhp8rcPxRZVI3lLBJjKULxT0GovmqkdSG8aC1oMqiBoE4U3mZhWoi8+NMTlUu9pS0vh5tzTBeqvUsl7I5RTlgOuVWFPioknRJQFwTAXkG+L7bhDCXjuhvZSiDWXMUo2GKeGTPtcQgbJoxnGOZuFVSuWXrmh9PBnKKzLhwUUFBrkPv202lY6Npq+zNESSlRBaVSvrKO7w8V/rLWLqsbPqCcz0pnCxZcP3PTw6jFBEx31xqwVS8as8o6mQOhQiXWVj4oFHZtWQPV4bOFZCEJglBO4IYV11V44oi4pj2L4kcQzLYrQqbJm0im80cYNcs4Hfr0EXxYKh5sdOm77kLskel10EbXJsVcO6M+qWyZ3mhs+1BzLDwUueTodywNKwUEzUjWZ5ALfN2d+WRhuKq9nItTbl3HntPnfXjA624vKTdhj9rpU4f9E+K5pS9WI/SleqRrTm14x3pzs81Qcm5wRP4ObWq5tt1+yqKp774CqmFpTMGYaPjTdG3kV9lVGItIWgzWMdaKzI6D2rUh+vMp2NyRi1y6hi0Y4n+V+69213FFGMPAjLXh82sDTspvJPJ05oHHChzO0mCkb5CQoVwix1OThPWvsZ+hVztv5I0kiS/5J185EoPy4Uk7VZtj/GfEUrM0UjljOBy0j/BbgV1ERjByN8mwfP/LfDlxePOOHT3tK3NjcEd8F8iMQ8BjQ8j3azaXtVM9vJgFGUesAYDaYUq7hjBdUDo8tggAl6cddXKEQVgwoTQYv/eo5crIoO2aYBbRwaX7FhAJ5iKI4w==,iv:2+gGyyZBSxq7UMAqn4FdSTJ0getu5PglSwaQT/9Yqyg=,tag:3ijdP9RCzJAJRPXQr+Chnw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWUtmeXRTYlRLcU94c1Jh
            ZDd2T1JlbG9CVlBWc2FpVU9ya1VIa3l1SFVZCmhESlRWNXlQZGxxcjFPb1orWmRn
            SXloWURWQjhwcVdaTXJuaTZaZlk5aDAKLS0tIE1weHpOcHdLMzJUYXhOT21uQUZI
            T1lQendQZ01kTzlvUkZGMm5ZREUvY1EKINvB/8OuXJQ5nRYb2e4MzznNSoQzt58p
            +2TGattELn53/Rf28MWBvYVjATFUJHQWA1Kf4fjw4zUJJkb7vZtFmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTktXbkpiTklya1ZiOVQy
            a2hWWmdscnpqalFJbEp0RVBHK2ZxcVcwaUFzCkU1QW1lVDU2Ukd6Vy9vZGpBZTRs
            WlBvQ2hsaVM2dm4rdE45NHl2YXlqMjQKLS0tIEgyV1U3VHIyQW5oaUZVcnVKdGlU
            cklXNWlLUGtKeTNWRm9xRlhCUjN6ODQKT0C1MsndDYd1nxCPVxzJRNcqy9pzoGbR
            LVBveHQETM+B6dEWdx+wQLzVIzk+V68ANlJS6Evt/MxmJflSxotKFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY2FXZk5zdCtraS8zT0hO
            c25acWp5Q3gyQy9yYnZZbWlpZys5dEJudzBRCmNRRjBPUm9nU0hlUjIwTXNyeEtH
            bHp0T1dzRWpheWdySnRUd21uMFkyaGsKLS0tIDZGYU1FdWREbnpjbVFxUmdYUFM0
            Ky93Ti83UjVrSkZHb0s2d0VGdWU5NHMKmHNsK0HW/z1qJzOZk2EoVEBcvRipiuTu
            SmHOrheZl6pQz2s/bWYw1GyRh7RDKUnmAYQuAR/M8OkdGyKDlsABNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:07:46Z"
    mac: ENC[AES256_GCM,data:l2W0yZ8UbKShUz7nFHwAl5/l7AEmmJdviDy8RCSznNQHzjp9D4jq01KasMx75i22hTLakuNItzMO+tSW5ve23kkqT5K1KdTDnKp7UAwoYFSjT/TIHacGy1iCqF+xAO+TZ/DTcTWMxeR5wGfyqSOPxbgArc4SOjJris+27xVQTHA=,iv:ZTG+b9v6JMLP+47xyzgNFmSNCjg6oI1mTDXLSnRf7EY=,tag:Dc0ttfdy5hnmo6rWU6Gytw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-registration
    namespace: apps
stringData:
    registration.yaml: ENC[AES256_GCM,data:f8RD7v7fywM82dhQH68bzMbKHF4fXEmmEVg87phbi+VlBcyuERMZPKqx5JrgKT/OCQeAsigh3OJ1oCkwfkK1s5KXWhEOkFkxnhfOdio0z23920Kby3bLckXC6Gc13d0OKx8eCX1AdKMUuyJYN+fCBaG11SHT86T6EctD+EO0cf6jOhpM+cFccxEAEEVIzJfLcNfp8thMv+EQn/dPQgLEIwicY2zFD8t0Ij5AaX0z8iAqPd8onmX5RFi5Vn+1wAVzdYmrsq4VOJ6HvuaSPI6wvo8k4+yvRWjzc9gKawYo9uHRLP94poxGn4mI43r8q8yQiOuxcfCOScvZUueKI8VCCqqo1RzR76vNzFWwngsjd5dofO4LSVQUbiVRl8TjX4Pj4wjQKKIVEmvOoPw7nd6yohK2xvXOm34Oc8Hl8aXj0Sdbd/brB5S4icZ3eqj4mGPltwum/zc=,iv:cUok80xMAMtERccr6eVrgU29ba9KsvZ3Q0i7ij08A30=,tag:UrB4v6C3O+8lw6cwlyIIOA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWUtmeXRTYlRLcU94c1Jh
            ZDd2T1JlbG9CVlBWc2FpVU9ya1VIa3l1SFVZCmhESlRWNXlQZGxxcjFPb1orWmRn
            SXloWURWQjhwcVdaTXJuaTZaZlk5aDAKLS0tIE1weHpOcHdLMzJUYXhOT21uQUZI
            T1lQendQZ01kTzlvUkZGMm5ZREUvY1EKINvB/8OuXJQ5nRYb2e4MzznNSoQzt58p
            +2TGattELn53/Rf28MWBvYVjATFUJHQWA1Kf4fjw4zUJJkb7vZtFmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTktXbkpiTklya1ZiOVQy
            a2hWWmdscnpqalFJbEp0RVBHK2ZxcVcwaUFzCkU1QW1lVDU2Ukd6Vy9vZGpBZTRs
            WlBvQ2hsaVM2dm4rdE45NHl2YXlqMjQKLS0tIEgyV1U3VHIyQW5oaUZVcnVKdGlU
            cklXNWlLUGtKeTNWRm9xRlhCUjN6ODQKT0C1MsndDYd1nxCPVxzJRNcqy9pzoGbR
            LVBveHQETM+B6dEWdx+wQLzVIzk+V68ANlJS6Evt/MxmJflSxotKFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY2FXZk5zdCtraS8zT0hO
            c25acWp5Q3gyQy9yYnZZbWlpZys5dEJudzBRCmNRRjBPUm9nU0hlUjIwTXNyeEtH
            bHp0T1dzRWpheWdySnRUd21uMFkyaGsKLS0tIDZGYU1FdWREbnpjbVFxUmdYUFM0
            Ky93Ti83UjVrSkZHb0s2d0VGdWU5NHMKmHNsK0HW/z1qJzOZk2EoVEBcvRipiuTu
            SmHOrheZl6pQz2s/bWYw1GyRh7RDKUnmAYQuAR/M8OkdGyKDlsABNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:07:46Z"
    mac: ENC[AES256_GCM,data:l2W0yZ8UbKShUz7nFHwAl5/l7AEmmJdviDy8RCSznNQHzjp9D4jq01KasMx75i22hTLakuNItzMO+tSW5ve23kkqT5K1KdTDnKp7UAwoYFSjT/TIHacGy1iCqF+xAO+TZ/DTcTWMxeR5wGfyqSOPxbgArc4SOjJris+27xVQTHA=,iv:ZTG+b9v6JMLP+47xyzgNFmSNCjg6oI1mTDXLSnRf7EY=,tag:Dc0ttfdy5hnmo6rWU6Gytw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-env
    namespace: apps
stringData:
    form-secret: ENC[AES256_GCM,data:CAVvpHO2deXi0dtY+wG0jDzu7JZDFm6fPGMOffeNVY60OAqhvEtFiCGQB00=,iv:pCXWCJkbO0DdbtEsITES/kzRzNX/R93YI8DZ/xewDMQ=,tag:QGij74zlXyT6XuwM1T7TKg==,type:str]
    macaroon-secret-key: ENC[AES256_GCM,data:QA9vvvbdRVbmXeiJnDsA8Sg6EC1bx4wUtB2CCHDctE864hRhT8TEyXtntEQ=,iv:c0SsXQImO0wjnuuHRCSYeVMEJ0ms7fw1P3y0yqTbvKw=,tag:OHRJCnJOnzO7AjqZvs97Gg==,type:str]
    postgres-password: ENC[AES256_GCM,data:aolSxJGaP2TZ/05H97BELl55vg==,iv:BJ8c5C3p5RvH4Wi8AC0Drr7SykVt5NZkKOWevffhD1s=,tag:w/OGZbXIQbi+7D3nQ7F3vQ==,type:str]
    registration-shared-secret: ENC[AES256_GCM,data:AE5DClr5JtjXiuTa/veoH++KwZ6ORomISNKHnffqcwzoot/svL6Obt2njag=,iv:6OUXudiH4VpBw5M3VbdoJyrTbUJBYk3jhTY1lny0hko=,tag:8K+RwJLgw87O3UntZY5ckw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWUtmeXRTYlRLcU94c1Jh
            ZDd2T1JlbG9CVlBWc2FpVU9ya1VIa3l1SFVZCmhESlRWNXlQZGxxcjFPb1orWmRn
            SXloWURWQjhwcVdaTXJuaTZaZlk5aDAKLS0tIE1weHpOcHdLMzJUYXhOT21uQUZI
            T1lQendQZ01kTzlvUkZGMm5ZREUvY1EKINvB/8OuXJQ5nRYb2e4MzznNSoQzt58p
            +2TGattELn53/Rf28MWBvYVjATFUJHQWA1Kf4fjw4zUJJkb7vZtFmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTktXbkpiTklya1ZiOVQy
            a2hWWmdscnpqalFJbEp0RVBHK2ZxcVcwaUFzCkU1QW1lVDU2Ukd6Vy9vZGpBZTRs
            WlBvQ2hsaVM2dm4rdE45NHl2YXlqMjQKLS0tIEgyV1U3VHIyQW5oaUZVcnVKdGlU
            cklXNWlLUGtKeTNWRm9xRlhCUjN6ODQKT0C1MsndDYd1nxCPVxzJRNcqy9pzoGbR
            LVBveHQETM+B6dEWdx+wQLzVIzk+V68ANlJS6Evt/MxmJflSxotKFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY2FXZk5zdCtraS8zT0hO
            c25acWp5Q3gyQy9yYnZZbWlpZys5dEJudzBRCmNRRjBPUm9nU0hlUjIwTXNyeEtH
            bHp0T1dzRWpheWdySnRUd21uMFkyaGsKLS0tIDZGYU1FdWREbnpjbVFxUmdYUFM0
            Ky93Ti83UjVrSkZHb0s2d0VGdWU5NHMKmHNsK0HW/z1qJzOZk2EoVEBcvRipiuTu
            SmHOrheZl6pQz2s/bWYw1GyRh7RDKUnmAYQuAR/M8OkdGyKDlsABNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:07:46Z"
    mac: ENC[AES256_GCM,data:l2W0yZ8UbKShUz7nFHwAl5/l7AEmmJdviDy8RCSznNQHzjp9D4jq01KasMx75i22hTLakuNItzMO+tSW5ve23kkqT5K1KdTDnKp7UAwoYFSjT/TIHacGy1iCqF+xAO+TZ/DTcTWMxeR5wGfyqSOPxbgArc4SOjJris+27xVQTHA=,iv:ZTG+b9v6JMLP+47xyzgNFmSNCjg6oI1mTDXLSnRf7EY=,tag:Dc0ttfdy5hnmo6rWU6Gytw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-signing-key
    namespace: apps
stringData:
    matrix.josevictor.me.key: ENC[AES256_GCM,data:2VXjYnCx0aa7WlDhwpskz/S73wgtufOCESugOJWIytOdtRLIbeR2JmMdLmRjbyzGbdzjGAC/HbDF0K9LNiQikikuFfXqE9h0L4sQDNUuEf5GxE3zJIYjH4fKl3tsL2/BScrCfMr25S8BARjbfnefk3rDlVlsUdVv1wRagBa2jDeikNgMEUO/t//ugL0gV+Z9OZwxP1+6Uf0f6R9+4aAx1GTiHYsEm8guQMP4V3Frr6iQRGAsDkgMKtcEef0mEFdO/rgTeLu1YlmtX/DrZbbHqK+dBmtHsBUI69RMVXS+URplW7TuYwOgwEt2n6gK5t3MJjQ3jkw7Kz6K7PMCiFh3Mclfreud3AkcyteEdgiHbCbMrN7h/xw24M2DsTgyBQXDfC34QWccT30qDtsaJou/ZrCnzHQn6sdnhy/H7OikYbqtSBMDgrqZxfD3nHVL4dCw5YQu/SZWiQ==,iv:rfUGkABYQaR1bNHikovo9lkwVEZfCYQ/Gpc/roAMYdM=,tag:4Sr75m50ExH1IxjkHX4Tug==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWUtmeXRTYlRLcU94c1Jh
            ZDd2T1JlbG9CVlBWc2FpVU9ya1VIa3l1SFVZCmhESlRWNXlQZGxxcjFPb1orWmRn
            SXloWURWQjhwcVdaTXJuaTZaZlk5aDAKLS0tIE1weHpOcHdLMzJUYXhOT21uQUZI
            T1lQendQZ01kTzlvUkZGMm5ZREUvY1EKINvB/8OuXJQ5nRYb2e4MzznNSoQzt58p
            +2TGattELn53/Rf28MWBvYVjATFUJHQWA1Kf4fjw4zUJJkb7vZtFmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTktXbkpiTklya1ZiOVQy
            a2hWWmdscnpqalFJbEp0RVBHK2ZxcVcwaUFzCkU1QW1lVDU2Ukd6Vy9vZGpBZTRs
            WlBvQ2hsaVM2dm4rdE45NHl2YXlqMjQKLS0tIEgyV1U3VHIyQW5oaUZVcnVKdGlU
            cklXNWlLUGtKeTNWRm9xRlhCUjN6ODQKT0C1MsndDYd1nxCPVxzJRNcqy9pzoGbR
            LVBveHQETM+B6dEWdx+wQLzVIzk+V68ANlJS6Evt/MxmJflSxotKFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY2FXZk5zdCtraS8zT0hO
            c25acWp5Q3gyQy9yYnZZbWlpZys5dEJudzBRCmNRRjBPUm9nU0hlUjIwTXNyeEtH
            bHp0T1dzRWpheWdySnRUd21uMFkyaGsKLS0tIDZGYU1FdWREbnpjbVFxUmdYUFM0
            Ky93Ti83UjVrSkZHb0s2d0VGdWU5NHMKmHNsK0HW/z1qJzOZk2EoVEBcvRipiuTu
            SmHOrheZl6pQz2s/bWYw1GyRh7RDKUnmAYQuAR/M8OkdGyKDlsABNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:07:46Z"
    mac: ENC[AES256_GCM,data:l2W0yZ8UbKShUz7nFHwAl5/l7AEmmJdviDy8RCSznNQHzjp9D4jq01KasMx75i22hTLakuNItzMO+tSW5ve23kkqT5K1KdTDnKp7UAwoYFSjT/TIHacGy1iCqF+xAO+TZ/DTcTWMxeR5wGfyqSOPxbgArc4SOjJris+27xVQTHA=,iv:ZTG+b9v6JMLP+47xyzgNFmSNCjg6oI1mTDXLSnRf7EY=,tag:Dc0ttfdy5hnmo6rWU6Gytw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
