apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-config
    namespace: apps
stringData:
    config.yaml: ENC[AES256_GCM,data:ny4Fp+ooDfL6XMIvpXBFxzT6ld3nF8TyhthC0Y3w9BuJxs9dZEmlDUZeUjF3YD+swAv4W26RTRzRHDX9t5p71d3NXsixn3zNgOIxhX082vH6mbdr+YeGYNzxBkj+IpFqlX4/PJO6xFDY7h/jYimlLuSUW5WlxC48HTlJlT6yRlMAN0u64r1AfHKZqqdM8Ri1ltpAJz51yBeCflpk8dX/dYGaNUve6uIM8fpD9jwzcJLdecve1L55xNfDaeaaJro67nmAskH8/rmnTT3wUfDFu9p6ElzIL3LFEZ7xT4wGlbGcyXiwVF/qcuVIOMipeAwCqrqE1sbBh98N7aDPgEirkvIbxkfsKrI7pmt3AaynwgQVPIFh474XAK9TnQGY9lP/040ElFkkYxhoKu5ioc4+9wY7ItKMhcVFbKxqXFYiQZezLjaTSi3x603tx7/x67jFJgsQ2pSbKK3QhC07a/vDR2ZkaAaEjAeIuKvpzUHJjprab+c7nUyNDmqI05kUh5IJhLVNY7B+6Whk81Q9S4kzO1mCorYmxXm2kvECtWjnxTkjOukccrcmcIoSNHMON7i95AxKuKx8qgHetac1dKFY0iDLbjoZKDd0KtuEkfdAdSXSNyH1ri/BEge6BlMRBb/8AXo6sjlAmofKyv8KDtDmBlzXJkl2/F0e++88lIMVK9oI2FJTwMCsU4OQNyPECKMyDElQeebMQduTvP6CGpSSoovNq8atH2PBYcImsBY7IsX7VxgrI2lcc6m9qKyaXHff/wC26l3gm4ypgp8TIG284jnlou/H6tY0uR3Z1G5PywjzHYdUiPPpFBThXlotalNR0kxSG/9GBm9fzLgvhY53I/Cpvb2Z7EGB2zHZpfoTsqM5NLDpDsTyxujD0iOD8tYeIwkUWrwqECgv6CxtUXkThtlHsyaCEPXu8Mr7whtyi/YzB8pxsLgzTeC7vZ1vzKqRotMpCAtffiGayLgGkOpGzkNiuVPCd5XlhhoQqubrcM9cGraayROhBC0iLiZ8tnWs1Dh/sA+Jp5Qko7gh55BUQgr8WAmQZZ3rh2YQessKhl84LV6Sgtt69TuT+pTNXroePWJOMOGs6n3jq0Ioy3E/Wpt22ZksG9H6hLTXtG/8eWR0ZbGyghnHdJFkcqJz1veIoGdBj91xCidOyu4ULyvUV/f/ioDXkQ4TZy8v6019YXjBXvNI3LDpL12CbbM2Z7R6P6ZvNCSTjFHpSwU3cRGit12y4BDQF/1NosPCVc2+MwKusxtHk+WLt0MVAarJcwugQuP2yRNLyIrpYrTypWwyX6QCf6La+qOZsfahY01XtEB7HOU/UVkWtcdUDestV7p9cYI6N4z6KaDQCx8WDbdgIHtTz+DoYoXZgFL3CvwqPsEUszuhsmb2SJylQ4zhqztPlTgcnLYIWiUnyGL/p3TZnbFE72Lkkc0VXFRdJ8TLUNt7U+pSY5d+qbeZcy9v/ZpGs0sz+OEZl6nMEtENRwKUERCdUMo6uwFPgMiFd0Y8muk9AG4D6K0GRHP+Wj8Zyw/jpapocfA3CzXj9e4UrHaa1ScfiSMUlN7tyIhr2DYS3q93yD9OsRzbFVS8K2FUXew8rxbSMFkIrG84WQo2jnQ53+jjsQLpf3nnGvm1zmxf5kHHuglL2uNrD77G6rK/KthPQjftZnN1/pPxNAd6GrDewo6BjyDs9c5K8zlzFgZmrceoU+EOpZ1Q1vvgl3iZz3FTJHyQ+Qi1Y4Q8LwLe881qcW+HDcWZsckA0c0zUJEsSFBWnBKGI2uZGIA7xHwhvvQNkb11bIXemFDJ+X/GXpnM2tBO667Xv22BZ9gxuif7j9NBMqwywI3Hiaa/Jvxw10IscHQOk1BFBX4B7RdWchuGozSeDfc54OLGPpktyqcAXH1DMvMsu3uZ0G8Yrp/IdU2xe/7PfSFo/mAPyJX4lGr/TxkK8HiXLvJnwbwwOCcMjlUvjDmacNols4Hk/QAS8gCiI8feOSX4hIcKmH6p3JvcujzfOVuQDC9s/tnnGJ7bE01wFsrTEShON8R8oWJJHNm7T0cXEq2yizZyjv2ArE2IlMeBMaAbYL3TkCga3QPf52XEnMGu5A2d0bUbFu/rP6w/gNjl5ai7iqTxwiVeQ8RRZqw/FbVdjH4H7i5gRa68qt+DLzFga3lAi/W/QYFHrbXfYhtheJvqVym8skoHP3qoLiTQJpNvCy67XvhtOE2uYIvMzy9UCyLL3r53G9vxiUmpwmSuyguyMbx6LwDTKLq0OLOZqCENpy2Pw9f/Eu34SCgE2WhbEb7ekv4LgykAjVCgTtkVNCnMrh3SIkNNhNID0VjE8jFm4m2SojlXH9/VrCp4CJHCOZm9qNIm9lwglFif3qkkEez7SajjzcbMJiJ9klEWpd2jPeVndNSO1vPUzdJbuXCPZVlXt1cA,iv:UJG+/C5UEVtVlsopvVYz7y8/wAX9R+cZHLtGau0Ff8s=,tag:Z1wK1koPUCsHTfXxhW5TGA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbExlVjFvNWVjSmVLcGN0
            Zm9nWHdmYmRCNS9HSzZ0MnVEMVdNcEZDMFR3CjBsei9UN1FvVlVPNWxhZUhuU0xR
            VWpBV1Y3VlMvdTRvaU1CSm5vRDZicHMKLS0tIDcwUEhNTFRQMjViaStiNGR6djg1
            YXZKbWM2NUo2cTZJdzFlOTU4V3pBNjgKU7Tn3PxtKc3UMsqzGw4kQ9vN3gapowoh
            a7CTgxDIXiHcY3K/BwBisxSJfW24Z9lh+Eo/ajVE9L6eVFZOSZwiVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMU1sdzMvN2Eva1ZSMFZN
            a1ZqRFhtMVprSWlHNlJvSnJLNkZPWm5lemhNCklndmNxdXh1TGlTRmRSNHFKUHhN
            TjNjVE8xTStpSjJ3Ulp0bittQVJ2YTgKLS0tIGVxTXRkSlBJWTRuYWNEOU9MU09K
            bURLMUs3eXZaS2hHVS81eHFSWHVBUkEK2uUp1e3Fe2lvZAH23JNhVEnprUe83BTC
            vjG1OfBdTGdCEwLlxZ2ZIY9v2TdPe9aC3/rAeCMRHYUYkbKix+vufg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbW1kNWgvaWcwdU9vM3FO
            UTBqRCtrMGdBRUQ4dEVCbnVMWCtlbUYxOXdvCjZkNHNrZUgwNHc0VEJCaGRSRzdO
            R2RiZjZscUdPQXpZQnU2eHVrYnN3STgKLS0tIDBqN0svSVFLTGdXRnRkYU1IZkxk
            ZXQ0YlFKVC9idXlXYXhZdmNNK0d2dUEKBt95v4DiX2WJUg4+56tGAFryFkwZ7dg6
            ymm0YH/cv1WMdEIC/5meTqNBn3wuq5lDM5B+C7qxmh3Fh48xksGHKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:12:58Z"
    mac: ENC[AES256_GCM,data:ME4kRN6ZnJitxYo22RWiPsxLdxKjfZ8V4p+Y/f/7zyTpHByajR51bHU5XobCotZRrhecQIvkupemRxJxMsqWvN8KbvNqqP0ilXj0bMvQX/h4uKmf7GAZgIDGETqqyLkts5iHjIFmeeh1Roh3XAnEAg/gPhlDiSgORmh1x70TaAE=,iv:Ltk/aFF+rJmae8Xgzl9GpcxKLubmrlKDizFZsBWpdIs=,tag:aR77MSHfzir1dIWP0fe6cQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-registration
    namespace: apps
stringData:
    registration.yaml: ENC[AES256_GCM,data:zddlQcDSQo7QfueYo5xPf6Pj7FM8FzoUWR+C3ewaS6AtIg6Bg48PUvt3O20kuuRQc9nsH7T+uJmXjxcglW6o1rzUKtJYV40UUhVfL1sGAZ8KOJmuKg6yqySrILhqausbBxmMqbFfnuDRH/3ewbuFZpUcaOv/VZ1rXSNHdioIQBKNVpRwyVUiES/uA5GjjyE+CrDhPQ1VRsgLnuVMoOv1TvlVWq/0gesaI740itkL//XEDJCQeuW95bIq5cp6vI+21BOudw0s6CpY+veXAavXfk1sRJdXmPG/CqQqkcl0G42Ptp5IRvgYc5A15zz8BIzBiDR03qrjItJ7ymmDP50KsiEm0199Uv/ZTaz7nPwYy8pJhh1ZP7DZt0AsKaWxMdjKdRcWV3Yr/RO2lz6+d9R9b5sB2EmEVAfZchMFnLpyX6FzpXUHnCTcYGD0mX2dioKBYeIUv3AVSn+sylghtYAETPo8jGz9RVAwHDA4/o3qRToiaEUIuXj4oFH/XAM4aDIJTPLMKMfUSH+1DOlf9Mq/cTUIPfHypjUJqc/BV6af0At2fQdB,iv:VQKSK51/aJ97jJJytdTFtN6aDRbBTm7PI5UtTeW1LuY=,tag:rJJPtj40z5pAbJX6ezytnQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbExlVjFvNWVjSmVLcGN0
            Zm9nWHdmYmRCNS9HSzZ0MnVEMVdNcEZDMFR3CjBsei9UN1FvVlVPNWxhZUhuU0xR
            VWpBV1Y3VlMvdTRvaU1CSm5vRDZicHMKLS0tIDcwUEhNTFRQMjViaStiNGR6djg1
            YXZKbWM2NUo2cTZJdzFlOTU4V3pBNjgKU7Tn3PxtKc3UMsqzGw4kQ9vN3gapowoh
            a7CTgxDIXiHcY3K/BwBisxSJfW24Z9lh+Eo/ajVE9L6eVFZOSZwiVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMU1sdzMvN2Eva1ZSMFZN
            a1ZqRFhtMVprSWlHNlJvSnJLNkZPWm5lemhNCklndmNxdXh1TGlTRmRSNHFKUHhN
            TjNjVE8xTStpSjJ3Ulp0bittQVJ2YTgKLS0tIGVxTXRkSlBJWTRuYWNEOU9MU09K
            bURLMUs3eXZaS2hHVS81eHFSWHVBUkEK2uUp1e3Fe2lvZAH23JNhVEnprUe83BTC
            vjG1OfBdTGdCEwLlxZ2ZIY9v2TdPe9aC3/rAeCMRHYUYkbKix+vufg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbW1kNWgvaWcwdU9vM3FO
            UTBqRCtrMGdBRUQ4dEVCbnVMWCtlbUYxOXdvCjZkNHNrZUgwNHc0VEJCaGRSRzdO
            R2RiZjZscUdPQXpZQnU2eHVrYnN3STgKLS0tIDBqN0svSVFLTGdXRnRkYU1IZkxk
            ZXQ0YlFKVC9idXlXYXhZdmNNK0d2dUEKBt95v4DiX2WJUg4+56tGAFryFkwZ7dg6
            ymm0YH/cv1WMdEIC/5meTqNBn3wuq5lDM5B+C7qxmh3Fh48xksGHKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:12:58Z"
    mac: ENC[AES256_GCM,data:ME4kRN6ZnJitxYo22RWiPsxLdxKjfZ8V4p+Y/f/7zyTpHByajR51bHU5XobCotZRrhecQIvkupemRxJxMsqWvN8KbvNqqP0ilXj0bMvQX/h4uKmf7GAZgIDGETqqyLkts5iHjIFmeeh1Roh3XAnEAg/gPhlDiSgORmh1x70TaAE=,iv:Ltk/aFF+rJmae8Xgzl9GpcxKLubmrlKDizFZsBWpdIs=,tag:aR77MSHfzir1dIWP0fe6cQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-env
    namespace: apps
stringData:
    form-secret: ENC[AES256_GCM,data:cofU8Yr7mNx2nPvi1zeAJV0ZsS+FWY2v7JzZUKyrPLaYIK4ULTg7qYE5nCo=,iv:d+wSgeOCvWl96GkWn5VjJ19TWkZTmQGQqgU3v2ubAdM=,tag:NOyES1UWIsPrL2HLzjSK+Q==,type:str]
    macaroon-secret-key: ENC[AES256_GCM,data:c3qj+1fX87ka4U+9i7RvONHd5fZ24/sQLV8PEk2I4eRSNxJE6ma+L9OlKe4=,iv:LXLGDJ6LBFbme4kJg0RfE8ZaDvZlP5OX8Cj5MI7XiG8=,tag:1fQrogovIboj4em8M7vO1g==,type:str]
    postgres-password: ENC[AES256_GCM,data:wsFwNb4jT5742S1oO8vMrFDqDg==,iv:OIjF4h8NjH30d7ONwqddsfuLR5QjVME+60GzS5ja8FE=,tag:x529tEhnMYGmkkvTrP/+iw==,type:str]
    registration-shared-secret: ENC[AES256_GCM,data:DwA4NDrGrhFt7WuwRy43DBp1uiqA8DaqMbyHbYwrGuZGQsBchcbpGN2As4w=,iv:ZdxbiA9tMQIfwqnS6mkzgPPoSDjdonZVVvj0uw4gmN8=,tag:nxooOe9vOGbOadU39Zgq8g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbExlVjFvNWVjSmVLcGN0
            Zm9nWHdmYmRCNS9HSzZ0MnVEMVdNcEZDMFR3CjBsei9UN1FvVlVPNWxhZUhuU0xR
            VWpBV1Y3VlMvdTRvaU1CSm5vRDZicHMKLS0tIDcwUEhNTFRQMjViaStiNGR6djg1
            YXZKbWM2NUo2cTZJdzFlOTU4V3pBNjgKU7Tn3PxtKc3UMsqzGw4kQ9vN3gapowoh
            a7CTgxDIXiHcY3K/BwBisxSJfW24Z9lh+Eo/ajVE9L6eVFZOSZwiVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMU1sdzMvN2Eva1ZSMFZN
            a1ZqRFhtMVprSWlHNlJvSnJLNkZPWm5lemhNCklndmNxdXh1TGlTRmRSNHFKUHhN
            TjNjVE8xTStpSjJ3Ulp0bittQVJ2YTgKLS0tIGVxTXRkSlBJWTRuYWNEOU9MU09K
            bURLMUs3eXZaS2hHVS81eHFSWHVBUkEK2uUp1e3Fe2lvZAH23JNhVEnprUe83BTC
            vjG1OfBdTGdCEwLlxZ2ZIY9v2TdPe9aC3/rAeCMRHYUYkbKix+vufg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbW1kNWgvaWcwdU9vM3FO
            UTBqRCtrMGdBRUQ4dEVCbnVMWCtlbUYxOXdvCjZkNHNrZUgwNHc0VEJCaGRSRzdO
            R2RiZjZscUdPQXpZQnU2eHVrYnN3STgKLS0tIDBqN0svSVFLTGdXRnRkYU1IZkxk
            ZXQ0YlFKVC9idXlXYXhZdmNNK0d2dUEKBt95v4DiX2WJUg4+56tGAFryFkwZ7dg6
            ymm0YH/cv1WMdEIC/5meTqNBn3wuq5lDM5B+C7qxmh3Fh48xksGHKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:12:58Z"
    mac: ENC[AES256_GCM,data:ME4kRN6ZnJitxYo22RWiPsxLdxKjfZ8V4p+Y/f/7zyTpHByajR51bHU5XobCotZRrhecQIvkupemRxJxMsqWvN8KbvNqqP0ilXj0bMvQX/h4uKmf7GAZgIDGETqqyLkts5iHjIFmeeh1Roh3XAnEAg/gPhlDiSgORmh1x70TaAE=,iv:Ltk/aFF+rJmae8Xgzl9GpcxKLubmrlKDizFZsBWpdIs=,tag:aR77MSHfzir1dIWP0fe6cQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-signing-key
    namespace: apps
stringData:
    matrix.josevictor.me.key: ENC[AES256_GCM,data:kmpjM7oE9iH6IGeSymNZaLIOTSazv+tIk71KsaX8xCJOqW/1Tb0Ts+GQzOATRTY/WajzE1G+eUiq4MeGOtcIuWxyl6fUVBZt9KJ7LFPC+aS4yGLpAEC4f7tYm76FSdBEdtNsusTOcmPQsS18f5eC1e91t3LHXiliAXFfyuHRctkPrzRHg3gqxARUpz+Z5vOr+tXBiZtaZwtD9hzlx81KF2J+jUlWJueAtpH1hxf8D7K7TzAd2E/oq/Vd6KjNKdaqSFsyTzHJtwkI5C8yzH7Mj3pc58gvIVxa20JfRJqLKwdg4WWNnPn5E3O0bbxVZ6koTkaMj0awKWSf81cN8B2YhWSNJ5wvSuTcgzX0ilr9Md0t/asQaD5OCwaNl+RmOwHJWoeBJrDk5ncIY40C89LmtYPTspuzV7IVNy1Hs2Mqv47/cS05t4TkZdGqTtGgbZyYh64uVfg+fg==,iv:4JjfZI/PhsG1NWY8LuwgBGYlU9xVJwh9Lz82cAfjs+s=,tag:eXLOBD89uEtdwZ9w82gsCQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbExlVjFvNWVjSmVLcGN0
            Zm9nWHdmYmRCNS9HSzZ0MnVEMVdNcEZDMFR3CjBsei9UN1FvVlVPNWxhZUhuU0xR
            VWpBV1Y3VlMvdTRvaU1CSm5vRDZicHMKLS0tIDcwUEhNTFRQMjViaStiNGR6djg1
            YXZKbWM2NUo2cTZJdzFlOTU4V3pBNjgKU7Tn3PxtKc3UMsqzGw4kQ9vN3gapowoh
            a7CTgxDIXiHcY3K/BwBisxSJfW24Z9lh+Eo/ajVE9L6eVFZOSZwiVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMU1sdzMvN2Eva1ZSMFZN
            a1ZqRFhtMVprSWlHNlJvSnJLNkZPWm5lemhNCklndmNxdXh1TGlTRmRSNHFKUHhN
            TjNjVE8xTStpSjJ3Ulp0bittQVJ2YTgKLS0tIGVxTXRkSlBJWTRuYWNEOU9MU09K
            bURLMUs3eXZaS2hHVS81eHFSWHVBUkEK2uUp1e3Fe2lvZAH23JNhVEnprUe83BTC
            vjG1OfBdTGdCEwLlxZ2ZIY9v2TdPe9aC3/rAeCMRHYUYkbKix+vufg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbW1kNWgvaWcwdU9vM3FO
            UTBqRCtrMGdBRUQ4dEVCbnVMWCtlbUYxOXdvCjZkNHNrZUgwNHc0VEJCaGRSRzdO
            R2RiZjZscUdPQXpZQnU2eHVrYnN3STgKLS0tIDBqN0svSVFLTGdXRnRkYU1IZkxk
            ZXQ0YlFKVC9idXlXYXhZdmNNK0d2dUEKBt95v4DiX2WJUg4+56tGAFryFkwZ7dg6
            ymm0YH/cv1WMdEIC/5meTqNBn3wuq5lDM5B+C7qxmh3Fh48xksGHKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:12:58Z"
    mac: ENC[AES256_GCM,data:ME4kRN6ZnJitxYo22RWiPsxLdxKjfZ8V4p+Y/f/7zyTpHByajR51bHU5XobCotZRrhecQIvkupemRxJxMsqWvN8KbvNqqP0ilXj0bMvQX/h4uKmf7GAZgIDGETqqyLkts5iHjIFmeeh1Roh3XAnEAg/gPhlDiSgORmh1x70TaAE=,iv:Ltk/aFF+rJmae8Xgzl9GpcxKLubmrlKDizFZsBWpdIs=,tag:aR77MSHfzir1dIWP0fe6cQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
