apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-config
    namespace: apps
stringData:
    config.yaml: ENC[AES256_GCM,data:WB7mmJIC3cNGCIQ+NLcwxV381onOwB3WPDGA1llHVN5vtlsrW/Hg7o+goTQcEtK6A5Ukq2Fqf/z7A5j08SLfSdAQjfpn1G4CwDDtyq7IsPL7nE3OmuNC+cUGUWQuYG7ce7DeDRUCtmroVSQ0yhH+U8RwEBRtsCXgQW9QRB58Zeqkfj0rf+BLs2XJq9RkL1V9hR1yI0u1RkFeiZxwt3ozsn/fq/96vMrgqrTq0GtnByf0IzGbWxAXLR2GjNyb3J6Ooo93rFWDCjpG9YnB9gyIzqT9c30G0V4WLHUJSbqmQ1JWsi4WZ1nFlAa4WWMs/jTS9aDuhPXSSqaIdeo0J/5G4I8BybCyLKqIe3KFK+2qtbMzFlyBmvUZ92hTubfs4VREsZThEfCOFQt7dT8QjoomSrc1brqncGCYiJlhMRTAx/Q2HEdVAtoKYcclui+7JQbgDCs9k4MwwfxsnFtLk2KqpwipV5i/IDJt+xH3tKgxQGuKx5U7y74Yevzvk7mpNlnc2zzYB1MI+LNdH9qs4M+XoEywegwsyAflj0BPDhLr0acUo2k7HKVBqpE/wNOJ+GISLwUeI3Q1/FUR0jG0e5lKBIGqaymExjlJ1drnRzmfgqR1ZVWaa9Gn5ougIvCUoTVBAsbICl9FBJQ+/KlvPVSGP+tFrEyDrBhWrHl8XovUuprYGSD33DIDuQk+/4iFPY7X0MuWYzw5LH1h5RmY74x3WP2BlVdkSczlsYWG+tcQxXseM6PiBItBYDFox/9e/68LIUvzjbWF+BUpehjmbz670RqLqXTY/AOGO6mN+V6RitJ9vIW9cE9nwrxvnzbuu+wKu6g3Uiah37X2z7iogI+ix088PXUY0NHFI2a+8Bx7lpeF2+X6tumG91gneftTemztZ/wi7YUiVVrpJAkjOGVN1rW/JfCcSseCzDSR0JjPeCFoBtBOtv0xVsgI+MemBLw6qlG4Xx37eODievQAYvtOefZnHqirfYPafHgwLRlWwC+H0OUFlrZW3QKg0PndQIATl8ucIm9DJF0J/PDNp/82GMpzPmA2p4xys0py75ui4yZJHRTHIHxtJ85ce7GCqsC5++kmmjeZaCb5DrHelrnJB8y1ecTu2ZP+6RORwH5LTlD+OFuXyqRbY+7uOzznLB/cSCGmwlmoVTt8JKgrjXvULogx7KhPn41O2VVBOKfrdb4JRZRVowmypchTbyKOcDG1E3B80bSfPInIeZP2FdCK34//kuswcy0V6N74yFD2fQ==,iv:QtQs9GdSJm/rBQkneu2tekSIsxOjQZoLG0Yd5R4xZiw=,tag:KU5y+lSgcegFi94mE+oKCA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQlJtZFFKVmMvbEwzeVJk
            ejJKOXp3NkVBaE4vNWJ0VVRzMmtkZ3BNWjI4Cjh6Si8vVERzejdSUVdBL3crajlY
            My9UUUczbjJkWUxBUHFVUms5OEt4QVkKLS0tIDZES1RXWkhrYTZUcmNlNkxGUmQ1
            SSt3VXI3bVF2dDFTSCs0RDIycmx4RDgKaXuIoqWG1AD9tq8b8s5vH6hg+OnpDVf7
            QkyxAkD4FUdvG9fGLTvnqbeyGGMOIpOokdz9UldbHj5yeR20TIEvMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYWRaZXhoaklxbkIyK0xm
            MkhCTG52ZE1CKzJlQ1RLeXpsUnNBck9JQ2pVCmVaTE5SSE1oaEYxRlViWGJwSXRV
            OGs0a1N5YkRLdGpIUHdBdkJ1Vm9yMjgKLS0tIFJBZk1HcG5TYzVjeDF0V2dEQ0lV
            NWFYdU9zWllXd0FtRlFjQ0NmTHdnQzAKJ0c522W8Kfe4V2xFSiIH5q3byizr+GJW
            Wcix0QF1DCX0xLeQa/Dw4aQzhCCPWDHJ56LGJP4ssC+ZlMXTBCq1uA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR0JvQktCc0UrVkZ1Z2Vu
            SmpaNmJwaDNXeU1mcVJXV2l2eXBlQnhIVzFzClBBdWZvd3BBRnRBNStUNnFKREV3
            eVY4NUY3WGZySmw2ckV4Z3ZrTENnclkKLS0tIHptay9nY00vekZxbzE0blYyZ0VB
            TktvL2Z0SzJYajYwZ0JjcjBKQ0ZBYW8KsmUc1MVh62Ek8saUKdzsBRQosCnXdJNy
            G8xQ9ALI82ljspzNFkN8hAa1Mtb+DJYMmy8jSolYifGetlnhV4dBAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:05:51Z"
    mac: ENC[AES256_GCM,data:C0+lNalfbQUeDqSJvNnHhh5vJwtvLeY6oVEo9Krnx0X/zwDsUKfst/SBD+ahmUMwVwGdJHuPLGrotYXVCj0/HE2YTuwbxKiEgGK0bQJ/r446hYrt2st5dWOql0wdBXLFBCAsBIGgxDuCpQpShMsFFZmQyE/Bo7zEjZXYFJOgH8U=,iv:n0a3M5TSKjdh/LUH+wozlZ3l7tLXX53nbLe4FCLeWy8=,tag:OApvekmhSO+QsAzEOQsKMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-registration
    namespace: apps
stringData:
    registration.yaml: ENC[AES256_GCM,data:FD3xvoxEywmk8Md5YjqYOkxGR+L4RG+X8mKX9iDfObRvWyalOqOCAI1dfAR9igqjCSHZBzmMFgX0DJiPkQfYkIXdk1hD5yEtUMGgm+GqBvs6l4DzQJR73MmofRPBbnCuADeCbvjYg+BvZqBF5iqZu7KbBBFDQwwbStmnNfjzdcgKfV3LJRJ64tbh1ajm9wxttl59W4ZxBKN7InxE8/6xOv5K7IYoX6pFcTGSZWVhVkb6htmMwxf5lg9XKeopngKaHvlt4wrgij+Eqj9aEZtARbNyDQkU4QkQV9EOnjX/lBUN0CvhUI1xoCJkKb40nPXgEP2anzD3FmFfq391GEMnh3equt0OSnU1oKpseGpmCA6v/s2vEA+G4f6oUCrmf+3od7SYqDDxW5h/5DO94vHGoDC7y7Xac4Acekz/XAhYCUDZpbkyDxoRMg6xCNciDT0WHVbHwF4=,iv:gpsMJ+YwSpR2x48fLz/lYV0Sb4yDaY+gbz/VUWQaZ0c=,tag:uFbP7oCBMloEVZK7KxgOSg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQlJtZFFKVmMvbEwzeVJk
            ejJKOXp3NkVBaE4vNWJ0VVRzMmtkZ3BNWjI4Cjh6Si8vVERzejdSUVdBL3crajlY
            My9UUUczbjJkWUxBUHFVUms5OEt4QVkKLS0tIDZES1RXWkhrYTZUcmNlNkxGUmQ1
            SSt3VXI3bVF2dDFTSCs0RDIycmx4RDgKaXuIoqWG1AD9tq8b8s5vH6hg+OnpDVf7
            QkyxAkD4FUdvG9fGLTvnqbeyGGMOIpOokdz9UldbHj5yeR20TIEvMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYWRaZXhoaklxbkIyK0xm
            MkhCTG52ZE1CKzJlQ1RLeXpsUnNBck9JQ2pVCmVaTE5SSE1oaEYxRlViWGJwSXRV
            OGs0a1N5YkRLdGpIUHdBdkJ1Vm9yMjgKLS0tIFJBZk1HcG5TYzVjeDF0V2dEQ0lV
            NWFYdU9zWllXd0FtRlFjQ0NmTHdnQzAKJ0c522W8Kfe4V2xFSiIH5q3byizr+GJW
            Wcix0QF1DCX0xLeQa/Dw4aQzhCCPWDHJ56LGJP4ssC+ZlMXTBCq1uA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR0JvQktCc0UrVkZ1Z2Vu
            SmpaNmJwaDNXeU1mcVJXV2l2eXBlQnhIVzFzClBBdWZvd3BBRnRBNStUNnFKREV3
            eVY4NUY3WGZySmw2ckV4Z3ZrTENnclkKLS0tIHptay9nY00vekZxbzE0blYyZ0VB
            TktvL2Z0SzJYajYwZ0JjcjBKQ0ZBYW8KsmUc1MVh62Ek8saUKdzsBRQosCnXdJNy
            G8xQ9ALI82ljspzNFkN8hAa1Mtb+DJYMmy8jSolYifGetlnhV4dBAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:05:51Z"
    mac: ENC[AES256_GCM,data:C0+lNalfbQUeDqSJvNnHhh5vJwtvLeY6oVEo9Krnx0X/zwDsUKfst/SBD+ahmUMwVwGdJHuPLGrotYXVCj0/HE2YTuwbxKiEgGK0bQJ/r446hYrt2st5dWOql0wdBXLFBCAsBIGgxDuCpQpShMsFFZmQyE/Bo7zEjZXYFJOgH8U=,iv:n0a3M5TSKjdh/LUH+wozlZ3l7tLXX53nbLe4FCLeWy8=,tag:OApvekmhSO+QsAzEOQsKMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-env
    namespace: apps
stringData:
    form-secret: ENC[AES256_GCM,data:b2K/p0jRLRQB0GOYPiv9HPeEZPvbm5nz1mUCd1vnOGzmn2t0LSjvUIAw8JI=,iv:+QxDvhrmwaQOugNET+oPHtCVtjJlYFQtZ4PbGskxyAw=,tag:f1CzSKnfg5x2xJHgRsLwtA==,type:str]
    macaroon-secret-key: ENC[AES256_GCM,data:5nFGkDVFFIzLohwyuZVsCmt71a1tyK9Q+XrFeiAKtl/z7uXIVtzQeLbN5kA=,iv:qFopoZBJrEw6Zr/BdG+r6t/APxr/R8gdmiLlJ+15wj4=,tag:fDx63q1oKPOPVtMcToHtUA==,type:str]
    postgres-password: ENC[AES256_GCM,data:fU/zNocBb1IJYUeEE7x7R48wAg==,iv:BmtL1lMAy8kjF/tka/pHlEyC6wWYnzIRKs6BUIiHbdg=,tag:paifW/AS9NXLIePkMzoScQ==,type:str]
    registration-shared-secret: ENC[AES256_GCM,data:PUyya2CZk6R+l3P84irCm4ngmgpfAXvUmmA0WJemOTlnDUsJ/1SBQQ+a2WE=,iv:Mw2lwpQFaGW5HP+t7+EFd/hme/HuNXFTa1w76MwdUXQ=,tag:bKYLDeiCHCt1FruLKb1aYQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQlJtZFFKVmMvbEwzeVJk
            ejJKOXp3NkVBaE4vNWJ0VVRzMmtkZ3BNWjI4Cjh6Si8vVERzejdSUVdBL3crajlY
            My9UUUczbjJkWUxBUHFVUms5OEt4QVkKLS0tIDZES1RXWkhrYTZUcmNlNkxGUmQ1
            SSt3VXI3bVF2dDFTSCs0RDIycmx4RDgKaXuIoqWG1AD9tq8b8s5vH6hg+OnpDVf7
            QkyxAkD4FUdvG9fGLTvnqbeyGGMOIpOokdz9UldbHj5yeR20TIEvMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYWRaZXhoaklxbkIyK0xm
            MkhCTG52ZE1CKzJlQ1RLeXpsUnNBck9JQ2pVCmVaTE5SSE1oaEYxRlViWGJwSXRV
            OGs0a1N5YkRLdGpIUHdBdkJ1Vm9yMjgKLS0tIFJBZk1HcG5TYzVjeDF0V2dEQ0lV
            NWFYdU9zWllXd0FtRlFjQ0NmTHdnQzAKJ0c522W8Kfe4V2xFSiIH5q3byizr+GJW
            Wcix0QF1DCX0xLeQa/Dw4aQzhCCPWDHJ56LGJP4ssC+ZlMXTBCq1uA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR0JvQktCc0UrVkZ1Z2Vu
            SmpaNmJwaDNXeU1mcVJXV2l2eXBlQnhIVzFzClBBdWZvd3BBRnRBNStUNnFKREV3
            eVY4NUY3WGZySmw2ckV4Z3ZrTENnclkKLS0tIHptay9nY00vekZxbzE0blYyZ0VB
            TktvL2Z0SzJYajYwZ0JjcjBKQ0ZBYW8KsmUc1MVh62Ek8saUKdzsBRQosCnXdJNy
            G8xQ9ALI82ljspzNFkN8hAa1Mtb+DJYMmy8jSolYifGetlnhV4dBAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:05:51Z"
    mac: ENC[AES256_GCM,data:C0+lNalfbQUeDqSJvNnHhh5vJwtvLeY6oVEo9Krnx0X/zwDsUKfst/SBD+ahmUMwVwGdJHuPLGrotYXVCj0/HE2YTuwbxKiEgGK0bQJ/r446hYrt2st5dWOql0wdBXLFBCAsBIGgxDuCpQpShMsFFZmQyE/Bo7zEjZXYFJOgH8U=,iv:n0a3M5TSKjdh/LUH+wozlZ3l7tLXX53nbLe4FCLeWy8=,tag:OApvekmhSO+QsAzEOQsKMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-signing-key
    namespace: apps
stringData:
    matrix.josevictor.me.key: ENC[AES256_GCM,data:36ocxgbFm1r41rvHzdc4MlqYKwrKMCfPz4clh+K1KErbpPFWBJj9KMfXxz6PNzfV662JHTb+f8Ygyu4IK5j8+h6aYuCwD+/ZkFG0XYpVdRP97FsEwZQOuZgB69zzY40bzu2xyEyJ82CiAkN0thGLNTszgQOMxJudY5HzZ1O3uZBT/IWbdhw4aiSNtB+fpH+Sl/sAYIO6XjPs43R+94I/CnRI+pAuWp2WHracgx2ZUzb9hih6hMbSdAlQNJ21PJPWOEpQS/ZJquSHE0etq+rmyw8VLFXTTq8Zm/Z2hJPLAF5lsEYMs3mCmrvEfmPjDBd/7lblzhb1xMf+lw+W6nPihof3+71t38u0XZHXXI6DfchsbdqYOj3IoCBUZmaQS7cz8vhfZILWhmFU4L/e1gKJxskZQ5nF/C4UUqzNxxj1Vnz4AZ/Pb1kTxvRIxvkyrgn7jo94RJa0QQ==,iv:sfKEHk+zwAHQpWSp02/LLrZwYfoNljo0uDSTUf/clsU=,tag:BmkkMuE1hE5WBnawhDWZOA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQlJtZFFKVmMvbEwzeVJk
            ejJKOXp3NkVBaE4vNWJ0VVRzMmtkZ3BNWjI4Cjh6Si8vVERzejdSUVdBL3crajlY
            My9UUUczbjJkWUxBUHFVUms5OEt4QVkKLS0tIDZES1RXWkhrYTZUcmNlNkxGUmQ1
            SSt3VXI3bVF2dDFTSCs0RDIycmx4RDgKaXuIoqWG1AD9tq8b8s5vH6hg+OnpDVf7
            QkyxAkD4FUdvG9fGLTvnqbeyGGMOIpOokdz9UldbHj5yeR20TIEvMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYWRaZXhoaklxbkIyK0xm
            MkhCTG52ZE1CKzJlQ1RLeXpsUnNBck9JQ2pVCmVaTE5SSE1oaEYxRlViWGJwSXRV
            OGs0a1N5YkRLdGpIUHdBdkJ1Vm9yMjgKLS0tIFJBZk1HcG5TYzVjeDF0V2dEQ0lV
            NWFYdU9zWllXd0FtRlFjQ0NmTHdnQzAKJ0c522W8Kfe4V2xFSiIH5q3byizr+GJW
            Wcix0QF1DCX0xLeQa/Dw4aQzhCCPWDHJ56LGJP4ssC+ZlMXTBCq1uA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR0JvQktCc0UrVkZ1Z2Vu
            SmpaNmJwaDNXeU1mcVJXV2l2eXBlQnhIVzFzClBBdWZvd3BBRnRBNStUNnFKREV3
            eVY4NUY3WGZySmw2ckV4Z3ZrTENnclkKLS0tIHptay9nY00vekZxbzE0blYyZ0VB
            TktvL2Z0SzJYajYwZ0JjcjBKQ0ZBYW8KsmUc1MVh62Ek8saUKdzsBRQosCnXdJNy
            G8xQ9ALI82ljspzNFkN8hAa1Mtb+DJYMmy8jSolYifGetlnhV4dBAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:05:51Z"
    mac: ENC[AES256_GCM,data:C0+lNalfbQUeDqSJvNnHhh5vJwtvLeY6oVEo9Krnx0X/zwDsUKfst/SBD+ahmUMwVwGdJHuPLGrotYXVCj0/HE2YTuwbxKiEgGK0bQJ/r446hYrt2st5dWOql0wdBXLFBCAsBIGgxDuCpQpShMsFFZmQyE/Bo7zEjZXYFJOgH8U=,iv:n0a3M5TSKjdh/LUH+wozlZ3l7tLXX53nbLe4FCLeWy8=,tag:OApvekmhSO+QsAzEOQsKMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
