apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-config
    namespace: apps
stringData:
    config.yaml: ENC[AES256_GCM,data:86BMGophvGWcvMWILht7HPDlBoRGnTUn2CvKovnB3PbQYtOgKSGSrGx0HCygRyQ3txUF1zQ+rY1kBd6lU2klsHbyWhindWDzDLIKIp70bXhz73+3wZZdOFk939L4lGyzL3lyH4yIRufBr4DIjzUUIRiFcoxE/Q1fta/Q9OozoUsVHzzhZY+QC+6uN1tHqtK4bKfBndcO96vaDSauSybh4ZD/NoA7EZ+WsRlZvjFWJ8awoDlUU89rqU4jdJFaSigGFNMcETWrcjnlMP1ryXwwzg09d6/v6g4k/FfkHucF3XJnjJBSRH0kKRridfWPlGcVWuYkGlpfuK+wR2r3OOFspBOeIknsAEqNWjVl+d+Z80389MvC2o4O5TUWs4L8Wm9TGY0kE5mdJYeQk/r+aLJwCNM2adTaXQSGOphOAzuRyLwzOXGmEjiV7q1UVyKbwjofnFUy8F1Bnl8s8xh1o4bAeTW0j8CQ0RyMhROxxZL8KX+FuwUmYRIE4IL1mwM2pDC3EsXqrNnwYjpCs1/eMOeiQ+b7AYZ/YcLyGJNUuMkNpNButr3TVbVJqj2cx5WUEerT6MlHxKcql6iX6U2yejOEPISzdak80OtuTvolfjWRAJXIEP3s0bh6b+BMKoRGJaIE2JZeIdXcFFCNHyVTftyu8/hieWTa4SEK+IIpwY05iFtJCukyDfYGNs5Jqom3ZeDgaOgyHwBCExk9TJwm1kIS7nkAvlsAX1y5l9EVz32ZBYQcI5/h1NOKMT9gksYSTJj7q3VbmaNwvYE8zmYDsIYVu/bEBG//+XJy8iueLIaJcEcrWyXkQ2llwQj3+LEoWwL2MWo0n/cF2wQWnX6OQk0xj+2b2VeKGP8oOItzbwC186/k9y1b3r9T+k4SS8aJVe+vEQ7WbQuNWCu/YhOTM5dZgfQgJS41AXESmR5m0oKGIU2x9hxJftMVr8F0Og+K+gxavUq+sSi3HAAhPV7LnBPFnFOGc09KcLN7HI0GBc7gZqKCiE7yIFjaQ+M3SEzKS7SyPqjCdDRfMCii4Li4tbnlxkYFHvLjBPLqs92KLYu5+GdUeZrKagUD6ryL6DWHWtofl5RsGeWhmEIj98UlcAJtujj/VGvwL08bplbfQf3g/WHzY3JFHZ2Ti3QnI1SqK2CrcM2P+de0QpOTXa/Py1B+YnvwrRCqiGG1bo5T7yGWaPZb90eVa7Kk536AwshBtx3SSq0RTvu8XsNyj7MMiC+i2geItk2busllznr3CADIQ8ZamgkIRURBHKuLBWqi7tm+N4VXW9UxGyrF3XE8ur13GNB9NfxJGb+POPSzD5ORMFltC/VMf2/EIEDiU+DVgYSSeY8/u6dk6zoelb//aQmDi362nt4qLvAkIZNGRUsAC432TLeMXKYxl51VzAJJ7mO+gu1ClyUDfwttCjZm6Qqt/rG1gJLZKoTzk/EF60SQxrUSfTX6hRwttk3G1jBb72lEadqGrubTP9N5cd+UT631IdS9UapGvgo+GwDUYPt2wRtXp3H4BllrOuCQmaGpPdeCBceFZ9FVrr4STsr8NUdPaZyd8E/JHkvxY8It8LlOwck+VHKk52avhMbcH5zQnFuOLgiKQ13dN+TuXQi3MqS/LmPhcn3frTrbhvXpsy+tUGk34FZ3gtNKytptKz13nTxag2Uzk8QIPss4nMC9FKxzrzaKatc+VRhY5m4htQOrZpZYpg8aahDlqt4mzDh4ytDO5XoFaXHW/uVqPnN+mAOXTK5SOENmZbE1s13C7Urhr7YWi0iEmD2PkmAZ2ixzsmwDSl5WDOR8envhnKtiSexmKSLz5eguMN9wKsMT/sB8nt310Rmgx4yhyTdMyKMwsRxlZO334bTnBtvr1tCYzcrq73+uJDerABf3iMYYnSXNA8GBdjOD0tOdwHjMWxqWCVJOSfMMgUoY/Fecv3bZn24iBVDrE3xdzmWOvkGQBJgrZEsU6qYpyiasaFidRYjQrHtZqLpwVadKVt99K+WkLSWFqbn7OikGMMVFO9gjnvjxyR6WC1tw4mc7oAX8nWizNImONUoNlcE8mV8oDQTAG4Xm8uwz40LgrkBmdbaNxTSaZYkPf/+7YWNnEW8IIehq/EtMysWxQRS7+tHtdgFYxFfD+X023q7ojcTRUp97V8sz4GTmO2Ck91TvOiZ5v9ei2GaNgAGid25XdqnWFRi/qLDV8k/WqErovkN1cdsyLHfmAskYNlo+8No9MxSUbPXhE5m0XxOE/wskon1ka+3XJPVmQZk6JcycRr/695tRpWIcfUhk04OmO+r04+LhGBVyQFhSxzEEh79NqiAdwhzLYS8xd5Otyz+si9WBhe6A5M+Nu2vZt8buEp4lvCtonyqbsEULeyWtCSN8lELKvvIvZADfodhlFrH8K603STCP6DJB2/dZfHnqVvVNnKs1oZ5zgyHiNJ18qhBbh712GisMfgDJdfQEVFYWioed2/7LQ43KALKYjdXpErJc2tbgWkXNpSB/uh79BXtCsBEPT1N161SPt591ZQhkW9GIjS3YnU19pF9q7czB3b5MLG2mrPkdL1Bp+W9ZmEGPUMX4ME59YqEak9yYw/inP6UfGtu4/C4y2tRpYBVRlrzcqkBq4sMAeR63jumErxorhb+OGbYXDpeqHWyripwar9n0eMtyUtFte9RmlqH4o5QFWiE7/o3IlSd+U162iBmKfMK2HUMwu3hUmu5NzliGFBtzEPGNyG8U94dfQ+V3GlDktmxss7LL1NklmWm7hdtUB7DBbvnMS0VuLMoV0I3/+T0q9IZV+YdU,iv:a0hnE/oq+wEcg8OngNQNCI7iqKIK6RRbURcvrzAIXEU=,tag:Sxj2NI/mh3lKu5jZEeCCrQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVSttdEdIaldJM0pVL2NQ
            TWcwY3RmYnNGMm9kZlZnUlllR2JnT0lNdWpJCnh5eC9FbGxtVVpadVZXNUo5dnlo
            MXBIWDVRVnBSa1JQRjI4TEczVjdST00KLS0tIFNiY24xYmkzWUJROW4wa3ZWSitP
            MkpaaFV2c0g2WllCWURKb1lEUkdiTFEK/ky3O73HG4CMjvzQErYzqgNPotJMc0Dk
            b+bNtkwzst8o0FkwXgDPok+0fNBH9jI6q69xNrRzObZ5aH+qhkj5pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncU1FNHpsQk1KUmRtUE1H
            VmdvMGVLbjhQb1lUVDNnV2Vydno3VFpaUWs4ClcvZFU4YnZFTytMWjNkVk9NY0w4
            bkNONUZ0bSs4TlFLcWEwRGMvenpXRm8KLS0tIGoyZ1hsNzBiaGx2ZGtIQUpubmxi
            bUJiSE5tM29SNUdBNTZMYkoxWTdCZTgK5H0yfOXEw/LWyMWGGkHnCwsKGxTByFmx
            1kjoGXQh3IJgQkHsqB5IbbMLfLnDFP1oJY/RUN8Z5w7Ptt3gc4EMhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZGZqdWxaZGpkbkdhSWVi
            TStOaFNoa0hOdmxONmNMcHVDT1pZRmhCUUZvClpqRE1Jb3hUMG45TGVQdDRIMDhh
            NTlYTVdWenlOc0NMUm1ablhpS1czUGsKLS0tIDR5d2VOcjJYWFZ3TEVrQTdRY3pV
            OTkyMGtuSDFqY0RrckZFRlJkVGltbDgKZfuOTsuqasTOSIwHNMaSBsQPZABJRrtb
            tQ5L6DL/wpz/iCUyc3j1SBgeZrxRHsFsaME0nfxPPv/omrz7X8ruhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:07:46Z"
    mac: ENC[AES256_GCM,data:+WNkJjRc3fpYNBpSLv9egnWNH9OrTwQ/dypJ8mv0L4b98a9NodCW1aX2mmOuJENhMDMEaYnJUYBDWeXLDIAatWEpN0uutVOTTHZ2ePQCxOtL2mmz4vporRPnCNB9nOz2mY86Rpe7jYir4AHClfJoGtOk37QXc5IgRGMgiDDLIrA=,iv:E3mcsKwkSTAZMsdPa1vUl1jPnpw7f8VYsFj+BM548Og=,tag:zYeEfv2mYGC24Uv7U5YhMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mautrix-whatsapp-registration
    namespace: apps
stringData:
    registration.yaml: ENC[AES256_GCM,data:8nMzJPyladmGRZZLZMOsE0eKbqgX315RQ3d+xFvVJmcpOmidR3p9k7TLbB74hzgy+JqAf/Hii7TPtbXWolzKqE++I+/lgod9oulEMETFXrCujZXn5MRPP/g9vcuUQ+xFk9hnWq45taW1Qox6cTTAoKIt0/aOqtOp+2tRMfXypO24p9joNLx20F4oRCQjCIbJUeQMlUtWLAD8fYNCmztcqpaGUyy100KJRb05vsFkL9gF+x0P2Nnv+R23GCkQUzlA9+fhHO+8YeQazNjHjLN7dO+2UolBAkIZYP114VEsIm5u4ZEV+O5sa+GONU/1RLFjursoeG5sTMvKlmK62CsZEy74EINdGfkwH4Ff5OJ89+xyQPSRyg14XULlGY5z9Tes7dTg/V5o+U+dvc5CZvuFmWlRoBbPRXMIc4wRaUAtBuWQyRhb1tBwRvcvGJjV1xS6BjYZn5DhsmvKLg+kIbwhMnm92NRRDFx28NFfUeGwHij1X8SOtXAlcVSdhbqSJhI4hZQGnUjPMAuUm72dKiQqD8fwWWfhAygHWRKLDpP0ApvDVOAX,iv:vNTTkBmz2uapJ7uR980YTx8iiuf8eSKZiKymnF8+n7I=,tag:m/U/065iTNfj/iuOIYunNA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVSttdEdIaldJM0pVL2NQ
            TWcwY3RmYnNGMm9kZlZnUlllR2JnT0lNdWpJCnh5eC9FbGxtVVpadVZXNUo5dnlo
            MXBIWDVRVnBSa1JQRjI4TEczVjdST00KLS0tIFNiY24xYmkzWUJROW4wa3ZWSitP
            MkpaaFV2c0g2WllCWURKb1lEUkdiTFEK/ky3O73HG4CMjvzQErYzqgNPotJMc0Dk
            b+bNtkwzst8o0FkwXgDPok+0fNBH9jI6q69xNrRzObZ5aH+qhkj5pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncU1FNHpsQk1KUmRtUE1H
            VmdvMGVLbjhQb1lUVDNnV2Vydno3VFpaUWs4ClcvZFU4YnZFTytMWjNkVk9NY0w4
            bkNONUZ0bSs4TlFLcWEwRGMvenpXRm8KLS0tIGoyZ1hsNzBiaGx2ZGtIQUpubmxi
            bUJiSE5tM29SNUdBNTZMYkoxWTdCZTgK5H0yfOXEw/LWyMWGGkHnCwsKGxTByFmx
            1kjoGXQh3IJgQkHsqB5IbbMLfLnDFP1oJY/RUN8Z5w7Ptt3gc4EMhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZGZqdWxaZGpkbkdhSWVi
            TStOaFNoa0hOdmxONmNMcHVDT1pZRmhCUUZvClpqRE1Jb3hUMG45TGVQdDRIMDhh
            NTlYTVdWenlOc0NMUm1ablhpS1czUGsKLS0tIDR5d2VOcjJYWFZ3TEVrQTdRY3pV
            OTkyMGtuSDFqY0RrckZFRlJkVGltbDgKZfuOTsuqasTOSIwHNMaSBsQPZABJRrtb
            tQ5L6DL/wpz/iCUyc3j1SBgeZrxRHsFsaME0nfxPPv/omrz7X8ruhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:07:46Z"
    mac: ENC[AES256_GCM,data:+WNkJjRc3fpYNBpSLv9egnWNH9OrTwQ/dypJ8mv0L4b98a9NodCW1aX2mmOuJENhMDMEaYnJUYBDWeXLDIAatWEpN0uutVOTTHZ2ePQCxOtL2mmz4vporRPnCNB9nOz2mY86Rpe7jYir4AHClfJoGtOk37QXc5IgRGMgiDDLIrA=,iv:E3mcsKwkSTAZMsdPa1vUl1jPnpw7f8VYsFj+BM548Og=,tag:zYeEfv2mYGC24Uv7U5YhMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-env
    namespace: apps
stringData:
    form-secret: ENC[AES256_GCM,data:6c98vnNRK5gjob46w7I4KI+dBFB2lKMxgRx5JMkRSRu9iOq9P9/EdnPd6E0=,iv:E3oCYoDSNRz7NUGQ2fg4Y1rSzonmKPRusZuFnNAdQhg=,tag:zgbJg1owR2vt/9WCdJd1Sw==,type:str]
    macaroon-secret-key: ENC[AES256_GCM,data:tYSjRJpu0lWs0luYIqIsEJ0rGJuNfWAeUjWisbyjWL4BrQ2ZnpmdKw/ZU3w=,iv:kwleAuUk7nHqT1nS+3gulD/WO5vZq8huXhMmTGCaqRc=,tag:XKBwJ/PAzvP4ajcz+ZPokw==,type:str]
    postgres-password: ENC[AES256_GCM,data:Aq7f6XEGpu862reCl/Fk0aeBwQ==,iv:9w5pOrumrympndmaqrlbeKP8kUvI8T6Bc6xUI0FQTFc=,tag:mQ8MGDIZrgxx6IFRCBz0IQ==,type:str]
    registration-shared-secret: ENC[AES256_GCM,data:fGkof2uWO0pwYS5eZWOauRIa+K90aHMEd0CbZNZX1zZmzQfDVh2ZRGr+NEU=,iv:Eju+NlIkZIlzL5YvrY/AgSJLVfyySKJ00jEBIxBLExY=,tag:0ZeQxVHeO9VXTUCl1yYVag==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVSttdEdIaldJM0pVL2NQ
            TWcwY3RmYnNGMm9kZlZnUlllR2JnT0lNdWpJCnh5eC9FbGxtVVpadVZXNUo5dnlo
            MXBIWDVRVnBSa1JQRjI4TEczVjdST00KLS0tIFNiY24xYmkzWUJROW4wa3ZWSitP
            MkpaaFV2c0g2WllCWURKb1lEUkdiTFEK/ky3O73HG4CMjvzQErYzqgNPotJMc0Dk
            b+bNtkwzst8o0FkwXgDPok+0fNBH9jI6q69xNrRzObZ5aH+qhkj5pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncU1FNHpsQk1KUmRtUE1H
            VmdvMGVLbjhQb1lUVDNnV2Vydno3VFpaUWs4ClcvZFU4YnZFTytMWjNkVk9NY0w4
            bkNONUZ0bSs4TlFLcWEwRGMvenpXRm8KLS0tIGoyZ1hsNzBiaGx2ZGtIQUpubmxi
            bUJiSE5tM29SNUdBNTZMYkoxWTdCZTgK5H0yfOXEw/LWyMWGGkHnCwsKGxTByFmx
            1kjoGXQh3IJgQkHsqB5IbbMLfLnDFP1oJY/RUN8Z5w7Ptt3gc4EMhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZGZqdWxaZGpkbkdhSWVi
            TStOaFNoa0hOdmxONmNMcHVDT1pZRmhCUUZvClpqRE1Jb3hUMG45TGVQdDRIMDhh
            NTlYTVdWenlOc0NMUm1ablhpS1czUGsKLS0tIDR5d2VOcjJYWFZ3TEVrQTdRY3pV
            OTkyMGtuSDFqY0RrckZFRlJkVGltbDgKZfuOTsuqasTOSIwHNMaSBsQPZABJRrtb
            tQ5L6DL/wpz/iCUyc3j1SBgeZrxRHsFsaME0nfxPPv/omrz7X8ruhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:07:46Z"
    mac: ENC[AES256_GCM,data:+WNkJjRc3fpYNBpSLv9egnWNH9OrTwQ/dypJ8mv0L4b98a9NodCW1aX2mmOuJENhMDMEaYnJUYBDWeXLDIAatWEpN0uutVOTTHZ2ePQCxOtL2mmz4vporRPnCNB9nOz2mY86Rpe7jYir4AHClfJoGtOk37QXc5IgRGMgiDDLIrA=,iv:E3mcsKwkSTAZMsdPa1vUl1jPnpw7f8VYsFj+BM548Og=,tag:zYeEfv2mYGC24Uv7U5YhMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: synapse-signing-key
    namespace: apps
stringData:
    matrix.josevictor.me.key: ENC[AES256_GCM,data:/qtUymwAFU+N3JySaa1mvBrre98Du0MXLuNPKjozdD7wX1GQDCYEBxkau/P9p5eZOr7mYCMH/6gi565/PP4DsanSkBFf88tQZOTxE8XaV+gOReOzTjvlSKLTuIYBkQy5cNR9h8QciONvGeOD6JiKGGNa0LWizaamWg5KpHajYcRXqaogNpqwzY28ZX1Gfoi69snU2qdLTKS1F3+FoyeHxtMF8rlXq6aM9EAdAjlEHWHsOrt+uVySFAMwMII1xb64Uq/XTwrA3qqWaYDOWRC83AK4cm28O8i68O8ynvgnnVAgkk51S/JOgCKQtaJuDfh6YDBJb5SYb4xu/ADyCO40o9JVjSPJiq/JuQCHIUox2ijlNzf3TN1JqR6btCOCLnGy5Ti9yD2JzsWE3cGOWKT+9TGsrUXFuWZTIiCvxelhoF12clh7NLET14MFgS5fOGhC1KByD4pEtw==,iv:lN6lhxVGsgnksCeqOGfcOPFVfj5BmFxXCJ3UIhNVA1g=,tag:BLmb+h2Bl593lfbS4M8raQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVSttdEdIaldJM0pVL2NQ
            TWcwY3RmYnNGMm9kZlZnUlllR2JnT0lNdWpJCnh5eC9FbGxtVVpadVZXNUo5dnlo
            MXBIWDVRVnBSa1JQRjI4TEczVjdST00KLS0tIFNiY24xYmkzWUJROW4wa3ZWSitP
            MkpaaFV2c0g2WllCWURKb1lEUkdiTFEK/ky3O73HG4CMjvzQErYzqgNPotJMc0Dk
            b+bNtkwzst8o0FkwXgDPok+0fNBH9jI6q69xNrRzObZ5aH+qhkj5pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncU1FNHpsQk1KUmRtUE1H
            VmdvMGVLbjhQb1lUVDNnV2Vydno3VFpaUWs4ClcvZFU4YnZFTytMWjNkVk9NY0w4
            bkNONUZ0bSs4TlFLcWEwRGMvenpXRm8KLS0tIGoyZ1hsNzBiaGx2ZGtIQUpubmxi
            bUJiSE5tM29SNUdBNTZMYkoxWTdCZTgK5H0yfOXEw/LWyMWGGkHnCwsKGxTByFmx
            1kjoGXQh3IJgQkHsqB5IbbMLfLnDFP1oJY/RUN8Z5w7Ptt3gc4EMhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZGZqdWxaZGpkbkdhSWVi
            TStOaFNoa0hOdmxONmNMcHVDT1pZRmhCUUZvClpqRE1Jb3hUMG45TGVQdDRIMDhh
            NTlYTVdWenlOc0NMUm1ablhpS1czUGsKLS0tIDR5d2VOcjJYWFZ3TEVrQTdRY3pV
            OTkyMGtuSDFqY0RrckZFRlJkVGltbDgKZfuOTsuqasTOSIwHNMaSBsQPZABJRrtb
            tQ5L6DL/wpz/iCUyc3j1SBgeZrxRHsFsaME0nfxPPv/omrz7X8ruhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:07:46Z"
    mac: ENC[AES256_GCM,data:+WNkJjRc3fpYNBpSLv9egnWNH9OrTwQ/dypJ8mv0L4b98a9NodCW1aX2mmOuJENhMDMEaYnJUYBDWeXLDIAatWEpN0uutVOTTHZ2ePQCxOtL2mmz4vporRPnCNB9nOz2mY86Rpe7jYir4AHClfJoGtOk37QXc5IgRGMgiDDLIrA=,iv:E3mcsKwkSTAZMsdPa1vUl1jPnpw7f8VYsFj+BM548Og=,tag:zYeEfv2mYGC24Uv7U5YhMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
