apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:TIz1jPIXXnW5OSBR31+n51jg3tMy3hb93exQ32XA6ANBYXv+Xgnu,iv:msgevgUuyvcPUXtqIunxXtJDz3cbehiO1dPlgyjkw80=,tag:HoD9u2MeyirJurJbMB2oCg==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:9ssp6QApDEzh67d0P6zgUnsUK7SqEGeTGa/l2afFa/CWfh0SG39RqYYuuwmjMKdurPDEla8uzXz/Ekd5Ila+3P8n5RB6kzen,iv:gFi7g2T5mlzl+9vchPS4ZQhDGA/6sVs7xMUTbJ6yJrY=,tag:3iLiJV10u4GI8rD/EljkIQ==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:/+rFhYeSdXQquJDxjom1Bdql6I1o98raXFR8h7QKwOZdbt9VWiJQuM/7mXWXZxHUgZNKqdu8/yt7YDdHr5aSxGIuQyt8M2X1AxYkUDZlI1e+W7M8MIClSuGa2i0mrirD1ON6E92SVjhPeLCNTHvEgFCCk4eK4xO8SUH1FE4=,iv:8Qcq3WOJ9PscFZe5G3gwd/JnR4sVLD9ZxFy4Yrk6tIQ=,tag:FtxjeRgiMe6RrSljfGFJhw==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:R+8ladulBjHDxw==,iv:m1njNVm5CHfIjNBly+/WaEHLOKz2otvLSOXVgi2wKbE=,tag:9kL6W5kMqAEc7dp16XJS7A==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:IFLpk6nVUnoDly/UmR2jK6nL7e80vxO+aCZjWu/4nqQVig==,iv:pvRYAl/iDWKN4xhg+T8DZRMJoNZ8YkbdeUpCpzej5i8=,tag:P72AFS7Uqg7+tlfyY/XIrw==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:A1du+DnLsK1LA+eEt/6hA3Pb1qc=,iv:NEgcp3x1UZ8T/yWrP9CB3raKvnNbS93hGme16/QQ8Ms=,tag:c22Uvd0oMzxDSfhmg4UqHw==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:KRTe8GxKDnifB+e/09Zl68hB6cZFg+WsxqpWTJkRP0VhW0g3b1hb72pIXonqPm9tu2QktLmaZSOPFELohOsAVg==,iv:BOkRK1aTKjAni/YweRx/KhCceo051q95TsnZ5q+Lz+A=,tag:2NignVuy8JOvuBH2Y5asoA==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:ATd1HzgH50PkFpRJzmk031SGlcetvoEB0KmBGc/mNz2i8qUE/IT+HBcg8w==,iv:iYn4CE+lThwZFEE2HvqldFvh/lkZFazdUVWQ6ukHc8s=,tag:eORabQ/SeymG4DR4375AVw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:UiFiTNeHpjTCerqqsYnaH0n6IIGeyvH7LsSvuEpa4/LWE6+WiFAdrZvtZECrahGKsxpigGynR1Eyij7UNoP/EPMDrh50ig7rxA==,iv:iQZBGsgJqE+ccf92n3RXH9ZESn4NdDLGzkoUPJ4PbAE=,tag:uJAObg+X0fbPzhFtbnMYZw==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:fK6Jc0ZYAvOFzLiuJGGGtYTzqj9o/4Om24qVZVbkqKFrxpGwP+QEYxD5A3HsGkBwY0yp58BMh1bxpPez2Q==,iv:Y4hlexcNZxlyN3OS+pJrUv4hPecxK8Bpj0oPgzfDXt0=,tag:ZIdUKzhUaexhQHHZbW/kWw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHT2RJVGNtdjZ2elY2ZGIy
            R0w2WW1kWnJvc0pvL2dCWnozOUJZaXFJS1U0CmpiR2d4TStpdFhhb0o4QmsyZXRS
            NWlPamFBM21wazJGMFdaTi96a3JFV3cKLS0tIFFja2ZiMUpLNUllUUpqYm9YUWtr
            U2RKV0RXam5ZU2JUOEhEM21NUTRrZDQKvIf+S2Li8j1jpvMf5N6c0U6KE4iOymM/
            dZFNjmAnfS6xvkfsjn9fmxTtiu7p8GNjxES0u+0drPG/dV7e6Zod3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVnhTL1RJNzlINWVPS2Ew
            bGFTZmVlWGdrNk5iZ2JIcTdUNDVBMFpIdXhrCnIyd2lBSVNDRWR5MXhpcnBocHY3
            UndMUGlNbU9Hb29rWW1lNXBzSHgwek0KLS0tIHFURHQ2aHllcDVteDZ0WGZvQ01B
            K1Y0dEp5emJBd2VKWFRvUGRjZDNaMVEKDlYdCvZcrTHvxXIQdFzqowAvN5yJNYtU
            WCb7rUC2Fx4U1oZccZNzdxpFxZWc+O7Xork/o99MzwOQhRGAUkmP9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZTBIb2s3SUx4bUQ2RTZx
            enl5dzl5MUNhUXlrWFI4djJmbmt0T25WU2dFCjhxb2w5S05hTXU4MmRSaUptS01R
            VzkxUDMwSFI0N1lmRWtDUURmMjM2bVUKLS0tIDV5aXpNV0Y2a2NHV1MwUnpzU1Nk
            ZmJrRmRBclB4RVl0aE55c0VjMHdRYU0KBUJER4O56g3Ib/HKMURrgWRbm5dGt2CM
            0pC95EiS3Wud5j95W69Z77SkmRb2k+FMfIqGLl/3NNU8aTymZXtsVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T02:53:43Z"
    mac: ENC[AES256_GCM,data:jXqYTSyvVFu/4IlsESW+mdsZrNumRLDjwk7gNDc8Jh0dJaOQYszEI5bTp+MBKAZ48xwcVXLMpvb18pZjuZpRw+C8vYRoL3hs5zwbAVITMVg2zvfKc1Fz2HE+lTcE/ULecfzY6gAtQOUugztnpRgFnt1r7VEJ98Jgu3wQrhGeyTg=,iv:07UUdK7iDUp6GcOLRikW5iSx9A0+KWLKVr3I9NrXXxY=,tag:S7cFd7yELIySzBwxiM7elw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
