apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:azhaXXUosfansyXkd0kP3w63R6X4OXvWCHX7PQZb8Md9IWtxsLNUB0QbMiUEopbrSJ1G,iv:afL+Ckebyd0Mm5bNdSEPagmaBg9RQIDwa3mhy8ddctk=,tag:J1UsQgq6yW1uwhsfH5JBqw==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:AQN5Cy2vIOZCm6Qpqzim+NOH7ILxMjhPmNccmRzxfmrJUmAmd0RI,iv:22Gd1G4uR05jEZkRqZs9htIoTAaeHte43F/wKnfo63Q=,tag:Ao8KDkv3anourjk8KJ6EnQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:LdJNrOr+k4Wsk7h4CZbHdJqvUAdwfqvas52e0gKABX0yMeDSJN7eiA==,iv:XtrnjpFUapL1p7pIZ7qGBeENrWxwVlKipcQwuR1+be4=,tag:D79gmbBHgKAt4l876QVr/g==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:hG7uuhJEhZ3Vk+iVhLF9wYLNR61eKHyh6DTyneZ6exnhw7H6e/CaFfsJTMmEiutLE02C99nUokZg4ttm74Ap6D397OvkTwuK,iv:dfiXI2Lc3q65tksjj5Ttwr+A3DaayTwA7tzW/7PJp8U=,tag:tyMTK36QZ1SshXazP9dddA==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:u77zbzFBJwhuv4UeJnnVURfxDAjhTCv/EeEc6eYCtN+eJVSVsqDqflUrs85iwfxIpKFjlKkRJKO/kMer1VfUEu+5czeSAI9AN82d9TdwKLHVAglsY+kDnv6RQ7uhEAVo0cB/9SePCvv5yKsWu2t451PP8Xc2HyMOX/dpVAQ=,iv:nzIe8Fnt69kLH2USy8v0e51Q+BNv92h5xcihW0FgOfk=,tag:FBldziR84hV5PThrbarsfA==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:i5JTSemlYHUG9Q==,iv:yN4gl47xNkdBZgAdRWN8Dzz17RtHaEcuRFuC38kHP+s=,tag:pv+dbTWJ2a51SQNyd5X1Tg==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:1qVzYeNqAz/ouMVQ/lCzpzn7T03cGr6u5GAwWn83bXlplQ==,iv:hxeO6YlXLAeWQ1XirnwQIIabHota7PGqGGUfRf7KBRo=,tag:6yqtAEUP2UInDHqKxPWZ9Q==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:UzRz5OwH8oGs4bIkB/wcosa/+vo=,iv:Ivvw+lMM9fP6t+zO/9ikYFkEXgH7uPO/1Fz1TrAQQNE=,tag:2Noc+23iwBql/+UIMi0k2Q==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:5TRcHPI8GviPFou8WeD2yudec1vTU4M2P0AAFstfvNccywqRBoEHjV535Cf3Gb+0VQPr61XUbXmhPW4wpJT1Fg==,iv:s4mCdnwxKJtvLJZO+LU/pBxhPPoL0q/te6x8v9B0nNU=,tag:uwIbRzB+z6f8/GQbZJCn1A==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:XvjCT1ainym/barHKDlP+Z9AUf8VzFJcDKXlRqqR7vTFZDX4KEdISKVsIA==,iv:Jf/980TjckT166utH/r82azexoNlG0o4zftRQGZ8Mdo=,tag:2y6/N/mTzGZamwGhekSgcA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:f2DX45h9f5Gc1AtkDtPthBfYnL0XNKp6DzorV3diaWhHx6StyicJiXQzGQ2AiSaAkbQ57HtK/ywmwc9L25FYBrBRIoxhCDpVeA==,iv:TrmgQEuMpb+DxoKz9z8aduEHuHXwlg3BczYe1FrwUC4=,tag:+dIuBUL7BbX86TSa6ZaFGg==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:dvw8fEVxA2EYWNcDtJurJesvOFcg2altgYR+snEltSQRLKLIX1wyKMS1uIF7MY2eVbGAS24cas5DbilkLA==,iv:Z2FdEU6TaNJI7RSzl+HIrypHshhoAsuKcK8zen1/mY8=,tag:oP2ZE/GUXYwib5aNJH/bcQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRjB2KzhkeHBhUTNmNXBB
            amYxZzFTUHZjbkxOQ2lNWENSNjVJd0MzUVdFCmpGZXAvRlBlTGhzS1hCWVBCcnUx
            ZE1GQzJYMXF3bjhtY2ZWaGpSUmh4WGMKLS0tIGhEai9Zc0JaeTgzN2g5QzY0L1hs
            a1czUmRDRTQxR0NudnFvUy94bDMveGcKU+w9w8FL81nTXEUofwYRiTbwhNabkncx
            Mp2lRH01ff56IlEJ02EBsK3u/9ljIDGdge4YCtQ45abHbTDVFaAyxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVlJ4ckE0WGR2YmpHcVdX
            bXdmTzlFdmI4UnNJSkFPeU51V01sWnJsU2pVCmpnaG1qTks4MTFwaXY0V2xvTEYy
            dk9ERG1JckRENFMrZGxWWDRJQS9ZRjgKLS0tIGtVYlhleDRUYWZ5SHdVNEp3Qzho
            WDRGUmRzWVFQaE9WeTlSUDNqQ1VaZU0Kxp/wmSz3rMTakeGjpsg1tw8FRypfxNHT
            /+GeLsh8K0Zs/jB61O0w+QVTYnVDfH04rH3eJF8Ha3M8pJCACOPY1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTysrNDRjYkNXQmU3VnVT
            TEZManJXUnpJVUsyL2JsazBUYzVLbEpVSVZVCmtjWVhYR1N4NVJRNkoxZjJ0Ums2
            WDQ3eHgxdXV6M3NWQlFxdWFjbGt5ZlUKLS0tIC9TWUlWU2hudVNFaXVYZ2dna0FR
            dFVaeis5dHRESlkwYzd6czd2V2JRYW8K63TUM0GGfct+ItR2oMvTN5lXbdbag62S
            oPoofUKABel1AW894pNYabHE287FmSntG3EhNw662mgoUWlAO7ftZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T02:07:06Z"
    mac: ENC[AES256_GCM,data:3O3Rmu57rs85Npw3ZKQE6uOL6z4vvgqX4J2JGBxb/vikXFYL+d6siQennUjKShlqNEeMdrqqbbH6EaQgxv5g1ucVh8aWmlTBqoADxLpvKt4mFPyaC35uKOFoRgLwg3Pr3/JdMW2KNJFqPl9oYQB3ZwndHx99uB9S9N0VYXxPmo4=,iv:ZBueJOZeptsTErOyD+D6IRL2s3KLk9g3xQkRXzruLCE=,tag:qz0tYLzz6NZj0m4Sacr9Pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
