apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:CPLJK+1bBWhHq59TJ9izp+d2ozpGEDQMflLORfJy2gppsrFcGhVq,iv:j7rjoOzhCKlp3z8fkkq6y/OS4NkEy37Tb9fNxs/+ado=,tag:q3j6VkK/s9utxmVM3yprTw==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:7XfpOpYZGKkuag==,iv:ozsK3Hjy+rvFg1EKsu2mTUK7ao4E7xERnRBeQb3qmPU=,tag:kodT/zcznm0AiDZL4gV1KQ==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:cjnTIscHlNPTSbiFJxvo5DrBJFY5bbonOECqR5m0slnDfA==,iv:89Ub8/WlhXsi675UptuUyqRTI0Vz683hNVtYAXT2WcM=,tag:h7axsSxEakgRxXgIOGkUrw==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:VRh0bjxLXBPQkNKXEtg0DXJQTbU=,iv:P3cAfvAwPvnMTs0k3HR4RsKQCHW9QnOF5FvnHhcJdbw=,tag:XAmHPF5xpWIYZQubYh1SCw==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:ZERIy4+qXTI4RXKHCYhY1YMTuES1gUCzGaVNhTFAp1T1jIkr8PAufUBhR+YOaIgDny/rqNJbuHfd6mSx4lBD3A==,iv:Aunl2zeErZhDy6q2tQ8vnvlAGOoeJ5v9mQhwSsy2u2g=,tag:aJI/cQu8AatwIAdbNYMdAA==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:mG3OttjsxKKYv2ZzuQK0Eo6bWUiVQvh38pXgue6SJNo6KudCvX/68n5tOsYVTwVyox8ABroWl/225fcyVA==,iv:h3wzz7b8my5GI618voqy098KeJp88WGzl/OY22Z6Yps=,tag:kEm/pIPI+Ukr6VHGPMdqsw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdnI1RGpMNzZIZVo3TlJi
            YlcxT1JKWis2TU1wSjlVNDhiZ0hNY0lGbFYwCmp0NzhEeWJ4T1d6c1g1ZVZCOGk1
            UC96TmM5azR4anJ6NTVCVWxoNVM4NzQKLS0tIEpPWU5NVTNPcDRTNGVOUXR4dmdQ
            Wm9QZUxzMjZVWlhkdjU4MG9TTkJOYkUK8KYji2gKQHFuXqJD1QRTFXsXFCetqtfH
            6uQbyWAPghl3TtJ4hyTHvyD7o9/ZbY2CmpJ4BHIn73IUXAhnZljXUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKckRLdlRVcmY4SXBlalJL
            OWJoenJMcnMvOTNXMlBLekZUeGhJYU1qL3pNCjVTUmkzL3lpdXg3cWxFL0s3SkQv
            eWpkSkErREhORkhtYlpkdEorV3JLREEKLS0tIGp3RENGNURCMW5PRUN5dEgzWXky
            cFNPWThSaDhBTzZkTnk5bTllWjlUaUEKw1dGIfy1JNhybG738KynO5FmHmEYRJBW
            KK9zD5ZKMVr8K/zzfcj8WUQOzhhCDhJ+e0MZvGsNcesdQg4Fz/tGmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVkxqbUwrbkhEdjhuTEVM
            MGs2SEJGQTVXcDhKOHpzWURzUlVqaHRITUdBCkN1Sm5NMEgxczc1aEsyMW50cUFF
            SS9TUy8vZ1loNGdFUjQvcUdpeTJURU0KLS0tIGZwRE5OY2VoamFnSmwyTzBSSjZB
            dHJ1NEJvWGFnbWszYnA0NXovTUljdmMKSS9Q6+YHLRtyrRX9Qz4pDa1y8M908Y0V
            rf7l1YuVg4ZQZsT4gb8Rp/ixcvZejN6GTKRUJEyc/WRz/AIUzLsUQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:10:47Z"
    mac: ENC[AES256_GCM,data:CDtCZSGqUV9E7i5RMqKhaCKp2yDta7IY65w1C++yByInWgjRdE0NMhsiZDDUw+WEskmJObOk5mpSh0yvMwdo1zXPb9jqoQjhDARyoAki0G9fA53D0W+ed/g3UritUSRkKE63YrjEiYlW5mVSV67nq8WUWqJJEjEzMZmKDrtDlpQ=,iv:mQtmK5CFB19QIhn9inAJ2qcIB0sJWbJzeVjX4AGB7cs=,tag:apFuPOfX+r2//QpUcSFyLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
