apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:LFNce2NWcoKgjgD9zxax91P6IJafh4hiE7gfMhnCpfZ3RgMFlg3x,iv:7maHrklCYiEi7XpSs5abKCyX8FPTf4yuEQOgWZQKVhY=,tag:5md5Mv/XIVHjkijfSQh4NQ==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:WRsjK8VizqtOCJzlkk+Ez7etSUiV8O4Mmw5/68YQejo3o+UFe6xRqlXaCSjsSQYSOn8CNUcD1Lqz3HmCWfGrsVf3t5xl6F1P,iv:/Jf5Vr7VL8k+A+JvOtEDuUESZUnfZhDxWCMyLoT0zQ0=,tag:g/RgGOce6KJLtFXCSOBPgQ==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:1a6DNCDMqQEyf/IVbIrLtDBQBpH7zABLjmr+S51Imq9heTE3+DDM3hOmGmXiPyFYxsFq+8HyyIpOIC5eIojYm+tgqH3EnXXeU83Mzjm9DEgVDs4vqwZdU2dx9UDnrQ8+ws9QDJ6wpQL0hLX8Y8FGQ/YXe0iFNNoVZBYFVqk=,iv:Uyqg7qZZ9xvoKq4YxG4R8lJvX0sEbSzOC91zZfBIBXY=,tag:esR07m/GMM0fx0vhTS1dqw==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:T2XGsrMU2KEHNw==,iv:KL4LTLBdSu8eoeH0t4YrA4nRKTpKsMI4QkYs2L2QzPE=,tag:dopR08hcgFGC7MT5tY05Ng==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:azHl5O873qxu09LV3j0RNwAYP1ZX3KS0WIJmM2q1bg+s6g==,iv:FzJN5tVPL6JnzytkAd2Ogy+rF0zFDM2cLsrOKSJKLzg=,tag:mI0K5kg08ABrm5Z+1BG+5Q==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:IzE3RXpG5R5eKyZecWYnGxPVddM=,iv:KEyx4Td93YIllDoq+J/Nv8A2BeEJcyJg3Ivs1IkdtmY=,tag:T1k+YbCrtpNxygpmvxGLsg==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:NirBVufAApxRXwKErkdHI9QhjoVOOr2U2/w/VS0EBGtjuSOY0/fd/SpWOY5/678sougwxTxsuGeSwc3hu/tWqw==,iv:uO3IJlbWMLgQcfyTpiYwpzmOcwSA6kviQu21Z51s6sc=,tag:NISa64KFosG382u0vvo2vA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:YVOysYbCNz0D2IbUkbAQ7OZiz8jD6dki5dUL4DRzhn6rkjkLwvG3NNMovUVtrIxShAtw4YU692ONZyAOk+U4Ro7UTHJ0TNi/WQ==,iv:Jcf+SCasAUs5MIG3r7SYvXsOBpZjHeC5rqwSpA3eF/I=,tag:jPuC2zY/tqS/v7E4flaInw==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:vt5ErGEzG2Y6iJPHsUBUnFmRZG2rb+kyIgeu4OScDX2urkaOh5i4HgUGKz8T14cQwnCiErGUwLb59pjNxA==,iv:9ZGPeOicwwwlM5d86yS7nAOluWD7IGeRpNOCHpmeFUs=,tag:eQSJzROCDNhUGvvj8l82cg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZVY4d0lXdDVDa2F6TDdq
            WkRvakxOdzNTVjlReGUxV2tMTk81UUIrVXpzCi94d1N4OTRRUElRc2VSSEQ5WlRT
            dFVPMjJBYjBzMDZBbWJoRGhkdU5kbjgKLS0tIEd0UURqR2tzV2hTWTZNNjhua2VX
            U2FSZjZGQ0R4ZmkxK3ZTODJjWm54bm8KyqrTccr4bCUIMDEgr1rsZDCp5bUBPdPT
            au8WwpAbTqdmayn+fKdyUW8vGxLDbkzZ8bm514r9Z3fqmb4J1jk36g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWK1ZWRHMzVzNVbjlvWGxV
            V3Z4YklscVJRampFNk8zbVJGLzlFYTRETmlFCnh2eFFqbHZpaG1uRVI3eUJIU1pw
            SGs4Qklsb1ZzN0NYS3dDTEZjV3E3OGMKLS0tIHJXMDIrS01BOVZmblVqWDFjSmpt
            dDFPVHpUbGF1Z2dZU05tai8reUxZeVkKJRml2ibYJWh2FjuHWp6JecVxiyH7uq11
            igRLwyjrEGXj67/gYF0eQMrsQgV9Cb6LWyu9UG0k+AxlfQPjiHue9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZFh3ZUpjN2JiMm1YTUlx
            TmpaMnI5ejYrVHJvdDJ0OHk3QUk2bVp2UGhvCjBkTW1Td1lLM1lQckZlWWQwQnJF
            SGJiS0dCbjIxSGJlZzJLYyt5eTlNcmMKLS0tIHl3cUR0cno2ZVd2VXFZVWpucGJY
            TEVHV3BxQXdxZjd4ODc0NDRSNzFPajQKM52SLtlvCCGHD74OGsXfZAaMN6oDOB+o
            7Ac8QnXfedffLqCzMe9KFA3CVQhDJzvQW+/S4rR6ATmi8jvbC8PkjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T02:35:00Z"
    mac: ENC[AES256_GCM,data:HsC6oeonusLYSynvOpHlfXsdyH/+dMAa3NZaA+cLIY5MjTR2Mr8mhbXY3XzZulgULaAp6zraBs82Do0E1ixcMELEypwtKOX49NlkWalKxmfiOiSAfQKPR8rDqwNJ0ZsSdjnTcDnDJ1+SHLKiNOuqVbXHWDKYesk2Ffm/xtxBHgw=,iv:q6q1BTL90+GoKknCp1RvhP6J7vyw6LnAFiMDn3r/0fE=,tag:2o65/5BQyqON1yfApZvpwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
