apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:0xH2qcPsjxRZe3ZD25zfRy4EO70/S6Eko6YHwH0Vs1ELBMf8n0T+,iv:ziu7dmzvQdDI9Zc7YNbqFUrZ7DOgT/LIISD1QhQuGfg=,tag:M5fo1WnmOpkUcb4keJft4A==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:24imlr/4LZntiZh6UDSEF1kROupvyW1GrHmaqV1zSd1pUN+dNqo8hXkG4zbioVnG+eJLz+HzApqA5P2q/PNTImqL4QTeu/To,iv:ze75y6Z8BABQSM5/7MPI0zGvy45SR3Nf0Kr45oO9C7k=,tag:0j4QAfguunXset/xCg3z9Q==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:kIUxbX70a7TjMU8a+E0Sp9ddRcGmYK/eMCrk9DGjQIxQXP90wBjBmuvnfCOrmfAffiZvwuo3h2FX0ObVUQdosr8sxxp/Hgzsz2G8o1ziHFe5Ck4G8TvTrLxK/rqH9afZrUvf+mEmH52k1uSDVT1YnkoQWN9TXi8XAqRenc0=,iv:o8H3Bv9SmaAFuW9EDdFVfuTqQnBxZkYdJbwtb2x4otg=,tag:GauxTwRCVCUNGeaNdqOOkA==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:m1auB//382045Q==,iv:D6UYD77LQJxL3GxinqHdYHRCcpvE+Iqt0//36xoOGl8=,tag:HZr2rgxJIbFWyRWOXuUrew==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:5vl7Tuy2EBbeGR0o3US6MXMSsc8/joEvRa/wiJmaf4xfRQ==,iv:eIbvwCMs6dsC7AJlviBGboDBs2SpTqCb/WB76mpW+MI=,tag:W1S0NbokYFkhLUj9TgyLSA==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:NH1GKHTLqLjbJGKKJqb7CKPUvUo=,iv:TDKj5XjtxKALhaXX8Bp0BD4+qyXc3nn2b//3QOgwd3Y=,tag:K15FyHUxZXYURrTKJjWnXA==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:M3P0GZMutTVN8RAoKI/CYXIRbFI2j/XqhRHyPSdddpRX1Q3B6jOQjuLq+Adf8QmEd379mu0i0OcxTjnq2Hh3MA==,iv:59aDR2MCge6EjVmvsclhUZ8Lh3CjY6pVgvAkWoE44HE=,tag:ODmVf0s2IKb+IshXsZH3lQ==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:a/eSrABp9EBturA2AYm4FhNnaCX0sfcNFdeyCDwp2H5NqiBXLco2lLCUmg==,iv:TCAsao4Y5YWPCObDb6N4qHQx3fwsCfBWKY1pa+waOLY=,tag:DG/dkMW0oedHugRNTLMaOA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:ZZ88DMWhsi6yEt3tJCxyBgqiWdOOg2yc1uyXE/SMOz6DLcWR9p32+wdXwptkMtTzsOWYQTLqWfbr0wihNPYV5qqP6MSUmKef+A==,iv:NmzCMviDkCRbgYDNjWCkUPVyrgWim1xcyRBruFnq9Hw=,tag:oJczoOS4G1F67O9THwJiTw==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:LcK0G3jkhESX9lQ5tAjdms/wkEIHOIQJKcJ0tG9Q1FcMCLkc5GUZGqmESh43fee6UW17+Z+ruG/eZ38+KQ==,iv:pGX63cZRrPEy1oluDvykz4ta5dH4BuWZ2G1QWXIZsIg=,tag:5Ihu2031G2IRtDawekkKqw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM0huZnlQb29ZN3dyN0dm
            RWdsVDRHZm1SaUttSzc4Rndlcnl1MGZsb0FzCnczQ1JkT0ZXQXBTVHJxczBKZ2ZC
            ZzRSU2Y1bVo3Nk15emFZRSs1WHYxSHcKLS0tIC9aaWIwUFE1aWQ4cW9LUitWRnh5
            L1JuZVQ2dmZQa2IxWUZJM1B4M0hOWVEKgfDawppeIyWM9dV9ZOEZNzGfUKQYlHq3
            D9xToImpHbrB8l3H5ZIPPPdstgMT4+B3PpgzMZSmPJVKjvaDdssEiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VGtnWEQ2OWVRSGNHSWRu
            OFhCYXhiN3BCRDNJc0RyV0ZFTitzWHF5WGg4CjZKWDUvdk9QbnEvSUtEd0ExSEtn
            MklWcWhoKzNUSlllcmRycGEvdnNDR28KLS0tIEo2ZjVkay9ORU5UZjFlTW5XcUdN
            NnVUL3dxSmtkWE5DNW1oU1AvK0NFZWMKjvrXhFO0XH0+ZyUDvoaYHZEA9fKqGCGT
            LNqDmVAoY7N98SjuwanWdf33VzVp031sSJrhAZpjGSUv7Xk4nwk/Dg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNk1vR253S3RxS2RFbU1z
            RjAzZVhqV2NiMWtTY05kV0FrYjgrNlgzYXhnCnV0bkZKVWg5b0VtY0VoOXhTRFJp
            bzBFWk9ickFJSDllWUtzZjI2djhsYzAKLS0tIEpYNUVLYWptVHFwWERNemtnaU5J
            Vm53bWR0alZhbHI5M0Q5Rnp4QTRxdUEKsk79RF22/qEtCvZhWzFqz4RWgvNeRhpL
            BWi5MQjBXr5T6gTjRMJMeM+oI2RQcNSdc56Q38EEBiMXB24goRBvCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T14:20:12Z"
    mac: ENC[AES256_GCM,data:VWf4HgIb7UV+aNiYnKVbRkDPg67Br4p7IYVwo5DuV1HSS7RCT4ocKuselqtUBAK+r2ObaLQG6FXK+bZwVmTPghZAZc01RbyOz+2JgJ5aF6saTaOwzL4nqKL/QqoW+uXagV/ewmVA9Yv8xoSax62euccxPWsMR15WRjYSX/sZvys=,iv:SQERfy/Jbrgf42wHk+kgBrbKJIFA7O84foHC/HpXpqM=,tag:TTGqClmwznUxDNJsrAoVJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
