apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:V7JRoyEyORbuKMfHuD3dAUrTsMFSmzE/nZzfh6SFSQ8Gz9Z7Ai8S,iv:N/09HjoRhjdJmNAUYle/a5QMdrc4GFh5BSDbCKx2epI=,tag:Ic9DgQ/NWeAb8P9IQxlODg==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:9/aPvTlLKxGjsCq6lpH8Y8HEyY/hzjCgXj5IUiD01EspBMf//aq0lHwrSwOZ7zS5gVKaOtLEJP1DzRAUSbQWedjriZDVrYyK,iv:BwfFCPcuzynYESzjk1ywBmEdfoaDY0eqoRLhyjOU1nM=,tag:nthqWIIW0pyY7zTh9wzV8g==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:5t4XxmYi7WBM/n0C2FSUZxRCAp3WqPN0lRkE4382jst2VqMJU6WIH5EiGvD/2oPPZscbJQ1hAmwHPAMQOtv3AWZxeYDGzdqMj1WVDXc6LOOrtgY+DPCK9QHOuUkfA755b0Wn5TvnWOQLTVyzcATKHzFb5XBvN7Fcc+Ad1AU=,iv:9IQ5m0j1ndiQXnUtCY6W2j/DSZzrnOyI2PL9re39EFQ=,tag:V/92LvKg6H+qZ8pKr5wCaA==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:qM0u4hZ0uZqhkA==,iv:G8y5qtkozyX+c0GOd4EozEsOVws7RJzjkLbcB0r5J/M=,tag:PibPcNKVgIgeqMs2lJeZAw==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:x795xlTSyjarTVTAx8xeXpE+uEoMzev0DLkelyWt5OV8mQ==,iv:ooIpaQrlW0NhQLYgEPcqVFTiqxhk1hcgP4YKKssheoI=,tag:iO5Ia1XV8EApwmA7xV+n1Q==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:mov63hd53g+W/DcNhlL5k2N0axc=,iv:1OGk4PqwlHn4CXZwmjlRU6YQ6HiicyvSvoQwmpT4gkc=,tag:mwpH5FRM0aMzBOBaJzR9IA==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:nDigUCAl3WHlla0q6cIXK7uqMmMriFROkVn0v3Hx2isjYC0ut/SU/zFCr6ioqWosA7KadfBmnRBorlnMe9Mb0Q==,iv:Oc5W6KdPq3e5Clr6Bt72IWEUbuhZHL14VSq37Md7S0g=,tag:BXARbQu+VMMRg7nloSxi/A==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:okR079J1oPS6leAq0it5zCruVOfIIFq0wL5CufClPDi2h4VRoFaByMyklQ==,iv:+Ngso/DtxfXwz0pH9d4Rj4qiOndxt28Jq8iSoF7yAVg=,tag:WVj90wDgNL05PfnRKpQCmA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:gaCoXxR18meM880A82WghmuaMqmi6BVXPcU/gC/iAbMvx65BEcLx1l7dGHcgdAvE5cQQB04SsAbjqF+cuw78dMO5cgiz+VjwuA==,iv:7h2FmjM3Np9kgUEvkUUPomtxtiC+CAtrhchl0NVYRYc=,tag:VlL0e/LYAocHUXCPJsDmnQ==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:iaeJFvuiEVoj9TKpucpw4U3ppLc449URhyBLczw+R7br6AroCh1aZgTYAyM9iHP21vf6oa55PsQwYhS7Sg==,iv:rIMVe8BkZ67NkpvtTKCeR8q+6doQl+E1Bu6OrMQnwLU=,tag:4FBRrgqgssknDJmfSOja0w==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WDFzbmhaNzlzdUY1Q1VH
            Qlk5Rkl2bmd2U0hPOCtFZ1hrWk1KSllmNUdzCnlhY3FTT2xPT0JkdVNuMDNUc0VS
            bThQQjVSQUl6VWZEeVdCOExkYjZFaEkKLS0tIEUrQStQRk0vMUFyUUUxNDhPQ1pZ
            bkRaNlc0TG9hWFh2NWFMdS9OYTBJZ28KBCp99kIa3tHNzqAMrdEsx+TOjHm0tBP1
            nV/2FhDeIoz37SdOs3HFOedGueC6tzsJHWBH6IPrGOLnBFT0HuzaLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWThvd3hPYm5BS3p1RmFK
            ZGdRZFBCVGY4dTJLK0tjOXZMa1k2cTBEdEIwCmtxanUwUE1leHIwZHZLa0M1dUt6
            QXlGeEhLaWxXa0pnSldwT0NGZFhrM0kKLS0tIHhaNmN6bWcyd1Mvd2RtRG9CR0Zw
            d0dsaHFMdkx4SXY1WEFkWFM3UzlURTgK7z28/2bsg8VJsKPt3KcgdmXhy1EU8jnk
            EjUy5tbcoErO6M3nH/XONVqcR9tv2z4qOxzz0SeP3sajHQIzoaPgTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM2RjS0NVRW9EZ2NycjhR
            aDhrMHRNTmVSQkZQbXErU0NqRXg4clIvQUZZCmJzN0VkYmNTaDdmQmt1MTdRQUpr
            cFB0TUdwemVQUGtLVlI3SVpWNUw4SlUKLS0tIGJVR0xuZnh4eGFscVU3dDBodnNm
            T2JCdzF2WFpLQU5hNlViMzIvdjBvUHMKu36O21XM5F/wRI9kceZseSUfLB93I+sj
            O5Dg6OUsRztzgReGadBBCOaoOh1PVHxfOnkgWBNTrt6vojuYo7t/Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T15:41:00Z"
    mac: ENC[AES256_GCM,data:c6nzBlPB+vhTcCtsQgnrpyeF4XbnUZ7lkQwE2KfFYJ3bEzrELDQAJe3T6ueBmZvSEjAZcv5EJHI2gGCnC0GEy0oBJqX7J/f42yRD3LSEm4236sef6ffIABSg320OHIDoySOBwl4cZE2+whrokP0QuFAwmgB3ofYYagmWQxn6/5c=,iv:hd3KTeHAdJLSRhd/FH39QNvYD2z4a0nPd+yPxKmTzjA=,tag:H1Il4h25Q9bIgadOBAmOHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
