apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:8saga5LcGTHgsPZk4ZFaH7HKkaYKiVQqwlOSb70MqNeZogvQPrceEmRJRk2fn3ZIzEr8,iv:A/NIm3O66pSFX/4SfPKFt+eiLFC+W8C0VwwWIGnxwSk=,tag:gWzUFWdY6SozAbEjm3+tnw==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:kst+wMmtITMxP0hIm8zrMiTbvst/vFg4Bl+fsLebXd4TVD628LnJ,iv:f8nU3mzZ7LfYUmBsBS5TPXuelp7U62B0CrZBX/NiHeU=,tag:1kJYrF/yrUYVHMezwQWoBA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:N070/IIrnVd7QYAd90sC6pdOsKVE3jgJojUnio7lT57iimpHFhk4Gw==,iv:eUIRzwgvWKGK/jM5BxgoI+AoHYu/ymCrSHR9+F56NNc=,tag:uB4vfIVsDzo/6ACQ9kNqDg==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:My6Y4pTZGTIfM+drpr/SbxK/yNolFB2QiZf0OSs5vtrdPGjwAbL/liV8Af7zU8122hbfiIh81/eGq+IB9XLyQ/Sv455mf5K3,iv:/U7Ke879kFBW3NA4eMgAU+6fXF01eM4mm8HC1ysu3NM=,tag:kb4N8GedOC+PV/xYNhxVxg==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:VsGQd4suyFub+J+i6wuLfe/kNig8M2xO3so0h3RhhaBo4xvmFkhaqaiL1N1PLRTqokPRYFstyU/qmAja4gI8JWOStrohFumvPiym/g5Y9vfXudXz1nenV27fvpInAyQ7i1kB7i/XzS4mgY1VAkNqxtjabp5l/Cuq1OLSykc=,iv:Enmfe7Ev9bM3zXj4nqw3yQ/eoCyraWtimYJ+ppLojx0=,tag:n0Oae0M444W86mlcwh3iJg==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:QF0YR0mGLwm2QA==,iv:XKoKO8AX9vjncXX/U8u8PM5MtK48/y0QqUk42Gb5oNY=,tag:STbQMm+V2qE154RLhL02YQ==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:Tfz9P2rLJd1bUyKg1a3n5Fs4MzCdkuSqaSsbUBDeRA9bsw==,iv:hEML0VBTU+LxiaER4VALtNXtud+tJtNfazkhHXbjTi4=,tag:BQygNLE3byK+WKWoMMRYbA==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:1V/Ns1bblgWJ+K9edCzFLIGfwiM=,iv:UVsXsvoXqKmImZFJnAI8Wl1TV9Bfx+oybUW/dM5Pqts=,tag:Gl3UYq30XsCvH30rZSKJvQ==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:I0Kg3zjAlXJAP6W9z6OkhR0i2s/mRNoQ0DgxHuINGcO0G5/5VifUA+L6ry5nNSBq7wM+LZzJpC9/rhv/r8frbw==,iv:hzjtF2r+95MjL5wipJMlnrhBUy1rU2ySVd232GfQH1k=,tag:QZC6sXbore4afquqbi1mJw==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:ovrT8WdoZKkZEEMYXwXcWpOE2LrfowRPKmHivF+Ob5F7IalpGA4wxAO7Fg==,iv:xuvPZqFiykF6ALNdHdlCxaGppugL6tAZkQCxdoFa7dI=,tag:aebLACO/VTcxtrvxa6AfPg==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:WJOE48wWnNz1x/r4onwOQnFr7NkiXKaIqx551wQI9BNynIDl6Q6xKRPMVyKI0ExcBjWj9PFgTurqyD6aj3KJb0XSdf9dzvr7GQ==,iv:GfHXxuDgKq4PTq+eI5uyJNa0/6uAljBjZVLkMhOfyWA=,tag:gftJImlN3GZ88jayYYRXGQ==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:dN0z5JMNk9KzrtlYP0MYqUrnEhVDprSpQK/xA7nRlkW97ADp3V/zZ5xAG8dXnl9t0Np1IKhYN7bvf/lfog==,iv:N1u1dZ8Fxw4yahdEelVRWXb000wsbijJThm9Onnx0xw=,tag:RiVlKS01/F7GwVwIVkYbpA==,type:str]
    WHATSAPP_BOT_NUMBER: ENC[AES256_GCM,data:rj57O4LdjVCTd3rrHQ==,iv:x+QOyO5cD/OxszqRCz1GOd8qNIlh+1Ol2yM/nuJhjxA=,tag:yPI9NvZT0NvkwVT/GNBMDQ==,type:str]
    WHATSAPP_NUMBER: ENC[AES256_GCM,data:TguNpJQRbrtoFUNEdg==,iv:ahzV5Bsa0XWcPjIRQheepKqjmuKgtWZ75fouh+9G4+U=,tag:3fmwzX4Y+g6BnhFR5VcxUQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T3VXOTZTcGJUQUh6NU5w
            aDNZSzVpZk52S2p0ZHdoMmNtR0N1allnZXhRCnV3bThIODhiR0JQZ2x0TXlHRWJj
            Vy8wcmRZOGp5aVllQlkvVXZ3TjZXMlUKLS0tICtxUENrSnAzeXNEN2tIam1iUUFN
            VXVkWURkZFl0dlJveXBaVlZiUU1NRjgK2dOJMkwtoi2f8XPd78ewqJrZnoNSFzN+
            hcpy+Tgk2eMhVgjP12FYqnVtfOPx+CGpQFXGgDhVGfPafWhfaZr5QA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTDg4aFVKWlc3Y2F0NkxU
            VXFTcSsxUHB5a0xYWFZJc0J0UlgyZEx2U2k0CmlvS3RDOXczQm4rY1Y4WVpnUEJ4
            MTFnS2pvQ011MU0xeTlIZ2lzZ1ErNkEKLS0tIDVtRTBEMVZMWWVxcGFqNGhHd0VL
            cGsyYktrSGNNeXVUYXVuUGZPOW1hT00K7QmLC+usSV1C9i+Xad2o7JtijU/de2XT
            M5iSptu9GuT4JNsaXFDmdg8XCmeHZmveAvGWKd6CJC2ad0M3UM2q9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIemdDTSsySlZxN3F3TGJ5
            ZWRJUHJ1YXkvY3hRblh1cDYwTENjUTVRZ2c4CkVOMzhxVHpLekEvREVDejlWRmVW
            aXZaZkxRVFU5dTdIdkhtOEFzdVdGSWsKLS0tIDhWbGhBTzNWSFZaTXdwdHFMNy9w
            cDYwQlh1TkgvRGxxM2RoVlJqbXQ2YzgKn7z5emhDqnObfGRbDlH7SeBXYMXrZTTF
            uf9i9XdjxNkqo3Bg63k0R2JQWosyc+UjYK9Of2suOCLTHOwrFZogow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T14:08:56Z"
    mac: ENC[AES256_GCM,data:Xyjxzy9u5lxrHbm6Q674ZRiE9D7ltkfu1GbdTsEH23e0ifcHknUKlXBhU+wGt5d/khdqfiYHxiZK/OALfV7map2Zrt9whljIz7e9dUQQ7YZR7NkK7m1wzHDfp/EoC9NxTRUCoArwNYfqfOVXuBomBB6l7fwhpguBI+KbWRNwjbU=,iv:yeBrLwJIUdZ+MUIIGTkRlhKFV93Myfxw2ZaQz5XlR0g=,tag:ProL4JH/Rq10JqMMFwp/IA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
