apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-config
    namespace: apps
stringData:
    COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:rZeIxsJ5YsQdAtUoST9jSvAS+Qi7WL9b99GJr5YsmDMU3FXFrIobGw==,iv:mArCfNvIAXg2PdiD4ZqOtSBH22dq6NPd2t/inDwuD9c=,tag:bc8PVddV6nNhsg11TJhMWA==,type:str]
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:vD7OIA7fESemU2FC6LbopDDh4cSVa/xoc6LC325/RwFWOnuvjPzopB2vUdrCVYdMTPkZ,iv:725k0C2YqQUERYQuzSKCJYPUQks6WBbOWRWjnnRKIoc=,tag:2YHB47tcFKisIUHNyjcEfQ==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:ouIx3sMuDDGkBWAQeZYoGnwlNI41+SAANfrR5c5X20RXTSwg+I+H,iv:0q3VmEixiLtQQPCTRTdK6xZlo0XderCquPRso4Wa6qc=,tag:X92nCux8/Ez8akbSirz0jw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:4JbnAZ21oIuokAAem33+KWuRa8NqqI6uBwAhMMdfhBB1tH7fMJCtBg==,iv:i0/olc4BH0tXUkQdDycC8gPLNEdfLMqxCjweePOvIgk=,tag:2Z4bXt3kLSQhSZvTTNLPUA==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:m+nI2ted9k7UJFcAixJqIni6GfpL78VsHOG1I94kIpIrAp4iEwcVomogROABWfkX2TAMKsznu9q9izBBt9avwo9hTfivOLWy,iv:v3VbUCUtkNd7CY/pQOv4Kry9Dc31DtLrT1Eou10ZxKA=,tag:t6VcEbwg159SYz+hB5BSNA==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:r7n5oKS58VFCx0HEukOJ15MsG0ja+Bb6cVGEWi+taV4gsE+Dwl9pUgifyi9fDfYUw4uCfDKSsJZahEMqo8qqx+glLo6WWN6miN3EuFTIuh3lIMTHCT8wN8Ydu0BUrViExwX4M6wuBhnBlT5NYVGGkh2FXXI4uwDZ/juQj+o=,iv:14Gz2OHXzYFndrm1JHGXvd9mhEPCuR+Co7Fkub7ApO0=,tag:8wvYWpD4Q+HIj5QDCdijwg==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:X0sg4Mr1sQai+A==,iv:ghAC0bt1/8FwD6tr6vYdX49Cf/ZKxPAjRJuict1Wwic=,tag:1PIQKdzvquKFU2tphYTl0g==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:0ryPjZZVKHuO8xKHijDAQwTTf2xhgtLqyYfktPj+IAVAYA==,iv:yrOzmJXceg8Z53xgTIG1Fc9qkWCN6dDBAvPwKdms9VE=,tag:nrImHThM85fTRWOr8PFGsQ==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:d9x4zeSENcU72OQdmLL+JxgBbXk=,iv:WisgiqjPi4WwYMpFgUQgEKJfg3OvWPfBUEsIF5uDfBQ=,tag:0qLilMBSp7qEK4EU+TPvfw==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:tpbsSwq3dEj1oZanZIbxKg/T85rfrrenSfnBtWh04zMPdfjw6k6BIOnKMWOeHpsW12gjCXN3wKSdRPmyXBkJlw==,iv:HOX7Pfzh8D/vKnWmzYCqLTPQsGyUlUkFZ8hNMjARUg4=,tag:XKnMYuSQZdduBXiz+Qsdlw==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:7J2MYJcBQ1KC/X/KaqQt+zHLLCpoTARNwrKdQt3UOy4Alcyl9ofTjpLBZw==,iv:W1cbhWY8fI6CuqKLuirB0vNOwbzeIlBOKgXKGle1dvo=,tag:fXPRf7u9rvnilsx0Om2mDQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:UucIIvdo95eAo5GZlj0FYYdcaReEOAnhzg7Tc5PiUD/i7GbmoLyO/a4/9Z4MBsc9Q8ku4bhfg8E60Wzkqi25KsmKJFMClkAQVw==,iv:knYIL5bSWtQI2Dwtyk6OzExtmOR9F174gfwwNTR6czs=,tag:grWnFJzXSeUYqma8yKTPxw==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:8LyZz5pCZArlRsDM+b4NIE2d5SOqUXTI62PhpBn0G50Itrutp/xlv9PRbYEPyXcNop6C0sPkTAEJ9NEAbQ==,iv:8bjWEbycuLUg9oSDgn+pT/MASZa+EBa9B8J/i8jic4w=,tag:K/Pzy29+OHNxrISbv/gCvg==,type:str]
    WHATSAPP_BOT_NUMBER: ENC[AES256_GCM,data:Z1SvXM8Qll1tnryKPA==,iv:l3DQGK9lo2IARrkRFKkUf/LAwbuFmnvv8ZqhP8zf9bI=,tag:y/z1r/XHMKktUKAJ7+ZqEw==,type:str]
    WHATSAPP_NUMBER: ENC[AES256_GCM,data:f8Cnlj3Kh7HPndhk/g==,iv:H59V1NOXbx2t17EqrBEwyBrmGtW8JytzRILPaguLrmw=,tag:gSPneCvhEeXCPDoKbQveZg==,type:str]
    Z_AI_API_KEY: ENC[AES256_GCM,data:N5hVMLx0aUCoTx48FTJ0WDIcSv4Ld73jfPkfi7A8Q0vdzMYphf5AL5v8+3dUf5MnZw==,iv:LLD+PfvPHq8Qqx7MFW2lEu/+Pra4tTGFPDsSv7XOYt8=,tag:Qw0B9msg/8bkLQey032Qkg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVDlnTGMwTTA2RkovM1NS
            Wm5YblBDeDc5b29YK3VpVlI2cCtzSnkweXd3ClhEMDdIODU4U1F3L0JOWUhyWlhS
            eHM2Z3VPUVBMQ1dDVHgwY2FjRHZGMzAKLS0tIEg2Y3IzelRWYmI4WFVuVUpHeE9r
            b3BxMWtva0JOQTJVUTdOS3FhdkErem8KNaT3ahab+dUMNBqiD481G3SE43JL7p3d
            XNU8k0xrgKGIWBMZgkcwifBF8ks+B0BPBA0TPEovYvESqo9LulkebQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaUhYdHE5TE1lTWlqcXV1
            TUtUVkkvaDB6MlV3RGQ2SGhFOWVHRDh5SVRrCmwvd3BNSFRJdkNZVTlDTkxJOUtO
            V3pxQmN2MTFPWTV0RUlXTmpCeVZlWEUKLS0tIDZoSEhZeDc3RDNVVXEydjFIUG14
            L216Y2hDUTBGL0NheHh5cVlWRmZWdVEKYb55W6CN7yjCpSragyMuIrYSfdUg16IC
            FWjfDMjzFAhEaW2gjPqMcqBo0qaiEjwwN2FTRk1no9bBfaxEoh46yQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYllUTlZidllFOXpzbjlC
            S1RPL3ppU1FLUEJKbzZDM1ZBVzVYRHZoUUhjCkxpTjNPRGtVZU5KMXEvNkZvMWw1
            OVVGb1NtN3pTalRnZy8xSFVxVnpoNGsKLS0tIENOazlhekl5WkJVMGtTcm03eUgx
            TUlkNW1SMVJBSjJoUHYrZ2Vsdlg1NUUKOIo00Ani3TD74S6GX98VzPMjfi6rIPf0
            jKEpdWnZiLd032aD0Zg41paOFa5AR+63osQmkHFAZ2ouJAkUF+LRNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T13:17:24Z"
    mac: ENC[AES256_GCM,data:t6rE+0kUwVmyMBNuxMNCF4du+a2qUhtHQEu97woBdpM1rOb+BgK/Klgkttkl9YqS+mfuqh4vXntv5+Zdo0O1DEr7p05lIObtbR5CoLMzMm7Lip3E/2kk4GcHxeA9uhzAWAKdyx9pEktDt8NWblx0SgBMYOJBkXKBmCQ9RiD2gW0=,iv:IowdFTXMzpcLhsiXRmmKsBDLkqQQjY2N1teAmn9wvo0=,tag:G4bNI7M3ANBz0xiUK4p5gQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
