apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:G2ZVJHEyEnqznFuVtX+789H8CFIyI/nHGNnLmXBaamEtiJ53lBln,iv:1x7LTteobI4rdj83PonFO+8s/1IbcUGyKM460YJ3NkE=,tag:KbQTuGPjXyi4BtPaMRihtw==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:pHgqL/DAW4ZH/MkUTK5rH7epVsQyquDyWTE/wV4UbyjJyTCDEPxO79hpYgMd1huqRm61G5oTmEP/xpgV9cXRgA0Z7gBYTPcv,iv:DQRxUUgHyiuLYZEEm9sXtM1Y03nyWDKPL0o6G/BYrUA=,tag:2FX0ATEWfTiLhVvcEz9rdQ==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:hwntz0x3d8efQ5/wMtChleloBYeIOdi3UIRc2s6BD/jScWcywuS9SmtgofBeV2lR1fyyF7c1rG2K1LyIA7dBIr199T5UJCgY39iaQiz+na+JI8qF5AB0+UUoeTPLK+kO8MZHkc+DdA196J4F+sjRwdGvtxbu5yqUqgVnKS0=,iv:yR6BLUYNZ0vVYAUbjEAehzR/1BOogcuGUvE2h14DuEY=,tag:w0ich5foiZpzgw/4S8tmlg==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:fasQxsRaF+vExg==,iv:cD86DoHpcdv8lwWhhNPcogvoG480/QDsVmbddxKX3+o=,tag:aqORM0MAU29/m/STzIfevw==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:7lMQn1KlV4VmabY9BcVf6J3YkwAdZPEO6NCT+pKkpOOE7Q==,iv:g+LFdRgsefgQDFUWHnqxb+rUhXrpd+uytYDGnu4ih2g=,tag:xivsNhko2P1+wZdRde6kAw==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:gPUi2J8+zk5miIe09fQNIOt+ucw=,iv:sbUwzhjz6khGs1pN5fgQ2dgeoMOxKU+bk5yBXhnp34g=,tag:xvRCjjaAcRCgtw5NePpq6Q==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:Z8pJdzVsiWIk+9rAjcuFWL4DnmZ7wI5mhbERmA/8FEuWtm6qr+G9tZhEzRJ6m85JzaaE3wO0oR9eg+IS7hmq2A==,iv:jLdjAeKaIQ0Qxq8Ei1OU++UXF9nY5d7j6focwEAYNtM=,tag:EzxryTF68fIXMtUPUR+IHQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:+R01+F4vfIP6RgMhwYeuaSFK1hLsmhbiViS2sZgN2MePVc/xpFVGRYJ5pPlCrIuwwceJw/0uvoBDStNPgYWP0jEkjmDlxIYXpw==,iv:aNOFgeZ1zIooYLSyQyEplQljBeiP4xk6X0+VL7+/RKA=,tag:Bfz+P1UF97BmkaaQjC2tAA==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:0bgyX6bHPn7n8epJs1fVKNiQ+9FMFeSE1+Q2UfVbOxjVnecFanKQbnbKwW/8cWNHrHgC4aZVZ9Hdziu8LQ==,iv:q54th6WkVteGkBtKeKOaMqtVeHT7VQltQwrx5kvionE=,tag:qL3RySxd0G1h4Ig+gOZXiQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieW1ucVhQaUJSU0ZxZXN6
            TjNncGo0eWJlOGFUcXJkVTNRdC9aejZYREY0CmJQZ20wRGJWL1JzYXAybGs0STRB
            NHNFc0tXSUxFczRvWnoyOGdnQkdNbU0KLS0tIHgyWnZGdDNsTWx1WHAvUnVBZWdS
            em42dkVNemNDdXQ4ZFQ1dmdwL1h0V1EKJUIdcvXXipN733LLsAbwBlUmdls60qXN
            WYIUSkMVwUBl+AVi0USAKef/ky2oE7DuMhAFsJYhuJ6j2QOrYS/79A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaFBkYjduTVRvMHk2WmJW
            ZlZuY1NQSUNmRlQ2SjlhWmdZSU9YQzB4eW1BCm9MaUNpbkdzOTJ5TjJlOUVlWG4w
            UGN4blNYVUEwbVVQNDBSdzl0Q1dqeTgKLS0tIGpkRmxWRU8vUXVOemVDam1wa054
            OFRMbHpOWnFnQWJHS2s2Wk84L0ZsZW8KngWmIX6eoADczxDTN0dWfLpUiOnfhYKQ
            yxm5NYm+mB3+Lytx+HWqMcInMyl5H9bpx1TaeL+0erQp7dITMj1Jzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bks2VEk2bXM5ejN0dUFv
            TU5BQWE2S0I2MWdBa0V6b1Y5K2pWZ2ZabHlBClB3dnNac0FVRHFkdTkxYWYxQldX
            UTZUQU9JMEN3OFVjQlAraDNJUzFGRHcKLS0tIDYzUFZyaHdFeit6TTRnRzIrVDdM
            OTRDTlJ1SDBEVkhvVjJYVVVML0p2MnMK4wr1tWE/WRBhNtE7y6o9wqoIfLnFHHtL
            mZ+A43MVHQgPm0+7xrpZ/Kvwj+4WksesGkZnCfSCEy4gdM7dv0yqBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:49:45Z"
    mac: ENC[AES256_GCM,data:P4v+vhStDVKl5E9czmSqNFhAXz489+H8aBzmzsNUsdcxePwS+9B10MonZ7+lugZUrVeTOq5RDMFptwVaZdK9F89D/yQHv34Noq9FEQ3iipEvaJhwg+M7ZtG4h+vaDV/rfZgKDrNuK6luXDBP6NU3GLRMzMB5ur1bxbZk9UX88tE=,iv:Z3be8YvlJcH+znh2PGMuTPQGyDBaI40hmJ8ZLyWy690=,tag:tTET3qOYk+GFHaWTxp23PA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
