apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-config
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:C7go5Y/IlX0IJGQ3bLIHd5hx4VK9Z/lXXeEDqyzjgYS4t9+3Th4Bx4XpsP8kV++gPU9/,iv:azkY/gdf3l+zjloYiZTuI0HY3K/FUAKoJSQcAxGnW/I=,tag:BNDiYcrTvOv1nJRt+BJ+8Q==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:l2hMS3KuFx4118ItCfdBGbsGEUczZagv6CsR3NGQTxtOOhD9FLMR,iv:m+yvJiQh67dHsHHfc+Dn3NlTWT3LO0FLZLgrSQmbDlI=,tag:ev+Ah2SeeWbEk9vB5ogSjA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:zd2ofrWu+IpPr6JGFs4huIGtwOZ2I66iGFzpcfEET83r8rZA5wmM8A==,iv:L4cCJsNIRDgbQT7zXk6TXJrNLdlFKISL1l5fsEx+Uuw=,tag:ZEsY2AlN0egol+p1FU2q4g==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:RjGxiqP+7eULI46x0YQy9ruY8LoCeJBt3kctz0rKG7JpOMISH0o2anVlT4bIr/1iU3KhQKpo42JLumCRNGCLV2VwGFP6fUdT,iv:NtCzXV/Tceuegoe4bOA5RhexG7OIjqP5zb1Z7Yw7dcE=,tag:G7fHg+C+Wc1Fj0rBv3Kutw==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:BZwMnXAhuj2rh/fmRVqC/t3PHmHc/x/gZQF65ob9YyXTyPB2FM2SZimRmLUwnbxAGURkInbr70Es0y1QqRoJyxYt66zlSBQvi5JHV/SKDDkDHo+2kLmJnqpRJdDu4ZIa1Ay2XS3J2QT7k70yNCJbhkQ0tg32+y6LAvF0/b4=,iv:vVyJEvCFZq7tnI/q42vhz1jTg0bVSJqZz1vWVBYyxos=,tag:Di3kXj0f+atBkoUovFpJpA==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:SE1R9a0AFaPOFw==,iv:pnMUeEaHXmOOZHva9LUz5+KZHhoWMX0yRWJa/lWQw78=,tag:8nL4FLxqnn3T6XtcpouOcg==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:miTsohJXPRMMy13GbvDs8yW9fCeh0Ff/gowVV9sWNfbzrw==,iv:Ql2/imiwAjbajU9qIijp1mCR4/G6R1YdyeM/ClxQKAg=,tag:RKurWQOl9NfCLgif4hEXww==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:wJkCGfen65+y5FY9LXbP9x4cm7U=,iv:pleJp0q45qHoXSnXDO3yDXkIXnJZkfIr3zMQxkSh04c=,tag:USwn/e2UoaqNhQTxf2zbOQ==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:Fxv2+dICZnxiUkS/qwgoOlr9+RZkc4NZ21zRWWgvEVL/f9i+nLTK2Hh7e6C8AuVpWJNw052mW24m+nBmVN3T7Q==,iv:M6G7OJgAzBusZ6zEM6EaoufzjLX9EW9lX3Ciah1yg3E=,tag:cr8aikeI9NLzJXA/MrUZiQ==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:F335rDmyjTh/8+wYVgkZOtGcs4yF77pKBDQoyQ4FnT9lhnDOMqM6SdZrXQ==,iv:MVzWS66RkSJsmadvo4WVgTYxIL6VDlYl5PuB1qQgLY8=,tag:pK2JD5V++B8qtUw9TLTefQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:NlgTXzTAkGlEAxccNWZFAaaP0fs9egeFJyNHykA9TTE1UfQVcBrjfE46gi64oLmJLwILf4h/bs/0SMokLN3ziqi2FixOqHedNQ==,iv:c8as1HjIhcm6jwcZDv/A4DUqlH1nuBAaIdGLRBzivNs=,tag:7KRHO7kdXLVFgHc1unYbSg==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:W+sIyo4zm45N+gVMeRp6JCW/Id3f3qGjv6ILN3WdmKdlzx80LgW2h68vpNVUXQkn1fOsWJjjDxBodjL/Hw==,iv:6A3rx2yLM9oi1zFFJXpKzZFcZ/uQIOa+oUF7DA1dPUQ=,tag:LpWyMXBMF/OsFVj4mGSdkg==,type:str]
    WHATSAPP_BOT_NUMBER: ENC[AES256_GCM,data:hwGxK77uuSxlqY61Vw==,iv:qb1K7j8B4vep1j8r65GTjt7cHPs6cBTG0Btucug2/cc=,tag:swIKOcSkP1oP5cqLSp82sQ==,type:str]
    WHATSAPP_NUMBER: ENC[AES256_GCM,data:RV9c60krY+UVwezMeg==,iv:2RrukM62pzZuNLObEs3F3ssCKEUS4fy2qNr33tm1D0w=,tag:IC+tWqBYz45ud6JVtxfbSA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK3ZYZG1FTDFIVnJkaVZS
            VFZMVFFMTWRzckplZGZHWXlHNmtwQndXeVNvCkxqMG1WRm9vamxwR2VNU0pzemdD
            ejhURFc4NXVVMFlqMGNKdCsyRCtiVDQKLS0tIEd2dkk0MVBYQU5BczRMUjR4bVVH
            S3pMSzZDVzlWV2hPeFIxL1V0N2diNG8KNR4yuBcmimn1wRKNButqKki22SznPZ+P
            Wy+nZEZFfpY4sWTDRlHJFJ39R4j6hHklW6VK5aHFokkg3d6Ohm+dug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWWhOMjA4ejA5WmNVcnhH
            RURhUDVxK2hWT0cxSjFxTTZ5c1lCM3VMT1F3Cm1XbFdidUdIU2pKckdRUkR3MVZ1
            emhZWW53RndRY1JUY1JiTHNYSHFhenMKLS0tIDFnSHl1VWFKQUJtVzZuVUVHc1hJ
            eUsvZ3lONW53dVZRblB0S2t0QVBQcVUKhIwQxrkYsHs9z/XgegeU1PuAWeDdI7rK
            KaaIT4dcUlYs+xaiOS1F48UUAJJ5mtdylzcnLrmV1UWHbz+kKIwU7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZFpTMy9KYlhnd1dsWUQ2
            aW11M0Q2ZUUxQ2NwZ1k4anNRaWt0Wm9UMEdNCnVYWHlVbVBSSGwwa1YyVjFCTXEx
            aGUvQVhzQ1dHYlZLR2x6RE5rSlp0NDAKLS0tIE8ySkJwRGh2MXFaUThSOXpmRHJt
            dFdzTGYxc2p0QU1zN1N6S0FvTU5oVWcKr6LXeAL8FpADN9n31P1PRa412VQufLGW
            syvKp9F8PhsnXCNWFfqPwhsLhB2s/yNJETPj7h3GMnkpnqmk80D98g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T15:33:51Z"
    mac: ENC[AES256_GCM,data:1qb6i5llDjbFt5OHg0vXCCyETyMPIHRcc0zH8SLqi8eaol5hgQhlMK5EpoEtFFSR0FMWu7777DdCkBGHrpk9Wk8/UhSBUEoJ1ugQu54Wn1keT8mYbx70vBGmg8VHbzyakOB4IZ7PoeQhmM5afiWlDrSbkh7Yr7QARCANTYAsMwI=,iv:VxDWRpfydABtzEqXs72+LBuyIqmtDeKboWyv9nFK3W8=,tag:l1dnjssVRumXaxv8rXQ8Bg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
