apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:oCxvFQPlHPoixsohAHY3YhyseRPKjmuYSy/oh5732p10GXt5uZyn,iv:vpfJT1sEjfu8bFf9HljbNwf771EM7wuG6nTrVQcRlRE=,tag:BTHOIbvzpiFjLXM4t5vN1w==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:T9CpGdFjwyNA+kg8e3gvwQWLj/cF1R3WMmaWLuZ6lXeMjSa0XLLvBr/2fZiZz78pGnoGM1I0suItbQbDr6VO9QXvNt8536d8,iv:I4QlsHo76tq17vMQnDj55vLC7KJbX9l9PpKI/snsdaA=,tag:0zn/bpsuaN/skYcB+36tAw==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:vE9meEeqWSy+Pnr4V6F+Hl+ewIpT5bXcqM4Cvfdzsidkz/wZJDwbow6Mlhfdcf7s++/nTTYrerbN30KMu/WyE3/Xk1MJUlN1bbW4ujYSNmIzhBTuXCXMimrEV6nJagDDJKDzoFuiO5cu78+652vbNxQ4fMbxDCYBl1WcE20=,iv:gM5tDd/dMZ+akjHXUVuIWV5sESXKy35v8Mv1nteC7nw=,tag:5gtOSuD8r8z9TfKCMyrBmA==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:w3xEvsk8NE8L4A==,iv:/0zDGZfYCqBn4hbyRv0qRmWry6ILKycSOJbOdmHBP8w=,tag:6+7Np8msRkk6xOyy6C2UBQ==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:O280SEj+/0Jz2KTxg0GRBIMS3c/vJgrZpVdeo34+LA9Q/Q==,iv:tf9ZDRCEILuA3FYW7vUG4PiGgOEzfWPqKilMiRVz++g=,tag:VaH9gAkauO1rKjLhLt6/IQ==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:m4ZvCjh4xltcABOOa9GtL2e82Jg=,iv:WWL5zY3VA3fQ4ggMqPSx4qI4EkjvMtit4H4BMAOQATU=,tag:97BfhpfFEsxdkJwC9m7mGw==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:5JIm+MPzUS1L9kO7vdXb2Hy0ZW9PJwp0ZZL2zkLsk1irkK12yhnE/+QuEW4FSmXnf9Wq1BZzddYY5W1XOXGPhA==,iv:+wat6X1c41FblwSkZ2lUEoxafbw7ckn5ViliW6vn8Bk=,tag:Rir0nYW8t0ftODQkKCXC+A==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:pvQPkiaExDD7lEIuCpsSKX/y+WNsyUPoclZe2K1P+CLVCOci/KMqTzmo8w==,iv:JYMEdHcJ37kl/79YUfA1zYNXRJ6YPfDgMTlQS9MgOxE=,tag:LaW10opgIHuLZfJP1hI/Lw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:GBKGKXsJV6A0zLi+gklBoNuK032yvFIL5xf3MQNC/TU6jmx4/fiySHCY61+RoZnmPJgt8FDJZBc5G5CX56qOL2oELUrtxIBiVw==,iv:64hIQCZdt8pLMNs3JFOeTlF867hMzUxypNX79Uo9Lkk=,tag:5jQt+4tSstlmk1uSrCSzvA==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:0qD588jdehE4qyATH++k9yy3H8b70IqcUT7Snuv6N7o/31ugMkc54pFF2wL9f8e7Qs3z6dqlvwew6/8kIw==,iv:VaDLV6k/IJot7rkTp50o5qKnLuJQKo8UP9wlpqKmZlM=,tag:PZkEzrmgzw3zTC4JZqG1/w==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVVpIOEVHRWRtVm5jbEV0
            Q0VhQTNCaWhtSkpBblZoeHRaNW9WVGxtUUVzClBRdjR5SnBpcEUwMlFFSjBScm83
            YWc3cG1teDdvSmRtOHJnNXVtZjIrckUKLS0tIFdoWVd6QnFpcjFLVkRqYktYcy9Y
            WUJvbVQ4NXVqYlJ4aVJjd1JDcE5wRjAK7++SdKmRknMLk2b/mbL9zFIiz8WhAmEB
            BBIvU9HxZXflHRIIlVXg+ZeQx2mwrBgW71T00CYDcdTp8Pls6gX0Lw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVTk5VnE5MmNYMWZVZm90
            cHh6WXV2RGNPM0dMQ0dxeHVseW5LWTlXQlhRCjBXS1IreWlVS3dSbENja3hhVWlu
            SldmMXVyUlRxenNUdmJuNW5jQzlidFUKLS0tIHVXd1p4U3k5RWwrc1o2RXRMR2xS
            enk5bEF5WXJCZVNhQkZyY3BYcU5ENncK2NK+GjtoEKBhskwY1vSLZLO8QdVNEflJ
            SlexC/8qHY9c0DwvlOqZRMXETFMmc0JnB8ULM30BQ/MR5aX3Cv20TQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRUQzejZZMkZEdEFzNTNt
            QlE4Z1ByUkVvUkorbkU3M3pVTmM1OGk3SlVrCmlOTk9oQmlMK3pFYVBRRjNWeDVL
            NkViM2VOM3V4b01hOGxXY1VhZHRJUTgKLS0tIEt4ZWxKWW13a2NpRnR1ZCt2MFUw
            L24rbldnREk0bUZLcjhiNGVZMlMra3cKJaq7fv5LhuaGuNP7/QaUlej5vlSqDPim
            83URlPNqZL2Xg44WVypK4hkWm/5C1TLzPPLMo3TH5/UuBuS/uRHrNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:48:56Z"
    mac: ENC[AES256_GCM,data:/QbC4F77nK4pKiqneeZZOu0BtUjTsr8jVBU0LT6cL1Xo/P3OxcCs9nfySCKA/aZocMLREqFlJfvVN0bY7l56jTqRfJTAtyO8EfLvuk8qD5xTtrkncPpZI+uLpWF2iMwT2wI81XShkcHeveez1wwwlB2N4LPRyERFHZIvGSodwkU=,iv:+mYh16wCFgk4rfNYBnEsWSiVj8mL6CMuhMyFvhpz6WY=,tag:a6/GDd8/NsqPgGTQoNHJdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
