apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:xFfH6uLi44nxg/MNS8yYXcDHuiT5/S4I86c7IiimtJUA4Y0t4Asx+sPDKdwj24364Slz,iv:wn7vjoHWhDPILeu403JhYgkz4mFEET5k/oZ3va6bs88=,tag:QHZfEGGNaeYZLnSHxB/Hcg==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:kQ2oscZZQQN1DjegNuyyb5c/Mb2vq5nQiBcwGkmqQmtw8ibTmMlR,iv:25EVBsLO/v779dSRbYHsiJmn9ZflL3WuwRFvBTINlTs=,tag:RS5aTdk/jrC6u0v3b2VFaQ==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:O2nLR8b52IiPXbs1X9HQiAhfbFS8JsLz8B0lGSMqCdw/6WFuTzCWuxbMVTxLbXx9ViZU4PTeaw7AYttloYRGD/pr6JmPr2Bc,iv:bbbFHVmWVICx/wwShuQ1EwR7PE14Ob4Px4NOhG7vsjc=,tag:VmpjTdCH1z3ookS7liVePg==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:tWU1oxgZpmjZq+Bb+nXdkA3EcFMbvOhoSQyy6JRnQ/DIbLrp/mK7/tiit8gP/a3ASSGZEJF+SbD/YCNDmLJ4eGNRYU0nmSVRcaAI3gfOlM7inClZL2isBTEoTU9YlKYYzBpmUrbXxMIYUfcFuMm0cxb9WHqJEkHoIEH2mwY=,iv:1mMnkzIVJMuJqsR0KOAGumYzjZwFAfnUAWc7dDOpK04=,tag:9KHwXIRQ+bX7+sd344MEeA==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:v2Wkv9mFl5EzTA==,iv:ptn4DiedSjO6Lik4ZuOH/u7BtT1V6taNFsGLVViLrzc=,tag:WUaoDPnjKxHqjS9EgSl8OQ==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:Fqyu7y7yFehenQbG9JpGmoSEEk7Rqkv4/SPTD1Bz7rdHYQ==,iv:0vF2Fw//3Jc8UA40N0SsnHIrKwmZcwoqHRgxHx/Kz9Y=,tag:x6XIa4WvqdFqNsilay+sHg==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:bRZDr483FASmCBpgPDEmFY71LfQ=,iv:FzbC5FxsG3Uh1rySEUuw1UW4oNIQmwLSLd6imNuje2o=,tag:AMg/EYG0pLfaOwKpyruldw==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:cfVYF3MulpAQXa12H53wFxVVpYJayEjZBF9bAWQuArTGlunG0+7+9YolO0I7kKn6Ge0C4+jymwvLdVkOOH90aQ==,iv:PrGK+jtpeJgjs71aVxC5qf8cFkyBeWnuwx+AjYxVdms=,tag:bHsH1honi6A2bRQinTXvQw==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:qUvgNniwJxAZreO8Qmt19naimf8nfdd9KjIE7puTh/jzpMZjAlrOLa6uWQ==,iv:r/cQP1aBuZaYSrbJfEJqO8jM+AELmdy9YujbyoDAX9E=,tag:X6rssat2DDg/E7/9Hn10mQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:GuZTzv6rzhhVvMHK9Vnmkq2+/KOYKLieGXAvl82FVFj324TrzAeuHtvR6kDQ2Am/I70Kx+ZktYaazRqS7vvo8A7DLkoKa8OvdA==,iv:ugQ5wD/hWSAYut+cIplSDDmAIQiXs7LtR5k+jfK2Ci0=,tag:9oqRXfLkTM3rp+FyrZPZyQ==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:dYmjRAbu3nG/LG5OtF22q3fup2Yjno4NOJnQ2s0kHtfJp+VgLWne3AEcFJ0i2eRhVh+rOjoj2kexnj65ew==,iv:xZD8kDvVWHazQGsuLn27qfya918yix2TIR7nN2yEKrA=,tag:k0EinyYbW5e8gb+IiLwRmA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVHQxaEpBd1JNbHlnSDZk
            bExOMUdHTlRFOFc3ZE0yQkZZeGhTOWRNUEZzCnpjTzF4NWtDWEFCV1VEYjMwV3Vh
            ZjNRQ0owU2lGN2p4TmZLN2ZoUGlISG8KLS0tIHR6QVZlYUZsM0hJTEtqczkxQnBJ
            SEZoVjljSHFEOEtYQ1RYVVNwVXR5MlEKIiLLzY1t5ZJ28YdUGeI+e6/uVN9pKwQ+
            1XkaHeghvEiwycBcbPx8uoEJP7axDvrFxlUHTNxQXpbzgVM7zYj2GA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbFhDS0wwNzI3d25sc1Zh
            Zi93aDFmcWs1RFg1VXFQRlZJdnVRMHhyVjNjCkxJWFV3Sm4yMTMzcThOdnQ2V1d6
            YzVyaS82SnFkTlk5R1k0V3pqU2NwQXMKLS0tIDBHQW5UUjZYVERuVkFsTkZCblpP
            Y0p0ZEVhVzB0Zi9uZWpKbGJHVDE5MGcKRvBQP27tbqfvzOZPkE8B1W3r6oscrVBN
            +k1BPw2VCR/X+EZ0VSPYNjHTz1zieuU3t81Q5nagRP0i1lfxt6QvSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a1pjVnpxNjZrUWVSTXR3
            WEMxeklrZmdYQk5uOHk4cHFKcVZQL1RiZFZVCmRRWGpqRkEzVzU1QkVvOWxaZmhV
            ZXF5RzQwQTJWUkJkVFhWUGZJMHhIMG8KLS0tIDd3Mnl3VnF1UGNSbS93ZVAvc2V6
            RmlNZHg4dWFlV05MYWh3NWtzMFZLRGcKF4/y7Rhv9/HXojXEmqOv/gocdTMneVnB
            olF9gPufgo93bS7RfDenzJnq4clsH+EGuID8rcihKQlVsG0CQgvYyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T13:41:25Z"
    mac: ENC[AES256_GCM,data:EQCRvnYbHdZGT8kAaHwgaxcsQ7QJ0JyUkbW0t+cQ2MIuQ5BbZqFaRJMaK4XniCnMmCm7aTueEoVnpx0g25T+nqtgMgRVxXHUeM76AKWTKGC+mjFF9l+5sCTQif/kWACu5zhzLZcLEXM9+DZOZ79LuSctEdEdh8M0pEmM/cZn1XI=,iv:JtfswiAPhc9n1oL1GYpSmsm8JMsxyJsO3RudFd7usFk=,tag:CV5jWVhJMPOuNBj8BVrf0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
