apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    NODE_ENV: ENC[AES256_GCM,data:k93rnx+GLt+pSg==,iv:KkjDP6J5b9T3MNSm0shOSpeXHk4NLovLI76rNkxYkQ8=,tag:u8/rJDVkh15Yc7vDlCNTnQ==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:5FAGDp+nZDOUp2JHuBRZkk8avSXfqvSll5660rmhYcHgAw==,iv:DnokeHxpV8k+e4ZrBWLD+1CJQwZbhu0owUkHKaUk9Yg=,tag:PaNAIk50/S4FqyGhxajqjA==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:4nPzMsDZxgTap07qncUQrZHJnto=,iv:VY1u3HexFp2MQ44p4YtLfo74nVVVX30Wn//jB0ARsNc=,tag:oWRRHEBKGNfxO///eMlkBw==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:hbbPvXX9DBPrYP54TFkso4+KQAgKlhenzxROaKcsKHwlDLbtrl3TVokL4IfDnkcf23vnSv6lPjtxEhNSmCzsnQ==,iv:2clJRiSlDLDx4YiJT4KJT3R9DJCZpNf42zkSfl/x1ZE=,tag:CVL9YcrsBRzzDjERTjen6w==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:6UR8an84BlZEdOpCHS+pPofT/C3KVsSewiRGZd6ktt8NQ0DryPc4YyUac6CxhTYTLvSFdaESRklHPHEHag==,iv:RCPGv00cjAViToj2Oq/Q2Rub/Nl0gTYp00nkU+qn628=,tag:GDiXD9+ovgrOMnpwlvU1HA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR0NiendJVXRMVVBWL2pv
            a3YvRzJ1NHl2c3EwNjR3SEJqbHZvZjNGSzFZCkpsMi9uWDcwMjYzeWVUYlpmTjZS
            bHhQRDNCUmN5c3FDaUpPV2ZaR1FwMVkKLS0tIDRHdHdxdTF1VHJjVnJ4Z1R4Q1R0
            bzRNQzhBYmxQWW5NVnpRQTRQQzNJbnMKdmKi+MxKfWP0NGWWBWASCdkHA1kZedu/
            5S8+kfwh3/Pm6hsxoJb7mhMI6wnM1N3d6PJRJX44AVkDix5mEz+UKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdzlZajJQWVlrOVZSeTk1
            QWVaMUdsZUZFV1NOZSttK2VTMW11a1VKamhVCmVBZEFzbmxkQWltRmJ3UkNSRldy
            VkREOG1iQjhmVmw1MUIvZ3R3cnV5MGcKLS0tIEE2aUY1TStJYm9wcUwwZ0NMUW5U
            SFlIaXVqazlzN1VPWUp3aGV0WVZGOUEKhDEQJuyxWyVIIwgFm6PrZLhWY8QlLaVP
            9a97hnJi0LVD8CSQSfyMnNinw8+OI7ZenyNHwvFad6qtU9jNVerU3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3b0VtZXZ1eERFakVMaS9D
            dVJqNmZMQnV2RWNQUzYwaCtlZFFtd3FlbFZVClVZQy9IRUUyUHdwN2lHR0lUeVE2
            d1FjRnFQZlRFVitnVHFkeno5TlVlU2cKLS0tIFpNRXVRWE5JYTFDekVWMndELzlt
            QW9BOEhmM1dvRWw5MUF2TVJvVWwyVXcK+YJXcO5ATZSQsi4zFn151FKjHqpi5umX
            X+qF/NVHscSZm+22JsLHgFqCfYcIe5vls2XFgLKHkaOiD5Z2zmuPnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T03:27:34Z"
    mac: ENC[AES256_GCM,data:5P9OgJ95ARwnJUPFLy60olin7UU1nbryy0yvjDXjqbeP020+l8Fr6d/mW9GPZJtD4+514yHbI64B1P1+54u5pU3Lo54ha1rWgTpDGVY/nylJCb/uMy5DK831eTq4TVUfLYP/Bc7Vogp3XoW6cAxWY+FQig0GE8Lh6iZY8bo8M64=,iv:OkLDZaCUUZNlijrnD46PXRFvMhVtKZ0Q0KghwqjuFOI=,tag:WlZJDKBG+PSAVflg5wcNyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
