apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    NODE_ENV: ENC[AES256_GCM,data:5LNo6NqzlM1Q2w==,iv:rucUV6qO/EU/+6KAwMZE+4LA9q5e4d09TX8E3snWWiM=,tag:M364dD5r7kU9KhBQvpDXNA==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:ZH+kuyqMAw8wBxjLleUoE1Xr8dz9tVEfSMhDB/jAkofiLQ==,iv:DfZrj10hURpgOmgVJpVaEQ9vlaHh/0wJsaxG8ooo7e8=,tag:c/JCOHY9I9gSfYH3sRmhWA==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:n7VM41DnTd/9R96fte8iAW8GsWs=,iv:aDTYMVZq62TIgNpp6cr5Iw1a1mcLFRR0d489CumxCBw=,tag:HQEETzu10fcIBtJrbhWv+A==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:ejUUQOHtmvwCOUsUoJqIXFpZkALRCeXZTw3omGQiFXKrchEik2wEvoZ0agOcv01gMoylbCcG45cPGzyYotGxEQ==,iv:cXrX45ZU/n0zVZA4npUDsefccsjxQZZMQuhvLh4WWE8=,tag:Utkbb8Y0b6s2fVHbxzXhaw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b2ZEaCtsaWYzM3hvclNl
            S1c3b1dMREpmNUFoYnZzT0pxUDdLWEdLc25NClVIbVdLOUs0N25MMGtoZFJPVlhS
            bDArVlE4WFIrQXFBNWRHbk92OHc4eG8KLS0tIEJ4R1dPVmlsWWgxaVcyZ3hndzRX
            bzArQTA0NlY5S0x5a2xsL2IwMmpNeFEKyD8gHBXDx3xp7lATUVVObjei1uD715zh
            B0C4csEzvgs0rllohUVkcVd3mRc4OFV8LH90TSMqujTfXHcWIOPZCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZjlkaUQ3bVc1S0pzQlZV
            Z1g2UnNYMlk0czVSTGw3dnFJclVqV0ZtTms0CkFWUHQ2MVEvdzRIbUNuOGkxWmVS
            R3VxaWJEMlU5VTF2WGNyUmdMZGhnOGcKLS0tIGdlQVhaZ050UHZGeWo1eGlKaVky
            YVF1dlVSSGhKWXJHeHlJLzk2MUpIMk0KgxEw+Jg8dvTRWM207KyfCiJtRyWrYIj+
            C/zHAkQJ13eFZfn7Moy8whcps8tCHnE4zxRyVgiFoGktCg/vAx+m3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVks3Wm1RZkFvN1ZBN0RY
            U29MdTdlWEpldlZEMWo2Qm1zb2daQlJkc0ZBCjFHTEk2RjkrT21yZzJ2eHNjODE2
            U25SN1JKMEdIQm5wTHRMeStGNnlaNEkKLS0tIGNId1hOTWJ4V3ptUmVlWGhUajM3
            MGFkckxYakw3bmlwMkREeFZyR2l6QWMKQHbe46hPnBPmR3Vm+IzlfyjU5BEO8Tvj
            aWTqyWL5v3ZE5vFWmLE9jfLfEgnqZKpraGB0AZudUMgz/X5F3XCa6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T15:42:20Z"
    mac: ENC[AES256_GCM,data:PvlAPfnwiKMOcU8klJgjKwC97OyDTus7RpMaxogWYpcenE9d7JcL/mRAW+YJwYappZsoq2ZJUEJiE2fyDcj/rb2oVF3nYQw4/aidqqtnko0GhJKcxeCM1pUucc89FmzMY5f+0Pur9LcLf034Ko0FvuQc2pLMXhihb2Dl1UTufUc=,iv:0to/XmqCbVdjH8KMLFBiLVsf93MTHAGQC04pn4TmGY4=,tag:V2QnUGZk98VFk0IqKr6fiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
