apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-config
    namespace: apps
stringData:
    COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:G4Vo/GIeH85Xcu0kGCacxbnu+JdSNDZrniyVQWRbY89VXgmobeTna4BzemDG1b54kNenA+fpoAMz1VEQ+aollEMgNhK6hlLxLjfdov9dIveDhcPD0yHYw3rGtrQx,iv:gwAwgWHBXdfz408ZAGirYSxcyJZe/WYPi5iH9ezDydY=,tag:DgMQELJ9/68+55NfeLNaFw==,type:str]
    COPILOTGITHUBTOKEN: ENC[AES256_GCM,data:KMTZ1BaLwE1H9EML/OcP1jTM/72RwpRune7RBZPFcPrzARcfnJYtiRaYKjDQAd46m1o4XaWcBbbYlvsB7QA02TeaHmqpO/CQz1Z49G/Q32RSFTj+YO0WIWIplLwQ,iv:xmsGUkx+UI+Z0cDnWiySBKaD55667PG5R/WuNSr6D3o=,tag:CfeFblEO8s5xUSArwe9Kfw==,type:str]
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:2znlpvWyNfB7fzIJBO7cREu0G8wN8OopA4Pz2k7cCACNhjUlTrmwR1URgcvjm12YZ7Ez,iv:rlxhpcwOQ4um835nMVFe7PvwCK4GNMAwHOuiLawl7gI=,tag:dyElP16da0UEe7MORLx8Eg==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:3J0Zpqfa3YdYLZ+JbwjdIUsf5NjRuy2FjV60Js6Ti0AcdmKbHs4B,iv:RSOTaQeqM898WOYCpHJ7knG20rB6xNk4F778rSU1auQ=,tag:4HndGQcT8XR7nRKQmTdX1Q==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:qZebEm6ypGrOvCyp+qcY/nRKZnWLR3IZTuixsxqsqiP8OtiQDKbAhw==,iv:Ls4GNkcMH4a0HC5G+rjqMjGkdQvgczg1p0wiN4jiaWs=,tag:Jic1q0h2K1wxPD2fsGj2fQ==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:uDRudKEkLQBWWuJubaCeo9bxciQ30QMjpPbB4pxaYWwdh78s9vF/OlvQhFkLVUZinehl6p3Ok4meGYZl4kYoXQj9f59UtOUY,iv:Cc3//FPQV+URc/21ZSIgqYGgIjiKhjTAuKM+sxhjWwY=,tag:lpwOKgDvoi8YMjEoItOvKA==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:CRlHOUYNdHAH52HLUPZQr7osZFBR3E1qeS4oKBJcpv43m98JfRzog5E7pzfg+M9C9GX34oLP7DFP5DAdyhsdcLsuNzvhBlZdutpOvefLYBt2Sz0zBnSX85CDkpu1ymj+6/SwZqExYOcVzctXLDfQNWHMRqI2VC7f+fsLMJo=,iv:w2M4SEktrarAaXCeEywJoQpsMjQuDrPSGUhD+g+z91g=,tag:k+oPyrjO6af9DOnnV5x2bg==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:GnFjdScA0SDfbA==,iv:OmQbPcbguJ1gBAUIuLBMK0uwm5GdIi6nSRy48vNlh4Y=,tag:qbvUSJrWATLskiM77y0bdA==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:nkddS0kFfpFbA1lxfeJyFjnOyFtq51F95tuWlDYkVwjM8w==,iv:JGBemO985YZCrMsDGUb1T51NvcmJn/h2KN3V6Emm+VY=,tag:xZK+4Vgn9cG6LNNeBzQw2w==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:7FB+79OgssPJ/RniS5a7lGs4QDY=,iv:bgLz59MKh02d7ZDE7UbwEgWuWkd+IXluisbb7vyTizs=,tag:ijeaOVx2y+7ZSDc0WerOoA==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:6GarAMqIZ7ZMIXYwi0arE7JD2FFMnN99Ywyl+UIHiOI/7FEdYMM3ZscrRUH34Ga5nzOt2xB3Vtu1qxAOtaMDcg==,iv:qR/Nc3jIyDkriRIywCjeWioKSh3f7CbDW8d+Wzq90oc=,tag:TuDoTuzXh02bRmSNK4/NKg==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:+gVdVfijvefjOeGS4PLrpT84o0tXK+PMEsGD1lPVaQ+zJE7QJPrQLn7Hsg==,iv:H20uydDTn+FlY8wI9Z5SWeIkjT7/2bAxoCL6HvxRsKw=,tag:9AgebJwdPdEyvDlHsyzZyA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:4c9xlC6Zq3GtHn3LsPT6zT1NMxnD6CqlZ/c+k70Q4Ar+cYp1b5nELN9RLqm+53tLgU3AIqRlKvGrj+vNR3xhsm5tcgpma0ithg==,iv:y+R9C9c/h5cg7j4ygjwtS1qqKVDD2/3u47/slW8O/xI=,tag:eooYvZchwTYkJX161imItA==,type:str]
    SEARXNG_URL: ENC[AES256_GCM,data:ENuihh/f2Kh047ex5Bm/eanFsa7p/u95441CS/CZmKusZ9Zk1GZy/F7O0NjILbgYmCA=,iv:6bP1QiOYER46hrMbC4bWh2ttcYs5ZmHw7WZBEPE6I4I=,tag:g3Xb7byOPOXIrSMuDlliVQ==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:KnaD4PgBQL7uvniVs36SYUARLVAcEjz1Q4PcyRcTOKgLHs65WiKPSYpOUX67nAGTPO8I9j+d+nKems2/+w==,iv:oWrIsY6r14QGMldeHFUJkFgC6gQ3zaGpin9c9LiGZeE=,tag:40gx88z42A31AEQ1j1gJWg==,type:str]
    WHATSAPP_BOT_NUMBER: ENC[AES256_GCM,data:kLXr/jVA7EZi4T19IQ==,iv:6EI/LeegdwXONjNXwCoIH7XZZ48NscWbS7UJcvaOAfs=,tag:b4guJLI4bIFJX8F9tdq/5A==,type:str]
    WHATSAPP_NUMBER: ENC[AES256_GCM,data:GYSEm0BKi6ez/GArMA==,iv:TnJu/LvC4h0yMzypChy5Pvjl50ypKg4/2ImQ9D8JomI=,tag:VSvRd/C6/VnqOH5Af890Kg==,type:str]
    Z_AI_API_KEY: ENC[AES256_GCM,data:SaKukG1ezEwXqtebGwWikeUpCrp5/qUGr69V4p8i9IEiTbcGSCzvqK6mZ8/gd3Rr/Q==,iv:yUtzhFJOAEjiTN9gvTuqIfi1Xkqh1LkSzV3ZZDxcZlI=,tag:o8rxgDQ79VfbYZlGh6smLg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTUNaZng1OUpVYmhHSVlp
            Nkk3SEpQQXk4VnRxbDFtK1pXUXM3SXhyV2c0CkVCQnNqenZOYVlicC8yYjd4Z3Vi
            bkMreVdHekNXQnl6bkE0NzBMbks2SGMKLS0tIGNFdHNmeHJaUUVUb3FpeEpHQkFx
            NU1YZzZnNlFJei84dlNPZ3E5SUZTR28KnZwnoqKF1Y6j2KWlQ8aHPOLmj0B7wvIO
            kuiitfBXOGEbo5I75bIbqq+7xQREpUo7Kw5VpPNJu4CcqDqWwFSc6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYWFsT2IwaFBYeVNvdDRS
            T29aYXFRb2hEcXI5M3RQRWpmSUtsRlgrK3dBCkJSR1JPQWhrN2hCTy8zT005b0NL
            SFdVeDdvZDVNR3BYOTFkeUZIazdTVGMKLS0tIC96aVBKNzl5L2hmN0sxQTRPK1Ry
            ZWlyUm1ZMWhQV2swZHV4elBTdGswYjAKz+y3youbkv0a7K0JQvC0uL+KDuED74n8
            ZiqcoETPC8eX3OF8WfTRI1mEFwn+41ahnsDixWGDu3YmuD8lowMvAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYW5XVFJyVXJEMHUvNG5o
            T2hYVnBLWUtURkNDZGQvcjZuOUEwNFhHSVZZCkZLMjJuT3Fxa09HKzB1d2F1UG1z
            U0JCZG5KT1dFdkZZYVVFVGVxWm1KVmcKLS0tIFFUWHJvVXZKWkxnN3JSQ2RvRlJr
            eXBxbGEyRUxDQ2JLd1V0REQ5YUZ6TEkKQSfxZRzeAYOWLW3ZhUcJ2pfZn3SMHBXt
            Ux+pYhWmr0d01xVp/ecfkLX9qoqlA5jSR9rJeFLTZoErPL57fvL4Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T22:11:36Z"
    mac: ENC[AES256_GCM,data:WFvkdjfs3DnDgiThlogzMys5zE4yO55kADZuy1sYTyJamJtxiC4NaaIqygOlt9pQGiNtsxrcvYczTxZZMs4mA6qWPaVWR0EP2fu8Mnk+7FtcbgGAfatGio0vcmXric6TJoO7v3Y3+tf1txeq5CkoCOJiSwcsjxPerRu1MLKiwRI=,iv:/cLait72pEabVWWKkBufT98RxN+71rO2nVhr2gGafhU=,tag:+cZ1ed9ZdcpbRxsdjXWS7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
