apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:tCwnzG8cNmudb8pGiHQJRP4nT/C6RBxYPdQ0TzdEoMFgan3mq9f/KBGYBEILUWsZUIgP,iv:3e2Zqrha4K+Nr+JQ37+7WfbID9mBgrn5VTEfBPjDslI=,tag:JeCgzy1mGMrPJiAQqJfKPA==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:NtzKddG+pFyFGdi2idGg/ObIu8DlGU+sJ1xsLnhiTiJ0W58y5JOc,iv:ktwh2RJIk7+CdLGe4aAeUnll7QIDhlJ+NyTr+z0xTZA=,tag:4ijk/4LpuaE7tV1iprsRZA==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:eABB3Ek/Tg/wU6pqhYQoQBVeGLvIuF5AQck7ee1AyUrvi2GYNta3ow8BIaW/WE3TbBAG6dw1taT6W5fvENd9epHYEkfKaa9q,iv:R/mOwXZyqPHO5LvXamdTf4mmuTTORUvG9xZ2oeB812Q=,tag:IugB20V3lLRihnSNQkPhbw==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:slCYYs9VyZCt9jTH40vDtHtU4yibOE35xcmZP2o1OFQ/UukvfE5G1XOFtMaq7oB6W1W7eL1Tsx0Q4qa0Lz6KCqOFTztNCfhmgW+L8HZ4qJq4bu2FQhUN7Pr9y43N9pxF+MClFOn4QBOHqOgX55pl2FzefrkkyzxB/3zOokY=,iv:5Tr71fjRskpYTnvlx2BsQqM62+G/SnwN1aT5aQnoPlE=,tag:RShyTp9Dge8KHjF05ayuIw==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:rgEJAEebvufsQg==,iv:BMnykuWgA+INiWtjCCymPP6YZDijEbTQkXcaDEV3G5A=,tag:DY2+W6zXHVAFjKxDvXwpbA==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:vc3lE12YcbYMPftDz33kKirgOMKsUlEW1yBZJKBCnDKivQ==,iv:NVrrcjRBNXGMsJG9eekRb7YHDf7LItheFT/iStZvJng=,tag:x5oT9CKCQQWKHPjXgFQ+oA==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:NtdtYOmBGKboBZFczx4tWt7sfPY=,iv:3HmQAeK22s2DXETTshzW78wY6UAB2Wqg3R8Ty61PFwI=,tag:DgJRpuIkaD4Wg+19SV7g6w==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:AC31CKsHWxvYEwktZj8Fh7PXLRfVhGuZZczr/X+XaeVkJy8HjSQMWzLwzYfyV4If62Djl8KOrI9EiUCDe2DCYg==,iv:5sAdrVWa0q0/oHGpD4XGs9D3+OYmAIPdY2CCOYCmpDo=,tag:6U2mYttkWJ37RFZspnkAXA==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:tLOi3Fum0lU8gtOqqhhnVLHXMRulJvgKJcc7n+uYWwPNElfyml0JEVKwxA==,iv:rWAdkK4FiPhIqSrc+p0Lu/LwZE8R58PBIl5wqRWgzPE=,tag:O3dWqzSixwaODQ5V2zz1XQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:V6bnmAJZQWLO5u/Lpc4KGAeuEikxkaq4p/NEdt/viBB2G41bS5YqY/5nnxh54m+LYC+p+/v0vCEOLIhMb49qc8dHigks8cynFg==,iv:cgAHFHPTtRLVSbMcABsl9Z/FdKmo+psSA/MOaLDvOBw=,tag:AZ4cvUUtXXLGq6dJQoWBbQ==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:dkg5YE7orsryX7oELnY9vW8UZHyZQT+Dk06y2Vmmik7Ku66YDlxOU7yYXSsfSmLxOutCb3t2lHbxHUYdQw==,iv:+JHrl65V7yI2iQY7rHSg2cw9otd8tzgeDVugT+xBJkU=,tag:DKnmw7kNyrknEVRyKcxHuw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSXN1S1JXZS8wV1IvVnMz
            bm5UeGdMMjhCS2tEZ0ZqUDJFcjArUVFXaUR3CjdzeUlFamdubVZybkc2YnV2V3FZ
            Q0FIekg5ZkY4NzdObUl0cHdBUktTNFEKLS0tIHNaMzZJQnBMYjV3UFlWRmo4SmZ1
            WGpZcGlGdWdCcC9kUVlJelVvbi9YUEUKOXMvgaJh2Lq9Xt43yrmA/ynROejJYkMn
            NgpIkLMGq+TLy8PvOBKpaK41X2AN8w2OF975WnwOCar1fvIrzH5AcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QnJZTStMWUE5NUVETzVa
            UGdQNGg4Yk45bFdZTTZxbzh2VWN5YlBmSUMwClN0UVpCRlhMVDJOWU5HQXhmdWEy
            M25kZ1lWRUtkempkOWJNOTZUcVRLQkEKLS0tIHVCMFJQVWJyQUx1Qno2WlNxTXZ6
            ZTRwR3lHY2syTnRBRmtacktWOFJtTlUKFdXmckBKd2qbPHVIm3p1HQ/wjbvnhjKQ
            8OwirobWm/o64v8vOpVRmOaPPzl2wWD/q2IlhKbi6WulbxLgU8y2ag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MUszcTZYeEFjVjBoWHNx
            WXNraWxnSlZNN2lLdXVlbjkyVTBpU3dxc0dRCkhRZlY2QVZMbWJVTjJhc1UzZHpL
            ZFA1ZTVGNVZBcHc3Q0FzT29IYkxMY2sKLS0tIEJCY2JhV3RIZDZXU0R5VDFJYXZ0
            NC94Y2VQaVB2QmtRTG8xbFRmT0dtRlkKksiVZBBxetxP4v94ilYv25jj8/xhmPgj
            PxhhNlO/BTnP6jmxKZpxG9YKESv6RemHKb/ue1lulS7YjnmFmFsfXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T18:24:50Z"
    mac: ENC[AES256_GCM,data:1wctvUY8UsTq2cJfs5neXiTJTmuHd/Ho9b7xRX27F2bpJIwii07mtGcyBAa2PrL8MkiP4p4VV7cRpynaYdoUttfEKp3BJsXBoWFtdkZYLeCaGl4xxZm/kYyhhU7Pt6bYtRDTqGZI7cd+ci1090VTbp2yW6013A5KdRXCXMaQfTE=,iv:BInGVZSniyEe5NkR2zcpXK24omH+Cir4uAAUg0FXn5A=,tag:XpyzY2Es0t7Cl6tLGkzXDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
