apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:K+ogv+Xz5jrUYJ3UBsiKH2K3NUYLqOWFrM8ZPGkKDc91h7KEt2BF,iv:VtoFMXYtdZZhPXUrwagptWJmSxvR6KoKdYIE9xD10iA=,tag:gvzKPOwUgf3aypgZHxl/xw==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:S95Xf4h0LCHOqxSy29PJtWGzNCobfx9U409HhWob950JheueEKyWmYoLYAcX8S7klVS3K5sRnEYyCBYbI6Fu6U38KNT1LibV,iv:KAKXJCppdNgpPjzr41uUDRGV7EwBt+qKFz6rrljkHNY=,tag:Li7Mt7h22cyhQzB4rE0ADQ==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:kKRRivHFNfndglr4l2lrfxgUXH6BGthmf/58eVkmg6TMtr+Iob24+qsfoy109DRthFMZO+Zed00JquUJWeOxA6yf8eWfToTyd8eSw/+XW0Sb8jhlMblefnvwlZege9TtS9AAeCbOMZI6UW2VBYxL/jvbvHBB61YRn4IsCFM=,iv:8OsEK06YHJR+S4q0bJmKp2+8qj4ndPFSHPkArxr0Xos=,tag:OBVPHRyJWR+VG6LxsaZ25Q==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:2Sv2H16kF+Gz+g==,iv:NYYDYCvKaKoXhZAq3x/ZatuXwhtBn65fabAf1vqv38w=,tag:IXTy21HFLk9efzpCby3W/Q==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:N15z++Ja44WVPQq7aCsCmcMw33S9nsktCPVNEuXZugL9Ig==,iv:LpsVYKq29tuUIHJKH4znO6QVqdSCOo1Ij55zSKojXQ4=,tag:rF6RU1CmDJhdhqYSZSUolw==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:5BKHGSPgeXZPgw1N3TwSKbZXkWo=,iv:MbOkFBdsANJC2yji/RySztrFDk4Bp1twdQjaCF++G+I=,tag:5KXMinhm7KzIb14ajx20Hw==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:NvQjtGO+j9XEhf6fNhGwL1XvNZLTNC81rkLTAPeODKjKuvh2h9c04dniN+wKTQpmcsE/QwwddmuwjHyfF0VuzQ==,iv:oJrXOR4iVpFZQNLOA03C0FAupoZQq1OWGpvfg3OEV2U=,tag:9B2C/tUR3+A3FuGPXPvMaQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:R6eHDdzZlcP2EuANjQgEk0IC2ArkWH35anrMk3mofWPwKs91Roo6PDRa0Wee//UtW+SnDE5opZo4aiwXlqs+EKrU7BvDXl9Y3A==,iv:f9PQSbQRNtUwNRXe/ynJvnh28Q2fzrpDSWXTzgE46Jk=,tag:of8s2nLrINm/ZonpuwPFdQ==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:R3PlHYe6pTkTKl2z5fcatj5C0AXlPfFTf3u+Ks+AxBU4dkp4W/+rfxSVTWib2X1FUouIaF4hslOpbqzgCA==,iv:334Y/1rXtFChb9MpjzosCCh2lGwSILTMm6Wgsv1bgeM=,tag:wjZJVAGAQz15UWhCUfNDzA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL0NDd1VrRGExdWxaWkZP
            em5VbVRBVVJSbHpkZDBGVGFiK3FMY1kwMzA0CkNoMEZNOXpYVCtYTk9JRTQ0bVg2
            akd6Q09WTDdjb2NyYmV4a1UvSis4a2sKLS0tIHcrYmswVzNyR2o1eVFncEg5ZEJI
            cjl2eEpVYTBvZjBvaU4xa00wMjZGbUkKFVRhyGaZxq37O58cu0fnaca4dOau0ap5
            0LEINmwAYWbCXATi0n7h6EBkvkv2/IeQOhbeLmHiwO3CR29AeER5KQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQncwZWtqRzkvK1JTVUMy
            aHM0ck5JdnA5ZUZETmhnUGRnT1hVN3ZVcVdZCjZIOXZhVjU1eVllU3JVOW85TUZB
            QW5vak41M2tRSjdCNlhQd0NDemFJYjAKLS0tICtWWkxkelMxY0ZSc3hlamdad1Vp
            bkpTUEJqWkx3N0wwK2Nsa2ZkUVhLcUkKi4zLOGVF1TC45iN7J4coUssvWAvwHeR9
            6NZgDJFNZj9hKL5fvrKMT4GP0hSJ5bbYFih8sdm6FCOEAUGRK7avNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNjV5K1VjODVDMGxqZFNk
            VVNMWjVXTVVkOEdDQlhpM3dkY3VIWDQrWlhjCmpBOElyZENTTGJ3TjF1aDNidlRC
            a0xVS2RLRFM1bkNwME55ZVY5Z2JSaTAKLS0tIFNzTUNFYmJiU2ZmQi9yYW8xZ3hh
            b3VndnJBRFVJVGhYeVlaa05FQ2Z5aGsKlfSaHs2X++Z1v6XvsWZVtcukmGGNKK0n
            22zB794ymGuVG8wmRhCuS9cmwpodl2uosGruGe1QZLV+q4vYLJqXzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T02:45:22Z"
    mac: ENC[AES256_GCM,data:NRowyT2YWmYpCGPqcMjv5jNTTooQ/9p+hHsKbQe863ea/eNt+yodX/f+I6/vs+4yAK6C2bIqirWEz8wf4RwFQbl/ugJFR/SPnYEZ74m+EqP3ukoG5LuQQNyFYBAmqTR6OwUBGRHXf1icb5rhVZgtc2qg9ujw3dHpfytOjGDHEFU=,iv:UmkeCNPcTUfXOMYvJDLYHOb1QN68AepVzlFjRMyg4lE=,tag:pUcBwDkz9YawJ2wXGYX7Gg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
