apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-config
    namespace: apps
stringData:
    COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:VP9zdizojze3LsbL4LZZ3OpLJL0xym2lTgzY+2gt0JGfgx7VzHt8RDsKnTLnlaxDWqO1Qa4LDmKNcA5BZqAgAhHWpKzaCWT35AbBF8B4Mi3jOVEE755MW/b3W6AK,iv:8yZWofTsRDFr/g8/bJccHV6+D/lGgKlcgcdMUFz+A6M=,tag:K2VRRb4ElKOtCjv5OFEVdA==,type:str]
    COPILOTGITHUBTOKEN: ENC[AES256_GCM,data:ZiBq9oZ6Zt3G8FzNRJqjP20DKaqiCD+zylyWXMvjOwP3so0zljvF6R+XiRcE+SSHxgXKIw7t2ySHkYlK9u/YM+ylVDlfIcTkzjff408ovUu3ig7AdvOmVPvwbzwn,iv:F2xh6NxEfUUfY8gZESR5V9LWNLHGiC5IqBIdGtoocOs=,tag:g/dTDiwr64TJ03dE8vyjrA==,type:str]
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:ES1OW62Tu1wNmhBLWMNRnzFmDl4+x24VZKT09eQvGM9E1VnAEnPodCVL9E3c7wlYlgQq,iv:RYnYIXawDS63009ERj1qZhAOUHGzluzT0kQkhmxgIKs=,tag:XjNeDAmT0LiqoeoVqhRcEA==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:7Ew+M1IjLZfmPdeo4kxmr7MbVRJZO/3Q6lSD5xXmStXFbt2lOnUl,iv:MerKqi/hnrDLaQcbV2TnkUzrjexYFV+kjjNNy2CafmQ=,tag:you734wPhm7DLbgnv5e8lQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:lqDuW3LQuZu35V/JWpM9ZrRYIQ/Ca8U4AmRGP+MGNIx4wTsGWJjt2A==,iv:biPidoMkuH/T8q6TXOsJ2ZK5WtXQA56hjcfTuBEpt1A=,tag:PQe1fDf948FVkwzHyjvluw==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:EproY6ojHFXn03/c+M66Gw0yoh4a73lV4L+74IFNUIL+l+c3kfNF7pNkcfv8ysStp5y6Voe+uAjJXwOYNwDpZsqk+poAtlcA,iv:88G17uQ+HeWQQ39tQ+4B6ylYL0s+HLKwkTWxNN5pJ7M=,tag:puWCREWgZJq9Gu7AQaA5Cg==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:u+xMydoH+sQPrGpK7LqPCwuUZuE6Q6XqtVzBD6rTHl2hgFk/mP69y31UIH6GjjfRN5ZKwTNSvFLWtofOIcg+hbBeCX5DtsJ9XAjEoEsCdpyPq5tQxOTfgdSkNU27S2aJEB9u5j2Gq8QhBLCCnV259kyu4Pk0c/oH9c3uTIk=,iv:XreupHL/klhqtPXqBpMthhizNKI5GGJJayAHq5iv6L8=,tag:gbqZWLa/cZZmGZB1P3O8Xw==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:XEdOohv67Y36IA==,iv:65zjDdGetngZr+atibbp1XnXDLxkFNw3eSojwFgUfNs=,tag:timPEc//5csM1zZElO4ghQ==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:ig1x8hN7ahJwn1thQDqcK+zYs1ag+AAXB7YJnujkGj3DeA==,iv:RFMLgxBblRfREw7/8lOD+l0l+KFrJdbF5d2Gq0A/Tmc=,tag:GnTyGcNwO2k5ZXsM2t2a2w==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:V0w4XxMq2T5xvWcJ7bMWW+FiO0Q=,iv:/hwK9h5we+v8AIA5/w4gXGS+cODFs0JnjWK4Mz53JCE=,tag:yZF3HBe3mpnOMuURnOMPKA==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:3F0e9yhbJBOhbGWzpmIfNGmVVpMQPOdZpEIiEO5mYCGBoWa83M2Af3lRW89JOoMFRfKNvv77xqh+IsNnhe85Pg==,iv:0letQmQT3EToAdSn42Ug18ORL5BSu+oI1Iqr2Cu2jYM=,tag:8lHl9j5KlcIbQEdOATtK2w==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:uSMrkeuOyf0dL9BXL6BGDpM9fcYzIDOvsoWrx5AZ+fZn+pxzjVT3+XAB1g==,iv:LbYbyoDyztckBw/kZGyZ8Fi8zwKy40i/840JUkrxie0=,tag:8jb+u7bZLZRSn5lXe3BtUw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:svbwNuLH3SpW+hmzXsfvRkvntcJ618KecYEHA2zgKNFNjU3wHpsEsGXQbscD74wbmtJywPvcSb5O+V0jCl2N/fK2tsTkga/N5g==,iv:8mESjAi//Db6yb0Mzcw07Zc0d9WxNJM1W1mEp4XlUvc=,tag:yLyaKFapbM1DdZqz/mHELw==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:HYYZ5PSwJVkJurzTxOFv2QvwTB/AurSZomDFqfnL0cNoMYmwYMc3gH8y4GZPAsPymzNM7UT10/yjG4GPtA==,iv:Aq0Srds4850ulWTT8b4ngGAR8Ec6eGDUPYmEOk4Envc=,tag:rIIV7uq/fTGUU/am9HXyGQ==,type:str]
    WHATSAPP_BOT_NUMBER: ENC[AES256_GCM,data:DJyagnMmdfOmYYl+lA==,iv:NKIVorHGRmjF0BPX6jHfkumfJJ/fUCfAb10xMc3lpjw=,tag:kOP3+Ez/MQqz1DgeNBzwFA==,type:str]
    WHATSAPP_NUMBER: ENC[AES256_GCM,data:nlMxj1GeapntjOSoiQ==,iv:D/WKV8s0hdJ8gGkjqw0kDuOHb8QdIbcjaH1NkDtXNNI=,tag:yhA3BnmEFNYMVs3M6w1BMg==,type:str]
    Z_AI_API_KEY: ENC[AES256_GCM,data:sCkTqZGZk3c2TQfPuQE2xZLDKbyOObW2R0AoSKHPrXHKCYg3b9fIITN/9N7iZL27UQ==,iv:s14cW0u/d+l/phFASuvQ+qMTi8X+OAQzuEm1huRlVPI=,tag:+2Tg/q8txUKK322Lnv/H9Q==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY3A3N3I1VGo0Y21LSStH
            dWZkKzliUlArbEs1ZXJCeWxOWTlDOEpUekVrCnlOaS9RSzNYUFpDcXE5TWtoWmhC
            Uzhqb0FlaHRzVkxIL0tyazZzVjVEdXMKLS0tIFZHS1NtU3NQMmwya0dwVXdLTFky
            ZW5EdCtFMmJLQSt3cjlzOFJTNVRXQ1kK1rz8UOs3Mre9L1dD6+aoJh5n2hEAnLit
            t/pD+gDMZZh/aV3kAwxa0fwHMe7OKQgxqmN9qUjAY5vHktiDPnoGcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdEs5SCs5anhKOXR6emRO
            b3MvQTI3VS8wWHZuTEpjeWh2bmhkYldITEMwCmhwU2d5MHNtME81K2NGRi9EZVZq
            WGRYVXV6NitrOVp5azJWZGkvcDJoMnMKLS0tIFlaeDhOZ2VCbHF3U1RjSENTaVZY
            ejk3MzVsOWJCZDVnWTZ1OHVkUjBrMDQKG6IFoQSlXyccDVff0o0d/w1V36IXTBuv
            uL/8x1yXmAoRWS97bntgZN0b8IRSAtX3yVwFKlXbWTXS2niFrS5Zmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSE13NFVzRzhwNVhybnRi
            MWtQbjJBYVk1MkVxNEtaV0hmd1FvcmEwS2hjCjZCYjBuTFFxY25mVHovdnhTU3dC
            VUxkQ0RRNVY0bk9SU2lXM0t1VTRSVVUKLS0tIHM3SW9uS0JFOXBORy9tNHJoRmw2
            WWl6ZWFGWFdCZENjYUVXajBKTlBDbG8KMBToX2yJRaarghZRXh6qVclpZMmq3rJ1
            XsdNrsgdcTtmtnnlzzTGW4T0ZYOSIFeLsvVjSyVX6lfAPsoKWMsMLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:36:40Z"
    mac: ENC[AES256_GCM,data:HeSQC/THnxHGYzrpu4vUj5kwunqM3orEqHyIQLXlzpPmGpbj5Lgq5QzP8nL3N5zTfiEzQVK4XlpgKWvHIGTKo0b6CD3vvC1baj3+ZoGJ2829/bM1/VO1lGi8n6L3MLPiLZbQH/FBRRvrWrsQ4VgQfCWsgPBzfYaKqKXjDXSmNKk=,iv:BxHtncIfjXYvmj0dnwZUnEKbPL6MImu/6rzfAzQBG9w=,tag:Sn0WBSUR/lHQYMijDny1HQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
