apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:cnRom7ERMFiV7nPfaA5F7XohTgZg4heUi9oJmE3COAtSmFBew+peIASl1Zz+4eIxRPvI,iv:SZzNs2vMhLxiq8O1z+0egINApbyZ6Re2HUwJEuoZXjE=,tag:c1IkbqAn2Y/CHYF12VF2HA==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:9/jY2jo3N7Me6GmNIp0/NU7rz5JK1qsrFWHTi2ByvnOXhhOLtTqL,iv:MuUv9DcEA2UgrbQ4cPRTTabkXIYixtW3RzV1CnCpm9Q=,tag:Ir/xa1MIbmglMZ46CRFqzA==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:8I7Q09JUi+rEve0y33vs/lnzA6Lr7wniTyxJmOqQNI3PmxJR6UarM3khW+jPSty2UeEfyERHCoM13sHXQrluqTW5G2AxRKxQ,iv:9S4eVUseTGAsq2HlmBBRC1UrJ5phtr2tYqkF49Fuuh4=,tag:3XSHwpu340yrer3su65Wbg==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:Vo+ItYBa1cZhGAvhjQQJnjLhOUxTXcPU/FuWnXc4lYtkdmbRj2gCVlPfnPIWzbMFSTuWP6MjC7Ad9OgNfX0cwoN9q6xW+q51/+GtDzdExj8SA4DlHJD9YbCXrmsAf9Tom5YJWJJUMqRKG/aeK6dHhpHt27m8/qzFGOXpVxs=,iv:trtbl0VCR5URiVGtp2YrOvmD0y0kedvuQG+/MOgwiGE=,tag:r2JqM48NO8rX6qIPfumlSg==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:IIyrDjMPZLun+Q==,iv:/gx5BenqSCR21xLxUaSoAVIyYpOHtJ0Ogwf7AJj4agU=,tag:jtFuA0nuRKCh35sd4/GpSA==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:5kJz91Zy3ro/ZtN+mpiyhvd0TCzq7pVqht+AxLNSud99hg==,iv:Yq32NsJ0rx4+7xz9Rba52xpvVcHTP2ZwZD7+Pn6K2nY=,tag:PutQA8vnnHndRVL5grMdug==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:hrTT3DqalYAPCdaPx6QgFqyoaRQ=,iv:znDdlo+CCBjIAbVrNANU6VacI3WzD+3PA/BxAcPi/d8=,tag:jh57IXlUcDHn3o+I7dHBCg==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:+X1MW4BQZBjY5WSCSeRrJPEOGP67yD84TYXAgxJdF6g6HofPsehyIhN4Wo3jk3InVlEMzioW90KAjo4R7pFWNA==,iv:qlAR8PEy/Cs1fApO8GBhq01ctZnRHb78AQ9NCFQkg7w=,tag:zgHkfNAQG7a7N1H7rGJRiQ==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:fqfG8rmkQGQbGwezZ2i00a52IqCprtIDMa0mF4mpCI+w9zseeh0vxnyfvw==,iv:jY9D7PqN22Fcxht1N1nQipiZc2bLkhE0FufYo09DR5M=,tag:9pxX4fpjlkRmDo4DSQvD7w==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:+mvEn93f0qLNgjdm3uZzJLYtNjlJilLmAH0GOMSz2nM2ZMSyaatf/Xfm2zWPoEueJtjXR6ArcTNbxxBrwAyeEi/gJM33DEj8YA==,iv:DdkiFOATBLtnEwOVVO98vLBMCZmoPx16lGHPFxwx4dE=,tag:lVsjBKECaKz8vTA4+vSzLA==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:b6C4yyqjiDNyO2XdxG9gravdSb9Zg7C/qsN7VsP9+JtMvduvp1gRXea6W/ewlkqLoYOLl8lMT8n2o4KIxw==,iv:HXkYTOoUCAe4W7z4qysrv7ySUI6soYpLp0uDfCM9pH0=,tag:T6JNNCVq9Dnsv/ErjUVsoA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbzdUS2t5cHhqUy9xZjJ6
            TG1hTzVHWGVCVUhoZ2ZoNGY2Q2YwUjlxaDFJCnFoODhMMnBYNno3Z3lucnZaRWNF
            NG1IYWZydTJHNUJWa2k4WFhiZWJqSUUKLS0tIHUyNCs2dWlqK0dZSWtIZWwxVUo2
            MkRHYWQwVklGQTlpL2pDek5VQVZ0cUUKOeloZVY2cKhoD7WWwvPVGzyCclKkHlkA
            B8aXOdLs6i/Zo5grRJMGl8WCoVHFJyvoRg3xRvAmxWKIHJQdKmg6Hg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRDBFdFBaVXY3NTB0N3ZP
            NVF0NjJtZ1lvMlZGSTNmQVl1ckpFYXA1djBRCiszWXFndnZqMG55WW5CL3hSQWh3
            OWZvOEtOcGdCR1g4OTRWL3FKMVVCNEUKLS0tIEptZk5zLys4KzV0TSthUEhlRGt3
            VkhCTHIweEIxQ0o1ditvMHdUZWFiRlkKwUL7UYF5bfywzrWrswOkUidj1VFnSJn5
            TdzVnaxPqpwnROkb2UgXmqx3hTnxmzdcj796JjuRBeGJ6eWEzlU9Fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y3BDSFMrQlB3clpjQ1hK
            VDFnZG9qQVR4Z013RUlnMW9wa3dzNHg3TGhrCjd6OVRRMTdLOVYvQlpqMGE1TFA0
            Y09HdjcyaVhMVTV4UTloR0NlcTZxaDgKLS0tIDZuY3IzdU1yc0loSWZBenlZQXZU
            ZXpJaXZaSExHWFBRVVJzekRCQ0gwZUkK05XVz2ul7sFuMi4yM5yKlGN99TVMDNL+
            iCI1daZO8PEC222kp70BmqpuVMbm/7tBBZW1bGuqgusd0rICGot4hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T01:58:59Z"
    mac: ENC[AES256_GCM,data:iqut0b6E49XpxhkNonG008zbagsTuJrxuaXV9uPUezXZ/e2mGVMVnoPWR68K9xQqX9Pdj9d/pYfO4NM+mzyxLCRCYir08IoZnS8j64vLV42mJh/wMpzlUyl5vULXw8bouTHxp2v6703zRKB+U6VIaU3APJT3frJKKxcrgqt2Cec=,iv:yFokHnhNCZD/zRWZnGGuSowsVPm7UkhCo4AqGG0YYg4=,tag:U2VkN7EXFNbMiBBalSnKiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
