apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:Ki/2/mM2A0lkJbVZ1vwzeTy8/6YP11/VDbJTOq2Cz0GQ4uFvD1bA8JLUH6ZQT8ivnmKp,iv:BsaquLCTT3V1QnXxmNzy92bRhJHPvG3Q1seC1pkE6RY=,tag:k2hjdOqf8kK5NDcJz59PBA==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:7ZPspxM+YsWKXdP00JK8ZM9MdfENYLBU2eGgPdodw6/0uFwNL2/y,iv:gvH13SszU0IebWgXum+R1lZYFIcXfHLiYu8e4j+vLww=,tag:hsr+YjpFZ2j3JYdWmF2vTA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:rNBSxESTBR3hAJdmidcfn1A6yGYRt8SpmwVUfpzRi24pXzPkDNn4Fw==,iv:wX5lZDAeibdf2POA2WVfuJemyZKikA6fwWRFY5xL7bY=,tag:+ctfv/F7drJDfgM2YYQbUA==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:pQ2xUj/MvEEll9NmQZ+WA+dlah4dk7pRBc7liIk4jnfkUWWoQD2PhGHpn88GhS2+nqt+r35UanLmfJFFDLuutzeIw9QXZRA+,iv:Lsnacbj4Neo1xwcU3lVF5Wm7/rrCaf3OH0sdy/bLrJo=,tag:b3TZvj2T/0/cYz/0QyJK1A==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:OPRBbNLjAdmZ7R4Enr6ypDHDZnEabkdLO8PWKEVLMu1QORtVKQsc7X7WgT8rJLs/cSfNDuO/wqQ43JncmddBscexnGNeZ4A9QvAAqjcTaOaInfVvfo8KMEu2f5yisFpYyRP8ewo7DwM0wABJ+l06oWSqbpoHw74cXjdlqUY=,iv:Es64j2GAFufdpu7uR9xbLC8NghrjtKRkN4JPHFmRAII=,tag:a7uo1FTiNg2WsTrc2MYymA==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:Zhz9DoIEI/uDbA==,iv:qrXO3APZJxyHDCJW3m/q3IyhG10LZtWtCqj0wC4wOrM=,tag:f4qf3oY3kFILjzlaBsEniQ==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:73Cgl0sJschEPOh0Sx9s4gKWH3OpJarD6j7L9AJrQCKdbQ==,iv:p+sPSkIBevqV7bQpziARYMfli/IQvBdaGI2t2JtKkZY=,tag:k5WmKkD45LgRMEVRxBNPSQ==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:s+n1bW06UMNHa/li3bsfNaWvTTo=,iv:tMxVXBgoRKHCVwKTYGFut6f1GBc00fO6ZxisZwhZprA=,tag:l+NA4Vi4C4hYp6cUgBDU/w==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:84XxN0Z3t9g27Sq7MsT1BQTGxdMbt9Q6PYYRFfrflsbqOVla5g2olS38vWVNzAm0g8KnRdLsuchAKsLGuoMMmQ==,iv:vymOX/8Jw2IhfJK7OGOBAMf6SP+Rg2tFTtRnI5F/9TY=,tag:iVmK0BSqA9ElkByd89eFDg==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:TITQKXFYk5TfA9c1XhgLmeim20Q57JnKHupKZQ3+14WPIHgC+1EjJQJjQg==,iv:pDhWkcOC39+WARmP6TOuUmSro7Sxx9791VqWtdg5h6E=,tag:YjTmvrtKLS++j9py4l/QlQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:hx2A5Su/ttVuRTV4JGnzh/itnwCnkKm6/9n373ttBTK/CnXPB3916N/0LTJGLBcLA0nKxUoKMgcdFBcRHRcFNA00NkjCvzB07w==,iv:5HJeYhdOjCTWzk/x/zQabZoYeCzEp9mYvb0mr2I8Osg=,tag:ArbK+oRsv4ZzIn9e45UZzg==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:xkJJm+bfujDn7nXg/PPF6Q7swi6SETmEdidgkYGsABmpjjXXir5amVQKEGHRpXsaBE4n//0Z9k7tPhMCyw==,iv:UgnI5hxx5/A5qMBB5DPqu9ROsy6Sxy2yucClH1VON2o=,tag:W15taYi+zDvJ/0R0TIn65g==,type:str]
    WHATSAPP_BOT_NUMBER: ENC[AES256_GCM,data:5PAD4IZ81lz0X5eRZ5g=,iv:lBnYH1iVad/AfSBzN0+p9uj6rWM1MMI/gAUjy+rKV04=,tag:YB1NTUbwl4R5mTNLNhNS7Q==,type:str]
    WHATSAPP_NUMBER: ENC[AES256_GCM,data:1/I9bCWbIscf2vmmxEI=,iv:mgS+eO6Iqr2HQFbeo7NzxbV0on0699twTpTV0XB7wqI=,tag:qGCuGKNZyWHkosfFXs5K7g==,type:str]
    WHATSAPP_NUMBER_TWO: ENC[AES256_GCM,data:qGk7u42C0DhD6Ev7fA==,iv:xVvXOXO2mcVnQEmjwmOJWsJeimCwFZV577vAlDmXD88=,tag:uC33+ur6PKSumL3QBdH4MQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWnZMajFiOEsyeGxlWGoz
            M2ZCUGZlY1U4eDVXOUZGQ2tUblpKcUdOWUdJClRLaWZySHlQSjl2dFZFQkY4TUdU
            NVYrYXU5OS82UGVNd1luU2piWmJJQUUKLS0tIHRKdTRxNDZtNGgvS3FSR3ZOTXBQ
            QWhtTjBwTHgrUWQxNzdHOE9nZzVEclkKdWv4odcgvw2jbVT05jT1wigRi1biCHVg
            NchLI408rSivsvnkuumSGXW3Uio3Ywzz4L7XfuRYxa0LBCvCanLGQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOWN4c0M5K1BHN3BCYjJG
            b0hEQlFuak1Zb1pKN0tFWUc5U0FJL0JXa1FJCmtvZ3JnK0EyVmJDVWhLbjI0Z2c4
            N0ZlMm9vTk4wNWlQcTFlUUNnV28vdU0KLS0tIE5ZZVF3ZThvMit6RkZ4amF4ZnFT
            UjkxaG1xNDlzZkQ1bmd2VWkrcmltcEUK09fNsYO+RWRQoUeJquRDilpL9yW8Gr3u
            ciyKv+NojQu2KVKyelIbIdyiXZybQwzvCXGgz9MHFzMzcQ/FX6+XHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERFp6ZUZsVmZpazRNMnFu
            VzQyRUc3L2hqSjVlb2s0UmhORXh0SUE2VUVRCkJoMThVM21SY0NiZ2ZXaDRNeWdn
            V1JpV0JXRUQ0WXdFc0Y2VjhVMXNGWkUKLS0tIHBxbGlMbUpqc2VPNE1lbTVOczdH
            Z0d1cC9uVlhpQlpKL0RsV1dweWF0VVEK6mUXs4C2bgZGXxRzVINSyfss0/9APUZk
            n5NA6x3aXk6zo34yY+/Qc5xdosxzwFMPJtF9KIncGD6QJHVzoMyCZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T03:30:56Z"
    mac: ENC[AES256_GCM,data:59osiCjnPwLUf/ELvY+WldVee2e2HwdWRYP4nlFSocuzPGUAtJRqeFDNWjgnEdrQN1RPyKx+1SRXzzMoApm4jejTR2lm6510hWBQcA2Nbb6bC8FvpqwTufc3QNl4QwL8dPiyQS27AixybqkwJ+G0Ulsae3QKTYBXlNt9Fmuhlfc=,iv:+SYQ/1HzQLopilRAkhaTWKn3jFLdZRZ2hyApysLBpGE=,tag:G8E2CifsxxJdHUWDp0VjKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
