apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:5HnG2La4ePPWIwd0FH7p+7dw3kbMCyO3rnwslw3PgvkqWh5wc7FPgqkJXkDW0mo0czRB,iv:phk/amg4/rlL2FjFF5FzrekD0EmxytlJotr4ahWiZ3o=,tag:BK4A0e9dNXQKh53/qPMIcg==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:m+vG07z7PbHGajzQvx8n9h6CEXhtz5CJxErQtEJQKZJLLibVok8H,iv:s+Oxqdcxf8pYuJs1A7SezpbhSVaeVrPdfADZ8ckmoBE=,tag:OkXQrtzlSzXWmBtAXjv/FA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:MrVj68Lzn73wU8lkiUvkmSGtGKN4xui/1kFLT4xtUP/sUz5nNnVzPg==,iv:vkZl6CecxOfq5qosiijrSPQ5SpeNvFyqegBxTCt/WpQ=,tag:iwGCaR2SYgSlzYyH5uZfGw==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:5qzIiXi/SosMyhf6UYUp+lBsSEul7Xy92FGSEfzjEz0CywSTI2Oaj9/zhGSQL8FbMD1Gyh3ccQ+wjZBMpjFrQdDVXrqsFuVN,iv:oGqLrL0IDfkkRK9aAoXnsCfW8343eaSFIFik6gSCDrY=,tag:Hqjn8oTAAlifzG3TXKfTUw==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:7waNZ0VGjLFJRVRdUopf9qJfL09NVIV6TyrAXILiYlFwb0vgUaJXIg1/dMLhi3h4PvI4G0rcLt3WmVijmmDfXBTohsRQS7sEzBfRvsIGQQNw39wDEw2mur0Eisdlrb3v7toZjCAQ3FisUpl6j4xHU6PcxNXfDkVpFrI4TEM=,iv:Oppk0M5EYBHnHIdtibnK6yv0X+JE7toCv30CA5pZdTY=,tag:iyq3UxfGnRVD69tTexvHww==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:NSQhJkIhdPPe1w==,iv:iP0sRZn4jtFb82wDriXk39fPogmIQK6OXrCtISWYRlE=,tag:VR26XwIMv3VHVcHYFlbK/A==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:0rh7RHbfHiGtMC1JqwtXJUCVFnp8V0jLETRWQVI3a8tDVg==,iv:1cyPBdvXeEFG/M1FPO2FMEotLHaBbJZBFqHGavqzadM=,tag:s7s0J17d2yX1FjnRTvjE4A==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:XiFXTFGbIKixQGmAHizmSWLG2Xg=,iv:RiCJuBzEaMQzmpiyHA375KdbrWBiKKwYTE8KyVHsypQ=,tag:FH6KWfkIlSqAxtUqpQ6lGQ==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:X6jm+BubN0x8DEmcoM/lrOeLkkiX7zGFv9uCQk6gFGRutn5c+HbhF4gEyxqIB23SrRqzYojWtzZc+gRQhTC37g==,iv:Z56AoiYiU1WfzjdAGoglkDfs+R1tEhf67dYo4UaC9nA=,tag:IYlNWU9l6h/EFe4Bpg+W/A==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:xYu5HdIw//oBjujQTzK39eekQL1qIc3gIK0n1OgDE+XlYdAGjCSQ6kf1vA==,iv:zBdSpRpy1Y05FA2CbvMJW0swrT01giPFdS1U7MFeFjg=,tag:8s2gHF5P+GTNQIml2LeA1A==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:Zg8CvCK600BV84AJZdRA5QMZNGQyuoulNypJR0q5VpumF4FavGoykRD+2IxPcRPD4DqqIi56jb68/ogpspiwsoPLZ7SGmjiCYQ==,iv:d2dMPcA6vga/cc0dRrTOymzr3Awxn1fF8TIh1159nGY=,tag:XaSapYFCqOzIe4TeEblBCg==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:OlTuwF4j6q4iyGk6Ix/bQypJMQ06MguyYgMbch3GHdD1I2eDlFRGsKipYs5SFJUTQBrWAaNDP+U7gGJ57w==,iv:YmkPv8mZmjDY+WmENUn4oIr9qKInKjjuD5dKflxGZjk=,tag:BJDuqnTW477pZHYa8h7mBg==,type:str]
    WHATSAPP_BOT_NUMBER: ENC[AES256_GCM,data:OOQ6bWagoYkvAUbk+pE=,iv:OjmEQufJ3R+xABB8+ObKm3EY7rNdqf3snQjc7zyiVaQ=,tag:NmxjflEM8N0+iyRmtaBZhA==,type:str]
    WHATSAPP_NUMBER: ENC[AES256_GCM,data:xFB+OLer7Avb1Q0lVK0=,iv:pFzj4i2pjJj5ggZwm3HVfjHEcQgYNcU7KI5FKrplC1Q=,tag:oD5nWDvcZXeWQZfJMzRUfA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK1pXM0dYQTQ1QWxtbzBz
            UWdwMG9YN3RMUk0vRjQ1TW8rNFR0TXl3V0VnCjRiU3RieEVuMitDQW10bjd3KzRS
            dktqZ2xkRThQSFBEa1doN0NtNEFpcVUKLS0tIGJicWtORDBHaGNsc1RmY1pKOUtV
            WjdyWTVDZm1sSnBPTkZBc1k4UnRac28KBZBQZGqKqorXQqZvaBTb/bTF6X2CY4gi
            FCT/FbOChE2AXiaVdg9EvCgBzW5R3ZKSJogaBm20FeL4YG721dwOOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdDhOZlI4SW85WUR1aTJ5
            RXBNeVNqUEtiaDJ0cThMVGhhRDNqMjV3TnpRCmZsVUkwUGR1RXBEaVU5alNFSVMx
            TDJPWVlSVmhWK0ViSXg4Y2M2aFpFd1kKLS0tIDNKcGdUQXg4eU12eWttNTJoeHY0
            OHYrbkhmSzlRY1FlYlgyenA1RXpZK2sKtAL/U81uj2z98I/VOWytztyKAZ37b0yq
            +cDtiUas/8asrO3iqEkfs2entJrQSAWtCfUXZBsC3TpjxbyN8EaJAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUGFyWU5sMWVHR0E5dmtK
            T0k4NnR5bEhXSUQzNVRFT1VXTzNEemRUbkQ0CjYvalprcXhMZlpRWXpsK3VicVpB
            Q0c0cCtXWEZjdVE4dDZnRmtTZklVTkEKLS0tIHlqd3ZHSkE0L1loZ2dxWnBZRkhN
            QjZnUGhaLzFRb3dLczhEN1hvRStXWEEKWpGfWnDoP91ji7P2eNdGk9d9yPGfLmNt
            jKInZuL2a9wrdQUEDtIGEPkgDkcm5XkLaMZAqBH8hnK4QzbTJQg+fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T00:37:41Z"
    mac: ENC[AES256_GCM,data:RLp35BixTV95TP2zt6UCK8muB/H8vaIA4DXzc41eWwGL7ZwNTzssssVm6oTUWg7qlRCtH9P6LtObTmn7Ol1VzCJL3Y6pbnOFstwiFrdwfqI59cNu2fij0H5XPl3wAtNBc0179imJgFzKOnsnq6aOmUyV/f2VZEWvBWcKENKuW9I=,iv:eg5REYcyXwtSmsOQYSQOFZjnf1TA0BDTzU4FTIqwsHs=,tag:+YUdPbYxnNgO4iT/2MQt1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
