apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openclaw-secrets
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:dk3VQwJN4HISy0KnaDxgRVb+lxsCvnKhuSyYQ1CqDjYojdToArhN64WdTrYSiruzDVF9,iv:4PMcaj9b0jf11cF5o0VqKs9pFVMIlSa0tAV/3Ja2d5Y=,tag:m2qbeZJJM7pcq5gAUi51mg==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:OCMasZ3xr4JlMJa5ut2Ga/E6WAduAdMZwmtJSqQ8yNmFJpnzwmhc,iv:qmEPWwN7claVNMs7U2k3cQAtbnRfwpR/baJ6gX06M6I=,tag:6myNbQf39fQL+aeeDELADQ==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:Z15do0GitiBd/MBz/scM5OUd2gmkqiY4Lo3ClIQdbhvqa83CB6XaRUKfQKwgxghpim9svgmrw8JujuKZOgp0xYQGdShYVVQp,iv:d4JQ5qFJdCyWD5zv0IeVIuJah9gvZ8zuCFFlpIz0HOY=,tag:7gBzCYtsyIWqeo3ij/soaA==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:ylCMMtCWIHuyCYR1NP7HOGe3MmiVI4LFmiLKBo7CdLcfgJ4nwi2C3CFB2TZ5Cz8zSjx2ZoFu+uHKy7a7pF0senFfG8LgUhJqk1GcL2Z3YpD/tLRAzYe87fKi/FyN8JMSrqW8dudxmb0FJrgd46mvzrf713GvSX3w3NLa94s=,iv:tCtHvVCDd/jDyzpnQtDZG8tk3Nq11DPX3LA19uVVyPA=,tag:KQlKEk6scxDlDPwwxDBz5w==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:GPkMxAyov1W72A==,iv:pTYqodYj5aScsakPYQ+aQ9dSD+pS1rwOgfEPqX3v8js=,tag:QWmnxlH1ehsYeziEiG0gng==,type:str]
    OPENCLAW_CONFIG_PATH: ENC[AES256_GCM,data:5vBwF5RZe4uZugeosmI4xYei/a8ThzGSDZvuSFVo/LGPpA==,iv:KBbWtrUPlmUaJxW0r+V/Pozchxoaxhm8ZBMWk51B0vg=,tag:U/8IWBU215RLlJJC4DpkvA==,type:str]
    OPENCLAW_DATA_DIR: ENC[AES256_GCM,data:lG8VFaawRLvlj/HKKbwVWSpYP3Y=,iv:nY7B5l3W/7FRKWbKbHId4/wzPPLS719X47VbOYZn+t4=,tag:BIETRGE2aDj+oXATB8208Q==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:Gn3lGrkx6Issz3E49UGEW45qgkNl92Ui+12y+nmJpCPFom+Cvuai4O0MHlXXGLzr2T4RQz5qHAOzBTEcPYTZOw==,iv:vStTyggWVqpx7LhTCccXKze0qxcdyxCjpQnNh8SxF3c=,tag:nCHPN8iScuxbbIz/eCTxwA==,type:str]
    OPENCLAW_MATRIX_TOKEN: ENC[AES256_GCM,data:WmrqV4ocxYXdONHw6CklZfAS3uMxzileh4UXJkYyq5Mr3jD/llSh813uhg==,iv:yKSbSd+orCjmGSjmof5m4ZSPrCTR8HwIlPOudyC6ipU=,tag:tKcoY69rxhjrqa2imqpVtw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:pK5VEqvdXI5AmvIbcTzXv2U88dnnvQq6vjQ4cWNh5EGh+nFfHzQVhgGZo9bYAxZXST3M7G29socm3N5IyaeBv8z2ZjgFX5ToKw==,iv:hnOvYi5XvRro4GfDKefq2AMofZ1feefmlDgr7E61r0A=,tag:R93xFTLnW7vCaXFMRpta1A==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:4NT9euoOiLxfVl+vBomZgKUcu74rW+vb2XXbVsXH7XA+8S5G9peDyPa5lGCnMJW1chhAEgphIEUvdiAP8Q==,iv:WF4bzN7A73SWm6mMmDBJPi24ew75DTLcRU9OHIC3Its=,tag:iSoKpSdZj0/pCM3dtqAw7A==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV05sWElCRnEzWXN1M3J0
            dkRKNmpob0dBQlFrTWVGdVZSR0NNaWpVaFNBCjc5M3dQWG5SQ2xFSFJINHFSazFv
            VWFZRGtnbHJrM2EwM3UybEU2dXFldTAKLS0tIEdRdWhxNk5uakJ0bjdNRFJCWE5u
            QnJLRkIzZEp6czhtNE1idHR2SUJzT0kKDI778zv6Ay9XhzVWhMmWWcJkXM7pTYzK
            nY1UWN73CAPD7YfvCdeJtzxnVUsKyU+A7ngQi1jyoFIPm7CqGpgmQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RjdkbVl6M1Fpa2lQS0tm
            SGpBNDg4b0FiNEEzVisyNmIyTVExTFE1dzJvCjQzWUdoVnVBdDRRZy90V2hJUnpl
            K3pOZ21jcDRNRlRUMnozRTZDRXVBNHMKLS0tIDJNOWpUc3Q0OVFFN1FFVm5ZQm1k
            WjFLTzF1UXk2aC9BY01NTjRzbHBCSUUKGukcvaVHVDFT/xIY7aOKxf2/oAa0GhiG
            l4TKwpvNKtz/K1BdAPhDCbgN7FGogAB8AQpNbASUb1Bi0Snea1R3fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMDBTWEc5akYyUytpSVNM
            TGVLdjlmeS9XTHNVcEkxZnBpWXZvQzZlZ1VZCmhqaFdYb0pGd2UvalBKU0pRT3dv
            cm9qZlZxSkFRd0E2R1d4cUVhMUMwck0KLS0tIFpNcVJZOTJUa0d4aUVGRFBTc1Yv
            YzVpM3Bia2hCeFpyeFU1TEJkeDNualUKhNZ8dSYNp1u8HPG+gHbiCtKqDTJlKh9y
            D8Z8GPWIrDnZfLjgzmlMN/EC01EbVGDhGrgWUuZfSdZVIetRf8LO1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T02:36:49Z"
    mac: ENC[AES256_GCM,data:w3YcK/5Pm+NrLsduh6BB21bhTP0eP339Fn/MzTNZZ/ZYMXIJwm+Neyfg1RAta9kHHHJ+rtS/JkMH4R0NpSkVTPdh7BBqWlbUyK+Gb6OK79/Bei5wz1gDNroC5mR4+1wdHF9pIMB+CQaX2QzZZ45SFyhhwSlsLzjfahBeXsPvx7o=,iv:Cy0HLY/YnRAdJ5ItmaR2jylMk7VL3tXEZZr9JSLPxVs=,tag:KxKTS+aWHhrwaFH+TyZnwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
