apiVersion: v1
data:
    limiter.toml: ENC[AES256_GCM,data:Yw0EFl9vmGFe1AaG52/M/n3xU7YLFz5ZZN0DKUiEqKOhLuvRbEj92m2DYcbZZN2dEcGQDb4fo1sbgjUz9zURSBAr6pTtOT5VYIioqzDOH/EIqmD/Pwes1ueYNeyCceOvdoAY1nn+rtH1KT/GHU3AnMGl7Bc16M6jZdHcvLhhCgurbmM6UIOlSAHhj0zYS8ugJo+TZ6z6GLL79Nx/LIzX2znv0wUsMsB2Cj9ZLrCVoC42hTYzukjoWTcfxd2vn0fVlsdjIFMO68kvLlgmRzXy+WQy0spJBrHgnXZUbEHWx2ZYa8sI0l4Ih8UOSrD6Vfa35E6E7VVSvAHLAdQB9OlVLcntlROeHD0VH3t4aLbkNcwL/LelBN5TDGg30/4Ge0k=,iv:M37QvMInCPo6ZRpaYDnB2HI4yrfH20AlvKE4bPUtBts=,tag:S45J19tKAOzpp5flCKHXSQ==,type:str]
    settings.yml: ENC[AES256_GCM,data:MKN240V3O4n5B9Wk6pT4o7Apbh9az0a11gbTu/JdBx5m0Z1fkXjKDtoajebEKrTrH0JIQ3rnIdMMnrjJ+n4xHU1n/RRNKmsCIr+wVTltKSqXT3/6FQipGnwaTp64NlTDrgOvZRrOGRxlzXUiH6ELe/0I1FMP4uFJFMKF6sBoNkVYMNDEabOeK/s1q0daoZ8+q+hzGC+4ccvp00L/Pl8EDBhGbb2xG44ZscrnrKpnRFQiNm14d5yp4YF8JfDtQuxNlxK+sEQCj4mWg3DkQJlvmtr80gh1FzsS4wxW+WcCdkhXPIh5bi79tgdpiJOyY1QVXlO88+Xya9RsSwWUSUKBo2lMLoms+qVWEUoN1zy7FL7lBy8GBAD6v113yzJaM2EQkJk9o1ukHAvsULUtf4NDlYTpQC5/vBREv/Mwe2WSB+Y/NkhITIeu8Bv5UOctXPyE5CkAH66dhPKcIhKOvMcTzAtAeOOBK7k9XdMU9NHIqqgWZJLFvl3PaLafOebzHx1nGiY2zTPBYn4hjtZ9UHXwIg/D6g4R3vaLcMle,iv:+ULwa8FoL1FgxOJxX2mJTPN+j49n2dN4OfiKfaA/SIY=,tag:utHKHREw34MMFX6TNJzGZw==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvV0xadjZ3eFMxZ2FiUkFJ
            Mm1wTGg4UXNuYW5QTThYRy9UUmlXZi9JMkQ4CmIwQjdhMGJtZ2dTQXJWUy8xQnNi
            SXdMU1I1dXNEekt4cXBCWWRERVdISlkKLS0tIFRaTko0V3FqUE9MTzdidEQ5aTcy
            Rncxd3V5bnNBMEdVRWxPUzQweVNFakUKDchfo+aKTVI/f+mK00a+FAeKmcKJTDKU
            USvzlLcyumcZsWrxMM5EnGfyO/NRhW2ipizQvYUE9q412ZcbIZ0a+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTGczeEdKUU9rVlM5VkJh
            Qmptdi8xbWUyNEJEUm9zQ2pLanB1NWVhb1NzCjZJdjJRTjZ3SE5WWUgyTEx4Zzk4
            ZzIzcjM5K2hsWnNENW1DWElmWWR6ajgKLS0tIHhRMitEeDZYSzJnYWRnRkgrYnFi
            MVdpWkk4dEdKdTBJLzNUKzFDaUVyUXMKqsl5UxuiyDIlj+8Kx6Xb0aw9Xca7Xtmb
            cTdV6Fj3rcz39p7u9QhY3FuXaLj4F+Z3ziEuat4LVU8P9jPZQMl8gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U0Z3Rk1HVlNMM1RNaUZj
            TnJORjRQeHI1eWtlQUtBL2FESmFtWUZkMWswCnQ3eURad1pYMllVcWhCNnNlQVJ4
            Y3hSbjc5aFdhckw1RkdwcSt3SVYvMWsKLS0tIGFjNDM1dG5QZmFjVmc1TTF3Qi8v
            QlNVUi9BZXpDaWh0TzYzVy8ySVlBd1EKMqPkIDibLGsgAy15ieS1BhVUpECxJAx1
            eHULmKFZqViHCySMjRmzHry9+J+sODGUUrdVv/KGSNE76hmuL+gNqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:05:53Z"
    mac: ENC[AES256_GCM,data:Wze1sg08e8ZQFNKLtVGhwSxq9C41PHkS7vtnuQaPoBWxyu7k7mUGc1omxqrD8dD5zUFILwbzRJ0irDk2oXu/UWSmP05qRX2mX6h/SqBy3TJr2HmLygKdKfU5zdcQzaOsGK8vJFk+KIod8rfC2ZaL16FkGnXShjURgRDlc21YHWg=,iv:v2635IxdwO9tSuBkdU2lkr/PLJV1klX45QqGf3yhCA8=,tag:0MIkVxSLUFrvJvznNpb4Eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-secret
    namespace: apps
stringData:
    SEARXNG_HOSTNAME: ENC[AES256_GCM,data:kLiTNzDqPDiGCDxPQAI2s3nhsRDl,iv:4G4Y8jZxenHCKAWBGPqk9quk4lzj26TqRpg2CR3rsgY=,tag:RSN7E7NNXpyPNwuxaQGyAA==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:yK2XrC9ZPBX/8d57XcobX9cStrXFiwEHRacOJ9Pr7JzrSZurtG7H79UA5OPam1AlSirngSJ4hmZUGKHVouWoSg==,iv:hV813XZwd91WYhUBBNjLfjphw89/wL0v/s52Iv+VCxE=,tag:DingvMLJU6v8FHXTasqfqg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvV0xadjZ3eFMxZ2FiUkFJ
            Mm1wTGg4UXNuYW5QTThYRy9UUmlXZi9JMkQ4CmIwQjdhMGJtZ2dTQXJWUy8xQnNi
            SXdMU1I1dXNEekt4cXBCWWRERVdISlkKLS0tIFRaTko0V3FqUE9MTzdidEQ5aTcy
            Rncxd3V5bnNBMEdVRWxPUzQweVNFakUKDchfo+aKTVI/f+mK00a+FAeKmcKJTDKU
            USvzlLcyumcZsWrxMM5EnGfyO/NRhW2ipizQvYUE9q412ZcbIZ0a+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTGczeEdKUU9rVlM5VkJh
            Qmptdi8xbWUyNEJEUm9zQ2pLanB1NWVhb1NzCjZJdjJRTjZ3SE5WWUgyTEx4Zzk4
            ZzIzcjM5K2hsWnNENW1DWElmWWR6ajgKLS0tIHhRMitEeDZYSzJnYWRnRkgrYnFi
            MVdpWkk4dEdKdTBJLzNUKzFDaUVyUXMKqsl5UxuiyDIlj+8Kx6Xb0aw9Xca7Xtmb
            cTdV6Fj3rcz39p7u9QhY3FuXaLj4F+Z3ziEuat4LVU8P9jPZQMl8gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U0Z3Rk1HVlNMM1RNaUZj
            TnJORjRQeHI1eWtlQUtBL2FESmFtWUZkMWswCnQ3eURad1pYMllVcWhCNnNlQVJ4
            Y3hSbjc5aFdhckw1RkdwcSt3SVYvMWsKLS0tIGFjNDM1dG5QZmFjVmc1TTF3Qi8v
            QlNVUi9BZXpDaWh0TzYzVy8ySVlBd1EKMqPkIDibLGsgAy15ieS1BhVUpECxJAx1
            eHULmKFZqViHCySMjRmzHry9+J+sODGUUrdVv/KGSNE76hmuL+gNqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:05:53Z"
    mac: ENC[AES256_GCM,data:Wze1sg08e8ZQFNKLtVGhwSxq9C41PHkS7vtnuQaPoBWxyu7k7mUGc1omxqrD8dD5zUFILwbzRJ0irDk2oXu/UWSmP05qRX2mX6h/SqBy3TJr2HmLygKdKfU5zdcQzaOsGK8vJFk+KIod8rfC2ZaL16FkGnXShjURgRDlc21YHWg=,iv:v2635IxdwO9tSuBkdU2lkr/PLJV1klX45QqGf3yhCA8=,tag:0MIkVxSLUFrvJvznNpb4Eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
