apiVersion: v1
data:
    limiter.toml: ENC[AES256_GCM,data:FyzOh9O/6vJR7wbLt1NkFMOwSefwI+QiBmva9M1LHVBuHEXw8gIiU4OEizKs2JF2oKeaHGxO48J7NB1+h31csyW6jADaEsSx2bZ6j3FOVJePwFOLbT9rZG8p9uCaBmksXtJg8OPk0M35NVFQK8krmYpvF1KT0FFcKJkzED5PbHNJswMNY7borRDYAfxOsoJU1P0oPACEPsRX6jsrQEumK797wJg1F2ENc8pgTnN7kLAXuWO9Z271l7p9XlfNuUrk/llLQzltN5W6DB/2CO4sHYjq4HfvtTrm2EVEtpjFn0xaBC7BSDkqhhiRw6vi1xqVALms1LYNV81VgtUpGo24PdIJ2jq8OaB5T6qul6VWwqkWDoCIVpj+Mr186THyc+c=,iv:qDK9APzsM+wALv/fntUnn9nCdpEv3kTGKlKJFWbUgUU=,tag:UVxkLh86AAyLtwFDSj+cEA==,type:str]
    settings.yml: ENC[AES256_GCM,data:aQuU9uPam1j4ZximCWWCooaHTSArtN1RlBi4zD31M0gJ4Qqab4VB07cmvsCD1nV3W5QV7yZQ1FgtLbyz+ffpkBqVb/MW1sSIM3Pji/tD7GBtUDbbAjqr6Hw+FmssrWvIZHB/Spkif7LMxt7qThppBLrGACvMBX294HqQuq2jIb9DPaQ9TKVZY4j6MQfDv5Gbo4/I/YEmH+T5jWVOa5sh/K/du8anrbqDHqry19t1Nm/3W0UT3f+8ToStQlTu71jv2WNC+wWxYArm14dsjiud0hs/WodxSw3fLXzwmPwMSiPvAqu16nHcJScdOBWZdjKLnT0OOngCHjp2SVLGxVU0sLsPCtPQD8Dp9zOofiWt4FwI3CQ6JhIvnUBpDi7k5RO6WLImOOY0ogvbeLJMsxqw1rI98kbjyN3BIkv1ol/XwU78qU+bO9INN6NrMn15aTbgNUDRcM+w0YPiP2arHiCZpBcM2mrdpW5KcXlQ8AkH/kULd/xkgeG0tHx/6ic4/vXSoQKVG+jVt1BQ7bJOMVRcucVK0PswbwsSzJoa,iv:qOs0f5PATK2CowHd7HpYw3kF3nsTVIBtcfkr0i3+2xs=,tag:YWVpfoPvjmlnDdAJSIk6mg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVEZjcERkMUlTZ2twWVBo
            SGxXSzdMc1F6d25CS1ZyTTkwcWRWWGczZ0Q4CklzVVBwM1E0WlZuOU5TRXh3dU55
            WUoxSUFsSHpmSDlYQVhCSjk4ajRVU3cKLS0tIGVqN0NFTnIxa0hCeHVyYk1wTXVG
            V2pzNDZyeTJ4K3FSdGZiL0hURFhFbVUKAF8KGHeVZ9zb+1CWMwPobSF73/OMDn0J
            VTNsl/BYSp36pZBxcEGwWxkdilE4lZvkbJMWdTYCIm4x/866xEFrCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRTRiMnh0RGt3a0FncFBM
            UjhwV1BkRUFvQVo3L0NrYzBwVVFBMFYzVERBCnNwQ0tON2xzbytSSXVORzVLMVNs
            Wk9KUHA2Nlh1SDVlc0hTZ1Z6WTZ4QjQKLS0tIGpyN3RzZVMxWWo4UldyNGdUZ3Jl
            eU5zU2QxLzRWd1NtZ1ErakpxTkpLdkUKnkRQAkHY1Gj5ir1L3ywx5gCmh7JXU5p5
            gcVPRSE9pMCWO0a1umwPcvTdAKc3UpTYbzcrD1IlngJPWKHifDzHJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VE5DK0ROK2NNMklnbnc3
            RWNtdWhmWU4xTkFBWDEwSGhZM05zSjBaejNZCjNnTVlMVFhIZk8vUXlOVGk5Mi9U
            RE5ubllZb05VaENPMW43bFlBemg5VjAKLS0tIEMxWVQxOXk2dXVhaGlTYk9RQVBS
            VEgyaS9vZ1J2REdQNU1qeWFGQkF2ZTAKUwlqkl7xg37+Dpy3njaWfPlgkAbKVmh3
            n10g4h7Q/f1ZoLT0LMRj8Ap2QGccW8+GXY6dac8rPVRmSG9A1b+A9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T15:46:31Z"
    mac: ENC[AES256_GCM,data:ElZPIDgd9R1qrxiC5k3pIhxPJX8MBjEaNRxuwie/bMo6ePwybaPDYU5aCaFIsZrBrx9ky/Lzxrt/NOtpiuhWjTWV55gISCp/yGUq4lI6e3AQ+L09fvA7+ZYJxcIL3Dnn+dGTObpCER1uiM2rb8iHJ1xNJd+DxAP1iyXE4hDaW+8=,iv:5x60UWU7Tvb7S+CTA94JUjga43j5f2n+nh7TqN3kyeQ=,tag:qfJVL5sswJj0k2ijfPjwVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-secret
    namespace: apps
stringData:
    SEARXNG_HOSTNAME: ENC[AES256_GCM,data:iTDQNANAQTnG83XMtS3YsBx0eDvR,iv:Z+UDihQ3f2mjMYfD+HEmFEpmpeOGPejaoFoIRpxYMT8=,tag:fuBSGPegaF+JgxhcWbx0NQ==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:fR6rlB+B9chEPSfMDlIxunk8jEmapJfZl1iMufpK9V63oy49ibHVJLs0oRHQ24Cp0PkrPUXlQTeZAsTYax5rng==,iv:gYsMDnd6cXaIvE1DwrGzL/SLh5DBHgs1o6wj/EAQv/U=,tag:mWlZZmST43QcbjIpnXyb4g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVEZjcERkMUlTZ2twWVBo
            SGxXSzdMc1F6d25CS1ZyTTkwcWRWWGczZ0Q4CklzVVBwM1E0WlZuOU5TRXh3dU55
            WUoxSUFsSHpmSDlYQVhCSjk4ajRVU3cKLS0tIGVqN0NFTnIxa0hCeHVyYk1wTXVG
            V2pzNDZyeTJ4K3FSdGZiL0hURFhFbVUKAF8KGHeVZ9zb+1CWMwPobSF73/OMDn0J
            VTNsl/BYSp36pZBxcEGwWxkdilE4lZvkbJMWdTYCIm4x/866xEFrCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRTRiMnh0RGt3a0FncFBM
            UjhwV1BkRUFvQVo3L0NrYzBwVVFBMFYzVERBCnNwQ0tON2xzbytSSXVORzVLMVNs
            Wk9KUHA2Nlh1SDVlc0hTZ1Z6WTZ4QjQKLS0tIGpyN3RzZVMxWWo4UldyNGdUZ3Jl
            eU5zU2QxLzRWd1NtZ1ErakpxTkpLdkUKnkRQAkHY1Gj5ir1L3ywx5gCmh7JXU5p5
            gcVPRSE9pMCWO0a1umwPcvTdAKc3UpTYbzcrD1IlngJPWKHifDzHJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VE5DK0ROK2NNMklnbnc3
            RWNtdWhmWU4xTkFBWDEwSGhZM05zSjBaejNZCjNnTVlMVFhIZk8vUXlOVGk5Mi9U
            RE5ubllZb05VaENPMW43bFlBemg5VjAKLS0tIEMxWVQxOXk2dXVhaGlTYk9RQVBS
            VEgyaS9vZ1J2REdQNU1qeWFGQkF2ZTAKUwlqkl7xg37+Dpy3njaWfPlgkAbKVmh3
            n10g4h7Q/f1ZoLT0LMRj8Ap2QGccW8+GXY6dac8rPVRmSG9A1b+A9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T15:46:31Z"
    mac: ENC[AES256_GCM,data:ElZPIDgd9R1qrxiC5k3pIhxPJX8MBjEaNRxuwie/bMo6ePwybaPDYU5aCaFIsZrBrx9ky/Lzxrt/NOtpiuhWjTWV55gISCp/yGUq4lI6e3AQ+L09fvA7+ZYJxcIL3Dnn+dGTObpCER1uiM2rb8iHJ1xNJd+DxAP1iyXE4hDaW+8=,iv:5x60UWU7Tvb7S+CTA94JUjga43j5f2n+nh7TqN3kyeQ=,tag:qfJVL5sswJj0k2ijfPjwVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
