apiVersion: v1
data:
    limiter.toml: ENC[AES256_GCM,data:EsOdRfBX214YtT5E4bf0r8l8XdrUNUm0gtLuyc+/VvjmVYXANE+s9O+R4GszwgDg65xfluSFNS+mYaLfHeEegGeGeZISJPtFJF8evyuytNIf6RyzqqJy3lPfqwHdwH3Jcrl/KsKNKllgUaj5aVXm8valHcpBOwbmCWu+WrgQ9UynvPXs7e8sk0sJsKl9TqHpbaR65dqnRZSxKFIybAJVLc8zEw9gzyMOSD3z+pp3qos9flwWeylBnZK67z9SPjMCPD49kh36OJG3CkxFcQIgy0oHcAimIc7+yglIXBf71WqWbSeG4jkI8gRZy9TtB4xZqsEX+HccwsIHapKycG6rqKGGXxUPCrhiTuWF63XrQgRkJFDFtEYktoF8J7P/zuw=,iv:6XGxECyFqgNTfZLHiTfJ8+riDm6Fbw200kktlKZ3IAs=,tag:2mR55ciU/EYqlvVy5OLKpQ==,type:str]
    settings.yml: ENC[AES256_GCM,data:YxbNruVSOvYZNDwjsLQHXUa3CPT/u5UWVfbisi53jNlFvWwRuU9FWWhey8cHAWfrcmjhMZxyFxfU4cbfkhTlBxL2OGgsh5XdEQe1uQYF5Zrn8epesu1qk1m5E5+G5pTqYg+Q3EKn903k+f6g3SGmfrdQyhzXJVeiN3f4XvOiY/twT2CxKqw+vpk8U7ek/SfJn0vBZk+sL5rLuAX0hTDa0jrW7cMbNjcyxD80yiARyrQ+WDtWtNFFyT6c7XvozvB3wd+XbIR351S6IIN01nymFpr6Werz1EMUHvxCTR0UzolNKOmlmxG8sJ8SlbHboggpz9oUH2dcmVIoZBQV8zyYnJGkkdweGZtcnXicnIe+vTd/zJZt5vAzoL+xY7bujnmtZZUSAbeCw5cYrFQEUhNWgj9B6aVhEgHUr/gJBNbkqp35aJZrxWQm124Ol1QfQecXi9OEK7LnUQrUNZbsPNW3zvgxO+XaVoztY2SJ+dJpIrRETlx0EKoQDWj743+M4BuGHpkbOc0vySj+7bwR7X2O6k5fDima6ZcLyqs4,iv:3rwZbft5oeuUIZzVkmw5lrhYtArEYnz466Jdont0Aaw=,tag:0p7sexpGij4vD0Y4v7LpTg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRGhtNnJTdlVUWFZYb3JG
            ZkZRNmdZOTEwcTEyTmR4QW1UdzU3ZlBaYUdvCkRjUm4wUnliZmZzTE5iMEJ2NFdW
            YzR6UnVlbEgrcTN1QnBYazY5MENCaXMKLS0tIDFEUERZMWJESmRtY0x4SDUxT0JN
            ellUbDhibTUxNmlFWFcwL2VFckxMK1kKz0dKVEMAEaTvWagQenKr40tSEXBHRWuS
            64906Cdn2X2Dgb91x3vF6iTxSLx1f4qquipjeUj0hTwsTKP2OUE4NQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYjlKa3RYN290UlRYcytY
            djQwS1RkOTAwOUhaYy9TNXQxSjhialpqN1Y4Cmc3TUdOODhxdXFLaFBkUlVvV2V6
            UytwUFB2clpoZlpTcWJ1d1VXYkNFWnMKLS0tIHlMam4wdTFycFlNS0pUYnJXVmlL
            VnNFU2lnVzF2dTFrMkh0cTNrLzhhYUUK1DSuovdNhb+TQfiFFA1iWyFFGEfFJaMi
            jPsFrg/MDD9g3wUvHamMIvc53gczJeDl7THXWz9zSLYEzL96AVQxQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTktKNy9yeEluNXNsQ2Qy
            SE5xNWlBZWZCTjNSWTh3MC8xdzV6azBNdVU0CitINDdrQnBjS3NtUnlOSXhYUVBl
            d0JYblhsQU9DZjlPUy9yZWxkNU11NGcKLS0tIEVEYWZUV1RoYllTVVptVURjVFlJ
            WWlmTkg0SDFqZzg1RGYyMFZOVThxMUEKUFKx2PxHZNbA/+xJ5cRNsLXtRYl9qsba
            ssEk2cOuMh3584zdAmfixMtbv1vRkYP7WMFKOh1w7ZbtE6GC6qwTcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:10:48Z"
    mac: ENC[AES256_GCM,data:pkRWneA3fhVdEwB1HOBqLAtZG4pWNK8qfR1JJ3kaoewjH3GV3aOZt7zx5ORrMEb7UCHK2/zwG3zsJ6OWArVlwmQKjgFYJt+CJXM6k2CRwIxiuDVlDxBCKgiGf+Ann4xpCWgIfCsZmBdrlLyItuWJ430KV4nFYBWSQM2PGVstgSg=,iv:weF6Vx76w+Yxb6gVsd1okH6TQpNhs+/Q1kpGoUSsVfA=,tag:CN0y5iHycSIawzuL5dod4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-secret
    namespace: apps
stringData:
    SEARXNG_HOSTNAME: ENC[AES256_GCM,data:hDRWWlWW9WwxGw4lC/mcbU1BL2ed,iv:aOqdeNapr/2pQ6vjCnaL7vaIb/rbSFxu6fBL1X3tWhw=,tag:jJzBQE40WnjLMwwtcIdRYg==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:0VToS/nDTDuAkjYtJSP/TSOD1+JCJWyXhotwJUUejLG0cSI204By1dc0SgrnlOECE9zNktFyqD+dmdWjAEbQBw==,iv:9TzimwB8rUSjGtQ2MMOwkdVJbrygS60a8DAavaqX75Y=,tag:1WagsCJj2n60BOy0HttW+Q==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRGhtNnJTdlVUWFZYb3JG
            ZkZRNmdZOTEwcTEyTmR4QW1UdzU3ZlBaYUdvCkRjUm4wUnliZmZzTE5iMEJ2NFdW
            YzR6UnVlbEgrcTN1QnBYazY5MENCaXMKLS0tIDFEUERZMWJESmRtY0x4SDUxT0JN
            ellUbDhibTUxNmlFWFcwL2VFckxMK1kKz0dKVEMAEaTvWagQenKr40tSEXBHRWuS
            64906Cdn2X2Dgb91x3vF6iTxSLx1f4qquipjeUj0hTwsTKP2OUE4NQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYjlKa3RYN290UlRYcytY
            djQwS1RkOTAwOUhaYy9TNXQxSjhialpqN1Y4Cmc3TUdOODhxdXFLaFBkUlVvV2V6
            UytwUFB2clpoZlpTcWJ1d1VXYkNFWnMKLS0tIHlMam4wdTFycFlNS0pUYnJXVmlL
            VnNFU2lnVzF2dTFrMkh0cTNrLzhhYUUK1DSuovdNhb+TQfiFFA1iWyFFGEfFJaMi
            jPsFrg/MDD9g3wUvHamMIvc53gczJeDl7THXWz9zSLYEzL96AVQxQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTktKNy9yeEluNXNsQ2Qy
            SE5xNWlBZWZCTjNSWTh3MC8xdzV6azBNdVU0CitINDdrQnBjS3NtUnlOSXhYUVBl
            d0JYblhsQU9DZjlPUy9yZWxkNU11NGcKLS0tIEVEYWZUV1RoYllTVVptVURjVFlJ
            WWlmTkg0SDFqZzg1RGYyMFZOVThxMUEKUFKx2PxHZNbA/+xJ5cRNsLXtRYl9qsba
            ssEk2cOuMh3584zdAmfixMtbv1vRkYP7WMFKOh1w7ZbtE6GC6qwTcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:10:48Z"
    mac: ENC[AES256_GCM,data:pkRWneA3fhVdEwB1HOBqLAtZG4pWNK8qfR1JJ3kaoewjH3GV3aOZt7zx5ORrMEb7UCHK2/zwG3zsJ6OWArVlwmQKjgFYJt+CJXM6k2CRwIxiuDVlDxBCKgiGf+Ann4xpCWgIfCsZmBdrlLyItuWJ430KV4nFYBWSQM2PGVstgSg=,iv:weF6Vx76w+Yxb6gVsd1okH6TQpNhs+/Q1kpGoUSsVfA=,tag:CN0y5iHycSIawzuL5dod4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
