apiVersion: v1
data:
    limiter.toml: ENC[AES256_GCM,data:r1Rd2dBKf9hFshDOcwVya3b+Y3otLvAMPXgk3Hbzxe6RFJ/FvDoaydOkTlkkdDCfBkraomm38ANeXsYBvCgvpuBB1gbbAbmPR4GCB8NYOYa2D6L0wRv9oE2poC40s8Gcd9JBqtdKwiQWd/Ts1VlFkGUaU4IqgvN2mezEG9rjZqbJlWg/N7dgbpru5LpZiHUltADOADNSaLhbo0meYIowmMRp5eBo7kjfnLRyd6qyCiwVPGyDnPxygtQvd90/AiAgaxxRh4HiFofB1D/sk/iaoAAQt+j8kh4QMawz6O20dFYzTrt3AzYs3KzC5at0O4svRBHtNIHl63DJ0ewJgKxrAa9yWxfXRObmrk7r17EaNT6oeXGyJbXPeCLt5pVXN7E=,iv:h7KgihIlGqAIG8xvCHBHW3wLVtaoLIPXbAhKmWg9e0Q=,tag:Am5yEJGNJNomrx+zXwTB9Q==,type:str]
    settings.yml: ENC[AES256_GCM,data:mGaK5VE/ZqBCFsVfvpWTJAEGW9cpTqFzMjR9QgezdTbU/oLnfg+hVwNSnY35A3gGOhuwEFCs0YnlBp2ftUkDkqWCqR0zmEQJGQvLo31Nk3ykQ+xtEC7lW0CXF6PvJuSQc1/K+48kk2BusCg+NgixI7rDBpQM5nrh63ox7gA9cM40dA5Cs5kRt9q5pANb/FWZ5VnyzuOxS4lTuP6owQJjLazF0nVKpY4kX7Uys5aS8UhogDfYdQIoiHt3YVeLGyLsI7A0pMcXr7cF7vPywqj/yqz8oMVslkztYPf1OocE7SazbUawDhhFTdZtEF3vs326wJQzTCychoTPa63RShZ6UzIpYtOFv9l8IYfBnQ2gO9NJM+RG8aD1rddi49Wx0/zDop9aUD9bGfQ7qnr7jkrDfflaLtRaOs1Sfmq/PyunPGtjgmgB/4GKrIyCqwEhSsIkFBJE81x0un3MkPsyNrY83zTE+8IxCg0ZevXfkJzfhFFypMjjdVRm0yMjF5D3OP8G4tWuNzFv/x8ggGfeIAlZlURsQZ3fM7wAI84+,iv:pXDbfg2O0OiFaQS8CwH4Y9nneQ3hOVO1is14pBF1D4s=,tag:YGdOlRxZAmMRdYDKFdJJoA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHKzBqMmxYT2ROYlVOeVYy
            Um83MDUyZS9Kc0lvMk5Kd2k5WnpCR254cFMwCloybXJKRlNuZWhEL1EwVWJ6UXpO
            UUg4RUU2MTdtYWtWcmI5VCtvSWdIekkKLS0tIFRvdjdYUmVwR2I1aTE5R21LTjRY
            OHg5Q1B3MFpXTEpVZWFUeHRYQVRZejQKimvXD9phoY4I2KEM9/AemTFRSXIqFOSe
            JwShV5Iz+SEErsCI8X17BrSAGmDJ7+3yQ9hIsvsdZ0dOutb2zIV9ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZ05GVEtiRlN3eFBMZUlW
            bG03SzlOaWJQTXMyWlV3TFB0aHU4TnlmMjBFCkxLOVFKOU91RWVwNnpTeDBHSmYr
            eUVCMnF2NythZFFYbVA1UVJrZGZDeDAKLS0tIHlkTU8yL1k2bUNVTEtlRDhTTFIz
            clhvYloxbEJtOEV4bUNpWU9icTlnMTAKoyrSBOyzdmRBS2MVKb4vmmKpVsEMqKH2
            YSy6YKuICkLiOkNv0p7dbvOXqBLrU60k6EAlaqlQMhEg4Gqz+RxkTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRmhrMmorM2JMNU5FQTFr
            N09yQ0U3bWU1Q3Z1M1dtSHMzK3NmU3B5b3lBCkVHLzh2Y081TVNEU3pNRU4wNGMw
            ZDZjaHVoM2RtK0NHdlJ3ckkzS1RzUXcKLS0tIGtiUnZQSEM0MlFkUWpmN3I5d0NN
            RnJNZG5XZU9ZUDlKSjNtUFNtTDdUa1kKDPhS3OImK4aq9613P/s1YZ75DSbH+AbJ
            72JW0bbs50MvSfmQijGlj6piQytrK2i54y/psCQdHQy5dA9AkwzY3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:02:36Z"
    mac: ENC[AES256_GCM,data:egc51JPxUs37N3wiHsvwfVGCaaGIJ7XwrJzLPlQoqNrZ9ZUQxNZ2pmMDHvdg4P6iVf9d2gYFr//NydTobcoYK+Be1ztjJT5nPF+50cDQTqNfjZcn/MiM3UpqFZal8Z0/A1O8eEdMnpXEdd4djL3sH5RwZZIq+S2RZhXIipQs5Mg=,iv:ulDg5Ei6MOKDrnGFeEC2/48taZPoYXnEV69T0JRiH+4=,tag:1ZU6b6PVSCt6RDkpl7VqEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-secret
    namespace: apps
stringData:
    SEARXNG_HOSTNAME: ENC[AES256_GCM,data:7h7zSI1wJ5G8ERWGp116j0PCN6Z0,iv:MZUTvqEKTb4lXxaVaijCR9o8GGs6d9vqZEsNfKwfok4=,tag:91L9AJMye1fDl0RWml3+ag==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:0ZhR+6zVqHElxje8pWg8LAIkb3n/kLOaPSbtCyccBjTKPAWBf/UmnP7WBXDa4/GwT6Wmrds+UtRnPUgcMgffgQ==,iv:KbdwkR/tzS+YLpY03oeF4sfvwmbeMvkrmTImUiWmcQ0=,tag:d3HrJvCmQ1sk/sgnPOLyGg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHKzBqMmxYT2ROYlVOeVYy
            Um83MDUyZS9Kc0lvMk5Kd2k5WnpCR254cFMwCloybXJKRlNuZWhEL1EwVWJ6UXpO
            UUg4RUU2MTdtYWtWcmI5VCtvSWdIekkKLS0tIFRvdjdYUmVwR2I1aTE5R21LTjRY
            OHg5Q1B3MFpXTEpVZWFUeHRYQVRZejQKimvXD9phoY4I2KEM9/AemTFRSXIqFOSe
            JwShV5Iz+SEErsCI8X17BrSAGmDJ7+3yQ9hIsvsdZ0dOutb2zIV9ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZ05GVEtiRlN3eFBMZUlW
            bG03SzlOaWJQTXMyWlV3TFB0aHU4TnlmMjBFCkxLOVFKOU91RWVwNnpTeDBHSmYr
            eUVCMnF2NythZFFYbVA1UVJrZGZDeDAKLS0tIHlkTU8yL1k2bUNVTEtlRDhTTFIz
            clhvYloxbEJtOEV4bUNpWU9icTlnMTAKoyrSBOyzdmRBS2MVKb4vmmKpVsEMqKH2
            YSy6YKuICkLiOkNv0p7dbvOXqBLrU60k6EAlaqlQMhEg4Gqz+RxkTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRmhrMmorM2JMNU5FQTFr
            N09yQ0U3bWU1Q3Z1M1dtSHMzK3NmU3B5b3lBCkVHLzh2Y081TVNEU3pNRU4wNGMw
            ZDZjaHVoM2RtK0NHdlJ3ckkzS1RzUXcKLS0tIGtiUnZQSEM0MlFkUWpmN3I5d0NN
            RnJNZG5XZU9ZUDlKSjNtUFNtTDdUa1kKDPhS3OImK4aq9613P/s1YZ75DSbH+AbJ
            72JW0bbs50MvSfmQijGlj6piQytrK2i54y/psCQdHQy5dA9AkwzY3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:02:36Z"
    mac: ENC[AES256_GCM,data:egc51JPxUs37N3wiHsvwfVGCaaGIJ7XwrJzLPlQoqNrZ9ZUQxNZ2pmMDHvdg4P6iVf9d2gYFr//NydTobcoYK+Be1ztjJT5nPF+50cDQTqNfjZcn/MiM3UpqFZal8Z0/A1O8eEdMnpXEdd4djL3sH5RwZZIq+S2RZhXIipQs5Mg=,iv:ulDg5Ei6MOKDrnGFeEC2/48taZPoYXnEV69T0JRiH+4=,tag:1ZU6b6PVSCt6RDkpl7VqEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
