apiVersion: v1
data:
    limiter.toml: ENC[AES256_GCM,data:L6ye2mo/RFRSRNYhS/pL4TDC4c9cAFJcb7cfTs+b7Uecyl/Kz7fg/1yvsuSW4kRElJQQy8xO1NvcVanHo2relcu7UMCz5kDqREp+OijCXZI01glXSCAtIz042BnHNv5JvTiw3zKKNjrhVSOAs3drWPWuyrv67uamuGDXs9mV+VWgJZwyPc68gIRR6j7yMmL+hqwrDlTNq4buVxWVziCCUQu+Nc6ZEufaPGlJfbPhnvNHVs+yZXFLYz6Xo+RNKQVo61gGzEedtGdCWPK2+pHavKUWThCIdFKpbgBSN9HNAfHQuGj454lGOwPoc5+Un7q5ANnfS9K6FrnE+VoKYl+A7EhHBZdLiRPD7UudRt0vFyKieY6tclsP9j5sW9maoZs=,iv:LXG06B51oQxj8OhHz2idJjMNlt3ReiAMXiB8sFyKmAk=,tag:CwcDverc189LXUolvmnTZg==,type:str]
    settings.yml: ENC[AES256_GCM,data:6z5BkareBkgGDFjBpRu8Mm6RmmalWsE+F55PGPotwMAzL2TsBCBn1tUXCjOzZswhcgYUAXxbf7M/5OtC0Uxpdon7O5nWxxEqE2Zx2zkdXySlbGAEtCd0Ji88N1tGf4omPr48YqMP+oyg3Pb5wr+CLqRUKKKs5MGj49Busjot4+5ItGBz6eZTencdINffs/CDLLTQxxdoYVYGYF+OY0x5eR4lo6u34AR3gMLymZzj9N/OF9diHk4iqFhXTjjdbMCzgR32mPLdAl7H8dtF18FQSxVrUxF9P1brBKTTCFBH8a6iwMgPsEJ3QtOxWgXfuK0xXi0xhEq61FDHc6Ul35H3tyFE6B775QSwNTNcp7J5K41sJ003QOWIW1L4Cx4jRI7TXJZdRU2AiGHLeusrKWtAdSEg1K5oF8oDmcPYjp8t05d7vevsVM5yHoXmRTdcH4NKdE78YD9/b80p9sRf0ywHbYP3swtpELlDG60t6WiQxmy620hHScK+Qc9NtIhBC1DiCkPIWlzUQ1HXhXGmWUGKqCiQTEU2K2RXJVT1,iv:gwiGbaGy9fQZeWAfp1uuoguvxy0KG5vSV8AVXbu5XTM=,tag:QZk2sXIy8u+fZNENlNvThA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Vzl0bERod0FwUG04eGJo
            cmVvZm03dGluQm1BUmhqazF6TGtNNS9XdGdVCkRHb2k3YkNVOCtSc3o2dmxSOHVX
            U3U3RTBoaVg3K0FRMXNOZWxWQ0JpN3MKLS0tIEQwbmZCeWovSnRZYXp0Y1pmZk93
            TWlRSWFmTGE1d1lDRVBveXl1RE51dlUKDjLUc6CWlBOXXTlOUvzSnnVJbQdbgdYb
            qrHcpg/qXDkFZJjZmMax/f+WPFJx+keVs4+ZMIeEVDuEVmgtyLbmiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcU1oVkh5MnZjMUNsOE5C
            RCtiblhtR1crc2dtcjRHQVZwZmcyS3c0NXg4CnYzVHpqV2t3OHB4Rk12VVk0QTJ2
            d0VLZmZWdVJwbXUrTFJIM04vZXF0eTAKLS0tIFFGeG9kRnVjVUFHeXhEUEVjQml3
            cDduWExFSS9TaGkxbU9aZmo4My9SSTAKkvb3P8gmrqm99j5m1O4Up2cAH00X9tLS
            UHWUovQqcUCzweunL3qYvdZlZ0bG0+/GTcfiIslu270++YDWecGXjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbWNFQ01kNk5WWXljWDcr
            dFRPRnBvK2pmdS8zQmZITzhjV1plN1lMY0ZNCldUQ0U3eVFrdVROY29SbUNYK0tq
            RCtTb0pJeGlkYTh1UXlTZ0JmRFpURTgKLS0tIDZEYzBValFLeEFFbEZzZU0vSkE2
            Tm1qQ3R4RnJnc0VQbytRQ0Z1cC9DZDAK56oJxQ51mbbHZLNgVIcjinsj7jBQ/l0t
            suVVqvihu0/HT6StxcjMRqEJiCvM0IUtnUgm78AzRPXDb6BEDQI34Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T13:46:16Z"
    mac: ENC[AES256_GCM,data:bVNA9pSaIkWpwMYYCn1CDkuQuD1nF37voGo+zHgl9qr4E8rixF+OGjzYXg4WcH0YqRzN4QnWJJNAs6Q8kWQabwAJEO3DUg119d3BXQ7/EtyObCudOWZI//owvn46QhXuhl9FwSp1RbyNcpnlKa1KQRCKmnOGKvdsagWRWySjo0A=,iv:g5Hz3IhltpBnomf0lry3InrwbTBL5SuCNaiXHs7oKW8=,tag:ICGlDpuTX3eVlVHZpMkVMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-secret
    namespace: apps
stringData:
    SEARXNG_HOSTNAME: ENC[AES256_GCM,data:IoOdEZVHJR2CFEJUctqK6BAiKOFz,iv:8pSTXQGvgAGYEXP1LfZVjYWvtv9Cr+2w26NehGQlO3Y=,tag:fPrsFI7tmbrbHhDXJxSpbQ==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:fkDJnFto/zTe8oUxEKUwyHwqXVyva7qTEoix90rFiomHE4W+2dT+LwiFO3ATAomWtgLuIKtmHZbu1Ny1Dk93EQ==,iv:EAPJB31AXtpR70AZEAUrujmsdQufp4SrCBVsa1kKQxA=,tag:szvrp8WRLRyHLfnzSwuavg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Vzl0bERod0FwUG04eGJo
            cmVvZm03dGluQm1BUmhqazF6TGtNNS9XdGdVCkRHb2k3YkNVOCtSc3o2dmxSOHVX
            U3U3RTBoaVg3K0FRMXNOZWxWQ0JpN3MKLS0tIEQwbmZCeWovSnRZYXp0Y1pmZk93
            TWlRSWFmTGE1d1lDRVBveXl1RE51dlUKDjLUc6CWlBOXXTlOUvzSnnVJbQdbgdYb
            qrHcpg/qXDkFZJjZmMax/f+WPFJx+keVs4+ZMIeEVDuEVmgtyLbmiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcU1oVkh5MnZjMUNsOE5C
            RCtiblhtR1crc2dtcjRHQVZwZmcyS3c0NXg4CnYzVHpqV2t3OHB4Rk12VVk0QTJ2
            d0VLZmZWdVJwbXUrTFJIM04vZXF0eTAKLS0tIFFGeG9kRnVjVUFHeXhEUEVjQml3
            cDduWExFSS9TaGkxbU9aZmo4My9SSTAKkvb3P8gmrqm99j5m1O4Up2cAH00X9tLS
            UHWUovQqcUCzweunL3qYvdZlZ0bG0+/GTcfiIslu270++YDWecGXjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbWNFQ01kNk5WWXljWDcr
            dFRPRnBvK2pmdS8zQmZITzhjV1plN1lMY0ZNCldUQ0U3eVFrdVROY29SbUNYK0tq
            RCtTb0pJeGlkYTh1UXlTZ0JmRFpURTgKLS0tIDZEYzBValFLeEFFbEZzZU0vSkE2
            Tm1qQ3R4RnJnc0VQbytRQ0Z1cC9DZDAK56oJxQ51mbbHZLNgVIcjinsj7jBQ/l0t
            suVVqvihu0/HT6StxcjMRqEJiCvM0IUtnUgm78AzRPXDb6BEDQI34Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T13:46:16Z"
    mac: ENC[AES256_GCM,data:bVNA9pSaIkWpwMYYCn1CDkuQuD1nF37voGo+zHgl9qr4E8rixF+OGjzYXg4WcH0YqRzN4QnWJJNAs6Q8kWQabwAJEO3DUg119d3BXQ7/EtyObCudOWZI//owvn46QhXuhl9FwSp1RbyNcpnlKa1KQRCKmnOGKvdsagWRWySjo0A=,iv:g5Hz3IhltpBnomf0lry3InrwbTBL5SuCNaiXHs7oKW8=,tag:ICGlDpuTX3eVlVHZpMkVMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
