apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: sftpgo-config
    namespace: apps
stringData:
    SFTPGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:zwfJetNVdDSbWIiZFDZXu5s9J7TUy+ZmQZ7RUcDXznhvJQ4rH5qtx9z5VZtn,iv:IxIvAANHJYVrpiTB2QheKE8Xnd0l24ChmU6MHzk6Ugk=,tag:M4KFM4u/fOK6lf2TthGv5Q==,type:str]
    SFTPGO_ADMIN_USERNAME: ENC[AES256_GCM,data:WLya0tk=,iv:pxfY1HSW1pR/mojn+gAGWwAzZUYWxG1hR7uGFw/t4Kc=,tag:+3UaL57v5GxotXCvdWTD0Q==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3V3BzdEI2Sk1lVkJLQlFP
            K0dka3NIZjYzVG5TS3NRVTV3MEFSNkg2RGdRCjErU3VIVWxRTTZUdWd3QWpia2xl
            aGpmcTZiUGhWRmRGTGtrUGp5K1kyVG8KLS0tIFNxOUljeml5M2hwSnFOaXNWVzVn
            NjByNGZvNFRPWHIxazI1Mmd6QXZYSGcKuKiQMDMmXI4elsgLq8Gi2WuG3qhj405c
            nuynjfDT0B7jvB6TgwK6SGUqbsjnc0ffHw90+o80m2AvDOv8C5kO5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL2JKSlVMMWtSaHdxSWgr
            czVLYzJEWE1McWlnZjFNMStXNTRKZFZyWjF3CmIxemtHSVNpdHRmOEl3UC80OUhx
            Sm1TWk9CVUQyR0JmSFhERzNxSENaZmsKLS0tIDh3b3E4V3psck1KSC83R3EwYk1y
            V1RyWGU1WVFRYlpZcko2QjlaMnRiNFUKc/f8X4IRlBsySeTkoAAMSBAMHL5TrPqy
            qXJW6fjScJrCiqv8eO7wz4049NbAECW3ivGgji4uQ97DK2hoos9CGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSG9xNDZmQU93TGtUZS9P
            SEdxbnAzSTRRQnQ0R0pNN3Jac3ZCQmZPSmxJCml2aDAySzNmakxpcms4R0FUYnBi
            Y24wc2t3aDNVRUNNTzZmaGc3eWh3d1kKLS0tIG54OTNvWERpMU5Qd3lDQjNTVUJE
            b20xRmc0WXljMjlkS2V6elYzRGVmRzgKHAGd289/E3uUmIkQvz+xOUjys0I2FA/a
            zzxnB36b4Cp4+Z3hcpyiC1BolWAsKTQByPPcWpjpyfZ7JtriK7GlrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:10:48Z"
    mac: ENC[AES256_GCM,data:SHRU0WqYBm5L22msSvosTNACoZ7mnsQl8DvU/qI//7coS4So1j7nnTcgLTEtGqx4NNu14Y/BhR+bHPYNF5lf/b2rP/LmgZHDfUF3kgMHAitPI7GzHtLih+bGK6t/n1krInYpQvqlvfQ+bESdA4MGOcTrEBYCKmUYWXp+hpLhEok=,iv:ybhgYlvIRlygawBBid6puPdkqGPRi0+OWuBZY/vLWXI=,tag:7hIfETiJ288kk+r0W7clyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
