apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: sftpgo-config
    namespace: apps
stringData:
    SFTPGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:zjvqgT6VzehMjzTmfk4dvW5XzRjCjzHdV0LO0nwzDVq6LUKw677dZIOsH1E+,iv:nTM1cgpcCt79/r/66LtNSkiMiSdajh11hj+noyvHIWA=,tag:+zAOLBYtUgA06sfoZRFENA==,type:str]
    SFTPGO_ADMIN_USERNAME: ENC[AES256_GCM,data:FQQnJOM=,iv:uWgXpIFZ3XCgObjsKRIWtY7fqqEbiWB5Vp3+FKk2KK0=,tag:onoK0mZ0cNoSI/DuVVFCAw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMlZkdGRRWGxUVDE5cTJj
            bEZrMnRpM1JRNmE5VmhDdlVSOW41NnJOTnhzClE4RTdZczRYam0vQUFCVUs3d2oz
            Kzc4RzhVbktKVGZzQ0h2bk9FQmhBVEkKLS0tIDlHMjRTbDEzL2pOZ3J6ekxHang0
            OVVqaUJNTnUra25sUis4Q2VJUWZhLzQKEyPIdudDhA3O3CrvwMBKMQNiUQMzafZO
            Zkdm2X+nwlYb6kwne6nMbmJhIMcGBVednMyMyOvPvbmnH/57y60UnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMFZudTJkUEZzWDQ0K1Z0
            WkZMK1dUNGREZ0JzRDNjSkQxdnFoamNmNkRJCkhUcVVlanEvMmE4RnYwWi90akxk
            c2Q1dTJmQVdXMXczemhJODJ2WkhrVU0KLS0tIGN1b2ZNaDRSdWkzckhjVXRJUFFY
            d1dlS1FqMFp5UFhFd0Y2RlhiWThwNm8KhPLBCzfZOcOuDPXOV3cem+SdV7zpSXoD
            P7jKlbm+/NEeVvxMzmxhCR8ojhcxI+e5+bxPGD0gTmlfjnFrnbA4FA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQm4vOXltbjJBNStqU3dJ
            REdYQlZNL3grS3NmQUJWa29maTQ1MVFhUkRJCmROYTNXOEhPcXpCbm5saUVEMXRC
            WFZhZThJVWVGRSs2Q2djQ2xzMG4wUHMKLS0tIEppbTZWWTlCaGNnZGxjc3RUMFRx
            Qm56SDFsVjhUZnZXVWV5d0xGaStDZGMK3uRqreiiiJQdmaaGxY1f78rFvqrk43dO
            AbJ7tOq5Ilqys8yMuCDL4X3sCO+sxIxO/F5suI6gNl5LMrcd5k9Caw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T21:48:57Z"
    mac: ENC[AES256_GCM,data:zYLDqyRg6oRIutZjKkXmB+4rInqCBAY5l6WYeQYAMDIngkc4CSWN3Yv6ETAQpd408rlYlf2QNUPBc9hjbGxJo8s0te7PxqeFw/9UWmMUqTbuqTAkOwL7TVF/YpC2B04mBtOE13DE/vYGkPSax6rjGZztjtxpD4L9A8T/UCK/oqo=,iv:yzHaCVAzNfZd9os9K9C6UzJXZcqmLmTzbvPuySIG+js=,tag:8gVHwRvdTNnwCJWnEsTs0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
