apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: sftpgo-config
    namespace: apps
stringData:
    SFTPGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:/vqlI7hNQCZD5QnjxFah+dQxSL0mXG23X6r/FwyeIORtrYyJ4Fl9uVoeU7yZ,iv:xa38/ELJ7r8C/cEleqKp67TM9Bcxs5+LZWi7w+Hzfsg=,tag:1P436/x/8cVXxDeoPqc66w==,type:str]
    SFTPGO_ADMIN_USERNAME: ENC[AES256_GCM,data:O7eKKuQ=,iv:l4SM1q799oFnveoXtVC1swutp/TnVKKNZ1L2UlZbCw0=,tag:eNMaMwIMyUz2rdykGW0arQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK0pjVjl3VHZQSi9FeFRM
            ZzhrL0lTZm5PaTBQalIzVVNheHRucFMrK1djCnA3M1Y5THZZWFV3Sk9yTm5GRTdh
            V08rZjF2NzNVVGxyeHE5eisxbCtIc00KLS0tIE0zU1dua1FrSVp4R2s1WVNGZ2Er
            bWhVOU80bXBNT283QTRjR1cwRy9hN1kKU1IDR0W/R5buer8DBagop3srT5mnyM6z
            BMxhb4xy6c7HkRvShw5yf6IPKYr2EPMYeoCYul1CU9rvSUbH9WnfqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWWtHOFp6VUI0ZmkrWnI5
            K2h2ek1EV1lvUlUxZ0FRV1JlZEpqNDBsenljCnVnam1mMzlrY3ZqRzFRZWZ3Q1lt
            TWd0Qyt1Ym9rbzhINE02eHBGS05NNzAKLS0tIEJvUmxZY3FzL1lLL3E0T3ZwSzJV
            LzJFcGFRQVA3SGVRWC84c3JtWkt0RUkKgWkAOYQouOiIa7Zdk0+IcpyK9MR0CkGp
            qB23zluIbD7KGbt8X2CHGrNmQtrjrObbm/rKbDgYid6wXNovE7efJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3U25wOC92SjdsNGhvRDhL
            MC9KbVZzRVRMYnozcFBZSmd1b1ROSVZMcjNnCnZGNmlSYUNrZ1VLQmFCcTNxbjVR
            am9pZjlVU1UrSDNaUzFLWFJuMW90V0UKLS0tIEdlVlVYdmdUVEN0dHZ1TURraDBx
            MURONlpycFloLyttVWxzQnNwUVNBcWcKEmivRrDwsiHm05pVoW2+fcuWtkIg/Byt
            nOJD+BX47voRARbYOAoWyvpUwEUCWL+SjASdvTGbV9NZRU/srDE6lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T16:27:18Z"
    mac: ENC[AES256_GCM,data:3vmn8nnnOzEo/ilCtirzV8nzWZMDOoBScYVImyybrbBjSIoqsZyqPt4BbVllW/zgsHnPpaDGVRFfLatodWuFGImTQqrF6TEZgVNJsBTq+yj0Dw++wMZUGFDSC1JjX+pw2GZL+ad8zYwrmMT/dtO/bsNnQahZzEjAYXVEw00zS5k=,iv:NMHnG4c21xkRh/fdOMdqZUVTdP5lp7O8QhE1SUnNsSM=,tag:BALZoeSbNy/0QRdfHlLKlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
