apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: shared-subfolders-proton-sync-config
    namespace: apps
stringData:
    KEYRING_PASSWORD: ENC[AES256_GCM,data:XEcs2wpqpW8jo2inNqulbz/rLe3JbZR8Ig/1zXVu8ZvyIFoFQUpymPPGRzs=,iv:XXJKkhezBM8D7my8NfJiZpQfATXYHLlrDYx+8gva0YI=,tag:/a0xsJlA5l099mInDV3VHQ==,type:str]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:LsVp2nHcLiK8JqWmr5qJ2D4=,iv:8V3qRrkN5eCbL8qVH73ZgFSsJZ8U6+vDyq8E49RHn1g=,tag:KRPkuMPFAKCw9fNGaiZupw==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cxA/XFmtXoUBfC6gwdJE9TVci+ic/fZxXTl1cPBhQbMqDkR017AF8eQ3mi37GfsJY6SBIUKr5jAqFvAR2HduSw==,iv:uFtb07Y2yzNV3Xu7PvR0+xmScRdG503UXu7XgW2xON4=,tag:Xlv5w4RRK/vnG4OKSBjZlQ==,type:str]
    PROTON_PASSWORD: ENC[AES256_GCM,data:BVZLZe5nalmjK2G22x/kNQ==,iv:pVenW6gVYCk5qWow02r2R5HrJXW66uLYBpXzwmW1mm4=,tag:wpChCHh54+Up6jnrJxGVwQ==,type:str]
    PROTON_USERNAME: ENC[AES256_GCM,data:GH6cBubL/Nk1vtx6vj5VqG9D,iv:5c/NlvXZs9KaMdOa3uwTnW58rcOIDDmUk+nUHq6+W9g=,tag:4GEwpQjZzVzGhtzUTgqSJw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bWZWaGFueUFZN3FrNzh4
            Z2VoNzJrUkEyS3FGRCtNUHZwODY1V1Bnc0F3CkQ4bTdMQTZDZ0JlY3FaRk1XT0M0
            cEdna0tXLzQzeGw0VW5WY1V0QWtiRGcKLS0tIDJBbkdIcitsc1NXdFdmUWI5SmhC
            OG1JaW9hbFBlTS9KckN1UnZrZWh5M2sKjj/sz1xI4kKJb08b1EXXhDfgHqr7ithI
            awQ4ZduDiuYWMUV8sdX51hG4iqwjxgPkHZ0fr7nlFMdiRcAiBVYVvA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbXFyakhTVUhYblBqR2Vs
            ZDRacG1SamdNbHRGdVNSMkFGQ09GSlFrbkQ0CnZFMlM1TXgxQjJKdHQ3Qk9uMDlO
            blRwS1JoUlpxUkNML0Z3U3pLZDdwcjAKLS0tIEd6bEV0UGdTQURZZXVFS0F3RmUw
            REdhb1NNWW5YWHgwK3Z3TktXTTRxWEEKceaCwtHNvyqOkqbRdu9SIF16vXkHhv7s
            p/iwLyX6feqgVqSixSWFjHsV3OXeK7LmE+SIPP08sBE4Qeq00UD0vA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT1Q1SHZmYmlBWldJRzlO
            RU42RTVuUTE3Mm53UERYbmIvWFVobDlHSEg4CmhndnVVZmUzc3F2TWNLSWk3R2Fx
            NWdaM0tMVXNKZFl5Z2VJeG5LQXpXRmsKLS0tIHR6b2xaVjRDdnA0T1VNV3RGN2VL
            Zks5dklCKzQzMzVadWhPSG1tWVhSZTAK92PSdIP9AfvzWx0UJqUtAbWF/fO/97SY
            kJwACpikGWeaD5ykMJmVKB3i3ttZjhIIUW8995OJ+yo4z9edOKA2rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T18:13:09Z"
    mac: ENC[AES256_GCM,data:CcsPqwsb78zKURWwi+A6rWpnXWkbc1YJbzjiapVUTOIc6vwuyUyuXYYFMDm7Vny1sJhvCSJdPL58Xn6HfhI2we7Z+xyn03arQKohmky9o5qPp/5zl9JbfdXgqL2kH8osoxqj6nWjv8bjs1/pc/o56HYHqrtt1rnSObE61715tUg=,iv:dEkTFroeURoBCB2AYoKTi7/BLfMXIlbRYCXSnsR0t3o=,tag:3B93QdmrdFr+Rldwalwilg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
