apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: shared-subfolders-proton-sync-config
    namespace: apps
stringData:
    KEYRING_PASSWORD: ENC[AES256_GCM,data:nk+tzl6X7bbCkWlX+Qr/qZXpRmEnIOylhGIckuBNdFx/rHKpz9SAa+ellWc=,iv:kuN4r83WJN8F3s68SPUrERP3FDpAI1o2UeOWALj/rAA=,tag:5n4A3DcIwdF1BFcagmqdpg==,type:str]
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:OLFp2N8sicg6qbAdNFdnLbQ=,iv:t7fy5qguBL0KJSnSETt0OPbnL0jWHQbskP921saxbks=,tag:VQfv+bn09m72cU9zCDXTrw==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:loSPkKVkd+Vgv8rRdic+cclKhlRz72LMRbQ9PRM3Bi8Ck83OB+OedpLdnmzfoyV4vxOCwzoMgcTpfn2Oq1LgIg==,iv:IuwcJV++ILYyqs4OXDMVhweFC5iXixi8HeC6N/u4oVk=,tag:SSJs9zhNzeqemWenBSeMcw==,type:str]
    PROTON_PASSWORD: ENC[AES256_GCM,data:iL8ktTC4vqonq38PGeNmKA==,iv:KBLMMThlAJPDQKvKej5QdRTehCGbuXwa+w6KuKN3n9A=,tag:U+xkU80j0QX/adFnrXdA3w==,type:str]
    PROTON_USERNAME: ENC[AES256_GCM,data:gfMv28ELRUSY0oh+y7UfL2Qi,iv:y9JcnmTJRnfMUk2W/i4W7SsgsQ9tZHU4QYj2oPNU92E=,tag:Tsm6dcvQf4av1ZEYLqJhYA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdEdwclp6QklITnlwQldi
            UVc1elQ2OVRhNXIxeTZ2c2V4c3RzL3BzOGpzCm53TlFjWHBvU1VEUWVWQzk3ekhM
            VHJHQjFTZWp0YWpnRGoxMDZ3RVFrNm8KLS0tIFM5dzZpbDNkc3I3dWFCVHNWMTV5
            Y01lQ3pZNkc2aGg0WGpKdDdwSEtKRGcKxzRt2y54qpGN0T1xCE4PMcNKexw1FK2N
            8IHd7MByJW8iQEgRQu3Ludxm9GR7ecc8ziepEe+y0Ef32AJy6hd+3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVUJ5YWpzcnloMzR6STdp
            cEVwRXNFRVlmaTR1bjZFUWFoZ0gxOVB6ekNJCjZmOHczTCs2alNGeDFxWEJ6SGdi
            Um9RcDdHcGtQWkJScElVYlAvcmlHcnMKLS0tIFdiOFVCTmljTm5YQmtSYTMvRlZw
            SGROaU8xc2JyWnVEYzF3NnBNenVrQmcKZS9uQzWmXcghXYmfNueSde3APqld70fS
            tyRTT4UxvoWtbIYET4BlRg+EAmCik5jGZyNI4bw4EMl0/eNHP3tOLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSWpnUXVhellQTHdJVkdq
            dG1VRVZ5QkJlaWZ2TmJSa1pwUEdqWnBYN0JZCi9Cb0lrbURQWEludmtmYUZFQ1do
            NlkwaXlWNGVRV3FPR1NuYkJUTHFMaTQKLS0tIHlEdzZCREs2bElZbFBYRWVpOVVa
            WnR0TG1DamRGNWR2aFlpbEhBcVZWNTAKY6S5pzoF5JLc4qnrTqtViN1pBPIz0NhD
            7sNGZWypdQWB5cxM1NSIB6ijx65ULrZA43mcRxcTgaXjibVqkCdSdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T01:51:53Z"
    mac: ENC[AES256_GCM,data:NsK7cF9FknfvWdAvMll2bH0jr7bBNYzBdIBGIeqSItZFZWP7+sayDpGGURBJZIB7G2oi1IbvNRZ0TfXd5dosAlEl9krgTba+xLAbCDwq2vi+6ozfSxveXUomAWBiuwixhaKi5xw7Z3yf197Ao8Dh6KWLKTMsrqsFplvbv8nekPM=,iv:QnIyzU8OY8b/Jn3btT4lgdr4Elgo7EFn2SSetNG0JL4=,tag:OsV/fGFbJnQO0UM4nl5Hbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
