apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:ZJ+fXORi+4hdb4nhk7Lxk4qa6WjeV3i1NI+QSxVV,iv:islMYa18LHwZm7XkF4Bs91EZ5avh+MUpPMz/jTV84mo=,tag:vDLBXKgR9mZ47O7j35E/Bg==,type:str]
    IMGPROXY_KEY: ENC[AES256_GCM,data:ISOf3woh69byTe+RdHgp5kA17Yvi2xEDdkLoTrRsxzBhjhpT+fKpIY2iASfRIqYE1TaHuD/ybHaTZH9mywY3yIRIPKPqMr3dCsz6Bftt9xsgmID4hh+tpQ==,iv:riW8yStDr16/NiNoAthnzYExRgMzKZ2IfbGPoYqQxXk=,tag:H8kgspp99FMRmi2L70Lrog==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:tM1VreF/StW49o8VZz3FLDSzJyAL4RERRoDl8Me9F1TOGfxOg9ElYkKLZU6+A3ud3XfyVAuLLl1WUt0QrQ5ZoNPdMWq69rlqmfn/gsc82mYziOb71jEfow==,iv:tAp9ptN5/toe8wlZ8vLELCyWeoku4BNrISAwovQj3Ho=,tag:0GR+OKmEn/HUp/5apvgoTQ==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:n5hAgOwpVwZUZcJO0sPaXcJ5smcYwOsAMFkCBEn2hdLoYPbHZCkwDYCo+oJVCt2Cf5UEwxzsqXft1weTf3HN9TywU0LDRUtweg==,iv:hCxJoBNJ9GAGEWOHD1TIBlZMVx8cvlfQR4lhHSH/dco=,tag:C/N6WPT8fwn/9apFkakJCw==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:UdAmpvUdrGbHtoIjc++b0Y3f0xi23eqYdE0f6pRA9QyV1IcsA2lnN2Q9WTKm,iv:kTHerKJ6JLiHVz47LQW6yQ0wdDnMp/59B2dArJ5XzYM=,tag:4jLJ/3pCQJF0bTb80UepLw==,type:str]
    LLM_FALLBACK_API_KEY: ENC[AES256_GCM,data:BagJfoN/vWesiZ8/e8r4t2cQ6ppAgMazsITjOkF5OxjINIxA3pVv3jMbdhKuNH2ZG6pcyaboXFfsoyQROQKITjvCNIIRgXE5fQ==,iv:29LEmbgPoRez6h5zHoCW/Y9E0R4Vo2lfMi7wNXbrits=,tag:v54jpMDAPHd7XPjPsytJjQ==,type:str]
    LLM_FALLBACK_BASE_URL: ENC[AES256_GCM,data:EPcmVhzfEflkzxekUn0Tg44ijgNkV0951yRfHCqBDqAtAokkEuF0iilfb38Z,iv:t7T+Y13olIcOKffusTKJ5I/s8WCxZn011RbgyZsfQSI=,tag:WmpRYxQgNJbdMtd7eI77yQ==,type:str]
    LLM_FALLBACK_MODEL: ENC[AES256_GCM,data:njF4llGHTMxPNeR2RZrS4GalFaJk3IA2duT+5YyNb9IW,iv:+OSQnyE8zPzIwiXnPgMln7MozJ3PhCHLLCA1jj77t7Y=,tag:EOnZ4vtSZv/wgJUh6I8q1A==,type:str]
    LLM_MAX_RETRIES: ENC[AES256_GCM,data:Ig==,iv:fqXbws5OgzTCNW2A3gV9liu2G/VZfbF3AJj4QZVt4t4=,tag:1QNTpw4R0Yga0qfPN7zyuA==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:l1s16s+rnhz9XdK0W7H3P8uEyVcbGx/nj82utz4bxU0b2NJRG+U=,iv:4Dvospinsm2ptfF4Ojf+wHLW+QJdL3Drkz7k/k2tTaU=,tag:YHLyZtDLWaCVpOyii+sZoA==,type:str]
    LLM_PROVIDER: ENC[AES256_GCM,data:FYDTDUQ68UE8PA==,iv:UXcu6+aPCA8919fZF0W91KTkVMb0IR4gx/uKf5BR+pQ=,tag:EoNy4YsrT1EFBr5jv+GGDQ==,type:str]
    LLM_TIMEOUT_SECONDS: ENC[AES256_GCM,data:30li,iv:AkTpeEgjvn4hh5IYDLyvpZ0dNtv/usNZz3CM3HqZJ44=,tag:geA3Gz7i1NDoX2oCSNiDBw==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:4zJvR/s=,iv:0iMpMXVxna+rO4eL4BoU6/JBmOZXcf73LySQKRYOucM=,tag:33UPNSavrOYut/NdYGEbhA==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:UV/p++Iq+pMHbg==,iv:rzVeDtZOnJErzSOVXuFh66knkowWyTzI5GbjtcSXGZ4=,tag:8ycct3mLt5qusSO6z19Y4w==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:8gUkVw==,iv:oLnXNqrJwUlaN+n4PXp2NbGIc0R5qo67mkeE5BPE8Yw=,tag:mzd8AKR/VJF8DgK1swu+sQ==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:nP843qdqfpkxGA==,iv:s/la2ENKOo/1yN/g3D8Wwli54BtZfIKZdxfM36jAZCE=,tag:zGJnpQGDzF0e0mpCntkeLA==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:JAFjTboug8zN82T/dpJ97bY+u4874mIW+aME+blykQfNbIm+rd20h1ytQB61l9cUBw9AXWVroloXavYyIqWjMQ8=,iv:EJIYbLNUD/1MgSPYfamMh5Xuk4s5XL80lkhwVdLRze4=,tag:kvXuStZL0hOpokXk+dH3tQ==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:8w60CKrT3WUu3sYw57aAA++X1vDxKNZNHVZIaZPW8V3W,iv:KwN40kfqku/iNxSCxC7Qnj02uls+t2nbTimIbHNAsNA=,tag:VMlz+ZFh4D4OR6ukvdJ1Mg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:2S4meVb6KFUN8YuXPlDtIWDnVUVear8zhOrynjl3Djb+8tRxSvOQUMJDhH49ZnfMvEphCkTymOd+ILhGV28NbcsA0rpdvKxJMARkbppGg0IM2aOY94GzNYe6YChqebPrgDzeKPGlXpKm3o6Jy0RHQmEqChhV0l+exojxcOn7xFo=,iv:qHSici/iDYEp43P1w9PQcjlW/fDFokQaNXJpIwImi24=,tag:Nju30jP73uBXGYw1rQtDyg==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:oYff0H0pdbkS01SeeJdIow==,iv:/JsprPyM4VuhQN+xsVqwrs2buVN416Ce2i4NWCeu0fw=,tag:rNJOylnB3dM8RBK3LPW8Lg==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:GN68M4PSGbEcXooYbSAwpNU31Q==,iv:LPI8PYYrcALo0HjyOgWtrQnxT/iUiXztNVZvclc8mgQ=,tag:ze9KDlmH4i+03rBad+mWIA==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:tCSMcN2cXpADQCVdqGpUUMErErtd5C7F7PyMk20MIdshLEaRqD0IMk8=,iv:ymlfabq1He5WLLUIraYBeZ7Rqv94SRdm85YnPwMLA/g=,tag:t+f00aNWdHdKZc8Uf+XyTg==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:270Hql6n3tNYKKR4KAHSJTPp,iv:X0tPOcfZysz8ZUkEn+5ykC8EOxIoWabUoHDMVw7WHro=,tag:0hXuJesbQYR8tIY0DGCdYg==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:O1bbchTHlisrSUXC6xzucA/JLhHsV69XnaCqIamsgD02iiLa8FzGu9M=,iv:379wMI8paCGjUG/u8k40yKxC2hG569uKCykTUfg3qc0=,tag:UmSFmlt68I7mpoaD+GKRkQ==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:ZvVhT/GLf0QETTN+yUI/OkUM,iv:iimHOR/BueYjdJcANMNedwL6TA5Cs0TKWsaQz8gEaDo=,tag:3VgZvfu4JrPONfZVOnv9eg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbWhHS2UxQzE5RVRsU3dC
            dmpZenRpckViUFQrdGNhK0hUNEV4TUVjYVVFCkQ3M0Z4aTQ5Z0gycmY0a1lvVVVD
            Q2JNVE9BVkVyY0NRV05RZldpQjJ3NncKLS0tIHlMcFlhNUgwRFhzZEtNZzZNa09J
            dFpUUGlLZHI1WVdONUdJalZjc3lUS1EKETifpgRIJrp3mTMcIMYPtngbBhUu1U9H
            IybDeY0B99DofWWpGjKFl6oC/agrZ8DT5CyVizSpHZej3T8/NLgy3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaWYxZlZBTmVLNjBucDcy
            Q1pORDBscWRXSEg2cm5LQkhkWDBkcUM0a1FrCmVrOXhzUTBBNEhWcWxjRGVXRTFS
            bDNDalVmNjNDeTZNcGhHUkFSNlBINkUKLS0tIE8rWkpwTHE0akFhME95Mmk2aUdD
            ajJPZDFRSGsxSjFsUnk4NWFBc2EyQjAKlKFD+ZGp4fLGr2kq4Gp9bAhAnDP+kZjG
            aKi2R0lwlWfwG63S7IgGTC8Lc8CE9If/CeNVO8ndKziD9K/FXsN40w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMysrRlhyQUNFN3BpOURv
            VENtTWkzcDhPdFJiMHVUajNnaFpVck1GUnpNCkppMi9jbGlnenQ5a1dpcytYYXFH
            TU1OZnZ5UXp5QU5LMytSd0dBeUQrQW8KLS0tIGxzai9adlhzUW9GMlNTbWdHb1Uz
            OWdrdWJRd3VhY3NKUUMxdElKckw2S0EKXmZRK4IIefLH6smGRsTC17vSDPtUv3xP
            gqv2XbN39ByvvcyFRvtnm9YL1rOlRBZ0Wr8Porb2tqnJ2It45AMnOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T14:05:53Z"
    mac: ENC[AES256_GCM,data:vor9aXkL6Qgdw9yQ1DOBAaCcalsDe1xPWieHniAtT/52drMkydahqEBtSnWrY0zRfjUxGPuIyVia4SdfznY5GQyOFKWM4MCPA91R0uHaubPVUmW8OAkgvJ4Ar43QVbCLZvDeQY7U767QGDkHfXF0JQOSEX1QYU9e91Khl9ZaGCE=,iv:nb1Jmfb6Iro97+FVZKEvVEh0oMV9ZechRPqaK+y12VA=,tag:GjM+2j9K1WDNFtAFRBjoMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
