apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:px0MRShfeuSIwGzs17oDpYzZFrGh3zn1cQh/HJ+O,iv:Tw5QdsOGFNcur344FUS0K8jH3Zh+kBpOpGXavUu0ot0=,tag:kNZuGVsdkmm1DbpJIgn5nA==,type:str]
    IMGPROXY_KEY: ENC[AES256_GCM,data:ZQ3u6lrVfo3LKcyIl0mYESXRP2q3uhk4pa06NaQCVlDeJ4sVV3BkN1btki7uL+TnTQgYNRzMFrKNNE9FS4Yd7XpFrx8phBbkGL1qa0Md+PA/CvkbIzmwRg==,iv:83+UuLqLX/QpnmBaOzUEk97kndns75ZYOpNt2zlrt7g=,tag:YlXIAJ2Fw9FqWTSTgN1lWQ==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:cj2MH3xJ5SB6Sd5J5vyPYZIzYLIcZq3EqdeBBvIzAw2s1AHmDW238H73FNV3/8sMRbaFkz6f3GJMGTeZUUGd1JpXQn5aTFvoCWJDgC5gheqNAG7vBxva4g==,iv:0XSt5sKbHiLTG0MrBQW5it6kk3Nv6Vy+Qce+xUsCEN0=,tag:13Jiiz/WYlcvNfHfd25pIg==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:fwEY65c=,iv:Fs0mSdBo2FNICAaxvAS38jGh6kjdHEkmyXSXNeit5aE=,tag:bTaYO5OtOQ0OWWOY43kgYQ==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:q7i1PQ/4abYjMQ==,iv:1lKcB28Ox6yWbm3Uv8fWQe+DEBW8hmxsVpjYTXsY8tQ=,tag:ZXV7e6HvPAqRb42EvzHmAw==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:M8wJ3g==,iv:2cJGeUEdYyuEmnVBSxAm9ypTFQ0ddmqJiJAkh3CTmXA=,tag:E7xoyOtSpIQIFOGxhvm6Pg==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:KHh/AfWAe/aDrw==,iv:xVo4AbS8zzTOTGoeOL68oOMWBDrpXLMVyBZwuEqYtuA=,tag:6cifT8TLk/wNIxNXEtYYLg==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:4HYx0F5Vj/JTwYoLuM9uRFTchHPKfDAPxqn4lWatS+w57Orf52Rsztv1Bq99m8HPh1e4vklEGG14lVuz3i+BLlo=,iv:RAAjUTt7MRB9WIPcsy1hfbh3DAVnX2g4xw1NfXRPTgg=,tag:79Jw8+Tq7qkrjdqjbM0izw==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:E3x4WouwCEwHdJIQUrOqcFfoKaOl8+BsYPvcRcCsSeGv,iv:v7xWoIUyU/HDKelo71neHK9mwI7sVykgXDMsUKhcqGk=,tag:tifDl+pGyBiwonhBuB0RXg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:cX4lpfT1t2HHT4ooCuZ4ksiu7m0hPcer99ph759omsmptiaPI3lzEvi204Vs2G2ISVHz9WHJvH6p850pkYDXaE1DQQXqYBazufZPSCYtaUhJIUQe/3CO5Q3HyR5q+LUzh5b/Q2A4BhDavGBbhLYGTX9E+E6qqX1WQt1YN9+xxD8=,iv:4c84CmNAK+uY1EPMzoSQkhyty92FSg7DsvMFVTjRqEw=,tag:asImfokrCIBQYfRj9CivLw==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:0aPWGj/vjNnLAU7T0YqJfw==,iv:yTUrHhayAhKv9GpDJXQVvVGc8VmsNp7ZapCTD5Ly3ic=,tag:81MRcK4VoctGr82KFo/urw==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:xlZgu0ouXV8ayBuri6lEpDlnCQ==,iv:qrGW1jj5NqxVaxW8G1J+sQzZ3BFaq0vou/O64UEPjhg=,tag:0isUT8bb+Es8+TX0ufp9kQ==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:mXD2LTkkpJbArwNZXRpkZtgzTPuoBb21IZFbn6mkZQA4MYhDRmNKYnk=,iv:RyxVyZY/EVFRHLVZ9HjYc4XgdCZOe2W8g1065FwHTX8=,tag:lb/qAMN1Ulp00vVKjXCJwA==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:kBF91GaBDbwS45Fps57tnZEW,iv:WDBURn3LrC+DpNb+hlpfp45cm18aeCcJouX4FEVQYGk=,tag:Ey6ddu7Kwl+/H2lSZ+7XSQ==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:lvMhIrNa/BzRh0DVaDWNthvWerRYYRonctfiUPM+ED6GqqtpvYwrc4E=,iv:Y2mmUvSAZyXguLmSAWcYniuvYM4zL89jTt75cP9hp4k=,tag:DhJIE4Hpn02NP5hiO+ZblA==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:hHPsAF9eMiXza6e8UHyK4lCA,iv:wEIE13CpEvjgklvoKl12wEk5HdoYA0PneuM1x5KvL8Q=,tag:mVZwmNgRzZomwl4AFOzVKQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTXVlOTNjeWZQWHRKQnhN
            eksvNW1nWk4vTTRLOTJhNTBEY0hNc3lPaFdrCkJXV2Riam0wS2VjVXBhdFh4S1o5
            V2Q5ZUNBanJlWUhBd29HeGZhKzVDNm8KLS0tIFZ1MUhYbnMwN1g0bWZQYXZTdXBY
            aEtsZ0FyUUN2cFBXa2ZzOGpMT0k0QTQKcHVW3GsJ/X6wHShoBHGYX+VEDZLtXFjO
            rJ3K7CYPbjKfovhv2FQoElyOFH2r3NW4Z37EghlBWMi6Q+A7Te/Y7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eVBGNVZCQm82ZXduTGkv
            Ym9Pcml2QUw2a3d4aUJ2aUlYZFNXMzQ4TVdvCi9LU0lTeFFLWTByMnRSRCswaTFY
            QndTZUsxMmduN2VMcWY2K1hHa213bTgKLS0tIEZ6M3pyank3ZXhnNHY2aU9rdURG
            TFFRTFRGNzhpTUZ5MlJWZXg5STFpd1kKQOUamOC4NsSh7VrHZdhJIFvLSoYTk9SR
            GZA6JQMMA/YuqgvY0qxtvIK1IYGMWXqdvGp7GhrPd4NehoNW9D4sHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRUFRUjdDOU1UNWwzMW9Q
            REQ5YmRYYUdVMXVlYjVCUTBldlhiNVh1Tm1ZCm1wb1V5MjlmODd4WEFEZlROWnhs
            MS82WVRXN1laajBVM2l5b2cvbENkaTQKLS0tIEo0ODZJSzNhazNkSHgrZy9MZ1NN
            V05OK1FmbFhzZ0R3bVhyMWZjTzUzZTQKQN2T5rAhbag2N6+vqmwvUYu04woM/NvP
            r9oWPXcwZV/YcQqTyFs5jLw/dAckUTKtCYiSWd6Wr8lXHGlby7RQOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T00:37:33Z"
    mac: ENC[AES256_GCM,data:b2wHc+SinEOch8PXDhGe+MJ/NQHDitDR/3x3y8R8oL8GPiaTVRevteXsrSU1yuFk7G29dr/zmyQPlP+NWsqoKQPP1Xbm3Cg2GlZwkYlVarZ5BnzyNTKV4H6JjmFpr5kVQji45AklqtR4mmFIzGSa5C07do2/LW29CVVL11yRwb0=,iv:ar+qHkEUhHdx3G6WVV1wuCPBLbx9tpwB3qDqkQr4i3M=,tag:jCHOXNe+JZTCP0XdAbAqvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
