apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    LOG_LEVEL: ENC[AES256_GCM,data:xu48d38=,iv:MKFLkpxtemZ+sufwmGDF64MjnDMr0ZFAKg4mmzgs2iw=,tag:xEjWeaeBHeEbh7r1Z/IcJA==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:Qnw09HLUGJrVKw==,iv:UpNYKRyBuRWTn9wyMZuKGPlWxkQkEmwUOIAqNaEt5UE=,tag:bR9qKsxcIYkAyQNIFMLRQw==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:fh8mfw==,iv:bgLeeOhE2EeDkd2iwbWrjpGSBN2HDogncxtBhwv0pZM=,tag:bVE9jiHp7Hna3KFiovIqpw==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:LpBO7gr2l3h+Bg==,iv:/PvseHGYwwXjj4WhoMROQ+0KcR6QTsbgxc12IuuI2X0=,tag:KZQp5LVpwXgM6GXesl9uvQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:cXTXXqjiZxdjAMMZZLYuXm472lREROvylJoFzv91Q+MDIc60kWDLUtWPAJH/UNbrNDIHYM/Ga/kYfxTjdt6a9DY=,iv:HTL1NibR70Hy132mbmsGsd3zxWOXh+uJYyESiXW8UVI=,tag:xwFk607QfkfeCNsXp9cQtA==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:US3+eW5ejHvumJBt4XXqwQDSkWLAjiVLaY7KHUNRA8G0,iv:KnXRvcbridjYmNrbaFJysAUEnSCju+EGgerJg4wjjw8=,tag:zF4eMxRuK1t/+IdXoiPpmw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:p3z9lvpqxJaftEBVaqx15vSCe8EguA6zb9Enf57REfYn0iRXTts70bXy1aIuE07LZ0FFwCt1yJVt4clJYWRgpozf/K8FPuoiS/JSdnS54M/9l2Nnaut8KkNBC5nMgsrREtvIKB0vMSLW0TXOyJZ2xFVaqDjH+6NlIvaw/hMesqM=,iv:qNX5ToLgl3bngyvi4+PybQX37dAzPpmOWO5aRMohBpY=,tag:uvSjNZUkhl0nKO/LnmvDEA==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:xCIwnv25ayGs4ycRkCVcnQ==,iv:iapZIyrRUaYzu7MQQTr4amICZzI4w6GQKlJyKzZvAx4=,tag:NpoI5BScr9rG9nzaBwMw/Q==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:wMDm+J8Rpg5MUC/wo7a+pEicdQ==,iv:OMwpoftYi9PXWtcldrVKezrAjMaeBmX+x41rD1TRoPo=,tag:x15vcjJ7hIHUUCcCFZMgJw==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:tPdlniiW+TQr36tTSMDvJWlQcLXmKMYrjY5JGdYfngRagFaLkgCgsTU=,iv:jMwzH6bVBNYh1jVs7DWKtXKlxNb/Zz+DiyAWko+cxZw=,tag:3F7Qle60qSW0elWv2VlVYQ==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:qC3VMYEdOTeo1lGLa4zdXr08,iv:SXDEOdsI6T0RvJPl+gn0oI64/DrxmLYaZrHGGEfK4jo=,tag:NxGXMxRf/mS6vNjxXvOH5A==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:tcoMZnLKd9zh43t5EZz7AtLpmKfEaVasxsgOa+2Ge43nhUc+vbya1w4=,iv:Znw2Zn+E+41tIjCvI3j8kyHEp2io34w7ophYtXgncN8=,tag:Ko3FynFFS6LfkbMYjy2KXQ==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:bc1kUYKV77+2QYjtbAPSsC/x,iv:3fJOYk9x/VtJBiAEcWkhUg2YhM2io3S+zJtsiCO8evw=,tag:X+j+Zm7k07kDVwa+0lN8Xw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NUhxVFdmSWZJQTBWSFpS
            R0RmZko2Y0JMM3ozNkJ5OC9PRit4OFFXakNFCmdXSGYxWHpla1JvRWp5aEJTSEM5
            a2N6VEJrOFZ0WEdZVHV1MXhRWUx3bVkKLS0tIEkxT2VUdk9uam9rMzFsVmZ3Qm9n
            eWdVVDlkVUFEQUxjYW85aUpFWFE0THcKY12EDdoBr2v8pYT5yyu5xvBSUbSbmp/T
            eRilefn/awU162EkJzox9jXSTN492T7PJUO6xkKMA5F3scbo34Gw9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZitUdm4zL2NKT1ZnUlNr
            UXArd3J0emdwa1pRRDNkUEZhMmVOaHl2cmh3CkRIckp1cERHZFBsZXB2VHZhaTJx
            RFVyanRqNEJKWm1Vd0lRZG92L3c0cncKLS0tIHJaOWV6b2M3WlFlSkdNNkYwZXFN
            RCtRUzMwVjkxS0cvc2Y2b1JiUndDd2MKhvL0lllIIYTxhBnRkNap5XVfIdCWcQt/
            lBg9InrdD/DBlKUyUJINW5e2Z0QPmwv10gP2w34n9Ua0f55DdMmKdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSTAzT2cxV3VNdXpKYmRa
            akx3TGF6VzBDaE16U2oyWUJWS2l4Z244YWpFClZZSnlDQldBK1phR1hjN0dxQ1Vj
            V1FSbGNYYWNUbC9oMFZ3NHo5Uk9ZU2sKLS0tIEhlb1NIRVdzRE1GekJITGVVbnFY
            a1JycWdYN3hNQXhuNVAxSzNXTmNzeUEKG/EijTu2Q78CevvnORU6IAOI0rFGPx7+
            8UO3qVeTEaxYXR4l+95OkyVa5wYOMzsT3DkEKg1+q3Srto83nOajUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T00:56:54Z"
    mac: ENC[AES256_GCM,data:nSafRmz44Q3Slhd1IKx0b4bzRWHZZOW/7G94fRsEW9THSHzCMLNsgqbBraFKE6eyAJhKRUZcXVDYmaxfAwR+o0p9wr60khHzs8Okbc4StbVvBJKxmMQLXBkmAqB+/aubrOwsuH7VDnodw5ZBppUV4nUNz7MeAP/SiB9N9ifNyTM=,iv:97P7F/TXyfAz+Us0VIv1TUiWmG4koePJK8+myZ50U14=,tag:jMqvN4QxSArbSfdZA0hnEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
