apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    LOG_LEVEL: ENC[AES256_GCM,data:qzJp8aA=,iv:nVkoKxMn6Ag1VWhAu6V8ME25adlMfiMZWQnGXWg8Pzs=,tag:LHD07z96uWtOljJNC4vpiA==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:pOUhY7GQ+Ejy9w==,iv:pgQG/WduK3ojOR54KHfpoLGns8WDwgRE0hAiQSyTBLc=,tag:Epi2scv48kIiznlZwV/Adg==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:ByjeXQ==,iv:Shw9TDqba7MexCSS32nQR8uaf60eHAIJ5zLuCMkOuvQ=,tag:x5AonOCCDrkbedeoPumVHg==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:qKAOROaYIyxhnw==,iv:9n+blWbl4m44VSg4qSQlNUv6jesz0He4M9Ej5i5hG00=,tag:dzl2xV6NnEYt9U6/n4R15g==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:ePKae0MmY049iaz/gl84td73IztflK+mkR8OVMKZg3LWV+3Vqrole1RQHiqGTlFtDYO2+LoQvM7/n47z7fx/pvE=,iv:u8KLlv3lL0TIUP/AtrGjCND4nvUmJi8Un3A5GPHw2Bo=,tag:cqdMYZHZbUbe4AQLBHSgYg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:op1WGThDuQyMgA+apGKo9Xn363X99+e/U/oiWoCfHku/8JZBeZkPa711szIkfOXnleKgEsNqGA8Vuj7anXOXdjB5Ehwy1YV74OWDM8NufJuWBscIpnIpb5ZSRm6IW+i6pzak0kVH2vZ1LN0pjP/aV2AbxDpG+RpW/HaMnq++Wiw=,iv:l1+p76bXdlkuP+WG78JUHevR3pYJqfik89hnL58cIaE=,tag:pNRGD5uIU2lUkP5qcNHcOA==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:kDfU6mJgMy8LGhdBBeWguQ==,iv:yM04UTpvOBv6TJKXGRxU8U2DT4Gcbjk+7IHAkhIxEY0=,tag:upbgVpWKWI5NjDwM1fAtVQ==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:D5H9DklsxQV3aC7dxbViBLvaIA==,iv:kO90qWFE90IO+mPydGathWQ0oAMkFPIADuUmi9URulA=,tag:rSiC4OpvGabrHWgjo04crQ==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:biUOf3769BdiEZ2R6ttCPB0G6CTGr8Xz+jys2g/rI4ssp+jZiJhaMUg=,iv:rdWZ1gQY71+0GGwxnoHRL/Khy8aDLGD1dgjcCy6vK5o=,tag:LCE+eFRvjmMwyEntVOUn6g==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:Oly28MbOuayUBWyg2E6yFLCO,iv:10VB4+3iehHAquVhZGIwrnmpmuR1z70k0QaS6ejMiiM=,tag:n0UNHzmigiICR9d2x+jHeg==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:a95A4foLP0JJMT7fCLSwFHSkR96RZa5gvwH5QxZzOZRxjPw+B0KySr0=,iv:ILUW/yazqhwV9BflZPLa1pzcWd3TkwHm3ynFSuPrO+I=,tag:PeddSm2uj2s/+VmDVdBMvA==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:RHc/RWRDL9uw39N2wUbW+qLE,iv:E+U1CMR2yvpbjtggSDIG9ALrmOmwXle4jUmXSgi6ZHk=,tag:NEtxwQjZ9a9MKwaCVtQQCQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaUNxa3hEUVI3YnVMK1dC
            YTFtS3RkOE9ROWJ2R1pma2ZNSmtHMG9JUkhnCmEzWVJSRUlRWFNFd1llZmFwdFhE
            M2YrZUxPTkZKS281dEswMnhJajRFT2sKLS0tIDVnVk5tRWh0M1l1cStiM1E0a1g4
            RTlmeENpMWl0YmVEVE4xTHZQZzZpMlUKMt9Ae8FLk46atY7ped2+h5bu6IhRrZ/1
            jefwAKuz3FsZ5ebjgAvPHXlAM5A9jVB0aMcmcnmV3cF5ek08sfmqFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUGNaUTl1M0l4WHUvVmhF
            RHRMaGNCdnA5a3hXZFdxa3l0bDk3N2VNTENRCjExaFNNMTlQZW1IQ3pMTWhsSnRL
            V3pXQkdSYWdvQTJTOVZLMUoyeTF3Y3MKLS0tIFplV3d3U1Z3V0pSRXpYcWw0U3hF
            R0JPZWQ4cjE0SGlRYkN5cGFsMjN1TEkKNBRYfkqn82SmYpMNAioQWyS19j8PYzui
            /0MdgqVaQL9H7I8kMIQC1GfKIW0lEZDxiPvgL4O71AZV90l56hrdQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5allZdXV4dUNVR01MYlpE
            ck5tajdLb1Q4V0VGWlNHREkrZ01jZkNKR2pZClo0NitUaHoyRGlOSVY2MGNRTnZV
            djRHaytDR3lvd09nVFJZbnplaUdWUVEKLS0tIDdoR3ZvV1dDenhNOVNFZEVHSzZz
            MmJ0MkIyNFRPT1I2ZHkyOUkrWHU4NWMKBv1Q996BVwrWdZ5uRabIIMeUdf0f6ybe
            h4dUobo/+NPMorTk3Bs/LMfF2T8elbO8K9VL3t8FyVDod3iNK+74lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T15:46:31Z"
    mac: ENC[AES256_GCM,data:T2ixtqWrS/sqOaftPa3a29A1ybxDVR/bbqzYiFo3Z7BtwcgNvuLjkT8PNhJZlAAL62QkubqEP/l6wfQL4r4dSByHlBHXQ4GJFwXLb3pXWrupzFvTkFIT9iO1fuyRSNTdIxRhS30Z+EBdNulXt3OCNrIE+yo6k5Fde2D3JlZ3hKg=,iv:J0cNPItRuw74yQFNNtLMFo/Qhi4NYjL+6tcaLcCRuRw=,tag:E6LHqogE5+HfGGwlh2/gMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
