apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:O5lcq8t/Mai4E0PrGR968YXULa4pDQehcFOgPUOR,iv:TOS8/idXcb0j4Ag5Tk5bPAmoeZiW8SWAI0AIddklfls=,tag:a/tfY4yJYlJRLPOD9khjSw==,type:str]
    IMGPROXY_KEY: ENC[AES256_GCM,data:mYWrNBZcBF5Pvp06wD35mv74n7pjavfLfaUDt8WadwtxNXWdjdbmcj9uJgEb5eEEC/Uo6VQMpaTSe6LGX3CrkAt32xF8Fbjnk6SStDRQh/WZ8KeZmJBzng==,iv:HONuLy+/w8EadJMvr4FdkQgpNt4ESZsmOy6NraVAZl4=,tag:NvVPsFv9C58aTnCJo1lOGw==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:ArJeXqiT8lgN4m7Gm+fuMMH92afhqvqfEZiQO9fOGBb38VHjNhCQw1FOTYXg2pTSbrRljvGKKUHg9L2wj1i5CcHJPpCgO3dlxffQUaZhdyT2RTYudBMY0Q==,iv:srTW1U7ejf31lKuTY2SLHcPzXN61sg+07OoEMMNZ36A=,tag:NjbHePv6O4AsELEjA5V76g==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:1yCDyVvryTrO9qoTeJl4lx6denWIQ4asE09UP5eKIDJkMtUHmAp1s7ZNj9Mv0ea2lUwysRx1BRETXa0tg/5p22p2Kt5ItvFtng==,iv:G/R1kyfv/fRjsE/zni1lmiaqCWeSfKqmxPi17qe5oR0=,tag:udpJaLHpJw3W/q0OyaMGFQ==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:Fa8PbD5Z8+cEpXjViaMgXQ546tD2cRgfbBnRHi5RvqCGvaYtegXhHMCpSeMZ,iv:2DMgPy0AZ7zxPOi0/e0myyUWSOBE7xd7M0qQXh5OeyA=,tag:KlBJzWeai1/DsYZYCTA9+Q==,type:str]
    LLM_FALLBACK_API_KEY: ENC[AES256_GCM,data:4gHlu4VnYkc6lDxFM2oVL7JljoUvJ+HjhMAJTupjqa+2AvbxFjHEGsf0bLvaTCn+piEMB9sifdTnl4gLPisVlwoymZ31zvD/rg==,iv:X3UWrm7aFKyxZ4GYe6ov7SDoq0VJLQcVIZTUvk8VMwY=,tag:h5bbIKEZsVf3AFbWsATkKg==,type:str]
    LLM_FALLBACK_BASE_URL: ENC[AES256_GCM,data:LHfg/c7u20NoLzy0CLxlRBrHXFJl5BMv+0bwArqCgRCsF80SRwrVp4sySD50,iv:oi58OCEH5f/X9M8+O2isp3vSkPOxX2xG1M5ekMeNKig=,tag:AJIOjAdb/M1QvAEprQyGiw==,type:str]
    LLM_FALLBACK_MODEL: ENC[AES256_GCM,data:aYXIGCTN7u1cIErphjzNya8OlURP+SvyeYjB95JVrZbx,iv:jJannUi5miUb6qZYNehKuDC/EKSwkHpYL9/6wqZUTCU=,tag:MXB/jujboLsY1Mp3GP4w8Q==,type:str]
    LLM_MAX_RETRIES: ENC[AES256_GCM,data:gQ==,iv:H/9kEeeZV5VZPvHmdJBmAa6+Y6XwphKj1Jt8tK57iwk=,tag:4NcJZILYqdH/mip15CDC9Q==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:tDYauMUpjDc9lCasefrgE+M+G1LYGLLMZFW7Qj8kKISyO5bhd5M=,iv:lt/IrQO6DbaZABKDRzNPptLMY0gb+Am8pjAfLXyhuVY=,tag:p+T9pst8ZtpV+mHuQy0j7Q==,type:str]
    LLM_PROVIDER: ENC[AES256_GCM,data:6vNwjxRdDOyleA==,iv:aTVBfQTQh+Cj471ZRj8dlNU9go99nrrSlPM9/vLbwoc=,tag:m9CcSZVeIqkjv0YlA8h9AQ==,type:str]
    LLM_TIMEOUT_SECONDS: ENC[AES256_GCM,data:EUc4,iv:GQxNyVsexu0qCNn8KSOSns9VZ53g7Q98voOBH1sRYvY=,tag:kXpflyOAPQTxz5kJnWce5Q==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:pdNmCs0=,iv:8K/+9v33hOrMRPCQgP3ZQCUT7KieYb2edemizygzFas=,tag:lYOokhnciTTrQgEkqUPENg==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:D6bCBLiX8GK9iw==,iv:/HHokpJAJFTd2rWspbfC0xl5oWYecE06uO9e26oPbfM=,tag:6qpNhMmoBtVKd0X7UaFfag==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:Ouktvg==,iv:HQH4TG4T3lgNF+ii0qopRvbQlcY3tGZFSdqEunfQtxA=,tag:STRyksqQDeMkjfGs7SSE5A==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:daj5eBNivZ8DVA==,iv:5MX0v+rPQs/PACunb0QPek1+QKo/7ObMxqWnRaqEdd4=,tag:eLAQo9B2LQ0lWnFetcF4pQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:G14/KYPiJxJtkOq4hNa9lnDsWbwpM8vwbLV+RJkjneBHumNcpPwdEDhQ7vub5y2EcYyj1dSH4qyaXzR0ffxcT4U=,iv:mvbW/3LMpOVMX5B99e27LsArVkk8nwlhC0/sxetI5Mc=,tag:DdwCWn3kenyD6SUADb63ZA==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:ZRPJGf4zf/rAGjKS4Cep/bDbVAwoRyic8tCP9h537Tlk,iv:++zlctnSBQOs+isJnpkqd4BjHnk2fec3sycWFcPHBQ8=,tag:rH2NNw0BPEleF8JBONfN9Q==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:RbvJ2ZssuIKW2HZEC6hjxsDdFrqL0zb0CoRXtawIFk18rPwO4O1p2ZT9LzO72iMAZ/YHvHLjDWHITIkIA2RzAN/dRZjaKyYrg5raiRhqSjx4Z/IyFoLrnNt6p9+zVN3GXS8F0TAlhiW1ArYakg6jxqhpIBUap/mfwJAPFKAGanI=,iv:k5YGTyqPPiGNssTslSt6vDXwfQzYeUm/R2khrEtfOOo=,tag:JxHatLLlLS/qkMkD5p1sdQ==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:7eQHhs6+kaggFp+B+JpwCw==,iv:YMzubmxhmEn9pmQfYyEOEMotHw7nf1yeil12HtjL8XY=,tag:w2FLL8cj2qRLxgrVePjs+Q==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:A/HBTs+qQenYWeiqp94Oh0Qp7A==,iv:FOmPlnjmzG5wXHhqTKU5NcccCGwPrrzlhQIMqw+2dII=,tag:9G+wl/rrXiXRWmHCQW57dg==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:tLyUaE+igcEAgPMM1GVR5ygT1B0p+ZgMVKPavBIN+mSMif3HxIndt+A=,iv:zThnFkvB4CCKwrC+nxdBu4jqOGQ3Uo2XxOyCbcGXpaM=,tag:u66vkYOgSXdbcSFScUEhzg==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:u0aj4YP+JehrIm973xq9T0CO,iv:qYKZ8jpMHs265VOZxSKqQUu1rGpKisUyMoro6D0AvMw=,tag:3bidqmsg+mm//Fknw/Y6Tg==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:7IhF+uUfQIcpZlG8mE2BnwC6VkL2Bw+gMod3TwU95d3r6pZB6u8dDWM=,iv:mcaqnYRXqrKFXxJQcqf5FI7B9n3nmhSQ9nv3E6XL0Mc=,tag:IARPxDnUOcV7jGU8W/0S0A==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:Ie1m0pZq3Yue7sO8doc86H7F,iv:imyJacPlqGOYvqdKEAD2Kx/5gbgLGEpSX7ysL5zxBh4=,tag:6ToH9zfJ30Px9cGwlLAjXQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR3lUV3BNTnpCRlNlUEFL
            UzZFN3ZDaVM0N00zRTluQzY1VkxUa3ZOeGpvCmhZM0lvY2Y2Ymd0V1FjdTFHRit6
            UWZrSDZZeFNOTStoaHFQeEZrNHBXUGsKLS0tIC9sbkNrYnhsaENmdldJYnJ4d1Zy
            ck8yeDdlUkVSRlExWEs0U1BaRGE4S1EKTTq4gZZbM/NZ3CH1c4k6e4rC/6QXUzEl
            w1hZ3l+wLgMuGc3sK/PEsLy5xS+A/ETIV6t4bKtiHVg00K87oyOEMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndldZRlNEazVmbHNkMHph
            MW92WGI3dlBORG5VRXU5ajhQZEMvd29rM1FFCjZlLzBFZmpjUUp5ZWtKcS9WWEUx
            R0NHZ2piNTJLN2hHR3dHUTBXVDc3TncKLS0tIHpLN0RrL3Q2NEl1L3lIMnNQWDkw
            dm1DZ3hMQjVrcCtEaWJaditwelVoT2cKqqbOYg/gmryvHlq0548ZjBUT+5brmWho
            az6r9ls1LUZmJoSxgNFbvovsTdbbgIQuToeCXSMYj6lfH6/gxfGJ5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUVFqRXptNGZVQytZS2Vl
            T2V5eXBWcVJwdkdqaUliK1pnNGtyd2NIMmxBCisvUWRzU2hLc3poYmpOVENMVFJi
            TnMzQURwNmYydUI5NmhnQU1NWFhoNlEKLS0tIEl4QWs5M085Wm51dDJIbG9NOFBm
            c3pJWDlYU0dsYkZsZ1kzWnVjT2RnS28KpEMFtN3iZC1X/lTMtaU0WkcrJ+/ZF/eX
            ntjqdZfEi211KjwajZEjfCFub8tT/MXut0DyRrZbH7oHaOijAN0T1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T13:46:17Z"
    mac: ENC[AES256_GCM,data:ZstIVgUpVir2hjCInnofoT0abIqXRrEVPgZ4cMyZ7/IPbg5gN30Pv8BDRJ5Ry0l23VC1ZXJUTRHwU6dn1ee/cbEOnNMG+vRXjhFWUhtuqeobhJk/OlSrATCS3gsdbkfVBpyefJjjFAUPGjdqbK4+PG3WH/310dFy4YSKl1g/QG4=,iv:yrEdOqpI/jl9T8+YB/lN9fGP0QStbY/F+LvPqp2c5uU=,tag:/oXiPi2mZkpwko1dmFvTwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
