apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:UyklQzvjUakJiu0V8CtfFs3FeNHALzJoi4Ltb9ji4P+L60xP70Q1WLq+w7oGqj4=,iv:mPdC2azpLHbJImI9p8XDcRLS0V+T54rSoB3v9ogfhmo=,tag:FbHNs9KyedSv08CyDy6dbA==,type:str]
    IMGPROXY_KEY: ENC[AES256_GCM,data:MrkdV01XXmwE1O7qgDC7eZzeKdVEHIVid2MssekrXwQWWHLG89Ec1bG2G9Ih/iAdql6GxryTss0jjoETytgU7aWpU1ZnWPD6euN+Yzw5BNedb9ovOOcopA==,iv:ngHt5+Qzwn75s+bBfyWxICQy694SliQoQNZjGlXKTyg=,tag:1yoH1wzqFYHVR954ZyjQPg==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:vJ/Mqr81/riUAErm4hDeAhnaEpxodnAjSRscV5KPyndq9hBXy8TNOJFPwV7lnL+BAk/ENlOWBss92FCuxhw/YuUwYEv86VRz8lGYfIusqCbwqJz0s/+7tQ==,iv:WUQaMImHyWEX2Bp/WJKpx0xAvp6ZJg1Hlp6RhmPpUk8=,tag:ugcwXG14kx2UtMezdUpTXQ==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:m0Vuj/4=,iv:nS1khtk+zntzTRKjfWTYi9F3AbOAfcwxK2Z1+2WcLvg=,tag:HppFvvSS2vaOcPHM/FuXCw==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:8pAvUxFRhltvGQ==,iv:BAHr0Rf0n/zrNrBMAPyYwfZU8kjpLupKlSFoytldxUQ=,tag:3ULy6r4W0vcSG+wjHKeAEQ==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:unPejQ==,iv:hOJovgNh3eSLGVSpTnqJTCVJ7Pxn/r6kc4TGeJmilLA=,tag:pZZXxU7XjSj+TBgytEkX6w==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:iTFJT90PpFkXbg==,iv:2aiDybtq1XOf1klOm6Yvc+TIjvpsLMs6j7AhzgxwXXk=,tag:CynwMjCIWYPmX8PbgORyDg==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:MgEvi2mBWAcsLs80ya8U5umLNeMg6yFzmkUbXEWpE/lRaOeDwOgSlsRZpurD0eeWSpoAnrN5Vhwk79HFurXjvJw=,iv:42hxOZLI3iTcacdvFwu/ehSMzWPziCnt34PP3gjFHcs=,tag:D9EVVD2//0DWUp6zskEzbA==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:1PJDuSz3bcmYlp4OLJQONsL5USZb85vLVYBJxrifpCGc,iv:LzKQOMn5kbizSYUe15NRPGSFCr6BDytkrF9bTjYkXPs=,tag:Whb4Jg+So717zeoRosOBRg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:Pycsxniy0jgSAMAOqkvmLykZDuXvZG9vSAoVCmkYFSsKLco08vFDkArJDGeQBfgxsgOx+zXZyxUd4TwmOM8XwWFR9JUCNtsk7S3PEGQifhE8txWdsbqC3SEzQr0e7KewvfvhrE0LOHlPm5Sho0iCKLynBrTk2THkhtZC65jzXMc=,iv:DPpjdkveWP30PErJKZWxeAeXuHYDju3tTBe23brtQBQ=,tag:wIy9MZQxzSybIhvTGQZkwQ==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:8kAOaeGilMNA/PDYDfULeA==,iv:xnP1Cys+P4bGI/PQbu860bVNQusDUc3wPCtUo4GYF/g=,tag:0WuejC9RqgwOqE5kLM6p8w==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:yPiG9t01SqpsQCg54x04tW82YA==,iv:VdLHKR1eco9p16mnPyyjHJWGfEaxTqdDuaFOa3iBLpE=,tag:g2u0sX2Tk1TvYeFhrrKebg==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:6Nmp5MW4TtCtgXgOqQg5I6E+xCctwNdAJrpDg00yCimjTNlovBzV2yE=,iv:YxjnAWh4qq4Gj9WJqdBy2CKgD6pnAccgZodVanUWn0Q=,tag:MHC5zczhu7Z38Y8jRPPkWw==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:6q0uNs8UUxrkTdjQpOnvSwFT,iv:CXCGL9qtAmgouLz8Fs4toeX2odlafBbvfR4t9Cj0L5w=,tag:po74zFT0iy95xqzNM6nYHQ==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:G0+2h+OOi3j7PwBrFE5S3zDhSqssZqQBw77sgQsN8IOVz7w0vA1lCPw=,iv:EXY5RU16vM+EDPfIFbQakZ4pQba1r20unAZH3WIEAEU=,tag:P4TzIbOkSLmDqRHnubUTzg==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:klL5t5IhGmPYlTYriDid6S/8,iv:eUBHGWyYJ19uwJARpfh2lrLlRkoiKE1F4LTz3I/L4LI=,tag:+RBXLGWrh8OxyHvHGfIDbQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENUU0dnlraitqNTFhQ3Rk
            Y1hDcUs4QXp1NE10ZWFnd0NtWUV4Qkd3RUE0CnFkOEovYzVFSWEwc004WFBUbVlV
            bzZzVmJ4eUZEeEYxN0hnRGhyaHFSYU0KLS0tIDBoeUlsOStoM1FkNEFnbEZKdjg2
            R2RNMnIxbXpleEhQaHFjb21wTXc3VFkKUYNaNzzZJViOj9gOXZTLQthLQUxwB5Lg
            Q6cbwbDdWJhQKSuh1ZHGZbXJq5Xiwqg6LnG5v6jLr3p2RsoX59z9LA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWW9EZ0NqVjg5Vjk3RnJL
            a2JsTzRBcXowKzJCOXNRcHc4SzB1ZVREQTBnCjdVRExGQ295VGpROGN6R2djVmxp
            aFpoU2MxQTIzM1NpSDNPT1lReWhxRk0KLS0tIEdadnUyZDRmWHJxalNZbllJTUtt
            OTF2bHZUOVZ4K0lMYlFHWkcyMjY0aGsKHbMdj7bjGFg9s2vYbC3I6cE6dbd4UunL
            +DcWbQDAI7qFlCk6bhXHvniDiLvXz+JhEYPxGNgFRslqyvLfdoHdyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OGViVFJYZkE3YWNuRUkz
            VlZJWXZhN1UwUlpLUkdTeUhNZWNhVUVnalFRCmR5Z2pLQ2IvSTlGWitiektHZkVx
            M3h4SThJNElvekNiNlVaVUVrUVM3WEkKLS0tIGFvV1pRVUpoeWhObTMya0dreXlO
            eXhzdDV5K0N1U2MvdXZEdEUwSjhzbzQKg0ji8GffZv63qMOMkvduhnUlU1WCD4O7
            KSOJc7J0h1vO7y2Zy9iuKOpgE0fZqLsiVXcFGd9BKmkhGQ1HhPipaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T20:26:34Z"
    mac: ENC[AES256_GCM,data:5T+5mejTFCJBot2a33VWyOExLV7iW7Q5SDU+23M88OKXVzTVOrAh8BWClb9VhitThdKDhye+VgXKg67s5Hmayy+bEWgonZsc01NEfe3bh3ct6bwBpbzBR9R+S7noAnjT18qRdGMOWj2lliYbmGChbEuu9STlyxu7VU86CedeMAA=,iv:1ujGycDsxG44aBGLpUPn3LcpPv2MXCLRg858lhRfPH8=,tag:iSelw21YJNVSPZvUuLdzcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
