apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:JUqcfz9Kvs3egAPbxANAX/yNVV7qyWLXfxD1C3Oo,iv:w+WxcMZ3+JTHNfoFkVL+ZnncgXNx3lU+alsUKPL2Q3g=,tag:PFdK+pQY8fseNMaZCiUttw==,type:str]
    IMGPROXY_KEY: ENC[AES256_GCM,data:/sWp0YJaCAIaAuDbPt0Xlyyxs3WDAgt7/m5t5WKVw6lNaUIxlAgLm9g8vCApDkxPCGmn8sWufmbTkJLFSSDfQqs2hqXA+3Uo6XtFgMwAdPBvQlGLRAMwrA==,iv:a67DlyQcoS0rqmk3Et4aIe/Xuu4BH3BqjjiEN8i4pXM=,tag:xrydZKwPOpQd/lnSI8/p3w==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:SbyIa6HkCKrwC1q7iq2+l2co7VyOBwxVR7trUiMzHOJ4dDo2iqv1U7AeqieUvJEvwtAFfL2QVV3nfMzPnwWVDjS0NnAHRjD9rQlj8rfLfffn6YYq3qOaVQ==,iv:GX3/+a9Zy48xzG3r7tWW+tzcT0QyBwIznlJskXM0Xm8=,tag:PN7djz9fVdf2e0/LrX6aeQ==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:XdpMYL/pbhz+fNCwRa11+aOE96L2lW0tNP7yjW98nbPnYJJ28kT9h3/JpSEXWNBmCFTAo2lmLWXuPYa9dcGupdsEu4fjWMANgg==,iv:l/T/XG+52Bmvig4wNau48CcezdvBRJ2ZJSWh0mhtDIQ=,tag:qdxMv1UenRffCJAvd9P1fA==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:33WfpYASSxo4wmDkz9rb7mLfGvQBanuDX8C7mQpkZevJC2SWEG032J/ycklQ,iv:C2cjPeKsP2oYu0sliZ4WrJ8X3JhgB/XFlR1YKq2HK58=,tag:69pUXEoALaRqJ2lt5+l9UA==,type:str]
    LLM_FALLBACK_API_KEY: ENC[AES256_GCM,data:GlfM6hdiR6nxbubTCeYWxgzCH05def2/2q/f4/TrrVPrujt3AywD8Z+fEnkBoVxRkgsRe819xXjm7H77RceaoiBDWXcUDMHLzw==,iv:a6MiW0cQ2QBfJ7TBhqGFr5F25Y3Ia5AJy3xTwyaUhK0=,tag:b2Ne1Q8dViiwCNZ35okDbA==,type:str]
    LLM_FALLBACK_BASE_URL: ENC[AES256_GCM,data:z2Cw+1VHZOfVeclE5nimzf87m4obFXgd/I0STR/9Oo4LFjUC+3/oFXefWYax,iv:T11/hhvVaeWpyVcN1fDC7/blP5XM1zb2xyM/v9qPKuU=,tag:70iu/w1bvmmqo3JtF6kLVA==,type:str]
    LLM_FALLBACK_MODEL: ENC[AES256_GCM,data:vQETuwOIyContPGpE8IR44ZMXiDVB2m1tr3HnNCM9PtA,iv:9EtfJPAkv8sLGxgQWPPKt05Wx8a9oNtGnjHV+HWfbqk=,tag:UrFWIdq1voJwb8hOHUsb7w==,type:str]
    LLM_MAX_RETRIES: ENC[AES256_GCM,data:gw==,iv:IK4Gtgq3mwvPe9/kTR75MYaEKToN758PdhZY/mnPvE8=,tag:B2nth7z3V1Y+UEcaFw48Qw==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:RWF7jN6bsoeD6tME+jx5M1lR90h3ITAy2W7Z36pMP2/tciu4kBI=,iv:i3ntJnoeYCi6dV/m5LoWDBrjK+8IYylSubV97k5GQ+g=,tag:ZTLViQlwg7EfXQWYcosMkQ==,type:str]
    LLM_PROVIDER: ENC[AES256_GCM,data:LbFaJTRyr0gQgg==,iv:4m9vo70BRUI0f49ZNqb8nLa3WE9b5O4p6UITdeTfMQ4=,tag:BUTG4OXmtEIQTtCEKBhuSg==,type:str]
    LLM_TIMEOUT_SECONDS: ENC[AES256_GCM,data:kj+i,iv:Ofo87Ytjqn2mwqTVsNtyjmhCtcILEtxGbaevtasv+MM=,tag:9Y3nvVN4j2L2cfM9LliMRA==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:9YlFc5M=,iv:C3uX1cF59VKquoRyUPvv354pDaeL2VNAAXYvmvEjfVQ=,tag:3GK/4tN4tnsGaepXQdJNAA==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:KBqSqThRS8UkPQ==,iv:ylp9xIot4Qf9Ywp59P6WfoFYSOP3LS/kjdm+khk7oWw=,tag:Nbr907Fmf24p9wcceHecXQ==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:gzNdIA==,iv:o32HW7Gj7oRSlLx+9U2mj+nfXmlr1eeiN4571DMp6V4=,tag:jgH5lPgA4YRQafj+lcxPeA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:JauOosv+yiyC7w==,iv:27u4nfWqU1t3OnmEMmdswVxxHY6oD8jXNjTLYYzqJpw=,tag:vYcWnOH0AD0+6OM2cnvsrg==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:pQEfG3dj6DYbo3wkN3LBgEW5oJBRhe26ybpZlxoAak9xdcc3tpQL/0jDPUK+tqfhDXrdiRMvFwAVcir82Wzyju4=,iv:7m3KpNf/Xdu45e76Pb4ElHJyYZXsukqB41Lg48Dl75E=,tag:WrRyep+A/Z+wfUFrarBPRQ==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:aO/Ax1EOhuR2nSNDwkg0/tkLXwNkoSddb9CFUyfLlc5n,iv:NeRkR5Eweq1jd9089CDcne4mFEkor9GJKfiViXfcdIA=,tag:zq7qKueJygRywHr1xDA7eA==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:ayUbA4AznH4Yg076LiM4Xt0y92sRZq0GtF54NR2yLePuRQAT4/wxyV1E0OhCAc+v7QojdPhdXABIL7UfgYU+87/RgWelmvH9tiLxNqtBa54Szy5Y5jfyc/OsbZ6Y2Chq9vAqXSq5pYr02jvOXXp6MpcLMvmHqv8YXN8zNOGFOGk=,iv:YoxVnhe2WxmoszinPUHYvvT3N16QWERLvY6uIoLIj4Y=,tag:Oqrlij2TG1AI93a06wjRBw==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:wJFASFmTWmDUIvzU5oCrjg==,iv:7x3/wq8jEnBkY6GeXvPf28GURxuhNUQHmBGxwwpkWew=,tag:TbUxK4TxG49SRvo3YGXj0A==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:Aaman6VP3b1lTh/dWCdEHgEf6g==,iv:ZGnMTBbywwxPLcGI4zdXgbFiRtZY5AzbG8oeuGqwv5Y=,tag:H0iZr2VCy9FgEQMVMRN0IQ==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:uA6/s+oVdKbdpk66Zd0DBe6j4jrNC8aoG2ADldAGEZx9NmroVLJRyDI=,iv:2bqWg0qxWuOnVREzlFEJIsJlTLDGKbLA9/G0sYh0frA=,tag:+MYFrUU5RjJJX2Q9Xo2qNQ==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:76WmUYuA8R8RYQYhDzTZXA0I,iv:Q0/utKz1j+KLXWZ7tV7T/THGiYvxK/+6JpFZnC+vET0=,tag:gPE9gB/w/80BQ32pm0ounA==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:gdae8jOct7ioM3X1Fuyq3BCs0jPlZBUUTsnPw87lytcP+RuAQvNcrTk=,iv:blfws1pkS0rkS697cPhOn1ySGm5Bf91JMSvRokY/B4g=,tag:QycqK0pH0g5ytH289QRl5Q==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:UEU8w/ZJMmkjPDTm2TGOQJN7,iv:lhz4zRYxo49VoiTn/1DnuOBD8UHorl7i98pk459kqXc=,tag:2yyaBz3VltDLaI8k5xAyeQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WHN0dXArR0VWbitncXhP
            cGE3SnVtVkFWaUpnZmFFS3ZCVGV3WlhxWUV3CmNsWmhqeUpLRzQvQ0dKUEY1b2xF
            b0pLUUtBU2U3ZGlnbzc2dHdvMHhHNncKLS0tIDB2S0NPam5LdEZwQkFBT082UTVh
            cjY4eW9ON0dVc1cva3lXOGhjVXhsWU0KHQftTfy7kvOU/dwR/EmDgq3QgTsxAZoi
            q4i+7a1twkUNCMuKy2JsmHAWxmRpvzTBT4wqc+gENHs+oFR247e0tg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UC9BY1AxL0d6NWJBbVIr
            OWJxOVJIem0zSW4yTDgyQ2VYTXR2Z2FqWTNRCmhJL3NLdUhSU0R6NThXUmpkZEUr
            YWdWOE9wZXgwTThrTWsycldqMWl1WGcKLS0tIDQ4M3RTOFRtN09rU1c1V3NXajlw
            MHJXUmlqUzBHQm02RmN6ajk3WjF3VFEKrqvvlBn5lkwKRqSP4J+ymTptT4cJhkw1
            FX1MsfHe1qKg4qFJH/2DFSQjWHkrfgJkDHDkco7fN+wmtRe1pMcGuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdWVreDB6K1JjejNsb05V
            ckllQi83SUlVbjVrRitaMnJTLzFRUzkvYkNJClhyS0U1ZTdjSWREVjE5RFVzai82
            d2ozejBrVkJxaXhGc0lDQk1vZVFPak0KLS0tIFFvR2orNkptbDM5eVlLN3R5dHBk
            VlJVOFVNdDcyUHY1VzZvL0xCV2R4WlkKIsKYMUGr2NtUpLdW61kKFAEEWtY8HW9O
            nNcvUPYFATzW6qnARIJxRUF/urW9ZDTQnPMAp8HWQm7aaQseax4Jkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T01:15:24Z"
    mac: ENC[AES256_GCM,data:FgIgbIIhZN8QryY1Ni2DZFXvQ5zSl8j5kBzFzwzUdx6Df8ZH4ZyeDkVCAu1K7rFqKyi07FLaedu8x22CsIMDlMn3vFJgb+6XQZI4+xautbcYYQyjeaxLnarGjsQ1YTTYe37T1jORTl5ZE1YMbyrCBvJpLV+A3nf2nKUoCZBuvPU=,iv:nAsXQjSi0v4fXqCDQoiHJGw5IHr7yjLWH8BOtybz6qg=,tag:0KgHbQO8pjqXIrKaxok1ZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
