apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:u8OZXWqojf9GiMHWnO+5yDr8evYgwg==,iv:6nNzG+2dfM35RubJncPr5sDj1KLv9oa5MOrCo8Af5iw=,tag:PDijZ+VsNxJsIK5c96OTHA==,type:str]
    IMGPROXY_KEY: ENC[AES256_GCM,data:2HSAkgXLf6/cPEwWeMV1h/McHO6T2br7YmCZq3mZnVSRWzl8gdId2kMzEkGEZDsRcsr3C4F7k/iAVMOOkiWkp9+BJ21AJRCt+Czt/Vu6Ydh9+kCTxA+Pmg==,iv:NtVIpAenPkLug46mvr4+nU6ESbbDLnWiP4MNblJXY3A=,tag:fPzQLx2dI4MTNICwth5k2Q==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:fHOLkls7eChDKLwcmZDhnLYako85UsK/bf/59/SXgM0wjBDLlguiFM65F16xvoVEGlUMfaF0kOpcnq496FyoSqh5cZ7zL80y7x9mYOCR/mZVmP9CIjnEdQ==,iv:3ROZNfGBcL5H27xZI5vdoEmVt+to34ggL4bsqKwlbiY=,tag:GNC/Srd5N+Wr6nPHWW5zmw==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:DKfz8yw=,iv:QmLFWApXFqxqro8FkZ1fLsBADVEm3U5dYKmwSSGKKrU=,tag:f3/fwvXPS3VWUb54klSyWA==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:w+ULRz+ahA1X0Q==,iv:mJwAUVwauPpxYaNb2MBSemebOa2DcIl688HNl4v9h9g=,tag:zubMrvPmusGWJQ1WFsL1fw==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:S+Qf9g==,iv:2d+QFoDEcz1TDWQn6U0CngLn5pXZTdLJmjTAyCKXBs8=,tag:4u5/C0B0XpoCBhshjKsJpA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:tRQE877hqLbk9A==,iv:CYDZjicYk9+/SQgg2QWs8LB+6jiqBzS9yF7f+nSU3PY=,tag:zPR16+k935phNt/tPqpt7g==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:65IwcuWrjnYUnU+KpDa5oA1aqwSeflOsG6y91/z4dhvZ7ThkSIWkn+R0v9wLc5LljKDL+LAaums9E1aQlCGXGdo=,iv:eq/upbDSeNsc/lgxCCOudZNV/2acnp+HNU3RdjE4A1g=,tag:xEyuEntb9hY/Ezd7aqpJng==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:rC4hTsRnchweHItlVplg5a+vGQ8CjLwwzTR8P0l0dhr6,iv:6jaeJOuyWYZtxBL7zac/R0nSJSmgxMQhAtj9wtXqeoU=,tag:Voml5thHq6A6OUbdJeN//Q==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:uIkxIuFiZWVnpYTpDn/rCoGE92SLreKN8SyWUETmhR+HAbbnQi5UdWT4EXEgBjJnr7guGhiUZjyEgIW9qB1PgKgczJkI5UR9rsq9/PA2IA6SEBejYL7W8saXgpfaDi0hGe8yXkEFXTe21JQNosbUyEXNudVYoOMx7RbZnwi6BMM=,iv:2lglsUaYj3FyEOMS/o7XIgINu8wkuS+/JlqeLhO2850=,tag:df7/ADHSEEtIRS/6LZy42g==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:lK2wxjjrP/etDrdiqrnwkA==,iv:KUkR26j0AWXJyGjQQBmVpEwMXWcGDCDdrtuT21xfZ7g=,tag:WQVG5v+RoZDxLYQ7buQHsQ==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:QU6G+zzXlTqiSi823zRkX74Rcw==,iv:Q+XQtf2qlw9UtoqPbtzraCuZnTTI90z3FqS4uZtLajs=,tag:51kOtlXoERmDISVl6+Wrrg==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:QtH/mki11UheXRZqZKIFkpeveLwVVrCIcqzOG7HwYxHsuUTZ0wKwfDE=,iv:FaeAF7ANF8eqyhPsFkASXElQM+vv8ZcyAO1IKVae7jk=,tag:cLkMB/GYQJlFN9CdPa1fLQ==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:w9Fb67lSjtrnlzcguXG+Y67s,iv:Kp7pL05gwMqwhKRprt65AwA7y5aH9pwB/MY1qR6mI6U=,tag:pYpEy/3u4xWdgAjqQneUXA==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:W4m9b79VDQMkjW5akXwaPb5nP3FiFbZQaFwJKPW4RxL+OTtYVBnFEO8=,iv:msbQElB+HztxN5ZumUGlclIbyfqurQ5FgJQJxTc/CRg=,tag:Bosi0TGbC4PRFp1AAnI+7A==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:GO8OKGmSQPbCHEcY4kJJqvYo,iv:5y/Bu7PLp8lW+SE7dOw6PIVYbSaUNlFRznG9Zkv7d2A=,tag:AZb3DivAw8ccbmkNh1+3+A==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVGJMRnMreDZ5M25iandt
            ejJCVWxsK2gwOGg3WU4yMlUveEprbGsvUUgwCmNhUFRXY3JwQi9DbmZuMUQwYTBo
            UitiSHlWamVabWlMTjJaeTcxMm1TWGsKLS0tIDZNb2svTFhjSzV5MGdRTHd1SE4x
            djE1OWltN244ZnJwT2xJTkhIVDFuaXMKRHvRmHwEzxd2P0EgXH1AQGzJAH6VESeL
            ls+/yvAUbs6yV1xESa9YjBbC04SdRn8JXYFDA4DzTIR6JXg10NQHzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb2E5Zk0yTS80dTFXV2tr
            UWtaSzEzT0h5V0VVOEx0ZzczY2NxMmg3UWowCnlHRUVoOUxKejBPdThrdU43SnZE
            NXFxVjV6eGtRUE5sdlBmbWZyUlVpWGsKLS0tIElwQytzam5hTTNWOXN0OGNRYzRl
            cnpVVE5BSnJkUnQycllLR1VkQnRtbkkKQAYc/RC1tfbSk5QifStNGd7ayZY2vpMc
            45A7CTE1V1k0MfrOjseW28gdnXM8nY8aoouJo7keiB0lRpac2cdsWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SmlIN1B4R05reGpGanM3
            OU52OG9saC9PZXhvNHhqc3p2ZWVTZ0FvVncwCkoxUHNDZW9qZWtFSmk0ODlzTXFZ
            ekExODNseCtraFQ0WlBnZW9aYWNBTmMKLS0tIEVRU3oyRUR2MzcwdURoeFRVNmtX
            YVdJMGtRc0pyOWRmYnlyd0lVSEVmcXMKqXovdNv11WHZ0CLnblmUVLbWF+ZBto9X
            wGS/RhiHNg6Z3uLV6w3rzzNXhvvU/wu9QObqlJ7HUg+LxQUAGIgUqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T23:28:16Z"
    mac: ENC[AES256_GCM,data:tUuHjGLw7nFWRbous4Lk80VCPFKDnZx9m+fTG4L8sO6P9qsp8XvmNzr0IiNtVYs1OgfOV7bpBEoErANC8m1/KZCvCFg9wwt6xxa2jLg8KYoCLRetHhfM1toB32ky687+7s7o25tEV8aDi58B7jnkA0KpmD9gPeSfCMxQpAEYdzU=,iv:SVSvLIZtAB/R5LrjNVVF+TS81DTMOfpT+NMuUcKOTns=,tag:lYpfWlpe3lv2yg0leTrdRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
