apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:MYY2DDpHhJfr+A0Ht4GwGNdCyaR8Ud3jCAv5mNLM,iv:jMBRgkzrpPgqPGrh5Qr86XxLtmc2v1NodoMqICjl7WM=,tag:mIm0vuw4XqybxhvI0d8sMw==,type:str]
    IMGPROXY_KEY: ENC[AES256_GCM,data:DmAXM3f9WsJLiYpFmwvgR11sU6i/uMaqmiDx4WaDzCKIJd2ZYBg0hAtr7miuoi0R+YE6qrUfgm+LqLsasDSORuCBYwxRW0OYoCDvW9GdZPkHhhZbHXs3Yg==,iv:CL2gyUpZ23wl3UZ30kRd0onDjpIWAOISaY7c5QX2IM8=,tag:nrE80k2lnh30UN0K+rU5VA==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:8D86m0oJyLwIjj9Nk38ts5c6f6gPLlBfXFMNUt36FYUlQQMeb7TEpUHzk/kuQN8zLhK73lrl8hjijOuIXNWufZQbfZuXBUiUCjgY58gwOuf3T6QgsxL/Qw==,iv:bE1L8mx+miYXsnQq6fugHkF24Vflgq8fIJnIQqeh00k=,tag:r4kGwiMknNibJlNHlFrh+A==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:4sG18jRt6mrfA8gd8idUp6DpdMkvhjb+HQaEAeYRbZ0pFjxLBualIpM3jg94hotKe+l4wMC1Oh64mKAU4LMXpkPhnKkrd3YqkQ==,iv:Rb6DZCj73HKWwlnAQNwK4HMJecBlzllsH2V/3HdcKtc=,tag:pkM1rHl2AWJGgeocZHSPFA==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:8I6oVlfER/3V/X9qmbM0sBqLPS9pfgw2010JbgVjPcxVRmtFDRnRLUNkW8jj,iv:yIL3Tmvc6G+tKpRQarKSclh6qMK0pOVq42CDfKUh7x8=,tag:uxPCAh3megvTVA/BchbJ7Q==,type:str]
    LLM_FALLBACK_API_KEY: ENC[AES256_GCM,data:G9A8Kf1g9YhCBrLHKd9stI6ndE6yPWsLpNVNjhptCn5kCzVk1taQN+7WNbLTd7I1lcketgFETOAnJUv49oaPw40qgmoJr4PjYQ==,iv:hjUSLoslxtqBF4IDGgjJ0rjtv2Jxirr7jHCiJMlkGVw=,tag:Muj1Crpskx3Yt+Y048kUfA==,type:str]
    LLM_FALLBACK_BASE_URL: ENC[AES256_GCM,data:cDMibWllafDo15tcuumOunb0Wk2iJuHjj4ub4pooVA447/7cJtXQRhZ4HJgh,iv:+KKUwMUNqSJBMmn6q2byvSUoGSTRL9gFiQKzqLArMao=,tag:ywzvj6jUjrLqKZlgLJfSaQ==,type:str]
    LLM_FALLBACK_MODEL: ENC[AES256_GCM,data:NjYOwvpa+pKycw5DCSXWmGQr1D/gEhAnLqIZTrSUGL7E,iv:0Nx7h94faAfbgIXjdZqbNxV1pRAlFfKN7RUAiivqDr0=,tag:0Z8G77w7mPPtWSmZ31Y+7g==,type:str]
    LLM_MAX_RETRIES: ENC[AES256_GCM,data:yA==,iv:Ok4eTO6z2RTLGar3+3caoCpc9BQxQB2VIB0kTbyosV0=,tag:haRPq8wMUOFiYSGj8SwAXg==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:CxujMP9dpBhO2wrb5pxz+I3hkVXUB0yw6KXsyBd99LevlWDW8b0=,iv:absh4n0M/dpWi6tRZ0dok2CR6bV6wnoLAIxLFBVcqEc=,tag:wmFfqKtaZBYk6sBqAVd6Ew==,type:str]
    LLM_PROVIDER: ENC[AES256_GCM,data:4Xex8LvsG+/q3Q==,iv:FtEgFxwInPbaDM5a1lsRZhPxmh0HxcH1WOzXtsd2i/4=,tag:U5SkI/PKQq1kIpZLHXjeyQ==,type:str]
    LLM_TIMEOUT_SECONDS: ENC[AES256_GCM,data:CNr7,iv:q0RV3OIqis9ZphVc5Az/GCMvHz+5Y7q+zZ6TX1lWYLY=,tag:vppSrGnuOJwZPdoeYzYPog==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:6/WlSaI=,iv:aAG9/F4InF/BsIIVAElVuR1nuTMMcR1VaIqVoQ/pG9A=,tag:SPQYooU5OvDm+BMmVKs2yw==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:m2GVEHrXGyimLQ==,iv:fnbR6SvRP63SI64ptsxECyJwMriy1xSV/CwKlXogkts=,tag:DZGa0nCmXQh39RuXEbQQEA==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:f7L0TA==,iv:NMjw4q5+oVF+jKNtMp/i/wO3XuyPKPB9miJy3+0sZqE=,tag:iUsaD4ZBqZa7qOBqahGNVA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:O19Ds4nBDNUB9A==,iv:fuTaPcd1XEzVLTIev2wdayeg2cdfNCg43y72NuvzYAE=,tag:y8DXfxHBjg8wGwzop+QvxQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:57OnOmKdiMFuWHfJwCvPghXT1Q7LjRxH+0fnsCNnHr6yqWgJi81i82QanU6s//TiSsG548qCi6oMu1YuLbgOvIA=,iv:SpRwHyV8VvPBfUFqXpCR7uQz4xrFDYcBD02I9Pra1NE=,tag:b1FbVXsdaTuTyI+58ELFkg==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:TSqJjSD++2L9YxWbs0yReuhVturgoaRQFX0zIMJ1dU5O,iv:+mR2mrwjC9UCwcvOZJ7hAqchRU6e8GgkNuDhcYl0Pj0=,tag:t4/gDV1A1MquQTty98cjpw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:o/rfIseWcuNQ7LbCqglog4v6Ow8xfPkqJj70iPz+WfrCDHLGbtNIDE3j9GSgbXMzUWxTjCN3t2m8PMydlYdzIBQfXmi1v5/nS/l7nS/N2ahI5J0zkfa18zH79hwQmaNwDdBcj9ZrMWwtr0dpQNdJJmm3NXY0gVHPuQFHw/Jp+Vk=,iv:wZH5wCCAVTshxwQDlCh2H6hxkvmhN5XERoGM1b5fFw8=,tag:OCi6hr8kj0lsCRjTmLPP9Q==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:7GsqLtFlHICZYRtTyv/Q7A==,iv:JnEjqLRvNPNSWTWSMKMy7xG8MXxq4GgeVjVFrlOxkyc=,tag:QpKrdNpH+85Fl50+30QWkw==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:EauzLTQ4H2p8wJ/dkBdt4G9Hjg==,iv:w1MuCLpPIQSrn/SksICpved3YekpSRqsPapzPsFPmtc=,tag:cuxxLcqa0wRa1xj9lJ+OaQ==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:Xfp7aJi6kdVOvYmS+HYconMA5zrMis60A5E4zBDnd4n5ciT7wSv5bc0=,iv:6ynkF4sP5MwvkgzQZme+bYOoeqzWh1Mh02i42XuSbSE=,tag:+erpHCNe5EATHBbhkr7gVQ==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:Ey/D5mPYjenZ4qhMTDp+YZaT,iv:NxHTZZf2G8+ZcMBjVfrfBucS7MxkuN4vG/e49KGhE2Y=,tag:jMNM1kmekdztyZ+513A7NA==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:Jal+6LZUElDm7mG9Gk0pYziqLcoxRKiuS7U+NjLxT1EiQP5MPpgbuxw=,iv:i6+Cx8c92kW55iEei84xzDtoRLy5xIUm8+Mt4EtWxR8=,tag:arnecuQXcWxYz/bJwzKBdA==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:7JeBsqoqQskje/FV/iQqKWBt,iv:EAgG00fuDDKMqUWj6JScac/Lo9Kli/n8wnLmSVnk59Y=,tag:hcUnsikJN5BeYpu6ZwuIJQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYyt0UzNpckl5WjQ2R3ZI
            WFVJQzFXd3JMTXRyOWdSVSt6cUk0UnkxNWdzCjNIUE50Y2RycVZUVm9acUhOdWxU
            aStFd2preTNZaStRSTFUaUFaUHJPWWsKLS0tIGdrd0Y0NjBhQldNWkpRRzhJZUF6
            dkVyWldybDNaYlpnV1hJWVkraStkcDgKPtP3R1qfGzPaOGQiy7NgFfeKnVlqOMAf
            Ai5v3NH7sM17Rmw+OqdamL/caLkgrxJjpsAUnr8FcXixmZYihTzlIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieGpybkRKOWh0VWZDQVpR
            SWFNSVRvVjRHWEhwdUE0SkNUVWFHS0doM1NVClhYd1BjclpYSlh2akpQTmdwYnlx
            VEJqS1dQNW5LNG55YmxhVm9FVEdHRHMKLS0tIDIvN0VKNmxIbTlEdDNZRWdJUVFE
            MGwxS2sxRENVbHR0SnFIazd5TDZaRmcKTfWfGLtgDuiFtFGbmUJ8YrUra/00Bj7H
            IbUKH8sKrKXTNJfd/9BfqbSaUXVake6J+M0ToKiLzBZ3YIX7zlMHrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bWRLd3VMUFQreXBJUjZE
            RE8wNG1tRDNYV1NESDRVdkRSRHp5V3liNlI4CmhES2R5YTVUTERXZTAwRGRnK2Z4
            cnpZNlQyeHZLWjFxZVBSNEFrOFFLMW8KLS0tIGJ1cHFKNUwxODgvandtSzRUeDdW
            UWFuRkp6NGR5VFNoT2hmR1Q3L3BBU0kKH0mj2srsRHC6e3FGmhAjS/2JypA4Y/Ts
            GZiTDxouamsr3x8OixJnCRe6BNHINyvVPsMMzzruYrCFncNik0ijwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:10:48Z"
    mac: ENC[AES256_GCM,data:vKAkviB7f+qvVB9Ev3y6oQwsfU/sEPS4w/heeYfgRQiBg+i501wUdSKlLRnJ2lJsl/qYB4eb9cM12lmG4hg3lK2KyoRXvpiSouPojV4pPMnNSJKiyQsFz3KsYeg+TovER4LMgAu23xj5eecvCxAbMygeXhhFdBanjnySxifTACs=,iv:2qj8XrIzf6EWU/q6OaVqKQoxbCOAqpge9r824uoMJWM=,tag:HwUn2zJkfhZOckNm4BhHDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
