apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:uYX1Cd9Ethp/4qO96MDZn/mzLpdJq1Q7eUbkz9Hb,iv:fRhhzoJ1uHNuZf/q49nqnK256FBulipd9pRq8xdTqu0=,tag:5M7LoO+cMKHC4ZaOsI7fwA==,type:str]
    IMGPROXY_KEY: ENC[AES256_GCM,data:XBqsTzcGjqZ+LVBR16snsMF0aYLjewH4hPRKxV4Izy9qwLa+T9pslpNxn88BFj/2/j+tfjyX1z1bghNGJyyCBkQ1k6eJotsCgZOl151Z2uEECJs9Yc2vQg==,iv:ekXxaTVwhnWc4xcM/Te6EOO/vToGj/9SQWcfb1oknPQ=,tag:udGxuiZqS2CGp+qCzghVTA==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:LURghhT4OXgVbYf/3XykovOkvQQDWiqk0tzJ30KHfrlptk0yWy8JutY0sFp03ITPBdkg+CJ/L2soM0mG4sqNDvhfCAD5nX//uuCh9GwCQJg0r2m0rZvnog==,iv:Zv7cSJDvlWZ9k70MwITlYdQwLdWOBs4QIbPBUocN9yc=,tag:FGPW279KTdXytKgDfe7z0Q==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:olErMhf0K/6Us07ibnzMI0w8B9OREi9yTDb5NQFxwvSeR+z6BumyC2IaZpO+3z6aQUSRDkWgEarStiXBdo+BMVLiZt614P2vmA==,iv:Mnspsz5mdT7pGiBrGIrY2vr4be3Uax3LgG333dh8O4U=,tag:ORdCFqTYyN3sHW2O1b6Cuw==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:XfhvbLgwu6m9dBE33UEfnXiFe9s/m/BDTwEZyVC/OD26ZN9iFkmWqIP8yl5I,iv:/PRsgX1JSP7okvH+2DxqZgs/L9nsHrO7+1pxv6ITSEM=,tag:BhI8XiZ4WlfDVEGZoh60xw==,type:str]
    LLM_FALLBACK_API_KEY: ENC[AES256_GCM,data:pUtChhW3as5T8lnK/UdfyQKU1k+v1Xe8M8GLAOqz2oj2sl1nEFq2PRksr5hLAJCMEvQ1cqWvbuqWQHJUrGWZmAMghmLufnSFcQ==,iv:uDIBI+ieiefusepISibeYcGkLJ+TgTJ/bOXTp0AAFoU=,tag:Seu0LoNbgCnekx6XpO0pTQ==,type:str]
    LLM_FALLBACK_BASE_URL: ENC[AES256_GCM,data:APNp+ENweG0x3GtYqnkgPI5q5PzsdqM92r5w5XiBUPYUGdVCXc1IYji24OEK,iv:99VgIz2/Fv0MeXg6yDzSXkXcy9p73AvJsgC+M17tKUo=,tag:ncefmrNm4qu6Q7fCVFZV0Q==,type:str]
    LLM_FALLBACK_MODEL: ENC[AES256_GCM,data:WlUwMbOQqshjAUBXd2UgVpu1eBVhfyWDzOpzyZ3SFI7P,iv:bOR4zRqZDElxsudh5aKEDx4qLRYK1le/TvYtVBn7ZvM=,tag:GBNXe/TXSS5kxwTB/veApA==,type:str]
    LLM_MAX_RETRIES: ENC[AES256_GCM,data:OQ==,iv:9PUPvR9h+Oc0CbQZZFqV/lBTV6KfdSOHfVwxKO8kuZA=,tag:2s1jjY8Ok9US35DxGWfirw==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:lzmUmYV7Z7j9/D1fJcdeGUybBgMUNireKCY1CPCZE48NJ9wdPYQ=,iv:bjkz0tHgXHlOF439euxz302KpjvJSjon6mPU0ZViG28=,tag:LXDFq3NC7bMj6acvWVx7ag==,type:str]
    LLM_PROVIDER: ENC[AES256_GCM,data:c8FTRp8VZvmCVQ==,iv:KUtXR2uQ2XRGwuRIXIR0Qh2mup9644NsxC0/iFvoUSY=,tag:g0FCxkukqiZJzRqzhCAztw==,type:str]
    LLM_TIMEOUT_SECONDS: ENC[AES256_GCM,data:S1do,iv:fzUsvZ9iztQGCI4LGFfU3s7mFbBSOieVUl/4jhd7MQc=,tag:NNMejGydDJCbndPKLbhcpw==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:DuYWfGw=,iv:t9nAjAuPr4GAVIYOKTwBgIdjyxmIj23CccgEEetlW30=,tag:9RTaKwNvsxecypBOWi+9hA==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:6lXkWCyM7Q2JOQ==,iv:cbpOMsyrhZaJbrlwZV4nm530n5qL+Kf1yecGD1H/sc8=,tag:CM+qcDQgS5HPwHOqz93LsA==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:7o8dUQ==,iv:65TePl9YPqbYRoh8zFbQskFSCoT0wAjoHpSQuK0mQbk=,tag:T3sxyXvpdK9KGfs7afdJBg==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:mJASGxrZFRyZHQ==,iv:Vgz1neKVP2YW+l36pn/i/ITv2QZB4nOBUCQa8HkXjts=,tag:reAHXvSB6yelOU6f9QlqyQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:J6RMeX411gg7wC/r3mQagBKtghaqH7Rgq3emrgVMG73W/Zu7pk1kjFRPycTh+scMfZNw/X6gTpWyiE3enzJjRos=,iv:2GSkxWQjGhY7pgBytwzI7qYqvuiAZ1yL+VFSRELNpv0=,tag:teRokXMZNK+7cMsyoN9o4g==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:X07+A4PGFUmwB3hJCJXAuLQKTHPucbBSMPQKWpsyf2Vu,iv:h4/tnbpOfsTChZemXAvVbJhaWAzee8BW7+ztQjIjkqc=,tag:Y+s65V2iQBHy4RnfNB9dOw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:nIbwQeJ6U5RsllDMYKD8uth97PwSnGsrw5Jiw1bakAiNthjGjlrKkKj3iYypD10nNPQevYSC2lwWiTMOiahTFRqmlkH5V8C3Nv6dL5TWhEAsNfUkkJGyA/h7WPbcAkSBfqTx/WEmWWFQPKgPm0h+VNjPI10Hp8i9JOzSmjPvqU4=,iv:0EJ1aGFUpJkFqTLYl4p9IWt8egytf7CRi04JHIPTKac=,tag:YtqxQTq2geo1ZbQtAEz9sg==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:zbo4C1rhZh49ddvaanXFPg==,iv:mVARWND86sx+tPDSomiNbOLIvTn2R8M8feGVrTXRn1Y=,tag:kQ1FyiE67e7r6aqgUYKLJw==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:4Iw0TrPMhCy+X0FJTYn2pI02LQ==,iv:fgl7dhCADjSJHFj+N2rsLxS06UMcj2r5I5enIbB89f8=,tag:A29OCZEKTru2NG8txRprPA==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:fxofUO+33uXONxlnKV7NzDuUbkAcjizPnITeO47zx3aPtpm3wL/kS+E=,iv:0jOs7f+rrqF2S8ARTMrJ8VDdP6gekbpE3tJ6CYyjMQA=,tag:1UWL722tbXN2KgLaavpZxQ==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:EDn1GMtwhT2acbpQtW+3yABf,iv:9fC6Ll7OiAgVgn+WqQXAmbkDfpU+RJUWL11hJVuC11s=,tag:ksXaVoJLvOUIMi+oL0GrZg==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:3ZPEaEfVnsb8pnXh+9wyr7UH6BPRck4civ7Y4GzV5IULMa1SIeoi4Fc=,iv:SKqB7t4e2jOFqynApd816jiAUjd2h+vEdVHKoD0cJkI=,tag:aP0fg3RrgyU0Eeq7VB6SuQ==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:QteDBT7UKz5E0yZBDJi6tP1I,iv:UUf2cpLPATub050Elf1qvwTeHEBUu8dF16D48D8mbhw=,tag:fmrsCMyS7zQ0Q39WgpPZ2w==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeFhHTksrU05lYmVSdUVO
            T2J5SUlvUUwwc3BHbGUrUVdZRFVlYUlsR1ZZCllwR1paN1B4bkRENEtJWDlqVVcw
            VjRNQXdaYWJNVll1TVNrSUZtTnJuT2sKLS0tIFJDQmx0bjZqVWJnQU13cWl0ZEFy
            amo4VTJEeGZyY0JOM00rcTNUY0ZUK1EKTAA7etGclPy4tdx7sMHPPkjfRPP9JtA5
            +/3lC1uXEltH3V/XPTuRyAUlq2PtT8KH4DRIidPAV9/nmgx8saqusA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWFhPYXdDWVZ6WGxXanRk
            Ty9STHFsdCtORmhLakMvdlFRZXhra1puaDFvCkl3Tjg3bEgzbE9STFZ6MDE2NE9U
            Skd5OWVsQnY4NmFLcU42c3RGMDZrZ28KLS0tIFlpbFQ0bU5MU3NKSTIwVGE0Wnhi
            SnRlR0FJalR0Z0N6YlgyOVplTGdtb0UKXTYR+almyn8ipp+ro8G/Q2t+BCDwNbwo
            rtNUhtBn8OhqHzHaGouvc554E/wHl5NePvl8ihhDtcVP7wH5flfCOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRjdyWTI0OXEyQXVSaWM3
            bSs1Sk9FUW1mMWVnazBZSFNSS3ZpVUN2emg0CisxbUxYZzh3U1BQbHY4aDhORUQr
            TzZWL0xOQWg4UHNxVk9YWHpRa3NndHMKLS0tIGRyRUlwaVBuQXkyQVV5a0JwWnhH
            eFZwWGgrZEZKVlRqRDd2blBKRnhTQUUKJz+ySJJ3LSgUwjl31sH/e2BTmrWzzg+E
            96DEVCixFBbttE99jPYhZh10waXgXzb6MUu4t6Qd8Gu+EeW2o9o6wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T21:18:56Z"
    mac: ENC[AES256_GCM,data:YDTz7/8Irixv+/GDJ+vfz6JnIIYaD1yO5/tmyDaSwqBuqmOwEqqBV2U9+pswCy8o27bbEnuC0U2Yl58b45PtgHMyCQCyH1jKSbziPYTHABgT1Yg/PtJRTG2u+1tt4D9/R6CyihZ2HEwq2c3G1goXaVcD99CUqk/4m2DpR9U/tQo=,iv:3u4jD7mZzWu3u+Cnz/Uhzc3P+6LaTzp4Sts20IPzBB0=,tag:NTWpMFi842Tu2BUGlX3AFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
