apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:O4ISfJIEzQBuvjEhGVqs6bSMIqfdPJdjeXVEOXZl,iv:vEGH7KtLrUk8z8T+LMZV2bpkIlzw3CDpeg527QE+55A=,tag:isPsS/o2oLE9pIvqta9BUQ==,type:str]
    IMGPROXY_KEY: ENC[AES256_GCM,data:racldDlXtzPfnFONIgHOF5+XBQhIKcFRhvD/lSsxWL14p/MQnyKtc5+8S/mqogn8Pg7cFW8RYpuIXFu9enq/KyeIkwxkHl/HZizEfKizexkiLz8+BC1bpA==,iv:1bkz4IW5gjVWxslXVWmKkjlgjVa2ymCRQC6ll+0PjU4=,tag:XODUw8DBEFCYuMP3nYXXiQ==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:v6cDC2kXTjdFUGHY1epJe7oKbr/LBHM/7gH495JweXdC1WY+QAtw8A/E9BNUDOQ1gpQ1kn9Dys3wSXR2thJLTmhq0MdpONM2otGZRKeg9sckEhdM1wFTgw==,iv:ICkMGTTHL9aJYug2Yc+qCbSjUvIacERuvlp5bLL3n8g=,tag:gy34EcCfwvygdepFG+sxpA==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:Gp7AhFo=,iv:TOuWZTsg03V5IslWXDFbg3DiwvVTm5ptfHvu1Xab+xs=,tag:7FPuZGjjzfxlwc+UONbJqA==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:1yF2xv/viaoo0Q==,iv:y/BnbC00NAY46JMRuyS9nc8kwK1kcFRkJ2kNasy/afw=,tag:RfOMO7Co14Y+x120jhvjng==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:G9u6rQ==,iv:uCfBrtBwwJl+P0un2y1kfuo1EH04cSSLlvswT19Z3JU=,tag:S1oB9xLj9dmbwIZRkNnU6g==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:5JyCtp8ZfifwDw==,iv:1kCCIjhtpY4C5tEHZ5yCHU7Uice0hoYlK0+bJEf5P1M=,tag:Tnx4REFFWLPHGSuB2plNwA==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:8XgPQh062wSGUWxDPT9BhCFN0L9XwN6Jc37RnEloZPCxE3gJZX6nlzHiyRb2z7ojsdaLJ7kOVW4wNLD9RdT25oc=,iv:zzL+ikDBsVjdEqFPIQIqJdAkxfIFFtGxwW0+dhDpG+A=,tag:YvHMBDmz0o8JgHvWHOCvFQ==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:EQDE5XS5niIpjE9XXgXfg9LyiIWVgaA8bB5u9/kmOf6H,iv:DTsNfpZRcxwMrPtB3U0aD/HbosWA/oMeQERfEra4/ME=,tag:b3T0f1GquJuuugWHpCCS4Q==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:roc3cArqe1G0BAO1kP9MoatkUh9Gwkmwr0UdWqHklsFmkzYpKbpJ1G53jlZmEsQZcZWjdvolWlCQ2ltB03R5UNckRI4NVLv9H3b2wVh6MIzjfEfjaSsfFPevAJ/u8rCDfGKJRTaX/5DzEZaxKZrqLKkHaVyOYIKyBmFAlqcd5dY=,iv:AqoRNB1p2X9scm9BMBIPCs7EoZdNjkR1wjR40Tq83X4=,tag:d6gMAKylCUk0tbIrjnwVmA==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:2Xe1WX2HENNDXfa6gj/gpg==,iv:kHx2GaWOeq6bVS92BO1jNahCvPBnCvSsPCpgs/6tnG4=,tag:1gj4Y43fxGIBPFNjYvylyQ==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:L8QTiJGamyxrR6MqBT+FIMjDMQ==,iv:WYuLPS3iOBaXeB13Xl/noC6b2pZKCZ4GOOyGw9DVc5c=,tag:b93l19QDrfNnZsgLeIKpug==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:qeVKOJCnzHtgyOIBt6TTLqz5ev21ziG8DthhQTpNrasPSOO5jMpIwPE=,iv:kPZpIy9wEol1tVUZ9g0Q5CCmvJlEw/DR240vbkKJXJg=,tag:xC9VECOIVa6nHrOpjzv0LA==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:UxhUtYLsDz7mKua6vdmd3QE3,iv:wKrWgySvvqWYHH+0ItI31t631V2/N33lpG9bTzCMPZU=,tag:ftbxz+QDaDouTKNCyi8Ptw==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:zmM2FWZwlUX1EtrAEVQq2oNXyV+akJ2dUiMkgbpDfp+pqcWwZ35tS6w=,iv:Pi+8u6fUp3TdNkGOFymUkXTtHWY3z0kf0XptUW38tgs=,tag:im5rdPkWE2uUiiwngo0zwg==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:6U4hwPcSnnf/VEe4LeZ3lPlg,iv:5km2Ch8Q/yjt72FhnDLLT4IF9sHzY/wqGXkbNFOGKY8=,tag:HB7Vc9+z/mMy69NDpEHmZg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSWQ5WitHTVlubGNBTjVF
            NFhjcForSW90b0FIdkZhOFpiS1J1YW43QkdvCmd6TWRVT1F3TnNnTTV5YnZzcmI0
            VFI2QUphU0llV0NTN0hBOVlCc1FvVDQKLS0tIER5L3hQbmZUVmNIU0p5WlFVbFpH
            eEw4ZTg4WXJNQnFKdC85eFNqNVJsZHcKDt9Xcg/Mtm4O8dNm1AgQt5LI4/Q4t6P/
            6937ZyKr3xplvx0k468wJtlAp3lBE0+OyPTq9Wlps6rCUME2b27GYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMkwvY2lJMjRGRzgyenAv
            dG96aC9wMFFONVJXcFRlNDN1MVl0RGIzMUFjCjU1cWtOeFMwdmMyWkphQ29jS2xk
            OThJNjhadUY5VXpMdHR4bnNHZ3RaTmMKLS0tIHdEQzhzTTZxNnQrTVVJdFgvNEJi
            V2R2SG5pMjlOTXc1cks4L3k3bTkzMUEKrUwEMMuQklcfCsp2nj5shiATIFROnQlU
            CYBNCUVNXIVsBcvnZLef62jKo7h3CKQR4ysIUB3dKGJ8lPMFOeR/Ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMWN0c0RrV2VqS0ZxZlhk
            alFFWExhdU4xbXlVaENjM0NKNXJ4akZORWtjCkthRGVGYnBkZnlOLzNPWkViWGhs
            MGJqMmREMjU5c2V3VXFiWk1qLzZvZG8KLS0tIEVUa09kZ0xPbUtQNjBPN3d5ODhP
            eUxHb3VybkJRb0xmeGF6c25KZmFGR0EKmKGh3iMPvN7C9pB6iGo04kkkQN1vDWZ5
            Ys8xJ8bqFCKY+DRPDZafEOcbs2ehYxVDJxjQrY95YJ9ScK9ZZfKMag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T20:43:11Z"
    mac: ENC[AES256_GCM,data:0t6tNr77xtRjL6MX5VaHWrTWOJCL4rC3S5OxfhlPzJ9m4ahvEKAc4W3ASUl+Z0R6B+WlgfwlZoWRthinnARr/6VmhOunt3iqThzb4utLBTIOe+Rwh43SANvNFcYgzTpf6sTmuCB9eZKBfBgogQ3ugxbHU+OCMbrGURE1/ax83LU=,iv:kl2xWOs99hPuLlbBvyGQKyfjTo0UfYCG2MeKqhx/0vo=,tag:NyE09GaOxlDor5sjJn9SrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
