apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: velero-s3-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:7VwscAAB3PuaxJU3gdMd6cYerEPet2vVxLRRyM+GykpEZOHbAQC58PZF8WAmB6TsYSL6I5waU8Vf3e72YPJOc5RfbXMoz+3KT2EYUYDmtLwG0CFksk+E5vfbH5bIDUgBYJUR6yTxO83MnCTwKZsHyA==,iv:zSDT2HKRr2vxDsOG1896JffkTj1/iCjzuaZcASKFVGo=,tag:q5Pr9cjr2nNyfN8tVb42aQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eVk1c1NlTHFPM2hnL0xr
            NDltcmhCZ0t2SzVWQ1dvb2JjVVo3RVFKYXg4CjRvQkxXSXVyN3g5bFcrVXBBaTc3
            VitwL3dhMnFKNkpOck5yY2FFcXR0ajQKLS0tIFdHVUdvU3NoZGFmb25iZ1JBZ2FL
            RUpGb0hwNHZvekM2UWxHdHBiM2M0dDgKS5cPq4BktyISe5s4EZDVvXgrK0US/iZ3
            7mh2WO+JwOmTYNabIy9mzHtUJ+gDBugfiEKlsVzDu10gux2PNRpzKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabHFIQWRzekc0RWtmL2VT
            SklDcGtQUTFodnpPYmVwUzBwYUFRL05VOFF3CmpJc1hQV3Y3MWMvUE5QZ0owNE9M
            dUNwaWRMcEhHTjRvY0FzNmFmUmlVQkEKLS0tIDVwN0xrRGhxNUtzTjhmL29VWkxq
            ODY5aWNzZ2x6Y21jL0ZUMFZlbWNlalUK9ghCb5WghUXNZ8FkleLYOfuET77ov+j7
            BEzwnGHQwzPd56NFc3xqelxYtadq+h04q5bVgx1SAU8hnVpCLkprqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR3VmcXNMVkNBOFVkbzlL
            KzBFVFZVZzNPM0d5WU9EZ2t2akhnRlgyajBrCkV6S1BmVHpiTlhiZ3N2SXlJTGNz
            SjNXTUZCcURUNDZpQTdhL05IWVNrZTgKLS0tIFlOczNYU25PUSs2MFlsTW5TLzl0
            VDJrS2l6RmE1alZnNTNBV0Vyc1pCT1kKfEjPdZIRSyBp7ViZMAgsJv5XQ4Tc4HUE
            Tvr5mFjqbii+UhOED6pOFyGDJo88hO8XjWXCfERHZuNRqRl60LKi2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T22:46:32Z"
    mac: ENC[AES256_GCM,data:3bUGYWvmuF5YYOV7vdg/d/L12DLGFhFXMPMdszVEiA7AoNz2Qml/0WkkOPiP4ol0zWcYgjibs186K3nToUNvBD7yk1iDIIX0jndabYe1IEm0zYjggBoQ2lnXVt99Xxo+PAH7WUS63TSSAneA29hKfvdWcgUo7FxJIQsXMg1FFbw=,iv:lc4ucAcytfapoObonEQpNVlbcZplXFIboYcBCGd2wX4=,tag:l4F8Hq8Hnbtu2al21boxJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
