apiVersion: v1
data:
    password: ENC[AES256_GCM,data:FP8q5qu8GB/0AaDsDmoB+g==,iv:vrRgBaT5BtDNqtByG1imwQbxE2NZj+F9hG7ni1EGsTA=,tag:l1H/fmND9ASpXV6pjC9V7g==,type:str]
    username: ENC[AES256_GCM,data:2hXrYVj7VfhHqenr,iv:55gHcpYnreDWCjiLObLghg85qSIERf/0EZCZnGJYSg0=,tag:yWKu5ZZVZGLkxXVEzCfTjQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: smb-export-credentials
    namespace: rook-ceph
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTlppMkRLV0tvN2pydkIr
            STJTdW9HV3pCcVZqS3cvVTdGTjJvRkJERkNVCnoxcU4vN3RRSTYzdEVja01Zejll
            MW5RcDdHdE9idlp6bkliQlFYd2dBUGsKLS0tIE5rcEdCTlI2YTlIaXVBNGFPUkV2
            OXpnVW9NUlB6ditRNlV5d0NtVU5pSlEKzpS3dQGH22FMhks+5CfTt3SumiPRH2j5
            Mv+ZPwudX64J0y7IVzrw45F5LIwaLHj9yBADHQRzvp/nLM1OlCgWJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMnQ1bDlFWnpxbFNBTi9v
            eVJVeFhsclJ1QzkyQktzWUFFSk55NDhhYXpjCk9iTk9oN2gza2Q2d3NocDhpMVFw
            NHBGUUN1MHZJem5Mc2pWZkd0aVVMc0UKLS0tIHVWUG5vUTE2Vk9DVWsrUkJwMnZ2
            cjdzTFBFVWZScDU5MTNpeXVtdEQ1QTAKsnRTxcAyHmK5QZfMSlluQ0bjAjhXI0lK
            csMaw3ge0lBxFzk+6nEntXiea4JhhEuy9nV0RiQvPXE6JIciBsd7BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscVAyWDZZTFlKK0NiaVRH
            RjNzYkljRURxMXV1ajFUaDdJOUZGZW9WcWk0ClF1aEN4TVVPZ3pvOE5KNmhKbmJQ
            QTNjTlQweS9JQVdTa1NYaklzQ0drTFEKLS0tIEtOVjI1RUw3UjVSN01ZUkMwbWNy
            Y2RLOG4ybUJQbGN5S2s0V2wrKzNzT2sKvYqUiy9Kf54ie8hjyqCPcjyelHZ+i6DW
            DytYjiwOtC+DAto0owtuB+OHEB1/Ekm7DanA7/3Qc0f6OoIaSX5ebQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-30T22:31:27Z"
    mac: ENC[AES256_GCM,data:dXHrzTBvtNfMCxYIiy0hqJlFcEvsAsuAfWV6DRuQ61zfaUlCsc/Cm4OZx0Rz71I7Pfp/0XFOjE6yz0dxrZPzhSulF/4nGuCW1XS/n2NtpIggC6Zpi0mbRVxEnmEMLX+27KVDcQUVpkCyWXiSouAJyKX0QNI2FCL+g071qR3u2ug=,iv:H5Fn2gZDwWL3V3a6hoyzCrdOJ1cMwBCEFchRrX0ibWw=,tag:p7JIi7HRSXta2/Sl7sszIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
