apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:YuUyDj3fkgwwX6B/vnV+fg==,iv:aA/rZzqwo/Y+Pq0vF1a7D0vvxYK4YwLaWk6rmCz2aRM=,tag:M90NTDXbPaHbpUlpL4LTFA==,type:str]
    userKey: ENC[AES256_GCM,data:SVlFsaphtC/Z0SGyT4huflTvWH+j/45WelYxTu8tzz4Cf/M4q4jO73KZbE7gqn5Vj8XzERO4LnY=,iv:oQN6xOTX69W/sE5PNImO4ImCpBYgpxgcVFxOXH+zuh8=,tag:ymzQhl/qDETWUxcMcva7nw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SHlHTERUV1dKUU9wNWVw
            cE5zMkh2akY3YnQzdHRvcWNkQWpOOHNEL0RNCldRQzY3dFV1UkhaT3dsdmxWMHd0
            SkJ5QUwyY3o4RTFTa3YzZVp6T3k5ZmMKLS0tIE14UFN5V3h3U2IvVTRaSTcybGpu
            VVlWZEMwdUl4WEdpTGl5TDNnR0d0Vk0K8GxafdqzeIii5CIPcsR9xOCUZ6dPOX7O
            yn+wMsf+xstrG8bkPLZ/m9ZJOjbZZvfUW1hX8o4RpZ5jLYaP1nYwCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUHNCRWl2Q1EyWFM4Tjc0
            eS9HNElDSk02N2lCTkpLTGJDdW9sNlhISHpVCmo0WXZjeTJaM1lIYWNqbERiVGRp
            NlN4cVN0ckJGTmtFN2I5bzZsVk5Zc1EKLS0tIDk4NGtkZm1hTDFQd3RMT1lFT2N2
            aXhaV0Z3OER2VTVuZHBHaHBxNFRPQVkKoKbUwyiaNLnILDSaU7+AxE725mxXlKm5
            ew1ng7ZS1qt2HtGgBu+OCBETiO27cGcfQxmDpysVf4iq81KXJ4Fwpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZjFkWVUrVVBVNDVtWlRW
            T3RYYm5FWkVkMHFHQ2JyU0dLUStucGhGOWp3Ci84a0E4TUsvdk1sSStNN2JQWTU4
            ai9tZ0QyTzR5ZTVhNFFmbExTd0psRUUKLS0tIDFsQlRDTU5vRUphSVhVRDFnRnFy
            dHhQcWZ2ampGRGJWU21jOUVYYkJoTFEKgsHrwQ564P0mqejO3KMcRoVHHqEsD2f5
            0FBdwd8qQWSbfesAIAS7Eik1w3rAbceN89i6K8bZU0PMgGiYxMifOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T00:38:21Z"
    mac: ENC[AES256_GCM,data:iFIHBn9wGYPsO4QYXq2COxFiHWYP94gFYgJ2sK+hoc4Q76cAmbycWiaLueTEbMUd8NWjaN3CABbvQxp5lfeUsFwW4M/QgkKQs+dmTqAYyUssdZKvxHnBWForbQAeVQRKJ0/zUHOKKrQX+jbVGCSSz3maEJj8klcjSOIz/AIN/n8=,iv:tu19J7wB8Cam26qv3uN7QNW/qDSViUGDgluT5GqCDMg=,tag:vuLeFQnMquwSJBpbCBJAZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ikqswcI+v1+3mh5aS/qTTw==,iv:dcmJi84vXKslcfWudjo4Cz3Up/GFPEShEeoMPU9xIME=,tag:reLD6XsmsVqx/EdRSH1Rhw==,type:str]
    username: ENC[AES256_GCM,data:lFtv101To7y9f8tx,iv:0JWxUKPMz/5el54wnPdqT7vnpNJRXws0iVK03lNmYSE=,tag:o5iWq25Dr/7tkQ171snAlw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: smb-export-credentials
    namespace: rook-ceph
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SHlHTERUV1dKUU9wNWVw
            cE5zMkh2akY3YnQzdHRvcWNkQWpOOHNEL0RNCldRQzY3dFV1UkhaT3dsdmxWMHd0
            SkJ5QUwyY3o4RTFTa3YzZVp6T3k5ZmMKLS0tIE14UFN5V3h3U2IvVTRaSTcybGpu
            VVlWZEMwdUl4WEdpTGl5TDNnR0d0Vk0K8GxafdqzeIii5CIPcsR9xOCUZ6dPOX7O
            yn+wMsf+xstrG8bkPLZ/m9ZJOjbZZvfUW1hX8o4RpZ5jLYaP1nYwCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUHNCRWl2Q1EyWFM4Tjc0
            eS9HNElDSk02N2lCTkpLTGJDdW9sNlhISHpVCmo0WXZjeTJaM1lIYWNqbERiVGRp
            NlN4cVN0ckJGTmtFN2I5bzZsVk5Zc1EKLS0tIDk4NGtkZm1hTDFQd3RMT1lFT2N2
            aXhaV0Z3OER2VTVuZHBHaHBxNFRPQVkKoKbUwyiaNLnILDSaU7+AxE725mxXlKm5
            ew1ng7ZS1qt2HtGgBu+OCBETiO27cGcfQxmDpysVf4iq81KXJ4Fwpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZjFkWVUrVVBVNDVtWlRW
            T3RYYm5FWkVkMHFHQ2JyU0dLUStucGhGOWp3Ci84a0E4TUsvdk1sSStNN2JQWTU4
            ai9tZ0QyTzR5ZTVhNFFmbExTd0psRUUKLS0tIDFsQlRDTU5vRUphSVhVRDFnRnFy
            dHhQcWZ2ampGRGJWU21jOUVYYkJoTFEKgsHrwQ564P0mqejO3KMcRoVHHqEsD2f5
            0FBdwd8qQWSbfesAIAS7Eik1w3rAbceN89i6K8bZU0PMgGiYxMifOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T00:38:21Z"
    mac: ENC[AES256_GCM,data:iFIHBn9wGYPsO4QYXq2COxFiHWYP94gFYgJ2sK+hoc4Q76cAmbycWiaLueTEbMUd8NWjaN3CABbvQxp5lfeUsFwW4M/QgkKQs+dmTqAYyUssdZKvxHnBWForbQAeVQRKJ0/zUHOKKrQX+jbVGCSSz3maEJj8klcjSOIz/AIN/n8=,iv:tu19J7wB8Cam26qv3uN7QNW/qDSViUGDgluT5GqCDMg=,tag:vuLeFQnMquwSJBpbCBJAZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
