apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
stringData:
    userID: ENC[AES256_GCM,data:FYkVpS20X1MFNg==,iv:MOja6/w9dg9WPKBlRgk7YxNJMyJYwIzCH3oHsF8cAvg=,tag:mIL+yK5OAkYDuqAK7eE0nA==,type:str]
    userKey: ENC[AES256_GCM,data:Vtfsbp20sD8yR0A7kOhwVdsaJUaIaa9a5VCYUThEOqXDrwzv8hA6Nw==,iv:P5w1lK83+1nsE9WI/uS20eB774VsBF2mTCz3/Y2JR9c=,tag:diiLUA7muVIFRxwYUpTo6g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTU8vNG12UG4zM2ZIOG9C
            S3p5d1YwbURJdzc3OHdIdkJFZUZVd2RSVEFVCnRpK001RTg2QStCNnlwU1NHbE1t
            RGVDendBS1E0MzR3cENYNFJobmhXRVUKLS0tIE5iTHhKRU55VHIwdzZacnl0ckdK
            UDdqdkk0ZkxlbW52MXM1OXcxWm94R28KDDCM3XZbjbrpHH8qns4qalQyijX/GaJh
            3L7QojiVDaluX1RHsQoVCPN6u/ZhSoxg4kgvn73QTvR631fxmmZV3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwajRKZ29ldzB5YzMrQU9u
            dXBZelNsb0FCYXFIMWhMUXRSVE1QelRpcGljClZhSDBremQwNmZIYU4wQmpnYWp4
            Nk95OXJuUlBTTHhwRmtNa3NHTHF5UG8KLS0tICtVYTBLU09jbEpHcE5uUWd6ZHVU
            QnRTVThQWEozYXM3SWY5Z3dPUGdmOG8K9LqkMejEWoWqjeMD8wbrbaUHjggVmCLk
            1OpWpdFnsblv3kIJt4A99/ly+lD+UbL0EZLmJ9xIFMyD8eTYKMd08w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN2VOYlphejVQSEVyWElP
            bjVsRmVic0lERFVvWlQxUUVGbG5CRnd5eDBFCnd6V1BhRlBDd3dtV2VUUzBWUXQ3
            aHZiOGM0SmsybmtZSmtMOGVFM1N3cG8KLS0tIElYYlNudW1FR0N1cEZwWTBIWnND
            QzVIbm9jb0tiUG5SemY1b0s1cCtMcFUKkVOnYdA1ll0/ObUO0adW8ekZG5IvKC97
            S5dMdbU1GrAwMv64lK/A/LdCHJhYTyigk6eymx4PNq+olouTgKtebw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T02:40:05Z"
    mac: ENC[AES256_GCM,data:8fe7axkVWlDeAOq2rn/SvKa5xql3IM00QQuqdVojbSzPMX1Ou1U5iCoMCTaJxTWw7XnNZhBlluZ3vc7LUqN7MHTWx3alpnwQ8O8638MRTK0+k/TOINxxCcbCOcJMn8yAmCB/GyPHs6qsKoYiugLIsMch9JYq64/ZhIjpDgpmwr8=,iv:s7pRpvtl7DVMHyjBT36d3aUzKxfTVniMp98H+KD7PlU=,tag:ITOl9UIGLgQu7LJxOb73DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:cEpPaXfg2BZe2GsXJ9bZ4g==,iv:eeVxs0LK6g5igNb7rMv4w2WgHWnl2TdFKLmahC39OTY=,tag:qfSfh/waeY+ndCpftl6cDw==,type:str]
    username: ENC[AES256_GCM,data:2Y2Us75GEs8s/AdM,iv:TH9oJEY5plh0T4fanrN4ezJieJYeGvACLuSNCBEUo0c=,tag:+tGv9VQg8DDE3I11VARvOg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: smb-export-credentials
    namespace: rook-ceph
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTU8vNG12UG4zM2ZIOG9C
            S3p5d1YwbURJdzc3OHdIdkJFZUZVd2RSVEFVCnRpK001RTg2QStCNnlwU1NHbE1t
            RGVDendBS1E0MzR3cENYNFJobmhXRVUKLS0tIE5iTHhKRU55VHIwdzZacnl0ckdK
            UDdqdkk0ZkxlbW52MXM1OXcxWm94R28KDDCM3XZbjbrpHH8qns4qalQyijX/GaJh
            3L7QojiVDaluX1RHsQoVCPN6u/ZhSoxg4kgvn73QTvR631fxmmZV3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwajRKZ29ldzB5YzMrQU9u
            dXBZelNsb0FCYXFIMWhMUXRSVE1QelRpcGljClZhSDBremQwNmZIYU4wQmpnYWp4
            Nk95OXJuUlBTTHhwRmtNa3NHTHF5UG8KLS0tICtVYTBLU09jbEpHcE5uUWd6ZHVU
            QnRTVThQWEozYXM3SWY5Z3dPUGdmOG8K9LqkMejEWoWqjeMD8wbrbaUHjggVmCLk
            1OpWpdFnsblv3kIJt4A99/ly+lD+UbL0EZLmJ9xIFMyD8eTYKMd08w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN2VOYlphejVQSEVyWElP
            bjVsRmVic0lERFVvWlQxUUVGbG5CRnd5eDBFCnd6V1BhRlBDd3dtV2VUUzBWUXQ3
            aHZiOGM0SmsybmtZSmtMOGVFM1N3cG8KLS0tIElYYlNudW1FR0N1cEZwWTBIWnND
            QzVIbm9jb0tiUG5SemY1b0s1cCtMcFUKkVOnYdA1ll0/ObUO0adW8ekZG5IvKC97
            S5dMdbU1GrAwMv64lK/A/LdCHJhYTyigk6eymx4PNq+olouTgKtebw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T02:40:05Z"
    mac: ENC[AES256_GCM,data:8fe7axkVWlDeAOq2rn/SvKa5xql3IM00QQuqdVojbSzPMX1Ou1U5iCoMCTaJxTWw7XnNZhBlluZ3vc7LUqN7MHTWx3alpnwQ8O8638MRTK0+k/TOINxxCcbCOcJMn8yAmCB/GyPHs6qsKoYiugLIsMch9JYq64/ZhIjpDgpmwr8=,iv:s7pRpvtl7DVMHyjBT36d3aUzKxfTVniMp98H+KD7PlU=,tag:ITOl9UIGLgQu7LJxOb73DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
