apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: homelab-user
    namespace: rook-ceph
spec:
    credentials:
        name: ceph-object-store-credentials
    displayName: Homelab Client
    store: homelab-store
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ1puVEY4cVR2YzFvOHlD
            TkZEdFczaGxoWjQ4SmNsdGUzaCs0aDBBYVd3CkY0eStRL0lYUVBiZ0lDMzcyVUlE
            UGoyYXpVb2JESDNReHVoMVZ3TS9GalEKLS0tIFFpelZib2o0WEhBc25ROFhicW9q
            eS9SaXNsTUkxTHBLaUVLUzZxNEJFaHMKecbPVr5DIE8OzTeJbG1nsHebeifAbKFt
            z8NxOjO/zuDQycJ+UxLJLHlt7U/hOqspN/3K0cZkoRDLJnXcvahrfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ1I3UHB0T09oeXlDUEpK
            S21leU9Fcjl2WWpqb3ZsQWN1MWVtNmh4YUZJCm5FVWpkS1Q4ditFQmp5NnJ1VjVx
            Y3BUTGZiN2I4N0pENVZWeXJwZTEzOGMKLS0tIFdib2FsUkFPY0k4TGw2RDhhcXJt
            VmpoK3RPQWJwOU5LV1JaVk5hdUdpSzgKuLFhNHthyd92OTNeDu+rlDBTZr2IXHD6
            nGvEpl5hnUoLMT2QtlsRk3l3T/bo8EL8KXMotzQm4Fe9QMDHjNpG6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMTVVSmhLenZhdFlMUEVk
            UStDVG1nVTVjOXgxRk14VVFpWGd0NGUyeWhrCnlvSVVPMHY4amhkZWcyRW5ydXYr
            cHkrc0FSSnNqMGFkNGdqVVNGTVpWU0EKLS0tIHowUFV0TEk4aGxoczBVNDRMUHVn
            OWU3QmYxa0p0c1JHei9sc0UvRGlSdHcKXk8Lje6kQu4L9W54tNMNqlVi15CEfnUg
            ezWJjPoNhYT4SOeCpGermrU320beFvDwpOcVsCx7HxEb56CBh6rCJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T00:49:05Z"
    mac: ENC[AES256_GCM,data:lR/ydAx2JY3Y/bJxN1gzJw7CSe2dDPXbcfo8lIyxDQCXNFwwHHq9vd3y9IsLrKvOI7Fmj/RhMWdc5mVYQW11pdHae51OixrE7cCX2phuVsuE3C1EPK9+4JtRwHEgjzc9f2NXXf1IOaMhvgXETG9n0xIPifOmy3tjhCCWE41DtTo=,iv:d5B+J/tp/gMES6abMPo9r+qnbs4H0axNJv8AnyjBefk=,tag:0d7BbawxI1JiTV4HNs1oQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    AccessKey: ENC[AES256_GCM,data:LRzcwh2jNB4MS3FN7xmEZQodhzmkaQqY,iv:lmcs1AZCFGEA9FggYtBNBHNlU6EYrhluo9yJ/wD/wIo=,tag:SqZMMZAo+ca4zVQhCwtDTg==,type:str]
    SecretKey: ENC[AES256_GCM,data:EjNYhZZAktYi3yZYnxhsvHGhPmRkU/7z/0FwTy8Iw09c8cBvTi02cGc1CKQ=,iv:yJxTm+7+8FcYFNjigIMkW6THdsS+Vdk0o7IRoJ/H9FQ=,tag:JgKV/ztyD0bZGV57ZatE8Q==,type:str]
    accessKey: ENC[AES256_GCM,data:ffPNVzj96eOhzhcDAtqqJpPcXpUggLnM,iv:S7GoSDl7ux4Qo9Qo1J/+rVB1tqicGx6hQzq9lhdVbYA=,tag:OiRFxafwG3xr0QCVgEwtjQ==,type:str]
    secretKey: ENC[AES256_GCM,data:ddssMI8G/6wjqydSNvzwAFFWsl4MwTtkrxiQuLTN+UmT4POGgJLxvyBk5Dc=,iv:RUuhRTeBhthXxasV25fMN0iijuMh4N4bgP7I+6QdSh4=,tag:14qY9d5nNzL/TB+XVKcRmA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ceph-object-store-credentials
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ1puVEY4cVR2YzFvOHlD
            TkZEdFczaGxoWjQ4SmNsdGUzaCs0aDBBYVd3CkY0eStRL0lYUVBiZ0lDMzcyVUlE
            UGoyYXpVb2JESDNReHVoMVZ3TS9GalEKLS0tIFFpelZib2o0WEhBc25ROFhicW9q
            eS9SaXNsTUkxTHBLaUVLUzZxNEJFaHMKecbPVr5DIE8OzTeJbG1nsHebeifAbKFt
            z8NxOjO/zuDQycJ+UxLJLHlt7U/hOqspN/3K0cZkoRDLJnXcvahrfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ1I3UHB0T09oeXlDUEpK
            S21leU9Fcjl2WWpqb3ZsQWN1MWVtNmh4YUZJCm5FVWpkS1Q4ditFQmp5NnJ1VjVx
            Y3BUTGZiN2I4N0pENVZWeXJwZTEzOGMKLS0tIFdib2FsUkFPY0k4TGw2RDhhcXJt
            VmpoK3RPQWJwOU5LV1JaVk5hdUdpSzgKuLFhNHthyd92OTNeDu+rlDBTZr2IXHD6
            nGvEpl5hnUoLMT2QtlsRk3l3T/bo8EL8KXMotzQm4Fe9QMDHjNpG6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMTVVSmhLenZhdFlMUEVk
            UStDVG1nVTVjOXgxRk14VVFpWGd0NGUyeWhrCnlvSVVPMHY4amhkZWcyRW5ydXYr
            cHkrc0FSSnNqMGFkNGdqVVNGTVpWU0EKLS0tIHowUFV0TEk4aGxoczBVNDRMUHVn
            OWU3QmYxa0p0c1JHei9sc0UvRGlSdHcKXk8Lje6kQu4L9W54tNMNqlVi15CEfnUg
            ezWJjPoNhYT4SOeCpGermrU320beFvDwpOcVsCx7HxEb56CBh6rCJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T00:49:05Z"
    mac: ENC[AES256_GCM,data:lR/ydAx2JY3Y/bJxN1gzJw7CSe2dDPXbcfo8lIyxDQCXNFwwHHq9vd3y9IsLrKvOI7Fmj/RhMWdc5mVYQW11pdHae51OixrE7cCX2phuVsuE3C1EPK9+4JtRwHEgjzc9f2NXXf1IOaMhvgXETG9n0xIPifOmy3tjhCCWE41DtTo=,iv:d5B+J/tp/gMES6abMPo9r+qnbs4H0axNJv8AnyjBefk=,tag:0d7BbawxI1JiTV4HNs1oQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
