apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:JYEps+UbkPoT3HoYF6nuIE2jd2E=,iv:Hb8S7wxKBL/ReJo8OnDqWpKUGEUQNRBgDkPXOsYB0Ig=,tag:pPq3NNAL+2JRKksPffK38Q==,type:str]
    userKey: ENC[AES256_GCM,data:57X1jsVEUJANRgjaIyNwca3gX7Vqsp6R9ZU41TGkQvSeKNHM5dR8VtMoN+XLhq1jBlbVhACSxRg=,iv:IgstPPU6HXgOkgjaEAF9gwLBkKyfwQtdNxws2zXeW9Q=,tag:e1m8tHcBopiFtxbHYqmczA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5K3ZtWWxrTklQSEZNa29m
            WFNlYUxMYmJnZ2ZmaDBUWUU0U2xJQ1NnNW1BCm9Ba3lSUFZuREVQWmVzR0gvb0VN
            cm9WbkZZdzlhNTFzUVRhTjROTlNnWFUKLS0tIG1UOE5qcEdIL1d3SlhPd25KTEJo
            SzB0Qk51R2o4V0FyMFo3U3BtN3F6SFEK53XheYJxK8X12ix8FjHtdb33ynY6mu0g
            8ZxITMruc6pz8XIBGXjU6n55DcnfKHIx6xDTZBmTTF78LWXclSOPbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRd3FtWWZBbEwvd3V1MWdB
            dXA3aTh2OFhBUGJTM252dFJFMkY0bHpTcUI4CnV0S1N1UFQrdUZZQW1YQUdtcFNs
            NFRzYkZjMkpNdDZCTGpwQnU2azA3RWMKLS0tIDkwUGNKTUtQaWJkRGthc3lmRHhD
            cUVVRzdJZWVCdmt0VGxVK01UcE9JdU0K5bhA3rV4MUYxfaNTu4IfI4adaPQF4WCa
            Yo3zZzgjrMhMka/IzEiP4049AozFF/tl2x3yFSXjCoa9jDDzsqoa/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUnQ1OWN4ZCtKU2RoSWQ2
            WVlaaTY3bHA2K0ZFKzJnTWZmUnRnRm5kQmhnCktRZmxyTEZBUTJUN2VyajBWZjJO
            RGZmQnF5U1hqbWZnWWFlTDZFK2lJQkUKLS0tIFI0UlRkQkRlM0VGeHA5Q0xUckph
            UTF0M2tRMW5iODFHRGlYSmN3Y3dWelEKuYOFIbt6Ivj2+WuTtTwM6JyJf/t+DrN5
            YCpksaatKZaaXwJFsAf24s52MbeuWJlmcw1T/BJCPUYss9cBgTlYpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T03:24:46Z"
    mac: ENC[AES256_GCM,data:nowSlkmTBiIKvI9DCfDKFD6dO3wVjlNn6SJf4T71kFcOAN1tmFbH82OhmCpnDicg3ij7JLzBopdaFtnPNOC+iOqqb7cNUZr9Sx6iaKRiIpTPO9LPZsQY7V4+SAWX9cr4/Xrtp0slExF9mGych456nOJIgBjIPSKWP6wduH76cmQ=,iv:0Cl3n/bzC6ok4XyhoU4a5RpXnjVhhVIbWQf/FhR34Mo=,tag:4nNyNnMYA5SbD8DYFj+KzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:0YFVbtuHbc5c+gto3BGNTg==,iv:oKcVn7oWNdQIlx0dZIS8MGN1K05t5tkUSwJ+hCDWPkw=,tag:b/IRS5UTDWSHOQ+cnGm9MA==,type:str]
    username: ENC[AES256_GCM,data:Mx6kWI1Er8r8V9ze,iv:HqVQN66Bdcc9QMBNd60HJcjPfpiZYJoXwAh7BBsqwWY=,tag:DPdpRLC5I8jRv7uJYdjbhg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: smb-export-credentials
    namespace: rook-ceph
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5K3ZtWWxrTklQSEZNa29m
            WFNlYUxMYmJnZ2ZmaDBUWUU0U2xJQ1NnNW1BCm9Ba3lSUFZuREVQWmVzR0gvb0VN
            cm9WbkZZdzlhNTFzUVRhTjROTlNnWFUKLS0tIG1UOE5qcEdIL1d3SlhPd25KTEJo
            SzB0Qk51R2o4V0FyMFo3U3BtN3F6SFEK53XheYJxK8X12ix8FjHtdb33ynY6mu0g
            8ZxITMruc6pz8XIBGXjU6n55DcnfKHIx6xDTZBmTTF78LWXclSOPbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRd3FtWWZBbEwvd3V1MWdB
            dXA3aTh2OFhBUGJTM252dFJFMkY0bHpTcUI4CnV0S1N1UFQrdUZZQW1YQUdtcFNs
            NFRzYkZjMkpNdDZCTGpwQnU2azA3RWMKLS0tIDkwUGNKTUtQaWJkRGthc3lmRHhD
            cUVVRzdJZWVCdmt0VGxVK01UcE9JdU0K5bhA3rV4MUYxfaNTu4IfI4adaPQF4WCa
            Yo3zZzgjrMhMka/IzEiP4049AozFF/tl2x3yFSXjCoa9jDDzsqoa/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUnQ1OWN4ZCtKU2RoSWQ2
            WVlaaTY3bHA2K0ZFKzJnTWZmUnRnRm5kQmhnCktRZmxyTEZBUTJUN2VyajBWZjJO
            RGZmQnF5U1hqbWZnWWFlTDZFK2lJQkUKLS0tIFI0UlRkQkRlM0VGeHA5Q0xUckph
            UTF0M2tRMW5iODFHRGlYSmN3Y3dWelEKuYOFIbt6Ivj2+WuTtTwM6JyJf/t+DrN5
            YCpksaatKZaaXwJFsAf24s52MbeuWJlmcw1T/BJCPUYss9cBgTlYpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T03:24:46Z"
    mac: ENC[AES256_GCM,data:nowSlkmTBiIKvI9DCfDKFD6dO3wVjlNn6SJf4T71kFcOAN1tmFbH82OhmCpnDicg3ij7JLzBopdaFtnPNOC+iOqqb7cNUZr9Sx6iaKRiIpTPO9LPZsQY7V4+SAWX9cr4/Xrtp0slExF9mGych456nOJIgBjIPSKWP6wduH76cmQ=,iv:0Cl3n/bzC6ok4XyhoU4a5RpXnjVhhVIbWQf/FhR34Mo=,tag:4nNyNnMYA5SbD8DYFj+KzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
