apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:wJDtmTgMajHOUNettlYhQDWgvPYLK+kzaLQgDuz+nhJqYFAzEjHcStgi90/gEk8v89YOV96iXrCzweknIdFxzHbu5rbpdF1cX8qF282rv0doHY4ZU1QUCFz31GIW955VaT+E1gieana18bh6Gp3aa+TkQwY3LBFFJa7Vm6hUOVYTl53tUpL6pfbsBXmZIvwUfiseQKW4CaVn8gN8zCJWxLe3sm/VnpLo1s5YSLgSyhcAng5N+Jw4QXtQLACMW3QMU1hGexT6tnRgI1jBDiahs0ifq/o6oJwC5DxnsYYLnKEH5Rxq+gtwKteIP3v8I5vsS8uoXz7ydArM2FUUDdPpgdbjWuVAVDdT+GuNGBP13HNDVd1/iribLbTPgdF5VrfFMnUHdmMhnU00B26j+VZh7WEq8oLTXJy0RsAZPonT4RKhMo8gyaF50Dq77CvsnA7KJ76/VCvSz1wouiwE2gyjTBVNvyS351DZUlGwe1hKNXbWMu9m7RCxKneQZqBjO3xjMqbtfJSbLn7GQrFsfdMGWbkrK2ZEzRSeKT78VFORaONNkCahw3239QsDfnUTsEvQtH0RHr/6jPEGY8dRNf7ZZqwj8bMpzC08nrFJqrApa82/e+x2dYIihgMXHhl8UUmgCWZ72zeiK0HcUXDJVDIop/lYAJDh80+ttLjLiSGsb88kK6Xl5dlTlh5zwf7s/Wk2dgSfETLYrHBULgSNqSVtY6w31Us4b80NJppBz8Bjd/AEe+K6xTyzlxzVpecWJ/P9dfbVNy0HjEBtqg==,iv:mhmQCXv846oDQnxxpKX92aHH6dYfZkhhV3ieQlAcvH8=,tag:s5vNX/5bDUUPdU9CVJfRZA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-smb-export-config
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZWJGbm5UOCs4VjdnSmVl
            SnVOOUhsZTlyWTlreEpYWUZLUEc4UUZYMXg0CkZnY1gwM0dZeUIwZTBIYzV0a2Iy
            TXNqQzdiN0ZMWjUwdjBMZnJUWkZxWU0KLS0tIHpyai9lNTBENUtXTHdMSkdNL2Zr
            SGIxRFd2Y0l0OFJWWEU3QWhVZHc3UEEKsd10b1M9KYOyksEmNcJgnVN+9eH4p8hg
            TUvqFehpxP4OK3OOyXuIV8O8c4w4lySLyaxlOkbyY7O6YjunIwaZkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBob3huVnFxMGhmOHROSE9i
            VS9wOU05Z09LNlA4R1NvM1ZEakg5MzE2UFhZCkMzMWNKaE1CcktlSXRrUndUbFZR
            d0wvZ3BJRkJDTW9LS1k2SlBoUjJrK0UKLS0tIDlGeFhBVk43cmh1bW1idEU3Z1pq
            enNmaDRwU2tlQWtPbGsvQzlsUERWU3cKcUBUzUR1Mymu5/u0WCyw4Bc33ofTrNoo
            Rtcob1+cir+giLiIuH9+O6L5wfncstDTRiZMubujaR6GW5hgvA3NsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVmlreFdEeHdUald2Z2dW
            dGd2ZXFvRnNZdDdvMHJHV1NsYVJ3ODFaQmxzCmdKTmVxNHlWWU9iZ0xIcjBVWjZL
            SXdTRnBCYnhnbkEzK09oMUJRUlpXRDgKLS0tIGxNNUJXajRLbFFtQXIzY2Z0UThh
            RGtpcEkxeFQ2ckpXUjcrWDZFRXNBUUEKE/wtCRHg8j+VC9a1wgdeI2NtgiuNluKT
            AWhCK0sudoLR4rbiFdFm2wf/ggcF0dpnExfs9rSkZtKriMpzhLL7eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T14:40:29Z"
    mac: ENC[AES256_GCM,data:QCSfh1vLg+vcgCqLPE0XfPrczm0emVCO6TueeFObrkI2QwyqleX+q/AuFP5NK1TPCxSafpqdYc+RTXUCDdStM5H8goz521G+Ac6wWS5BtujVyVMsa4lLqRfeX10X0nVjpbtT2cx68IuEVQSk6ROk2T4G3AijNluoG080b+aJLkI=,iv:L5L4L4cO7/IveabRTFi3Zv7IK6/rWk6EnWHrMfuzmuQ=,tag:f6bDrvcdXpFI7K2lyO9NJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:bqypHOfecCU7REOzW2EnUwFDj8I=,iv:B7K+dQdQgK2VNORPJeINSf3IrrxwmVl5ZoqpioHcABk=,tag:LEMO0FwM858yF6tsUY7dHg==,type:str]
    userKey: ENC[AES256_GCM,data:PINtGXF2ebNcEnU+F9QgxZmnUHE62bB39N1BcU5+rKpjrS5cfXVO4TfFBMTZr28R2Tx3GfdP90c=,iv:bI0M1KQrjP/6x7PZ0S95o5GgXx0Fi3o4arhraMtBrfs=,tag:mxVlETA7p7Pk2u9bmHssSQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZWJGbm5UOCs4VjdnSmVl
            SnVOOUhsZTlyWTlreEpYWUZLUEc4UUZYMXg0CkZnY1gwM0dZeUIwZTBIYzV0a2Iy
            TXNqQzdiN0ZMWjUwdjBMZnJUWkZxWU0KLS0tIHpyai9lNTBENUtXTHdMSkdNL2Zr
            SGIxRFd2Y0l0OFJWWEU3QWhVZHc3UEEKsd10b1M9KYOyksEmNcJgnVN+9eH4p8hg
            TUvqFehpxP4OK3OOyXuIV8O8c4w4lySLyaxlOkbyY7O6YjunIwaZkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBob3huVnFxMGhmOHROSE9i
            VS9wOU05Z09LNlA4R1NvM1ZEakg5MzE2UFhZCkMzMWNKaE1CcktlSXRrUndUbFZR
            d0wvZ3BJRkJDTW9LS1k2SlBoUjJrK0UKLS0tIDlGeFhBVk43cmh1bW1idEU3Z1pq
            enNmaDRwU2tlQWtPbGsvQzlsUERWU3cKcUBUzUR1Mymu5/u0WCyw4Bc33ofTrNoo
            Rtcob1+cir+giLiIuH9+O6L5wfncstDTRiZMubujaR6GW5hgvA3NsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVmlreFdEeHdUald2Z2dW
            dGd2ZXFvRnNZdDdvMHJHV1NsYVJ3ODFaQmxzCmdKTmVxNHlWWU9iZ0xIcjBVWjZL
            SXdTRnBCYnhnbkEzK09oMUJRUlpXRDgKLS0tIGxNNUJXajRLbFFtQXIzY2Z0UThh
            RGtpcEkxeFQ2ckpXUjcrWDZFRXNBUUEKE/wtCRHg8j+VC9a1wgdeI2NtgiuNluKT
            AWhCK0sudoLR4rbiFdFm2wf/ggcF0dpnExfs9rSkZtKriMpzhLL7eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T14:40:29Z"
    mac: ENC[AES256_GCM,data:QCSfh1vLg+vcgCqLPE0XfPrczm0emVCO6TueeFObrkI2QwyqleX+q/AuFP5NK1TPCxSafpqdYc+RTXUCDdStM5H8goz521G+Ac6wWS5BtujVyVMsa4lLqRfeX10X0nVjpbtT2cx68IuEVQSk6ROk2T4G3AijNluoG080b+aJLkI=,iv:L5L4L4cO7/IveabRTFi3Zv7IK6/rWk6EnWHrMfuzmuQ=,tag:f6bDrvcdXpFI7K2lyO9NJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
