apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:pyCI9/0NpZAt6xAj21bSrK83Bfg9vtqkYq8U8QvxO0LPs3sg5f+4Gai9qgoWT4WAQJleCbsHCRd7H7hSTjESgo2dWeXLAqumfk3cAz7GyQyE1II2WUmndFOJxgvwyrGr0+wccQBaPMYoDAq0laX8t3W2Kbz6S9rfr9dMB2ch6cH+zTRzfcxfNA42oGSVvxFu5FMj72gHdSnWkuEKV4FczYaxy/r4rIKO0ojbJC/Mlse4wiDraCjMR8oGOEKIXC74CapuzOIc69RWYUgjCmkFk8t/TFF9n0j0vA6x6pjF0nkzpVTAzNvlJ4gwYF7AjkUeCSJvEDUCWBRRxJVC+2X5dlQ4to8RhPZyI6vyptb9nfejqHO5IYPXySQ+9hzszapV6ywQINp+Jxa51wIANzVvmkUXBDN0iKZeSy4wD7+CthNh2iefz9D8fjaxvFDqLIru61LbJu3j+At1/dOW2lO35W3araMfcjFb8JTGzPYYUWSL3UgWE6BhkoNT74YP3G4wEpfjSSbduRIEil9N8tfMCxRf1zTDS5moJLsrWiMlnT9p/L7kmi2FhOgpC+InFVmgncuv/QYDUjlW5iaXAhz9qO/lOgMKvAkpMNcloFkn8++ihGOVk5qKcinYxgclvg0XJA3xC9LXjE7Fd2ljk67/Txan37xgTezfsNO570zUl8fuVtuONKVs+AYnaHiKxtU82SlqpfCXo9VJeQZHaIhgVdcwNV/Jq7eGkF2yMlWRHzDe6EAKs/xFTrT5aTu5YO/Q463az5JmopY=,iv:7Hrj2Ucm7oH69+aYI6vHd7/sOJEw2LHQECBXJr03IbQ=,tag:9nKRZtcFoks9YdkABe21fg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-smb-export-config
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcTFiNXE1OUM3S0pUejAv
            a09mL1RUWk03SXdwSEdMcHRDL0p4SXkySzFrCnhiWGQ3bExYYm9RRGI5a3Q3Z1py
            Mk4yeWhmWTJ2OFFuZGkrVHkvUkk1MkEKLS0tIFBxemRQZFFtQ3BCRlo2UHZQNSsz
            ejZGbk04MTVMWUt2cG0xbFRHaERFd0EKhjzT6PPUMo4bhdaMgKKrEeu6QxNCwnre
            ugrwaR5n3wzJ2WMR4v5ejQCyNMuN2Lj3GdQCaFvHMMZCVxv8H0KYSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUmV0M0praCtwRDRnVjhC
            ei8zeFl1ZVJSUGZnSFJsMFVRM0dLbEx6SlVzCnFSTTNwZ3dNREY0Z2w2SWVnd2FO
            cGU5R3JJMnJpYitLdmlyaExqemYyWkEKLS0tIFRiVlVWVVQ0eTVUVTVKZytZd2RY
            eFZ4ZG1nb2dvZUNWWEp0NFNETkhmL3cKFUImiIn6VLRadjEG/uB4Z0/MsyMbWiml
            NtsKoGZbE7cZDG1Jkuiw4lIqrGajSC1lVGSEW6wV73QdI3R/wPFD5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUE9BZHRCek1NZ0w2M293
            Z3gvM3pyMVI0UHJZVkp5d05ZWGVXcFhjZlhBCkZlV09KRHM2STN5SEcyQkVVa2VG
            emRHOWpuTG9MejVCZmZCRzZybkUwaXcKLS0tIGVTaXptWmlDZjltN0xVWlNUYVo2
            ajc1Wi9qa2xQaHBHRzNTV0hONXVVY2sKH1sEjDHRvsPjQpX+zwRO2Hao0HTAsbl4
            1iiPDaqL4wZPYZqzrVYqh3/IzLMqgQiKZUUo6+qOY1tJq4RnisNn2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T14:58:07Z"
    mac: ENC[AES256_GCM,data:qZ3rWvj/BsgjVmCG28GVyw5WQRjT/J5zF2wgS+zmd/6sKcy86XlRSEfo/SPRlJ7XGm0QwYBX77Rwh6AYGLlICVFtkLjfIXtLgIt8cM/bGehq2YOaVx35kGivc1iPDwjsjBAGG9oQ7UTMkbIKqhUOpl4V/41QG3pIX1MfKRVPCDs=,iv:swS9laTvaJG1HMWRBw07hG9hsN0yL7xcAHU7/Xb+7C4=,tag:5Kc7MpWIEMZvk22f+rHjlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:VqZy2iTai69KpB8tUD/VpHk5drw=,iv:FIF0lHThvMe04sWPN5rmaAGlIyIlflm6IxJC/A8erm8=,tag:0sLrA6zkEPRVRRXcXGNwNw==,type:str]
    userKey: ENC[AES256_GCM,data:efdQfUJacK9Ihvh6QHc6RSAvoqgMmttkYg4vWmNE4dtMNzEyKvstlkDJXacxU7dUWo1/yRHInbM=,iv:j7KJCxuYNxKYWlO7j2j/TB7kzQBTxe/GXeEYY1wn+0g=,tag:YeWtYIJR0IMgLqWFbbUgcg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcTFiNXE1OUM3S0pUejAv
            a09mL1RUWk03SXdwSEdMcHRDL0p4SXkySzFrCnhiWGQ3bExYYm9RRGI5a3Q3Z1py
            Mk4yeWhmWTJ2OFFuZGkrVHkvUkk1MkEKLS0tIFBxemRQZFFtQ3BCRlo2UHZQNSsz
            ejZGbk04MTVMWUt2cG0xbFRHaERFd0EKhjzT6PPUMo4bhdaMgKKrEeu6QxNCwnre
            ugrwaR5n3wzJ2WMR4v5ejQCyNMuN2Lj3GdQCaFvHMMZCVxv8H0KYSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUmV0M0praCtwRDRnVjhC
            ei8zeFl1ZVJSUGZnSFJsMFVRM0dLbEx6SlVzCnFSTTNwZ3dNREY0Z2w2SWVnd2FO
            cGU5R3JJMnJpYitLdmlyaExqemYyWkEKLS0tIFRiVlVWVVQ0eTVUVTVKZytZd2RY
            eFZ4ZG1nb2dvZUNWWEp0NFNETkhmL3cKFUImiIn6VLRadjEG/uB4Z0/MsyMbWiml
            NtsKoGZbE7cZDG1Jkuiw4lIqrGajSC1lVGSEW6wV73QdI3R/wPFD5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUE9BZHRCek1NZ0w2M293
            Z3gvM3pyMVI0UHJZVkp5d05ZWGVXcFhjZlhBCkZlV09KRHM2STN5SEcyQkVVa2VG
            emRHOWpuTG9MejVCZmZCRzZybkUwaXcKLS0tIGVTaXptWmlDZjltN0xVWlNUYVo2
            ajc1Wi9qa2xQaHBHRzNTV0hONXVVY2sKH1sEjDHRvsPjQpX+zwRO2Hao0HTAsbl4
            1iiPDaqL4wZPYZqzrVYqh3/IzLMqgQiKZUUo6+qOY1tJq4RnisNn2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T14:58:07Z"
    mac: ENC[AES256_GCM,data:qZ3rWvj/BsgjVmCG28GVyw5WQRjT/J5zF2wgS+zmd/6sKcy86XlRSEfo/SPRlJ7XGm0QwYBX77Rwh6AYGLlICVFtkLjfIXtLgIt8cM/bGehq2YOaVx35kGivc1iPDwjsjBAGG9oQ7UTMkbIKqhUOpl4V/41QG3pIX1MfKRVPCDs=,iv:swS9laTvaJG1HMWRBw07hG9hsN0yL7xcAHU7/Xb+7C4=,tag:5Kc7MpWIEMZvk22f+rHjlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
