apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
stringData:
    userID: ENC[AES256_GCM,data:VQl5FoeppV1oIA==,iv:3j+1aLN7Aq4y89FroU9yjRy+MMwTydzspGVlU5tcyFw=,tag:VGZvb+5hUHe7H/crE7F1EA==,type:str]
    userKey: ENC[AES256_GCM,data:4EB98RHZtxpLOZ9fFdRmnemiZ3fqu49yuuRnMHHawnZY9Er6P1RKMA==,iv:MYownLyOaxYxehiKEYX3724x65EpVI2AJXsS+/gdZZw=,tag:ZDNHEOUf/7RGkdOKrAIWow==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5S2tUcWVYMUFYRlhQSlBh
            NWR4U2VHVFJpT0wramh2azl6Tm9QWHFmd0hrCmZLS2NlM210dHd2d2VwUTI4TlJi
            MEZ3bmJJS0Zub1pyVWs4bU9qVGVrWk0KLS0tIGtrTjNjck5MeG4rYmhzZHpCMnVM
            KzFFOEczQ0QwTnNoUEplV05NdXdHRmMKDXBW/eBW0hjIvA/9tuwqvVe/RNOxa1ws
            uI9AMInT6UwHNo5LS74Qa8PYkS3cP0bQbe2mEEZbqq8Rcr9jmugVkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MDliY3dTWGRZUVJlMGh4
            M2J3RFZDTUtrUFhkZUx0UGZYOTVzS20xTHdNCm54RjNnWkpnaHUzY3ZodmVieEds
            QUVETWZBOUYvRzhkc0xSVmYxOXBINTgKLS0tIHZMbVVwMENrQ0hPcGM2M2RvQkNW
            RlhPNWlVM1R3YlJsaDVDQWtESnpFVVEKDvhVyUuQxxk03s1sHEJRGDRgqkJVcQoC
            OMR7pU+dTi6dE0Pn4lMGsDtuEWTij8xBz3BzSLv2XqBJqg9btol9JA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZW5kZnZiRlppZ1MxR2Rm
            Tm56WTROaG5rY00vRTdiTG5HOUl5aGJhNmkwCm11dnhTM2RjaWNtTFNmcGZSMjRv
            ckk4YXpMVTVWSHFVYlB6NEFPaHJFREUKLS0tIE5VVzVVaGJDVzE2NGRXREtXSVRP
            R0JsTW5oNUNWdzE1NVVHUEZkbXNYSncKokMaGo7pwUhfzzVr/khQkqsvIaEpYkem
            oQw6tT21iZrpd9kk5nG9ES5s3Uox3PDUGGIGLkmZZxTKxJXusFuNTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T20:20:29Z"
    mac: ENC[AES256_GCM,data:KAwZLiAEUQsP/NcXYuP7+qrkya0AWQsYdJBaJIUHi27BnmUFdjoMMrpuOnK2DMs7bq7W8+eZ/Dkv96CIug4XyVd4geePMSwCMBdRlzmRN4TyGx3DIGheEqS7cnu/VFGiYbtRE80AdQdvweBwPg4j7A9ZwfZsIjs7w4CU8xsgvPc=,iv:nIZgYu0qaDkCkwpCS6hgD8+zKaSzfXE4WYXhIyBv56M=,tag:J2qCY5JOLoJfEoMJTtmAvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:cnOiHzMV987Fh6y+ZpEgug==,iv:cnxBje1Dh6ylFP9HsSR97K5bt1sWx5QUOwsi0ogRYWs=,tag:Kh6xrrwEeGkUbjZPWDbmCw==,type:str]
    username: ENC[AES256_GCM,data:HFlG2AX8VfgkLOrq,iv:8MVYhrAgM194pyTZmj9OOybtOtv5AVxnejo0zXbApMw=,tag:w4r8EwLydi2VMYtfwrYUTw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: smb-export-credentials
    namespace: rook-ceph
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5S2tUcWVYMUFYRlhQSlBh
            NWR4U2VHVFJpT0wramh2azl6Tm9QWHFmd0hrCmZLS2NlM210dHd2d2VwUTI4TlJi
            MEZ3bmJJS0Zub1pyVWs4bU9qVGVrWk0KLS0tIGtrTjNjck5MeG4rYmhzZHpCMnVM
            KzFFOEczQ0QwTnNoUEplV05NdXdHRmMKDXBW/eBW0hjIvA/9tuwqvVe/RNOxa1ws
            uI9AMInT6UwHNo5LS74Qa8PYkS3cP0bQbe2mEEZbqq8Rcr9jmugVkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MDliY3dTWGRZUVJlMGh4
            M2J3RFZDTUtrUFhkZUx0UGZYOTVzS20xTHdNCm54RjNnWkpnaHUzY3ZodmVieEds
            QUVETWZBOUYvRzhkc0xSVmYxOXBINTgKLS0tIHZMbVVwMENrQ0hPcGM2M2RvQkNW
            RlhPNWlVM1R3YlJsaDVDQWtESnpFVVEKDvhVyUuQxxk03s1sHEJRGDRgqkJVcQoC
            OMR7pU+dTi6dE0Pn4lMGsDtuEWTij8xBz3BzSLv2XqBJqg9btol9JA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZW5kZnZiRlppZ1MxR2Rm
            Tm56WTROaG5rY00vRTdiTG5HOUl5aGJhNmkwCm11dnhTM2RjaWNtTFNmcGZSMjRv
            ckk4YXpMVTVWSHFVYlB6NEFPaHJFREUKLS0tIE5VVzVVaGJDVzE2NGRXREtXSVRP
            R0JsTW5oNUNWdzE1NVVHUEZkbXNYSncKokMaGo7pwUhfzzVr/khQkqsvIaEpYkem
            oQw6tT21iZrpd9kk5nG9ES5s3Uox3PDUGGIGLkmZZxTKxJXusFuNTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T20:20:29Z"
    mac: ENC[AES256_GCM,data:KAwZLiAEUQsP/NcXYuP7+qrkya0AWQsYdJBaJIUHi27BnmUFdjoMMrpuOnK2DMs7bq7W8+eZ/Dkv96CIug4XyVd4geePMSwCMBdRlzmRN4TyGx3DIGheEqS7cnu/VFGiYbtRE80AdQdvweBwPg4j7A9ZwfZsIjs7w4CU8xsgvPc=,iv:nIZgYu0qaDkCkwpCS6hgD8+zKaSzfXE4WYXhIyBv56M=,tag:J2qCY5JOLoJfEoMJTtmAvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
