apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
stringData:
    userID: ENC[AES256_GCM,data:TFn+rbkjwP1F3+ekPY6OpA==,iv:f1jezewsIL/XXm4dE/Jzb/EGTb/jKeeISJpa1lh2oTI=,tag:80PZ3NV+JOribmZ7Fvnb6g==,type:str]
    userKey: ENC[AES256_GCM,data:3MV5QPrQ2bUBjgUpwFaCoVEb6npw3Sk1WXtmM8WmzR3tc3fbFllbG7mPWi7xRXp2MlBKi2sl7dw=,iv:PF2T9mlxOxUrOjYQ5ViWcsr5Ujpq+6c2+2k1qrs535w=,tag:Q9EB5llWk6Dn04fimBGCTg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQ0ozZlR4cFFKcERtNXU0
            NXFsdUhMU0VISjVaUTkvOWNyOFpRbkRIQVJZCm56N1hLM3lCMngraEVLSk1VdFp6
            b2UzOFk5YkdMaXpZeEYxai90QWFtem8KLS0tIFppZG13T0JUR01jeDBEbmswRXJB
            djkyV3cyTEdDL2prMXpGeklLYUF6SW8KDn1gouTKBPnf14XIOlHa/0bFMBpzKRDm
            1E+1wrH4ynyb/ELZRlL+uDo4+dIBMD2WYh/XB8pXHqydEG6wNrRBXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySEdaMEFRYkk5Y095SUJY
            cXIzWnNBSTV2aDJtZm9YWm1LbHcwMUJqMHdzCmZFRzY3RzBrQm1Iek1UTy9SOEc1
            N0J2WnJtQzlnbjEyTVlXeXYyaWcwakkKLS0tIGEyUkQzQ0VxenpsYVRNTGg2bWY2
            aGFVZENqdE9Lc2ROSGVTbUdWMHJjRVUKQs/2ckGIZLog04eVCZ046B+PVkbTUY8D
            Yzub7n6Ilytfah8GQ8DBdvBvDzE6qqI+bx2phBqqRGZ7icOLZYfzEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaVZoUE5oQWJTSCtGSm43
            b05SVzRsYlJvMklIa3dMbVpsUDZPU1V2VEJVCmVUTm9WZ3dUQXhtMDQ2cnhheW0w
            Zkk1SE1lNUZsS2ZXQUhrVzJMOEIrOE0KLS0tIE9Zb0Ixbm5jL3AxYWdzMzhGZWU3
            RG1uQUxQQVlrbXJwNU1QbDV6bldTM2cK8w/tlcsIiJHRmoO9sga5uht2g45qcsj9
            Y2lDzlDXKiFZqj/gWgx8xr9kO9GHamWdyCzDv+fxAhk6a7kXsRvrww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T19:57:11Z"
    mac: ENC[AES256_GCM,data:7qhA9Ks4DW9mWU3LpT6htCvxLqWTrHholP5RZI6EO0PexjX7NIDsA77CsTlx82bZx31Penyw+S/SkzBgYTKwhvF0SRAWZVHDbXRbCI/QQa7HmQHDFYQ+QD8nslIzbjNvCVBHAYJb83TlCCf9NMEEKIxHDL928Wpac76pcoU6qz4=,iv:DP3+qYGWRSkETI5Yu90+nkBK9asSp7ggTpnf02qSkOE=,tag:gyaUqiwHxPCTsBpDQOckAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:5UkexiZKEeZs0ACHifVwkQ==,iv:+x8JR+f2b85cPeLGTK8uQDTcJEQlShgwnJM/8LGNvO4=,tag:0YeduNZZKqB4RvL75AtMbw==,type:str]
    username: ENC[AES256_GCM,data:kU+otDxKvXuGkiBe,iv:2ajC7gouQ/aIgoFAOAQPg6Rww+HUIMw3VDA/hTmylKk=,tag:5FkiX0O8fwIUVtUBtiObLw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: smb-export-credentials
    namespace: rook-ceph
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQ0ozZlR4cFFKcERtNXU0
            NXFsdUhMU0VISjVaUTkvOWNyOFpRbkRIQVJZCm56N1hLM3lCMngraEVLSk1VdFp6
            b2UzOFk5YkdMaXpZeEYxai90QWFtem8KLS0tIFppZG13T0JUR01jeDBEbmswRXJB
            djkyV3cyTEdDL2prMXpGeklLYUF6SW8KDn1gouTKBPnf14XIOlHa/0bFMBpzKRDm
            1E+1wrH4ynyb/ELZRlL+uDo4+dIBMD2WYh/XB8pXHqydEG6wNrRBXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySEdaMEFRYkk5Y095SUJY
            cXIzWnNBSTV2aDJtZm9YWm1LbHcwMUJqMHdzCmZFRzY3RzBrQm1Iek1UTy9SOEc1
            N0J2WnJtQzlnbjEyTVlXeXYyaWcwakkKLS0tIGEyUkQzQ0VxenpsYVRNTGg2bWY2
            aGFVZENqdE9Lc2ROSGVTbUdWMHJjRVUKQs/2ckGIZLog04eVCZ046B+PVkbTUY8D
            Yzub7n6Ilytfah8GQ8DBdvBvDzE6qqI+bx2phBqqRGZ7icOLZYfzEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaVZoUE5oQWJTSCtGSm43
            b05SVzRsYlJvMklIa3dMbVpsUDZPU1V2VEJVCmVUTm9WZ3dUQXhtMDQ2cnhheW0w
            Zkk1SE1lNUZsS2ZXQUhrVzJMOEIrOE0KLS0tIE9Zb0Ixbm5jL3AxYWdzMzhGZWU3
            RG1uQUxQQVlrbXJwNU1QbDV6bldTM2cK8w/tlcsIiJHRmoO9sga5uht2g45qcsj9
            Y2lDzlDXKiFZqj/gWgx8xr9kO9GHamWdyCzDv+fxAhk6a7kXsRvrww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T19:57:11Z"
    mac: ENC[AES256_GCM,data:7qhA9Ks4DW9mWU3LpT6htCvxLqWTrHholP5RZI6EO0PexjX7NIDsA77CsTlx82bZx31Penyw+S/SkzBgYTKwhvF0SRAWZVHDbXRbCI/QQa7HmQHDFYQ+QD8nslIzbjNvCVBHAYJb83TlCCf9NMEEKIxHDL928Wpac76pcoU6qz4=,iv:DP3+qYGWRSkETI5Yu90+nkBK9asSp7ggTpnf02qSkOE=,tag:gyaUqiwHxPCTsBpDQOckAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
