apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:hbV3GrPuPStBsd+bMGo3mmIkq+ISE5eGhh+GTI5iEL5V1G/ONQ8rhtzZvkVyJwC6bgX2iHyRo15fOhAMpdBsthJXcwtlNsJ+E9GgBSz0CctuOTiejwdtWBzMGIWSOk8oTbuXgDKM1YR+lucOIN1Ru8Eq//KTo9kUFPjYRk84RQWoM7PZyNHMesa9Dg9TVuYkxtCZDjXxImVGHQJsE/vGFEI8p3t7pK3iL3ZwdrFjXXWIq4T9KbvnM/kjG4t/OosE76t/QjFVkcpUPU6k6M5r+OBoc82007/OaNhL6HjvYL8gBxRQb11jgaAVwUGtu2BCDjls2KbbgMfgq2iFpDquBNq6A2siWJbw9ws8hoUKWYDoiV42Yw9V58kRPBcA+YKizeR2tzpov3AUuUlM+3HIydXvxIoN/L+amtezWQeMO78/YxwmtWopxjiO4+wdlRMgpZ7h0UIu7vned5NoyLm1GgODrZkUDsGnbpLmhoIf8uLtJAEzE2zwRqdFaTP5VlBN9JbXXYTy23kpp1SkrJreUyrxtRNGJ03dIlJE69DaDE8RaocfbTi9zua4ZIaL5onIF9a/Rq/70DWzge3I4jN0MgSSoJEltYqJ65Xyh1KmekrmcnCo9YjFdt1VzTTPUmzPwHpeN7xbJd0I1e4QWzxn5m6IaUihuBzQ+8cL2V1ffodUVHEpidfcTHQ8xsemhLgThsChbOf/k/70szOJFIsi6m/M1qF4GcvnkhMdhJaagrSUwwWpgVw7sKY5cz460LOB8LVa6/AymmoPyAz+gPWCeQxVK/M=,iv:sXJezE3DSfms7HTyT5ryWBiHeh6nm1ANDbmJM0UQwxg=,tag:ljyTgqPkeh1ePFrOb7eNvA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-smb-export-config
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMytlUk1LeUd3bHFMNEl5
            aXpDU0ppQkd1d1R6L0Y1a0lqNGp2SUd2SW13CjNMclJLYjB5RTMwOURpazZISFJn
            b1VvVklyRGFhVS9uUVpJWGRnQWkyMlUKLS0tIHI2ZXB3RWw4N1djalJjSXRNM1BE
            S25wUUNoVnBFa1phM1R4SFAxRVRtRk0KEvPyW7xblpNtf+l+XDGeO1O+mTnvAZRK
            VWGFzAPEcxhlKe4gmW6oFTmV2uETeEOxvXM/pYgo76ax0Nyi/aZJSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YUhFVlJON3Z1TnVTU21F
            Sk93ZkVKL0k1dEFZQ1ZkN3pRYUFJUCtxdmtnCjBUTjlUbWVYaHFqQjVUdXpyTEFP
            bTdxdjJEVm9kTEVkb08vYTZ0NDRlQTAKLS0tIEVGZmNRbEtMN0ZGV2xZSFRaY3h3
            dzVEVU42eE5obHhmY01GM05JekRMQ3cKDnJNJVhuArD9K8JGqqY8UUUuRSz+rSn5
            xJhW/yWluQ7F8F+93sivHo9G0qTbaSwVdKDZuVaRQ2TSSYnJ71gs+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSnlsdkJOS0ZCUElPZUh3
            OWJnVGpIWXBmVjAyTnVQTzRjVFQyZlNRbkd3CnZEcnFvM2wrZVJENktwbHNsZ1NK
            MHpPY2VLQVBKZG5DVDF0Rkxqc3NaVkEKLS0tIGt0VXR0UUErS0ZFUzVTUkpsYU5k
            NjNCTUJycTdvVmlYOWRKWi8xTWY4NHcKTNpgSrFImePFDbbN77SbY596Z+I71QhG
            QE61FXq9taCxR1hvYAg2NgTBC31SEdIEwCjCyVDbOOKZ1R1hUGdRNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T16:11:09Z"
    mac: ENC[AES256_GCM,data:KB0IJYUYeVXDSdOXOTLOPLPV69j1MUen5iS5iUT4Rc3d4bWbsohSrOpCtlRlTM1+WFTABMhhL93Eulwr/n67f9LwLg/WUqwsJx9L6Djt/ZbrFrFUWsyWZ3dWlLl7X/elIVvfP1Y3gptj69/u2mcH8ITYjTl6E3N2PpYT4e0WQZU=,iv:/+dhqfuD+GXL5skA275UTk4M3FaymAMx+l2RAfQZvBk=,tag:oRlkwCK7E0MpFFs+qPAx4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:Mh7Gum2YcJaofysVsurciKHDuhc=,iv:OAu68j902pdtuHtHh2ddG5JdB0rwrNpaXRw5LwbQ1xo=,tag:V9UIymsP45thxidORAuGvg==,type:str]
    userKey: ENC[AES256_GCM,data:g88kEWGfvzsNK7s8/QBg6BLYmEkAZ69bNLad/8tYC01MRscqY21+tCX0FJGVjvX6g13T4UkTFDE=,iv:kRnSMo9HwVLZXNZD/5ylmwBeQXhqHGwOI2cape7qIcg=,tag:DGyCxqD+HBg6/QDT7yJi4Q==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMytlUk1LeUd3bHFMNEl5
            aXpDU0ppQkd1d1R6L0Y1a0lqNGp2SUd2SW13CjNMclJLYjB5RTMwOURpazZISFJn
            b1VvVklyRGFhVS9uUVpJWGRnQWkyMlUKLS0tIHI2ZXB3RWw4N1djalJjSXRNM1BE
            S25wUUNoVnBFa1phM1R4SFAxRVRtRk0KEvPyW7xblpNtf+l+XDGeO1O+mTnvAZRK
            VWGFzAPEcxhlKe4gmW6oFTmV2uETeEOxvXM/pYgo76ax0Nyi/aZJSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YUhFVlJON3Z1TnVTU21F
            Sk93ZkVKL0k1dEFZQ1ZkN3pRYUFJUCtxdmtnCjBUTjlUbWVYaHFqQjVUdXpyTEFP
            bTdxdjJEVm9kTEVkb08vYTZ0NDRlQTAKLS0tIEVGZmNRbEtMN0ZGV2xZSFRaY3h3
            dzVEVU42eE5obHhmY01GM05JekRMQ3cKDnJNJVhuArD9K8JGqqY8UUUuRSz+rSn5
            xJhW/yWluQ7F8F+93sivHo9G0qTbaSwVdKDZuVaRQ2TSSYnJ71gs+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSnlsdkJOS0ZCUElPZUh3
            OWJnVGpIWXBmVjAyTnVQTzRjVFQyZlNRbkd3CnZEcnFvM2wrZVJENktwbHNsZ1NK
            MHpPY2VLQVBKZG5DVDF0Rkxqc3NaVkEKLS0tIGt0VXR0UUErS0ZFUzVTUkpsYU5k
            NjNCTUJycTdvVmlYOWRKWi8xTWY4NHcKTNpgSrFImePFDbbN77SbY596Z+I71QhG
            QE61FXq9taCxR1hvYAg2NgTBC31SEdIEwCjCyVDbOOKZ1R1hUGdRNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T16:11:09Z"
    mac: ENC[AES256_GCM,data:KB0IJYUYeVXDSdOXOTLOPLPV69j1MUen5iS5iUT4Rc3d4bWbsohSrOpCtlRlTM1+WFTABMhhL93Eulwr/n67f9LwLg/WUqwsJx9L6Djt/ZbrFrFUWsyWZ3dWlLl7X/elIVvfP1Y3gptj69/u2mcH8ITYjTl6E3N2PpYT4e0WQZU=,iv:/+dhqfuD+GXL5skA275UTk4M3FaymAMx+l2RAfQZvBk=,tag:oRlkwCK7E0MpFFs+qPAx4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
