apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:rbpSytWmJLCkMwLGSoFx/yBeJ/xkH4Ep+uFfc0B5CAH9umQ9aIN1QJnn/4V/QaqCh7DfdHlPiUgFON5KApwic0WI7/Bb28T9ylPoUOeent85xeAX7ZWj+Ld9MAfdfPtQlrh8htqdmr+lZwDMiatWkNnGoj/5G4gxPirKwgwCPshkh2uCNlbKYzMFtswKfW4wp1/3PX6HtqPWesj5zilbPmONbX7uS30atY6QjLKK6UQnS1sRzJ+iMeC7Bgh1LOiVRv2FxmRJdujOy60DbIIIvKBfo5Q2vBmOEs8ATaXze1ejQYUVO4e98QWq3zhZaY0xe0dvdtPdVOXK3b5XHJ7zN8W/DxMpqDathNicoL7Kcwgu4Xj3V+btLUwJ4ozcc7WdZs2WWgOMNZsermd+wfu+kgxoY7VWEk6juz+26qaYKN9HzYtU4V3dPlCllRVBzmdxMVvOb4d7dH2ZRejXo+PICef+1Bd4ylNhMCnYZEaig5soyxDWcP1M7k5fxdbrpkBQDoALsBVXZLww3LJFOaXf5/VWy2dhIztJqrCiEvDgsHn9PNEkhAn3KM4LOnE8Y0f2wAONLW3Hsv6hG9fRektZvwy5927oJKJUMxWK7mxo/KVQPktOKiWMCBGdVb+0qCXl2GRYaEl7XrwDRfeYDJNxaT+Snf9Aach2q5xTHxjumNRFPwgmFFfCiDCfkuRhrvK4P5TiHHakGJkZztq9itbvGSLdfpO1V46pq6eUcMdf/LP5sGFPcm0ljecBDtDNNDizvR2zLg1+2LAN54oQDEodGwKK0cNZlizFiBQZnv93JN2t5Vw4I/0Qoz1PLYDrpW7Sgp7T/O0YPbLA8o4xkjN5,iv:Id8jYw6DFVgpT4nnoILFQ3jmdBSn2yadcz1hvOdfD9U=,tag:cnXzuvpoJUA96hPrYNg2mA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-smb-export-config
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUXJ2bmx3dXpqZWdleUcr
            WXg5ekIzbjI4Q1FDb1VRNDFKbzBwenhEWGo4Ck9HSE9oblkwZ3N1dnI4SXI1UUhr
            ODBwMEtLVGN5bHBFcG5IeHRiZTFsRG8KLS0tIGpocVpCSkhIMFYwVDF4elRiV0lI
            ckRlbnJRQkljMUgxSGV2eEZQckR4a3cKY9T2rRklBNixjyJq+svoWBS0sxiTJ89p
            YtvRHpsr7n+WdvIhbYAdrs0eM4T/BgbgoE4pMWKwSQJiGJ34xZenWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbjR1YkFDTzg2Sk1qOFEz
            RlhPVXVHRktRS2JlbE9yNWRVaWtSZTFzK0RzCncyc2hGTVNMRHdXeE1SUDJsOEdz
            bGtvOUptMjhZakdZL0JVWEdGMTlsTW8KLS0tIGVoWmdLYnc3RGs0eEdvRndQRjdF
            eUZYamJwTXpjTVdkazRYNjdnY0RtaEkKdI3jMqaxeb7vsf1RN52oiKxQoKOqVc5e
            SKPTnckh+lhhXvb1hQSY20H13x8n9xZwHgFXoTkUYd6Tfmz56oTJuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUGx1a3V1RGRSUTFQNGNF
            dGU0dHIvUG9ieHlBV0FuaXgvKzc2ei9TWGxVCktSZjNnZjlZQ2l0Sis5YkRJK29U
            THpsTjBoenVxU3hQakU4T0FVRzYrN3MKLS0tIGx0Qy9hdm5ySUN3Sk01a2htcTla
            d0t5VWR6STBnT3FRSWZkRjhQM2lPSGcKI8cxDCJeXAd/GYaEbkSMxnG9B3mON68X
            FAFtwBojkFubduyGZf0Jk8wwz1jR7J/cqunqNxQKWpsPZAyUuX7BkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T15:25:44Z"
    mac: ENC[AES256_GCM,data:LsDCGdn0O2MgkiVK0rZ/HDwoe9qSrfvxPc2NdXeg86zR8NcBUtx5oMcriFNR/0calmMLGRDOLaWFYK7VILIwOtWc89LFsGBYX+sb0bVt79qogA/QGZomExvlzpTetNt9BLGg50Pi8Cuuei05/PPx6YmuUlLkNmZdrEGiV0eJ0KA=,iv:9aOmJ3aHwMsTmBEwH7HHBxRou1oFk75fCa7hhwoO+O0=,tag:O+9EStQX/P+fKBX1VAAFcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:OLOaeRIMt1u/eTFhuLoKkSK3NgA=,iv:/zyNd2OcLWoWsMKKU2GAsvEKjoymkJW7sWZ3p1CvAoQ=,tag:dGBlAnLwVHcUPhyOBlUz9w==,type:str]
    userKey: ENC[AES256_GCM,data:HV3SukZn5dXbBDD6o0CNDLocIgWrnXOVyQfZKfhCEftL8gTncC/BgO+aoF9dbgo82AIASX6a3fs=,iv:jgQqEmsLVVNmAmJCs4bVjetfF8u3YNocGMsYkYNb7Uc=,tag:BgUmiZau5vU4goGYMC75Ew==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUXJ2bmx3dXpqZWdleUcr
            WXg5ekIzbjI4Q1FDb1VRNDFKbzBwenhEWGo4Ck9HSE9oblkwZ3N1dnI4SXI1UUhr
            ODBwMEtLVGN5bHBFcG5IeHRiZTFsRG8KLS0tIGpocVpCSkhIMFYwVDF4elRiV0lI
            ckRlbnJRQkljMUgxSGV2eEZQckR4a3cKY9T2rRklBNixjyJq+svoWBS0sxiTJ89p
            YtvRHpsr7n+WdvIhbYAdrs0eM4T/BgbgoE4pMWKwSQJiGJ34xZenWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbjR1YkFDTzg2Sk1qOFEz
            RlhPVXVHRktRS2JlbE9yNWRVaWtSZTFzK0RzCncyc2hGTVNMRHdXeE1SUDJsOEdz
            bGtvOUptMjhZakdZL0JVWEdGMTlsTW8KLS0tIGVoWmdLYnc3RGs0eEdvRndQRjdF
            eUZYamJwTXpjTVdkazRYNjdnY0RtaEkKdI3jMqaxeb7vsf1RN52oiKxQoKOqVc5e
            SKPTnckh+lhhXvb1hQSY20H13x8n9xZwHgFXoTkUYd6Tfmz56oTJuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUGx1a3V1RGRSUTFQNGNF
            dGU0dHIvUG9ieHlBV0FuaXgvKzc2ei9TWGxVCktSZjNnZjlZQ2l0Sis5YkRJK29U
            THpsTjBoenVxU3hQakU4T0FVRzYrN3MKLS0tIGx0Qy9hdm5ySUN3Sk01a2htcTla
            d0t5VWR6STBnT3FRSWZkRjhQM2lPSGcKI8cxDCJeXAd/GYaEbkSMxnG9B3mON68X
            FAFtwBojkFubduyGZf0Jk8wwz1jR7J/cqunqNxQKWpsPZAyUuX7BkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T15:25:44Z"
    mac: ENC[AES256_GCM,data:LsDCGdn0O2MgkiVK0rZ/HDwoe9qSrfvxPc2NdXeg86zR8NcBUtx5oMcriFNR/0calmMLGRDOLaWFYK7VILIwOtWc89LFsGBYX+sb0bVt79qogA/QGZomExvlzpTetNt9BLGg50Pi8Cuuei05/PPx6YmuUlLkNmZdrEGiV0eJ0KA=,iv:9aOmJ3aHwMsTmBEwH7HHBxRou1oFk75fCa7hhwoO+O0=,tag:O+9EStQX/P+fKBX1VAAFcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
