apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: homelab-user
    namespace: rook-ceph
spec:
    capabilities:
        buckets: '*'
        user: '*'
    displayName: Homelab Client
    store: ceph-objectstore
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIakNtR3FSaW1XMVVmSHZx
            di92ZG14cXhaMkZORytEaCtJR01Xc3JSZ2prCmx2UEUybGJQUkEwak1RdXhIcEtR
            cSs4VThFUG8rZStySUluZ3hNVFJPSVUKLS0tIE1UZVFPRHdKekQ4RzhkNUFBRVl6
            bkZ6VUpZUkRjNGUzQzZDdUpFZE00cncKjujlPq+7ET278FE1a6FT6vzOLAC6lKoM
            3Z7gJ8yv/7W5MFrZbpPI2/VCpMmqDrv7gW3CY2AFYVnq07Z/vAgubw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWGxBZmowdUhtTW9NOEov
            aE1CRjZ5T0huM2YrY3hSTDBSZ09ubDlEVUZ3CjJ0b2lSS2I4Uk9ydDZNY0RyZGNK
            dVl6T2VTK0tYT0hTNi94cmlXcy95UGsKLS0tIHZ4R3dpWDgwd0p2d1VZTm5RMzhL
            QnBLSnBPbE1UYzJ1NEswVlZoWFdlN28KTQ5UWsXWT/7k3G3ODhOV/2i53wjA4CZq
            dwAI6+acmoyukYHodZPq0+P9C5MSZxRqOZ5GWYSXSRFp6V9+qvErjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ejUyaTQ0M3FFVFJjdFls
            cnFaZWNTZERGT3ZnT20yU0xqWnYzUis2QVhjCm9UZ2gzVUZZRGs2dkdBaVp4bDBi
            dUtqc1N2RlJEd0FZcXdGa0RSdHpPdkEKLS0tIG5qM1kzWkdZc2hEOU56bnBaL3Av
            MW03QzNvTEx4VHBQL1lwSzVQYndjb1UKfZU/ihIsUszTAsz51om4rdqowmUi52i1
            cdrtahCP7kDRA1udKY8KMz6HqUDZQtADmf2N4MGH1DorO2aO0wOS6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T01:05:50Z"
    mac: ENC[AES256_GCM,data:5Kdo3pecsCPsyqrNzuT3YuSVtmwO6V5z+E4NouraVspvGybpGZoN9rjWUAx2ZEC2ww844FCms/8Q1ScMF1xriiRUFKu9j0jhWikNoKeJaZ0kRY2EHaB1xwcq3n4liHQ89PLP+5y6+StN+bEvLV5/BMtuB1GTZKPRr9UdG8sZex4=,iv:z1HZT8s/tByB+Cv5bq7GL8cQ6kv9DbKJL7TZ02DUcwQ=,tag:8BJzUIYKzIOPx5Uu4K5ySQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    AccessKey: ENC[AES256_GCM,data:WfQT3qo3xJ6M+GXa8teqjkNnhoU86OAb,iv:3r2Lxk6wJSa1QJ9wBpA+thsF+bxwQEND0PMLEUwnoiQ=,tag:PmqKvtn55bfc/N6LucW6aw==,type:str]
    SecretKey: ENC[AES256_GCM,data:OrXgLmm/nPTq4T7W5dljsuKv5p5nOk5S7jUkumBD76lVCf19R18GiCb/Uj4=,iv:R6rF+8iSYay1k2a5+LO6zs83t8y5+ticxHhiPQwtmmw=,tag:WyoNBHXlz5L94/QjlBbg9Q==,type:str]
    accessKey: ENC[AES256_GCM,data:hGxvKqGDww+eY/xDn8wN/3J2V9HpN/Yp,iv:AmkC502kxrGAqZK2KU/Au/YFeCFlXcKr4ierSj0qyNQ=,tag:493aAsX8bpASJKxcngkouQ==,type:str]
    secretKey: ENC[AES256_GCM,data:zf0VwsBkWeQXSYhGnUcjmqDLazNt9JEdR2aIjnuoQKMigA7RO+hXMZFvqPk=,iv:hl/IK0vFyz7Z9klyZ/mOfOoyrqL3XidldjXhWBnzU5Q=,tag:2I2uzqrn1scUBRu2qsoFXg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ceph-object-store-credentials
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIakNtR3FSaW1XMVVmSHZx
            di92ZG14cXhaMkZORytEaCtJR01Xc3JSZ2prCmx2UEUybGJQUkEwak1RdXhIcEtR
            cSs4VThFUG8rZStySUluZ3hNVFJPSVUKLS0tIE1UZVFPRHdKekQ4RzhkNUFBRVl6
            bkZ6VUpZUkRjNGUzQzZDdUpFZE00cncKjujlPq+7ET278FE1a6FT6vzOLAC6lKoM
            3Z7gJ8yv/7W5MFrZbpPI2/VCpMmqDrv7gW3CY2AFYVnq07Z/vAgubw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWGxBZmowdUhtTW9NOEov
            aE1CRjZ5T0huM2YrY3hSTDBSZ09ubDlEVUZ3CjJ0b2lSS2I4Uk9ydDZNY0RyZGNK
            dVl6T2VTK0tYT0hTNi94cmlXcy95UGsKLS0tIHZ4R3dpWDgwd0p2d1VZTm5RMzhL
            QnBLSnBPbE1UYzJ1NEswVlZoWFdlN28KTQ5UWsXWT/7k3G3ODhOV/2i53wjA4CZq
            dwAI6+acmoyukYHodZPq0+P9C5MSZxRqOZ5GWYSXSRFp6V9+qvErjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ejUyaTQ0M3FFVFJjdFls
            cnFaZWNTZERGT3ZnT20yU0xqWnYzUis2QVhjCm9UZ2gzVUZZRGs2dkdBaVp4bDBi
            dUtqc1N2RlJEd0FZcXdGa0RSdHpPdkEKLS0tIG5qM1kzWkdZc2hEOU56bnBaL3Av
            MW03QzNvTEx4VHBQL1lwSzVQYndjb1UKfZU/ihIsUszTAsz51om4rdqowmUi52i1
            cdrtahCP7kDRA1udKY8KMz6HqUDZQtADmf2N4MGH1DorO2aO0wOS6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T01:05:50Z"
    mac: ENC[AES256_GCM,data:5Kdo3pecsCPsyqrNzuT3YuSVtmwO6V5z+E4NouraVspvGybpGZoN9rjWUAx2ZEC2ww844FCms/8Q1ScMF1xriiRUFKu9j0jhWikNoKeJaZ0kRY2EHaB1xwcq3n4liHQ89PLP+5y6+StN+bEvLV5/BMtuB1GTZKPRr9UdG8sZex4=,iv:z1HZT8s/tByB+Cv5bq7GL8cQ6kv9DbKJL7TZ02DUcwQ=,tag:8BJzUIYKzIOPx5Uu4K5ySQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
