apiVersion: v1
data:
  password: ref+sops:///home/josevictor/Workspace/homelab-reborn/secrets/k8s-secrets.enc.yaml#smb_export_password
  username: ref+sops:///home/josevictor/Workspace/homelab-reborn/secrets/k8s-secrets.enc.yaml#smb_export_username
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  name: smb-export-credentials
  namespace: rook-ceph
type: Opaque
