apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  name: amd-gpu-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: amd-gpu-dp-ds
  template:
    metadata:
      labels:
        name: amd-gpu-dp-ds
    spec:
      containers:
        - image: docker.io/rocm/k8s-device-plugin:1.31.0.7
          name: amd-gpu-dp-cntr
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /var/lib/kubelet/device-plugins
              name: dp
            - mountPath: /sys
              name: sys
            - mountPath: /var/lib/amd-metrics-exporter/
              name: health
      priorityClassName: system-node-critical
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      volumes:
        - hostPath:
            path: /var/lib/kubelet/device-plugins
          name: dp
        - hostPath:
            path: /sys
          name: sys
        - hostPath:
            path: /var/lib/amd-metrics-exporter/
            type: DirectoryOrCreate
          name: health
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
