apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:MkuBa9wpHVS/jpF/slrJSLL6L3qbtd7MNr99lB0+mI4oYSFz/OAyWr1/fjFXCuSktJv7PeP6QIc=,iv:+iICG/l9bQuxKcafiuvlw2Qf3h5S4hrFHZffe0PJzNQ=,tag:jWZZjHpd4XcDMSraRWYqGQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxS2U0aHcrWHBnYlBSU1cy
            VVNoemErcE1PNU1JK05qdys2Y0k4UUZkajJZCnIxOGFYczFsemRrSkxZSlIxamZ2
            SS9oaHBXd1AycVpOU3JBN2llbHowK00KLS0tIHVrSEhVWGdDS0o1SlBaY1lxNE5w
            d2Z1eUt4K1JyS2QzTUtmWExtS0xlbEEKRkmdhCSdzOaGAfeB3TzQw2K7+xR/wCz0
            O55gl4ol9tPsFs7c1P4vL+K43ZzSBT8kEyM8omtMOQZq1B5OFUneJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZditLRjErZXN2SlVsNDkw
            VWlmR21XUGNnWXdpWEZFZG5GWjlxZVRyVkhzCkVnWXk0cm1iOUpHc3RPVm4yMVd2
            WUhxbHBLM2IweEhkYnVleVUvazdaTDgKLS0tIHdJUm1KMCtxamVKclI4RHNzZ1d2
            SXZ3T0ZhcnYxZk1sSmVHZjRNNkdXNTAKthZkSfcJveKmx2fKHd1aaYRuKeKXLBQh
            sLoc2SiRFgSKe9RM2bwvlxDSHR50bsSMeWAe1a1gpmHwCD/o6GeIIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCamVkSHRZSHFUdmMyamVw
            bFJJTjJPRmhmRFByRlJ6ZFJML29uS0lKaUdBClYrWjZlRXdGWk1TU1ZCeFBkdXZo
            UktlQU4wSXNMQU1QcHFKUERwTGpqM0UKLS0tIHdlS0FhanoyN3M5TlFCbWMyUW50
            MkVNMWt2SmxTZENUZVJQRjJ1b2w1UVkKJFVCfX9k1WRSBReLdPNHiA+Qzk111bj9
            YGMU8LjKkGugq1DJU4BCXHTbc0wg6joLUt6wpLtA+WlVfXz+Ui9cOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T02:07:36Z"
    mac: ENC[AES256_GCM,data:K1Y/fg0W6zPWqy5izT40nEs6k3Mh1OZLRveyWAQJ7UGieXZkv4HDQh2625ecBXcl/w3vG1t6gFEUJG90gipsekjX5BjU0KqcxX7LqpP0hk910AeQTBrKEjHE7Ts4CL2lCz+POld9QqD3HLk0JKlSyGYvLHHLWUCGlEu/dGqlcEg=,iv:Cj7Z/RCzQZpCHGfu6YlDKIFxGBZJBoy+6jPh80EFzWA=,tag:LpsWB1U5rb7jqXzcqUX9zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
