apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:T0wLKxUcs8dJIBGnCPy0ONDd7vF/WAqSHbAe99gungROJk82ZtgDJFQVtj7hCFMPX+UFDhv3FjQ=,iv:mVRmCW1q/WRsdm58MxowGuIutPNOb0KVHoTuUFF4J68=,tag:FyUfSTNmd5hdAJCX7eLJQQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.33"
        kubenix/project-name: kubenix
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRUdGTHVuWUQxeml3a0VO
            QlNKeEIyR0pYZ2hkYTR6eDdPVzlpakQ3QVI0CnliTmlLRmRWM2J4bitTcndxMGMz
            K3dsVS90SHluYW45dmQ5UzdLMzBXL1UKLS0tIEU2UmVqdUdDb3FQWFIxZUZyWjNC
            c29EN21seUlSTXlCODdRVCtRRS9JeE0KT1wcih7Erc3yDPhsMcVzWEVadW3+bKcw
            YYUEN0K7Kk1p9vrDm9JBFhYOeY/6v/gYLZy64CjLmcDtdElUv33Cuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQis3S2dWYVRVYi9xRTc1
            Smwxd2FUWUdoN09odnNydCs5KzF3TEF4Unl3CmtBTzBSaUhVT2xwRVUxbGI2VWs4
            Z25oTm1uWDRiQXlLbmVkdzZFcWJkU2MKLS0tIERzM2laczFpSnU0bHhaUjZpQTZ4
            SWFmRDFKb1UwZlp0clMreUpBamQ0TlkKonSdYOUkarGAdsADnnN2nAl38vvofpJb
            WT+3LuRnLqN4xa8u0b8VfTGIWMmNwlteiP1OAj0+ZdQvAPDK/cPkCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbEs0V1pib0FzbzhoWUoz
            eUlJcFFLMk1CSlBNU1dEam1Lam8yZW91OUVzCnVqemhiNUZ6c3RScEdpZXYvQ1U4
            eUtiREExNFc2L2E0VzF4UUp1YXYvUTAKLS0tIEMxZTZyWi9oaStYQWo2eDFaZVd0
            bW55b3Z3RUxQQXZIMFVCaEd0ZkZwVncKi3LUUuBn6q++SC0HUN0zAJTbwQGpeyG7
            iJCZ+YxxUA//IRL2KecqhvYpgO9AhIF2LILvYbsuBip5tpTi4Pdg/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T20:19:13Z"
    mac: ENC[AES256_GCM,data:Nx58iCDglwNgE+kk5vGOwl5oXQmFtr8xAj1HcJxsOtOdoq+lg+tazDzFKUgCGKj8FTToo5yaktuBDcxkkesnhP5nEhf8xeczeApf46j1zqK9d6WldPWGxa/I6XPiHc8tX/h4HwgSH/5sNPLD3V1D0A6Nf3gIv2bbrof405WOKvU=,iv:mDp7oCBzPR8/dH1TKixryBc9Kfs4H6hE6ZkqRm1fEhg=,tag:bp6QyHIwC1ETatyoimpCuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
