apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:zlYiVVKJIUokLRDRvIZJHrmvwVMf4RUPYiaHQLTMfk+CwLbp3DaIosYXd6MsJUshGiHPakLC2pc=,iv:lpEnv+MkftqJnHDNmc1mTd9I/F7eO3VnyAKjbwaQfiw=,tag:HjzHTMOrfnwSwhkLOvDMpQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.33"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa1Rob0RvYXUvY2RqZWZj
            Z2RCN0RzN0IxemxPRnpuT21ndHlJUWxQYTNFCmNQdy84Y2RIajdqMndoNjVpYkJn
            bTZydUdtQTBEK3hSbXAxOElHd0VtUnMKLS0tIDN3NUoxSFVnSVdWYU5FZXBpNW5z
            cXo5YS91MkJ2bkxwaTRwWlBMbk5BLzQKSo9VBXnMlRvUE4HlNH58UZovvGVLmLFi
            +M0Tm8NYXDLRundeYV67yx22r/Cc/jFVPkqIEM8sBW5eFFq9WxhVfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWckpIVUZvM0VjSCtFQ2x6
            eFAyTjFLSVpiQUhHdUQ2bkcxc2RQNnBSazNJCm5rcnNiY1dDV2tMSGRCZEd6T3Ry
            OG1oM1YwNXQ4dDZHdmZhK09ubnVYN2sKLS0tIEp1SVg4eWFybVBnbWY1dm50ZVk4
            M05rV0EydHZpaGZHUnA1Mi9JVFdHVDQK2ntw7KQOOIZ/l+JYO2MWoOHyXI5DQOjX
            oq8IqVgqF0HObbPKkFXYaWM1+AYqQmA1DUaWhqPdWOUA2O2gIzw0OQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRVdhalh5RTZvdTVITE52
            Ui9EYmlzTzlNTHk2K2E0L3BmVXY5MnBDS1VZCldxdU92VjVUR1lMczc0eGRDTU91
            cVlGZmFIL2RwNTVZYzQ2TmVRZlI3ZDQKLS0tIGFYZFM2Ni81QXZDVkNWc0N5dDZS
            a2tXbDFpNGR2QUYwRFUybjBDK3k1dUEKqztQAdZbvp7nBcsGcMIvWGPH5OzMOM1e
            HCqoRosuCxjP+f2BFxR8lssM1Sa7nH3+HiWQkohZ/J2b1qzza7SUgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-12T03:24:50Z"
    mac: ENC[AES256_GCM,data:6cjzSbQpNc9vHFmqHjJdPePHltWjYiRbhpF/WCpH6XjXtPYs3LyPnXiX0GiPMNFYdeiDx/eAO7B52+FglLlchfB/eziRcrb4TU4HOLunKOefWrkvQVehc3ULsN9BWMH+WVCBtW41nIiJXY8eIymIdyrybAfhHuwoI/oErUDa47c=,iv:GGkGF1lrOleXfJp/wO8obYfXyhib9q0GT4WDn7P1xww=,tag:DsLd1S2aO6qJ9eq+iCoy0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
