apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:VArlmhm+z3jxMC17sWfuNKoCjdobJflIEmpB8hFfrtNGCKIaObm2fWHck1T33iV7PsoboG5jhYU=,iv:LyUwtNiJHJKJTwZG7kHB1UId8XjiEXiZabzU82Mw2yA=,tag:uB4/5ARQiLcYEx8dMP23aw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVE1ESy9ZeDYyaVlPT0ZB
            YzZjOWE1bWZrbHczNW1hYXltbkY2cHMxdDNZCmN4aFJId3gzWFd3MVl4ejhEbGNC
            V3J5by9MTWJZUlVBWEdueXdBd29jbkEKLS0tIEpJSE9HeHV1MlpwTFJKUTBweGhN
            SG1RM1ZxdWhnTHUvbGVGdTdSQXp2SlkKNHBBlfJRDYQrvSOiszsxVmNXCzAEPA7w
            Dev0FJfp95VtTYk2L8b/KpAM34eod59t1oQFolla03LuVaCmY2bPQA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTFdMU25ROVUvMUtnTERT
            b1hGYXhaU2JGa0MrZWFQbzErTXY2ZHZ6QlZvCkFrV2llMjZyeEorRU9aNVIrK20z
            Q2xCOUk0eXpPTG1nY1RYRjRHRm0rL0kKLS0tIDUwV2l6Z2NIaWhPZ1h4MC9ScGwz
            Tzd4S2liNEtidzVqOVNTbGdlMzYzVTgKzeTOzQ6G0F6GPq3TJf7CDHhpNXDYs/4W
            7EhTJhHUY7fIFjNDXst2JfgQkTqOqqosJ4dyo8hpZKOSGKmU7fDMLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMekZZYnd2MjFib1NCeVY4
            RjRQQVMyTkNZWFJYSUVwcCtacWxnSGxqK0NVCnV0aG5KanBLT3ErV2dIdlVQdFZt
            L05JbXVnUHhMRU1jZ2hzUFEzVDdtL2cKLS0tIHhUaVQ4WHFnK0hPcU1xdkI2TnFY
            S0pyZ3ZCamZZK290T0NYcC9UUFlNbTAKx+OZMw6ZGXN9i4BssHgPTX0OqvO2rNA/
            NeRhoKtLBp+0oJ/fsXm+WSOgYhjN6mLgdyKTQboosVz2zGPJJHII8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:56:11Z"
    mac: ENC[AES256_GCM,data:NtplFwi/URX+ssglo2X2H+B5oOJTP8eg92I7whGxR5za0YCHx96YnF/r0IENYdlOU0B1C6OlrHJsKUNkwUo1RKsPAoNzEZcRSZyn+xKGtYuX0TvVtOu/GqGay3ReTJUcLTodiUFflOweQuC+nnvdiwK+Y8rvsxAXx6FFFNyCYIU=,iv:W1Bnbb3pdPxbYpzUr+OJit7E7lreQ7l00ebHvoIFp8U=,tag:RGhczSovZAu+1XCIC8o9Pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
