apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:zGDnW8tmozTyDb2Jkql8y36CaD/cB9VA6h+OdTj6EnE+wskDbtw6uVSF44o7QFj/hKMRftvtevE=,iv:ao5A/c0r4wVTB//q0Lz3T8ZjwINRfn+ngpLYgfnni88=,tag:KRvtgURsMFrPWjga62atzw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.33"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva0l4YXhGdHZXUGV3eG9U
            ZzhOM0pZYTZpVlNoQmJCempZeFhBZEk4aVFRCmVVVFJKcHBwRnZWeXF0U01IdDF0
            Y3VUb05HaVVaMFJXWFdqZURsaFgwWmMKLS0tIEp0Y285MlYrVTdhTmNNYm9yODNs
            c3VVTHFKWitVSFlzMkpMeVlZVFh5bkEKf30bxxrKPvt4AIRGuxtvqsAq5PzsX0G4
            r83krJOGMk6RCYF6HOlPTH+s6pzsVXzCaIAlLLNJSSaSBSGiJxJKSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRkR0NVZPK3JTdW1ISy9W
            ci9Cc2hYZlNQWWNUck5BZVJ3TjliWU00SG40Ck0wdFNYMHJjUEE4Y3M1VHdIN1dQ
            WG1ESkVmK1lhWDRmYUVFNnZScTFCR2cKLS0tIHd4RlIrb2dWNFJZTXY4czQvdnZi
            QVhsWXpSekxFK2pic0x1V3d5YVJzd2MKaHU7bmRwbC2Hmfl3Dct6sjsIxAsG7hCh
            p9epdTTxI7T3nXOGBEMZie7rVXO86N5xKA1jxjUoEkIs5iPPymc3ZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMUhYR2F2cUQ2dVFxZnlY
            MDFQZEMvSnZvQndqU213Tm5VN1dReVl0TXhzCmdxWWhHUzlCcVl3elJkSmdsQnM0
            NlR4WUw1Q0N3eldVcjc0eXdqV2dadm8KLS0tIG15MU5kQWFzQ0oyNk9kZjhjemRl
            c2xNRElNZFNia1czeDdVVWQ4VWRQUzAK1AM2wEs+KIOpjK5mxIoipTd37UkmRbKu
            r+mF7r4xgwchvPvUf5vb/FxyhGD/EJvNQujMUaw95krHdrpASMIJig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-12T03:34:44Z"
    mac: ENC[AES256_GCM,data:B7dnExG25WDfQEDWUAVov0RXkwAIH6gsPSsymtGQjh5M061DvpyEXDHqAWzzK+4ZrDIY1kKet1nj005fTMiLqlvco+uJuYBwHu4CWFLPyoogYIuru+4VIbJWS9IH/o0SuYzYi42/HjEDyj+uzIxxR0PYCecNllVMLIO+ufNWbAk=,iv:dlcXGkOeh4Ht/1R/Hyk9tlQtR2oat1r71pnS6UYPS3I=,tag:rqRC7rtS0mAf/8xzhsU49A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
