apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:NtFuv7/P24SDlGCf+XnRtg7lCrRNiLhGsIiEsm7t7/2HEg5DoM9ONhSEfJhDmW1ZBfCaQHBIPaY=,iv:3dV+cEa5sfcU52SeW9EcoUcs9Q9E9xeezispNxkhV54=,tag:OrGfnEV0dt7sLoQt8GMv4Q==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MTBuckFQY1BDK1JMbkJp
            Q0R1YjBnSTllVERqK2tncHcrZDlPeWxEeFJ3CjNyNkt2V3hTaDdISCthL2pmeGtE
            MHZxNXRlaGE5T3FmZVlERTdnRi9hMFkKLS0tIHhBd3JOakdpWXVpazlWVmFTMmdN
            c04yWHJ4TGlETFNZeXg1MEhFakVWNUUKduMaq0zrP5dfz057FpZwvnMJqZDp3ASO
            75wsNjUuGuSMDuHCKqqAKATJIxbhs+q852GkbGycIX8NR4739jZZLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT3BteEg5YlllZDdabjcv
            azFLdk5yWTF6aGdHdHhMRmJmeWlmanpsd2c0CnZKeHE4UUhocmlva1hEMmMvOWNo
            NFovTENSTFVXUzdtVW9Rb1BvcTZUd1UKLS0tIFJrdFd6Tm5GMks2QU5zWGV1VXFj
            bUZZUmRHVVQ2bVI3Ty9hcXlzdnNOUG8K1yAVbuRTlrk9/jX/TtLVuBbGssqxMg0/
            MQ0Gs36mWtULESpnETYrHocfYa9yNuOw3w+roB9dVawsvOdAjP9F+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV1dJdVBQRkgxZ05TZEEx
            eGxQaFFIMkliYWd5ekZvREhZVHFGM05McUE0CnhPZjl5V3BnYk9temZRQjUxbG1j
            M3YycUNybDZpL0FNZ1FlVU55bk5pa0kKLS0tIFB3M3lzRVRjWGVpcWZVajI0NDVp
            bUF1emlJdlBWMEVCSFVBYUJWWGdkSGsKSTiV3CyRt91Y13FAGLLWvgi7Fb1t6K1g
            PsIcSDJYaznBjYl94hPEa81hNKf3fSJQRQCBqmteA04yte6Ew2ruHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T15:44:30Z"
    mac: ENC[AES256_GCM,data:ZsysKfVMdqSYFSubWssRumZvFcv+YuOAVEIPwYCRUv+p/Z+KW6a8sa/ApB+wzQelZWbPliqr3wcBweDTNefxeNBcnxtLzVTsNsOsBZEJapYxd7BbuivGD6rS2KGcU6wvEhpEOwPzKqj3cHEVOcbUKuubxdZ3cBX/4YJDeBekAHQ=,iv:gznLOx5q+J65RzbtgEt1PMEmH0+kY9GYi5ez6qrRefY=,tag:k9jyUiA+0XGttRu9MnKevA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
