apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:M8wSJNxwIDr5fMb/H+6hDJ6K9MZR3KxwJUmrvMVMTzc0waJwz7wiUNTbdovj7eAlAgRtatDx8o4=,iv:3BzHudC6CQYASOR/yv9oOG1SZ/OaiNY52jFsX0f7Ulk=,tag:2JsCNUSyRlzWoAhiO0qTiQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.33"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1alVJT3cvZnhCbTVURjU5
            TFlqRFNpL3YwUmRjZ0hrcU1GVXg2ZXNKMkRjCkpuc2pqZThYL3ZnQUU5c1dyQzdJ
            OHRMM0V1Nm14Y2lkNThCdS9lU01LNmcKLS0tIHFTZ1BndTRGYWdaejhJcU9lWTF2
            Q0RtT2VNNGFobW05OHIrbUVBZHdyamcK0WupIWSCYvqYdTpX70Uw257wUm3L9K+L
            hY4YJmUJNsVYHxNR6Mihzf0t0Vkxe8y/Z8VFI0Wguz4OWTMceI/0gA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHenR1dkd5SXI0eWFsV3FE
            MitvLzRZb0gvY2t0aWR1Sm1CbnhjQXkrWFhZCll6ZFZnU0lJUzIrN0hPc1JlR01l
            NEZ3RjZnNGRaYm44TmhwSmlyc2ovd0kKLS0tIFVkeXUxMmNKYUtDOHZHaFo2dlJY
            WXBWMmdBajBRbS8wL0ZtaWZoNlBHRkEK6UzTaSAKJaRoRxpcBWDCTwZAra8VHVuI
            Y2eEEgXa5D1fj7UxjV/XB29JEG7ENDjL+IdMLq9FaJTh/251HSfYqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdmdPZEtNcGR4YUJVRTBT
            TzJ5c2RRcE5jWkhnV0FodncxOVQzUkNObW04CkkwS1REQ1hTRnlVUkZ1SUk0Tm1Q
            WDdZZGxNaS9QQ3NHYklFbis1KzR3bEkKLS0tIDdjMVhSS0tmQU81ZjJ1SmZHZHRG
            aEFCREpnYm1CMkFBYVhFNGpYRWlSejgKUrNsb73yTs06gaI9cf3b0SmUZz6kkhNh
            IsxAyPC5owRx+5HMPQPrH+yM33BqNA/Bmy3lU5a04KJjS3szD/kiQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-12T20:28:29Z"
    mac: ENC[AES256_GCM,data:a8B9ksmKsafrWE3leUDIuknqacLeDyDLfGsfhKEB6YMe2qp7TX1am168l6BeEnNFavNqktEF2d+00L9sGoS6HHt2+zm52pCrhGklkI+n8k0LBGuyXj0lQSxAoITinbDl/t0fTuv22Cl6bzVYE5HTv0tzKOneTcFtm6nW9618gzE=,iv:r3O0O/UMAT1uHdS1pa0E9ZvUU1Qu3PXwez4wdrwfXTg=,tag:gXYCTieN5ThYq6E+HOgpiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
