apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:aE6YaCLYzUA3RPHVYbShLwaVjbF1OoQfqJwqcLt8JQ2Wj8aCMNMafzzZAnv52Pbu+IvqE92LEbA=,iv:65DvNGDxn0PEFKbPeD4FCaJxCtWSxmpBNGzJ/yTwqvU=,tag:B1LjwFJJkEmAbEKsTQsdeg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRHQzWGs0YmJFQm43Sm5W
            c1hWWHFTN1N5cEdMa0E3RjVCVmxiWk1VZVQwCm9weFF5NnFmV28vdnpsS2FyT05k
            YlFibE1SZzcvNHNRcHFwTEhFYm9KRDAKLS0tIG9FZ09qSzVzUjlheXNFSmtFUFFC
            QnpVQUtGaDVKNGV3QlNJRHluWVUrSFUK/8OpfvKvAAKKT9xLdpKXLhHOgDgUPx09
            OSdTqc/1KB/EEoKc7CCwNF0S+P381JHXVAsy8jkcKGHRRgyGdrZBlg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWGZDTldGdzYwZFZQWmY4
            NEtlODgxVTczNGJKN3RVL2xRMU5jMlNrbFZVClIzQ3BCYXlDQzJkanF3Y0J4bHRN
            bWlJR2JNVWFlS2MyTWxZVlNZdlU0czgKLS0tIHpJeDcrbUt6Y1ZBUmNyNjVMNXg4
            ZzRmWUVsdll1UHZwRlVmeFJpejRaRk0KdID2K93JpqzINzu79rcB1dtMHs9A6qLE
            k0FWtQCBZ51CoHqHHvDrbvevmi3tVfyCcOQdvRQP3Ouv08Ma5Y8hfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVkxMU1RVbkxzMnYzbHZk
            anV3WWNGMEtoTTY0Q0dUNk52UVJSQTQreEVvClpoWUJuYnJSRHF3Mm1Fa282YSs0
            VmdYZFduK2xVdi9zSzhVb0hyY0dNU2cKLS0tIGdTWHpBY2xZZE1NWmNBaFpOaGRQ
            QlBCYjlEWkwxUVhiUzE0bEd6NmEwSmsKb5R8vHNX1MB2cMYD8FfsFN0l3U1MtIlm
            /rye7lchhErDa6uo7I+XAH0Aqp8RxjsiHq34XlTPaC2bDSJ4WDduEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T03:10:57Z"
    mac: ENC[AES256_GCM,data:Q+qUz60EUcwKSLluzEinK0OZ3kJBsVE+6KEGraoMhjEgwFPYD/3aHCTiapB0MUSLGqD/ER8K99reQexPyRk5hw0cDjQ5He8RG7cIt0j2pWVGN1cWR8adx/mdsoGg6CW77EdLP38Ov6hBd9/AUAJIugG6DEls9r9m66NJMrtKl/4=,iv:YW7yRZtjY6LEQUpDJ7t+SeDgUcCFicyZiUU+vmwbzok=,tag:0NxtS0/o8BONax6ALuiw3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
