apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:09LR/ssKrVDjmOSboufJ3eTW5JQSDNT8VY56tEW4qDuf9LarMQoLQVAHMTAsPA4zKjEfnrXI3YY=,iv:a7H6bTxCo+0sKUJyZfNs4C46INndjFhDQMFXVYBzJao=,tag:/g5C98fpe0EaIpRfhut//w==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d282T3NaN1NpVHRBWENn
            TGZXZWZyeW1vUlJMME9JS3ZGaUVPa0ZabW5jCnoxMHBaRldQVlJpNVRVc2I2NVZD
            Umx6Y2d5aGdERDExYWdHeEF6cktmYWsKLS0tIGFYaUplZjVVZGo5WS9yN040VHV2
            eVJiTjFzbms1NzJiQlFhcDBDZUpTZE0KtfBp4DoIB1WlBLgwp84Mnp/nZbLAgw0o
            AG5i1NWfI3UQ7XBik3N+wjmTfvkIi0JE4zFQjztU893h3aQQQD2b8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWWFoWCtTSVRDOHVRVlpI
            TVkwZ0VEUmF2bWNuN2VCd3FNV2Z5dDQ2bFMwCnB0SDU5RkkxUkRIVFhqbDU5VnRT
            eCs5V1A1ZXVRQlRjaXAyVlpvN0RPV00KLS0tIFFEcWxjdy9GcjVaNm5xRjBrUUhh
            YW80cXp5UFRXMVU0aWRJbkhCZXA5UjQKkEK8Am2ypwlViz4pcizXKG7V4VA38kAm
            sFdAaSKKhBdgwzHjbuRq3Pic/1NLzwn6VTPxE4oooc2815fZsL7bgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeVpFZHE1WnVPVWVIdW9P
            Y2EzY2xGdG9KTUxWMTdNbm9YTTMzcGRDOVRvClpOQ21JNXN1NDRwNFczekEramN0
            ZzNQOWZuY2xDVVhzNGFwWmJ1T0JHQWMKLS0tIFV0cWVPalh4aFhrSDhHNE1rUUxS
            WUw3ZGtxVGQvYUVxVklJaXU5SW9jNlEKlbVk8h3WBGl85yM7w8/FReuAkd5PgpuE
            OXam3j1D9WbjLvxMUS6WdcKb5arbeKJvy6twp81W6cY/hL/AR+c41w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T02:12:37Z"
    mac: ENC[AES256_GCM,data:/Art2BApdGKLbALaxGfiro8/+Q6cafgRyK9lQC/eyNbs4XOrQuhE5A5493Z8Htk9F0yoon2HmubbprKQMK9p9I77kxp9uLxjYj2aOVDdEb98NJoJM3o2HVs3i/zaZEyLSmU/wzdlfkeAyWBR5ZblBLqbQSGbPxe6wRqbm0mYqY8=,iv:/5acPyMZHeWFjmZD28mq6cO//ZIPyxBibsFT+X+2RdI=,tag:+bFFl6tg9wp3zSlmw35Ebw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
