apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:dyQ6yyJRX3VPHQ3sfUoAR9swk/1syiEVr9zu/dKZOVUbu4ooE22AwUyv1B4haqjIRxDnXcUXlzU=,iv:v+bkMtXgupKjdulPL69dEMlk/35fdrE87naBdtCLLso=,tag:wk0A6WjVhcFGFIqq4IZH4A==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbFVZQmdaQVF3SEM0cWdj
            ajF2UHVyN1Nobk95NWRRZHI5L3k1RTF5cnljClZDLzMvR0VTeEpXVWZYbFlKSVVV
            QmN4SDdYbTdxd3lkYThuNzhiRkxpWmsKLS0tIHZIYm01SHJhMldMQkJlaG4ydDQw
            VSt4N3FVTERhbjNrMXZvbjhnSHhxN3MKtQm9H1df9+MZ/ap+O4X0DsU9nuIQfwkQ
            qL1P0BksG9zOv1l+Hm0e6fPwHYQjrCOxWl6a6KIsOU7fCxzl2O5Nqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRmd1eEE4akhwREtSbVhn
            VW5XbHFhaEFHV2dpS1VFSk1HU3QvMHRHTG1NCjI4ek0rZ1NpdEkvbFloTlNMV2hL
            TU84TjlQRjBwKzZqZ1g1QjRBMnpvSVkKLS0tIDRaeGNZQ2c2T0pWWDZXNmtqUkhL
            cG1SbFRDSnZJaVN2eWREdnNhSVkyelUKZpb03+BTVrJVGRUeIulVUo5dI8oO8vXs
            gvR7qgTff16eXH7htQjVOHufIhPuF+aCA1ljkCDvnR4fGWrj3h5gQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcXl4djAya3VkRXMvQ0I4
            YVBMcy85L1c3Nmd0SDZwSTBqeEFGaEdCSDJRCks5NTRzVks4UmxsdktvcFNQQlZ2
            Z2pxa1hBbENRYTB1MjdPSStOTUY5SGsKLS0tIENmQXVOT1FId1hISW5LT21BUDE1
            K0VGQzJKdzJqS3E4eW82dnZHaWN0NXMK6G1mdYmz+eQHvlAZ8NUibISt8glInqfC
            JRQyZu9d/ktctGKX7eULfi9Lw1zq8YiYofJOekwHuWgxECCtwU8j6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T23:10:05Z"
    mac: ENC[AES256_GCM,data:/egQUwKnStIjANkJBA1vQA8WYsIWginiaRUL6yEHi607OHzdGgFXyKe6y7n585EEtx7aekkluooJI8dVz4JgW2WbhfzAlC1BPWsn8E83zgJefCCWAAzO0ZQ56lyDHlQdbd2VX2uCfAwrRy8V3AtcmduZQzPt/ewCx8XMc+4iSBI=,iv:NZ5unwb34jv8bbqiNeOw2VCIm8N4IT1pHASBanedJAg=,tag:k6303bPcgc5hhhL6639gCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
