apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:OQpo2lU38Kf/3leh+/DpUMJCsw7Y6jqWe0kdC+3MgOJ3Lb4o1yyEOiemU9aBGVaeIGz+4RnFyFg=,iv:t93mo8L5eJoHcOExBHd3lRRwTdOXD3vJskS3ylHx8eU=,tag:CXGo1tvf4Sn7T0wmjG2vIw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYUVWY1pEMkVrSEpENmJq
            QlBEQkNqRGZQT2dPRHVtZ3hUL0I1VEJYL0JJCkNINnZPbElIQWd2ZktZd0pibHF2
            djgwUHZjS0FoZSs4bEhyK0lXaFA2RjAKLS0tIEtBdzhUcDFZdlYzTHhnQkxUUVIz
            UEg1TUw0b0c5NGtBWFBueGE0UWwxT0EKkY8zaF5z6Sd/GD2TRP+qHuMTyjEYJiBr
            hlFuNAqH1Lg3CyFgnAi/oM8fBj0cOBkGgH+bw5e6S/MsSwK7yhAiIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQU1vOGZ1VmhyT0prdkJU
            b0pHSVJCWmxuL3lZQVdmK2EzN3NZK3RnbUNFCm1NUGx0SGI0d1Z6ZjBzN1hjQ0dX
            NG9BWENRdGhjQWRpd0U0akh0L1BtUDQKLS0tIE00QWtPMzF0SDJoQW40cnZwajE2
            RURwM25kRCt5clFXeU9iaVNaVXgwcjAKRnnQCzja0MNzvSnNemKkGPk2hbSnhbpF
            nDxUdTA54lagccvV5bbWjF8hRtecsG8T5LMNyVuQyEQn997uqDTy8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dUJvZTQvb1daQ2RQVG1n
            cjJTSXJ1MVRZRmV5bGpXdCs1Q1owVHV4WlNrCkg4c1daYVF3UnFqZ011dExnNktM
            Z0FzSXFGcTRlTm9WZTZlNDVWRDQzdzQKLS0tIC9qSWVwRzZsMXpWUk9YSVFWU1pj
            TWt5QXhxcHJvUTdieTB3Y253NVRKRk0KxLusP5RmYANI4H2geLTJAF1xX9XLhpjl
            AStesT2V1sls5dUq3WFP+hZ3ywYem0gQ+51bQ574vcyKh+EBgxljBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T01:57:02Z"
    mac: ENC[AES256_GCM,data:O2REDLAjNpSBHkDvLl8yxoVe4/jHn1a6gCKeFgpU8qctsTrOnzTW1o/e8Sq1a5RnEURyMV64FwGhGdaHUl/LFZdeS/3VEYWLay3kXwm6NZIHf6LWXH5FYPAHUPz15xy+L+DW7U5g2+IYG6HbsMXQPrdWEZ89e7t7fuh0zLmACEM=,iv:Xzuld5LT8bNcvaRCTiEx0+5BCQSlwlIwvAjtMdojMgE=,tag:sgGDFYqz5xdACXVNqi9ZEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
