apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:HOdP+Qh33gwJ8loXcwDxLTqoMhVkvJqyBac/ZEoXqKLaGWNkIC56zrvgttcwg6+ZPkj7h43jrR0=,iv:nGXxxJDrG5U/cy7OpGzSUrjtAMnLDoHqWNyKH2qV3Ag=,tag:bkDmJcQNiNVlQWaBAbyaaw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTE1kcExQY2l5N1U5SU5P
            RUNqTDJhT1VLUnZpWEJORWVqUW9iSURxWWpRCldhUjB0TnJXWGJsWEVKK1pHWXYw
            ZXZvMWk5b1VlQjgyMHppcHptVzMreFEKLS0tIGNoQ3lFdkh2NFFRSzdoZnRLbkVs
            Z2JwaWRldURLNlJSc2VML1VuMjQyLzgKAHoRed9k3fASiVNUb4awqWKKcw98Wpfl
            JAa6Auc92wNMJnV/SaWN84WqAKfij3h8IPpvAVyZJdSGdsYVhGLZ4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSkhTYVVKVk5jbkVkZVd1
            RVdKNHpuUzNGampTZVl6RlV2S1JNZWhaMGc4CkNueWcxQk52UG9GLytPVCtBZnBU
            Y1k1eHlocU9UUER6QTdHaDl4Z1ZYUHMKLS0tIG1jcVdyMitGbVFndGxqaWJPcHZQ
            SUVrSTBWQjFoa2xkYkJUVTdLbVBoMGMKZ1vtmOBU9n4O0U29AwJYEwENaNhjFB0s
            ARAjmd0NBJbry0RVsKaJassWIn68DS6WTIbBwVXiWsuSdCF1/v+Etw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSHB1enI1TlVvMmRGU3VH
            eDd0SHZ0UXJwaEZ3QVMveWxMMXNsRDhRSDI0CjVFTHlyYzRrSmJlcmQ0Vk5iOEEr
            eDlHUXczbmxDd3hvelVxSUU2MHhqaDQKLS0tIHFlQWdPR0FlZkU1T3c2Qm1Db2RI
            U3BDV1ZWNDZLUHV6bTByMFd4WFAwRDgK0pF0TJY5Sxam0y1ciralbb5BEZU936MG
            ILsEvDUxwrAQmitxx+7xMvr90Z+7LaY+7eN0rnXrvLIcXwb0Rkxrag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T03:17:07Z"
    mac: ENC[AES256_GCM,data:932KY1cE4dM2OqJLNk+JJELWHblUni3fBza4BIMw9GLMtElQvaGzugb+6rkpPtwBoNahvP9nJYY0xULMwpK5Hu/Z5gRPbFnlcZQq8eGejOYeyK9M81xrAWxSFoll63wA+uL/EE//lOqWzoD3vYROFjjPoxAGkiLe7zTAP8+PboM=,iv:H2bTmgiWNmhThIvXHqz9PHC15rsRc/BMOyVF8G9Koz8=,tag:5v5fW0fe09pgQ1KDcUmb7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
