apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:uwF1EKEhj1dh5Pr69KidV57TR5xWh//Ya9PgA7BBXWd6nojjkzYt7m6SV9MPvDwn2TZBo+mkTvs=,iv:1C1ufrzAFBeCRESuUAgAV3eAASYzzluT5KUyFghKuVI=,tag:rI7+AvkAdrWOzOjWZaZvZg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRFBHWGlzdXlyUnBiRHZx
            VkcrUkU5dVZyUWU3UWRlYnNoSXpUaEFQMVNFCkVJVzdsL1ZnaEkzYzY3RG5ieXBW
            VDFUY3VhcVdFVWVTa1NnLzBRY1NMYmcKLS0tIDdHYU1IdWJ6V0w0MGNjOGJtTXRx
            bk9kaWZXT2EvQkJlMHZpOHFmWC9qb0EKqRQVPutL8DyHC0yJ0aTD7Zs36AyU42Rq
            MkMd1DphZF6lchxdSkrGJlETqoEC2kQZIOkFGKi5t2U8myA3whc4jQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM3JySWZoaktkUHJHSDZ4
            bHpsbXk1anJTZ3pJbFJIYkkyd1U3ZGNFc1hnClMzQWVGeHRBejVpcXVvQjF4RUFq
            WnppQ2lkTjdRd01FcUhqNTFKY2UzUWsKLS0tIHMreHBzZ2hpRHVSWEtBZC9OVkNy
            eGgwMHpsTE81Y2xSS2ZVSGxWZUd2VzQKpbadWXQWxZjiXs12324vX7eg+J6Ww66u
            MebYTeJOWgZ4Yy5zdK6rtJXmBO3Lyo2zMKUhb32F8gc0qLm2S9JqKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MS9KYXNldG9aRENyMFNE
            TUJ5aFhIMU92U0szdjhMbjBzNmNKYXdKNjJrCjVNb3REa1Vkb0VLQmhFZDk4ZnhW
            NnYvYkErSTgvUk14b05CMmgwUmNIT28KLS0tIEE4aTUyb1lEUG5iV1NHaG9HSUtx
            dHdVNGptUnVDbkRxMUJJeU9JUHEyOHcKHJQTbMBLoFve6wWdesVbk3PcxR92ODWf
            N7K2puVuXnnS3gYAJQT4OTh6y3Nx5BV5AWalEMFkkfJa8QTPYHSJmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T01:49:04Z"
    mac: ENC[AES256_GCM,data:VsZdEaVYRVWZ5PQWR7Fa0lpv35cYH5Xz32svFTus5GzzFDHPgCSnVNNAWHzYXfq2gu5T6ofvo2naaCZOYzpb8sWjfHY9ApdWSV+HC9vGA1/drE5xiBMk4Vvo6F35lg0VdI6sJaXBIXv0fV00NRVWGQNFpd5TAmTGo4X9xcGP0wY=,iv:iYoA8bVYt5S+SoBdvcKvg3dnodgJb+wY6Dbr36Nnr+M=,tag:mrLd5jdflb0QDPhrmOmCUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
