apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:U4MvwDYWViS6RbdXs4lJVpkwwwJR6v2L7bWW5qouSFeS1dpkg1Jyyr8BtZB6MAQ5h0O8kOPQ6e8=,iv:Mf/aQTFQrn4QeuUAxNFOgkmBo0PlHiQm4/BRRF2B+dA=,tag:zgd+3k2h1xNflTgC0Z6jrw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSXc3QkpQT2g4emp6dzdO
            Mkp2aTBnZlluQVBIUk1QSUNoS2tvaEJ2NDBFCnFtRHlraThNU1RYeUYwNU85cGNC
            cjBmTkk0M21nTXBVTzVRWXZ4KzZhMHcKLS0tIEg2dmVHUkNzNFVnajZPVThObWND
            T3FxT25FR0U0aVRmVjk0VmxSWU55VlUKOCGDfkhWs0lORZvqTo7hV9T7HqerAPTI
            /xxWl5xi9Tmtc+/V1sQaiYdXb24W13IW761cD839jS5JaP2afjA8cw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NmJ6VVJ3MVZiS0dNaXhv
            WjJ2RnpURTJzWkdGTG1BZGFCMzdzS24zVW53ClVIdml5b0EzK0NUeHdjREVsVEl6
            RkVBTSt0SVg4SndnTThMQ3V5QXFxb0EKLS0tIHhvMDhsWGNDaGtoZnowK1BrQXJr
            ekxkUDZ6TGtpUjlIMFNCTHloTDFDN2cK91plJLpcqnAigcRtuMdDuGLWuYe5VupP
            e3aSIvDrkPv+BJaFwXYW69hWpTORalVIhHsYFEs+5aXJmwzpr8NbrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOGRPQjR6c25MMnhxY1Nv
            OWh5cUNNMHNTcks0dVROTk5RVlBwYzdHd3hzCkVtNTRuWDE1cldmcmdNeDBjOVA4
            TjRoaXRIYjB3MlhadWpORWMwQlNGZm8KLS0tIFhMNHpYV0grcVUxL1JUb2g0Z2ZJ
            enRuTGJ4c3lvdUg1MEg5UVdUZStCTjgKrPO1u+EdVtmHSReXxt/Lr4/owb0pXDjN
            g0KU3ba9OcofVtfx6pjRJldfK760vRNx94WGAvJGZnCDbaczeKkauA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T14:03:00Z"
    mac: ENC[AES256_GCM,data:NOZIQQT/e6bhQfP0b4tDSWZnqKeMp/vuDJl1m9dnFoECb9RIZLI5wrTt9gW3RgpDvU00kamQU2H0tpoDcodiy6xE211JmghwUH/vfd5e5BEzbcj91Mp1UrLS8gENS0AsZmhcLMkSZgPrQkSQcqZp6Pr0G1SZlZrc/z7+N2sRVtM=,iv:evR+mV6ajbtloKEbCMYK/gNewJK41/4BVhbVkw9B30U=,tag:L3KXL6eky13NXpl6H6wm/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
