apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:boLYRrmiorZ3fDJmUabhZM/GBT2lCPqFCWDAUv33Y/QSjdhyhOjt2SZlRCt85ozY31g7gC66FO4=,iv:c6PfhaYVn3IGw07nFc40lm/xbQ6Qw5aa8AkoC2HkS0o=,tag:xuJFpUf/boPlvUMkOt05Jg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka3NvK0ZaSmZlTEVoNXM3
            ZjhUV0VDdlpBdDBqdWd1SjAvTk9FU0h0TGtJCmdsUlRtaE9sZHc3Vi9GZmViTHVU
            MjEzcDlkL0xhWnhBM2I4RVdkcTl5TUkKLS0tIHM2VTdPUzRmbXpkK3U3V1g2d1Ju
            c0NRRWJ2aENLcDFHTURNaXIvR3VLTUEKnl0sDMmlvDQNH+YoGmUIlsx4vaqkCHBZ
            mJR3EJ416stvhxWUzcnMevOEjAMfusNogRrEgzgpo7JyzmmVQMydvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYVVBSnl3SkFOdERKK3Ux
            cVZHRy9DbnY4UUdzV00vd1hhWXRUc2VaeERVCnN6Y09tTi96SSt4eTRKdDlYVUNj
            dWpwVW9EU3NwTDZzYzYxZ3RWK0xJaEEKLS0tIDRvdmxaMTkyZ2N6U2NKeVlaMDVF
            ZytsWVVtNmFUdEJoZVNsc1J4VFRmaHcKsdasE7oTLDWLgVPDH/dqzQyd2vsCOX1H
            JDRBNOG9G4YaOx9gjnvvKWX5uVhhU8ffcv6oplfRw0ewQkEx6b28UA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMXpEMzJQUk1ydk5pMlk4
            c2RyTllSY0ZUTy9tRGNOdnYzK0RHeHZvd2k4CkpiVVpvNVF6UGlHeXNwMDViUCtv
            NUV2MnBNbFdGSXgwRWZYR1NOTUFzeTQKLS0tIG9DUDRHc24vSmJjWlN3YWM4Znhm
            c0FPT2hQZnRtRzV3MEVnVWVyRzdNYmMKx9/AEl9T+f/78b0awdIs0ebFvXk5AI/0
            150OD0cfowY8QhabxVIBEvOeYtRb3GSBHRBb0d8i5xXWIcJrWnavIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T22:59:16Z"
    mac: ENC[AES256_GCM,data:vdDdPj1t6qf+wmlgryHHLbbbekOtLDqE2WXq7gnvVcuzGUZPDY28s82UXzCp2fQDOSgjnnvJH0e9KHkOuGthuW+qIvTDJKOQ4TTecApLmkHaOxdk4Xqvd/dWbzqwcRfkLHn/HBXn7tR/8Y/oYPZMBao+RDXuqX4me4R7uAM7eZs=,iv:TR6LqRZiAVco1TXoSCPnrZslayeAd+gyVM2+XF5b+sY=,tag:zRA1fDB7hMkM+Am7hTRJNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
