apiVersion: v1
data:
  cloudflare-api-token: ref+sops:///Users/josevictorferreira/Workspace/homelab-reborn/secrets/k8s-secrets.enc.yaml#cloudflare-api-token
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: '1.33'
    kubenix/project-name: ze-homelab
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
