apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:p+ldLIOVyAt7Yz7HeGT/DuZklPjlZXywV0rrxxDxSC4uFLVHQJaFriuxcqF3u0rs7TRA3QcGjhg=,iv:D+GEdtuu5WHTUKSp3P0u3qUdRYe4Nt0nSn4u3N9ozyA=,tag:jtxD7plJst1mSSEenjoOKw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.33"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPREV2elNXa3BmSW9ML2l0
            UWw3YlVkTUNpRCtDYUN3dWZSUXdVRzMzbDFZCnJvM2cwNmlaU2VoZnVqVmtqN1Ar
            U1REOEc4SCtyeW5tZ21QbzhSbHdxL0kKLS0tIGtuWnI3ZTEvZmE4ZlZta3FrL1gz
            TVdaRTdRemVFZ0tHYmc0YS9YRFlGTFEK+XqE8hNazaBusoZlZBPkn1YSaIRZ53cG
            BCAbpTO6nybt2+rzyOwu58TNu3u9l5I9NKtAr1u238vwQToZ92JkrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWlRaUkI4SEdFTmp5SDNT
            Q0pHUG1makVMYm02V2RudGEzcTNQenVaS0JBCjdldGFYVGdNYmFNV3ZYbGxYVy9Y
            d3FyQWZ2UHlTRGVvUDIrNWI5Z3RvNDQKLS0tIFZSeUcxei93cnRIUEhRcUJNVmF3
            UDRXcWhPMEsvbnNTQ2tCR3ZVT1hUVTAK52IyiVcpfGpjixq2yX3u3Eok494Y0XIn
            PNN6mCHjM1X3K9zrxBSIsz6wSYZyPb1MRaTqQcswmrGOXqo0xFFy2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZjRGeVRGQTRGUjh5dXRt
            SHZqLzhwUDBOYUw2OWhkQzRvVVcycU42akV3CldsOEN6ZkFKdnJLR05kTFh4WTN6
            VnczY2NkUDhrdmlPOEtTWkFIL0lQSjQKLS0tIDdjZnFSbWpLUGlMeHFjd0F4MjNU
            QzRURVEvS2dubWs2YmpCTFNLU3ducUEKINFwmiBg+D2+bcb22psCZZA4ZhkUzpKV
            2vXNvtZojNAzlKi5cEzT3iqMjfeR7373mVoCwJpNSb3UAV+/NJkFyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-12T20:14:54Z"
    mac: ENC[AES256_GCM,data:TcRKeBbPozncYlKjxBpjVmr7KqpDKpX64I2RVVfD2OMRXBg2rAGcIDFhPmeTSdIURvjvObmuKlDhIHnlY483i47AflFMB8wYzF+UDA5DKqJQJ308TFM+l/KDH6IP+WZaoSw1d/KCMpCYfx1wiQMNnWP1bLjWzwJ9DNW+JmtYJOE=,iv:ZCe2XBTxi5kn0IzCpKXXxcliCxVYNLm//zL2HViTfv8=,tag:hJYxbU6HreScwyF1lsHXtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
