apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:kj/3D9n/LcSNDUJb+msoVcsywmHhSu3xGtTKahS6VGOkRfIyih+iyIJaF2iOsWrzdZJtkymy7FM=,iv:2vA895mtK6dJUyT4sqJ9i0KG/A4dC190NRP6AaPsefw=,tag:IgHLJWt5rbSquplATTxUzg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdnBCeG1WOEdha0RPbXg4
            bStzcEZDUTRwd2JMbVJsWS9lZXV2NlQ5TnowCm81UEdPVW1oTUdGa0dRUGc5V2FV
            UElodzJrQ0UyWlE5VGRiK3ZoWlBDZzAKLS0tIEVjRURRYXpBdGZ2RzN1dlkra3pL
            VldwZi9RSDBUZElDczVDeXdFZEVRRnMKLsHAni590eWoIIk9OEjyGogksryWnRLt
            aZFy4nGuE2umsBbesnh0WYwIo3ESMAKax58jn04oph2D8zMhUTloiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOL0RjY2tuMXRSdm40N3F6
            YjVQNDc3RXhzdEgxTEF4b0llTlJPV0tVM25jCmpHeHNSTkFDSm1QR1FKV0h3alF2
            VUVONCtYVE9vMkJmQkhIaWVRcHNucVkKLS0tIEx5SW15VkowWDZWYk1jc3JaUXhO
            YjVSWWxjdjdoTmcvRHgwVjZwUUtoQzgKcsyB0DqfpngHmNq6RqhK6vIt7o3kguLk
            6MRZl+SuNY6y8ixaJyFOwGON3Cf6t0o6E0ShlWer+WCQD7J0o+0LOg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxb1grTTMxRVVCRDJUYnRj
            d0RJU2pIM3lZZldjM0YwNDRHUVB0MCtKRmhRCkZnaHhKRmNiL1FEZFFudUFEQmNM
            VHFVVXRvRVlJVmpqMDRxN3JMQmFLNG8KLS0tIDEzVDVGQVZiVlZkRm5uMmJHa01K
            U0ZadHIxdlk2SzhRa2R3dmd4b3FIZE0KPsynIO8+c40gMl183eHNVA7ESZCnCT01
            yokBwxZTFCFts6+IKpQdZpEoFuW6EDCGsWi1y3oy79bbhiXQPNIeSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T03:06:11Z"
    mac: ENC[AES256_GCM,data:mCW1tmaxvBslUZYDt9oNrLw++2mAMyMtq1B8dumlqPYHkKiSwszUb5CQTDbOazRXCwuTXw7/cGMaiFrUiW6BtJiNGJXkaDaiiM3fOvVS4Nty9gD26V4rlEC32hlaPAtTwD0tQnq2QILHaXw4DPPsEP2RsPoZB0CnKvnIHcOAjWk=,iv:ukL/HXKCpOP6e/Hta8XrR5D4WXUtq13fhQf0sVYCGg4=,tag:Dw7ugMPli4G0uFe3yk7Qtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
