apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:KP6Jm1W43wuzNzNM1ViC/lwykBtdTDH3CcEyOuHjXMbKWBdIrxOzDR5jWFHybe4ZTioT2mTpwPE=,iv:ZEL/KdBNOMmk5QrDzN3UxqiPezvDejZAY0Z0v1YUVS0=,tag:io0zEgoAqBFR9iSRjpPFGQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzekVCWUNSRmRPWjlpSk1H
            T0xVbHY0bTVFSFNJd1hHVm1vVUd1QVpNM1ZzCkd1OGJXVXhuSnBGZEVPekl0b1hF
            L0dxKzVoR1Q1c3htVU1TUUJIWmpyYm8KLS0tIEp6NVc1VXExUEI2U1lWV2hiZVRh
            eWZXbFc3TWk4bGh3cFBmTnZjenhwUFEKk9OyBDi/KEhqLlBXHtsobc/nakpNOaw1
            JoLH4raeJWXrZ/PcWjqYnebmWvYqCFLHTG1hpiJxuSPMO11t+j66fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNXp4TTcrSGRmbW9kMUpl
            aldpMzdhTmpEMWoxWnBlRmJBRHdjK0VNTndZCmtraHZSVTdzeTk3L3l0M2tIendT
            eDJOS3pVaW5BMFduenZkZjBOaVdsSG8KLS0tIHl5K00zb2RlT09DNkNNOEZucmlq
            bVFHRjBzbm55NW5kYktFa1dWUnFGamsKWhORpqH/biOGoA2jJvtCJLVIAFsRTH77
            Dwjfuoz1Ch8WJjhbFvZO4gb0IOluYtiBUIZw+vA4ZhDuzn1YYDC4Rg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzc0xRVjFnR2M5Nk1KcVAz
            Nk13OWRESjN4WFRzZlBUQWw4SnUweTRuMmtrCnlYK2JJRjJkZ2ZPWWtRM2l3YVgr
            S1E4Tmh4M2liZFZ6Y1h2ZE1wcUpjaXMKLS0tIG9naGtaN2NXS2V3NlU3U0ZkVjhy
            Nks2b0NsbnJFeDlJN2RtVzRQTGJzZjgK1/jbWp34R3gpxidWUU3uS7lW6NT/g2ki
            va8hh6fIve/XjtuFJDcnEjT1/ced0GUUJCTnQKFXNtDsJXdQdFFdiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T23:14:19Z"
    mac: ENC[AES256_GCM,data:kwZJKkeslBrnu2uKIdVLiyb29o1vR3CuXLd7p1d0ePhwf3Q2TXW7qt0s17aJ4vp26FBazs7QfD/WBggYI3aZcuGFHhtz+yXDdokQV0bRSqli4NCOZGOmCWvzrJgLfH+YGU5uGgq7wGPrWJTkrf5L9qSSMq9MpZWXkBdxzmqR3rE=,iv:BeD46IjsPyk+5kGPSJ6R/yMiy4wvmkCypIgKDYabQYA=,tag:x3rCmPnie1w3xX7LhJgaUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
