apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:Elz43LZIKxqll3OFFJLqxccfL4ufWMyA19JdeL7Bbsh7Atl6V5j5qthNqvAiTxDVR9piJSEXbNQ=,iv:MwJKwEnkALOtqj8oqTpnEtb6D2Eiy0TqS9puWsRwIec=,tag:HuABUvndNJDPplSRWf7BFg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRFAyUFUydFJXMjhHV0Zo
            ejVwTFpqbXZqeTZWd0VmVHZSZFZFRFpkUVNzClhoWjBtOUU4RFhrb09oc1dPcy95
            WVVhTVlaQlBBTTNjQWorTnVlT2kwN00KLS0tIDRvdVpoK1gwb2ZPbUFQNFN3R3p6
            NEVMZmZSYjNrV1RKRlRTbkRreTc2eGsKefeIymavRPNW3j7pIDmUmqEX0lbo9+Xw
            phZwZt1KqT9gn61ednI5rT2R7ZuckmIsuI1g036/6HxLA7EW7Jb8FQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT3NjR0lGcWtLcUhCQXF1
            eURqMkw3a3RmUWk5dnMvc1BWU2QzUVhKdmpRCkFsM2kxbzJ6clRTaDJBbW8zTnM2
            M2dnTGxnc3E5SHdLSEc0RUdWZE5Qb0UKLS0tIFZFZENNeFV1QVFLS0x1NzI3RHRE
            YTR0cktpVThJbkpISTV5WDMrbm8yak0KuuVL73eT6fXG+btcUZDJc8zpIt/KWQn0
            5wRUlyfvwTHiNlykEcu9GypUsp7mnXnpSg75eNivy4eYNe55FELi1A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dVhmWWFZaml3cWVkVS81
            SDhNblJnekNZbkpRYjhPVS9iaFZWUjFRUmp3CnE5VWhRM2ZoT21GK1hiNUhrb3BF
            ZW1kOGtFbHRWVDFLU0doVkUwMmZBbkUKLS0tIEVkdmxxUUJBZlBwdDgxTU80UFdm
            Z2pBbnBqeSt6TFpyZnRweFY3ZnA1T0EKYmgGcMEWrxxmWqR2z8SWff/EnW3MMy1U
            FoAToo1GHbRjwXSfUxXvfLNzgQJ/h3Hupdiyc9NY4gPtInpt2uVolQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T17:57:19Z"
    mac: ENC[AES256_GCM,data:tJTXMcwFbP/FFY6SUZCms+ywG+ePol+BHnPlux2T42EW9WZXhJTtWpT3TZNKURfunN8KsJT9dm7Di9VxTzMoagU1vjo5KubJOZVzw2ab9H45oD7+BwRwFXK9i8BKxSiaOu6i5Eh/dfRh9M82x20yC/Ncryxg4bPPUtEYFkwPIw4=,iv:dDEWDFTo/NZ+GpAULJXdi7U2w6Tv8txR5MMa7YphAHQ=,tag:9LQZuwKcKyYzEvVrE9nRmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
