apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:B2AreOYP9Hw7yEkvE3dfuwgt5Xw7ozWuY0agC3CgLXEwhTeX1ELAApdywm1w59qQzQ1Rv2IySfg=,iv:ZgoimjyQkVuo/ISty5Khx7wk5VP4Hw1Vnz+7PNNJpOA=,tag:2oFuWxosIhUOqRLhfQqEaQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.33"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSitmeFk5cnM5dkNteW9k
            aGdVZXBGclNQTjlWZkVsSmI2VkRpRml2Z1FRCnRvMFBFQnU3d2VaOHVIalFRMXM2
            Z3ZYM2ZGWUlWUUVaNnhybUFQYzZYWjgKLS0tIExjNmJmL29MVzY1cHJNZkUyamlN
            ZUU4OUV2WTdIT2M4SlVRck5EOVRjSTQKqMzadonw6GmXQJ531HLIbdFZ2JFlmSKF
            OHcteGxrSPC41XSl+BE7UvlHOnpmMUulZ6muUVswDnOR4TZwm/ko+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOEV0WEtidExoV2lUV3dK
            R1Rsa1I5a1RPY09yR3Q0UUJHdkNpajc4N0E0CktPSlp6cU5mTVZpYVdrY1lQV0NN
            aEp2MEs2MElTUCtUendyM3Z6UHFTME0KLS0tIG9Gc0pqdzhLMjFDR25vaTFRaWRW
            eUZodS8raEZWSEVhdDRJVndtM3BUbG8KBdKf4Ug7tkabCtbo9OhxV4IIP89palXy
            T6+ls1SgsWyEpTSrXZKFhhNP91JO3douV6QxEVQWfuA9hQ6TeF7oQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZFhYWU1QQUNOYkhzTGhE
            WUtaWCthODBodFZaYjhGOHcwMHN1dkFYQmowCmlxYjJNMVV2ZkFmUUVkQXp1WlM0
            ZUdhTXRSUnRUMVlDZW9JdzVhMjhJVVkKLS0tIDdaMVZSejJQRWNOakpFQ29hUTJH
            ZVJyaUZLUTIza2Z3ZUR2MUZPdVJFOWsKT7iPy/Gd6qNeVBupB2StjVO0S4SkjNCS
            sGUTGY5wJ6v+5GrX6qkcY+ibEqCuxE3Cfnl9oXEMoko5AuuE72zk3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T01:21:29Z"
    mac: ENC[AES256_GCM,data:8xnj9qc0sEeP7aF2d9IdBBs8iiB6beTkp2CHVig96I1l4lfRlZdpM4EPStAPg7piqmr5v3YXrmRxUYLE2MsYudYdD3UkXY3wXnMP5/exgbTm76pXCxSar64zKUxwh2JVR15ohDZT/mx/jzxFLWaQWy4BNriuacOm6i9USRCl76w=,iv:p7GdzkIiqqOXGnWmHmJLmHlvc9j33Xq9GWgza9zwkhw=,tag:PWapXyVOokPIcO0KSqT8Qg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
