apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:pBGAp9TAk+8LaEj4qjtBVKIHY+R/bheHpGvJp6xsq1Zi7mqy1zb3odybTQbNMLwL0ZOOulZOtqo=,iv:N71PorMZ1RWak0veHBFHlEju+FTXOqhDbqqscorzpdM=,tag:rngiJ5kSQQc+5dsSkVBJxw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWTN2Y2d3clZ5Y0NiQkdi
            QXU4dDhqbjJNM1o3b2Y0Z0tDNmU3bEhWV213ClpiNDZFdnVYWGRCK2ZlQTN4RjJB
            S0RuaHlaODhCOUxGZU4rTGlIVEFPazQKLS0tIGZZaVZkZ1pqdTdqTTBKZ21wQW9w
            TFAyMG1mclg5U0M0YlBTVXo3dU9hV28K8egqEYJlcjFRapp+i0qwEGeIhUNeVQi6
            Cnt/lTQ8ha7OmUCoqyQp7qyw9giZkaApQeJ1mu+ookwJ6zW/FMUIkA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb1FtNzZ4MUFxRUp0VGc4
            REdjQ1ZyT0xFeE5uYTF0d1dQcHVCQ2prbWkwCjBqcmh6ZjBJVSsxZWJ5NmFzRExK
            R3pVZFZ0VlQ3SWo0UVozUWREcVF3NlEKLS0tIGZVZEJFOXhtalVWVmNpbDd0WTZh
            OFJGcnkxK09iN29NWGxlWTVqWm9NeGMKKzbgowhuvOm4VObKkKiiG/c6FGgLb3tb
            CDeEvcc9WYq34g8geh0frfZ/TXEijkJlcx7uaaFombbGzRINi1XAHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cGZnK255dk1nUytXZXRt
            UnZMQ3pxdEZkakNxdkhTWnZzdXBEUUcxSnhBCk1RWGQyek04RW12ZXMyN0dmTkJF
            ZitoeXcvaHdZVkJhTjdxcFVpRDczQ1EKLS0tIHB6TDUvYUtoY2xRa2M5NzNYbXlk
            Wjl4M3E3ZmF4OWxZNE93VDVvOWtsN2sK0mXv0EoekToF3UUx8ILzzldxCK4XdX9p
            J/V+Br0zyxlU7fgSyCyQkJTo1VkfSOSXKBGxJjqQDC7z6lvL6i6lUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T17:50:35Z"
    mac: ENC[AES256_GCM,data:3ikuqHOkLAb3788mkb6xt9vlnT1kueGVBUjPkGaqvt9Mp0Yy7MQhw3lCuY4NMQid+5iy5Ipfi1o2ismqmOv8+u9AGbrNhh3bBkA4+H+tR12kZp1XCN07IarHmr9J2NW9arI3e/FutVsWuia8XD2DQGfO1mmN+0BXoc+0qxQkQu4=,iv:CbJ57C7Szgh8L0oUMfC3eYOXvCpSFgvHo7RZ7KZxSKQ=,tag:hE/srALqcyMMTHYkrOE3kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
