apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:YfqV6t5eb2YP5j5XabtSAMcPjIB81xlsBXqWxJbLEq3Ot+/g/m11EzteJxvBRjA3hadjtS7Dhgs=,iv:pXp7K1Grv1VjlGeupgLtSOKvOq+L+bgVWOIBSHCXlHU=,tag:yZDI9t38j8Oc6IENkUlpYA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTVo5cXVQZHVlMnFWZyth
            enhDSlp3bWJDTmRzZHk5Wms2UkJWQ3djSFZjCndDSUk1SDc1R281amh1d2Q4b0VE
            RFdnN0QwY1UvM093MTNyQWNSRVorMkUKLS0tIGhwcktRZW1VRmx1dFVheDNkVWdN
            eHd5bUlvNVVmZ3NQeWlSemVuMjJFaDAKYLnTC2Hk/vIWbfhdyw/o9tLnsE2nhHei
            6Ia3p697z+k7FtM+6u8GQS/K3T7XlvcMjDQGhFtJmOdRYWLRVGizGQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOWR5WDlUNFR0Y01qMmRZ
            K2w0dW9ZUk5wUmxTL3ZlNUpJWCtpZTFiOW00CmFFUC83ZkZjYXRsc0hOaVEzOFd3
            RWhid1RlcjFFZHB3a1lNNGoveXlrZ3MKLS0tIGV1YzQvSDdZQWkyVThTQWhjWHQ4
            ajRJSVU4TjhLS2lJMEFlc2tIWmo2MWsKJ4L3/EAyxz00kHyCCdilS8gQv6u/jn81
            TPz8kR1yW4YIkAtT0mDWtkgLEvv1YRgXhaD1KFxJ9df63XDy04RMlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaHJaZ09CVjNtaEpOTlhj
            dk5TdkhSMXJ6QnN5Q1I2YkdDQnJVQXc5WHowCktGd1diSnMxa3JRMFRHRWI2S2ll
            K1lhbmI3ZXc3bmlnRkxSL3ptVXppVU0KLS0tIDY4WlN4cmRpdGNqUXV2WVI1TDlk
            aklqQnRZY3Zvc1dOSDVDRTdVR0VMUkkKsqorHbY9bwn+7ZNfrLB/X+1px5qzFatu
            4BJKIvBWm56rBnKBBzFufQmfMalloFm36qYR61KOOfJsQuXwZqT6cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T13:25:10Z"
    mac: ENC[AES256_GCM,data:/0Ip65Bipvtg/HKE3WmYLG3pW6SVCkwSHzgmLPphV1jrg3H0q42ekcccGAA4CxTZ81rvgvIcfL3+2sEA5k4ahgNSr39IKDd4nlUSiTtWdtaIsTnUoD/8t6mUMpXtpucp0nRqvuXNDK9CLBpFHFh6HjHxw2xETHFjx7Hi7u/CRRg=,iv:e7jUvWgrd8gFKb17ExyYnCRPJYmGfkxpi4C2o+h+Nuk=,tag:MxtU+g6EvTxoBE6obVr8MQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
