apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:Z4R/QchnzJZSRgT+eS/TW8SQlbO4hv46hgR/ckjk/HPHKJMsWNGlyAeC6CJZ6DGf6LoLUJ45VS0=,iv:Lig+/MFy2grGBzOuhmrGq6YG1vORuc+Jn67cdsZFor4=,tag:VA0JLqygx6JiKBJOJwVetw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.33"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UmtyZWx4SGNhSmVPTis4
            NERBemlDZlVEZzY0dlNjZzlUWXplWmhKNzFRCkFtWVJpRllSd3k0Sk0rVmhMSnNl
            bEI4RjJDZWtLSWlhV2FaUkkzc2ZXUTAKLS0tIGpvc012REN3bis1akpvTWlVSUFI
            Rm93cEFkaU1KSlNoa0VhTk9MZmtoU0EK2c106hqJorpo58h2ojbON7SaF6Id5LCm
            3QpBg8DrUNeK/9vStA32teWgMX5EHpk4+C9BNEZLQa93VMLxkFzqsg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTT1k2ZjBQRlVmQnBEMENw
            OWlHVlpCOUxBejhOZ2xibXVqS2hyTEYwbUVNCm5GdFB1SVNWNFVtalIrQ2dOa3dL
            U3JzaUFXSE0wYXJDYS96VnRIVGJZeU0KLS0tIHZva1pid1hKN3lVM3lYV0Q2RU1H
            STZCMGFBVG9aeTdJVzN6QTdEbEJhcTgKagecBerqKC8J36H4g+96H3sENh8I6oNA
            uM0akmo0555ECwNqQ14R2pOshv0mfT6r2ffQQflrb7rvLV9XxHMUnw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYWIwcVhDbWN6b0wyM2VN
            NHFscVBHWWpRbERQRm9LbFc5ejJNam1ycTN3CjBYTHhrdUZIVlpiT2Q3blMzeVV5
            SHNGbm1JaW9WNUR5cGFTR0dLNGlMOG8KLS0tIHNYakJvMmNzcFh6TEhiK3FJYzM3
            SElQeWlDaXBZc0FMMmh2VTFvTStlSVkKBe8T1Dhi5EB/e1qPCk0BgEL7q3A8JfAB
            T9J6FD+mcshHWrpkqqhiiapZM16deht6kl2dLGjMcALFTJrT+IO8jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-12T20:25:44Z"
    mac: ENC[AES256_GCM,data:2i28bijcm6t7oHcnMjtSWsl7oGgrv8h+7pT32JV6bX7giAhe4sm+85inlcgWWUuk+6tTNWwk/NF1BwnACjclMYA8NiEYCZIEFQrMS0GDFZhFiDPiVy1jN3dGaWl+0WOOt6ZYF6p3mSXWT1Ng6Qqy0ExAz+D8eCFslB5SrOsx7Ok=,iv:dREVVLW1WJZR0WDyZykIcC3tHsfxNJzSdTN+nfyvb14=,tag:lqVveMuKY6MFxZ4T+e/yTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
