apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:ou7VckxVwf13puSrzUhKtPEWizQThvvzCGLZ3j/yFotAmE+4Mny2oPeVKuDUMsLnJyxnxYyU0RQ=,iv:M/1aVA5ygRDn/eDIjY+lIWtUqexe3l1dqkLsksTJGBE=,tag:YW/ytjJ0+ulkUtKlpBMAyw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR3RqTC9wKysxb3JhS2hT
            L0t2UHNVMXp4OGYwamEvZmF0dG9MQkcyam1vCk0zU0JxalU5NHl5OUJIZG5HRUNB
            YVA2U0VrWHBOcUpNbW1zYm1EekZPN28KLS0tIDNrbktmZnFEUmltczBrbnFLRXRt
            dEh3Y1RYeVhaZ1dHN1Nnc05sMWRjeE0KY+yNyd+sIHeqJ/RoZEjeq6ZSd1W9yqvJ
            bVxtNtbQ3aKb7St7e6M1Ego+N+gGOQ4SJSnjNqb7kIaOar4FL0BW0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK1NaU0VralBHWFdXZ1RU
            SGR4TE1IRkZJUWh3NlNoWmF4djZXVzdnL0VNCngxUFYwakd5UkJsUjM0M3dLZXNQ
            UENEZUdkY0hPWHJLL1lOTHVUOWlpNzAKLS0tIEJGeHErek9IY0dnaXNWa25vY2ZR
            c0d0K0NGd0lZWlNRaGJzSDlWVTZaek0KP6VkS2lTrwrwpOSuI+KP4g74CFx5s1ze
            D1YR8FADDzPEfh85VmyetEGfS6DofpiaKMFH3Ly0r8NAR28Ue9PxbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMXZ6dmRCNnNiQ2F2bEwz
            L2VFa2tRVnFZeTYrMmVPcVhKaVlSa0YxRzFNClludFBEdGFXOW9lT1gyT2lRMmh4
            M09laDdwY0N5cGcyNktzcGlObW1XUjQKLS0tIEFIUmZ6SDhQSU5kU2RsR1EzamZ6
            ZU40Z2xMTm9LMzREa1Iwb1NFNmN2U0EKrCEZUOzsESKq31AIkSZJfTEfPPjf7iVG
            awcFiuMk5LHH0g6Qkm5CTHqa3apPbELJeEPjxC2wfNx9TgP1+zHd4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T15:51:06Z"
    mac: ENC[AES256_GCM,data:ZNMtR3MjhYZ3MoHnybBsfclnY5K5hE2jJFvRR/G+IxKT1wJgvksezAMHKS5z1lqUdMWzn0Vtrj4FX7AHMwDh0Kc3WBpDW0yKaLhivYiP60+z1k4LM6uhqgUDjI/vzkaSaSK5LaYkfaPdyI0jDnA8HCqX5knfYt9Wq6x7BFhVBwo=,iv:Q2XLQbyQ2QJSrHzMpz9EmHkLQ0FCJpetnIiQAWGdZ4E=,tag:46yK3RMoxT7LxuQTyF2urg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
