apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:6eSCH/PQgCEBs7UYoNKQ2ULgHT9ih4mM3WVs4HaaVP24FHRYIUygbQ41ldC0ytZAUCpjzewDntM=,iv:fafvWIWV288OSO8U2UNFJRRO6QJ1kKjWTOh+x/iED30=,tag:2V7qra+qyvgXVUD4leHv2Q==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Q0U3alVQTWUxRU9GMG9s
            amlKOWlLZkYrSnVoRTRxSGhOYkF6Z3VLQmk4CjMzYzU3UDJGY2xDWjhFcUhONGhG
            aFp1WC9HeUtCVUttMWJQRHRMYk5zY2MKLS0tIElwNWpYRDJLek54c1NaTDlMaHdz
            eEJYRDB3b0pldnBUc01TRlJjNFdVeHcKgeVqQqFkd/bDvi/a8UuIAcI0KZYXds8z
            dmGTi3qU9n5ro+kpdnLxIjTRxTSAxalCpGRiMtGLZ5umyOsfwNxxgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWGlMaW9rMzE1cStZNnZP
            UDZWaXpJTWRFcjdiT0cva1ltU3Bmb3pzWFNvCkQ1MG9KNzAzUFUwb0ltaGQvcHo1
            bWFtVnZFR1BWdGYxOCt3cW80WlAxd00KLS0tIGVpVnBHN0wwK2g1RFFmbHdUM0pS
            aTVwN1RuZEp0eWNTWFJrVmg2cFNnWXcKOY82wWTlw6HWt+1MVgUWbuCRbuPxnTLI
            96AY+nX4UjrON8mrybQrw00IJaZDkd+Ocr0lyThFrfGttH3VdwYDAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWTZUeHcxQkducm42NGhC
            UEhEWXhZaytHL2pKbjZsa1V4Rkdrc0tRZ3cwCnN6eHA1QjlHNktYVWM2c01TeS9l
            QmZtVERQUXhOTG9KOGFLdXNtWTZIbVEKLS0tIHZpQThkVjA4em04eWowcmdMY1pT
            d1VBWXlrQlJLN2lsYm55UWNzRExEdlEKgCWSjfdV6Y2llKYale68hU9C4Zosu9Uo
            MHtgMpoZcYnXCT+U1ZKNG3PGCY6jkj0IxppSS45OvtsKWNl8+y+JDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T23:42:39Z"
    mac: ENC[AES256_GCM,data:9uwk2xRTY7fTq9dYTXXEQbpoYMcHbawFuMmSOM9etvVzmgEZ4EW/TjibOmPxc7DJCYfvj21RBxse8xFuA09rbGXGYOUNM/p4etpPdgBfFElMKqUlZBjuNVp1eCYzZyzs3xiEeWuY9U7x3XuMFq4n6YhAUD+Bdt6PO9nStLb+OS8=,iv:IF2+/vv2aU6/bSsvQye31/SmsMejTme95qvD2XBOxAk=,tag:A8hhBzCm0WJmC9LMrUl4zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
