apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:TBtJg6qohoafLQM9w1CiZMuQIt7tf1CUntRg9eG6Q3voR83kwVV/v6S37hnD0nU8U1IGOlZwoqo=,iv:kOe5CIP8KsG3QTqYN6YAMpNxmyfKhDKNlVckys7nVGw=,tag:jj9Fxkg0UbZ9sU//FYi69w==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ05SYzRvZTFlcUdCSlgy
            QTh4MUdLcWM2OFVXTzNVV0xhQmhMblYrNkVFCm1KY1lLLzB5VUdjVHBleTNxbDNX
            d1M1S08zRTZxWDlGY3AxaTA4N1VHR3cKLS0tIFg2aTd0MTVhTXlyaUE2aE96dys5
            cjlLWTBxY3hSS3FBY0Z0RE5BSStGT00Kf36ZlkNVzQOCyXe4BbIMzTBegLN0iUof
            WRxz8zq6pOsS3g0QsMQG0PBeB2a+zi+MuwVtLMLQWsUdimn3SSrIeg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aWV6NHRVR3JnKzNMa2ND
            NWNwUFM5L1pJZGQyNTJuanNsQ2N5MHVuQ1U0Cm0rK2haekREWE5MVEFzMUlwaFhn
            K0IwZ1hXTkhoeXcrV3lTbEt2bWdpKzgKLS0tIEZpT0dsaGJva01SNGw3UU1ReHJa
            RzU4aHNHU2hydzMxTXBYUWdDVENOeDgKUSbJLnH6nem8ZXL/Q/164WIzK2FFgdEm
            xB+Cl39Ua/OYaluUjMKV77JMCRD7TQ0s9iNWXwZyjtWYCRd/ZZwR8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeGNzUmUrTzYreFlnNVRK
            bmY4OEtHdk40SWE1aVU0ajV2Mk04cHJUd0YwClZSK0ZkVG1uRXNsL0hjWXlDMEpv
            RTd5M3pDZnphZGJyQ0ZaRDBMOW5sOVkKLS0tIHNkODRPNTN6djM3T2RkRWo3TWRG
            RVpKdGVqa3A1SGlwYVdPRCtNTWRzK0EKPn4GU7aQa92asY2TlKMgdTofeHhelAFL
            eQA4ORCKSGa6M5y3B5FKqybRjstI6xpz7/mAvsQPcLH7RnaBIxUZog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T23:58:25Z"
    mac: ENC[AES256_GCM,data:EGJ5aeMTTRxtsUQsBqg2g1KfIK4LFCJhWAa6h1+C1eO8EmarLNlUrP0s3cCa4U97uY8nvlj1MwOvtSpEdJHtIVLsoa1y32TxDRcA53U5ohOfp59Vg7u9Lnmhmj1lgrBO1Hm7Jz7JyCXyBw7ajjafRwr3UwC2hQPut+BKJFU8UGc=,iv:/jXz3OwGyRA68AMltZUHGumoFQ23AaDDOTte3xCKl2s=,tag:G7MOAmy1hWhrF6J0Mb4fdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
