apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:R+kg+JSh6gsjgi0hMLYEBcbqJWtgY7W0Vl1wGOWLE18tn6I2oFn/olQVv++2RI7XlTBE1yyhuBk=,iv:Bkjtwd/Zd2KvU1M4WSvI7Z6PrEGr9OjydNhnl0e5IYk=,tag:rxMDvu+cRcFJZJB7GcTbhQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ1JSSGdHSW9lNzhsS3dH
            d2ZVNTRVc0dEWXNwUXBzRWhHWUZwcmZwbjBVCmMzT2EvbXdVaXFZTlV2MlRPSVlG
            RnhKZ3ZwcXBSWW1CL2pvV1hBZDNTNFEKLS0tIDY1d05QNzBRVldVc3hBdWszdlZq
            anJBSGw3RXI5YTZlSVZlaEdvMDIvVm8KuzAXNgtVSZ0B4HDOISCMtIw154ZADZ2o
            324Ze+xOOI84XL57zXdXwCtpix5QIpjphC7sSERfx9++Fas18adFjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMnVSZTE1QjBQUGRNUzJh
            TWRzMXR3OE5aU1h5a0MwUEZNL2tQZHhBeHcwCmEwbll3Y1YzVFNhL2dnWkpZM3RT
            S0hCalR6R2ZMTWx5SHpzTjhQWnNmUkEKLS0tIFM1NVZCNkgvMlJQeE9BeERNMTJn
            eDVVZzBFYW92VWVtVzU2aXdja3lwQncKDqlBaJLCy2hL7bQPYTW9PNjlDQBrt/qA
            M6aLutHy1mc8e/Sls7LaiiKfwH7KQdtrCSJHxUJ1AYdXfQ9TXP1nRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROUxaa01oWXpyR0c4aTdi
            NUgvVHBDQ3hPTFhxclhrd0xXNzVPVFZXdzE0ClVoaG1RY1BnazQ5N1U1SjBwbnVE
            L0F4OWxNK2VERmV0UnF3WXFWMTg0YzQKLS0tIGN6QWxGbUxUSDRzaWhWVW95UTlR
            Um5IRTM1ZVVkV09SdENGQ2UydGZmMm8K07JzRT9bWaoL+kd7EkQVirfAnShCbAZo
            NxwLxf+MdQuUiw8NqAF58o/hWHc2EFpbLWwNdopR4Sj9bpdanCt2Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T13:29:25Z"
    mac: ENC[AES256_GCM,data:JL56t7K2JEDk/nURQ86OvIxBdTpdygqq4V0zplOKCU0yoY4Iia+1WmLaWNud+RYQhEwMFD0UsJUXySFOUQDDHvucNCg0xdOmlFTy7EL8jvjpPm2EG9QxwIkrXfEUHx2OwYZLmed3yE/sKTSH/mvLsyobqrA0LMYpfYF8LuzlLZs=,iv:r8EmDF4c62ddZ16mBTHNXaaqaPNFO7JKgvpWVnjCvTY=,tag:OVPvmuCflsqfOatjtzurxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
