apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:YX6lKEQWeKIQZl9QgO+eZr377e/DCAfE8MOAfgFjq+lPBLN99ZPdv9EksFVW13hbwGVHQbSvzFk=,iv:B5W4Uo5TJgRQQvf2qqlGS5dhA+wAxhiFhGKj0laJ/kk=,tag:LxJNAyXuaM+7f3thFkaEKw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVE8yZWNkbkRCS2RxeUZw
            bWxxVXd2NkU0VnlFTzI4em9nMk1VVmNkMFhZCjFXR00rVGpZYTViay9kbnc4emoy
            aDVJbURwTzlRaVZRN0ZQaDdaMGJrTkkKLS0tIHdwdTdlSDhvR21Fd3ZnaTd1UExL
            NGZWN1FxQi9KTTAwV0lPNmVHZmt6eG8KQKXn9CFupIVIptcRYHCl/Vb0uLXmiRsR
            BWKRISB+2VItLVXg1e4fulmYR72pixfXWVpgLu7SOO5oXPnkq9ZsbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb1hWWGJpY24wdURVY05u
            ZkNmcWpTak1LZWIzb0IrQUdqL0VxNXYrWm0wCjZ5VWF5dkhUc3dBRXJOS3dmM25R
            Rk5FOVVhS1AvS2xPRVdiQzl0N1I3aWMKLS0tIEt2d2R4ejFlV2txR2hYN0dhSmVR
            d3cweDNpVUNNdVhVZTlqNGVnV0wxaW8K5h7bK7kF4YC5QQ//62Vo3SZh0j/ApB8N
            qZqVLFkXhunFxyYGmPxvQPhAkwEVUpBR7vRo1M8hEDHBnOYIViM7NQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMEE3YWhhTmtpbVhWK2s3
            N0tEblFnSGlqamNrMVpKeC9KUDZvNXJ2NVg0Cm0vd1NLODY2MHF5VTdWeC9PSlc1
            aS9xSlA1aWFoV1JHRFVLSEZrNnFGT2MKLS0tIEhhZUJUdE9qVHRXbXo4eGpqcW9n
            MDhYZ2VFdFJISUE1VWR6YzhZcG5kQVUKkW7Cuaq2t0VRyavE+J3nt4TFcq+sUKg7
            W75Ls9uzGbGFbO3+Uj5PJqM2MRipYOlP1nDSRzPuYQUot7/2K7aaog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:25:40Z"
    mac: ENC[AES256_GCM,data:2UHrgJfvaMq6U8sV+kbEPeC2eRLWk74ZmjKtgVebrgXSqtl96kfbYrB3Ukh/k+eP/EjcgAUKx0iyzPXq0BoUigHIygmv/Ij4p+i7uwJy6etD5wgpvN/4WANuiJ32xbZS0S9JvLBQXc2Bne+RfpfN+zf0X8NJMNjcCM+SINfOoWA=,iv:htk1KZQmx/NWgx2Viz1any6vooRHJTzuE6IksRkWjdE=,tag:tnLedSy63svFbFmweDHNLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
