apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:utBZUJLtbVpHb8Tvp6b9jN1u3ucaq4WvAjcfvB+x3vWVx0O7HeJ3A8EIGUCkP0KCoExnrjmpTwY=,iv:CqQc1W44o/oBmycoZDBWnAzAGo6NMDXk7C+B3fudAS8=,tag:GcjsHn7KZ8dblLRd5e6iCw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb0J0aHp6TGNzb2R4Y3Rv
            bXlaU0VGOHcvM3l2bFRmUXJSTFV5UjE2ZTFBCjNKUjB4K29vaXhiMEVueXlsYzhj
            UkJnS0lEV1dneVNkUDg2TmlzTmxHdmsKLS0tIERtNGs1dkNMZXpzZWc0eitsME55
            aEpBd1JBRm94U0NuWnZKWEV4R2NodEkKR55LVEu8Jv8bLonGRkMqrm6FDPP4NRwK
            T0qAf6GNe24/b2hAzyH9DB0u3R8An4VCaFidmQ76/GBh5rRjso/M3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrb3lvaFpuT1NLQ21hankz
            OXFBL1BDbUV0M2IwN1dTZkk0L3I1a1cwbzNzCnBZMnhEZjlOa3NINndRekVycEJF
            YWJ6MnM2VTBzek9XdmhJekt6cXdUUDgKLS0tIHI0amkxc2hTYURkTjU3WTBSU2hB
            dnhhWUFJeDhkM1Y0ZFRKWHpqZktxeVEKsbI7jTvxQY+zghI28cRPdYxje6hOrENK
            zA2Ex6beIqjD5yGZRYZDq5jcVZ5mxIIJQwZF7NlmZEl5ww/ruCt6pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Nmx2ODFzSW1Rc3U1eDJQ
            alk1eFJLUmltRGFDVnBuMGxjbHg4dUtsQkZFCjg4cnZHd0F6TjVmaU8yVjZ5ZU42
            ekRHaXNDRlMxSnU3bDArM2V3eGdLUXMKLS0tIHZFdkRPVE1DWU5RTThjb2hIS0Fw
            c1ZMQWF6c0U1dGZXSnlFU09oaTBlT3cKdLGRSPrg/shvb2PQEp1ZOvBE+1lz814C
            Xfew9AX7uiIpsqwGaM49pSp/OXkA8TSlp/ykLT/3Zo0Gy2KB8x8JZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T16:54:06Z"
    mac: ENC[AES256_GCM,data:CmXExX0/oRBT8zbeeH+FKfXPFhFbcMrszrgwPbhStI3MkI73Hq3rhG37jphlfeysRqpGLE53ZqkR1jk++lhUJJE1rB0cd7Vp0ZoocsPNwUqKcQmsoiMiwKEj4h1U9VP+U6XuyBXhNUpVHQkG7pU1hXUe6wLwSmV0UrprAGX+C/M=,iv:7VHPYgcFWKhi6Tn+BTOb5f+jOGWXV5JKDNE5oN+WXj0=,tag:es7RYYhUK3XMowDZLpJSNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
