apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:4R0XYwOsbPXIfw6DLglVuZ2mz2pbSkCzrtNR34NpDGmTxFg8PvnnxGo+/5Viqhf3eZG/TC6ImA4=,iv:z/Ldx5YgNNCGT5JY6LHnTASDBJhTwDP7pKAIjFTGepk=,tag:l8L5aWe7BMRkMC4+0/UXmg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RldmRGh6dXRZSm9pRmEv
            cVByS21SYWQ1Y3VhZEs1bnM2QjFtbFpxSWt3Cjl4cDhjK3o2VnRRVEVRK01mWEFV
            bUdEait0T1ppRjB5UGsyZkRrZjA5OFkKLS0tIDFSOWNyM2VPZkZoUTFVZWZsdlIw
            QS9ET2xzRzB2VmpkT1ZDMDc0dzE4T1kKSs0whtYMP0jTQRzTdW5Ix7e0sKU8QfBc
            oEaWfLkx0uHrrzT6wf5Wbsw2ku2GKQiBE85dZNf/yPeVBV9XbyzbeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVkhlcUl1Mit5bFNYbVMz
            WjdzWStnR3VrSmMvMnJORk82N25hbnU5OEFrCkR3ZElpZXRRUGRGRitWQzhOZlFj
            K2t3SmZrWU1nUHBwSERmWjNRdFRBWUEKLS0tIHlCOTgvNVQ5cUFVcmQ0RXNsQ254
            dm5pU0VjL1FOY2ZMQnNjc3lCaVZaTlUK0aDdPdzkwunzFMeRDe+p+IxUZ0h860vV
            vVhY2qkmkNh4Myt1eaHhMGUJOBCeScqPUssU5CloSwO2WvUSdT/Szw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaamRSeEtnN2wzNXczaWlS
            MmNKamVUekY2VmdmRXdPeGI0TWUvQmNFYUZBCnFOL1dQVGxVNFg1a01DeHNOOHkr
            Sm0vcDFEcFJmRzJVRURrYjNmSWN6TUkKLS0tIG1Mb0drV1Q2QWxGeG5KQmtPaGIx
            MWRGUEt1YU9TUVJhY2UzL0pHNFpKS1EKiQucLhVlGRZKHMJiDfCoWT73Wk6mqQ6x
            0KJyedxEwJ9UZE2EUFQs1X28vd5zPDs83pPTvJASLjvNWuTHBRmatg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T03:27:44Z"
    mac: ENC[AES256_GCM,data:2HpxHrL2jCj+/+8QTh80xRm1T+0fsKoBsblM9OUbHXcN1IkIIdUsq6UQ8umS3xTHoTO5+1RJFsuz4q9BVAT/rlkv5gu1f7sufTL5NTjXLL/pp6fKn+QSCH0h+yyRJM3srz0M9xwSlkAvohB9RQuqxLMQRScv9CNtF1Bz1MbnM44=,iv:uySrM8UNuVcTS1zsDIlcG3MYSiaqxicmpQfXWbnsy1A=,tag:x3190lGsQtRZ4qg9L51sKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
