apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:PAlPx+3Oxk1fbVh1Pq4W4x2MPDyS2BWB8KrzD1pfjP6eQRfdaClfFbkb9sj/w+M7kL2Qd6B2B4k=,iv:W45fHnYj1CFpZ2l1THq5hIL7b3ztMAC5rMLJnp83ac4=,tag:rq/g/7tfFfkbG3A5Jq2WJg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweHZLakdKaWdKWWNWbmN4
            TTlZMjFPano4S0VyODhScWNkbkRDaXlvT0RzCmx2MHJTRDJWQlpoSHkwSlA5ZkdU
            RmxsbDh5UXQzcEh0Q1g2Z1RQTmpFeHMKLS0tIEZVK29QNHlzZVVaWXdmVE9wRFIr
            UHA3bU41cFkrOG9Ba1drRGJEZGszZVUK01wWXCUiugKT9w+NFrCEaKM3jQfRdqSt
            DNXl7Kuju4yjBm87d7fKid1faQodnphLPYNBPR6xVr0ztZOT+CmoSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEckxoenIzbzl6VEt6SVNa
            bUo0T3NLd1JLRDlpVVBGakFRUVFIaXliams4Citxd0VpRVJlK0Fpcnp6c0t2QVh6
            WDA5czdLeGxMREZrV05JczhVUXBPTGsKLS0tIE8vK25pOWFRS2ZTZ3I0QStJWE5Y
            ZDRTNkVRSFF5RlFvcmtQaWltRGpQcXMKgp/sgmVpPWrjxmDqUh3+Yos5qVfLwD3N
            BJlHubS51EzaZNJ0qJV2Ty0R3jBZcv2B1dH0BI7IeTb+KkELx0458Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbE1rNytodnZKR0JwZWYw
            cUV6MHk1aThIMkZXNnFiS2tjdjNjaEU2TDMwCkR2WVcyb1VlSHd2RitOVTErY08w
            QXczNmJBaTl6cWxUS01CMlZNaWlpK0UKLS0tIDRzenlpblZGSmwybnRxVkFZNEFh
            QWQyVTh3Nmg4VERvR2lod29HR0NFc3cKHQBIDQy7BzT9ujxQwTVUqLcjHNF0QT/M
            g+uZAodqXcyNq+LvqFWIXOvVALyQ1Jr7bH/nsfJ0VLfWX0BcRO1pkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T17:11:05Z"
    mac: ENC[AES256_GCM,data:humr5eRe7UogZwyYcDktFVcp3ZflbSPic/a1+pN1pfp915Vok9XUBAVC+y0iTbwt7oIVpFNSTKTDjgdzlsFkA7cW4YRkTjn43FZoz/AogSmwwxPz69PYJ+pc8S8Bs01dJjT6hR0a6ITejKbvBQ0RYNhSLZDdftKZfgGzuWftQBg=,iv:XJwOakC+dYpilaZ8hoj03fos1ij6CEFO7HZ4s3kHgmw=,tag:F5fzeKNK6jBQnHACg9RAZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
