apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:Em5FADl22sQebWfh9xe3JN3bEeHzOP7ptuSjIXz1h4DzSQCJ7o6DkcAx+cXbqc/O75WDn7oVUZs=,iv:RpcPx3PCyfaWrg/cPFVBIC6bM7cvdk89BDP1PRAJGz0=,tag:D4G9sdxYhuVWc+qYsjxCHA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONC9QSDZLVGkxdXpzUkdn
            Mmh5d0VNZjIrTmJJM3FTRXVsTGFzelR3d3g0CjlLVnR6TjQ3cG1oVlhZS2JRUzEz
            R3djaldqWUJuYVhXNWlTd3ROcHdiY0UKLS0tIG5pQytTSDl1dEFZOVJib3Vycjdx
            MzBjNFhscjI5MHZCaGJSYllJUmJRVWcK5Lnq0dgESmjw4tlow0UZVq6R4+MWFaRq
            CuClfQotu1baOhaAqUYNKl3MbKQvNs2+y/NSe5hLwvgmOQn47ZzzpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd1B6alY1bkxEVTJ6SGpU
            bmpyRU1mSHpIWDFGNXdxZStrdGt1empPY1Y0CnQ5ZDlJdlg5L0pKODdkRU1EOGVu
            OWJGakNDUkQ0L3FCMmlybWtNM3lmL2sKLS0tIHMwRUNRdE11ZTVGNklGKzNwTXc4
            cVNHYzE0UWhMbHdTU2JNaE14YXNhOWMK3ixSKK/23/sRBaCiW1ZBNOI/g9bGrwHK
            OhVNALs9k0QsF7McAgPq28G82gfQnI82CfiWsCohPYr6jBv8SzNxYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSd0FPdVlFT3cxdHR4QytD
            ZmN6K015eDFOVktNYVZnOEpRUmtEMU5naVE4CkNPMWUreEdJb3NSQ3plKzY4dEFt
            blU4cWhOUXB4UWZMckJpUXZ0ejNVM0UKLS0tIDM5ZERRakJ0WDRyWC9oblZsODNi
            ZGlPU0JDcWFuRFU4N1FFRndkVC9OMFkK5V+0T+b31kPepZAGFFvpdmV1nv3UHnLC
            s1Ojb4EQsNBlGEX4AUp+QjjLY4gIfoazvFsJW+dh0kegoJHMlTJKeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T15:35:34Z"
    mac: ENC[AES256_GCM,data:OMPf2tqEJWS7k0Wy4xSyMqL1SmoIoNGiLUtEoR66muGbZlcQ1BSZvQTiQYhVjBP3WvzOokNhK+spf9Zc+xWNgW/8KBCLVCq9LOAQZjWfjyWhu29GXVwfnh7o7HcNtkbntdunrjRrRum3AMEE9Y+nEdGQYlUnoepgbJhuCk6LfVo=,iv:q4989l1igYuMxg5/tlndpj6hXZwz49D9CF7smt2vEMQ=,tag:7lUBAPNNUKgecLQ4yvRrCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
