apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:4bnHoMdVtP85uoSeBXVBRokn36+ul0rq7X3Pu991wNzYkB7wXRH5AL5fAICVKNOyb4iNG87A6W4=,iv:DPvu/OqxqH43PWpopxxzLl2pSSzO/SXC/4LFu1cH6j8=,tag:SNBgxjPgYLv9F0Uh7/omsA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYjZSYmYvemN0d0xaVmRM
            T0JiV1JZYlBjc3Q2TCt1cjRERVE0aG0xWmdnCjVnQkh1K1p5VEhpSTYxNlRObUpx
            ZXZrckU4WURQQ0pOQ2FTTkFSS1N3YTAKLS0tIHp4d0pJQlpaWk9kTnM3UDFuVHJJ
            QWYrbGZnK294TjJZTmxiTlZwN2FlTUkKj5OiwGIZGiHohbmmO7WdGTVR7nHPj1cW
            KHjhnjf3lvhCJb4Qp62iKIWDZA1lzoQ/Ysls2/0a1JFNHT9yrE47kA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRWlPbFdKbjBrd0dvbXNI
            Vkp3VllzQlVIVnpwL3dHbXhqTGJmUW5Sam1BCmNtSUtoeFpZdkxsWG9jN2ZQaWFD
            WkZZOUZhMUViaElvcjFqYXpxaE5rZmsKLS0tIDJpWk5ZUGdNclZIQVFodExHSVF0
            aU8wN2xZbXRNMmRYdmYyVnEyV0hFdW8KKcnv0MPEoJU/3lplfGKkiRLWtl3rzA3p
            bORPKkN6ZpeGL9FA+jFV9/gBGQw8SO/o3JXRSfssfxJcLBg/ND53OA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSjV6SzhiWGNSK0ZZNits
            SXpNcHlXQnlBSkpRTDhSZjFHcnQ1RSt4MkJZCldOSkNJL2taRzZGVllGTFdVTkJD
            UDNsL1kyZ1RvK1FEWStiTWpRRDBjL0EKLS0tIDR2YjEvS1dSVEd1U2pQMjRqTXJU
            TG5hNFdIQTVFWTZjSWlmVlJlYTN1VVUKEOFcQ9M2tehH3JPMDIQ0fW24gXH6mSSW
            lxkybugIQJOwd5rPPzCRqfVHU2KvoVj+jXbSHf3J1klkxg9O9/l6NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T17:38:04Z"
    mac: ENC[AES256_GCM,data:VMjYIRp4IkU5/ccRqaWoCW50j17wTBg2a/5ESlYE5gN6FBtusn3L5zxVkfYXw3M1AC3c6Oj/5q4FC8+AU9M4rUy7jJCu46yJJpogCGbt/ZW11OZ0i9eVmO6Fj4TdJQeaij4iTki711hRhs4B/EYTSvidU8peVikUCUPgveDkXq0=,iv:dpRKBVNzRV72zG/RT9ZQ3tHAn03omaWcOHprtFJ9RQI=,tag:CLwE+QCAZ0qPfje1PXYNIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
