apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:b2MKUhGIQfmdvggf6oWW9kOInPbplHet1dWx2gUmqpfmpntC+WTpil2XLgyYXL7w9TPqPhu1dLo=,iv:ofWJ+chFp7q3d+bYtnATFFgl/nTNposNKCbaPjqtghc=,tag:arOaFTRJnOkEzdDSmRnp7g==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQ3NXbUVXcnMvK01IQmM0
            SVBKRVdyQTBvY3VHV0NBci9SRlBSckNMM1cwCjNtT2F4N0dDU0MzYVVVLzdoVmk3
            R2l4WTNmeHZFZ2N1RVpUZThzUVg1WGMKLS0tIHZldGJ4TU9KLzUvMFhDV3JEZFBS
            NkdRb0RCUDNMVjlQcFJEeU5PTnBoQ3MKC37H9/IBhnrb2PbNrGLHkcJTc6KL7v1Q
            ljCuV2Ebvvs4NoRMv1QZWp+Q5P+n+5So5DwbyBHRXnzZsWSN/jzJPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhN1g5eWxlUVE2YVF6NTdn
            aWsvSDVESmROSGNMc2pONDhLNFhPQVVTL1JZCm1vYUEvQTRaenRHaVhHTjJoVWEx
            TkNGVUVMQVcyVVgvV3hZZ0NTUlB6SEEKLS0tIFJXUDhhV0RVNFh4T2NnUzVWM01E
            N3IxM28xR1d6OWFtbGFySlEzYkM5TWsK/V4R17OCobkVCtaxYntRtbu2wWlWV/83
            Jw7e6FJJivEZDF1Z7uACI7OPxwK+cAMiJl5wVk6rJF/VBAoqUf/+7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUTNwTm94TjRGbDB1eGxw
            SnU3U0I1ajJkRUdlRmlSTGR1Yk45U0hFWkFjCmpCdSszSEJ1d0UyWDE2NUptaUVq
            RnhkWjh6MGMxTUNZakJEdll5a0tNUXMKLS0tIFVqUlMrUjdWTzJrTmx0ZC9BZW5s
            WmNXTVgzZ2w3RnBLVWRiVXc2RDdEbWcKKQFTOKbrCtcLkaIBFGD6JErFoRWSSjC8
            xXxH0igYiWJMrN6EBLX5Jzuq5RocGHFYW075VDgsOUNymf68cBOLWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:37:19Z"
    mac: ENC[AES256_GCM,data:nfqHc0l7BjB2UYJxCJMxCghaFGQF6qwoYBZzdbnOYBiDFUCAAxVmM1jWg8uuFjZIsF7pRcjXg95dvtpCvonbFY7umcqeutyxpeFg0+4cpxjMKmjWjjBVbGmtFu7BNPRdyaFHo3G2DCKN62v1kFcHXmcDF9U1IbF4xz2VRkqPT/c=,iv:A7Yy41cmze6KDYMcygzLRXnHjDHf3kf2szz/plOoJzE=,tag:N8uCbwZ//G5TjbMgBB7NjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
