apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:IrOYZOMQPah66j223H3fap8Z8Frw5CFChP3K1SvqgUW0R63ih/y1JhrBiJRHkyxu1xSL4NPEKXk=,iv:oNVpnZpFlfVn9Sd+aJe9lOl5zelcXwWlTU8gdc3W7Gs=,tag:t46i2GngZpS0vjkePeQerg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.33"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M3I0ZFAremR0bGV3UUhy
            amVqSHh4MXFnN2lxVkxLZDkyWXkrRjNZalVVCjlUQ05RRHBBbHU0KzlrSUMrQXlN
            anpsdkM2ZjcxQS91YlpTT1JEMEFJL0EKLS0tIFY0UDhyRXZ4OW9reXRUSk40RE03
            cTNZUG03N0tJRjBaczJ4YWg3c2N6N3cKbhn2bO1HNHd9MdnrnZVSJPSI6sXjJirH
            lZos6PW+oFIIRbmQXZyUZBITIx9UlI5JAuykd7rnpBwocTncgvMYbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcTFrN1dnRDFWc3NvaW9a
            MXpwd2hzdTAzS21CamVwQU9LYXJhWmV1djJnClRleElBVC9LdmNzMkxQeHh0N2pY
            bmF3V2ZBeUVQVjBTOVZHMU1sY3dXT28KLS0tIHM2R3ZtZS9aWGNTWVFWYzhQVXFy
            bEZqSkQxejYzZExac1hyRzlHSzJJdWMK83Laz7DjD+bB51AsG1SoBtLY1BjXsY/9
            XknxnAF41LVxv8EWN7cAXBEjmlr4zGgQLA+3rE/ipyUr5TZh00+aPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTlNVU0hDLzJ0MWgzdTZ3
            N1JzZDE3N2pwb1VkSWhHS21vQXpLc2RKU3pNCmFsV2l1Vkd5TzFwUkxiUjc5b2U0
            ZVpxVHpPeVpVWTQwVXlrZDdpZkowTUEKLS0tIG9DcGlnZVc1aFRJR2szZW1TZ0lx
            UTJzOXV0bG82WGhtUEx1M0V0VUg1Z0kKIHLZdgmShy7MfIiTafjRQ6pbB+loHuCv
            y85ytzH+6Gk71ftaMEM63/0HiHnhjFV9XvWBwXWbc4TMfPpPd8bbiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-12T19:55:07Z"
    mac: ENC[AES256_GCM,data:geTrpZnUWK2AQoR1tCKP5Ag1LD+uLrL7g5RHUiB+hE4e4rQrmkFCyu7sgpOHtV1A3FeEsr3VF7v4atFCy1AQ4O6I645nwx5yWuAtVLYkeM7B8sjdojJ4JH+e3I3MNgxWma1M+oM9tEn5W/1pn8SyVIqE6AdfmgBKmKKZYQTem04=,iv:VqzaoHGBFTMVTl5iyFp+SZCJAE520bJhIP90KK0VtFQ=,tag:KpB+lWad1T/yT4j96yL+Yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
