apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:H2vsC4doePG88o8Z/bqsvgVfkHuLL8YsF4W1uDUcKlFfAUn+XSA+/kz4VBwC5I9EMU98UCtC9So=,iv:BnYgj5/ml8I5wFypVSAgaE6b0P8SPZK9gBarJM83sRw=,tag:S4MRHUV6vMCjB8bd9FxYPg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT3NVYlJpdUsxV3RHTFpu
            cmRJMEZiUCszV2hFWnhOL2NDekJIRVBiaGhJCkFvZ01GWkJkWHBTdVlvQlhZL3dY
            alg0ZlpKaGQyc3B3Yi9uZ2xhS3UwejgKLS0tIDFrYm5Pd3lTWUNKNk13U3h4azQ5
            ejNDZ2FBUmhtdnEyVmxPZmtOR2E4QVUKOYpfkA9QqaXWBEC1vhH+rYdmMv11ZSax
            wBrhFr/gY0HsMbUk32vKieSy6ronkd2RJt84rKxnHqBonTOtsimT7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y3VaaHh3WlNkRnFtVDZV
            S1BXSlZyTGxpbTBZdnhuUEkrS25JUmF1alYwCnhYUG40L2lZQTNwOENiY1NZTXM1
            dUk5ekZIUHhsWlhIYkw3T09oS1lrdk0KLS0tIDFhaUZoRnV6UnVid2d0Z0FobHhE
            RlFOZzM5aThRNXpvWkJKRUcyYUNLOW8KNO3dCvDPFzv13JlPNyQjiTgiQNK4isP0
            XiCp4bBf9ajB/vA9k1Pqt87uifcMdqJ4WzPDrRtmWoTSEZo6rxytaA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Rm5Hb0I2VjBtMmVhdUty
            Z2hlREp6RVAvVE13c3VCY0huaGJBWDdNcnhJCnJaeXRuaE5Sd1NjVGhDS0N5Z3Js
            WjczTUlVN3d4bmExNmZxWVpadjF5UXcKLS0tIFMzWW9RT09ncFAzTXFld1RpakJx
            Z0lkdVoyUUFjWDl1UFVmbzFpeUNZMmsKybxZCmXNVnCCEcpinJ3U+DGIqSkVB2Dr
            fAhya1kljQGLt0S82qXm32dDeYDGhd9C4inFuQjkTTyT9ZdsdrG+Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T14:04:45Z"
    mac: ENC[AES256_GCM,data:E53UohbldCTpvWMfPdP7wMlCzLrFfhVO97hm/9Y5rIS9gQM9xhS5gaFu7+BpG9BLbi22idbtnw35STrunrX+nm4LQCA9Ym/qU102X5ut6XwOM8zRtsZOkO9CpQPq0kemmJ6Ipvhgu7lMuE1AyVCL/pTfMy5hK6eUTeebt/2Tg7I=,iv:1Y4COzVRzxOQzqy38Vc85/Sz0PC7jAjqn6ku3N6BBIc=,tag:CVC/dIqQel0tJ4K/pS0XeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
