apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:xLsIYixn2jD/dXmsw6KICi84FBeCrKLuX3jAxQjrVQ3d5L42ALE8YSbZamz+NGbHlaEz0BN1c6I=,iv:NRuR54rzeoApBJmW7hL+4sZvipwFiVRut9hbQ0Fo+E0=,tag:8P0ZSLfxmNbcEB5zrJUk9w==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTXZIbTRSZXRwaUlta0RB
            OHZUNWhHbkJwbDJxUVJZaG9RUCtHRkU4NlJJCldoZU1iMEJ1a045bFlkTVpEdkNj
            d09wdFRYcXBPN3ZCd0c4WDg1T1RzYm8KLS0tIG1KVDFWNUhiTVIrTk5EOXdDMHdX
            UThwOGtmNEtIQlFFNERKc1hkcGRZSVEKJ8rrO6hqGKzIvns48fwN4BuRe71FN3VJ
            b6qiNr8bQacQlDY/ZJkA5/9Gde+UStYs61ru3uMZB6n59hPWOC/VYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMmRCQVduc01CQW9DKzVv
            cStGbDUxcWhTbkFKWFVEUVUwYVBHQkliZHdvCkZWa1NYK0s4SWdPRUZnekVJb0tq
            TUkranI4Y2tXMndzV1JDSmprRXM0R0kKLS0tIEVOZXJDMU12RFNEU2orTHM3U3lU
            S01xSng2RUFRTkJ4dzZDYmJieU5xNjgK2Qde6p4mc0TKDrrIgYGeIRQH9fCbuGBJ
            hTQOeQRLwd6QqSmwLXYTEJkCz9m7ioJeHHG0SGpF3oc1cEUb1vCx4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TmxOREptaUVRbExwVE0r
            bmlNN01zZXBJVlVWYWxwMEd1ZTBwUTdNOWlZCkFTeVY0Q3prUktaeWNhWFRTQU1q
            bFRLVmlhaUFhVDRGRTJ3cHVaNWVIRkkKLS0tIFFoZUMvTnQ3NzVjaEhmKzQwSzUx
            L3pmRWlNbUVIZklUUHA5WmlJRVM5dUEKV3Q/Au1hIhHcqXncNsJST4aZ1cA/iDBx
            tejC+B+Df3m4Pi5HslZYOTdXNqatquSganuJ2/KNwfUAhmULtIDGFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T02:44:04Z"
    mac: ENC[AES256_GCM,data:bz9aqYz4iBVKvsnXziaUwF9gkIrSzCSp94TGtWFguEOXhSwzgjhO5t7nOQPIFHxL2sYLH7VZIg2dADggqOe5oFcRhylweoNdEnd7/RkAwLelSnstTofi9najaLvhMCA3CmgsSnhVnsD6JhIeOoLvlcs8bsTl4LMpx207+8qOyT0=,iv:h0rA5pPosC3es34lQaDcmuypjZOvKyv05DG2I0d+Usw=,tag:LYzHjXWedi+2PJjFquUJZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
