apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:jMW6eWnAQdwrUaa2xv0haHK15AjQcRDlJ7QcIGKYkvq7j9PWILd/fhOQKjlAh0e/nFodOn0BpVk=,iv:gZC2HqRywP3G0g0+LjEEK7Aw16JCSdk4tLG0YatHCpE=,tag:/vkwcZMmEGg3TdIjiYdNiQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZUNTcDlYTGZpQVczY1kz
            MmpwYkdrQXBsdkQ0SThJUHQzMWpYaEtZYmpZClhrU2thTGFaWWZBWXF3VG1SeVFE
            bHdsRGJ5QWlxbEhCK0wxWDIrRS9xbWcKLS0tIEtXWHB6Z1FCOS9KMEtkUkVzWjFO
            QmxOVTM4YXlDTkZSOWdGRndwdjIvUWMK9Poe2qQtOaqPVG/LPytVHxpiYbES7YCr
            greA1Iqcc4f6KzMIHNzjZ44fFzo141JSZCtvvjDc2hwJziWMd8ReGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISU02a2x5dkZHQVJBQ28v
            WFY1S0dYUy93QmZJVmdVWFdEdlhWUGF2K1V3CjVBeUY1WDZ4ajYreFNpaDVPbXpM
            by9IZDJwUTlJb3FsRXlKMWxlY210eG8KLS0tIEIzZ3RZb2YxdEd0YUpzRXhKTnVO
            U1lTQWs0UEFFczUxOW1mOXFpWFErQnMKZDRKcvQv49WvsktxfSxbijYXiHhibhs7
            1cwAb+xnr4IF49yN8RPTviM+rELADPPvCAsV5+t60wi2FdHMy7/Bgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RTJNN1JxeTJSSVpQRDB3
            M1M3cDY2eUdha3pXRHNQN056bzZ6QWRXYm0wCmhxUjVtam5rbW1pa25SZjNEeVZP
            ckx3WW1vQWFrTFVmSTJuY3NRNW1zQWsKLS0tIE1wUzJCZ1BBWHQ5ZkZPTUFtL045
            QzBmbVFTZDBIVW5vOFdvMzloemdxejgKmCvxNqVgtsCJsbGAjsZz6Q4aEzVDGuwT
            D12lAg8NmXD+k7aRicdJfCxVjZb2T35t2TwWf8ak9jXgxim2OqSrdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T03:48:33Z"
    mac: ENC[AES256_GCM,data:dAkzUCqiFp/doDBDc5rPF+xgER+kTUBkE4HfBgp2LgldRDO6ZifSo/eUD5oG2A0E17V12ZvEmpuJ/XkOMrR1gpVa/E5gSlFs68FWTFXC3+bpnvADBSQDyX54nrnDEX56EYdxliESISlbMFrGXRDHRanWQ8YmruwPDj3hJDGbdKY=,iv:mEvwRpBMk72OZHrKZJScyhktUMHyBHR/u1H+2braDUs=,tag:MEwoEILq70NRC6izFHJMCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
