apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:3iJNjMFShGBUwquIkL8dVRCX6yt6lo1N6aeCGlgyKkwaHon79LfBrZ5Z3wDNroeFYuqvZbuDtcU=,iv:lQuvnYSSJOmzAgTn+VnudVXwI6L38iCOQqkxbHOdZfs=,tag:vQP5qCqWp6NoYJQN+iYRsA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.33"
        kubenix/project-name: kubenix
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSjNjeks5ZzI1R0p3amxk
            Qm1mb3pHOFF1QkZsN0QrOGNuQXc1Mk5obGg4CmxTbnFnK0F4YmRkMmdLeS9tUFdl
            VGNiVWJ2TE45U1NKQXA2QXBEeU1FMWMKLS0tIGtaaVdTcGIyMUxuRGVZZURoTlRU
            SERrcEsvRjRjY1N4V1FaNDFIWXZBZmsKbL4M4QCAxO48Tc0a4akFkgGnnoYid6gr
            y+X8/V4s6x2nDzuThVkFkQ92czb9ympvWWoNOqYBwtC26YguKt2GWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMks4YlBqRHQwYWl0TGZq
            UkN1c00rdjBlZmN4SlcycGtlK2MxNGpJTUZVClpWd1VBaWlENUxsdWpNcHRHQWtn
            NmI0c1NLSHZ2cTA0TVk3VThaRk54TTAKLS0tIE9iYVdBcXNtNzVNeC9RaUIzcHZF
            eDBIa3ZtWEhJUWZBRjlRbEJUc1BVTk0K+kNZAf5Z89OEBSHHevrBetUo/2Rq9bqI
            MBJ0FajtehlYYJRkGAixsMOh7H4MUcqK1K5GMBcELuczsesNxf93xQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVnZIZlpLb2NLcEtDRjU2
            b0JMUTJISzRFTXpVMzAyMTgzd2ZMbzA5RkcwCjlITDdWeVJNRVlhYXkrenJQK3Rh
            U1J4UmNBTFlNSW1yUGZRVWNuUDFGdlEKLS0tIExhZG1yWW9KS1dIdHNyOHRCTTFw
            WjZKMld1TkNlZ0laejZvT1FVM05IZE0KwAJ0OKpOnZvoMw4TISUh9TW+4Y2lZ2zR
            293ITmKk9OIXgUyl2rc3ERfio/kx8FW5LE0P8JUgvI/7Oo0YMy5hhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T20:06:12Z"
    mac: ENC[AES256_GCM,data:uEwzZLA0wm/raAu/4um+jK4PBvrhi6mthv0bcyth2bFCLUb8+xciBAdfD4Kh7j2XqiB1YH7g9knaoHRkEnGGLdh6A0f7A+4TYnt6nDbHArMhHxFomcyZlLD+0T/53mbhQGiy00Xx5ESlZjyVIiOIsv9V4SnYmzc95BuH0gg+lgY=,iv:7LLKh3QHJQN46eZqQashTkm+46DQM6XX6uqLvl6FxyE=,tag:qW2CFTeaoEwrHOSKMNh2kA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
