apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:nbKfVcy4Eyq76QKXEuvMlxDHtppVqKZ6IekSV7WWOhXiD00hV0n5QGifbPE7abFswzvAn9vuKRc=,iv:pWvIVe7RBTrPmLg7GjFVynn3s8SsPGEIR0aQkUOcDWs=,tag:7kKYoMLb+eaXCFEu0q9iXg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.33"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NWVCVkhXZXg5cnB0akg0
            emxLR2dRRG1WbDNIMjBnQUwvRTFDSHUvWVNJCjFXQjZSQ3hGS1VReVY3ZGMxWUJL
            NzM5YmQzZkg2Sk1Lcml2bFV5NW1QcjgKLS0tIHMwNzh4cHVyOWsyMWxySE1JM013
            dzdkb2NvUG5SY3VDamhQRG5MaExzQVUK1Fx7zAcWXNXmWVKmrd3ZKbwpqUjEV1Qb
            ID7A5P9nbwc4QOzH9hBrOuMYtrio0JGKA/tWS3SFndr1FtYB+PAplg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUE5kdHpBYVg5M21taUhY
            UWhXSU5yTW80RlN5NnF1eklhSUhhQXAzd2hFCmlKczRiNUgyaFRxdXB5K0JjNUVL
            SWloVThKMFJXb2U1K3duMFdPV3VWL3cKLS0tIHB5eEpoOW0xREtOU1diY2o3RlVE
            OUxGa1pnR1BVSlY3T3RHdVVPcUkreWMKPYQvVxDL4DEMR9Xpmd/x5G5lg7a0bInr
            OcB/laXLYp+bOgBKi54rPy2eUTbx3SaG7nbzApTRTVHx7piyAkhM4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RmQrb1JVUGNCaGNRaUg3
            d21ET0gzUGhNY3JjdUZpczZwT3VKQ0N0bmhzCmxsQ3lRM1R0N1V5V25EVElrYXpO
            MXJMY3VYL01iSmZSTmJZRjNnQUhIVWMKLS0tIG54RHVyaEdBV1IzR1hSQ01KTDNT
            bG1HTStmbE00bTJ6b2NUaUhXUERXcmMKjKcb5Yf//SAVt8eD12WJNvV7CbcLe2Uk
            FXNFA7x7+9SfoCp89KuQ5GiFnLaLaaZEqbI9MimTDuA97aTZQH9OKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-12T03:29:20Z"
    mac: ENC[AES256_GCM,data:yzH0MmLa6slMwyOpofzTYyPhhz5xYhG3+OQQKRbPsYJ3SnAXNeuzusmChGTDD//ca99oJAkY5Sj43oY6FfqC/LjnKqnmTBrNi54yn4fkX9kjX5DEmD2Swq0h7vY6iDf9KByjNqUeVT+FH6wTq/Hasrghs0y27yI6KtIjJw22M20=,iv:h+XntwjQaAfgoxDiErNwq+5X33lKfPWBWD4/I8y7DRk=,tag:nVshdHpiXMbStvE6V0aoTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
