apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:LsnNoKb+dnLFl8eDUb4Gq4kKUXr+SPpsmylTRu8aciyhXdc4xULere4E7yi4ggHQYHhhNLOiO3Y=,iv:xco7hW1mVWFA3U/GR/FERodSZyCJslMx6B+BdTTGfSc=,tag:7lud53Jf4sbBCsNbNQCvrw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZGtNNll0M21xYktXM2l3
            NXBoVE5kSGFUMVhDb05qNS9qZEloREZmbFdNCjBhOXpFaktaQnNDQmt2WHJxeWlI
            eFZSV0FkWHEycjRIbjlGV05GMDNMZ28KLS0tIHpPeVZDMlA4U0hoQ1pkb3ZWN2pQ
            YTBJcnZja0FGWEJKdDJSeGdTV2NoRDgKQoCMhdIIapbqUyCoIHxi9SsqKY/6Jh2T
            xzZgneDsAsB9AAQoNo+Z9I3YRyGbpvJFQSHhwzRpocfpwk6zdVpuEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcW1pSXNVa256VXhPaGRV
            dndNTmN1aTh0bTd1T3Q3TmZsZUI5OFI5MVhrCjdDdmtVaUhUNlpuWGpqNzVZNTV1
            cTRWN2tLN2xiWXBtcHBNRGpzRjZubGsKLS0tIE1RbDd1RE1Rbi9UUGUzS1Jmb1Ny
            aUQ5Ky9oVUIvNHBNRDJDbCtJODAyUzQK/vXhVVsFgf5+vabqydQYrwfM/CWZRH0E
            l5+lPjUSwslGwWNU30j8aQOYDo4Jv6+WeLH6cv2LSJxchsI424tNBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRUMyMnp3UEFzM3FzZ2RW
            ZGs4NzRLRWpEckpVRTJjRU1xclJFRUN0MlJZCnd6Ry81SEp4QVkzTyt2ek9SR1V5
            ejBFYlp4TTZPbHphRGV3aXNMZlVINVUKLS0tIGNDaStVc2xwWmdGSEVRTk1MMHhk
            UHFWLzZpdXVycUx4VlczVGV6LzJ0UzQKmogBydS/Hr4jb2VJc+GHo5JS5jd7gRrT
            B7/lx9ZheK36DCo27nFKrIC9ZD/DynO4RV3vupBfBLvdk65kRzZxMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T03:04:30Z"
    mac: ENC[AES256_GCM,data:It6cU3Aa0OWkw+4IVQmVW1/qOy0tFQLX0jWpZNzQa0ONRDKgFA4FAWQ/ZTkoMByD2QEx3bMGocmCmHlvn3Mm/jBxtBUDF8BeC8eAAr7CYTLRrn+MfLDpoymXil0SS5MmZZinzkOnI/NOvvqOj3pArtKFKmdGEHkfOIIvN8a0Plo=,iv:EJ/z95Jr+KTh9koCbkvy30MBi4BQbWBmsMQxKab/TN0=,tag:/dddWpFNYdNRuAgEfGMImw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
