apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:R5jYT1wAp0plD9/KnJkJJpTlbpnL+O2q7MjOY7n1fKSiXTz1Y66BvaRvE7Q9zx7ceTCCdD67v5c=,iv:2mkABO1Ve6I8u23Nx2rKMzkMtYtFexkC3ZLLZIgXeWU=,tag:JlBPkyGr+pTDcRrgpnHuCg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSm9NSWJ1c2w5K3BKSm5N
            NnJSRlZUK0QyQ25CK1ZWT1pKd0d5eVhZUTNFCkd6NHRUZTl4eDlYUmFFbVBPTG5W
            cGtyNzFSbW9CWkpBVlRIQ3pqekFvQ2MKLS0tIHdkNDBmV1l1aFRMSERxMjBoWXVZ
            UWhiTzJ3K0JqK3BuVVY0dWYxQ3F6V2cKU0rlGOtIEq7taRvDdEJghYBwUFP/Lpfz
            ASCIEiTZybYOcV2Vi3wpi0j8d5CawIkRrK3lH0d+LVyb5ozOBm/OkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOG5ZODJVM21IQTdpcTdO
            T3VGL3lod1cxL2JPM2IyM2ZjQk1qdkVWZFdrClBQWkxjclBLcmsrUlJEWVAya0ZP
            WkxqanFlNmxKcVFLamxSSS95S0p4VUUKLS0tIEczYU9TNHRrMS9sTXUzRlpEeTR4
            UlArU2xaTVkvbjA4Qm9iYTZYVHgrT2sKVW9NeITzr/91swNIQvPgDeedBDo+LxDs
            /ufFTUCVaRH6oTJeuI5zCDp22QmsZTOgqjNGK/aikIp3ik5kbb03Gw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cFdiN2Jpa1BMYnFvQkhZ
            cUdKUkRwb0dPWVp1Y0VFbmkyV1VqMmxXYzE4CjVHVWVEWVFrMExmeXhGSFNHemJh
            M3hpRzRtOWp3R1JDOVU1ZEI1aGVtQmcKLS0tIGtLdTJUNy9hR0JLSGZPSFZkZHBP
            a3pLZlZIbENjNGxKMExIcW9ZZ2lXb2sKIT43SZ926aCloJRf0sxmFt4nhnFfWKYK
            pGR/pWEkhzFfDnxTkSV1jPbzReiVVZu25WADMXynlUXaqBfIlTCQSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T15:17:29Z"
    mac: ENC[AES256_GCM,data:j+6wDsCVzofZg6E0RhxHsolYH98/ry1VyepzNHB/0fYJXOyhSJcuDCVP5SfN7sXNXXCjHFS4GdwxzoNbdhWMe7fxYSd4KLEAkIsMpVq/p61XCNTwxp2FMfLWt0Fa7BhoV1R8/H2sNXnrgdwR3o6yQPulWr9YkoxsS/1YHlBo5nA=,iv:yQrTAMD9EjXyyHeVyIB/GjiADzsLp3pldumi8T14Cck=,tag:u4seuOX3Ch13/TKQhH1Inw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
