apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:ZNuLmfgOylfp/fi5tDbTjXQNlP5astW3xx+/UcX2NiOBJJtV6pd44NpWf5mlwibE98KUpvr8X6k=,iv:FQodlNQsKZysnOfMJDz+tkN+ctQ0c/evQGxZU7SqLeM=,tag:BUj51XtxYUHpvfDcgiwhgA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVN3RuYkhFRVpoMUdzUTln
            eGtMWjBkQzRlMjBBNmdYZTNHaDRab25jV3lBCmpMZThIZkZQeFFEQUhZZTBSY3Zr
            dzNBOVB6cW5GZ0x1UWJ6RmVuY05VUlEKLS0tIHZrL2NkYWpGYzRSbGpDK2hUbFg5
            bElZYUliZk12dmFIY3RaeG8zQzhWU3cKlQ8sbU9pma1r3SkZ9hbFMrBU7OampWO+
            m35tBqx+xg2YG4YmKSwLZqT0HRL/ComMGkI2jgXmAU1hnd4T726ehw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcEVtc3R2OUpMVUhod2xv
            djU5L2wxa0VBZFNUYUVTVW9VUmZwRUlnTkZ3CjY1Wm5WSEU3T0JvQng3YTljMEdn
            L1pPWEU2TlhBSmRCQ0s4dHAxbzVQdE0KLS0tIEJIWXNLRnVXUHlSZlJCckRqTFBD
            YmV3THhXVThCVUpBc0N4c1lYT2JSL1UK3HJ4bZodjwmRZLdxl/Yu1bmC5vSABwkT
            G5Q20a9hikDA0nPIyIqCyqgPq2EWOFF5Neb+IUC9PbnCrxll6GNFKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bDlHbVBSTE9rSGkzVjI3
            b3h0SWIyeThhUUh2QWY1RmhLQXNIeUcwOUJjClF4OHhndmwyRzZWZ0diRndsRFZP
            N2pBbFFiYjlkVEl0ZERUbnFuOVR5T3MKLS0tIHBsdnVWTUkxckFLWEttaElOYlh3
            TDRDVGdaZUJGR0FVem5acWFGY0R6dk0KqjlmbxLwCok2HwlghpC9eG2LYC4Ej1mN
            HHOlV+93dsyZ7zFeABzKXIsP9WssPc+SQnClMVxDAjWgbf3ziNCdqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:22:34Z"
    mac: ENC[AES256_GCM,data:DvpIlUl9Ikvlo2RFLLLiGLV0Nuo8At5KV0otNCZgsH+2IfkNnQ0Z11aFtUh0FYnjCA4WT9Xfubksz+PyCY5eVxfUwX/8X1ivAf8IP044zTX7uNntp2rTfDPYGYBtW916iF+IqoP8BmIWGgOV3HtPC7vz7PRiRW3NVT/v+obZOWE=,iv:WE9KTCY7JsIuRMfRB5eNSuNbN+ZiVR4RjikgZ07bXeI=,tag:qu45DCDQjgg+XRR2DyV02w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
