apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:aJbpLaVqiyZIDRyN3X8G2xcnPBemXTspRwB1E0RHeScWMgAW6zZ8Nxqw2qLFDNjV5lPmHDiM0I8=,iv:x/Yc+JuDwKzuMNoaHWONgHxNMiQ0Yxzg2SInmU3h19k=,tag:I6faA+X+HltuKuREck9wmw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWlFVQmcrZVdQRDdoNnZp
            ZTI1Sk9hSXpKMGtQOU5uOU9KVlNvTG9hSWdvCjdjYmc3bERQaEVocjlvMFEwbm1u
            aEd3dnY2YjlvdnYyTTZXUXN5ZWRvK0kKLS0tIGlDdXJMbHB6UU1YV1FvbWlUNWw1
            MEgyOTlMOFMyZFVOdFA5ZjhFaE0rajAK/yxy0wKwOS4dMgZGASfxL2zX948v4RuS
            GKgPuhjEfv22FVHimWoC89e+zg2Vg7WFZWlaWKhgG0OLv+8XEZ7kJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTjJkMWorNWRHNjRvdjV0
            ZFFKOHIyTXkwMENEUkt6V2FUOGJnNldTQVVjClpnaFhVVzZFOGRlMnZidnh3L1dm
            U2o2VGpBQU45RmZ6R3gyOVdyeENZVEEKLS0tIFpDcEJwa0hvZDZaZnl5ZjV5WEpl
            Y0pRL0tIWEN2YzFNOWV6Sy9hd20zY0EKAtMYvo/NrX3A1HdfkOogRNnV52UosF+n
            +6ZoeEmbD2odoqYWwG5eNT2lEuLHGqMI90URFQp4BRTNMhFzOSDH4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZXd2U0QvemFwc3UwZXRp
            NlYzcDgreWJ0SGViU1NBR3ErcFNtY096SDNjCmNzMmhJeGZyVWRpRE9BblAvYlpR
            SlA4RysxRlhJc1VCY2ZyL0g5Q0FIM1EKLS0tIDlLL2g1M3hXeVc5UElJYW9hM1BB
            MHJIdFNPM2ltdm1Hdm9BMTlUb254V1EKhEdqoDRigKvVjTDtwkqWdS7OwGkgYhe8
            jRcuzqE0mz3m8DsQhIO42p2ZgNQQ9ard0OoDlFy9fTfsT01b5Caw2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T15:56:24Z"
    mac: ENC[AES256_GCM,data:Q/k/1A/4p2rqHIAz0RvGoafj/H6Sy5dMMqEG0ZA8p7qAAGkwKtJzCFy2gjifixXWQtP6ty89k1N2Nq5R3jtDqAx4187LHQbH4s90VpOCJaSn71Jf4d+kVG3ODRBcEPwrEfnxZ7LwxsrL7VYXocglBnTRG2s8Cbd0IIm5nWz9qqE=,iv:+wNzZl3Zlcc64IH1LN3WgrtIvtNqnEwK5HeMH5OjK/s=,tag:IckoDvztFOvV5UH71Frh+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
