apiVersion: v1
data:
    cloudflare-api-token: ENC[AES256_GCM,data:KM/aScaG23PDRIO7pRJGDjkrfheZkx8bHWs1SlvVyOmBkile/aEJbN3WnkY+9d/n3lxK9l/4XvY=,iv:NBrPlbf9L7ANNDZ6iXmQOUJMCR4x5swDN5eCTQPUZt4=,tag:czO94ix4q9LePVGB36Xwlg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUmtFTGVtWkFZR2VOTUg3
            UWgweE14TEhUVDB4WkpCdXFvM0d3NUVhNVRrCnJhUzRoenpyWWJ0aVZVMGJ4VERq
            azZUR3dqdU5iOGwzWmlSdU9EeWM0cXcKLS0tIGhMTHhOeW9aK0hoSUNWMVBGNXZX
            N0ZnWXEwU2lWNVJpUFVvYXhQZlNXZjQKfKex6d5h9xG7bEXpe4x5NcqVbNhA/qCo
            kO10EU4iuJ4lAlyDIVo/1xtkzTZpWF+ErBHaGZZJKwFWsyw1iWZ7OQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMW9NMU84eTdsQm9uRTVZ
            QWFqTmpNYjUyTVNzZjFjV2ZBbFpSSmxwVENJCmdRazZ0VXhzWjl0QWtpajdVTnJ5
            emlaUDI1V3ZwTkVtNWZVRXNSR1NzdmMKLS0tIHl0VFBMT2tMa1UxSHVLN0ptOHlj
            TkYrb2VsbHYxWXlmdnZTOTNkWEtmaW8KTlFlxEVjGu/RGfjX734uO+hhzMZq3sps
            +626Defi9s8vggzPyoAHT5GrUFbIgjPBefzlDzpLYjgj8VPrjBir4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WE13bzRuZXhhNDdJOS9r
            UHR3eTM5SW4wbjdkUFc1dWZraDhrS0R2YTBNCit6bkJ0Z2tlcGdRSFlOWkRXWG9r
            dENUdFl1YVhxSG85U0NtU2g5cDN1dVkKLS0tIEh5Mm0yMGszL3MrdFVraHRDaUly
            N2dac2h5NjlacW94ZW5FOW51ZVltaGsK/ptt4GAQVH23ZwYpTHlRSTik+4RUtCwY
            WnBCr9J0QoYylEt1s4DCOvdAFvX9peciAV73ObHmfyOPDORBL90M1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T17:05:58Z"
    mac: ENC[AES256_GCM,data:F4U3r2j8PMsZ/PW53xT2cIqHXIfdaThrWPhOViPb2/nsyqKIZXzbjUUyImgrJq0L4B/js2ACrlyHMirlJqc2ZUUWzpFskIFiv+RZJxSQbLMYMlrgTdxgHykpna7uX/J3CKA8E/m8sPMvSQbn4yuvY/dCcWmily0pc9vkWsnXqqU=,iv:dOEcEP13acXmhDs5+iDcb1goTG+Vwjs3cfhjfKLm+yQ=,tag:/5UDltabcegvS+lqbAcfIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
