apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: alarm-server-config
    namespace: apps
stringData:
    LOG_LEVEL: ENC[AES256_GCM,data:f8a7qw==,iv:f5wf6jY1qBYaE98SJDMZ9Hu/yHanteFoHgFBD5cZtLM=,tag:HkiByziqu3eDmkL3403LPw==,type:str]
    LOG_OUTPUT: ENC[AES256_GCM,data:xwY7xg/2,iv:u4CbCXV35tXKeweC3MdLGqmQosNALjze5bk8bZw0YqM=,tag:G7ZvJGr+j0mSNv6f1sMrmw==,type:str]
    MESSAGE_FILTERS: ENC[AES256_GCM,data:NO/iFsn9pbks,iv:3M0jmIk0+uj6eFbJn1niFsp3gmfYgbLiv0sNof0TlPo=,tag:ech742ztkQWpArmvqm+rrg==,type:str]
    MESSAGE_PARSER: ENC[AES256_GCM,data:DTLtbKk=,iv:pZQxctP4EUXiTJdHwx1KIomSfVuizh6TuC4MEdeZLKI=,tag:UYbNcSyoFnArV4oDhi6J+g==,type:str]
    MESSAGE_PRIORITY: ENC[AES256_GCM,data:HTRR,iv:sMF5VZzfRcrZvv7mguZXOLkFWdjZPT4JWrM4jwmtxu4=,tag:CJhoqwaIcc6QVf602SuIXg==,type:str]
    MQTT_TOPIC: ENC[AES256_GCM,data:Sh7JJ0ri,iv:U44iMIaPwgAxI9+6hVeBe9sGe8yuETW9em2QQF/bixM=,tag:TYGHfhK6O2S1loJSZceAKg==,type:str]
    MQTT_URL: ENC[AES256_GCM,data:cJFPzDlbmOyWqVMz4PAaVTs1QpIDlpEGVKzZzbES6lG11PMklZX120G/g5Iynm1YIJCQqjRPMp9Uku6J4sti8Dp1qQ==,iv:1GerqCd84ZZPlnxILBLx/oKlqA3A6TuHGtIRZYVHBAQ=,tag:WiSQEwSPwztgm15abwPk0Q==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:S3Hrcg==,iv:+JCloSMDSVbPnU6+rgKMp72OBs+YL2ynie5VaYVNBgU=,tag:1QIddLIvX5WtZWFvxyoeVQ==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:oewWLWk2,iv:w1w2Xihl9uRVf/qdOL0BjbIoY9F0feJgVOp8oadO2h0=,tag:f/EU9Mc3Lhu/2spf+m5W3g==,type:str]
    NTFY_URL: ENC[AES256_GCM,data:rT5IuFCQ7ALgT+zqqEty+j00ZszmcoVu0uY=,iv:MIKVO6YTYTgH2di6r2hQ6i6ypekmJY9rgzxHkoHiC0Q=,tag:WWcDgTKqp8UNP4evXiAfjw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSjMwR3Q1aEJNVE5RYUN4
            Z2hSa0RFOG5qTVFzZ1UvL0xzVTFEMHZqQWpnCkplOXpwWG9rdjE2RS9FM0pkVE1E
            dFozMTh2c3RrRERjU3h2NVFVUE55dUkKLS0tIHlOR25kcWtlbUxiaS9hUjhOWmZu
            amxDUkhTaEJrRjM0YUJSbmN0b0hnYVUKYxgBrBg4Q9+50kcAZ9FVeXqyajWVNQ5z
            EaMR/9PYG1cn7F/uZsxSnj6PqY3WStXWsnYxyi5aGVpgSYJPF3CXcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZERCcm1FTVpTZHhoYVVt
            YmZxbE9Pc3FLMlZ4NlJyMVdhU0VZUVE5Qm53CkZDNUpINUpnS0Zwc2dhd1d5OURM
            V2s2eVBFY2tnSnFKK1dweFRTU1l0ZUEKLS0tIGJ0OUtDZUJ1RnpnRVFWT1YyOUVK
            SGNZaGZBSk1IK0lMYjNiNXMwVUY1N00Ke6Q/5YCwDEDuiefOSnb//CxiOihkjFeG
            EK3M6fDQBPEKEkyWW76YU3dZmJ+KCbkbXcQeZvmH3qbEnFh0gw8Mhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVkIxVUc1TW5VdERmZzRr
            aTFyUlU2NXpQTGpKN3ZwdW8rZyt1UnJxVVJZClFxbGVROEhEZzFHYitJTzNHMWs4
            b0NZQ3UrbUF1elUrVTVIVVFwNUhrdVkKLS0tIFgrTkwva003VVhLd3lDa3l1UHVP
            Y0c1bnRSOG9Hc20zZ2dLVURabjBzYkUK8XFQUCmuQ50cN1JCCO0mhHshVbOUa/jQ
            RHipUW1djpN60Wbgs3D+i0Sri683pyCRNN6qdmKP6dFCAiauAV/pFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T15:58:10Z"
    mac: ENC[AES256_GCM,data:tf+j5w8mrDEmFb5D9jfh6xcV1avZAaXlU15H5RdSdprGc+ifPptipkdVW7Ct2V6yInJX31B8264eJxXv2VtUiXqjUueQcuqUpyM6Y85a+EPkXQSFrEBUyyaE5wbYNKTWqVlNoT1VG1flen9RpbSiPSmWfLL2X9w7oJrDgyYnLwo=,iv:NsRn6GfV+oELY2TNrz/eAmvNED69VFLdm7dKSFGdku4=,tag:+8JZXeN/h6vgL6xHWEYJsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
