apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: alarm-server-config
    namespace: apps
stringData:
    LOG_LEVEL: ENC[AES256_GCM,data:ca9gJw==,iv:tXtZgAjdrTAzcO15AxjyVV4bcki4S/qoKYWdk00I36g=,tag:xMGOlt4I9d0gAIbxdsdy4g==,type:str]
    LOG_OUTPUT: ENC[AES256_GCM,data:tm4MKNOW,iv:WEcnNBMqV6HxShvd9VxzBGr7fVbrsjvErB66mOYeJag=,tag:/MkW90cSnVFx7NNH/wFcdQ==,type:str]
    MESSAGE_FILTERS: ENC[AES256_GCM,data:9OcOHf2FjLgC,iv:MgQmOcgGXKqYIcwfmtWNHrIyUpIDIX98yEVwOae0TZc=,tag:DYKpEAuHMvYdhqgBnC8lxA==,type:str]
    MESSAGE_PARSER: ENC[AES256_GCM,data:huu5pbk=,iv:3NUR/ukroTSncwHLdy6+thFeESnz6D+pJyfoTmKaCLc=,tag:bOHH/r4Kml8GUvs/vL4Jag==,type:str]
    MESSAGE_PRIORITY: ENC[AES256_GCM,data:bac6,iv:orFgv6Z+jA6/9AoO+NJL93Z9GBcnPctciSioI6Qaph0=,tag:/mWsVBE1la7joCX+AryLMA==,type:str]
    MQTT_TOPIC: ENC[AES256_GCM,data:82N8GsCT,iv:fzVN30hzx1xMP2AOxwSQ3HNYO8H69zFsKJjpq/M7yzA=,tag:k3gS5yshKjqt3YLDmbw5cg==,type:str]
    MQTT_URL: ENC[AES256_GCM,data:r7iU585sCKl33q3xxuKhNOuVLZFKFCbdKcThXHydQATEwQDYgC/WwqaEcxQ/iszfAtyjeP+s4NrHww/Glq5rK8ZUGw==,iv:elPMKXfUgmGGfhcLjVJ6aAFVOouyl1sBA2bMGzP7id8=,tag:Zt0/YsRS6FQ05KMOcYFcuw==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:0i1SMlk=,iv:JzWOFGywT9OtfX/lIAdUTNzMQE6KZao/BZ4pjfxZTYc=,tag:OFGpVz9TsrKx8lj7CxPE1g==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:5qyd39et,iv:n8VtL9joAEhKLWlsJYgmZXPaY6qgNkQ1BcQ95xZ2GRA=,tag:1MXAUjjbV0JArWo4JXR0qQ==,type:str]
    NTFY_URL: ENC[AES256_GCM,data:KgnZujKqUsp12iw=,iv:nxU2p6QEWoahPfWkzXxecgcdv7n/rm14hYf0U2dJM64=,tag:WQtihZOuT4NsLL/Hjegu/Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQXZ3VElrTUk5aEIwd3pr
            RjVVR0dWZWJSZDF1Qm5tLys0ak51bm15RlFrCnovQVRPRnJUc3FZcTJlSmJRN1pC
            anh3Ukc5dDNhQVJpZ3k0VmpGMzdUUTgKLS0tIExwaXliQ3pkZnZKNG5MVFBpVEhM
            K01GRDVldEhUUzY2RnljL29jR3BvMU0KNbgpZauyY05P1TBVdOv8KRuGVUH7T249
            QUjzJMazqtFD72XsNU4hDli8ADD1DqQL6WTD9aQF+ahfMl3ye//6Zg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxU3hCQW40TnoyaU5UWXY4
            M1hhSzdwOEt6TnZyaDNhMmF2VVY0bXZvQkNnCk1VU01HZUN2dE1sUXhCSnU1UHJI
            R0s5dWZTa1pnU011RURvelJYakNmVzQKLS0tIFJyUmpLK0tYaUdCamJ6Vk5yaUxn
            eUNtckloRXBkeFMrRHNTME41cG1KakkK8cpmUn2n4+ZoAN/OnoMlrf5H+tZ5lBNF
            EiKzQo5IJY/R8F0jPjvPeJ4aOQTVxG/dzN7ktMCh4zZtoW8rLh8CsQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RG5vQlBKU1g1dlEycFBP
            US9EZ01PRjQyanAzTFhMSU1GSkNWTGlsTWtZCnVVZFFqVmw5SC9jZDd1Si8yRWl0
            a2I5TDErSHFKOFpZcGxTZitXeTlISm8KLS0tIExRaXlaRnY1RDh5UmQ2TEk0NXJN
            aGR2SmRkd1p2dXd6a1ZkdHkvNGtjZGcKEeGfg/ZuB2OZ+xqlWEqrD7NgzpEK9bOv
            IDjzjXpyAfygU0TFe1P257CjlrIxrWXbNSNyXyZur4N5P07S2DOhCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T15:49:50Z"
    mac: ENC[AES256_GCM,data:dpI65CNZyPqGyMVN5SkRdSuDfA7NgpC5fzV7FPEwSFBTfu4WQyTjfE94WY77HHByEegCa8qcTxcnepH0J4ZwVencVhrQ8inKyqzO1tfgViDoXbikd949RpI4WfrgqChpLI8vspR7TMnX/+5bDmXHELzHA9QpqUlKU/oAtQf6N1o=,iv:PNAXx/6iKzgSDqQBQZ0dMopk/Br54b/AE0ONSWzaIl4=,tag:4E2jAnwFyqWUf7uckxk/tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
