apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: alarm-server-config
    namespace: apps
stringData:
    LOG_LEVEL: ENC[AES256_GCM,data:oGtOqA==,iv:sPrJfsZ9kvMNU+Lo+7HNY7p+wRe214xZksw4PN7TMVE=,tag:X6zp/G9y+TtAiEzQX3Aw6w==,type:str]
    LOG_OUTPUT: ENC[AES256_GCM,data:zh4FYgLv,iv:l48uHCVkq9q4uWkqFBOOhLG75wMuMkmcYybzDD9ocXk=,tag:ciztEuVmPyQi6JGgSZOE3A==,type:str]
    MESSAGE_FILTERS: ENC[AES256_GCM,data:zO2takEeAYDm,iv:XzMuq/Ql+5vltBwNdY3G1WP1+jsCr5KfntjHSPIbwD0=,tag:0hqJtld+POzEwAVY9sazJw==,type:str]
    MESSAGE_PARSER: ENC[AES256_GCM,data:/lenp/4=,iv:3LNnPaJd8Yg/itP00qUTSuOaNMX64e39HVMkXmgcIyE=,tag:CYf+nH+EtwY2lILPRCpcqQ==,type:str]
    MESSAGE_PRIORITY: ENC[AES256_GCM,data:IN2w,iv:GvycjeYL99WHGRck3ELKNI25vHCH7qOEKjr1c/oGfYk=,tag:TxPTP2Ny2QJzeerrrEm1FA==,type:str]
    MQTT_TOPIC: ENC[AES256_GCM,data:7kD4gKnB,iv:yzFXrQL0Pt0+1PDnl/S9g+KS+SaNSzNe0tLXExy7w3A=,tag:QB/S4cGZ410pEmRB4tywSw==,type:str]
    MQTT_URL: ENC[AES256_GCM,data:SFLp7RP+uAhVbcvLmJVcyZM3hxeDG6robVzKkMzxQFlczjN8GoSi8CJ9F8TDH7FAoAPkSFWC1nQ4gme1acCELDTRig==,iv:xhkWEAds2MR9uUFj5evkxbF0l2SUkR/CZPNDf/XvCDg=,tag:icGEQTlP8waMXqT+30qJPA==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:hOpHTA==,iv:Y1WOlupHjfPX+TtLEZjQ+ZVl72Ey6B8WnuSdEL4EdUw=,tag:n0pZxbw/ey8DjK2g80HQzw==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:1oIUm6td,iv:/Lm0Ett9Jpa6ypgz/ceyD+KDyWkXya+We6Ba1JpXjjc=,tag:1mKTYAzjqDKoSB+NEE52Ug==,type:str]
    NTFY_URL: ENC[AES256_GCM,data:cusUpH2q3m3+oDg=,iv:Fj+2JbtoWAJfeE/g/3dlvaioct5tZ1uRPXHjX/GJcO8=,tag:cSYlw222Hhfu6SeyqR17iQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaEFrQ3hpeHRkYmIwOGg4
            cHJrY2dIQ1hlcWVOUFFRVU11ZTRxY1NFTzNRCnVpcVdaUE1SakFMRTkzZnpKZ2M3
            cXU4NU5hYjlMTlFndmJlOGJ1eWhsSmcKLS0tIEpCY2tmdnlLT2pXTEFna0FqbmRu
            MGo0VTJ2YnN1T2RWS1ROQjkvWUM1YUUKAVjXRA9m27vYopgcVNC90AFoLGmHI80x
            qjvjJ+DsKaNu5gvZnyIob1ATTFFXjfb+70HWp0zItv57Nz3K62wITg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSjVneGZRWW1XSzFpVTlK
            ZHRBTmFRRDZBNTBwR2pWR1JvNUt6U1EzTHpBClV5Z1lpVHFqNjFRemJJeldjdHVZ
            VndaUzlBME9RYWt5OEdmelVVUmVVQ3MKLS0tIDMvS0l2cnUremcza2FDS2hhVzBq
            NWg4K3htUW40MnoxVEFTYUozeStTWjgKH2/ph8/0mMejRqWrnM2vI7dH/qTaWgwY
            Phk5wXoo0gk974pLmHhOonIdPrthaVFkVXmpNqSzi+fa+zi0LCa6vQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwclg0dXBRaUtQZnh0ZW5H
            T0pFcFJFWTh5YU5IN3U4aTFXUmQ0WGhTY0FVCkxvWHYwN3hTRVljNFVOZE9VL2Vq
            V3ducnN4bW1FeTRhcm9lZUt1dTliNGcKLS0tIDFxbHptanBBTHFyTFAvM0xMdEMz
            NUlYcnUxWEtaSGlPcHF1eWVHdEdLOXMKYK8bj+WgOUbD3BRjiboWxh+3nptkUSuL
            gBD1lcLe03qZfIZORDbLmXqY7aFlOBGD06xut/tFe2jMsyp6Dv+iHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T16:06:41Z"
    mac: ENC[AES256_GCM,data:gSy2zuXWoaLahgrTDzFFjDN09cyrvRXFHnSVHfa+6TUqGg2VobtRMIAi1SiZJSYsb5rnZcIKmJa5n7eOYWaZVmjcWcqtDdrNjzZ5IXlICowYyySqfxvcSlebdE62sK0nq5+XDACYSxOhk0qmymlB+uvluC6sUn6dzK38WQFjw8g=,iv:In+R10Pv6kPdMUp4M1Uh7mwM6WQYbXLOIqW6z2U+kUc=,tag:qXLyj2pIKZFH0qGKoOuSYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
