apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubenix/k8s-version: '1.33'
    kubenix/project-name: kubenix
  name: apps
  namespace: apps
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    cert-manager.io/issue-temporary-certificate: 'true'
    kubenix/k8s-version: '1.33'
    kubenix/project-name: kubenix
  name: wildcard-certificate
  namespace: apps
spec:
  dnsNames:
    - josevictor.me
    - '*.josevictor.me'
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-issuer
  secretName: wildcard-tls
