apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:FznwT9uWGXiaKS6st469yDmKu0u4FncojvIlr4/OgMAeYX62ndhtQiOQXwnoA2Z2pRRyOs5S/g7BUetLdRDTBdgNx8cRZfKHBx3L6yx41z7Zn93J/CyiZzVGS2rYpOVb00U+QjbdUC6Dx0lIrdKlO4Q8AL8bSxRx3nG8m+MnbO9IR7Ao19cDsylV1W4VDYY6kckYfHTqaGLNSBq0jZ2QDrGHHotRHQF11dLOBu2fTUUEVlnL8CC9D082iJTubwIrWBx9shBsnOSR6RHF7DYfC0UXZwH0dcUVzZp6+FJKgwbOx/UoWsfKlsR5XPwBoXMwcwNcPJEs94+11l5bQYuLkOH2H2cxG2NwipkjVh989SSRTbTmlj/rITj7aMARavqvskrt5M4aKDPuT+LJ/x9JjZBvLa/1vM4R7O9zVbPWLFXjaEUU8zi7KI5Wjk+jIsO0mOAMzhCZBNY9ZTjxf6KG2eAqBuREEv148GrbSl/7qWKS525Dz3aVYSyfeTabnamEEVJ5qv4RCWocnfFrzuImzQBRM3N4vCpiwtlpPRaQz+XUCOZSGvWqXyQrG5w8Zu5Ebm21Y8ckNWW1Skd6j1hYsXMAQrLvZrA0gRa7UhL11l+27Zs9mRQkpWuQsTO4Qxotd5zHtAWegpJLNTeWOrh+7sBPTQRRS2UkaobRi2HybEaiY0dgwTpJzFiJIuGf6XrPwSVIXichsOW77+s1eO6bo/M2nD0UPt6lcHfZ1NGMMWOrnmQW6zNx3w58mg/96cCIsrfhW0/coKXHyW3UVkicWdZIpx4CVKI7DrJec8dECl9VXvcsy7pEXNHnjj/6XHmKKPFWc0u+ldZdC1xDuE1plIw6nE20m3GShErvlZhSnZ+r4NydVTkMW5+Mj9Bc0JbetYZ0SeE5athuGUDQA+UvW51y/6BATnLZwEwlKnsfzNvnD+YP+jTO2nDWjoUn+Xfh/Xs3uz/u+OcYth3bZtf8J8xzLXgSyywLF/Jp4FirWOdkbzhT2H54yWmnzMcoFUUule9JmMmvAiG6aWy2ojEUfVN/xAKGrgaP6eBQDepRx67UVsMJ/lSyV50Qe6fBxOdPpCZePeDhm/cUvfCQSh4b/67hM3D0ZnjP788dn3kZGjBpqZn1JrmrqZuaywBKNaAouMwLRxFqj0Ugo8uf2NflT4kQUg6z9BBYg5w2IaL6tN+jWYPXTdswtdaVosqglRxDHiTI1KJHqA2EhhbvEpF2EvZA0Km0btwKgMDqbBXYO1MwqRyGtPLS1y+jcpmw+8GTiJSQiyzM1Ct04J5C381KPF+MWk7HlDqEGZPXpmZ335O957lfsnYv7XQc9Op+2fc3tbyaTBm3pgk1wJcIqh4bVl5v3CQNBanfdr/JTln2o+Wo/lPS4CKNm4spYmqZI+rLN7ihfX0+FTD1gFvRDzZL0tXykaLoQ6BEBnCy/aqmwFlRJlBDGyIPt+WwW78PmW5B6kQx5cK4QF6NNIg+VCenNi/2SofOxUWqiVqgGXCEc/Ty1aqbh4+07s9V1zfhQio96KbqNFSmjBWqsr8C5aJepoS6Uj8oSj12BRZCdhp2XbdeCGZiCqnE5WMaoHD+1rviIEo4NILLqnlsudw+gTgRRVB8Puo0I2N2xQHAaZWYQmYWftC0GeBbLriAOYqmMpE2zAZ+fBcnvr2reOaqegYP2aPhQmezpG+32KK39hZP0OfBvXLMTJzbn2MnegmriUzdnDSCmm/jIdAOdQorxtiEBkfGqrqVKjcvHUwO+nvcWe+/oTgtn6GbJPJte7p/249AAcTm2xwP2bh13ADCxV+bY1HoEQup9wF0ABrEFLE4R372f4BJXmPcpyLIZGFfvHhh7TRJ9X+/cDVFp1ibdpgLFaWgOWYrxYla3mpcBWkizUGBhSMePLBtmfJwBd0Rio+HtGEPReZyU7Nx3gRVDsPoP0Ai6AtKWA8dmdxOTvpecuxt2Tq6cB/d52DnIEE8JXu6fntQ2jvs/Mn14ymrOvIdaLMxej83MT9LpLTiZxe7TXzywUD2dITdT6sIFaeUcikjLuR5R9KbQVe6a04TFwZ03+hz6MNk0HVIyOJTuI5Y5vx7Ryo685vmu9Y8DdxDRoyHmzBr/YuD5AJLAzW3FxHNMlsuaWNIM0T4VTl9JB3HBG0K9rMvOkqLlYDZGaFyDkQCymVQpuqjb98dzrRf3YyinR3Jm8fFHyhw+Gxpk6am7f5+CJkFHSx2UfPjOEtiy5HY89Dnh7Pc+mSSCJDofZ2KnesuFLrNZ5I395CbaiMbBaIBLxYCOrzQoV288T61b61aoCZov9FSZ/BHXbU36g==,iv:BQaCsIiZAT4/d3FFfK7B+snh0anXNfZCyavzt/e4dcQ=,tag:9nohRtHjYbf4j6ONHIu0yQ==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUWN2dTBMRG42a3VYc0lm
            WDk3YUFnRk54WG5ackZUNThsWlkwcDVtTlVFCi9ZaWc5V2Y1UFduVmtTR3JCNFVM
            OXBZMW5BM29kMzYzeFpRWkFSOG5kZlUKLS0tIGZhckEzOFhDaCtYWkpLVHUreXRz
            Yi9yTXZ5cmRoWGJhM3Q4Y1ZQUy9qRk0Kukbd8GoqasFUecSCzKQTZBa7TJbeJHml
            muERY4x0MBsjuU5H4T0urJzsSiXQgqVrOX2LFI5ttEBFzB29F2H1/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST1dndDJFcUlTUkNNSjk1
            NnFSNXV6Sm9yZHdVTlFHeHRGOUl5MkxIdmtRCmhIRUtYYnV2SlJCN2F2U041Q2tR
            SGRTZE15OE5KNWY1dWVvYmVpbDNOajgKLS0tIDBHTHdqTktBNlJ4QStNbngyNVVZ
            TThXRXBvQUxvM0ZnTnc0N210UGNjOFUKYlLEt+5Onqfy+OQjIplLnw6KGANG3Pkk
            CZG/MetKEkApkNuvhCPeRVWyXebNpEcujNSMqta/1TN5veEkqCe90w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN1FFSWYzS0x2L244R1E2
            dHhMRm1tbUxyc3ZBYWRoYTNtQ1ByREltcXdjCmFTV29MUEVHZUtJZHlxMjM5NGZK
            a0VBL25pWitCWDZudGpRUHFJelFCS28KLS0tIEphcVh6eE1OWkNENkYzenZaZDBQ
            cnVWVmVYcXptZzhyNTQ5YTlMZXNodUkK+KTXfczwttebAnZlOWLbiHgzk5m1v/k6
            3R7GQgDQW/0v6vUG7bu/UrnwGfDc6rT2fEwPMXaAUn5K9np3T6TPtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T01:25:38Z"
    mac: ENC[AES256_GCM,data:/ovBbSTKpSdqO8aNQ1YbbrR//xI1RNiLBHZ3UVtxVtDw0k1tjtTrVNMoZdPf+/6xJOTndJ+qjzGVd1PdTZNEFD7kDSF76n1gzi+2xMIBOPPtR3l935SNg+a1mZxqcmnuYi7VoHD0iU6Kak7kgT9y1d41BoBf9cx7P7qL1lkStlY=,iv:X1mK5umkcnWug4n2Cehzh7MDCUhf48RsBz82njFKuiQ=,tag:w+1DVsn8DnUjRDEdQ0ZHxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
