apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:eE7/J5eVvgPTxPCiGCnFwb/fK5oHNL9JVfngRGLOs21xa/3EAX8GjbJz9OREM/58hlK0tHTnHFCo4me/+SOAD3iGk22FyN6gP36PPRCZCaM+Ze8bkORXcuFhrYYDNw5F92xr6krsH40O6g6U2aqboMeNkWqXWbqPARUA2OKgQYjwbtIvrDYX9qr6WRc2S9FrtBV4uysd68ls8Z6dZnOPANxyU+D4W96PzvmRywo2GeJ/1yzAjPyfBkg/P+ljgT3+wUG+0alDxNugxsYMEyOpleZf0cMJli6Ep10LUQ4z7TFsgyEyDtgbqINMAnGRjvDogcODyWqKMdO7BrNVL8plH4h1OWUDBjiW5z33UXrl6NcEc0m4OWmHahSYYh9kBwbUGXC0KeTuhGRaHuKp0G2wSWYE+ObKwF7KDYeGIlvcdv5NlNtlPe+EdR0d2X3ySDj0ANsFw9WkqI75nm6w3++plOb0BqJBTL5AXAvPWQ5MrchB6MIvrrPyiVHGjoLS9o9IBeCsFE5SGQsQdHJDpjzSv/q72AaRpKl62YVricICwAeBKEarNq3Le1+nh2171GtFkzBSyLNhqELTKca0f2GNEIhJx8tC2EMM9zVmfB22GxhWj8yYXJgtMJxffgzUG4Ph4ItwJm8Be4sTbyZcvScgomf3305D88gRcu3jwQT+JsGbT4LUy3OOZRSbkQYQfiCc5j+PAVI8CwGWQHjOWq2vRA5mwRz7ZiTjoCM1l/JHwPhn8jnRQpdx6v2BkYvMbj6VvgkwPBWJbK8wHSUfiDd/KWDR+uz4bYqTCN4GPKeRqfYSYZrH/m3jPB+tfBEcpGe4IAELj5F5LpmJyLmscjWdSb1BPT3BWUdH6y+X34KdIEcoe7cXPx8rmdRo/n9vjX6BwZXmufJXmGJuR0dNfnxQe4SfmlOxlOq1QGBqxWQtRjzk57GKFBKqznufPdAgKPl/NTg930eluW45OOjbYn8v2bhkMINp/DB0snjoLnQY01qTdGawbPdmTmxQFhF5923FyYLujQj1dw6GqvudYw+64p8cb+SuRfHUiPRxQxUKJFxR0pfjtqk2KbNvyLKnJMVVM6Cvo7Seh/yg58D3CDBLzz09JPohognKHtx8WHSHf4d5oBwAca6G9H62IFLlyHZZHzBMhozsIhy0PoBsY56tCfYtD0ZdBJn3UzBaFnYuc0oQ0jgeQFe0ZUwHH0XW1/eoCVBC5zSy8BzDk/S8/VPDj4Lkvkc6j4z/4O9j0SlHlpZ963/T2nbnHrXZvOCLJD3rF42vBS5vwCuKvD48U8hpnwnM+B7XqZLbCMTi1oXlrheK92uh0FGrDLuia/8u9wqKo1Ge0SyN6tFFni/76ir1C81YfU+Ky40VCYzMqaE7d6Pjswec/GaMmSZl6OTxt0emziq8C6BRY1WYVd9nKQdZtEpZwyGL4ksit208qT7SJ5LUyAx2+8kjEFrgrLANu21/qIK4omFUvRPBtQPTpZlXAOHV9o3Dz/pZJX0sa2VZlE2ECMo9sPthOCXspOf2X1rykmucD07athU6CVQv+Sd6r2iNEedGJZ+pumDGqASyoO2fjBivETAoB7A4Zccjk0sdtdeNMMuyS5njaR9fuWBxMm77P2rRAWhw4T9J5otsMO3/6eqcqu5fVZkEaO/K0MrL8PnZZF7NIYi12RZTwSNfyoZZlTgh8EwZ3pJzVIhgnuEWwhfw6fWrIygvtbLg3cDWkfNIyRnXv+V27v+Morkr7BzbNAzeAuXN5+QTBEbVy+Q0trYtV1ddBEpYx/3QEUp6E+lbj/kTbzo3W0qqAwCCYjDDjFSjLlVCK5ioQQ4XMUqjABWUbR4nZvInO+fUSn/IJ8+GLx1Cg9zlIxQmM/S2P1F9TxdGcKhCekrv99s/JMJpmdmlvHQf4X5p2zeyjhGnW6c+O6+CvSBBzuTxenkgYeEdl3b1l0qt2g6VjZn/Iot+KaMhLG59hqr4pICJO2Vxo4MrA6Kv2cwfYe2zL0v0SM2pejDTlUeWCmGER2SGMJOr7R6m0icq+ZliRnjfVVetW+t3DuFH8Q8cyNYULya3rSyz1jY/rZuWZHN6EzQOfw==,iv:J1Cojl1oJ4Ypuw3NylFmWQYe9k3KHbKeIUOQoNRWpJ4=,tag:a57ZwO3mNhyiYaYWKgmC6w==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSkJRMmhjQkxVbXVNVE8x
            Rmp3SXluVjNoek5aejR2K0ZJc1lZVkU0eWhZCnBaK3pDR0UxQVI3NWNjR1AvMm1u
            TGlhbHZiNXdGVVphdklwSVAzaTFDVEkKLS0tIHNCQkhXQ3pyV2x2ekZpN2cxbDJk
            U2xiOHRjUCtWN0IweEVuN3plOGdXMjQKfwWjOrabYX1flsj0sNltlckR83yS5WiW
            h0odQ/kVt5d70EHuFhqssUe37YmDCIbAvXpU24PvmLprA+OEyzSiNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQUxsWkRhcWxZdjJtaTkr
            SDFYU1dtUlVtbGJ3L2NHUmt4dUI3eWJDK1RJCms3WUlhSmdNSEVrTy9vZERtVnlS
            bjlkVnVzbE5OWU5oUm04cEtqNWNuY00KLS0tIGJqQkpQR2dJRlA2QjlZeDk2REdJ
            dWdNSXdvOStQN1g2VVlDSFhsUXJCeXcKtCYaxqoI2eAF+y484dMzF8HExNeBY8uk
            T61RPSv0Nz73BhFqNZuRjzSbx932Bb0HU8T9stYOa8A50modjz/90w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNFp3QkE4a2loMlJWVk1T
            RFFCZktINCt6TEc2QnlONU9QTWRISDBSVFZzCkJYRlBmb2NGaTY2b21NYVRtTndt
            aGdLajA0ZWlrd1hVWXpBOFgyZmV3aGsKLS0tIEhNeEg4U0k4MndpRk1oNWZZOHJZ
            alBneGdwT3dWZU1nZlpUNjdUOSthOUkKKgo7ZN/xM+0rb9XsXR444dYVkcaWUda6
            IVM68kBggVAJvmHrSUvCEJoFFDC9KaNxwvZ31ImRai+GGJApRd0YSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T02:15:57Z"
    mac: ENC[AES256_GCM,data:UukNJu1I7cBC9akycji2nRXn+pVn1UoJCa77qNiZaieL0dOJI5q+XOYi7jj7wK+FhqTbIt2jeN/dyOyFqdB6G+MkrNpxq+PtwqNqKiSL6/gErgS5FxIQ4otJQdv9jVcrxvMBCcmI12IxSW1QIKOorfixWIAs8CzLAS0YMNSA+/c=,iv:v1HDMtRf+YoQDLzJnevX6FmRyqTZxCI9mrD4/6H4S+g=,tag:xgYAHpZc5aOe3pSENzlAmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
