apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:6z8v/CQfeYRB+EScajMDrhCjkjypYrkeMIMCiID7D9RL2glPVepZ0l5uwmfP56g690oaZQ8Gpgjv3CAYt3dVQWuucITckpbQh99JaDMqw5gtMaulHtt717cJyKSTjtbPELZfsmZB4orr+2oOP9QWerhwt40ZbaPfTI6AgTFyYVs1G3U+eZzzZs4AJFevP3GpTAb9slgROkz2ak6NJ16IyNedq6Xioi+YOUPf1n4Isr521y5B4nQMf82s73imUNdIbGrSM5L+2/bzwFa8CoOSaY5Op2+3jwaoZzb+e8BUd6DacveZ+nWkJoBv956lxphDz3C9y+bq5hJ9+wfrK7WOkBfXzmVuxc4obzGVaEQncdeT1OXRhoA3KaQXsQKsQGqhQG22/wJUloZHAUm9a6rUOC8ebikphloZA6RC7oIkDnrV7tJFX172GZCL6NKeXmFFYRtEFpsuiTKzF3bXS7oQgzQv+P3HuiVo9Av/OG7+x78aM4kDixsClecZ8cPM41XiDu3u2Yk+Gt/VerFNR7eUwTGe3gw8kbF7m7quR5ljrnPvs75C7pit7PgnfN9JbQBIrUhKvO7ZVoCilxgw5uRDF8vJ042aO9Ll93kxsW/ImWN9DUtzzxdrGA9G2hlbPU/IIiUgWmfDBLwWA+Hv56lYyx58XE/mqFPHBH7qGIdcy+9+HGRD7K4fTOhNovcn4asVMe/aSF09d97SgVFrqYviaDCZvCk865jW+srCDquWI4q+6sIhWHkNwYs39K4b1iQ2Spt3TrnPFv1vv8Vs/L9pbJI88jd5l625LOmHjVn0PktJviBjSR9QxF0eonzmYwoxH5PH9maiY3UV1WrBorOR2AXQGSO4qb6D/NYPBe2vLy+AhS3e+Dwou0VhQYeDmlntnWk5TzQsqF0BcvzJ3tLkTLJkTic7dmWEe8Z41R7BGQgJHYuo9VY6GpyG4Ji+CmZ5a3Jij9q4uTWQ2rMy/HRQXNIcAIWuhbdn2BgUQD+3ln4aLlUWDhLslXcxewvtiALx6n1yq/inPwTUWyOINKbLZl/hC6eYwsfsA713vSW9xGTRkw8soiAnhRdxDirwP1Acnzw3PW5W9X3OUVKnAeWUrjplbwPupW4pWskOSRjMgEUUXweOOkX83TSvl1x3OkGJgoHzrpvw2k0kc8S8hdq8qztxI3SQEhPkgg/Rzj/zlqgSY4OLpC5bffTNjYaGKD2Cpqt1i/hqhumje1IOzKReJeLwElWB25YOowvZQC4g9O/sqMwI+ATp9X/39kfaZTDKfQD1fB661/xZZsb9NM24+yI+Er5wvgYWkTubtoYO7smEVYNAjLvtKNtK96IdZt/aiqPQItxUQBC5FgNc2EwMEARQCjY3VPYQN0g1THZIUC5PkizC18oRXSgKtcKT9beVQOlm7yEfoNPkQX+e+LGY8q3LdeEN2vks6rtIJ4brCs6Kt2HbkLcCnc4g0S2/8Uso3gfNcnIedOZ3L7KpXs4Bh3tdSDXrkwSHQ9qhdPguTqWmFJErOn5c37arkjpfdhlMikR1yUJTOVDdtSc2dkACPmicXBsG3pSG7FDRzq4yNlyEYSVgdkAQ2d5ABokTVjTtODcN0LKjegchD+38Hh+2IrIlIC3boooQpj4l4lECD1KYhUPHbWxvwW6AOQmOEKp55V2VL8bX3bFG9auPYjertNxNNMuqBkpq7lAMPkpC5aYy3AHqsvxrG31oP2ihiJeZB+hfE4UlZv2q8IJ6lMiB/RrH/YTqeWQ/07VoeliG7IIZOZYFkp5XDmUGTCjr3lJRqkiIAoAOVUVVVJJ1BD7niv2MIb1CWrgpbhC7jdFIsrTNJraaqi1LwYmtt69O6wUTXwTS9dNlTWzlEkq6NIHyS7x1xIMCiqjXkElSmeys8Ku8w2Hacb+m9OqMecEBJyYGP8MQPw==,iv:aed4qqWHms9KMMJYoQ3RKX7Sp5978Ybr+DuOf8jjFEs=,tag:zZ4LvBwE+vn8eFSQZvKbjg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MVlTUVdzcGdDdzB5MEMr
            Zk5PYS9rTlc2bHp5NFZyYWtRUytkSDJVSkdZCmJnM3dyQ2JVVTFHTlFZZFhVbk1v
            YUU2dGYxODhjTXRCTHQ1QkJyRlpXYTgKLS0tIEdHNmlET296RzhudFE5MW9jbDJv
            RFN4U3FYOCtmZlhwNmJIZGhoWnNYTHMKcSOHRkNnjbJjRfLyKfmJPC71Erv2BoVT
            HdnFyT/BblJjkRMO1U33Tyzt2WLRPMlJuxz8gTbVOXkLJxOeDfHZPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bHFHV0xLTkNVS0hpUERB
            UnNzbTkwYlRJTzF6YUs5MWxDYVhEc2l4N0JFCmY2MFhoeUUwdkdnQ3ZqOW4wRm5z
            MjAvTEE4SzFuTTYyTkE1eWpNZ09GU3cKLS0tIFRwM1o1b0dvcDNHQm5FS2tzOVMy
            dHFFWjlsSHlSeGlpZ3J3Tnd6NEV0Sk0Kz2JvhMq5mbXO+4g1O07/kddlAL3CM2rG
            gcUU49dCNxqzOKvLxpugxFlMfv9CD6H3fbgjSNLqa7vE6uuK6Pch6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeS9IRmJkRXFSbGREWWlq
            U0p0MnpRaUNlNW45Um9OYlhlMjJPRGJqQ0RNCnppaWhUdFdlQ2JtSGlocGJtTllW
            Q1F5V3F1eXI0dWFWdjkrdWI1MmpVUWMKLS0tIFpzTU9lRG4ram9BYmFYaHVObHEy
            Q2xHUElYSW5GY2tiMU9kS1NRdEg1VGsKZHTdiXRy6M+iDmiUrykat5byP8+DdJW3
            6WWFsy/+FTIE+fq4YD3PXEXzc7lxIJP+r1q4WPOzIEFmE6dNK98qpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T19:44:36Z"
    mac: ENC[AES256_GCM,data:GRBe2tG5SwaWUzbH6RiRQV1hOSeyCbTtA8/iT2G4s6kLkM1f198P2xMvqDI9nOSzQIrZ1ZRvP3PUBkHEZML7agnNlOv3fK7lfmcTI/+BlUqXX44yZOTzTEUKgMRdXZuXV9TDYXjO9a2eFtBwTxpqY61E2jDlmlbZKsmapDYHCXw=,iv:v6oLKv3Qo2fhHs3GA9N77hdyXYXJjHdSgzV0kfsUcfw=,tag:L7/IP1O32omoiJcbtzvQmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
