apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:PO5WNPlFvW3yzfIqUN/nT7sU5MHAxfrJR8qTiuhC668cvqOwAr0LShpfIlutl6irhvxxbwL+l1csL0L8rGlPQnT102vjW1xQ8RqI/UaFgKxOxVZArZPZZxEqx7ziP8UtnHAfxNbICe6KnCfBcZZ4vSFI059nXUR7mOlUk0KIeBUi4jSk/vcNs0qYs8cg2f72O/W1ZpF7iJV44zfp2vRGAwUppoJ8UqrBUyVWKGz/r6FyYaReyqmvFJczg+XvTe1ws/62Nwn9e3N0gtrXx97BYajlwNJ8P2IyMyTTWPz6WUl+3w7GijVED8HBmbR4PB9Iva7Mw+JvpvywnQl9yuK+hdQQZ8b6i8yWNbSefN7HIOOdDG4U6p7GbWF4WpDd2MDNJcCEi5CWLBGoGbqQgMIcQGi7oW+wQYK2k4F5SxYoPDDnzaqlP/0I5+f8FdnvGUTh8xqXjx///J6m/+bahmL2wkMYlx07x4cGmzO3vJgwwzqxpuuBJqxknLvcVDnnrWOfKgGqmRn56pHt4wDHzkErQ2s6w8gD5I6reSjkvgnlot1+lLt6H4+y0alfK+7qbM3VkkCE35HS8Str2xbRc45M1KxMGnwNtCHShvGwqJBKtknrbx2e02/UeQvcgzR1mODXhm/7FOVcLhjspGowkSNJHlJTPEq+45tszKgeHa+4TvWlHBnYXt4u676Vj9qp/AjAaARZBZRfqC5AdjUFGYCTU8Lv5ra6y3gmYa/tZv5VrwQiTLm1riOJuudIMoGgS9OCcL2fvvgH9rvfDO+laEw4XVu6lGLuLdkIWx93umYsYjdviyklRgiBIBYS/QGynpEFvsfUDD+TzzK2QO+0b4t8lJEYvPJP8ab8O6uE20Wh7I/Q7HOd/wZZQUsW/37ymDqb8SdaNVGTwZnWi8vHy4qD87KNhJuQGxE9rIPyKypYicpiq8YXxGNwZ8dF3r09h6VKH92fHpz0jzZuJkWp1sQRo6326/5fTHr91hc4ft0mUlKqih6A0MHW+G3gcE7q4j+SibHni4JXSXVtKwDiUPLPkTZPjpWKi1Tzne1V2hY8bSude0l03I+8hzuGoTg4DbUGaGlj7XT+Irn1ZdMXPCkIXnwzExmb9KbI3c+l6RHtAYXRn8wHEJ2KwZAdR2JAd26Lc/IJm+CyPgM2Vf/LGUYg7/3/WYAHTyOJbSRNGKH8dJkipR4HCLVFgReTteq3uvlTYeSHxABQvrSB+Rclzg+73pZlSBA3Vd5Qg4NlD5v7pVMtfSJX7KzFl8os8Zi9z25+vhxuLkkos2dy3DNthkZoSZot6NaFIEOSSVvAks515qGitjNJ3EvK7L4wk6zqsVJbC7rCsMVyCU+Nz2hmYMz7hvBUWBEwRAnFBxixmcAg9iEY1jqwMsDcfHlzfSiq6PpFCBSAaXWA9MsvVvlFajLYN43zoaQ5nuDfHft0iRfIW18oGfSerWYctVYun5Hq5lR/ID1hM0BIjrUH/8PzHERuHv8HjRMGG/Xxlo0XKZhJYqNm6Ehw0Jz5SIq0BsXSR56j902bbCP7XOAMH3j6iR/FeRtNd9EWMSkr8bLIN4e/6+Vj63PupNxv4wxrpcZW3bRxl+5N+uzmZQ1Xx8A+dfmUjIljMv6Ix3YSaNhRujky8e8uvW75/S9PGlkJ5+ShNmGllOk0gOlNfI4jSQVkW03KsyA77ty2bnoBp4w4qg6YuoqVuuzas7pEl6x6XiWLtn61PW0qWR2HW/zolosy7kACnmPlEy5o1PjubTKFViw7wQuPBBq7Dq7fal46dc5P1m+U6o5SAPf7puRUgb5OwSNy6cptJedd1r61ly1iJ4Qi4VBob2Irz50GB3IAZ3V2vCppEz7MVZYUFn+Jytligwx2jvzILkU3L+dLAIvAIgJ+kX7imPOBhAqTMEmYim0vEc4Natg9c/Ej1sJ4Prv4ecmFrnikMUqFG7OCVWpXPQfLMDW2R55X0QQlJtM=,iv:ORiOd53YileM3LSHSm9uiQw5KaNq3tDXGj3FuoIZZ38=,tag:W+27X/S5PXCB6jT950voCA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTFpLMjJGNlRXYXF1YUVw
            L1UxQS9UR3VDWjdCUzFmTVRyZS9rMnlNUVJZCkNFTTMvOE1zSUZTQzRXWE4zKzNp
            aE5iWnRlYUdaakdUOHJERitCZWtjQUkKLS0tIDdNdzIwRko1RG9KMGdvM3prRWF4
            ZU9qZmJoRGtNUVNZcTNPeXNnZmtncmsKt950bBG92GKDY8MPjgGfxBsIyuISXnZp
            BWm8SNbIvrnImU8eMyjODl4OJR1jmfV0kO9qyJoz/0iWnlRPV/lyHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVS9DYWNvTjVuWUdwL0gr
            emlsdFU5bmE1MS9BMi9ETUo4SEZlYnFHM1FjCmJ6K0RablBEckVsK3BYbXdHRTBI
            WnEyc1FXd2x2OEl4dE1GVG40VlRTR3cKLS0tIGs2THFpTzJESEN2NEhqTVQxNXVD
            L05LRThIVng0eklud001MTIyWWdEUzAKUDCjpdzz/LKwYDMApia4Q24PRspegyjQ
            98I5hfBkqUrilcQSFM4Wq0uzHE2oGs0mqRsZRRLAS2c0gRplmTo8Fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdzJaRFZoSEFTZURLcHdS
            bXRESWtJWjE5c3U5VFN6emxsWVhMdHFsOGo4ClJ5R0M5K0pMOUxmNDRmb0FnU0Zo
            L0FOQzdCdnZLYlg4QkJldUNXUmZWcEEKLS0tIE9wY20yOVRLNnptaGI5VDVyVGNP
            VHZKWFpkUTV1RC9QK3U4NzhkQSt0TDgKgmaFjyZwyBlKEJe8Bv5b8N7P4ToBzm6y
            UF6klWJFzz3Wz8jbC7DGFYXxa3z3tGXSDgy5wUMFPBQBvo+KmV9gyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T17:35:13Z"
    mac: ENC[AES256_GCM,data:nljBVBOSGbwDxFmQurxdY56ImDoR8udZiAUu8Bj8cwuHpMlCpSp5H8J0KLBodg2R/ESUJeRilIQYv2m24k3qIu4Z0nfNnImzbytWeWvD+aDU1zxTgj6wpvbptdBz5ydo7jYit/pctco5ZvuA6/eIVlUH/D9tel7T6EBjZksEyB4=,iv:l7lmI8WQbzvQrcVF0OibggboPswx8OP5FDvq1jZHELU=,tag:OyAowuUy6DxKaX0cRboApg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
