apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:ZTiSUsyCDYN0d1j/G4Y+8pY+hR5/3u8bjzLKkKx4dS7XTWsDOLt9VaUK7kl2bPEHB8oOc8eaRqz3IL2x9nmfRVnH9tlPs2g/+zbD5QGvfrhPM+K7DddqgI9AtTgpoz2R21nDwBbuySfNP5etZbbSW+TCtuxrmLjrRF8xbWih8QQhoVQ7acl95giWgZ66JxpDr8n7CuUdRLq7cL6rAIVHxs9yhvNBcE7DXo7CkiCZSVNza9WqFfTVj0aedpWL5uqMD6WRjoZv4mxsiswRUbyL+kZ5JdEwb3q1YNrd7jMm/Dl6Qlh6/RWL3tT22OimqS8mzg5xH4/IHuz+KU/u/CmKPZo9fsf8N7kowB88VQcdBuQr9GcTJvDN0h64jvyRXv0x0g7PljyFWr73QwDO4vol+vGFYm0E4Wo8QfMIxGReSwKCItc6IMFEfrG2VlreLb+zhanufFzmzgZOSQmrDzghv+40kaIQdvkQWx+PmYFhtkq+sxzE3FnlxVtevAGfohZo/qffobcTbLnwDNhaZEpMTjFKCrYaKpXepn4hqR8ZRz3QsZAwaRDriEPt+N1aTpexN6FENVqAwu6JBkaIi2avN7Qe9KxyYjnsbd1ICkd0pPkPEMOwCDObSaO1beemt6Yif0OCzF1qj66gWJsgaQuYziC4j2sbh8PtIhrX3KcCLeyF39p+9lilZ6YvlGwVMPLFqhSNTesDMZ1gt7SUZ7luekIe4lhczoAPk5V3hxVnkQCGF7Z6FgXnB6FvoVnaJvR9x0X7MEK/mPNjZ8Egpo6/7agL7yDbSjsDumq83IBb9ctQ57owpe0QVs0z2eVoL91jBjPWVk7XJZF/VwxquEgqKjJYHyDovRZWg9eHkbxSb/5rKOTaX/YtF8VpsFPJV/QxbY+od0CbpGyCULWVYCfF9tDpFSRXIjvfRUM09NMREoSlbRoG4pksxj9aYPWcXdFS/OYROyLRHb7WfsKhyazCy+xYWsAZSUSJa5T8M8p4UU8VGTuB5C8B1LyYThlarHjqgXYGWN21zwbYWWMphiUhoHRw2J+ABbJzMD8VpGI0n9uZmCduYlZH74wx1XfknMNEZjIjzSJ5bnJX3jMfRPXBBlfRqFoSfWvcIwQn1Nna2sP1pef+NZ+JyaqDjLN30a/JFDJqezhBt5KLGizfmN3Z1MTC7r9aGmda+XDD+HIlVmu8QXy5fnVmqbVJBAG59aNLxptVnN2L9SofewneLYcsacPcPbGxCmRi5nFOOUd+ttqXjCotJ4ovcc2DWU0EeJ+jzJZYAqy5Ge38X+YjIp6O6zaYKVaY0vHuCF6K2baS82j8zHo7MgkBZAcsF1KuYyv6PySMrnMoEAbTOyMKTAyM+t/M10gRSttJXj1RkfMP7+6gGdHBG9sAJIIdMZqleMJOHcTvL4ylUUD28oGeVU5AA5X+Slxl0i23sL/oV9nfn9EvDXlk4jlrmRw0o7jn6Y16FDAKPi6lyFnJ7AksHC0qhngMLhlLoakqIOZUD4g1VQXGYWAGsIzDDpojCaSEpQCqFNRZbO3KPNwSlsHDsRJtzR0q42C0sI4nuU/eV+r0f1Ex5ixf33JN6YMHFsIzt2TbcKobmWUXI3JWrj7al/7McB7UALvMJ4kAzN4Aapg9asAzR9K7wUaeszbFuzV5/NkmVoYvb3eKurtIL1Ewn+5IvSHzA1xGm9DpSmkWJNDL63J4t+UF/NALvpW5QY1cMO1SmPb+FgMt/T/Uwr2zI9II8HAJe20KCUpOtkSxQKhU7SltvwsVCOzj9EWD6yju5m05Kwd3T9BNRkKCt4oSPi+hmMI3LizW7DShiWqpdBc/7mApzwxjM3RCUPw6/Xou5lrf+35STfKIvS1bt0OohpJ1gMAPb5xMrh7uM/a7HCBaCzzU6ZyoE/ysGnn6tkV6lGxA/Phh2FH3tb3qXNIApc97/uVNaEEo+6f5uTdufOQmvvsxYTfcndx5H4x3zciZgfE0uByH2pmloUG/rKoWqhfKpru2mlUkeFTqSyD1ANTpnQpIBQxxmF2ork+sNdJDoGX2Y5hhYAE5PO8SZr+VMmIReZAvWejWyKylsWzlo4uSOSx95AZdkfLoO5k+FAFu7wu6WI8NT7oCNQSJ0kq5MMRlRp9dbQrBaBYanR5nT0wZLKjYumGMSU79untM6ZzVLkYmi7WbQVJ6ZMAm5NGYQ0oyIWw9iBGhSv+vWp9FLeF51MTiRrYp0lHtZU60rGwA682Lj5Kyn0h8qFe6v96cTXFHw+fGxeZGZn2JW898K0Xu9hRFe2TTJN+4j15ulEhcTfMoxzf0IgEybHISRQ8EN8z/sAV8MpQsEjk9ymWY3Ff6wHvvmYlSBF+9j5J2nznlRtOrpTVLbQ==,iv:SmVlc6a9/Kj7P039WICflfJeHFhtLsMC3Qrva8eJmTM=,tag:hi1qHVAeQZmF7uzhGQFX/Q==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVDFrMzBLRjVIb3RFTWJr
            d0lDWnNUVENVZ2lsVFp1Ymp5b0UwTFl0aUJnCnJOamZ6cFlWQ011MDlFV0VrVWJM
            NE1EMHRqZHNBd3hmTElGbkphMnIwUjQKLS0tIDd1T0NYTExjdUVWT0ZiWERTZzFX
            QlJJeVBTaEN4VFlITC9kK2pIa0Q4UTQK+g7feLjWdexjOmnb+Zvt2rAC4a6sqPdq
            dMkhXrj+MdiLAwQfUl8+nzX18vQuou2OstLB6wYggQQJALlnEgo1bQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N1VoUHFYRndWUjVvNWdW
            R0Z6Q1AzekRlOGM2c0cyMXR6cDBlV3BsRGtnClRvU2xjdTI4cDhIdkZhbGNSTHNi
            c0FvTnR2cXpteTVVT1hBNFgvM0xpQ3cKLS0tIElKcE0rbTNxMW40Tko0d3NBWUZT
            cll4eHU5RjRTV3JsbEF6YmtLRlU1ZEUKJeAniuxUjqt6rL1CJZqfWT9vkql8fRTC
            +aBaQ86JJ4qmvcpov6VtoQGRpKvLZobGBRfWeUWAroGD8w4n2n/Ztg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbGhOdGtCbVdoL1JDckYz
            YlpiMnRXbFlDWTUvT296eUFaNmZKUFhHdkNvCmZqdU9hV1RDelliQ2daM0dHT1RP
            Ui95Vy9KdVBXOTh5K0R0OGhvVTk4MUEKLS0tIGpPSzdqcXo0dTFwTDRYLzFURTli
            a2NYdjdaeVZQSjYyNDhTV0JyVXIyeHMK1Nlms23jCHIM6aYFrBIDGJCF/tS4zSDA
            Zd3I8pOpQaHYXfGhF2OBHmbovG+Ox+LaGdWvsS5SNgUPxf6gjQq30Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-20T01:30:51Z"
    mac: ENC[AES256_GCM,data:ZNwB1/VcHq3Z8H0Fp4vTh7QAwCeewO2gT+vybmKGwO8w/8/FIl6wctzFHebhW/xscxC7I6QFyqEjTcl21wDHkCA10zQ2UDJooo1S5d5mwVvQsFVaB/fIZw8xdHLFNh1xmMekF4ji0h+kD4MijYi99hhFNJ6R2OgJZ5p1fSF6340=,iv:7YMKma1hA66B4fmQ7ksBJwuhhVhDazV6kztYxL4vSOI=,tag:wfsyDVrxzO+JgrZ2ld7Ecg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
