apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:FrBVsCgkaHhvnpuccjOTvgeRgEK4o7TYjF1kc+ACax784gN3DPEbMq0EVEAOQjFuLl+0zLcwzbIUxuCQqazTLXTE40UBCcI7r11BsCEBTsTCLhFFzzW9JNd/ienCC9O4FOj48/ywNlhK2XacRBzDSMDhL15XmKEBxdBMWrtDOX6v0SoMjIgNl+J4MUJyXa1NOiKLk+gfGYws6BIZAvF2Tm8e084P3jGR44/cPxOuYrZmNxpcVnSn4sv1uJzorl0cIw3U9/nS0C9TzX/oKnI5aSDrc6ufamNwK+CpRwDt5r1ciT4pL4gf/I6ZbIPsiF2VGQYfB7yrGeL7YX6IECYHJg3MWl0zoEjgSwPTEH4571xrygq78OqSVv76Urnh1SL6ZQYPbpBE/uie11ZTsjwfB0W87ftzAoy97aVZtcD42x6FcreGP0RVO+AZfZr/SJMBK4BskoebjepUDLQshzBiYE7Ky9TN8/rIPmH30S2sXX5JzZ3HohfHX3jDjscuJx63iNj5hpTxz9VSKCDL+6FKwalmSXS/MyqVMHCnb5jc7YzLDD1hK2nA9sUVqYU7hr/3PCDXmqcsZ8/slsnM7R0Qd1MqkIWD0TUX6BXGV4Hsc4hHDGDFV6D45yj3psNPoeWQJ0p/wndUUeepvRWW0GgtaOKw/PWNej0cyPek3P2UxY63J/e5I8whIh5gvg9UjVz1HNRSy3VBE/4NGqRna0ZyXhqEeWIY6l2Vzv/62hOomHuYawFWuZ/IpAeUSKvIW4KZ5Y/YA8MaCChNU7ip+cgQ62LlyS7PvncXiSs6r7mLxAabDFvC4wk31xlt6YSRXJOey4NSUhM9fmZzzHC674xw6V0b++SVxTHEFJnwQfaHS6xo3MaaJctU8O6HCVPjdTL1h6tLxSHx8GsyffypQyD7YYTQTEU4Lg70PD9WmoFYi3DeXAgyoqRxkbYyCmb8erJCWhBHCJ3fk3YkF4LJBmp/3M1l+dEmeL1R6WxrnXewKG2IxHFcP/mplny5GJ43QKf6/IL+RNLCCkGakzcD/eNjSbidXF8fkMBqB2nXufEACfOHmb6b9b0wYvJC+aG+mbULu/ZaW25IbBN4QswQj2+QjVl4iWW9FlBHBekk1jM+ZXvg4+u7ZXMkFfaRKU/TIXlqyDvhAznSan9WXd97rDIOsFrULYn48XfjrWdSadTueDRUAVnNywYHZ1QQnUtTI2XyRWp1hEBsJRvPEaNg07j2lFjBYvEn2jsFgBfXu2nFZEC4++C4gD2pIGh1bca6gYBDkc7JOWoOEMo5doBoIexOqOUqMmCwygMg8eIDXsY4HSdL1lsjgJcWzx5V3OyxYcoX+QeH5WPIXOCm3XZB86rJGvNNRoiMRsAQUhgSrmA33tm+5FicRVIRTqePV10M5KGRGR2o5b6xv8+qJSBYuV5bLxcC6QXAraiBA8JSlSVeHvhdoWitIvYAbaOhkAc6BJvXOC7fnuMeh7Bi98kJeBrAw4pd+rGRQ+66DBqqJsg9Oy1snsOIJNOkP9bKyjhGHvDVoJtj2nVRcEL41X2tdJ/xJYpUkccHWzfZX/4itkIEZWWLOIrzsr8nR9Ut37TDxdz0MRqvrEppFwG03aJ5LfTxEuQItauVEhvewzX4+wlnzRwU6LH6oxOB6gXPTEByUPZ9aQ+ljY1z6McM+NmI4RWjJpU21Hn0xzK6zRxMGaGg6FEnR+GEG5/UNQAcsJgvA4RNjUGNpYn9saCfBNFjNZjpd9MqCC02FbV18VLfbrQoBu7B9Pxz8G691ztwc4KIeAOKRfnYoYajYYwjCRkQwr2Qk0DJ8pcKBwgqbXPELFEqgY1kxrqFAidbCZUMz80uXqSwl3DmzVtry8Yx2ROrfgpp4Ltn37EHZwp7Ib+4Ap4BqpEfRwx7jTll8F9PiM/fRzQet8jb1Qs=,iv:dNT9HinSPrX3od9NUEDdykmhz1yD74PnMNn7PpGe5XU=,tag:2L/DInFGPDAQTdi4fBIUKA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQTdncy8vWllxNy9WdkVE
            NWFkbjh4c0tucU1ORVNFY3M0YTZzYkJNeTFRCnNlY3pVS052SGlJZGJXdUFvSTV5
            b2Q4aWFwKzFGWW9PN094eXlud1hqeWsKLS0tIDN6TGN0Y3FSbG9YOTFOaUsxcUQw
            eW5oM3prK3VBeWZhNXBIUlBUZDEzOTgK4Y6Dy1lN04+V+UQ+p5whlFokydARVJaM
            SSHTwVyG0TV6x4A2R2VZcYjD/4QPkzFq6gmDs+uNOfxsXA3V4RnLQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaU1BOVlSanV5ZVYyd0o2
            Q2Q0THA2TjFWZXZISm9qOCtLSlJncWkyY1NvCnJPdlBxYzQ4d05Ka0twYVN6ZTEw
            d2FLNEhmRHNub053MUI0ZStsRW1OdVkKLS0tIE80REhjc20vQjdoMEk4a2pUclRR
            ZzNYY1gwR3VMN080N3Vac3k5ZWxOdm8KpvRMKaBTBDYEYUkkSNBSerCisEtpRGLf
            SrtEQh00Gv/0x9s0vBWjR+p6QNFduxAhtkDOUe60JnLBCeRuqdpV4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOWUrcmdkMEJidXJPeWJX
            RDBmT2o2WjZIY0pMbUMwOFNSZGlUVmozM1VRCldZc3Y5TTBXRE52TUZVcENRb2xB
            bjdUSmt6dTl4QUVaeU4vMmJQMHE0eGMKLS0tIHF4Q2lBcUJCVWxTUEk4SGt4T0gw
            R3V2a0R2Wm12bkFqQS9UaGFFSzVxcUkKe13ABbLiz6ynN6IVqfdTRJOe4DId5GyN
            mrwqIBNf01m3rGLwmANVO7Zu7iV0BogTungqaAeRZRIEtIl9pnlK1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T19:55:52Z"
    mac: ENC[AES256_GCM,data:CYTxv0ExdfqBunmr9kX/O+9a8Cmz9lA9ixNf6i6dbHx1WAmqji/zr5wSy4rvOedawkrVF6q0/ojK+lSO0LjjtOHWX6iU/QC0cE4mfzJ/G2mcGs5UgHyQtjWoPIgzf0IOVa7Lcu4w3iBBCDLgrt2MzI1syvIEyduG1VoRHdo3L24=,iv:VzCwSvQ37kV4KzSjt47pNlQis7LA8iBgAqyGEO4MPdQ=,tag:V1Vt07lM7y4J7ZKEk2kzIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
