apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/controller: app
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: blocky
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: blocky
  namespace: apps
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: app
      app.kubernetes.io/instance: blocky
      app.kubernetes.io/name: blocky
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: app
        app.kubernetes.io/instance: blocky
        app.kubernetes.io/name: blocky
    spec:
      automountServiceAccountToken: true
      containers:
        - image: ghcr.io/0xerr0r/blocky:v0.26.1@sha256:969aeb8e573dee62c565c6e1f9604d44a367adfcf560edac4994b14af90f81a6
          imagePullPolicy: IfNotPresent
          name: app
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config.yml
              name: blocky
              readOnly: true
              subPath: config.yml
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: default
      volumes:
        - configMap:
            items:
              - key: config.yml
                path: config.yml
            name: blocky-config
          name: blocky
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
    lbipam.cilium.io/ips: 10.10.10.104
    lbipam.cilium.io/sharing-key: blocky
  labels:
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: blocky
    app.kubernetes.io/service: blocky-app
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: blocky-app
  namespace: apps
spec:
  ports:
    - name: http
      port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app.kubernetes.io/controller: app
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/name: blocky
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
    lbipam.cilium.io/ips: 10.10.10.104
    lbipam.cilium.io/sharing-key: blocky
  labels:
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: blocky
    app.kubernetes.io/service: blocky-dns
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: blocky-dns
  namespace: apps
spec:
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dnstcp
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app.kubernetes.io/controller: app
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/name: blocky
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
    lbipam.cilium.io/ips: 10.10.10.104
    lbipam.cilium.io/sharing-key: blocky
  labels:
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: blocky
    app.kubernetes.io/service: blocky-dot
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: blocky-dot
  namespace: apps
spec:
  ports:
    - name: dot
      port: 853
      protocol: TCP
      targetPort: 853
  selector:
    app.kubernetes.io/controller: app
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/name: blocky
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: blocky
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: blocky
  namespace: apps
spec:
  ingressClassName: cilium
  rules:
    - host: blocky.josevictor.me
      http:
        paths:
          - backend:
              service:
                name: app
                port:
                  number: 4000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - blocky.josevictor.me
      secretName: wildcard-tls
