apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:j6giOk5MXOArrCNQpF5f8dgYu+Gm28W5E410HWzJF9dfCwrGGY+U6Yk85gN2hcIW8scEgtEbqQakxU5axhmc2DyVJlUBb1ugbgSXwou2u36/kcqqOQrtLeQSSnkl1DwKBl6p4nimtz5arMApg8vQA2uWk9r/q4Id2EDymMq7CubDcIuSnKp+a7OCMfxWqQbs9KR/WoY7+ctY7PwCWrtkzyUVnS9ySrBJg0gzDiIZOkNCf6czgyhAcpOAfK8CTjYeCJHsYDlfltp65JvPadH4fNwEluX0iuEotgt3Si5CpaaCRXHvlnK/39Fa8u/GPH5LKsPbyTnh6OijUJMHJC/fdKbQlBRL28oyAW71K3xA1b9l7rM0hljt9EK7lgn/ZBVBF5RRA53+af+2e3vtYXWSkKIzdVWZZ8l/fRdBRDisQvcVRXmz7jjnwvi36DbzaEBF3Qj1SOQJhcrCNDsFvxbBbltNxU7tmCKObt6+OqkWHFN3tz01g7xHKd1rv35ZBkfd7qus1Cai81jY3CoE9BxPiQthSNaidHUb4Y0DZcQoECpDVKCtibhAysiSi5wADOcq+cc5rM18k8+r2KB67BbuKRdItj4eF7qwelUbLOdWWFFxvm+WFz7wRmdV5vN/XXYC5kCCgp8MOVvGCq+3Oawpx5bmsm6OfAe552BfqTVi5cZR/fnxOsjL8Kbnzz7PbvPGd2/CUVpizQx90w6W8yvTTRZmqW2cPs7XhbGKMOHtjCKiNSbI/XiMNboahAG8VrG4AWZyGfqeNadk+a1MyYqCnlosZEJOAf+tTmd0BaVYEKV8gC5q9QGgq8eS0uCuOtq5YBsJ2kmny4PzzzqKk9bfi1764d9EVWZ4jr0eq/lU4ywMFhxs/w6UY+OprZWnus+/ZaxlnKJgGXWAHbB/8/Al212xnOZN0x0PPoFVQtNica9t38LRzvHH0eUWlQDg3MuqIAQWiPq5du+zwbn7sW2Xlva41Lh8Y9OUtvYjU9WuYfvp1mGQz4LnWR0cjr4WsPo47Al7PSuzGwTnJmnzvICf7VlfTQGSWX2CALGlwtHvb8uQtmnI2Ej+2kF6uHW8x+Vi11TyQtApWDYHXuMEa15lqxQKqGdPbz+RCX2ie/BfAtNDz3vNcoFtoqAsMKHEr23SVvC/Z/7Q5YUYIAs0lqBsDT87I4pMsbx0hjQoQgRhUhP54P6/SAvZ578wS0qB2Tno7JP9M3Jj5jQoJaQ+3eLmPBYFHRBaMEBX/pEewtqfZOnN7eU50LmuzXDb7PWHiEySB1ZWFx+80LUR/q8rIhmQlJNEut0siKzHDO4lhaRmEeTj2ibWWeaJv6t19hKYK5Ykg6ZXmDN27bFoqQhG9xlVqIVRhNcYDIQBSbO4C+7xVvdUHZZmbRhjxOW2m8W4SdbWmBBDzkC9WXhmAQex8dLCzhB2xXyVx5nmOa6e6zYARFjcXvokav/mwBSsfrG9bBjM1++5XrHdmkmWnIPUyhCsVzrezsnWmokcjLdOEh9u5N2Jv7I92KYWfHEp57jbbeKjfcTRAcauk7AU5Cz7ZAQYx/8sflUPiv5cW/ZLh0L0xNiQWOMWGk+0JVHz8FogUSWcGzFgD0WM1hCvMDJeYvk9k/B8G3drl6oRXyz9ydrNrkvtLRJPhjt3N9hpp4P34pUpn1QJgCoEIRj4p53JRoJmfXZgnRPkSbXozZE1hr3soRmhfhCmWU5TBr9pR59jcrQhpPa51fk0domY0EdSYa0OS+2RlPgYIwxAWSWPi3IxpFf5GVJmTTLk7VWz8nrz98wWEHfAInRbVT8Hz/4zpzPOwXNDYkn4DBh/Otku7TtREOdC/ZQiU/OtMMLhX4byWNz+GIck//hvE/+jD5zJhT7yLm1pijcIY7chJVwfS9Ig5c/CZC78zWSkkcIWjwwXpPULRNMQi5+KN8YhA7NflCPpypn267SLHfi6e14QpIpe0GtEj97eEv4RJHqz/CdUBFmsMOPTj/V2ZwHSlXaHeqNPS/LSMu9TSMBgmw0MgwmisNhXu5oi0BGkdffaXO+k7wnH2RYvWuZMhU0pbYqHvlFXpnjh7V04P0nxd4e7aDGebOqrHu9XuR+Lv7Qcijv5lKkXZBSrta/y2gSgY1kJhm7itWZwu7IZfGhsYlmEIP5s1bR7AJDlYlBAOareJTk6iDvNE/8rExRmNpPtts8+zIKTlx8kO8hNyNvtIru59iwzJdjbsK4yoOQU6A71vMoWi8dkoWjWxjS1fqff+I8RekUmrPXvydA3by/N,iv:z+bDcM90KWXAtr7losqwQ04cuGy/IfKtiyGEKl7XKxo=,tag:S3nasHr6/pwqVwrW5d98qQ==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0blpUaU1kVml6dWtrdjMx
            TndRajUzNkFvcDduNHIxclJNVHJEZTNLRzFRClp2VS81L0Q0cStpcE5KZHhqdUJr
            TFN0clRORnhWTitOY2V1Vml6RTZEWjQKLS0tIGY1NjVabXNhQXgreVBYeVdWNi9l
            ZWZ5RDNYMk1saFpEV0Vsa2N1b3I5eEEKR7sU1UH9710adH6FzHc7ZkQ2VWzpQ+op
            1YfHHwgQbbN3Y32HdG6pb9ZFBjKPFnGZcPX28miXluEuVHQ2lQAZ2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RGhuQ2hoVis5TTRuZ3la
            K3dYd1hCSWRBY1ZDMUJDZldQM0NVOHJMOFJFCks3cWphYTluU0txaUV6OUpXczJ4
            M0t1dklsRGh5aFR3S09RclhNSk5pUjQKLS0tIG5TNURZV2p1MzY1U3ZBbytUdXRU
            eGs1QzhaOFpxdUpsN2dOM0VVVWVKaWcKEcZ3Ogyw90UhO2/J6eusbyxJSQnjvIa6
            x39IQMWSVF2DTYWtjxA8V5HBaPiFLDvvDbdriutAfDLyqkrXzJQqgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ3NMMU82K3N6anlxTGFm
            WmNJeGJrUEh2NGVOaXYwUzIyVHVtbXEweWprCndzL3YybUREd0c1Q3ovK3BLKytB
            QTl0RFBNN0lwTjFhSDJGZ3AranBnVlEKLS0tIEZiSmhDY1B0TjVNMFZCRzRTZEtN
            aklRWHBNMjZrTjVybHZxb3pSWnJWOWcKG8yorfzUCHT3aE5yHv6/4nufd8IPG+xi
            UUYKc1IjraN2a8kgMf+lK2tXpeKzrVyFxnlgVoAVSG1j7ecF9nmTwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T18:58:35Z"
    mac: ENC[AES256_GCM,data:fCVAwATKX3qFYc6OTZv5YJWCN8EAF2cRPvuR83XE2zY9fU1kmDuI4DMVTsxPSnqIODpfY6giB/Ialc25jfKyZFTMSZs+fAj3+p+7dyxkNPVe4unGxq1EOL559WNmoIsjxuKMo+SIgNk7yLc/uxa5ibGICLNMjlDTP1bx8dYKuvE=,iv:t28ZJsz5IuWOmcbP/HE/UGI6Nr4Q2ect3temqs9zAH4=,tag:3gkCqk6x22J//qa/+bezTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
