apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:ep0Usiz/uDycbwnLZBuM+0euOX7MqiKOpJIoNMeC7SIz4EMwAFYZltHgdtONU8gPUkyVZb8HSFbuORsPNLiVeLoM8l63HIu9FgC+eSgP4leTJ66HvJxiIPqqx8YQrW+HWnbE0LvVtxv/A35/CPP0VngX6QB66xSi4X1WTqHEfolFf5UBs4C51Rd6/97psg0rEeTljhGDUbRIZapp7PETmEYD+G6aH6hP7nJEagrKg2tx81jy5No+jQeUH8RwIC1Tu6N9LPwMVp49zK5zZFkXL9AbXfWGIJQRIEJNY5ujqCccbDSlvIGsOq7InukFF3ATiv1YYubLOldtS2rKy+uGt2aEXVeQ47Arb29ojhTpeRQLoIguZkPhhwFXrMvkKzYoun+Z9UIjSY/gtto2DOH7tsOWXsFtL2Zd6kZdwz+GMaq2AMexFAwHOxFlWgn6/DUuA5DvgChX2Vu0us+P92VEoN1YViIHNEvyWJ70KWUH5T+qXYBBOEVH8PSn7fWOgM32WiHTcxgeALoppeg6Qv22XzeVwRXMZfg8vlSlJFIi0r4tXwMMU/0QL6Nzuix1absmZ87XPOnXFcF5MsTvp4w4JkCu9g4x8EA6pW+WFxrQvpnewxjUC7WVjYozwQCoWQFWqzBl7efgVDAw4Tn7YSZjuTU1Es/SaOQymfGfOPb0FzAJF7tKVuKKnS09kaIk4QbZDUxqvAGpNlYjfg4KL3hcAMN7gm3gR3r6NuTJJ4U1T1rvv8bfsOE52Shvia0lTZqBnZDmNn3GA+W3wpBWDNWl3T9XeAXJ9atWsWvPs8N3Aq+GMATx1Bcx9cZkV9gyUMBSR6Hgty1UgcgSkopMowmf3FHC96LDXTco/l9KmhxOh4Rg1pmB1WoIIWrJxlyUSM05gVhHbxA8qRYrTocrhmDD426+B9ATd+3VhVMKJpcw0hC8mYfzQz5q8znBtAZlM5h3uzredk2yzZIBLz94CcWiMmBtTEhSi1jaGZxfMHwXZDuE8UPktijUu9I3yz1hfocmkC91PdWCuZ98ajXDlsnxLiI5NrjzMTeaBX16VoLLyvYXPpA02uVhDmqj84YtgY8uuWValucc+jARociy1tQQ45Xig6YVZufqZ5Of6aE/1t5irVjXAT0jyJRUe/MdRTZ9ACLT6NmVf+soz1XAhGD+WXzMyXcvrSPMuf87IC3LTwv6gxWWT1kb+YkyvAEB3Bn9ceu87XJEOm43LSDelqpocYTupnmVAZgqp0BNzXLrLtEsxrhFp+x4hqYIW5iPaMVBQyfZLgFvt7gv/HROLZV11XHzFQSaH3XOLWmOcFWzRti27c7gM3K2kMZQtfbSvYM/u2OYpO8krJMofFUJDdp3itYH9gUtoBUARrW/H8F0yfraxRfMs9YvulYA2/7hIjGRgHf/G8Jzk0Qctg3ZP3qzhypWsldaSAp2gRvwMboaffdZLl/xm1bGp72fKgIMOa8Tc9LJ7sL68K1VjKzdyDdqPcz40y5ypUX0GvVVnrZRS19h9lIqUcU9j2aNbLz+hcuJWMt7pjJX5FtDAat/X8suzIG7JR5LGKk87RwPOJd4TNkgsCkJ2BFMN2CpQkBh1rGkyv06jiQ6YXiHAeS1a2f+UKUngjvhzGqHYN2vlo7KRZUT3G5vDLpxdhe9JQ8JmpsEvWJG4WluUR0TaiB8OPcN6Qss4Z9/CljA3G0Oo2a8Yce/BVBtcR7IxWhG/cL2b2f+ZiVLUnUTH0kc7VIRJaO4k5Keg2d1cUjvDNK5yVnC+VqrOZ09YCAnZ7B2AcG+RiwuTrTMDdxPfUtkRxGFHNe413ZAU0dMFfRe8I4RZEQSoVNb5ZVp/aQJWPX2+Axo2iqNpTszawsAvAb7XdHj0bbelnL2o93XJP0uWxQReF9Ngm4W1k9tZePb5BrFFONcZQCeZGB8sT5ZtlS4ursPkWFzrDSPRMjVduxDvu2fCkuWBH8XLDrgWxdgvriVOzizsMTCBxxcblFdW5NbmQrxNDA84wMkXg5GgiB6WkAkj8Jgyz8JTWfIXdLkeIu1IJkPeWk9qJW7AoazZKoMjg5KzAYeaJXMYwPwvLR5NrnMT7R7GNP23fuSdJ1jhHkrIHqPb1ibT0i8v6uW0Z9449FcKP4WRabEeJvvd0YP7Hx5NA==,iv:yhfAcRJ1aIHPfX71I9Hfrx4aHT8SMEdwFDe5AvtmnD8=,tag:G9XGJdbI7GbPA5BGBAR9JQ==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RzlQR2ZWM29CaUpzRUhy
            Vmtrc2VhZmt3enFvb0ZnTmd4TFRpcWlYWm5ZCnVQdjMwTVBMTWdXRUxBRkpMcmd5
            ODVkZjZHa3FaaWRrd1pBQzFvWFhtMmMKLS0tIFJjamkxRFgrcXJ4ZlpEa1R6VzU1
            RTVwZGFyQnUwQXdZUWMyNFBtcmMrN2MKEkVinGa42segNc2dAey2gUMvhoQaLvKh
            HhEvbQSeCbElxgQCpFvb0S++UshSToIPlphN6oBGyGNJAFi7XX36BQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUUNDZE1XTlBpY3VyUURH
            NEF6YUFjWFlWanNxSzZMczdQeTZYWGxXNVM0CkRnbmdLeFVNcFpHb1diY3hVSHR3
            aDhNL1ZSNGR2UjJKemFXSWlhUFhTQncKLS0tIGpXMkhWVkE5L3hGSXgrN3BXc1gz
            K01mSjUvOWZzQ1VFVC9DL2hvVlplL00KpC2xoXMNNf+JagRGZ0LD1KHOg8lAgefP
            bJ0lXgkqpmwNKyKsuc9ZH+DZ9cdPqSgBxdWv1SaL6PrNd+y3zrtJqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aDBxNVJzc1JhTGJrNWhV
            dFJia0d1N25oZ1grYUp1dDBjNWFHUk1CaGdJCm1oUk5nRUdYN2JUODZKTis5eVBx
            WHQrdm9FVzF4OTlwZkdaVFV5bTAwR0UKLS0tIExlVHpiaFZrUFVMMEhDQ1FtZzZW
            Y2UzZVdhZTMvWklJaS9lS1BrZmQ0a1UKOhglwvYPRiCGJVz7SDf2NXyQ5i8Abhp7
            TzaYqgH4rEPyBMdO7AwmqBzqba4XNNWLUAnibvoWO6MKXL/FtHbHUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T17:59:04Z"
    mac: ENC[AES256_GCM,data:szKhbSHDcLmIGmZn1tmrFdMmaHc3pu+Gt0Iu+X8HZqV1wyWMZTB75xqezJsqcwWUUbgLUrDwiOBrvcWVel+xJITZPz/oHo/lcSH54T+6Ga4HKCd3xRQxGwSZk/v0CVKBdck6xcdu+O2PWyLpzrB4tuLJd7/2zPZHrWmviBRFqDk=,iv:ceEnzMTjcRMYO1GhFZX2mD5d/4keIdl8RsbRtyFGFxw=,tag:V3wbYRyGuGTB0CNwYIyNVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
