apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:jd9Eoo6eVAEB6+4yY4A+jF6rCqS1oFMMqdWN5x0uHJOXxU5vaasPg0xbjZ4T80ZctGeEQNUUT/yzsQWgYW/RnKgZxA2YDtlAeSXNcyCMziaFp8Cr2dOyILTwhTsF+03Puua8GkwFArTFSjHAdOg1Jtl2KduJ+SUfvZzeO6VKDzW3fg6APd8mJh8o302u5X52lhsk0BIn1EllTHVcb4F9eRMXWHLzyt1q45lox1qkgUux/o63YdNHoYMy73jfOijbsK1xyZTcnkNqUrgpAd1goc2X3HVyTlF7wRBUhDfQ7bdhQ2HJhlipbo+C1kJOUhjQQcO+LJgWTIC3B+jaDcOzr5tL0dWSkxqomT8ekT+1G7FVPyoxBQw1VyXp0jNtZelkMYQz8Brz1WFo0mTymUkATmb4+tyz8IO5If2+hnI7CpN3z0RPFv6PJcxUm+V9xDa0NejfntyDYBMa0SJ8Yxg4gp38X9g5lNLxLie/DhWwfHybrQ/OO2xSyFYdDbCWtvNZitKU2yneOhDrv8YdjFn2VOGFlQTumqEbI72o+PJgRlC6rC7iPbpzBkDtZgHEWTkj4HrrlmfyUMNeS5QcI/b6O9OFPwO3uWtUjcLki+rXXH/DlSRpGdjSg6o5YdzpMvfjomMURsqHlydxcqUnoREalvdkuKwcXJKZI8R6uciAo/6IZDb647I4jhRC1YHX7qP/9PlTtQfMPlw60KkLSNocP4YsplCYF2+aPEU4SiYZ5/8pn7uVCR5LfFkVss62Av/eQUNe5BY/kiW34zzihtCYKHQ/QtCwZLBxkd/tUnt1UQOuRNzwmxxkCRN49UeXp6g4HOcyjUcU1cKKCJHmYqVOBLag3BDPXaKxfv9FTYO2xZ0sBDjqHPlIu8eDC5rO8hULZe+19iY/FHvwnsv6V5K58Vxk96i09DRe8GJmEmk7iEXmAM2F5bDwOoRoZNFnIjwzNXQUrz2phg+jnaRxqr6/mlEHBJkqpWtWfLvf5+RI3nVP9NKGmM9iq678eWf0utWWChIZP/wEh6fyv4nKXJ6W56vF0nWd7k/A9wigvyEVMgVpWUlKEv4HXbTD0Mh5kdRLV9mo2gS18mxUeQVi0SUNRZs6GX7aSM5Qs5+hZBfGDcOtSpZ924XQZw67aFr+jRCtFIn7/Opl+uBIuloHONBxpQd+8WXqgE6TyR43BU7Ar01YSmUO7JNxSvldYWBamGJbYtLOIqFV1vo9uSGSe9o+SWkhiT0ObmMQSPI1MkST7AaE+4kEuGLhm3aJWjBcHBtyOR9zaNUsbYMhLIoiL8MfmppyjHDypghgJoQBHUEeKfouWZtIr1ijj5mH/MhEIJp+3l1MZtVeGUrsCOAbM82BRfCHTwCF70xOUKysYQWe/uhiTAPRMapUXRiu/dFMumBNv3efj82QVLz8DEBCDce24RV4sbuoG1y1FJpAKB5XHs2Fq4msHfMs90SkFDiAG5fW60ozKXh5JUDJPGEeApEZw0suhiYByoNU9WmVjZc0+LSiCNJLaVYZl7AftK8wHlFyHXo6FAzG7f00DanJY4edjmpoDC9mBwy8c+aAehywRmzv9JOzKB/2jsEGBp2OcZ5Upm4Rl249FO6vXW9WZoZ5RxReZcwO5sET6MpgNrGZiK2N2DGyNdvm34Iz3R6CeGaMm7QN5/7Cm2AsBpdM2oLAR+VkJ3T/f+vlJ7xJ27AsblEqjGAXe0VY6E6HkWzlK3OFOJN0Ff38QnPtOickBXLkn9F68kVl7g8UHKgAQC/GWlqLvsgVX97IeaqOzhImGhgFt3Mq75yvV8zgyk8eG6g7RfwNphH2X8UAagkPn0O018u6Tv9fbs4tF8CzyuaO1IbW6VuMe6Ac/ScAjC1ea6Zir3H+bFamzpONAo0vD4aZgaPDv6rYr+xdnBSz9FLnUZf4nYM4UKzTuxO46GBZOkPIFpFkrP2tY2HFp5RMsjmeAiodOKw6ntIbDgWKi+J6KzkLNxVLrxe0KlfksnRLjbwzNFKYuLBz4hb3L/QSrmwAaK8fYexviURHSl007nspHPxBXXzYm+M62hkzDIOYMRP95PEXsScq1aHkMbC+ZotJUHE8a094lf/c5K3qTpnwtHQu7qThrqo/cwjSD7T+X+TvmDX0kwFXfSiASI9snIs=,iv:8R4DWNsngUgnz6o1yQh7puhavgaJE0s4jqh3c9aGI5M=,tag:w/fmiBriq+mourQZaSnbrg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbkVUbCt5Q21zY3Q2ZmdJ
            RU5KR1NvRnVkakRkckVQWjRTMzN5UjZLNTF3CitadFNFbFNHOGZ2VGxwTlRuTzJP
            cTh3NUtJVHc0Z2ZjODZBV0UzcTlzbGsKLS0tIGhldldaZ0k5WEUwd0xRdFJtbGZR
            STFkL1BQOXovMUlhWml2Z0ZlbVJtYXMKNHpkK8niXki2GZ4maPSFfYHJSn8WFs5k
            6VdP0SJzrOL8IFL3+u+VayE3YGt2m/wkbU27WGa3rDsncZcMdJCJxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcUJ5YzBHcHpJRjdnWmtD
            RjcvSU5TY3FleFd5dnZkc1VMOTFzaGhyckMwCnQ3OXFrNE4vWnZ0NitZUVB0TmlH
            NTBaKzNucGxKaEd6N1NHSzVPblllMXcKLS0tIEJTbGwrZHZSdmpteG1ta0tqTEti
            SjhiOGVSaWRkOWdWdHY4TTBXOGJETG8KPX8dd/rw1CS7x+L5sSqlzMzxnxYCAe0Z
            JRpItd4gvYoOxGJUTg51+EbZIbVKyITbNbR+BoDbTWtDUSnoqrNjGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYjl2MGNpTXpQb3lEUEJk
            VGZ3U3U1WCtaVTN4emgzOVZ4dDJwRUVNQ0UwClRKZVFzYXNxK0xEYzBUM2ZBUEFh
            WGZOaTkrVFIrMmR4VjFmZEhVYkl2NTQKLS0tIFZwMnBoL0dvV1FlQ2FpQzRobmRV
            OEU4Tk9mQVE2bGFrMCtVaktzK1RUQmMKKBEPhRLBSnBZNd7lT+7I70e2guZv7jlV
            wwwCMcU8sjzs+4DIFImPa0oyJdgkORDLYfoSNvDusfY7iJJX+cOVUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T17:18:29Z"
    mac: ENC[AES256_GCM,data:dH93FtYsNZRC+RWQScWW2LYxCJylYiWDu8B4VxZq4f7fmFH7+Dr1irYA5CyP56YrSeFhtTjvE24MSEjNtiiItUyT16DpXqbClMTkTRmNV2rIfOlPV/Mu8hz6EdRAvFiKn7brRMbTaFXfWyvMlZnx6FZLpWlQPyJEBq9Wd61Szr0=,iv:pelg4rVAQtr0Mlim1EWc4CxsInFrZAwT/tw1T4l7ySo=,tag:EC6LYYhtZgdlnE2SKlIu3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
