apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:rPhg4vz+N0J2teMPYS4qe7QF0OdX94CropBPx3p8EVl5JxH8KuGKTO/+RhY1TSdet3SYOGUgi4Iz9NVsftFpbmMze6jf962XaM7FshV284N+HXLHLv3R5vCbaSEixszpp1KDkLJJBnuDDzkOhlSt7Jo72S1d+4Xb8K7d8YYV/fvh+Gy35QnQ/jZpRrEPfLeDWcjlnyRiNYRi44MZcK8+btpoLZs3zVraybHwxD5LJyvxwpFIEu0u6sEKYYjTnNts6rQG7phci30nVqbPHJHZPtkzTpqkmjG540GdZ86gTdtZNF5SIO7wDleuwqlgHOwOsLrc9HSSS79kjdXkV/4isj0nJn6kUavQhUDWmBlE//RUKVSGiG0v29FkEUQH8wmkwsWmkPQun2K+2fi7a9PWzrwNTcgpJx60t+ZtYv1IfsuixO3/YSEAQKvbPT6uIJ/Iy25XrkP4oYAYqKHSKf4UHt9rILHkeDbS6UwzMqKTUIJL3jGG5G9I2m2JUww8gTKdil9eELWL0xj6uV2+TCwqQzjGs7F/1jLOTRPWo+Y1aks0xSXS3FTLux5J2YgFo4ItZZsGqU1gPBlhH3tjRm49dzSYWYudPPEDTx0BEXX9YiImgyWcFf5Ya/vnefCmvJsBxKQsdyih3Mf6u1WcHOKo9JFsohV8/y/JGOhPDiBBj45b5SWzAHhq/XC7wM5qtsqTqAdzuhs0re1Jv7vWE9vwTRbXLsH9q39OxbPXkNVrhNRz0Zxe1F1kDEn82q2WTfTrs5P8Mg3lqXUaVgoGPkWk7fJQsBDYeyva6MqiDFWWErGXCmJ52NIae1oaP429VeFfUdSnBQlNu46FT5uQW2+T87Zixz/VxVvc2MaczVoBz20CGJDujE1E/5Uu7CBo+jBKH1YTv+0zB0l8aYxxZJpuRQSQVTy54q+KqUlxZlu8EoTVvS0uA4hwXDuF1w+jyFNkar0cytcNc0n3BcN7m0qAxMwmpl/tf9BDwQ5Fqh1LNdfBGGO9mB2gTs3wgGsWDjjh+4E5SAkntQVmAeFr+pz3fqCKXpmNwjlyBVbhvPnOQIZecWjJ0L/qGF2v/egtbfYOlx8ZvviFabEzVGqnqVsvCAWTqNrN6oAKx2j2lb0N1jfJV3rUU7+hF8Aj3EARoX9IwOTugCjlZiqHlB3zk/bBQ3rymBBdTe26fjT7d5bFkuiN/jsxOGZHSfdwfS2+twGuZ5CYwm2WS8Lk02LtBmoB/JWLI5HtjXcjKlQlEbuwYF1uS1+5hdmBSzIWwaEd9UvbQ5w4QNo5op153jzvNndgs9STs52dA07WcsL3l76aabmQHF0/y/2nKUktIWi+kKPMOvh6sxR1aPtKvwkWayiei2bvdjhGyUba3FnOMJzsT8YAoWs2DPCfSptfmAJSvH0rlMlhmWw72LIjZfIv0WoE2Rz82VYtQ+96qODJhcX8/vtTPexgbmDvQmLyuPo5uPjx9KMCNtHyg9aRJBy54bZxQxn2sWFe3cl34T01V2DW0E9nZb16TQwHt9P3UXW/ywg/5Mb8oPQNuO54RgLVVDni8qD4lWodPP7f5rKZg489mzHRmaktB2p3PRoPMrTCtzLvNFun0h9gW8Q1P2YEMj2uMl0JtxZblxQdkTkyPZFPxpgfY9C4VQcDPFnq/agfYQFzd5VgMr0wgKbm4VKl0/CLtpelxu3dMiDcPZFi0ttSdDCqtRLN7CW24sH4xKwR7CY6RIYRud3xYy46LhIykIORZVBEgLp2/3uX2q8X2MZ43twVO/wiuRZxOeVbFd9nDHyWKse+TJJAbIn7obKU1KtmchPdc0FOYGIZ09+SbxEvhe3vWrLjTiCvQSxqSg8LPhsyNNclJI4waURZuBqJZ7/GQxB1h9ohNSVBX/7pX6tIQcIU3BfwPq4Lh3jsaV0JzI05AZIptfVqUK9HskkwwAFm+g977YU+JlKqIR9lTEkeiBoSRlq10BN6ey3vnq0D9rKq4BChNYmd96VG0gvm8yHCJLnt0hHXbD6QiB00RdIIXQwPw2YB6LShpiDBsqdrJs07ByvNT5NB8+pItFmRdF+fbaZFPeygIUpIgSZra7TkHhnxEBp38Sm93ZZwAG7RxdVDuMs4t3KnIPERyHgDUmbljIULEARKDbY4UIDPu0Hwywx9btU+T07xxDgZBbC9tMLn5mC1978X1EsuBehzeVfECEtZFkK5aVEo6i7lt8/GECc=,iv:duMppwa1JsoRbiVDYDIpZeDN6KM58OK8BBuL9rNyeso=,tag:b9ivwFwPrRxkul1hZQmzkg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZ2k4dmVKTDZNNFFCamc3
            U2ljbFJVQllJM0NkWnVHZWJIRVZYN1cxbGhVCnpab3Q1Sll2ckJ3eDAwalllenla
            VVc0SVBTd0JoVHNxU29zc014NGR6bU0KLS0tIExoUXJYM2M2Q2N5MCtWVEJkTTVI
            dTR1cDZ0SW1EZVFVNjBNSVp5djlCRVkKbutuJ1xEEvjAgflKZgvXysMjIzU2CwV1
            7/WReGrQN/8mOakRZ3iF9hEu88yLj7oIL9WAKEzXya6LwXSTdhuAUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTmJWYU9XakNIU2xYNmlN
            NFhBWnIxQTRJZ2REaVVUckJLQndIODFGclF3ClN1eHdFYlpFQ3cremlmd1BjWWxT
            WmdNaHp2WUJYdDhuZUt1cUYxNnJ0clkKLS0tIEtEQy8rMWpqUEhPcUJBTXVxYm9z
            cjB5Lzl1ZUxFQVZQT2Zick1sSGhTNkkKBh3GgaLvQz1rxzPy5B8hXFJoNcyouMhQ
            jNJOXShlThoeNcKlq9wPBzEnVLuuuk6rA3++OcKVP9hjy5iC9GrPrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMktnNktVVDZ2TUVBc0ww
            dHhPY0Zzc29YbE1jSjZrVWpNSXVzajBncWxVCndoN2JpbmtJb045YUIxRGpjaHhQ
            ZEowVWxiS25HRHNWejhtaEwyT3dMcjQKLS0tIFhnYXExNEZWdWtiSkdNcS9SSmpt
            aS8yYUsvNUJjMlI2OU5oeUFnK2U4cmcK7x53BBxZPPNi/ubzOoRHVgiKqjUpax3K
            esxvjuOzKFMI4UtzYJ+TF522pm+VlkqWjPxm4niAeOWq7kUrvcI/Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T16:11:53Z"
    mac: ENC[AES256_GCM,data:Beft3Czmiuqe7AXRbHU2n++Y6aH0ABnrk0SB20jWOapHPYHXDtZaPuWcOCnU8ygGghrjBCjGru/fEXuXs8EmILQ12NMiPYZsPKaRtnG1zegh6MDLbTIwtihT/XbGr/9xmIi43+DupeYnaVwrtxarNVq7Tn/mcc1mE1KYNHCPt3c=,iv:nCRQHcKx8qg/IuS9pNIV8xC8IjVUkMn+pWA14XcgVd4=,tag:/IfKRxixxB+qSBJlZHviEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
