apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:IMwQeiEAC6Ll33bnhty8ZkIE5VnCtBRnASzHzUjLDNS8f1UXLm/xKQDUFr3E/4jqRbapyxprcvLC7mn+YfpLbQ+KxAfk6ssqiyu59hI0JJ5bPut6AhqFhHYJ4I7rnVsED5/PSfJIb+H3WSIPBUbSFrZFYd7WmbXaYMyxzcYjJBo9r/vDnxYzKI0Gmc0JgyBg902mcH59bl29BzYMAqvF+kIGKGTa1mCZSv00dYTe7zXKj92IzviDvk2dZcJHDvwwxx0gbhUtBN1VDyyjCBXijw/T9yhVDDuhhi0lpXoqc+OfFaZaOf+aME9pEX27bfb4qNthih8zPl9f+maU0Y6Kbu1/ymwEj7h05nz3z/KwE/UmcpydlDdvP0X4TdCXQ/jPxEr8OkFesa1I3578bqnn8cesHNnTIcpl4C/kgUmMM8bl8cRid5inDGiALn9A8uDmh+ALElCAnRJ4UVITmaBYT0eZxTKwRlPB/oO5tBMgi9nOg6U4v4GFe1nuqflVfeSL5flxOs+disveQNiYaFUmSN7LhMOyuvkJBoqhuvaiHNNkPbuI3mBiwpUaxwzNQfGW454OqZi0c4CYUytp450WMT5Mi3O2yK9jkboGQ/5eS1UqzCWQpeqZuCP8egThPeVbWs1su6rkXRNEEDP2gWHNa043JXoSXcUiYGSPLxkZ4+pwiBWF0uJ4EeDI7z0vefV/nXWBZvcgRQe9EOp/V3sA1YdwjhmAMPpOiOyZUjrfbjM2exy9n46I5Zf0VH2f/OcDAJIdIWHFz+JthH6WLkGPwp1gWnaPz8JflKoiCwR/C61wz93ktl1W9d0wTIo8oVEI2i26LcciL1XnHf4/6EoqYeXJtGq7xvr22K5IoISgVL3JmB0k2bWJRJN/jMFEsPVQ2tybM/VPzSzp4Gfnp3rTBh7RwxjepKeUs7uzB1RJMQKzDqdr0Vtkoij82T5y3PetaOidSvkD17VNnCXODAm6Kd8yCH7CT5bpSGFQCEE44vJMjMOiLAJ4UC2MvaefuvX4Ir/xp4zIfnM/ycQDbQD3ftabfNf9Eia0nwn0YyKNzrVIH8q/dhBB4yVSlTIoOIFWLhvTbhNBCuQObmZGJqO7NeLKZuuD67B5a1b4nTvF9CCc3oaNCW7DyRE/GEN2ZOXHTH+mlfjnjjLZbGb+wvWGzT20pfiks9M+3qiQ/dJy9TSUUh1LUM0HNNUsLQri+ZT/qPv45xgbaOBG9bKujUTgyD8b/ao/aVT6+ABpLBuP7Ve8dZmvklpbOGYm/e/EGimtWsoBIFisxXT5bB8xZJE8ZySrBcE+0Lma1WBArTaLRNkN0A+e6OBcQTxG6zRut2ZDYN4+hAOmtMCr0MOONpbBOeuJcDORWVh7VHoWAePog6EUbfpvXex/2vmuu9JvZi/Uuz+NkoTt3u4PwAnAWsKL5bwd8NWjbacbyLkC33C+nCWgPBjmj9w4flmyk5Exo9MxJfWjPtEV8VvMkxW4mPVsMdUvnxDkVk02TV4k1kd6kizAOYZ92Cm0D6BRFcBgVl3ELh/CK9+eILckWkpUmoncV4FKZhF8mZeCR0JaajEevjSfpitpwMIAST0JlR/XKBtaHZ1Z1J9JO8vl3Y4bCL+QGDVLDmrxlZgWQlirnAnSUWp1H3dwQYXdB1+2fZ+MnBZGttiVjYP8BVJdOJZxgbAAAJqXlrc/gQaVZnuVqX3jATw5QB1nisf2/rzIe4jBUwoF+oWwLm1aqH9FV4505YfSEYUWGCko0ZSqbWuMIs+nkL8Mx9rPtn+aECWQS4myV8omtyPsk1B20HxvH+SRrTN6moAhf5v2wFjWypXfboQW9seIUNleGFy804+cwVEyhy2eZK37mTsTpr4YfdXw/PYHEs+YQCRcgVZUKLq+kn10VhXhDRDAtNnHJRQLm4g2VC8V7V0=,iv:5PJkEcuMlqP2pOq0n0IB227UqcMjY793uEiEQv6uZBc=,tag:asS150adCczErwmRtujxiQ==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWnFIRWVwOE9MYVErdFJi
            Q2dROW9BS1N4b2JxcEZkTXlvYk9GMGF0YjJBCk96MTNsR0Y3UmdWRFFQQUZmNDVY
            SWU4MWJGNmJQM2hrdDVQMTdOU0hNN2MKLS0tICtpUkR3dWtxM1haSnlZc1J4clZL
            OTZ2MU1PK0NNTzJPUnM3Wk1XS1ljWEEKuM8Zmi/jBypKlb+W4r93zvzKpbRCOcU8
            Mbp7aoIS5gKi0B+z3kLVIU7Q0D2EeBx1NnVSKfuhhppEtoiznApVmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVEtDNFBOb0E2Z1FSMllu
            b09YeVBTODd3anp3bkEwSFFDVzBEL0dMbW1BCkgzZEhBRFJQYmZ3S2hnZ0xTZCsr
            K2dBLzZSZXF5TktuajBxQlpaUlk5SWsKLS0tIGIwRW1mVVlxT0F6U1pFSlZIc0Zt
            b0hXcDU3ZzFMRVFwYlRVazFZWWpuMkEKyVjiJ0zqKjiSdrNNOvTalt0WP2ozyVAQ
            4zkVLkt15MCeeBUGnoQ3sRQEGwbDGdkY3SoZgPbVATHCc1nvKakb+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwY3MzM3pmWFpxT2ZmTVhz
            T05tYXFULzJzL2tsazBKQS9QWWVMWnVTSGdrCkdhVVE5TkVTb1BuOXpabW01bndm
            ZDVFM1luY1drT2Vsc2tJLzRYSzlUVkkKLS0tIHAweStJY3Q0WXJrUGptQlRTTkZ0
            UlkzZjVCS0Q5RWM4Yzl0eTZHTkJIMFUKsbwa6ccbOnMdFatgll51TMpGJhs9cHgA
            0Q+m0r/SfDqv41bd4GbQOUwFQtlZmZrDEHf+xs7P3PSqbDfKeM/9yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T17:49:41Z"
    mac: ENC[AES256_GCM,data:nqzZGTCGkPy83eAGbB9diV942taoNcEobAsW77ZmTp0mU/eXY8jY6aM1jwPccBocnnaXxWG/xg/w4q8EZUy3P6XhRUhgCho0JAqMts4gNTxxjbYHjVEg/wKnMIVQn4J7OOUe2jYUddS16MFIaSOYRtjGE9Rxs7a5nIn1ovaEQqI=,iv:+nOcBQalbIxZiFy3X5bIUfTOtXP55wdNwpXaY3uiYhE=,tag:LEu1TE2nPDAmIf2SZbqucA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
