apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:qHRV9s8kagMEckYjnWt2k9gqQRx1FM/tJFgyozVgwzCSimAnsqAPI0FjHSLr6rdU/xLnYK0YxoUkw6t+P5h58nCFIp0eQNZdvc443UjuDDbBmWNisgU4j2M7t/fJDREv5I75jkrYx5jqW2c62eXFw/w3a6omtUGX2AubbcLFSOGaVYyFepQaPF3E3opw2qYBhtJbywt+1Mk0QYwd2mmgIU3NSB38UvnBS1YCsVTkjh4WA12n4N3NvrmJrZZ7RJ7aI5wbWm++Uo7SSMZkhAG46/Wf1O55ZPMIqiXbwp3ny0oBobDejUqToP6Q4fGlb+vtaUH3j1DrCi7PuErqpbnjeuyKXEaFqTsGN4RE98ZErsu1k96fd/FNfUfolzBL+So56kuCHFuwfWrTYyhHXA4zgn2cuUO4I+yRAkb6xrhRbToilxPk0f9VHWTdnGSnh2gArRQ/on8vh9ZUXGGRs2iNShmokWidSFdaRUpgsepXnkyCl3Cg4lKBvhIHffcDfozzL6cpDyJ0syWwxgmWHnCGA3B4xdCI9R99QvX7RkLBzMhOS+UxSEZ5Jj0b/Vwjv81N6tC3I/3Qzl9z4doDgxxtImhUVdcXcBEdFk3TicyB04two3ALiQZkwHxux+38/2PyYne9spmYBckXc0wCFaE1VQpqBW3aGSD8rpRfktk6TAayo5OM+4GYy7nQofBlRi8yKt4yvGGBUh/5QC91lNgSoOfHYHuAzfHNcAovNKr0ffY+vOkzfNBhRpTt7Z9zvgzWdHwbMe7J094QZdhnTsXnOJxjkwdUXNI6LL67Bc8wfWutYcy6WIlwbl8HO3Htwqo64mlGSuDEmWIXRp/sWnG4jJ3ddpJN4gdyi8IrjHP4+9US+1+qkDcPUQnBtEI1x5wRaJORDFnMhsG/tU63EnoWZW70K8+TO0UkPeOTPXbe2yK4oCuaq6fjffIWrsz+E5A7yLveTHHWcd0CHWSRnICfiY5Vuy1tkQ2z2PjEfOS3tbed9nz2tgNu41HaK7iYPf90AaPqniI8dqUCIVcMAQJznyqvugHWp4Q56g3srjy6DE9nSX3aPzEvr2aQ1hIJk9MaifCxITneD6xH7yTq5ENqWOa4FOsY/IT6LXw0bMU9VNL9zQCqbHcF8EFkQdimA9l/4pjUlU3vZlf+wmgMcd1OOmZEvsFY7WOKqHr+hktIiL3zU1kP4bF1gY9XXTIHTRcipNE9pYsxZ5cQyeg469ZAr5U9+XMJa8AZKnqZ/aeibskBqBNjJLOJsfFCNsGSEn35QI+qYrgfhBUNsCcH/NCFl6t44/ezRXwmwsbLB+2nXxTv5Et/B9VAh2QbIrvTY7WlDhfI1NUoE5Z2LZpVDpLWNUVr/VblLjuXxkjjNdRlNEe8o8T3Vw2o3PYG+GXaP02BUz3GpZw6tprDtpaqsqjHXDrDwBolUYVK7mo+Tvly0zQewIR9V8sSRA2QSYCgCN+ukOHnfsg6NicdML31FRPoH6HnB+xMleP4pKDlr7yVOM7mwfM/aC78+BHAqahxCuzyqLh1VBZann7SExX4K+DPXfrJcOZSb5NgnzIcTF7s9j4upN72ZH9uhEq3LIQ1yXU7Q/8O4IibOElAygRgNKTaTmhQvRrK2aGzSOBMcfquyV/aO3UQOYga2w45MxDRQ4i40zjlYDso9s+W9W1pO4LrVrI2v5FN1v8KJQWMvNaUP6w2xevHMsl9qPlS6MjF8vd3KTro/elF2Ej8YqbKkb5Q75TgkufwwnlgAI7OdBIRSebiiggfnN5lirLgo9j5gc5jcQ29ElnTWJxTEEjdfT1P8Ct1WScpcU19aGjYfBkNflTqT6SovtV11VhQlEfIQuUfPKA9sEPLxAzcN0RLTfrUjgA0yW/sjFW40DNpnWA7MoAsuOz79r1RMblrv/p4UI6E/oBnydNdGvxAokV3qHhlsmYiLk0Swo9rLTEXoCYHTO5BaKsHRNSJpGHPOpO3aqbvjq4oYGHUuvbt5z8Eirq1/41fb0Ce+0nsTYsM71v/KqwBAizAaMmTjBq6ETqrkIqhlpTQWW69cLmor/rZIp/44pelS5t/DFFfllESZxodFw==,iv:C8MIqq5moSMCAI/JxlE67VvDttCFX3+nRoTSZWJdw50=,tag:BDSttqW7TTd/eo/SzXoMsw==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbkJkVnBlNm1tSTZGTDBi
            WjVWS0IyZ0hIRndWbXVZOGt3T3crb1RzY25VCmpDeEk4R28rUjNRYnhaSUZCT09P
            TUlvbURpazVWMlJwdlJST0xjNWlRTU0KLS0tIHcyVFdQRXQ3WnBCL1R3bkY3ekc2
            SUp4K0ZRVWNtYkFlNGVETW1abnZqejgKPOtmCur1Wbbf1+4P3nCKfvdOiDTqAkPs
            01XkOKH5Z3SUfcFpm+k1gPEneFlXRAEcA4wOPuSzgN8hcfu9zsMGcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMDRmbzl5VUZrZGw2Z3NN
            a1NpNkRuSFlicDkyaEkxSldibEQyVnR0V24wCkRoMDlGY2RQU1EycjZEVktDQUtn
            SnhsQmZHTk1KYUlETi83cDBBcHB0ckEKLS0tIElSSDlvKzRuR1dzeDUvWCtmc0xp
            aTE3dldnVmp1WjFmR0FhUlVUYWFIaTAKHzCZC57ROvA7dSzcfHVrGp9p4dSZv7zQ
            QQq2Vo1sNhpXdaee3Cf+TVSM3BNoTj12YjxzrS97HnZ6EmCNd4FO0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQy9ISFNEaFl5RXRpbkYv
            SXl5bGJEdXVDYkRYWk4rZGFGNCtwRFpKV3djCjUxTnFONUovQWc3VlpoMFdNR3lu
            a3RjNS90Ti9mUXNwRW1FSTdZa0didncKLS0tIFNzT2hENjZrUCt4Q1AyRm5yRlpT
            QWJkR291UnRXVkxxMDQwditQeVIrbTQK6jZdtA+CI7pRwUjKkuZspNNmJKmfJsGO
            tAJbhqwuADCvrZ8bUT+8R4zHZA8S7brqpCcGeOrGwWMh8p9LucdVWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T14:31:05Z"
    mac: ENC[AES256_GCM,data:0FtdQJ7oBOuXzD3iLUxZhkk8Wrl+/e6YeMQpwZRLKhACvUsATvN/DaBoqohhICmFMOPWJpT3+RfK4OrF7fzppUYivwBNWMLBAUOsFTep39OKuipaQdPfYA6INZOOr9lHDuiSfrQzq41aM8z+Rm8l+AEi2xvuizBH5lOf86s+z+Q=,iv:ucSa+TlUKK5bvWfj8IxvDeU+LPLpMlzEIOxIVjnMuKk=,tag:37/8OSDsqchK4gkBTlGBJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
