apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:EMqQUTKjPQonGcRE1g0waaotd1ZKJJpRgHDDRIF2PEZfrg/vpaeyk8mue2/Co120T/MIvF1VYnICmuw8YlolYnvTrrGn3R8zXZPaoICPrntD5Ab8Hj/13RHcjPPz+BXO6oBZHtuYnAQ3minnhVyxDY5M/J3yjJq8sZA08otEvrrOUAfh+OSqsu88k1nPHcODcuiWDqAgSzZ70CuY8q7IejcJbKh6JHGT5dt0RdBjelIl8/Ba2RCe0V+5feTeCRZPMOHS82uh3E74B5vhQOS2nql75dbWVEtVtBBfsPKOzvYk3IHCbDzoUy0ArYGrJFuEQFqP+RHd4yT9Reqe9lWrdh1LVXa82+ASS3El1F/AuIfdZYlCUkTh8HB1Jw9ZDV7W+8Uq2c2hbK+JlnhYLl4yltYEukzOduUWHBkgU1f+4kCEkUboX0LVrsOg7VJUJHsfsXVh7PLS8TdPVvz8q2JM0CCBhm2iOcEcMWPPOClTnVVIhzo87oRLQZxBdXYB59rqL0UlfG9l/qvA26ObWXC4L3XBrGaITAR075FXAMmxjCWdS1Q1c5WEtHzNdVOQLMvdeoIwGuZUHj6otZs0of6vWxszFrl4k/umrFY/hUNsEQka/he0fTG6EE4r0xIRiffCJYMzP1IGP+LdOorkHbvRMswwvC0oWUsgtzruMrvh8FLEpleLFzE+FW8yZiWknjYwXkfsfLUcCdCBaKSLaCPTWmS5S20QL+Cg7Or2AMULyJKDT1ikSSgpxEY9tpokFCAR3T3GKMLmkHRCU5YwMjqYH3PFaAE3hfhKH4JxtowpJHUm0YuyXNWspM4TUPPOcLPtXCZJ5FObrKDoeBT1Ldd2JDOLwjXvRUcXp0tMnM2QqQENIsm8JNM2Za/P/QH8LlKOlj/ci9CchhtQilBvvUVFEbio/7nAthr/k81d3yrxYMJm/jHaRtgtLkd/P54FssbU5UZQ33/XizqiKj2yM8fkyMkwV2x0DMrHW4nfyrQ/wY0b34KuLeEvWd5cuxIy4/eCWNKRv0k14oEI86Ax27FupwD8JyHyZFKjh6zUHfVCSzmaALwnn1TWp0iI2ZqYY1YT8rn7ZrCPJR8OCJRQiRxkwCzHMhsRpVDhCHPC5mRI8eiYiRybCohaFnYh76YZ2Ejy3IfOKW21E2KQQHVcjZqe9+uX/VcIrASU5vZVR8y6DEA3yP2/1LR9TNgivyMsxSw+/8+tDYQ3k6jAf0sde+pEoJ+w5Z/xx9tjZcObiduogsAvPb8nD5a0ckAdKI2sjzN3tOxl3gh8bZGBnKSvuklJ9+RHuek5E3pfvgnCL5Rdb/QBY1mb0RGCEmTW7GsFSpxZNCuygHJBo1n698Rm4LljCBtqWGSHRn2lvKUv7fglWsyosysWwOUu+xB20uPOsTUwCCxo7TZLHGESHcqwjBmIJgrA51gsXlwKLQMt57Ci6C/zeuoF2VmlVnISHQeidXqjRuwR+UOv9M32DLkhipBoAvGC6yMfZ29oXH/e1UyAWxEQI7akM+iANbGSDLSB3Xy17bEhCKyW8HDqGWYwAxre3kSKERtK2VSGnkWCUgCYZEFC6AQ/dUB/X3mcTs7RXeAP2MHDfemfNOJzn6kt3L/y4wGTTi0jorTznSVZAsVuzF8jpgY0mIwN8F3lROPOJvSGEqNVZHRAYMhFZW2VNUvxI8CEYCXuJIo8TcwGvT06WAbBV7gvgLlQ9QN10SU7G7GGCp3EiQ9hxwr/gzBZkM+66uQMdtko6NEv0KL/ak40R69JIgmrWQp1g9qZzV5Rvkkefx7ngs7FbDwTcL4P8+XtpxXYNtAePVFSaBNxfkN4KktP6XoHWvLnLxXl4kCZBJPqoVUONlxnRQgWz7NS164=,iv:3X1va9Ea7xvh/BxGGauQnxMaYKM8OfUrUq6TVZsPNzY=,tag:mk0R47anA01vtuXidU48ug==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSFI2eVI5WWJwK1lDUnRK
            R1FzTy9saDVzVlZrRnk0RzRDUm1mcHhtMkFvCnFNc2Z6UmtaTS9ENi9UWkJIRG0r
            Z05xd2FYcFZ3bFZzOGxyTDU0QmpMOHMKLS0tIHFyZjdqS1pINEIxTEhvRms2Z05s
            YWk5Wk5XU3JXQlJ0YmhOU1UxUVViVFkKlpR9X3ylVz5DVtTtiQtu21OJcim3neUP
            Av9obdkfc5B7nAxCIsk1i12wGNf/D2ZG/IfK6SWUqZv4jMZtvV6WjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZHJ0TG44RHl3YWkyODF2
            dHZOdkNiRmNNQWtCNXo1Yy93S2d1bGRrSkVjCktyTjA0OEVyY3dnU0xmTnBzcTdM
            NFFweWs2bVM1WXpkeUxNUTA4ZFdtQjAKLS0tIGY3c3VyTnlMREd3ck9xTExYclhV
            RFBHSlBFWUhMTEl3ZWxyekd2Q2l3dmcKcB/fKbladjmt6yLG3VgXNEy7DasMmsMG
            ci1JcCqeMcSopkk8UST4LQMKVVB8bDFwvLVO4+KnjGnU563sPW8f0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWmlzTjZ3Q1V0YmNuZlQw
            SkFaK1hRZEUydFJPemsxS2pubklYR0hURkZRCitpL0IyRlJOcWRuMUo5S2RDSCtm
            czMrZzcrUE5XeEhvajJ0d1NhSllsSzAKLS0tIFlIeFhOanJWU0RuRlVEL0treUxC
            ZElVdEErRGxESGNsTkZtVEUxNXdaWUEKJZ5DBS698C1phWZ5QmiockZ0+PnckLEU
            2YH0pcrVYfy8/5/AerTEhJeSjapVzwzOkm7zfeWTk9ltlPCdhxMpqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T20:23:02Z"
    mac: ENC[AES256_GCM,data:hRzr1li/WQb3HecITb4Xs/ojGBOnq/vBedcj3tn6JKcF25XCKzzVc2jwFO7KJSN4ibCZoeFndTJ84nIEpM4E21lJA+bWcXyUP5eQsXz36wv0ERDThUpHCMu9GlSIudRljog54sEyzZBk/uosVVNK4EWFT/sNlzcwNzkV/rAzMzM=,iv:MkRPs/QyQIxl1mUIYNUyXaV0NlE10sMglShHvUr+yVc=,tag:VT0nGgxqvm4YqjUlq8kRnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
