apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:V59GslaYWA2Jyg+B9xz98Hw7l7s98eIefdtfUAVGSt6syb0sRNVhxPQ0pTRC5yjgtw/xkKpm3ppl0G5DLjM3rvJ0W00i7q5eZB9RU+TaqHih8jvc1BHTqJt9UNWxa9lL1PVXh4/0LPNrwBH6hwZWE+n+MBCkBhmNkRTtb9bHm6qR8I6RVBqrf8WRR+7OBjKRWEKrqIGG5n/sRYoZ8MCXhgShPR7zVfqvYEw4qv+cr8JDlCtomRT/hpjVryX4dbnW0QPlEtksYor1z6HeYyqoq1B8rwsx6AHu3mgjTSRGcno60Yv7mwgS0+pUTQ/cF2aKJRdO/tG9i6SUVsOxzPKhNFT9fRRn48T9eAx5rDAsDR556T1poIjJlhke7SMhg6ACJmRQCkz/O9uzOhJhTzrWKe3nXNH78Ug+8pPBSKNRoPFIK0QJvf45fZl5vI3DPdKHaOWU9EPIX5enaqPA4ApoQgZfLF5O32DvT7/einScDFGv50lSIoi2s1iSWwF9lwhCjBROKc2Y5jYwit2GJAzKqL5f24zTfJkXX6M8jxnys4e4JcAGZ07/y+id4ZsavMfAQoPX4xcT7frk1iXMaV2rEw5bgTXbcjtfyV77Nppgloggkph8gqVo6W4H3A2AlC13j/icdw9pHbNzzfJL88pJUk2dy6bwHpvlCuexJuRZiec5nELryh+hWcxgjUCq4aP57PNm6i/dykRSIpfR7JTPQ4p6Ko1EJR/y1p7oGd4++m76SeefIcHHXKuI9kUEBIq1B3jr2/AGbDIryXE/rPy+qc3Rx9JwaGssZcydakb5sOlUO2f3l+MEOiYr+ik2PrueWPG8sNDD8vcUmDcInQR4PFJCg3ZZ/Ipx9wCJ3up3gPjkQQSK0YpD67qlF4Yd+fuWFKofL9q+iJJXDUXWy2megzERNBEnY27tNj8QOowTUP/SsnLXj8wIp2ILql5fzrJrtYk9fyyLzYm8pgHGjSUMQl+WpjkRAROXMHdrOIgS+sLvn4GVxexVn1/MVlZRrQo7O9dr8jZA0Z75eacu/lQ7cNOXC+3OkLGzM9wG8mBTQN0hoyeWscKLzLaaNbKHwoEqaef18qEOFslLwQaP5tx6YjP75rWgZ4/3hCfVVYYyxjI/WK7PGJ5awQR2/ZUice/H9MSZF5+60LemtlaVmtNreJG1R7uhT4tqyj78dH/24I6W6KWO4U7I5kgSYi7gPNeeeGRkLTdrZ1Vjat292U8YfZqLTtIblwIkPhvjIaKVazDcUXVyKpVM/KTucHlHHkxNWPIrRR/fJxDZJbhBcOdZGAbVrJs3Oq/CnLLhgaDR650DHMYzAZkgxWCZr+CmZCu738nzrW7w7XGP/4noudvCw7l5DniQX8uW3P+gBvHtJuFeYAEoO4JkIjycAkAU3qifpWqF8QMQDU/C0+F293PSDx7oTguKA1fYElycjPhy4nm38eyNdPNi/k4vuVHV32h3jLp4nnYkn0zHlJBWJLChFFlnWLGD5/ClL++0eP0Hnp6kACjDDyvZQ+bsyWrP0OdK+/pPdwOQ42trCumE2X3NAFJRdwzkXWXh+S5+GFem5+q9lKac1wxR7AWHnRkfXpQdn1mCIkutQ7051ZuVynxs+tKeEs/LFR19q99FHfRyeQ1n6vf07vR6n41kS+Q4njvJuHsTmKLYg5I0k6p6jhG7m9s6IHroaudx/Jr3qc7AKRZjTHTsf3G9zivgr+JBCe2HAC321/Qzd+C7PlPgdir4h+rz/1u/7IYUi8oPMCyNaE8XpDly4Gl9k+3g3AxbX26Rwx+JijsPKD6Js42IUDAVdQZ8q/BXz/iV5m7oUe64hLBlYyjq/qW6ABsQS6/bRWhHbgB2LfMg/Es9ZWyI7Lgo2roBqFFEBvVANkqY9DBBOxcMCsAGZFxqJ1kC8vA1+zCyY8JAoVDIjKUFVq9WafVisL19iq2v+8qUoDQE8DxNUUmYe1VQuIfxjVSWjnbXGjcJjjTorUVl9rUogA0DsOCmsbAisnGtRUAbIRuYQxrhGYoVc3ospE6TJkmR0VvO4OEwuZs67rosVUSXAkbZjAF7diN/0oA8BwVNLeiRZh//9BMaJ9dYCtoe1rVGlDPJyJjyTYPe8oVTGnsUoJmdIFyP7K+z1KgOvfmtHp8+df9AW+VVWkmHoi3pAfgNFw93catMk7jrAUgnLuUTTE44tdvmhck9lXuWypRMO9GWseeYErzaYVHCJQTk32+H8pna6Qkpfsq6edCicJ8fPU7Crs/JzmWtkorEdXOLeiSXtmhui9eMuukQxk3d2umV7VVMrnOm7fePLH3cqKaoUXyD4ZJ1+GtE1ZV4SopwDNcDdtOmmw/lKHhLPg3revpHrqQOEH1raZ7vToWU0yoGAlkmswPwJWtlioms/ZuDQquA4rOg4F/5W9A4/tG+M3z56aN4MCrImZcLIRLgTLOwBewQGoxQbXkdjmMLULjTe/UpNEU1FVc8HZyVi74SJW0ze+9rM94=,iv:5s7/UtreP7KR3EFfabwGRGEKua+2jgS2brV3vnN63Kk=,tag:vwXkAXgepObMNU/OIpb+3g==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRkU4ZUdRWGEzdzBjNU1D
            QzRMMFVlaVJPREd3RFZUeWNKRFVCY1lOKzA4CmE1ZGlrWVhQNCswcXFQbTNHMURw
            ZitYMTI3UnlRRGxkVHB5SDI3N1VadE0KLS0tIHVGZ201YzZsOStNQWRoQmJjV1NZ
            MUwzZitWSStUaU1hRXFDUUkwMG44cFkKZeExxTnBXF2W2K+GRIHj1Q6PFQ+Lrzw8
            qqRZXlMBchSSVIkFO4U6wkurAUQB5nzFz5iu+CMvjwKFaDkZ2C+ftg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTjR5OWFYeTdYanRYck8w
            OU0zMTRxTmJEaWQ2YSszSG03Y0JXRGx3SnlBCnNycmtZdXFVVDk0YkRscFhueWpE
            eDk0eGQyak1rZVFuL05oRWZUU0ExdjAKLS0tIFdlMUN4bVdoWkRzM0QrKzlmUTBD
            WmVKWkg5dnlDUGFjQWxzeXdCZGJGZEkKvxJvh7aY9mg2WnPOL+mv8kt4dl2hipiu
            ddDlJHWkUW4jtqCBjeDC8Zm5gl8hhnJ+dhWA6vG0HOsKZ6BOC2ELhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSU4xVnlXZnU5enBaNzQr
            N3FDWVdKNFpNMU0xS2VFci9pZEdHWTZPL25ZCmY3UTBvTUlGMXVGcDlxekRsTWdX
            NWhNeEZYQUV3TmZSMC9Cd3NXS0UrZU0KLS0tIGtrTlp0MUIxVkkxbFRoTnIwbExu
            NXh1dmdpK2xjbmcxMEtxUWNaMjdpVDgKVkgEn8QN13bBX5ICTNKvmINEiWSD5D2L
            iTewxja5rrxPytGtIW5wd51d3YmFxThi+mwGcUm7obkFct0xhapwGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-23T18:24:14Z"
    mac: ENC[AES256_GCM,data:6An5Ubfg+ZQZwQCef0AQOQXM3CkHfRCDwZMG1zaNA8AOmCZxSN5f5K8bJecYNQ5is6BdCBWbr2sFoAnkwpEF4a3rsXo9Lr2RBfor+NHwA70lDj9+ystPjnYaHdyY/rdU6bE/pc3hngQIceracpfKzLFxVeTMQfh3jizJx7AbG+Q=,iv:gEKQl3xx6/831DfEbvQlYQ/TgdL6noNiIkmpmNJmzbs=,tag:huP3ZNFBVX6yIQT6TuEVQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
