apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:yNCdqjHRf4a1PmHcdwRHSb0t+sAQvJvNw1R6CCSedbwem/lktd26q0M2W9edTLzRSKsLnJKeFqUctrpY01uC44aVZuku1wINFlw5GR/Zp8DNUC8fq0Hb4OJ6Gs0xtDnX1R0Nm1vMxjddUcmhhHHaFKMjMTVL9xDsj7ij0fvKpkg5ifoR+l4ZPMQ4vXMrVhLzwvx3xC5of6oseVKNGg01kbY1H2y2wiKLVRa180cseBaggy73KXUHq4FpHBLFni9aLeWPTD6Ya7SAzd8lCfABZlNffs/LPQofdh7QnLpMXf7qAtR+P9scTc8vYrZ6r04xBkrxQYmR9iIE9hiGy40+SNA2c+BdxTEMzDFq5fgK3PfDbijK0xaCHNJfD72qvE1+8pyd4LQ4glBTkKJFIPAEnvCM7IxHAqore7D1l4BJzCrAIvPETfQpgh695ot3nWSdiXWZdTtCWgJeCKPTDZud4Gc1vXiB7pddQ/gmUUmqNcwW5fumA0Sq5J94Ys4mSFZwOBwFOW54LmBur3YYAvQJpBUoVLRNUQDZZsQLKxKcO7BFkXlgCXsGQFk9ob+aQ6D+UIxg3svnd98K5UAJC6O0iyWgKRW1fi+emtuS9JlTdJGNs9K+0qV/mdpTdabhEx/tUVEnFarqpTDRr3zxcYaS1Dq1KZouOJWSOg8sjegNtxYJnmxDNXzL4i7Ow+mqxnXG6RtZlFFY+u68Md8LgG3PO3fRfccRESLmYHqCY/y7dloQG0CsalAQTNQQu9jY/fMpW3z1jrusRsxCfnVJnYiUuinjgMiFqMUChbHckGSMSpsnpB2nhs/ttnvFSTkJZSoJC/x0HotLzBq83zkEy7wm1YDHJ/2b5yG3lVRBdK28unRa9bCbOD8S1UjuritBrDhdstcLzUPn5Ff6ru2XsZmec0bosvc5Y85X5MmGUQhEgHPR7aourrTr0s/7KzR5gKv2l0Ib5MvaBDOTWzDMhr6pgFC14PAwlYddBueeAJN4lrHoZ57Gr75HS0dDct2eOC8FNKN4lmFixYqIrJiZvByXK6ulpcaBVPmv7ItKgF0b01cEjvZubFED/FfBZh+whD6quwqj17I+MyjnFFBl1kl/9IC0NJQknAyZ5++BqQhJTsVxXI08CoklkcLecdgaeiiQ9WNDvJmsqYwndG0BWB3kceRcS+zaRg51ME9+a2zMYI8mLrdy8pw2xJGwyfcoL8FmCcAhIyLc3YZHGTfNbWmGr3KNyZkC4gORRS0cVWIwQHYW4Gv9nKSc6arCoXzFjmzGkTnuLCvGeSqbDhxcq0BX47x2uwdgZBucckbgdeBGUuzOjw7eM3ayeVxFQijxlE7g7g7q7Ln0CxQxpWtR0gb3DJ27OO5p1j1MJef+sT2esogRHoQan1N0VOFq3rvR7kEv5pBVqzGc/KMFsPMGTk7OlcWZe/yPAlqGvtMC8FUy1P8M1NkqS00Wv/STNrtcCchIdNmfXxO3XPfX5jQyF/4nNVeTgHltRK0qPPGBUVKFpot9Zw5jrcCxsbO4yxmpb5+rtZEpEZBag2Ks/CxH8R5O06966/UJGqVVchY+0rkg+cXbcOz4oUTOfCwfSK17Fe5beGiTVCYcJGlgrYxkZNZVrJ03AF2YXBGjdLgyhSy6yORVwvOXSRbW842evMRIaNW+t1p71WF1ijLJoy8n9GqVTM1K4x+L4gkMVIlUa5ZtkPmC7s7PH/7bLlY+1A4zKOnrjv30zrWwAhbVF0RL6UJ4ZY7Dl4ZFEzzExdq5dlXHmJ9jZd84uzK7ZAZp24Oc8FuBFtdRQOBMtPzuO2yKaC9HvmwrKmAaoynwXQoVoeGpCGRW0/yMWtX5JxzNaLwFQ03rPuaoeV/wY96IwfbfoP8aCt4Vu0+YyMUQo6bcptagBBQOEdXiF11AWnRYEXKjx6bSmEVtKTM6p4Ot1D+FWm0eCqWudm1l6dhUTW0dWAY67sP6QbQOAVPzk3g=,iv:yowlf06GrdFJHtKC8JYNDOasKhn/o1XidHkKmw7g8hU=,tag:c6QQAsFy2iz+rgjfg09Xbg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OU1oY2tBR3RTZmYvWjdE
            eFAvUWhITmUrQUU3VGR2SG5haUFUUmZmYzJnCmFuK3F1SnZ2aVNDd0tsYmh1Q2tp
            QXp4RStHTFRMZ1N4Vk1aODdNTUs0azgKLS0tIHd2akZRUElWQlY3OHFvdkJ3TFFT
            ekRLRlhwTEJqdWdFQjFudlc1UEtQeFUKoDrN0SmpO5KFqHFm3PQ7DU6swZPPLkPt
            n176/6+jxC56bnXoVoUlsKHTFMe6h4z5nkZA6+4F1iPNt1ezL2kUfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMjBxWDk4elhYNEIwUXNm
            blFXZVBuRVJpSCtPUGxac1JiNW1iTzdJeEhZCm9sMEJhNEFReTlVUWhWQS9Obi9L
            aHRSbVd0UVhUT1lKQTMyZUtIR1NwTzAKLS0tIG1vWVV2RmNTMDdxQnVGUGhLS0t5
            YXBmVjh1Ukl4UXBBNW5MVi8xK3pwbW8K+90Fu63b2cPP5DqQVK2v/rIgi2bsNkgt
            OrtllRFz69Kja+TgP1Kmuegk88TjDLh5tuinOUPMuoHWiEo+r1Euyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJK0tQbFlpWSsvN1BocXhj
            UGg2Tm9ZaXhTSFUwOUlIbUMyTWZRY1BXeEVZCmhrK0JtQjVac1J1TVVUSHFMKzIz
            NXRibzdwd2Zybm4yQUJlaFFJNGxsYXcKLS0tIFpnR3VEblltaEEvZFBWSnppWEt1
            SVQ5QjZGUndnOElyLzdWUWpvMzFWVTAKrime8E/z7puIphHDYxkDWt2tcmEDloVj
            f1EBnUxvAHp68TxsFj6H5iwLPWRyZ5dxDA4ZI+vpgSfat9fsbwzOYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T15:02:24Z"
    mac: ENC[AES256_GCM,data:+B74rLTIKbD5u1IUX5crEU4Wd5xTi+CW04uH2yBZawxXlsIFePiILlepHa2ucbSLhX1nwZqQp5vt2ck7IKE9t8Dtje8zCR8V92xBzZxjB11nxguQiO3QaxbBGAcOGTosqncHshzigdmcO3zXM2EVaARhhs3ulwE7Ex+ppWEQqnQ=,iv:kSBbx6zBxek5qbRwTCWmDNVPNNdpEsgelUh7+vLl2W4=,tag:0D0Srid5+o/MZzf6mkTxJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
