apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:7L9L6f5/4elP/mbL8WoirNcgDhR7XnfbtNxSvijQuJQOMOfpGyWZKmG168dOTMO/nr1nVahNdQ6rUIia/23dFAy1dQ3RPDJRaZrpVGoCsTaYzj0miNVm6IApivNasVUQ3qFPuAnD3abCD1OMcqhOK3hpo/x5u+9P30MzRBFP0EbAm4x6xnM6qwhWm8AeXalSgnKwS5MzuGXoq/Ha5ZAP6fIJa9gLzNA7rfNWj8nKswPC9yiCwa9MnlGVz5feVjOU+jSMx8t0IqB315cuOnI1/Rz6Vm50B2TlbYIlhbgdp/ftORD4xlrkKM81oEy+/loBFQp0s9OmhU+ctBSHiEJUIXwWmbMAIm75wW5l1ucjSOSH6Q7cjj5sVieuXCzm1JIMBQMk/tTRCw5znr+dfcYPhNy4GgO5Za1y+p8CuExdDQngmD/9SAwZZDNRWypSKoVCY8p3vuFTvYBxP6mKiW7qZ3YFbEetxFgApkDN7Lodn0uG3uMWGfFjaPk+wIUHIah3lSTnNxra21whiiFhz5FGwio03hkPq1aTBTvjngtMyYS/WeW2bqi1YdBLqLpxxdwA+AvKSwMytpIjoP51P4KsjxKJrzdMbz1WoCNyZ75ujJDoyhF8zbMmcmgaB1vWxMvFtAR3k2//VteCfio68J9P5xRuBsscdjnlGnBbT3lLfQciKPDto3o5NDA9zcBrbeXpHnfUSzl4sMXgUW1RMdHASaxcNhR2Mws0OjGVEsf18lYy/PO/CmIO+csTR+3xzw0K1UEiVMwfKvADQ2NFl746y3g69PFALiMfmjiAzKYN9cs8ec1/q22/Og8Hjow0ZxCAm3Y8lQYdNDFUAOcnMRj83fSAljYaGN0xwbTiUnY9c+f6N+XFtutqZmVc2mK1cmbd+O7emCqiXpxhOHm7+QnnoAQM3tsw8wYPirexLyWwODG8i2YQoioVw5mXOJ85f4r+yObzs4nNmaGUknshksDSim+zBI5Gk22r8O/mT8FgXLbiHtEs5VEQTQw5JtI8R78HxRIezmlkLuK+IehxuaHJOTEgWV0BDgSSjjxJKFFujzIHjKeQiaXM5tBimg1m7TKEtL4M5kqCdMewcssjV6ej8JeM3OB3e5Ba8HvVkfKakdb+YqdXo+r8xH/PDAufHc/JmOXyGjccm8ApT16cYtaTf5xOvg9yBdYArS6405MEbpQ3mWHahz77yW39UbuPUQk5oJupWAu++2pL73n4ZXX1OL9EKNtPIxMcpa4WvcOoZXoPLqun/AT/gSMizO95Ej5IVyY69Vq3VDS3CVPmNif4tdluTysnjEcFPLT0iE6mILbOeMl8iJ86XCD7dEgzzE2I/P7+eAd7S+YaxXhq0eCSHGZDfWJQcu7V8B8BJQ5Mc/qB/wR+NC5Ci4ByQjWkoVAdawrMMKKjmyd0kluODQgJWv27gIbT5bKM7KdgOxfuigm6u4J4UMZrEFOnV6ak7fDX/39ZNPkxIZ+XqP6eh/O5JZ925n4ajgEcAeGhqWsOw0RlPNddqVvpaSEZxYXyBLd6vq6eTNuBuh4oVNNrwYNvxq1VST9Aj1JOb2VCrwGmIXf5qMHgInjd5GJTYGxxUm2q4scauIw93GNRt7Ajm3eG27EUCiU2EfFkKPhQwiRr9UN6BElin9PQ54QpdCkMx43j/wFG9M+CUh8LvsE3V42Nt8SC7dPIUrHj5wvrJFuTOvcu32BHZTK42Cr29lZsuHdQ+U82/cbzqi05X495D5DLhrAW+vBRfss0uFHxhzYZzndX7zzDcAO5kaFb6C+PAwWmeYwgFl4/mkO83eoaqeRWp0w3AXQnHIXAaiNQWlSmtI4Ya+2FGAcIrWfyvpwEfUv97MYr0ZnNKehlyTl5NcQQTx9khiE9OzGx+zsVj64BXvX1bvewLPTG74SzGP2ncENkePIJ+7r2tW903t7yDBjVb3Z/n6m+nlUhiBdqjTGU5f7dBad3vQsUcGGjF7nHbk3/BQvmqOs1gS7n7Drn/7FQP/0UycfHEA1eL2IE+9oDNqnThA==,iv:r/J9iPwv39WeypgYRUEh/ioiIofs0zFFsEecOJ/umL4=,tag:WiH1oNLqCWbIG1x/Vi86HQ==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TnE1aWFlckFYNWFaTXU2
            NlVwUDdCcWR3R3dpTmFMcXkvNXZ3cWx1NER3CnJuMUwwenU5cEVvU0hxTXJPRkc1
            cGZmdjFCS2ZIeGxUeDllN3gwcWZXcUUKLS0tIHJyWUU5eFdwNnJVWnR1S1pMcHRl
            WEwvSFhzWHh4cGttSnUyM3NvZG92bkkK8KkOdX2A1I56M2sj6hvymJPv7zGnhvyL
            l/YOz+Jq5Q1wXNiKmXdf0c1mWnQzPploTY9+4rXmUVvxkA5BS/V9UQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSek15Ty9WMXZUdlQwdTZ4
            V2EvNXBEWG12TTA5R2JDM3FWTFJrK0ZOYzNBCnRjTlBWWDUvdnAyRkltSm1SUmpC
            aTQraDdKUmw1RzZOVWRFVUdZalZaNkkKLS0tIFNlK3VlcldjRTlVQkZXbFovaHhi
            SWEwTkJVc1dhcjkwSXFndDU0VVIyUk0KJY+BEXyrAQHrxm+SA5H0VCaRI824s8P6
            GsVTQ7OafEvHKSwxy9JYIbFsknuWXxO03ke7DMJiERwLAW2QV6Y3RA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MWp2a0s5KzRldTIyWFpY
            ZUFjZkZRMExmYjFodmVLUC9ucERJRVpiblUwCnVZc3VuT2xHMzBzWVRPZi9zcHZ1
            c3BCQktodW0wbVorOWtmUU81WUxEZE0KLS0tIEtaLzliSmFBNWN3TkxtN0JIMEFH
            R0dOWENUanByQm5ZdkZ1RHNOQjVyMGsKgJszOjg2RTCDYOnmQinWa74OP8F7xrly
            0hySfzOBRYB8fWNhAoBO5HCTcLw7S8c143qJRTgtX13laHrmwN5B+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T00:27:13Z"
    mac: ENC[AES256_GCM,data:GbecvdaY75svQW4FAm3opbr+9Z4a2LxpA7l79bq5rzLItCEQDqiHMnmWLjZ1WWf8Kp/NDTejhei2aF2Ic7InxGnHmANCbKDKN8mk/ckVxbAGvuvNr0FdP5mWiv96LVVhX6iJ4xSoEdAv7sVxQ25k6B85fuO9PvWxa18yP1zaYXg=,iv:Stae5W4R1/mKQIE8Y3cZ6Eqy8zQZkWWnzmRkemlm50E=,tag:DoBObXGaeQ/Fjl+jGbqyhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
