apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:GcG0Ma+XE6YkM8Rp0gScKiNTGeUqedEtgWm1MjwEsndmp/JfGT1jrVkZ5xRFYDb8Gp5wJoYblpdT5ylFI8zEM7K51DSwPtsjBOwWq2Xcz9dcsZTGiyOUL3thNPLjAd/JmtKCIiWsktEzs3mOgAdeOxQ/CEpLLX0GPmr2rMN/r0lxWYcRA5TUkswCc482kw4KjCRLJYIVKoZKtgrM5HAb+GqXTQ94DIhR4iNnPEi56D+SJ3xS86ytfrqTMW+NOsaXqCrmKLkEku3lZTCwBavu7HmxWoHhvgJAWbKY9UOmkGQRNQ22qU0ROd20xLuuDoteQruMm673ECSSXH8Wpx3hUO42elaBYsQfbbkF6lTU/ROzI96CywnAJZ32/czsfWe9uCMpjrUcGtzBz4Lk70ODCzfDw1E68/8S5S+dT2Q7mh8gD8kb2IMmi5p6G1KlSWbANGJ3XlVmZvvn3vO+ZFEnXKFVzcqQwXK1YGozBLrwFGY01U1nGJXbVfjyi+/rE/+jstNtNg0tkx9z9OoxCgR5RM5bJLayGv+Z/4W06tiOlmC6I0n4Q59JY6xuxEhJh+472idrJbomCI+HkIV8fMKdFWZFFE5PTmMjrmdtFY2lqvGGQWQmbckMajZtNOL8HFOXjwKrxxgP61sQCDB8kXN/3fqvRmCAm5O6UesvryYyffEnP7Xi4ct31kKfQo2aFokqMaWaVo4V+AayVoaIUgOtgX7Z/E6MfFcAQGLPNKb2FcczV4x+GMjjy05i1xpx3+A9sBzE6BHcoQLthvCRjGmfkVdfP9YMVuS9EE0loDv1IemHfh9P5UcrJ6LqWpcPPVpO52MWW6wWL8r3ipaeexeLu7UlEsnvQwuyqknioUq3dfrHQZOKh8PrX1t+omXO8XQJYvLCY6x1f2E++TkaoFMoq1c2VreRPovyEdXFHDu4KC+Nza7RawKH60Nhd+7yX2oG6J7FFm90cbUuId6Zua0zIuvgUJlSqc7ivoHNCxlYjnZGDeyYxxEArvmK4J9PovEJj+rL+1q3NAOvxdbBSj1aQeylIpfrkd7DsMzRtYrIg6DUPeNhoBP8h284b+b8+jtccSiXBRzgAmz2BD02aoYGMuOKDqHUDCAjM0WQQ84Y1wQeSdIIlgKOITY17m/zRZSF2hNBIABNWAQ0ik/cc66TPO5rbPHxYcp4a1wN+2ksMTI9ocQnb8HvV624BqTqwoOmatdJgTrKM/j7EmwfIYFCcNMjI5hbgkHglzSCS36rboOBQPDT1ZX+GMIS1G/ky/nYidXXA2WQKSS1onjmnNJS4RQhFhKu8Q/8YXl53TW1b//3vkp09ysLElLBQY5siMCOjdxQALfImCr5QIWiqNgEyBZZ0TWN6uA2S4svyqnIX0lU5GV03QVHMfWm7Jvh80lFulqeXe++PWdEkRqzHkD2DIeLaahzK5sKBvVATpddGrkVBGVZSaEjRqEs96HBAy0TgpOyPSNY+IzmTaD10nnLhfQ7R8VAm1VT0xbIIRNXYMBnKz4bKEW78lW5hMaakCjkt+2mBObhWYqqy8De4NKTQr/qWh6yAzzCa9TkHZ6ynWKToeelNF+hjo1VnEmCy2J700pcz4hJKOJH/b+zDM5BIV8zmdQZRD5KcHdWYzM4lzwsbgTTNaWU3pDIzcDW66KxBJBx06q79kK7kbt1m2GliDhRejV/3bEnkX63h/ZpALBdARIvA7S5rNxVtO+j2qya/K6z7dn7Xbr+T+UroGySXhV0obYpDiu5TwBp8Tapt6z3IIZ2lcHvkWsC/JWbIp1AmGFFYWmw58YOtSAC3lhp8rcwwqUiMINJK/wsAp8EGzPgRJ7Wvti05wTIzEEk3sWYtUedUisCmDQBwK8fEsxdwOt7XLsJgJXL49twvlmcuvvkk+Yy01BeWjv5XptHbJSjow0ipV6NL3LXVdGWYXOcumXYJbbc+W9bgsO9nNtJsXb64GUNW7UDATmYQepkRY8IvN/D/CX0pNO+0CXgxL14wLl9xV3LSyXYORNPJMLxPKNHpT+FRMARVFHt5RdEmIMchJ7HbRPnrhjRgr+c/vSUwDhN4fERttjN3XIT6TbREj/R27JpnMM3Hm50s7Lsl4WdWSMscdFfGV/K/mApMrg8LAJvYCDzLby9nU3G58TYJthUy4SZd7rXDc2VfCwoZAbzIl+n3EUgGQTt3o6QjTasS4aInSe1rWpl8FNVNkhaXYOvPiB5MKtOQ5SImgMtoPCrkuKIypItECq8UgnkIMxdIJTqfFcIXp3+LJMenM2olBvMfxDNfeiXLn1c2zkEFMXiWOuMCisPduskA1ixBQq7tz6YGnVt3bC4Xsh8/N6NzzmR9WwSwEcQ4SJbLKbYCGiRQh6sWMfHNVkkF6xyWXKklYh3HN/4kXO2LYlm0OniiScW5Zd/uRWK3uB+CDDuKRuNXEG9Zofg9YtRMi45GxzTsCP1QerYTxCVpQomQAYU01fkISH39XUkfQPcWHdcvf1sNeFlSYw5BL9LXWpAu/x0pBjeddXgbNtVYhoS+1cjGcj+ItDaHQFwNXIWskmnYWFkGtz0Or9YKU2Sx/19CeFcHBdlnzT005wIkVDujARxy20qnNQoUhc=,iv:dtTeikhIGmmY4Ld3rJFQmYquGdikBcUWuQw4X28+r1Q=,tag:EZpe6pUi6kWgbBTo4ZWDSQ==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RGltR0p3ZG1yM1pCRWRU
            emhlQ3MzcGNYa2JSekNBZkNxTWZHVHowUm5zClJZcUFBend5aXJpZ1J6U25GbS80
            Z0ZUb2YvZEt5UGd3c3hKb0xucnhpNDQKLS0tIHJSMjZKMTkrR2xLWEkxbXZUM2V6
            dlJLN0dkMmdqNHkydmNyRzJwZER5dXcK9nkdFzg9FftaoU59LDsEPo+Tkshzjmfn
            geUtwU0onxkQ9bqfJO9pnzbZCYIYOWXdVa+7H4+jdf/5ccN21eIkPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZGdiN0N5eTYyT0k4SmVL
            N1kxYnNpNUtIZHF1bW1uZXJ0RHhtSmN6Vm1NCnRxVEt4dkhzRmJkK25tWWVWVHRs
            clpzYm9SVDlZZEJUSUs0MkF0VWpsY1EKLS0tIDg5eVlQT2R4d2VRSUM5NWZQM1Zj
            UWtmZkV6a0k1MXdYQlIvOFMrSGFqL1UKI2tK21ycEW63d9g+t2BZyZ7HSkUhtg7I
            0qiE+KFYyOoVF0MtuK6G/Bv+08LkLQgImVkCrpb/Z3/hPu9iXVQSlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZHVlT1psY3ZzRmYvRElN
            SDRGVjNXamYxUEpyRGlpNGQ3R00xbFV3QnhRClRzcTVkaEUyR2F0cGNRbmoxL3JZ
            YTVYUWJIOGpIT0dMaG9hejdlOFg3Vk0KLS0tIHBZT1JLa2hYNUdTUS9jMG9wdWky
            WVR2OWwwWkV2Tkt0cGQ5empYZ0ZrUUkKJ5JTir9jQJ/dKF86IsK0K0NC5za/7wuD
            e5zrXRhvBB476Kgvi4gdMvDOklH18LAXYb/Dkcg+NUT5YZO5MRYiwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T17:49:16Z"
    mac: ENC[AES256_GCM,data:9dvbzCQ5bBN10Ot9yeF6ka02gKzzwRNepeQ0NZk1I4pKreFnwW9tC67tNtDkZeEpe2R5RD3L44gBftXtmqrMjHVEcne9cE13AiQ/2ALlmf3dco3iCHXcSwefUTyeRLB+m65ivFzSmPh/RtaOa3a27n6dn45l3nf7W8EDul8v3vw=,iv:gJ1OYJs/xJ5vB1xODtzQzmBvZEiAmPEaryPmTwqsa5c=,tag:VD2399iAotSPlTikbOlbXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
