apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:p90jeZsukl7xzs4GkUGE0571QvNLaWbknSe6PZCrsw3d4RBQaC6IIPrKzedsIpQkeqPI9IAnLdvZW/Uvb+XL1beE+ZOmgYhmVf3eTk0EWJ6//Q4+NbkWYD8JOeLsG1jLzEr+zPCBUPyK3iccdZv9VdBdPq48R5KBrmCqeQL8U4OjOu7P5xqrVYfp0ouQd0JZX38gzz64x3YJvyeXRwqCKvR2htfhWvH1cKBelo+AxldwFOaJQKkamkQ5roYYU/qP64wpKsOMPbMnnMEQOhVeJ7XWiUUZ46q24mPoOKxnTjLi/Ap5SBTBAGjQMtJ7j8ts6PwFrMCx4Rj3u3EJpC2K54IpHzrHEq64gKKjRFOO/QE321Yk03OYNqGFSaP3iOlohC+JmusnqLe7bs8etuX22D4G6Mc90MWOu4qeyKGXWzR/FlCx9vigcVXx5/Pap1muFKaUXqcYVk+GbmIp2SAcJ7paT5JvQsdmkKML6H4OMBzh9ioUGE89mWynlPq6xQh0EoL58J+wqo/hCcHgvhj9AH4/7Bvg2Rvi12Ft0VvIwZcsw+XwDs1cR+B2Np6AsI70ct+j1odCnVQiUArLvU43OzJnCXJe+iYemNQBVH90CdBt23npuiytpuUzK+c/qNCzBSr7vwqAYhyCMPu9gjoBZrGqqxx0+Wb3myNVzkDPgSaVxtkfXOVKFikGOPfqC6/f6OeEn2AXesz0+4dLcElAJk8sSB/UZ8nF11jfGYfq5KXK99haisHtG50xWz+PCiidbymBb0OSaCDnET/zj1RtDdCvk7SarwQuF0yLg3kEchJa3tElPCqLPr+IkbCvEbejufJ7+ZvdZWZK2TXd9u8Q4ZUZWPl5Xi8ZDliSQTW+gT26H9PG2GbdRuB83g2uxmZoPUy6TuGKxDxnZtb6gW0i14k0aW5CKtb6Lgab2L+F9/csqc7tnUOPria383coMwdLcNLFPJt18RUEZn0XuDx9cEku8Dksg5BAL1C72DYrcWyLVZO7/y97EEi1lZ6YBPjdzc2XVCB239zctlvJpjVuhFaF8svuLKL9uPV9Vs3xv8v8flJ6J0bkKooXA3u23E/cjJXVdgSBRCzc5KhtOmxTR4mdFn1ukn3vrc7JFExZ0cd59bv3iV/k4n90U9u0E+vyZqTRck7FyN4HCJmp+ZSla8gjLMSJM93jufzCjH57o6qHiBul2c6ILBWwVT++MCh3d2kf7i4r8PIQBdI+mvvwjCJKm9DAH+YmxkmqEMy6ibwKFlPCp33O9OnZNVvKaCzAtCVtvdhUI6xtFwxoUfl5QMuripoaId3iLcmyUDYDFb/KsMU/aBZlB2bajq/G8wDsGyRCTZf3172v73yigBbEnxsnipd3ZAxazowxtP0SYC71jwTZhZm/7a28TlUv+xyFGTPgyhG78Km2NPs1pFxW/GFnAj6A/vEoEmx2koclYq6xzwMD6OSD2mAojV0z9gRLWU7PgHhiU6xAgN9E5yQmng+XIX5LY9qzJER/Br98XDdKOLEH3q8gpzPZVJ19zEPpVCj4NwNJoXgRil3/lONCUnVd04C0HSRtsO+4zPZQKGX1HQfiQ7Y7cDXBJ/WeCbIAtQp0P/Bc36bq7cMtEh64ibuw36ZUdPppzkLlyASpotOjv3uCA6knqWMPNbXS9HJ1Zm85Y/0JbLX9/mo0IK8cIcZ/oD/mU96X2laEYM8Kuh4zRbsgdRjK/lwSWEHOn8AWs0o0EF+VGgddX5AGYDY0HKth5wHPpYY4j4a4FIkHQEQPE417ErcfiDYWL9/fqvMElTXJxIWNkNRhpHsiWvk1TA0vkEfED8vkaCGs8FNvpXFsWeCQ1yffp6biTn/Kkctm8by9dvkAJaIajKMuKAVrvMzwQlZCkYFVwN/3ZkK3IASPL/LQHhmbYclJMS/YwlR87RNX0Kk0S8wZsBWrzQfKvtMAZeMqJJzcC5hJakLW7D1a/v9oS7DsOVn6P4l7ue0I4Z2lBvb3pcFdKKjphh3Sr07d6TKkfUSQwr0LE8KOxSL7xID6CzxEG0pbS7B5Oxr0HRv7CegIA3yyeQqtFUesniMjbpeMWkYjDXxSVgx/JvjXbZTnJZPwLVnrZu5BNp5o2PvxsNwkgts8sbdkZrPqDNVFWRQ7Olsp0hCps8hNVg/E3mBtO6QBb3W7BINCfGN7n5Mw+jEyVkSaWKPN112Xhgw8evFwbogCee1uv0XILt8tyRuG/SO1oiEFwXxwa6cu9zw6724L3NZrY1TosfY7ibBHc/mxfWrdZba4fGGlOG2FKDKIxE+NmToUP4dhbhUCAX/fs7Odh22Rzb++/3EC8owJajgqCFY7eQRqvjXazIQ4xKISVtpz89mY3V8FedqiKVpTfQCm2menJq+kFKRC4OYu7CrbyimUS60/G0IKOOQQ668VW1A/MEA2/0nuEvf4jIwqRPv4szVdwnVxzZB7elEyujmuISREBwjhFal8stGDg51kPwNguxOSor7m8IHYTlWxCXCzs5OJTMtWaWSjujiLqbbGtumV8mlvDV8HQnVOkFEYXUE2I0JHU5ZmwS/jBPps1pWrVPKWDXJ61LcvkWHOp937QXg3vQc6XZh0GZmSQkPNwwOdusrsIMkkeB0n0bzWs6aLhheDB+RNMhEIPc7VW8ZDh7f+tNeXNKcX6X4PaEQH,iv:0F0AR4E3RN+8PE5olOy4FD+YTs9S9Y+ymdsqO+TM5wM=,tag:moyD3XYjpnHI65lyCvH+Wg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdTAvd2lpNkEwdUtTem15
            UWRTbXlqNWRZVkdzdXdQcStyWEw1U2g0V21NCmJOUG8xeGRwVzhrdEhVUEZhRTRY
            b0hpZzN2aDFOYWF0TDllMyt2NWgrNFUKLS0tIFFUNzF2VG02ZU14V1BIL2RQNE1w
            d3FLd1NXQWM5MTQ1c25VaFhIbitwRFEK+CBTbxBuzLsR0J0JDBxdFjhB5WMZ1QnD
            XwckHXIU8L0a+5jj993Q9vPHj+2bKk2RuEhGK04Al73NOUtM8XLLDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcStFSXdJQVJIRFE0RERV
            cmQ4NVRkdzhOdWRjd09zSjVSOFBYQjJ4MGlvCmhBR2huODVhbGVZVHZGazVqdXg2
            TFo4aXYwdmRJV041RWlDeXY5TW0ySmsKLS0tIHVNYTFMM24zcW5LZWJBaE5yRkNU
            S0s5OXF2WnZ6SGcrdXp1dkpZb25YTHMKfZnKnvp4/9tmmHne+Wap7eYLb6JfqFf1
            CmxcxqMgJwLjRKX4nUhwwBjIkBKRRN1XuOYsVlM8dIO6WImw06YKFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUmExZ051and2MGRBcFlv
            OHhtUmJBTVNSeVMwb0RJazRndTUwZmdxV0hNCkpzSUlqMmZCSmIyNkhwNEdORWRM
            cHp0RG1RNU9aWVJ1Vy9GaEFEcHZweVkKLS0tIEVpVUEzbDBWcHMrSUI1UTRNS3Vn
            WVg4T2hyODhGS3RFempmTHNkRjNZK0EKCQ9T8LbG9q/Cje8GqKoleGmOxSaX30nI
            iHwk8IkJGZzW63sa1Vc3cZr4yL/A56ZybvxqTWGGjkCr/rvDVK8rmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T12:21:23Z"
    mac: ENC[AES256_GCM,data:JWhQLnTVb6CubmD5jHEFuuz02j5D1jpCy7hxtB6HAkJcOXcuSX86X0xXZsvYDEcHJQYJli7Hup1dP+PaBfTMVqD+J+bShKolMCQKnj88LUvnOg3oSBuztqkA4gH6hm4se+ThN6J2M+/rwMcfzPwa9q8fzQLUk/0NDFr+zTOlCS4=,iv:T/V0U1AsUvYVLmpvg5mROpAvzxVTTKFmg8MYoz5UmQI=,tag:fT7XRIu8NWb8tTbWX8d9AA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
