apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:YrN8H8/2OSJMIatfkhnGC8TSKWw=,iv:PU3g4+d6wYYFyRC7mPYrWfk0lgDlHLhsQr/eS+FXKgA=,tag:ZU+HK+jHjUqIUPSaYwyV3Q==,type:str]
    userKey: ENC[AES256_GCM,data:K92mfHHFijXJFrM7u8IdJpYc0IyUaktBWWu6IZpp4PuyZRTpPeDKwCr627RySVUZBUZE/J7+JWQ=,iv:N/C67NQSnokiP9MdeGmyMAAgeGPRf3nsh3+HreW8StE=,tag:i9/HXbA4ge9ft3fpl4SB0Q==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWm9DV0pHS1pmRDRzNGwz
            NGVsbGRZaHZPRkFPODA3V3BTcDlSVW9PQTJrCk9yTGdoZ042UVpjc05zSlhUZm95
            QTA3MUxqRjM1ME91UTlZOU50QnRFK2MKLS0tIFpkUzNqaFJpRkRqMEtwOHVBbEpp
            eU5NQ1hBdHd0dWJUWldhZWs1TUlWQ0UKent8x9W5LkTjx4a386WSYsJZmH8/zRmB
            5Sqb2FwP2IagwOKYv2+O4fDa87eKSi7UocPdiUd2lrMPcWAePj24OA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyajAyWmRncXhJU05BOTha
            d092aFJKci92MDlHMWgrQTQ1QnFBVmE2OG1jCjAzcVpZdkhQMzZHdkF3cklsc3lr
            REFwQkdST2dHZUJ1OEVKNzkrQ2MwZEkKLS0tIExQejMrbDhPTUNLWEhXM1JwQWxx
            WktuVTlydEwxSUJBaFBQQkFJd2EwQW8KExaqGzf4Uj0mQiBAiXR61jK7P8LOa6+5
            63IDMmPQNJkXaFTL+wqJLuYendea6yJMlp81cXwE1hF/VyFWGf48BQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYkx1MmZHdW1ILzJCSDJk
            ZlNuWHpMdllJek1QclB1Um5aeGdpakE3WFhJCjlQS0hTWVlZVkRXUDlEa2p4VGxq
            dlJhRUh5NWxkWW8xYXlZNnNxWkIrbkkKLS0tIEFtdWh1ckN6VnZFcHowUTlna1J0
            cXNwanYyT0ZibVlKbDdMUmhva3VlMFUKUBdgejnkUrFzqIv9CqUFGCBlOkc6/z9t
            w32QvZOrkG/ls2y0T9FN5E4WxXULeaqNxM9hrt2+0XP2JrS82h/u9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T16:29:38Z"
    mac: ENC[AES256_GCM,data:LCKUJU+rJVRiVhSBBPv4gJWoiHsxSfiMtcKDZgXtu83j6LA0uCXuewtnnQLV1jwBo7/MQcIFgzZ6Yssfq6VROjjvC3dSHkkei3Wmnro8rmi01EzHkyuNMb+qZaDDLTO662fMjA1U2imJpqZ/YrTDXWyw/46ztGk+O1PHJGGLSgw=,iv:rv+GYACxKVIf9DBt8vMarn9PhDGyOk5mdhPFCQWV3jY=,tag:ppOBzlwY9RbQjsELPAoyTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
