apiVersion: v1
data:
    AccessKey: ENC[AES256_GCM,data:gR4mR1nzm6pW70BYR4cUxbh9UFabjBDC,iv:+gtyTt6/pnvmK8aooK5ejINIbx4F/aBqNL2GeJOyZTM=,tag:YXvJgl550t9NkNaAaGMI7Q==,type:str]
    SecretKey: ENC[AES256_GCM,data:7VKQwa9pT3jRsBHvdF3nI25FQRaaHpR0zhQ8tDWNYWe9bppWqwJ3GeTvCN0=,iv:SuuwyXfyXZjUDvOAoUbxvx8vvRBL0J3TupqZ521ZG4E=,tag:S9uwp25hDDBUuyHNKVJ+Kw==,type:str]
    accessKey: ENC[AES256_GCM,data:wo6Y3lREV35RKCav24Q6K9HoJ1xJivgA,iv:NNldSTTLjNoU5Aa8SM5ZVZ+fVIbVgCMqLN9y3tYcsJ4=,tag:9cFYsAKqtnLZCAiLvyQKgw==,type:str]
    secretKey: ENC[AES256_GCM,data:5AjnAil8vABd4q0COKxwKLk2jQspEj725L9DHm6zxkKaDm0Tns7qtJw85gQ=,iv:LEpU2Y3EhsT4tEfXtQNxNQRpfyRofJ8K8inQbmxfSK8=,tag:LPdIzzdSPJfTHe8YdAAS3w==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ceph-object-store-credentials
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBId25pVDlDTnRlQTFBMGVl
            ZHpYanREM3VIQkVuM21mR1dOYk12dzYwRXlNCllub2c5ZGZwYXNoZXlveFZlcVFt
            ZXZWNVlSdTk2MTBPaHdDR3E1QWIvZGcKLS0tIHNKNTM0OG1rQWpqRXAzWDJpRWcr
            MkJER041MFdWd2lDd2RjdUZlZ2huSlkKYXFj3dqAPBVwx5svJW2ouftTMLs184BO
            MANzkgsiHuVSwXpVqdQT65fk3ceUpJznQrb7vQJReVKEydkvuIzyOQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaTRVVnR4ZFpuRktZSG1F
            bjNHaXM0ang0SE9HQnp0WGVxZ3BrOVphNWdZCkFFaTAya21GWmJzeitKRzBDTzh6
            eW1FSXQwUnMxbXZrZnBibWlXNVpXYkkKLS0tIDlRRU9heUlyM3d1cVR1aDNKcm1B
            aytrak90YjI5bG9rY0tCN1FuWEMrQjAKO3ljefnAXEXYc6cmpWb+UH8pIuYYrwIb
            ubme+RNivBTG0Q4wOA00S06GKcZMZ0y89zr41CR1EZhUg3J60OqDBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUk5IclNrSVFNVnpDMWQ1
            ZjRPaURkMnpBU1EzcG85SG03cUFDcUNFbjNjCmtvMEZkTWxZWXpTSndpZ0FRZUJY
            cTFENnBLR0ZoZWt6KzF3SDJlNmdqSGMKLS0tIDN4aGM5TXAzQTRqVkh1NmJiOWNr
            SitYTkU4a2tjekthMHN2MGcyQ1NtUzgKXz3ABzDnP02yWiQ1m2OGjFRRAfojdMwJ
            1OfL0dTaVuU82vc+WxxwXmN+0TXhXcRI7ZL1vzeGt4BYpAKQZMXS4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T00:49:05Z"
    mac: ENC[AES256_GCM,data:XhyssmDaj120EfyfHWAnA+/uGOUVvwz5w+ZrJZIP0Y6CfVDbJBvzZoCObNUA9MTwGOSXhrj1HMNw/nmKdWCH2fvxiMlVvc0VTv7EWNRGuu4xpRCiGtJwWiwEBuIasRAycoyITlJh9WeCOaFaI8A+wlYUIeP3PnH+oga8zYh+3C4=,iv:ofJaxIwkW79AQT88S4vORxA+tBF/axMDHXDQ3cIm76I=,tag:rC8WxcU8NBIYRumlePTvDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
