apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:OET/69Yrt/NJ2rxCNN6iWaGtSYCH1ISZ6M+HCftfJ9FST0ryPkfoADvl7b7WgpR2S0pGVPFtagHFiqqMXsTGam3ptg6bPfErMqa/BYqjF6DmFTha2FfLZ4QstoAnXqDXlG+LorzvzR5e1S6oziIbUU8HJZ/EiZZmga+sliDDHcpXFrdpmWdtfWzzTu05TOWDCV65lNX6841UOOAEnw23i4aeZONrgH/9H5b9QfR8KuMDlTW6HNPHHLVCPV/SNxA5IVwUo8wpQWPJSk5w0gvVHiosRRapZjCl0kdA2tNoBTsCbCHKjnKm3JZnsGzGmbZDtTEhkiU09pElVE9Hkk4oWs7SxhYeLvLDWL6izamSsw+gu0RXcqLUmAJH6DgU0Rr741HUymQGc6qj0bKvvtvEGDS0t89UMZX9pTTbQmaeoHuGcoPDG0IXh48smBgMZKN6cbU6OfEPx4k=,iv:34RV7dTYhAM6zN/WeO41BXlhcIwLULIFTbTcElwAE9c=,tag:YsfEiNFc7uKXjfB7pdhnhw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ghcr-registry-secret
    namespace: apps
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscUFZc05UZ2NuaklLTDZ1
            bk4wbmo4V09TQlNvN3d0OEdzdTJmOWViVkRrCkZoczlGU2pobENXbDhTa0R1NWs4
            R0Vwa3ZRdE16Y0w5dTkvNG1JeVdlckkKLS0tIEtoYW1sRjRBNUlidnZiZGpEeTJz
            bDZ6QUhiczdLTklJUWNqL3VtUTRPMVEKRMMkYTGibbN0ApopDXOiYKuMBn2nBI6i
            6xu20ptn/QOnhNGOIQ6mjHQMQymeZiqLdtgV3LK3vIRcNl1z4UtvgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRzdYY29NdUcrZGNVcEUv
            aDJOUnJGbUtya3JxZUgrdzdPU3Vwb3o0NmhjCjJWdVJYRjJ6azRjMUJRdm9YelVt
            NDJVT3lTaEROakQ1c01RSzhtc2VKdmcKLS0tIGdCU3Q4TEVpZU4wakswcGozVW9H
            Zis0SjFYVFNzY21CYTN1SjFpdzV4bU0KH/13udRK6sJnuBRVyT95riS6xCa6akJz
            4z75kvGyWR2bghrZmgPO5O8Y97NmjJfd2QRMSHNciHtLGy8qhcG2AA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRHlZWjgvWFJ4UVVMVzBB
            NXpyZ1EvTXVubnluS2NCUzdqZG5Bd1hIOTE0CnlMTnBLa2RYaVRnTHZkeUk5cXBK
            WFM1WExRZThaTkdLYS9OamVCMmtVb1UKLS0tIFdGY2w2US9RQmpXREtkUGNYYzFo
            N1kxUllDcnl6SHFtRjhXc0ZaR2NCVkUKcBNmUK2qvJBUAYGR07T/2OKJcbc5Vx7i
            qSi9LhiPSQNQdDQX+jOGiwzHwuq4AUvhjlKDjeULHPkTHfA4z7r6fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T03:01:12Z"
    mac: ENC[AES256_GCM,data:57CMFGa5LjuOuO1BjlcTYeTMqBaXFsr1371LLjZbGSq8Bvj7aNNAfWa4VfIRuGwW0UEyRJEBmc6rwP2lq7GqB6Dc6GbRhP3969ytUBDdiuCcwLRvXWh+2eaHVrLjUh4S2Q6RVHmYQXUbE2C9KKOlZXHbhYecoG72Wr84pFhZN9s=,iv:sg/CfHqgvchQ/IcPh1qDXk5hi9sMoc+g5syqZUp9S90=,tag:oGN+LdnXgfTajXaxvHX6yQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
