apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:hKXrtC9IJSapim7ydrIJH+xzzsmE/bGrfzSCGwZDzFtmwPbnGYWuNmUwVSDQSHoXSOcebc2fE6AFALlAR/vRe5AVx9wGbCxgjTG35VSvnwfUh1+jAvYBrY8y6K8cC/nNhYn5oRy3yUcgXb/FFlIdXm19Lvyi5HUYN03TGZ2kNjS1nynJcsYOWv94sQew4mxfqSWcYMeEhH+aDgvIUrDjO65eMQpU35+7hxNwS6rG7UZpGI3Pd/8mQdkyo6xmXP8YgvFNfm12GfVghKoQwbtUhP2fUdT+g9KmhmswONcArichzFGEYEsPH1nOoCDG4b0Df94j6+iz8mgo93xb1RVlo5dJ4E4=,iv:SvfDwZk8bDoxXyApSggdCfasqp1xs2Bs+PQvuJR5+SA=,tag:lRB0qa+eS/w+vwqiRULY8A==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ghcr-registry-secret
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMGdJTEpad2pLbU1mRUZ4
            WnduWkFxdUFNTDROMDdLaGxzbkd0OENWa1dNCndRQ1dpaWJTY3ZhYmVtM3R5RG4z
            R3pFckVlY3A5Tkk2dUpQS0VLOGNtWGsKLS0tIDF5QW1CT2tXK3VTUk5URU1DV2cz
            WVFOS2JraitUZk1UOUJIUS9kL2xEZ2MKQBYV+4iCyRFSi3YeWuNqW5dI+zewEAgR
            hN246CLHj5Rw1DWNAhxipANOuTG22pPwoFVdzGiTIInSFl/5KmLizA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eWNjVHRoSngrWFRrbGp5
            dUVCWVZaU0hJR0lGeDVBUlFtOE9DdDcrbWswCkpOY1djNU9YK0VOaHcvbjg5eEFh
            WHpseXVBSDNPQk9JK1oya1pNUUxlbG8KLS0tIFdvZ0daSFhyeFpjTTlXWFM2QWNE
            SXl1T3A2eFhya3R6THlxbmhlYmVHOVUKKyU5GwAuvW3/Nc+6Vo1SswZ3P9P9M9Sl
            kS2Bq+Qi6K5ItMLWQmWTQPfSjBkBNoJdL89qbVB9N1Sm86hCEqU86A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSWZqL25JeFlxM3VwSm1o
            YXd5d0VSbHp6Vzl1Mk1ZVXRLbXVCSU5jV0NZCnljQmV2MWFqSkVBayt1OWFndU9H
            SGNPVXVTMUR0K3liN1BMcmZoN3NKMTgKLS0tIFJhdFdCNGtLZG9yalRYUzhkSHlo
            dTF3a0xRVG9ZZmg2NHNYVkM0UTllNm8KfxCRfpg8zyyba8wXZK7fFhuhHmf97sB0
            Pkm6GnmXiX0K49DH3BkQJLpt3yMlJ5k44AvecosXm5LE/9Knzf3ajQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T01:54:29Z"
    mac: ENC[AES256_GCM,data:yMBKmzCZ/tPtARelQ5t/gU6CmFrwfvjIRD0aiaCusQ7DiIov8PYk6CVMZcnS1kQaXh9shmbD5bef5Dn6KUOu9dClS5dNFQoIlDYEK4IzAumM2ahArhry2S3VJWb7DDYDav56kPL1WfKXhEYCMh3zbM7742o/0UySoR7kf14bpQw=,iv:9gUfMAKk5Xc7Tnk2lswu+u/ULqADSlranmN9tH6Gis8=,tag:dPS1nUbk95u/FfSLeq8T9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
