apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Ywi1UcknZ8j4Ri+FHwn20J2rBaTDcn2/dw6iTX2D911CRthR4iMc2b4128P6y8yS7mW+lk1R+jXcgE0G3Uni3gdTLUUz3miBNvTKq9WUhyeof6L5qaxcmDe6aPJAEXErsnulv8/SyPKIvYJycOzNahoJ3We3JgmXV0J30f5XElXzjfs5BsZhE8v6AA+xN7Pw2uGJQJIEmq2WpH1iSNO2RbBv5+jL9eRA+dG3M/uvU42L/ACg9NUmNJlYeoRt4A/NGClvc562WYHxtfSv0Rlh3wyiBOflcWQwSe+RiDsgeT2rZkBxgEZ5FBCrWifmmUnW8X/xNqD+XRFaNgzW/Kzu3VjSvmc=,iv:f3jjJfDkC3yUUTKWHG2WgWIfAzvL2DWzXWVyVmc0UA8=,tag:JJrkNam6fEoe0XPxe9huqg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ghcr-registry-secret
    namespace: apps
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MTRwbEFJbEZVU1IwRDF5
            aUNTdTFrY1NxU0xFRkhobzFINW5CQzJ1TEFrCnRjYnN1Y0twYmRCRHJqMUExSHVs
            Q1FxdVgxN3FEZ3JOQ3pQeS9DSGs3NEEKLS0tIGROVVVvVkdGTjZydnVac2QyTGE4
            bksyMHk0QmJRTVIyZ25ndTZsZGxEUmsKg9KjuHc2vBPWZ7pHYpp//xKPO/6JpOM7
            W0GgvdECyZkvOUUtGDqQFDPhWkYiSJIUyoC1B9N0AhZTPuvHOa9I5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWXpVb3NDUEp4ZG54Z1ND
            MG1MNXNzR2dBZFVnSW5OUERHME9XR3ZRQ0JVClFvZ0d3ejR0YXFNVnpBQTI3Nnk4
            SkgybEtwdG1PNzdzYjQ0Z3U0djlrbmsKLS0tIC9GbWJ5UGdUNmZFMWpFQ1g2SGlU
            ZTFaWms1b2N1VWJFOFBHYlBrY0lSMmsKnjrgKFoL6qGb69UN8aVsfj85EgldhXMQ
            x4GHPcZkSZm2T0t67/JYGESODiPFyodN0GEDMbvp8wqsCpRrj0UNsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV0hGaUFDUy9DQ2pRSjZa
            c1llbnZzOUFUZUhTbm5lTXhJejZEOUdUV1FjCktnb3RXSXpvWEtZc0MwTS8yREhD
            aG1xMGtmclRVR3F1dEJZMUJUeHd4b3MKLS0tIEUrQ1BSN3dDbFdkbUxRM29wN0Y3
            YVJIdis5bGZXVWZnT3FQbGNaYXRxMFEKjpuyob48giB4AN01j1EixRf39Ik3OnyS
            lYi5umMCo9AAiGNvLKjB4CJRkIlYNi2VWeGPrqt10wutgYXnPsYX6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T02:53:46Z"
    mac: ENC[AES256_GCM,data:yOeDIb8UjuHhlxgs42auWP8lzFNOZlAg52gz45V5hqD9ZiloMSWxQUnKWN/f1bKBdOr28t8kk1o+zJP+EmTGGe5wYpokndoue66Ftlf1cdBSiCCPESYlXtF6ZZjG7wn/2p0YoKDtpL6JWHzeCo6BAV0LVeHtL7vYGCUsLNiZQe0=,iv:ViZm2agzPG8ooRsCuvITyGbEn69zPyQsTNj1CjsSsKQ=,tag:3t/7A7tDuMoCBSIaQ2RuvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
