apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:FJg4o/WLkZnuubRBsTuKcFxZCAaYB/8YDVz4Gjugrwmyj3bPOyVKTVsAyu3rgWreZGYe2/NIs68xtimiWHTnNrEdqioRetyZmqhmXTRf14su4C/rvoVudmKJt9Vf9qggJX9tF6IG5OQtTOY9D0cu8tqAuAddstAcen+jwZcaIAfiHlWO62IvM2cOrR/jWjD/2PeCFRsWkAY+tGnxIfm4KPVV+AQ2Bm1wczOGfBG2xA5r5IVDW3kGMIrnpKXXdc8HVjadXTV3jWhuJml9tIRgw8Y+fFIE6gtyT22JaFH5u4KLzNaW43j8oKx99pethldBToqfJ0NloVzmMZ9seQXAmwof0IWA9AZ0dTfugQ0nd5dtKhgiB4/CTJoy/or3EqP4JuGZOzPZaSBwbve4b0bPFfCpTknPNCJH/do4d17ipBYdNDm67W+G9l6e5MEf8giDfapJ1UOm0D1pTgkXBTT4t7XB5cHz5w/vUl7rOknqxW9h+TsH3/8Hazy9XRYT4qlSZs+fN+kqRj0=,iv:U7PbjEru9HYnZ+zmIi//DXu5teXlMXb9EN6XPR1yXOM=,tag:uW0d/y/KH2LLL/z3QMPImA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ghcr-registry-secret
    namespace: apps
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTm9JN0pyeFpPeFF5YjM0
            ekJDWHVmYWFNbmR5ZG84dFl2cWduUVg4VldnCm9OQ3JFMnRPM3A4VUxCaG9KVGRm
            N08vY2JSRnhraHpmQTVWSnh2UkZyOXMKLS0tIFdrYWQwMlFiVk96SWQyOVJXaXpH
            YXh4NTN5U3VERXN2Y1djeWpBVUl5RHcKyZTZwzW+vmomZv50r3m0dvcDW7xOrt6V
            PCJEwCI70OUEWNyVZTfoPX2TJ5FrW5b5FOZ6g7J45c9FCqE1hJ0VYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc2w2Kzg5K0hRR0xhcksz
            MWhPTXN4Z1FETDc2N3l1em9QUjZ5eWpRTERzCjhta0IrYXQ2QVJOOWNsQkN0aFI2
            UDkrQmUyUngyczVGdkhLeFUzT20rOTgKLS0tIExuZXJaUTh0OW9YTStoRWZLTkE4
            cmJKTTQxcXl2MzRTS2cvbWh2L0dGWjgKMGTd29RWQpNza0KouFfcxUeQRU7OFKJv
            OmfPVSLaOxpR9rrBHmdEIOAh+NhJugx4L1s95vUC/wkeTgGF82IGNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdldmQnhPWFlwM3VzRzhy
            ck44eUFyYSt0cU85NFhNd0p6NnJYamc1YXhVCm5qZ0hwRnpOSkc5UU5HTzk5S21W
            UmVpVytua1c0OXE5YSs2bjlzNjZteW8KLS0tIDVkelpWZDBZREhDelJUWXZMZzIx
            MUkwbm1SNGZlZjZCakFMd01zb25HNHMKWqOZ7966p7hXZ1BmtYyVNJz/OqevjAQJ
            +4Uk5R6mq0rZ9gtIZxTWmqxl9s+k0vEklsNtmGcyyIQdTGcvmJVTDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T03:05:39Z"
    mac: ENC[AES256_GCM,data:CtrtGUSBkJHRBUs7ldcVLE/CXifhTE7Vn5X24RisOVR8ex/1Vik2eNp7iqTYXEYmITHBawr4pau0WqBBV59UTtS+hPXl6BjNtY6JcBvfRqLhXFnb18OEPcMW6zb1egug6X3pmeUhA87SDQodS5zAyp5tPzqVSk6D+s/CrBq8wJM=,iv:nm/NVE1RYWPdjImmVI+3e664o09cYoZd6kS3eojhVcI=,tag:tdX0q/p1yei54VXNhYUJAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
