apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ghcr-registry-secret
    namespace: apps
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:effuERqzTR9O1K2ZjZWcDjxXGFzoqm4vlaoIuRvU+Cp1p7c7eIjafyvYd/6M03syM3k7ny1DPJN3komccgHw58HVeFQTgpjAOp465uCtdPjcM4lKnujW6BzSg8QuZzmEAxkdnxHRISXatdsoCq5LR1Vpcy0dyEvIhlBIV/TMUPZeLMKCvDCdW454O1kASZ3u05II+WaAJZKImToibzXjWjkNXTseemBIVlrARLKrwKgD2gP5zws+zzfgIdMuqT5E+gRkR+oSQXjYp4rgCskfyU2wzpb4WF7uZC/z7NJbxt2by1WEEjqfJGDc/fGowSKBXdtscmAtDaF9whDST2yHEXFANVk=,iv:FYHxwjUncq74wEcynCs0Nd0auXea3f+ynjysxgKYr2E=,tag:t9FNaoZqrsGy4zJZNuovhA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWE9iMk83eWRvemUwM2Fm
            T244NVlDRHVPR252Z3ZkbFZ0d1l4KzhxR2pNCk9DOWwxOTJiK0ZMSUFkelRXU1Vz
            M2RwanJHbjlxVUdLVlVoNW5OS2hzaHcKLS0tIGhCMWtqN05SWVNXNFdFYzhrSWdO
            bThBeVdhY2dsaEdFQzlUK1FTdFRNZWsK4jOK4fYLsfUo+nUfqAL5MKiwH4m77fWP
            tNEkM/E3IWOATo1a6ExnKNn9pyMy76Z5aU9kXuGwlLEABG3s7GJy8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ1hhVkxDNXpOTDBnNkQ3
            T2toamhHRC9RVlFqaTZqM2FtQ2ZKM3lpclFzCjVZN0ordURDODZMZUpQM01IaEZO
            bVBHcVlQcXNUSXQxbThUNWtKanhqWEUKLS0tIFV4THZhNVIxVUQvOENlVFZDWGJ0
            Y3JlRGdvOHpSUFJGOGgwMnVOMW45WkkKWDiiSBrxIu6EmWggEj5DhtaC9Bd7aRt7
            GuWkiX3VIgzU8MNNlocTvBz/FARHkGesNGWJxBEDWeE3IBnRzLT9sQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQU1DOU1Pd0JhOHNOVGhV
            TjhKdE1obVEyVWFheWQ3Y1l2djQwckRmMGpNClZmWVorTHFCSXF0YitqN1l5L1Vi
            dVNNc3pabU4xMTF3WE53ckRqTjg4K3MKLS0tIFpETVhBRkhiSFFBYkNJOGprQnE1
            dDRlWGIvaDMzK3dRNXFaTVVhd1hXQzAKfkoEsDT599Ou1WAIReBp7ymog7ipQ78e
            uKIpWCHAFPiariXHLrByyENaK4s07rh2turTtDsqpW4N6JASGCbbkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T02:38:55Z"
    mac: ENC[AES256_GCM,data:F+D7o7Qc2J3rMXQTOuXe1Gn3sSJQr3vNr08XgCjp2MsPawbdb1twRe3cxXuB+WxMHUbsbL6/aNNgZwKqxMDf3mzbVlkazPMYtt8afw+rDR0uPC0v0Q2yREEXlDaP690LE9Kw5iFmnVcz5Hp4xgPG9mdGtq1XSx74i0GzUvYK+Zo=,iv:+Gfx0ySz2yUEgH1Bm40LC+yeFcMQlyJdtphDKlaEOjU=,tag:oXYeton50gfIN5OxIsdpJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
