apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ps4otDYSMmhy/vSVprp7EV8lb5k9xzTOouv1zZVInzKby6enZENZ+d0qv0+CQSjaYUVz5rA3/ny6XwgQnfBcw52hLP0Vso608sq+lWIWDcGdgLW+lATQJ/+U3h/9r7ScWM6YZgm6jb81c16tYXGBObvRTPnnwnxPulKfL3AmteUMYb3dBjiArcuCNO1HshPTg/6l3qLcyL140fi/4b49oX9WrkSj6DdwW3VnqHDN882hCC6nceOxWpzOy4YQEdpemS+VZYtPrG73LrJ9dk1ZDtiHnQjGAcH0IZbpBu+vTp0xVixXXcalEwxOBC88h9e9DjPFjQ==,iv:E3cwTh7lEwT0R8u9TfLsq/hxOrP42rJcK2ZB2LckJMg=,tag:IO4ZnrhS0uBH6p8j9KLC8Q==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ghcr-registry-secret
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBld28xT3JlS0VZank5NnNJ
            SzVJaDN2T1VHWjFCbVFSYXZvV0lSTUh6bGprCk1MbllSdzMyNldwZjlOMURMZEJN
            WmVyQi9CcFRveTk3V21HOENFS1ltWDQKLS0tIGhyWXB5ZWM5Mkp0R0FTSFA5cXlq
            YXBhZUxIM0hmelhKb2ZnUEFSTDd1NHcKR0A4m3fYBCgN4Ni7ExNDKyWbIqAe02pw
            D0KjmyU3CVESUSAEjVg7MRrW6qxr5OOsDzIzznjYHeL9eBsRi25yew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxV1NpczdiOXpQenQ2MVJu
            S3dIK1V1SVZXK0hJTXJFME4yL3RDSFloMms0CjlBbVQ5MVRCQ3ltL08zdVJsVUJJ
            NUJPMkc3d25tU2VMLzlTTDhBSC9CUTAKLS0tIHp2SHZjTlFSak9JeTdmWnJlejgx
            WW1vb1BZQ0tlZWdUdXM3Z0I0K1VOWlEKVTb1jCJHF36r9RkhlsnFtS0l2tswfmfP
            L1thfxmdBl7Wk0R16nDWrP0BnTHUS4aIMpgIkv9s1B5g0N4a4Oq6bw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTDJKZmpzUHNOYitPMkdq
            aFpkMW9vTDJoaDRjQ29hRlErTE12WmFKUG1rCmMrVTUxdCtzeHMxTExySk1FZ01j
            VU9mc2ZzaFdEQUpWM0QvdjEwRlAzOEkKLS0tIGFGMU1XTUNGR2dDZm9YeGo1TjVy
            WUo0L3JsR3p3b1FkNTA2Q3lKbXM0RkUK2gu6/KuZzyLjeXyBj6IEH0VOCnOIfHbr
            noG7jT5q/jGhrQnTU1uF0Qhhu/MJTEEgXDiPy9DFCHqOXwpq0BpIvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T18:31:54Z"
    mac: ENC[AES256_GCM,data:oWanFJ6R0VvtCDzuNrrz5FDZmZRL/N8NsK7s6GeJKJpm1pCeaz489OrEqmFM1/F6Vf2JSj/hCVbFx1VjHCwCLMdPeuCH0wuPejdfgoSluM21J55V2KZ6IHm3fyGwsQjyA/0VA2CyfTfnkDY3BBJqilAlvpdul48D8o5urV40K6A=,iv:gpLLsm6b5RUqOfbnlSPD548yROa7VPRKySdIhwJyRLk=,tag:up98msCcAOVDLDE7gelTjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
