apiVersion: v1
data:
  SERVER_COUNTRIES: ENC[AES256_GCM,data:XhLnbBeeMeI=,iv:YzW5BPGC671/2ievIznug4ps96dNLo/ZAwaHqhUrKZc=,tag:rGVSj4EvNCHhmzYH/6qz9A==,type:str]
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:eDmog+wpHJQIVcEo,iv:+DIG/zLPIqYfC7S6gG3ESetWQnFjujlpGBQdtdgce+Q=,tag:OhM2Mu7Yty/jSVV1MoxJbQ==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:nuvr/N2oWlvT3nJr,iv:/46a2rex6NLsY57yUiUuVBAO/rGhMnrDYAVZ/qmePwE=,tag:M84MowMicKe61zMwMzbeeg==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:2J8Ki/Gh3vEIOcAhgxRTAHhtXzxTkVxdkm3YTpf/UJBUy4uD3iLOUyKP4oj7gdIWdKpy2aUyEy+EtpYB,iv:kfklB48rgbx13Po2zIWyZxrNBSyszm7xyjYlSmQGxV8=,tag:o2L2w83du+emz0hmgEQnrQ==,type:str]
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  name: gluetun-vpn-credentials
  namespace: apps
sops:
  age:
    - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QzZEVDNCUklFdFJkc2oz
        WVdSVWtySmNFcVdmTEw5bnZXRnl1V3pYcVU0CnBuWTJlT25DcW5KUnY1VG1aRGVw
        bDdxRVVPTEdEKzBNTU5sL0F3QXg4emsKLS0tIDNyRjAvNUJKZHNBYThVc2JyYXRF
        eXRaRHBhcm95VU5NSnNhZXdTekVpa2cKu55WvghjEREgAYDhjyKRBwNivWX8ELG+
        L2mn2pEuWPHIUHx791yppLsHgfpkihwpQA/HhaRAI3afe/PTs8JS5Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUlMrM0RkMzZmTjJqS2ox
        Qk9DczNoRWtTSnVsc2JKOE0wd3o2WTluNVdBCkM0V2NuaEJhN0ZybjRqa09WZzhU
        NUMxb1lUTVMybWExTDJxbDJUcjVKSUEKLS0tIFVDSElvMzZTSkFvS2FlSjhHM2dG
        c1lrVjdubm16UWVkWURPaUZacDVMWEUKoXc1+a5Rfli2JGAkzv6kDlIaqlD9ZVxP
        tEivniHsw3Yd/Jy681RO5zTWo5L8RPn9AoP+Y1bvIVrtLvD668SvTw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESDBZWUNxT1VDODFUV0NS
        K2tBTEVFNEVqcldKUnNidGk5K0hHMHNtNUJvClNuTkg1aFc4azRnNHZmOC9CU3c1
        Znp4dlBMaVo4OGlTa1JMSUVpdSs2RFEKLS0tIENacnJORFZZOWVLZmt2OU5nalJx
        SEJqdm1ITmMvbEdldEJZKzM4VnUrUjQKC0sWdQU76TRkcRzGV3UNF+1brIISBgdk
        UmhduQQyzzEMCzlPIpHcHGf+37eKnnqEpV5PkJWWZxTa13Y4W9D8zA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-02T16:41:33Z"
  mac: ENC[AES256_GCM,data:SIp6Wi93ipHEuA4l46KmxYm/t26smixEv1Zyw+EWQWEGGMN2MofpiufAoeE07vOeNUsWfdI50CmDz+jtCJtVhUtw+gCtUSrMt82wy0GkqynUly4Z7DCLnpqxDWN0Vq+xfjIm4EDLRjsCXyYVioVIu6SDcLtS8NpRzyC/E5DCHik=,iv:DslUNkrtfxcUIq6UFN3FLlCP5VV3avdrY/wnOk0rSX4=,tag:BIqocFjm7Nh1ob696rB6Fg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
