apiVersion: v1
data:
    SERVER_COUNTRIES: ENC[AES256_GCM,data:CpBIZy8Ha7M=,iv:wSxxOeoZ1mNq9hLpRSN6zbASJiCVUMsPwpvbwv59QsY=,tag:YaXxCWBzzdMrsxNIPMv+ug==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:4wHZheymqv6ANi37,iv:crLr9WbeeND5SdomU+hfpSOxRRR/CKtMU+rrmuxMhyc=,tag:/j8mjiXUxct01YmZdzvZZw==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:Z+a+BuC9/VSyqWhH,iv:h2KVKG3qiFP7SXl8zzNNha3vtc/TctL+lv0p8ou0S5s=,tag:+3dHt5d+TcJYTCL1HXf5yA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:3F2bAFJ7XEI9XjzRtxjZrLt0RroI3XvflZO8RNZtRmFDW6SXh0Gpmrfc47BoxfLRLqWUyp7yLbi0I6oW,iv:4TEj+kEvfIEtdpz5MmkUMcbKxIsKIC2Qu3J8/SgcgXs=,tag:VwkMlDf5vdsZFtGMAL+I+Q==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: gluetun-vpn-credentials
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUS83cGE3YlpBaVBUSkk5
            RlJBbnRwNDFaM3hudTk5ZmFRSTRXZ1NtKzEwCm4xUU44YWcxMG9YMHpydmNSUTU2
            OTlzamFiQU5FSTF1NXVJNGZkclFoSlUKLS0tIEhBUllpSHgzZ1ZWOEVFeE03Ymlh
            MEErc28xczhPaC9sTXVVaEc5Z0p2Z3MKN1/J0DNRA5FB7NTh7kULUP6d0D2NWGvu
            Fcen6CiVm/OQeGt/koxdAiUDINmiLys5jKtsBtZYjZb7oWHbFChRTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQklGL0JqSnM2QXJYd0h3
            S05NOVFsSG5GaER3R2ZOdk1rWlA3cm5zTmlrCmhkemlOVnUxMDhuZEU0Z1NtTk50
            MmNQUUlwYk80OUI3RmRzV0FwRHpmZTQKLS0tIHVNOGpQdkZXWFRFeFhMck9SRklH
            WFNWYjlRTVV5Q0svNWMvOUFYc2I4aVkKaovx1a4C7x0iIihT4dp/bpcSNe1Qx6xU
            8ZCUub+sSgiR02dP8Tf+slVnK5wO+GkbMdZSSepfabLH3s9t+lTosw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRakNaeDI4M1lYZE9xVlBE
            bkgzN1VqME5DRUZoNGFkbFZhTHM2ZCtYRHprCkIxeG9RWmJ6MmFrdGdTR3FwVU10
            Ty8vREkrRm5VdHRHaUtKNURjN09uSE0KLS0tIHEvdTdEWTRnOVY2MDFiVHF4Q3c4
            MXBUb1UwZSswUDZTUFNZR2hXV2dhQ3MK3xWxULeWg3099Pn+kINC0I08G7ihsHQw
            E2CXbWxaX4uWxWZD3tBggOakyuRb2vt1suFtfmVmm8CrwcB9uhBI3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T16:29:38Z"
    mac: ENC[AES256_GCM,data:75S6u5fp0/4SVqfDrWjPgBWbhXr15IONolyIVkzop4IgzViI6UeUv2Dr0WXtmRuaqxvOSWq4mkqrLhjhUZKP1EFEiyqBgRWtF3OT2OkmEIBizxEKIlC0NSX8TiyfsPePvnrS0P+XvqQb3KLO/IAptJPLtqF5n+t6WulI+1uWw8s=,iv:ip7CdhI+cDD0sB27AVl5I81SabemfGnNC6GKTn6xTTA=,tag:UqVM4WrEpbODHGLAczXNAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
