apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_URL: ENC[AES256_GCM,data:pI9bqXpBX6zeA7twLiBBMM7vbq1qt46EO/6Fu7n0o3ZJJhs0PwS6x6E76oea6gy4edTc81Tbk2YwiP9i/sDkZVbjPA==,iv:qIQqiLpsqKKcjkc4OMXtxbTTOYO6qbpQFKOYAC78efc=,tag:0W6EktKQJhq1F1TuaVB92Q==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:DZBQK+ELqTLncGZ+UkUtPsW7ZLxhp29xBerDJaBH+mrBTW0=,iv:vmhFL31lVa2XTANI6uibkg/nn/NOKpphSqXcM9y83PA=,tag:3j8ZrZNOIa98H6sWyv/YfQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:P4fryeZa6gMFMRvZYyB6/Cd0QOmpbv3jEBk+OIo/OBWY05tRRjLPgxaY6aVPmijbmZtxqT/gOg==,iv:xMfMaeDk7NY++Yv1UPFkis5eEIND404kPwd6Y+Lf78s=,tag:aQQh0wxQw0JLz+6Qp0mHIQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YVFRY2NPZFFNdTlWMzJz
            KzEvUlAvazFWVlNkVUtXTHNiZEY5bDRLdlVvCjl1N3I4bVdwbTVkbCtaS2J2SWYy
            cDllcC9RQ1ZubDZ0bkE0QStuMGdqY2sKLS0tIGV1eXR3MmZFSnVsUTJiQWtoa2hL
            bnlhWVVwU1IvRmw2VzE4Y3g1Rng5TGcK3AmtCVfKOCyNxI2RmTvfFavNzZxD0vOM
            MjLTV+gYWocJ+Q4qF9j+hAdc58rJhk59cVC6MczjMzNfLtIr4KExdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNXVERTIrUlRTMDkzVjFn
            K0FvSUN6dDBFVi9SM1ViTDNUaDhjc2dZUVNRClB2TTJPektqdUZ4QWF3bjNNOUpv
            UU5HODJSQVNMUVAwSGk0MmQzcVJ1V0kKLS0tIG1BaEZDMjdQWlhuZWJIMEZEemdM
            TnVIRFp1VjhQSWp4RVhIVTJ6eGpQRWMKRLVFG0zX7fjxmkHa5nUt9D1IZb11wyzE
            SU48G18trDz85Vkf33eunpt3oBxgpbSQy20P+LJIEnIL96jew1tj6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid3pPb21aWm1QbXRIUk1E
            VzFiNmJJb1JrUTBwMWxvRjVYY29pSDE3NFhRCk1lbjdqN0gwbFYxNjl3blhLMTZ0
            TUhVb1JxcllsSDNFMjI3R0JBc0NpN00KLS0tIEEwNElGWUpXSHdJenpIdzdUaHNJ
            RG5FL3ZlYnVNOEc3cWc0K09iNUNqazgKa0JkUAlEWuGJN8q6MmjPs3Jfg2i08HL8
            sQoyCeYlBnmQqAI+ZlEXKAx6ZkGq9p2KRRnt5FC95uIKuHKSXUOzqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-29T00:00:54Z"
    mac: ENC[AES256_GCM,data:BFcxNGqBJQg3k9lFIGlDbq4fMe5N5EllBYl4w/qQJ9A3SgxD6DrysiLnUwgfWAfUHz2JahJ1SjTttvSyd/8OVke2vG1bK/HVh+ASf8b+pU6ucgANhWabLyojt2Qr8wMqp9h2/YE4GbcQzIHCGnth/WpHvxHVUaBd/KU/04zxXkI=,iv:nmuVgRkm/EO1C9sXbvjkmwik9ZKYOREKr/6YpD8t+Pc=,tag:/xfICEe67yZJtbqKK8iDNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
