apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:oFrtKd30,iv:Khh93KjZu3BuW9o/cI0JZJsjti1qXS4s4JWAPlix4sU=,tag:fF3lcnD0CcBDS+krdxLjig==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:twnsNptGiaqJLZrwMQ==,iv:eLiW2eez77RKUXyubDO0niA2NjeLL2p6HRqWpRjBJjU=,tag:oo0mOlCbHuCLYy7l3wZnlA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:rBjuyunA4vc8Wu/G0I9E8D3D2w==,iv:LZGlzQxXjT0lQ85FhgtmF4gHG2CzWPw6QUxE7zUwXGY=,tag:mG8XolI5ZHrmEG8pIAAzKA==,type:str]
    DB_URL: ENC[AES256_GCM,data:O5Kxpx1NOaLXsppGYL0dfv7Xkmn/HashHcBmZQN0mME2zBvRro4NJ+tC261px3ZuEdv+VzlfU7aAzFr6hQSS1zfEkg==,iv:wyCSnspDyMBqX676LpcLjTZsMb8wwKUIxayJEMTK7kU=,tag:HcRXzfKMhZBL7U3RFmddMw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:y/5O2DBnVEA=,iv:PsX/n5iO65IaE5rRycEhwONQR1OtLkGgpmdObLcr+i4=,tag:mlHRPH7nYjYKgc23pwXuJw==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:eTnccHLFuJfwWjwp99QQKsAS7m6zEdni6Byn/fExpJaKPTI=,iv:PAojlN+irWh7gVDXMNz5V/qRnLtkks9kMHHzNVXvYGk=,tag:vqhua7exKM8EHN7fM8FXOA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:x596hO9R6frwCVeOissxkwTGz5Mf+quHW3MNrmZf9IVqQ2NG4DlyDNAeD1uct/fTxENh4DGvzeHOXC/mpA35Bb6dG+Fjm0qFKmMo8V6ZdzCgZvwZqr3wiwY0U0csvSHITDX47jlHv+jSjAvF2eLlqhNYxXb++tV7iVRmSU/+5uCFnsvC48GMUvWAJJEf+NK73Kc=,iv:jFKA36MZ41JTeeVtc0Hs1YPqbSOFWTZw0h8DAXiPEMA=,tag:diJGTqOqjptMGxiL96A2MA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbnNNVzFSbG9wbSs1ZlE3
            d0kya0ZmYlNNMHFzZno0UXErQmJhelpGQmhZCllkd3h3cVQ1UllOOGIwU0xyeEFQ
            M09aa0NIVGJIeGNXNHdpZUswdXV4Q2sKLS0tIGFLbUJITldUQVVEZExVejlUcXMx
            RHJvSXpETk9RRW1zbElwSWVaNjRuL3MK7EkscE6EV4iJpUIIG5n3NcxOPDDDUSz2
            FJ1OKtxE7vJNsCGYKZJ0Y5YEDvsIzVWUH/ImDnywv9HcT8qHugy5EQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M2s2eDBVVHMrU25FMTVz
            Y1ZmTU5iSzRTT3hub282Um5TaVlwa0UzYndNCjc4cDJjaTFubFhQZWxGTFNjRk1y
            QmFVS2R2Z0VWcGkzU3RTdXRoM05NbTAKLS0tIFJHdGlESG5pYjB5cEk3NVBPTnE2
            Q2EweGFwdXIrb2RiUGxYSHdQcE41UGMKVNOelR6w869uhsHBbYpNCFyJzbrFmmW5
            3+lXSOwZG/lk9YCozoE5ZZ2tIcI+ot/zsci86t1HqiabEskqGsAm0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aXpwcktrYXUxTFZJWHZ1
            UlNIWDhGZlhUWkk1dm1qTTBYeTFhOHdHQjE0CngzQ1dkZFcxNmtaQTF0c0tYMWIy
            SGdpMUhoZmQzTU14NmNDR0U1SUNvZWMKLS0tIGt2UjkxMm5wcUw0L09GK0xqMzEx
            eHJ2L004YWFZY1lOYzAzWExjWVpjMWMKreWmz/EDVQVWXTG+n73aU0aK2GZa1/Sg
            c89cNdJ/fY3FFX5bvSDjwKoQx9fAwg/m/jO2YLy6+PWdpqmYpEZpUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-19T15:51:37Z"
    mac: ENC[AES256_GCM,data:OlJVSLR/545nIxy4oy7pmlBkHauvhRly8Wo9R5SPLxenLvqDAaOgLJZrRJ7NM1vz2OnSiyoqPNpWLIStLoKVtR1xkIYkNunQ+g/Uyz10P9g9W7hhV4XJpg+bYvpitSMP+hxB4sWFgg++YbP0r15okOP7CX2U+3A03AI2bUqUSLU=,iv:bAAQFHT98+AIMkOlNNLdH+TWVlHlXel67dmWFxLxpzU=,tag:4m2Sdox/X/1LWiiY9VxKTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
