apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_URL: ENC[AES256_GCM,data:k/Vxm5ceHwKOwFAWs4cWoskXyGMvx+yf2igu/AnC1j6schVFugQ0lVcgyPj0znSz8BceoFnDe1gUiM31QG3BCuuneQ==,iv:AUk0MOgOUrxxuGfT4QHsslWyZXjzskHgN0avPr5xteM=,tag:SKXkp9lsugvk/LxnMYMMxg==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:Kdx9PJc40OiUakSG40MJgwWZrhHJF+wcmKqTRIB1OJZaHE0=,iv:lGp69r+QW16pZR9fhVu5bCsLhlhDIBkIahYoC6mSY00=,tag:fAfPaRWbVlviB/v+uGDJAQ==,type:str]
    REDIS_DBINDEX: ENC[AES256_GCM,data:2A==,iv:qcTuEUawFwEMVE6AFEqCfbHcOHLu7K3CYLIjG3LU3Qc=,tag:oLnnDCcXxOKwzYujehMhPg==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:MnBJ5+S/hDFJVQUXZtM=,iv:gVjdmlaIW43J2skC8c7NXtchvpOGvlfNmfWX8P+ExsE=,tag:RBTeqyBP8A1kzqM7WYeznw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:qFNFQcf6uWQOQe9fnCgqH/8/Gh0rt9AW,iv:wS9h3mkuwVAd5L6570qCZswJFq75dKUG5kdcliTyBio=,tag:UoDhuBvih7Dz+kjhP2wkwA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSlRWOUcxVHNad2RVWHN4
            NUUyVDdoMzkvOWh0YmNzemZ6ajd5azZQdTJJCk9vNDJhWGsrS2dIVVFBN3lMelg3
            cTJEYjVJQlZwYzdwUTJBVlJJQUlFQkkKLS0tIHNaTnZYM2hKdldyOEV4eEdBdEFw
            Mit4S2JIbVF2MFhyWW42d1NwYlR3UTQKF00VwiszMg2/RmkhVAlrh0aEMdXDCiuF
            gDbBvCYM8CxLvo8U8jvgKeuJacun35mNzufUuZtAmjyuGerCo3mS4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMndKYXFVWUl4VVpjQWFr
            bnpsNk1CNFZyZzIwR3U5Qnd1NG1JaS9PMDJnCk0xb1Ryak9ybHR2czJyaE5ySzNo
            RWJsTXVYQTQvVkZtTlNLajFGclRhNHcKLS0tIENiVHpiTUs4WFdvSWk2TmV6UThq
            ZXcxK1BqS3JuejJ1R0t1YXhibnYyaFEK2cCni3dEM6HCRz17pf1NIrphhSAEpyqq
            v680MctCaRcNP7h54oLxL7vXMxBTz/6qYErkbnESf4Q9UrtxT9VPBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cVYwMjdKdjhybDlUeUo4
            Q2pBZHBLMnRZWVVoaXJFV2U3eWY2UlZidkVjCmQvTFdUMXJhK1B4eEl3d0swVDVY
            cVJTM0ppc2NnQVF3RXM3cEZEQWJmQjQKLS0tIFVoRDNBcTQxaE42ZldiZXhkMXgw
            dWJhdUVYM3poRXFGWi9mcWlHc2lENFUKR/ARDQ3CxoeEzQU3zR24k5UYJRf80+2b
            XBmkVMeOX9YSP9VpSN3t5RXPYDH5RfgyWO92J/Gxjm8o1Ddfqnq5iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T02:23:41Z"
    mac: ENC[AES256_GCM,data:iVvw0bZQFv1poa5lk0jPkNt5DUQZjqtJRNdEadwuSlJIN4IC59VQcCzOymsjl0O5XDLn+i1SqEw735O5PPnb8J46iA4jDnQ9P7wIT9cljxBfzxi13Q5IrIk58B7mH1n+atmb8bv9bZC/C/Q6Nm8134BZs3Q8NesHANalJexjs6A=,iv:au28/EkyCqcAAEstHCSBNydsXDJbX+Pzb0bGiiuvnxQ=,tag:CECUdb5WR+5U1UrgC4jGzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
