apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: libebooker
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: libebooker
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: libebooker
  namespace: apps
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/instance: libebooker
      app.kubernetes.io/name: libebooker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: libebooker
        app.kubernetes.io/name: libebooker
    spec:
      automountServiceAccountToken: true
      containers:
        - image: ghcr.io/josevictorferreira/libebooker:latest
          imagePullPolicy: IfNotPresent
          name: main
          ports:
            - containerPort: 9292
              name: http
              protocol: TCP
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: libebooker
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: libebooker
    app.kubernetes.io/service: libebooker
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: libebooker
  namespace: apps
spec:
  loadBalancerIP: 10.10.10.123
  ports:
    - name: http
      port: 9292
      protocol: TCP
      targetPort: 9292
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: libebooker
    app.kubernetes.io/name: libebooker
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: libebooker
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: libebooker
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: libebooker
  namespace: apps
spec:
  ingressClassName: cilium
  rules:
    - host: libebooker.josevictor.me
      http:
        paths:
          - backend:
              service:
                name: libebooker
                port:
                  number: 9292
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - libebooker.josevictor.me
      secretName: wildcard-tls
