apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-db
    namespace: apps
stringData:
    uri: ENC[AES256_GCM,data:yYIClrSeTZu4Dxs6Ra89+EQTnpsSk7BrzRXsMGlK5eqJb5H33B/r/zjMBQr5s5EepbCGtG9pQMH6qGZCnjROk8OB3QWmaeA=,iv:8CQHr6pdlOBeVD0TPXWknE4ugGCGnC4Pm/5E9DHgl0E=,tag:bc4wWL9pSlrKRDzBxd+1Cg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdEs3SEdmbjBBWUFzeGti
            dy9neXExRlhWU0JNeW1SOUtsYmlzQzVkSDJZCkxoUHRsNWxacE5XWUd3WFowNkQv
            aTJWZmhQTDRMZEFTQm5aWWREN25WUjQKLS0tIEFJOTQ4V0lrNTJjbGhDb29kVWVl
            Zm9SWVYwN2lseWtBVWwwa2J4cEF2YW8KpYyNqL27WGNRUhebVOBaARTRKx+GkPG8
            BoprmHQktzxXbIqjNg3fvS/VJ+0I6D+KtPpk3sAXwf2Q2Xm38Cl1Sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WndTUENoWmdnTWtKS1U2
            SlVZVGxXSFgvK2R4c3VqenJGMnBOOXFvWlVNCmsxa0FkWE1Ta3d3QjAxd2xkQmNH
            cUMvanRaYXYwMjJ0R1hGekcveUlSNncKLS0tIDdGTG5PdVcvRUw1TE1LZGVzSVR2
            Smp3UjQzamVzaEZLVTVmdVdBV3FRU0EK+Kz8WVm74VRYSmczPlHW7jARuZDZQsLg
            ZLDQ7ogxco3jQPQtj8UdG+4HGIj5FXYMGcAgu/EmobparFE54ROeiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NGlwRkY1T2s0NEViRUcx
            czNMcVlzQkZqQ0pHTWhaS09MVEVubFFlQ21FClFvc1drbitZRlN6ckI5VEZERGpn
            UFZKNmJXSVdNYWF5emVZcDc2WTZxNDAKLS0tIEg3Zm1vYkZwZkF6RFpQMkVybVpC
            WXNDM2tYaHpjUEh0ZE9PRmF2NGloZHMK+aLtnDB4DowavOpsWEEC77CeiTYSmLCy
            NPx/oKvIvIpfJwQfnEv2DeEPOlctZqJJOiIkHVGVJUyG2Tst4ULwiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T22:18:00Z"
    mac: ENC[AES256_GCM,data:gRpcDoNH5XpjYOr8KXPtvxVyKCzsInfUIkxXjGDs14BTKtrpAmh61MdJ+IkY43yyoK4UVEp3TDNX/mtzm1LLcCg1/RACQZpk2t3DqGn8/LouGqXG1RdjWKf9fvyYDi8I/o3L8nqfGsBZn0L61XDsxXEJn3kNsF/MLcC+md13yZE=,iv:hgLYyClDvIFarFjvEsEwBhGVUTbXCZZVIK46n24gBDo=,tag:xfuaDEBYpRgOcwsCbf3qfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-secrets
    namespace: apps
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:GSCPNPCSUbUxjlP9ixUJ1e89og0kyMpw62Bh4ZEiak37JYQDoaGC9FH2L7s=,iv:3XK65gywr47Q7jD7u0mihDFyEvBT2m624V+Nz7mx7nU=,tag:ffc/fGEEOSkkUYy8E3BK1w==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:PoDS4v6sXK/rQKyovYTnPTwCxGkL0dJH20L7eTQgg7DFHpKHZvfxHmJMK0MBKuFxxRhIxYcyk7gmUksLO5rrjny1YG+YUr7pLg==,iv:wXiklWRm+APQk00iVytI4L4X1hNxqDAN/7uXdLlQ784=,tag:NMrP8p2PrpPpFkqpHSv+RA==,type:str]
    OPENROUTER_MODEL: ENC[AES256_GCM,data:LQ/Wm/hxeD3s3snT2vnQ7xmYwMlfOwe6Z3l9,iv:soZuGhiwl1+c+QVsynx9cOlvyP9diaNqueRowWo7Das=,tag:hMERFgruoKIq9dXtLFIatQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdEs3SEdmbjBBWUFzeGti
            dy9neXExRlhWU0JNeW1SOUtsYmlzQzVkSDJZCkxoUHRsNWxacE5XWUd3WFowNkQv
            aTJWZmhQTDRMZEFTQm5aWWREN25WUjQKLS0tIEFJOTQ4V0lrNTJjbGhDb29kVWVl
            Zm9SWVYwN2lseWtBVWwwa2J4cEF2YW8KpYyNqL27WGNRUhebVOBaARTRKx+GkPG8
            BoprmHQktzxXbIqjNg3fvS/VJ+0I6D+KtPpk3sAXwf2Q2Xm38Cl1Sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WndTUENoWmdnTWtKS1U2
            SlVZVGxXSFgvK2R4c3VqenJGMnBOOXFvWlVNCmsxa0FkWE1Ta3d3QjAxd2xkQmNH
            cUMvanRaYXYwMjJ0R1hGekcveUlSNncKLS0tIDdGTG5PdVcvRUw1TE1LZGVzSVR2
            Smp3UjQzamVzaEZLVTVmdVdBV3FRU0EK+Kz8WVm74VRYSmczPlHW7jARuZDZQsLg
            ZLDQ7ogxco3jQPQtj8UdG+4HGIj5FXYMGcAgu/EmobparFE54ROeiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NGlwRkY1T2s0NEViRUcx
            czNMcVlzQkZqQ0pHTWhaS09MVEVubFFlQ21FClFvc1drbitZRlN6ckI5VEZERGpn
            UFZKNmJXSVdNYWF5emVZcDc2WTZxNDAKLS0tIEg3Zm1vYkZwZkF6RFpQMkVybVpC
            WXNDM2tYaHpjUEh0ZE9PRmF2NGloZHMK+aLtnDB4DowavOpsWEEC77CeiTYSmLCy
            NPx/oKvIvIpfJwQfnEv2DeEPOlctZqJJOiIkHVGVJUyG2Tst4ULwiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T22:18:00Z"
    mac: ENC[AES256_GCM,data:gRpcDoNH5XpjYOr8KXPtvxVyKCzsInfUIkxXjGDs14BTKtrpAmh61MdJ+IkY43yyoK4UVEp3TDNX/mtzm1LLcCg1/RACQZpk2t3DqGn8/LouGqXG1RdjWKf9fvyYDi8I/o3L8nqfGsBZn0L61XDsxXEJn3kNsF/MLcC+md13yZE=,iv:hgLYyClDvIFarFjvEsEwBhGVUTbXCZZVIK46n24gBDo=,tag:xfuaDEBYpRgOcwsCbf3qfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
