apiVersion: v1
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:1YQaKU49hxfHXzfjfkj0jXn54YJjezJ0Oy/P4s/sVYxvAEg3K1c2U31af6ACIHRP5ALV7g5U6/bLfFVH/p9UzpxNkp9FDrh/Rm9Q9RZ/ZOr2MgmLuwAVxjcY4Hy5q0TxizFbv2TfKvzY6RGITerW50rjjtZu2eyNGTiAgSJ/zHlkcW49PUBW27nSTFXl1WWS,iv:ayc0GrNVPpT6AKCrGe8FVWLUVwlmUuppZ+6WuIR3WUw=,tag:BKX5V+PuIXNPsk9lvUmdtA==,type:str]
    ANTHROPIC_MODEL: ENC[AES256_GCM,data:WPbZqM0UoMNIdLyb450ANoidiYVqPJ8JmM8AngC9Hb0=,iv:sropn87uMUllLZkySD7YO9P9uDLH2G/QrBBFTKrWUMw=,tag:Y6Z3Dy69SnuqAKGghYFa6g==,type:str]
    uri: ENC[AES256_GCM,data:j/QBgr11C4UmOC1dOJHM/kkHm9zpUkG9+Ez91E8inZjL86n/sEcTeYc1DfzsviVTpGm/17MbWFs1DcytuEr7hxFWYv9W9b2l2GgpZHYpmuL674v05iXjeAvt9ZvVfYoE,iv:hpVywA0Sin9Dmx6tHw5ldNPwRyundnHLjxBxLOiH5LQ=,tag:JWWMxJim9B9RiwNtqtsDKQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-secrets
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxV1VnTE9ZQXBUa0tFaWJ4
            U0FURUE3N2tuT2tmb1NHRUVtN1NkNmhrR3pvCnNENHl3SVkwTzkzN21MQVlJZnhC
            NlBUS1FKYkhRMjk3dVo0SXQ5c1BxU00KLS0tIC9hUDhweDRHZzNDWlk3R0J5ZWh3
            VnM4UlVtMjlqNTJQOER0d1BGazR0Vm8Kg7aI06oJmO/ZaUMClX/ie/l8p152gFkH
            eF1MH0TcezDXZc5BslDupc6vz0z4NjpH3FkUxsrjF6n2S1U4crFySw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZHhxbGE2QVFveUtUYWFN
            RDhRY3dVeHBxaHNkMTdFam9sN2ZhaGx2aVgwCklYOFQzYnpQblpCQ1VGaWczVmsv
            RDRvdmx0VmF4cE80S2hlZGQ1ZU1SbE0KLS0tIHFob0hKcDgwKzlKN3p3RmVQc3ZV
            Zi9KbVQ5VnpMdGNoeVJERlZKcjArZGcK31x+QW0Df1oAo4ZFEdj5KwrZRoIZHIRJ
            BNwMDwQ5eA6XVqyNQG5n3jYTVao/Y9DVb1a3DkM8WwuKB1HCvOv8Qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UmtjTlZpZnNRZWVDZ1ow
            b2dINnZERVpxRmw4eFZCYlZhcnBtUzl5bEJrCmFkTWMrcGhZbDdOTFVPV2lhYlly
            NkZvcmM4ZlJ0ZCtjeVMvZUJoYzdSaG8KLS0tIGNMZG9sSDNhSm5BMmdYVlU3NVN0
            dVRsVUdxR3pZemY3OG1RbllvMXdYZ0UK+d1cKa2aRipzP48l7e7tcU66jDiS5EBA
            gJkVRkkDa81LtCgKnwDEXV8xB98aFyLrbgZoIxN2DGC62WJG4Qulng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T02:12:25Z"
    mac: ENC[AES256_GCM,data:jwqgs+JQGyB5JHFfK73o6cfZ3ZsXA81CXDH953JbRRRyyyzIIZABlWt/JjQ/JMaYVbluEtMTooI7Q2N53WMKfEVxoRtTeziQ6/JQojQ3r9IMEazkE3DdAtgYG3yCXsIJlSpnJ3tMF3RxoXp8FBywtxWkTcIct0htA6ufTTM5qzU=,iv:RfFN8m08oXnEF8IWlETW9jZU9m2YVjrjIvgCan9G4uw=,tag:4g3QKeB2nGD4ucDbe6Rmfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
