apiVersion: v1
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:10BL4Vhcq6dUQ1cuva5kKKw0gE2XNeGU4Rfy8zlmqE9zICsvzFMqaK+kAkMdxcdadfFC/qvpc0Y0rE0FeHEiKf+03lXoi5zh4w6UWbMBWDWys58pJqxbwnw6W54WeTe4peNTsdxw0Th16hNH/ixnjB3DVVn/R55lHNvBxHXVZbZqJOyM5jqE3EqCQ0W9c/bO,iv:NZKsFGhcMffz8l71ysXMIsa4WYY4R1gnWhotajD9M2Y=,tag:dN9php4sihp5Fi/Mn3GKdQ==,type:str]
    ANTHROPIC_MODEL: ENC[AES256_GCM,data:Bcix/JwHUxWc1sJfj9YkM0a/qDnfl5fP6zo3t7k5q1I=,iv:WZu1gGGyYrzYzr+tWNHCxLBL5sAnp/uGz1BzUU4Ur8Y=,tag:u/IB69ozA+t7SU4HnHsgLA==,type:str]
    uri: ENC[AES256_GCM,data:L2Wov6UXcOFUBxE6ZCuC15mjF4PMutbFoBF3q41SC/jAE82/FIaPz5oHAnaSK8y8Pe4Ph/r2AeSda++eHFAc6XlxNW/o47Ldab3Hh82WZWE=,iv:K5jzfNVVzXm2/xtglpETqGLS62a340eoFkwz9niAt1k=,tag:ZbN13ab0u5m+NxaUiHavwA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-secrets
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbVdVN0Fqbm1hZzVLYUcy
            RHgxclJ1OWFxS3JqcEdId3REem83N3F1NW5RCkMwYlE2RzRRZkMyYXFneCs5WXlw
            SDNEbFpaZ3pnb1gzWDE3TG9FTkx4TFUKLS0tICtrbmk5YmJ6ejFRMzZUaG9naUw1
            MEpYc1VQSFNZeEdFOUdReHN2NTJaTVUKoNEx4qavxI4HZo3HJg2A4cOmFCx/kfwH
            9JQPFXGfDP56UZwHLfMve7FdoO3BgtmQCzY9KvqrjTgx0MA2yEoVQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWnhsalZNK1Ztb2F0S0g5
            djVERXlPSEhWSkVVRHQzeG41Uk45Wkxaa2gwCk1tTjZIb3YvR2taZjE1eEpuTW9k
            Q1dUajdVMmw3UzhLL0RTUkthMVRLSDQKLS0tIDFCL3gvczIvdFpYSlg2K0lmVlZv
            Wi9GU3RKL1Z2eDVFWVkzQlF5Yno2Y00Kck2PgsUe+YGsGEuazhHdvrnCT680KhNq
            YEahstcpHVKXGIHx9bsNyiI4pDlPwgZKBQw9Mcrhrzabc0yiqiaKlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQUtzblhKeUNyUEVwMGov
            Snp5QUhOZ2JUTk9oUUhkZEhrQm1rNjhFRTBzClZLcXh1MS9BS3U4UGQxcUJZSlVs
            THJMZnpjL2U3amV6aklBQXI2cjhsb1UKLS0tIHUwT2dyZ0s2ZjFvaExrb3lMTjBV
            M2oyT0pGdTZuWUF2Tkg0RHZrUUsyQmMK+HGIr4Y/vpLqSmcw/Oaw2b+w0HYFC24W
            m379Vh+aToVDVsRym/kvz8o+Ocl26ARQ5BE0fXUPJi1ZBep6XvN/ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T02:18:02Z"
    mac: ENC[AES256_GCM,data:xn8/vKgcZ1xL8NTbk5TA8CvRaKuHlj6o19QhJ2abI3Ua7AHlRL1mKgeRlGjQRbQKyW+bzasn3V+PCsqYtcyZhqqsR9+TqjW2coVcZw5aCjfeMx1siUdJ34KWO1zVXmzgwKnFp0Frlz3xi2Lm/6V0M8+EB1laXDGU09J23eKHpfM=,iv:mqmECBtZ2A8Hw8z0DNGOF0HNUiH77mXTFFt3Tz1OJRg=,tag:FR6Hqct+VsLnlnWcL9RGlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
