apiVersion: v1
data:
    uri: ENC[AES256_GCM,data:2docKGd4zxCtwoT6iC2QYQzT+5Y139kYJewWZbRTY2Il88NuMZ1tVIcus5czCnbcjZItUgX+dxPuQIM3pX1O9tonCHUWNZDo6WMTsh638e0=,iv:TCI/2rqmRhxbybN69zQr1PahOeBsXkc9mzn1LvaGmDs=,tag:LoxYDbrfTkItq7vWGc2S+A==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-db
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQXQyOHFaMmRWYUdGTkt1
            dm5vb20rRVNwWEpycU5iY2lKVitqS2U1bVRjCktMK0tDQWtIdDJQbDZ0VjNsWTNY
            UnBabTRnQmNvVVlrcHBrZ0dveWZzSEUKLS0tIC9wUDVKU2VBTy9PWG9LckEwTWtW
            VTN1bXpNVW4zQVB2RkdyeEZEcnNhOE0KUC2ypVo/BWxJobiwJxXVkhAyKIV1OLFN
            vJ7OvS9Xs0YGdQMJKgVQ+nNvmzmozssJa6Q8/dw7hPhXRuo92HDk4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZjRLaXVMeVRjeEtmS0tn
            K0M5QVcvdUlWdkV3VFJidDM5a2l2OThjRlNZCmtYaG1vOExMclhXV1crYy9Cckpt
            ajlCcW9hM09UUTJac2R5ZXRVTStjU1UKLS0tIDI2ME0yWFFSZXFCTEtHSHdxRlc4
            aytmb2JJOXptWUptckgvOXhod1MweGcKyk/bfb1IHQZHQH6Vep1ePCRO21hLE0hV
            4qq1Kv/foYm8wa96SGNlN+zBlRupbiJt5kpj9Hu32Q1OO8rYDywdFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZjJaa09PdlIrNUJBV2FZ
            LzFSWEpmQWVkVEluU2hicmdhYUZCbkRyZVZNCi9WRU9RbXFHYWt2cHJCb1lVZ0hP
            V040aVdqODgzMVRabmk0Yk1EWWs1bkEKLS0tIG5JOXpFMkV4MkRXVkZ0SFJJU29E
            OGhyUGk4NlVDU0d4aE1PMlJXTlloMjgK8umw1F9/plnH524J4hs28Q+PabLzrcR/
            wtC0VVh+WodR8XGhLd+yiMABtqpSMip51ffoorE/n0c0PUOE5iAztA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T02:19:56Z"
    mac: ENC[AES256_GCM,data:8cQkWli9qdGWAopoOB2id5w7Xoqg9jE+wo9GFpMGgDwVNmXd3arOmrFd+udSK5fIYofeo4OVOFLHUxUVBtLENbNbYlDLn29FEx/1yqxsVZZCMCrBUARWQzMAKPV9B4fYj2bQmcXYrEH0xfZnbQNF+QLKEnWfWdeeZAvQvYdXY5Q=,iv:O8OkyzIk1tNvFvrN6FKTeQayNN0HXLicz2WCxrjzRGE=,tag:s8BGjCBWBzh68E7UGhLNMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:jayiFJNgYS49s5r5EiDv6OuCrET1NvR8HGpuOBazNwZyT4H/AfvaRGretRbWG0DLBXtzeq5OyjO1dABwNX4tixU+IDHUC4fBen3DvpIDyCDT4v0GeN6nzhfZR33fcWXo5IZPcCCdj1NE9yAFShsEAOQOgFoA2DReedWBv/GTh+qDP1Avhjs0ADd59qbbCaqY,iv:xVgzygKqijjZHUfTN7WNyByCEmb1+gVzB0fztxPvElY=,tag:mp4ZURYyNOGwv2PQs1NmMA==,type:str]
    ANTHROPIC_MODEL: ENC[AES256_GCM,data:LkUk0yT5b1sGr/7Qc68AiFJAsYT+dPmOz8CZdikPFqc=,iv:6p8bAvuxISvBGtM8Yz6fWRXeekbu2AcjraF+SI7OOns=,tag:1Rkv/qrHFBkkdiEb5AfcbA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-secrets
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQXQyOHFaMmRWYUdGTkt1
            dm5vb20rRVNwWEpycU5iY2lKVitqS2U1bVRjCktMK0tDQWtIdDJQbDZ0VjNsWTNY
            UnBabTRnQmNvVVlrcHBrZ0dveWZzSEUKLS0tIC9wUDVKU2VBTy9PWG9LckEwTWtW
            VTN1bXpNVW4zQVB2RkdyeEZEcnNhOE0KUC2ypVo/BWxJobiwJxXVkhAyKIV1OLFN
            vJ7OvS9Xs0YGdQMJKgVQ+nNvmzmozssJa6Q8/dw7hPhXRuo92HDk4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZjRLaXVMeVRjeEtmS0tn
            K0M5QVcvdUlWdkV3VFJidDM5a2l2OThjRlNZCmtYaG1vOExMclhXV1crYy9Cckpt
            ajlCcW9hM09UUTJac2R5ZXRVTStjU1UKLS0tIDI2ME0yWFFSZXFCTEtHSHdxRlc4
            aytmb2JJOXptWUptckgvOXhod1MweGcKyk/bfb1IHQZHQH6Vep1ePCRO21hLE0hV
            4qq1Kv/foYm8wa96SGNlN+zBlRupbiJt5kpj9Hu32Q1OO8rYDywdFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZjJaa09PdlIrNUJBV2FZ
            LzFSWEpmQWVkVEluU2hicmdhYUZCbkRyZVZNCi9WRU9RbXFHYWt2cHJCb1lVZ0hP
            V040aVdqODgzMVRabmk0Yk1EWWs1bkEKLS0tIG5JOXpFMkV4MkRXVkZ0SFJJU29E
            OGhyUGk4NlVDU0d4aE1PMlJXTlloMjgK8umw1F9/plnH524J4hs28Q+PabLzrcR/
            wtC0VVh+WodR8XGhLd+yiMABtqpSMip51ffoorE/n0c0PUOE5iAztA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T02:19:56Z"
    mac: ENC[AES256_GCM,data:8cQkWli9qdGWAopoOB2id5w7Xoqg9jE+wo9GFpMGgDwVNmXd3arOmrFd+udSK5fIYofeo4OVOFLHUxUVBtLENbNbYlDLn29FEx/1yqxsVZZCMCrBUARWQzMAKPV9B4fYj2bQmcXYrEH0xfZnbQNF+QLKEnWfWdeeZAvQvYdXY5Q=,iv:O8OkyzIk1tNvFvrN6FKTeQayNN0HXLicz2WCxrjzRGE=,tag:s8BGjCBWBzh68E7UGhLNMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
