apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-db
    namespace: apps
stringData:
    uri: ENC[AES256_GCM,data:zta721FKY5avYwm0qhpY13n4BJEtzeZPmh2JtKLRoWjuKeUcidE7BMzjdNbbkLcs2nsOdvTRbLiFY0aDNCeDj+zJMRPyhpc=,iv:Y65bK66o1pXBp+iSrd0hAZZbJCIJWw5Un4++J6gfR4A=,tag:5F3mpnAx/MSwwvxbRLlSog==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb1l5NjFHa2Z6Z0diSUlH
            ays3WDFMRVVPSEM0VDNGczNHbi8zZEFteVZnCjFGMWRNL0FPNm1VVytOVEhBcXcv
            dWxkNDFjNGErVlNVckRjc0grbjlJRFkKLS0tICtsbVJyVm1KYkNqSEg2SjdjN2Fj
            cUxsT1VWWGlTRXVqaTdDS3ZRN01xazgKHRdn7wzR79M+KAiO/JKc7Cu79e0sX+kO
            hsnCqtAxU36hGLC3GS0x/veiLxibvuykQyQiwch/lQB40zpfoED9Uw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUTlWUWlnM2hMK2M4Nkdu
            UmRGdktrWkFtNklPSXlZVnhleml4Q3BYb1VNCjBxaW9zY21HLzZKUFUxODF3emNI
            bDhKL3R0Nyt6Q2UyWkZ3b29Na3k2b3cKLS0tIFJLN0ZwUmZWcHhCRkliclYyRVN6
            a2pLV3Jkbi9IMkl0alJZK2xiaHNueGMKB4x9LtS7+nOhlt8UDup0wZ0YE+uDOLT1
            PuR2f+OFbSwbjrgfJJoxyB1vkFR5e+ATn3w7bBBtlPUaYx3YV4u+Sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z2diMFdDV2drcS93ekZJ
            b29OcDZkT2Z2ZzNYTXdZMlhYb2JwSG5zZFJzCllTL2F6OUg1OW9sMXN0WDBmcHZ4
            eU0ybHV1Q0F2TnBlcEVzWHQyeS9Ybk0KLS0tIHFpZWZGV2RJY0cxaHZTaDRuYUtW
            MGZObFZnWkRUcjY3U1FhdzFWK2QraVkKsTa6ZmB9QNZwzDvLuue6nNomOHyUseWM
            JL8445tkjFoEWLuG6LFQRiM5IsCFBKj8g9qeU4HJdQKt8J2F/vCbug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T02:40:45Z"
    mac: ENC[AES256_GCM,data:rmELIMEZbipA0Xy2bvFbu4kix0FOHjY02Z/CeO3ppVHHmHpkVr86KmZBDArO8i4gUJdpF2J7tSA+tw16+3lXvqP46lnXRAxS5drV95uhyTvg6GCc+SW+DGT3MbacvlozfPaPJExpZbPRalW0B9wduWZxgkLWabz6RioCW6j41UY=,iv:zqNHW98SfD5KHJdZo+cpgivLDVja8tWCCI9z710h6tc=,tag:+xsdSx3Xo3hz7DfkPxmbyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:vL08+xd5e6UiSQLgSmjcKBsSiHNvFeq4Zu04GBjyumbDEFbvXGPw3JlO60FTDCUBNsxPkhrKxbu5MMAefkoPxN4b3kCjyWLsHEKFQKI6uCRxHDS5WOcJWVundDMD14UZCFOy6KR/P2a5kJ6nmmUa+hO2XkC25AIegMPaEA0z2JMP0SIwfo/08IGm7tbBjNgd,iv:L4YNtXrsLvwJkqTZV1GrNxA5XQkTpRcTc6UdnSeB7/k=,tag:h7iLjk/TqsdM+PNwmtN61A==,type:str]
    ANTHROPIC_MODEL: ENC[AES256_GCM,data:69b3BobvtnrFDDCPCYvZDiiOlAPEFRHYwyVD6ZISwkk=,iv:gWP9vNGSIPlprlKdoPzz3ia1S1QRdXXlDsmGhzJIvdI=,tag:m7j0VnZux2qL+DQv+/VtXQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-secrets
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb1l5NjFHa2Z6Z0diSUlH
            ays3WDFMRVVPSEM0VDNGczNHbi8zZEFteVZnCjFGMWRNL0FPNm1VVytOVEhBcXcv
            dWxkNDFjNGErVlNVckRjc0grbjlJRFkKLS0tICtsbVJyVm1KYkNqSEg2SjdjN2Fj
            cUxsT1VWWGlTRXVqaTdDS3ZRN01xazgKHRdn7wzR79M+KAiO/JKc7Cu79e0sX+kO
            hsnCqtAxU36hGLC3GS0x/veiLxibvuykQyQiwch/lQB40zpfoED9Uw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUTlWUWlnM2hMK2M4Nkdu
            UmRGdktrWkFtNklPSXlZVnhleml4Q3BYb1VNCjBxaW9zY21HLzZKUFUxODF3emNI
            bDhKL3R0Nyt6Q2UyWkZ3b29Na3k2b3cKLS0tIFJLN0ZwUmZWcHhCRkliclYyRVN6
            a2pLV3Jkbi9IMkl0alJZK2xiaHNueGMKB4x9LtS7+nOhlt8UDup0wZ0YE+uDOLT1
            PuR2f+OFbSwbjrgfJJoxyB1vkFR5e+ATn3w7bBBtlPUaYx3YV4u+Sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z2diMFdDV2drcS93ekZJ
            b29OcDZkT2Z2ZzNYTXdZMlhYb2JwSG5zZFJzCllTL2F6OUg1OW9sMXN0WDBmcHZ4
            eU0ybHV1Q0F2TnBlcEVzWHQyeS9Ybk0KLS0tIHFpZWZGV2RJY0cxaHZTaDRuYUtW
            MGZObFZnWkRUcjY3U1FhdzFWK2QraVkKsTa6ZmB9QNZwzDvLuue6nNomOHyUseWM
            JL8445tkjFoEWLuG6LFQRiM5IsCFBKj8g9qeU4HJdQKt8J2F/vCbug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T02:40:45Z"
    mac: ENC[AES256_GCM,data:rmELIMEZbipA0Xy2bvFbu4kix0FOHjY02Z/CeO3ppVHHmHpkVr86KmZBDArO8i4gUJdpF2J7tSA+tw16+3lXvqP46lnXRAxS5drV95uhyTvg6GCc+SW+DGT3MbacvlozfPaPJExpZbPRalW0B9wduWZxgkLWabz6RioCW6j41UY=,iv:zqNHW98SfD5KHJdZo+cpgivLDVja8tWCCI9z710h6tc=,tag:+xsdSx3Xo3hz7DfkPxmbyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
