apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-db
    namespace: apps
stringData:
    uri: ENC[AES256_GCM,data:737djLIy+vwLiHSdBNF9hhDaHtCkQXafDXFd66ZJ7pCZ8q64vaI5bjiQtVsTv6KqO8vVsLPmBIsDMjzSyh7cEYv7b8pi6NI=,iv:omFcduy2n3HrGvIn2IqothTcMGS/lX3wY7FehGVC2w0=,tag:vrNgOIBXw1Pi6lz9kcGAqw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTlQ5RE1JK0VLZW1VUk8r
            N0NlNGpkNEZDWVloVVNQT2YwaVlWL002SFJnCnFvdk9DVzYrMEJWQlNicWpFaWR2
            QUhTWTMvN014QlVrbjI3ZHgxUGRoWTQKLS0tIHZjcUF4L0dBaVozS2JkNndTWHUv
            WUlZNExySzJCOFprVWRaUXhNKytoWFEKq3MmLxqbAb6AMg3hPJgtdkJT/Yp96zKH
            oGAdXzgWMklT8zR04YaLUhu9Nr7XO3uKZ0JXIxvZLzFP7/wENRupFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSWltdStzVzg0c2JBU2Ez
            bVB2NXY1c2JhT3BDNjUzaUNhaFp4amlhcm1FCjl1SmwwRG1yRkkvLy9PS1dWbTZN
            dlNWQUwvaUlxRDcvQWRNUkpCU0ZLb0kKLS0tIGZCY3FRTWZGWjZtaEdoSjBjRjVo
            TlVTRnU0SVpweTV6cEMvUlV1bWJ6N3MKyPQB8Y3hLT3JlqgZgejFxvKf4nTug5Hn
            +uXL7LHp98UU9R5P0BSdL1T/J1HuRVM1JFXv4gWwBSN4Bl/B1gD8vw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZlRQQ2JNeFZ6dHQ1dWNB
            T2NPVU0rTkt6UWYvUnBBa0cvQnVqTWV2MzBRCktBVkRXZ0prcVFHSnJLd01LWjdT
            ZXNuUGEzclBpNHNsVEhsL1BGWnBtQXcKLS0tIFVrZmpPQlVuRS9TK3FFdEJGWDkx
            SG5wTkE4d1dBbEVLL0VqZjY4NGVqdjgKJNTbK/wMfoCEwjp86gDwwdzeWd+cUJv7
            EyWQ62y8tH6ghNES2N/8lO6Dy0c1wjqMz6Icv6x3YgueCMqsePVuIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T16:23:58Z"
    mac: ENC[AES256_GCM,data:KCgIrsym9cIFHgaWKLB+8LCH/pdV+Q9K8LrNkil8LdxdrS8R2Pph3loFnALeUleZIUvCXFdEaW4IMRB6/jXMTMuH1KJXsjHjWNNSgS+g+5IhF3/2Ml+VQZ3WfCxBzIYTKxD8lgUso1gB1KArpj8OFyoRZLo1FLS13oG0HXMusEw=,iv:0ytN8Nds9cnOBcrifWkkKJbLdWR7p8arQLptROq07xM=,tag:tLc0IUPHWTT15atn0zpVtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-secrets
    namespace: apps
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:b0QWmdJ5jjCEym4kVpl/sv6v/mPWP2pvbDf4uhPA4aH+85YvBoxk4RsMp/s=,iv:XZu+NbyM0XzE7wdTcAOengl6ou61/uLNlCDin5zOD7E=,tag:hdDiVfOJEXPMuObIQ0M3rg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTlQ5RE1JK0VLZW1VUk8r
            N0NlNGpkNEZDWVloVVNQT2YwaVlWL002SFJnCnFvdk9DVzYrMEJWQlNicWpFaWR2
            QUhTWTMvN014QlVrbjI3ZHgxUGRoWTQKLS0tIHZjcUF4L0dBaVozS2JkNndTWHUv
            WUlZNExySzJCOFprVWRaUXhNKytoWFEKq3MmLxqbAb6AMg3hPJgtdkJT/Yp96zKH
            oGAdXzgWMklT8zR04YaLUhu9Nr7XO3uKZ0JXIxvZLzFP7/wENRupFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSWltdStzVzg0c2JBU2Ez
            bVB2NXY1c2JhT3BDNjUzaUNhaFp4amlhcm1FCjl1SmwwRG1yRkkvLy9PS1dWbTZN
            dlNWQUwvaUlxRDcvQWRNUkpCU0ZLb0kKLS0tIGZCY3FRTWZGWjZtaEdoSjBjRjVo
            TlVTRnU0SVpweTV6cEMvUlV1bWJ6N3MKyPQB8Y3hLT3JlqgZgejFxvKf4nTug5Hn
            +uXL7LHp98UU9R5P0BSdL1T/J1HuRVM1JFXv4gWwBSN4Bl/B1gD8vw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZlRQQ2JNeFZ6dHQ1dWNB
            T2NPVU0rTkt6UWYvUnBBa0cvQnVqTWV2MzBRCktBVkRXZ0prcVFHSnJLd01LWjdT
            ZXNuUGEzclBpNHNsVEhsL1BGWnBtQXcKLS0tIFVrZmpPQlVuRS9TK3FFdEJGWDkx
            SG5wTkE4d1dBbEVLL0VqZjY4NGVqdjgKJNTbK/wMfoCEwjp86gDwwdzeWd+cUJv7
            EyWQ62y8tH6ghNES2N/8lO6Dy0c1wjqMz6Icv6x3YgueCMqsePVuIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T16:23:58Z"
    mac: ENC[AES256_GCM,data:KCgIrsym9cIFHgaWKLB+8LCH/pdV+Q9K8LrNkil8LdxdrS8R2Pph3loFnALeUleZIUvCXFdEaW4IMRB6/jXMTMuH1KJXsjHjWNNSgS+g+5IhF3/2Ml+VQZ3WfCxBzIYTKxD8lgUso1gB1KArpj8OFyoRZLo1FLS13oG0HXMusEw=,iv:0ytN8Nds9cnOBcrifWkkKJbLdWR7p8arQLptROq07xM=,tag:tLc0IUPHWTT15atn0zpVtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
