apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-db
    namespace: apps
stringData:
    uri: ENC[AES256_GCM,data:EPFSwQValLJIQHyK4aYXTQKP2Q7W8gaWgji4ribemIUk3IhUtJpKPXbBUGaETskxS212B6aaKc/lEnzFYgIXDhzan6nDbcU=,iv:gRP8DUksmgWyOhrEqFSISEaeYjnAVrIKwGCpIbUv+GQ=,tag:NH7ipSpC22SBWz6/ViPeBg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR3FQRSt3UTJuVWVWNk1z
            RHRIRkcvQ0lKOFNDUnRydldTZFB3aWFuNkEwCkNYcC9JeDltWDNPclJrRGRuRWRx
            Rk9od2F2RXhmNjY2WiswcGdGSTF5QmsKLS0tIFRmVFZNY2huT2o2RTlDYm4vL3Ir
            ZGNTemZhaFF5R1BFaFRQU3hNeTAzczQKbpAs34AZaAJ98K1dM9NOyvZ62JPdS16L
            ohocGSCGDqozmk6YYfcZalvRt6IDtMNhO45xMCXD+hXDQbf5dvFFFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS1BQaDlLOWswbURUbUVK
            ZXFaay93SDBJb1oxendUWExEdEwya3lOWFdrClpVNENFUTR4MFkwamxjWktzYlhq
            WW1xSkdsUExQV2srTGhYTWE0SlkyVmMKLS0tIG9XV3d4NW12bGxYZzlUak5GYmtu
            Ykl2ZFkrMzdsUEJDckRoMGhmUDhtN2sKCecQTXEtfVGOvaEtcvEx+I4UpdpC/Q/g
            khtuDUOtryGzQlrT32nLeZgzjhm4EYrjSIqwQRDAbkocZjmYK8VpFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwenQyalRNRC9TSjUwYUQ1
            UmhHM2tBSmRueFRYWmRXbTRqb3FlNHVINUJVCnhIdVJsenFNMXpQZnlzUXNRa2h3
            dC9yMkRCVGNaSXJZWmdMQU9ZbGh4L2sKLS0tIG1hektkOFpSc2F4a2Y2QXI2YXBm
            VnZVbm8vQ01kMkFPZ3I2Q0ozWkZ5RXMKUh7ft6IafDmFdOwf0A6mbupPEpwTvxO2
            fxc/jt1Mm0TIs90aYvzMna/991Km/rQOdIND1KTXzrjnOG/LJnfVlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T03:15:36Z"
    mac: ENC[AES256_GCM,data:5NAUxLW8gHlFK4HXnDA/f8o8y5TNV15WHUgbTT96px8TODSG5txqgAPMA04ARPEhK4EDJbdi4rioAsqknI5E85sW1dznOCUp0gfIbrW28h5vyUAjZk1GIdrxdQY5gp/jn23d+t60M5KKAcbyJ9u46k6xqlacl91Dlf/zw9JJRwc=,iv:C0kGqUDEooQkAqWYaXkN7yH+CMZwxDWTj0TrQTTePh4=,tag:V43AzCoZNlx3NlPKCieIZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:PUXL15Qd8qdKLYb+1DGUwJ5hu8aXUGf2omgPde5xwKmYg+PGfIlvVqYU3fK9ZnittI92UTOoFavy4EAMx9/I0Omf9tPnU5fIzGsDXKqBrrnV9KK4GbLtPADOI3w/bSAOpF/PTkj/OWCAK9M30j7dRxbQMYY7Ms9G8aju/RS8Jfz1rPf3gwv6ZhhiiNrNWcZs,iv:cs7bkSL+PTdgfvim/hzCYgYfkr9ZFSrNWDwH4YF/+lc=,tag:oUP7mYTuXdRi4R1XkajQzQ==,type:str]
    ANTHROPIC_MODEL: ENC[AES256_GCM,data:jKgqHjKAgSx7ck2/jTsksBKUFUlj0Jqqk7icEmNX+1A=,iv:kXBUYiHkj+HVINlSTfK3UUT0MEe2iDvQaXVgSHWe8pg=,tag:eASMJHlF6NVNIw3rZI6w+A==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:pT2/EJVM8IAgYWzR0oif94riJza2EXKRMD8PtY/AL9zlkTo6Yf+xeGE9whzEv3pbpsQXzQSU3JvA7RhV,iv:K7aVnI20Sbr1fgnIodDX2YVKpYi6ldGFUlID4P/2p28=,tag:lMh9BUICZiNif12tbzhqHQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-secrets
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR3FQRSt3UTJuVWVWNk1z
            RHRIRkcvQ0lKOFNDUnRydldTZFB3aWFuNkEwCkNYcC9JeDltWDNPclJrRGRuRWRx
            Rk9od2F2RXhmNjY2WiswcGdGSTF5QmsKLS0tIFRmVFZNY2huT2o2RTlDYm4vL3Ir
            ZGNTemZhaFF5R1BFaFRQU3hNeTAzczQKbpAs34AZaAJ98K1dM9NOyvZ62JPdS16L
            ohocGSCGDqozmk6YYfcZalvRt6IDtMNhO45xMCXD+hXDQbf5dvFFFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS1BQaDlLOWswbURUbUVK
            ZXFaay93SDBJb1oxendUWExEdEwya3lOWFdrClpVNENFUTR4MFkwamxjWktzYlhq
            WW1xSkdsUExQV2srTGhYTWE0SlkyVmMKLS0tIG9XV3d4NW12bGxYZzlUak5GYmtu
            Ykl2ZFkrMzdsUEJDckRoMGhmUDhtN2sKCecQTXEtfVGOvaEtcvEx+I4UpdpC/Q/g
            khtuDUOtryGzQlrT32nLeZgzjhm4EYrjSIqwQRDAbkocZjmYK8VpFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwenQyalRNRC9TSjUwYUQ1
            UmhHM2tBSmRueFRYWmRXbTRqb3FlNHVINUJVCnhIdVJsenFNMXpQZnlzUXNRa2h3
            dC9yMkRCVGNaSXJZWmdMQU9ZbGh4L2sKLS0tIG1hektkOFpSc2F4a2Y2QXI2YXBm
            VnZVbm8vQ01kMkFPZ3I2Q0ozWkZ5RXMKUh7ft6IafDmFdOwf0A6mbupPEpwTvxO2
            fxc/jt1Mm0TIs90aYvzMna/991Km/rQOdIND1KTXzrjnOG/LJnfVlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T03:15:36Z"
    mac: ENC[AES256_GCM,data:5NAUxLW8gHlFK4HXnDA/f8o8y5TNV15WHUgbTT96px8TODSG5txqgAPMA04ARPEhK4EDJbdi4rioAsqknI5E85sW1dznOCUp0gfIbrW28h5vyUAjZk1GIdrxdQY5gp/jn23d+t60M5KKAcbyJ9u46k6xqlacl91Dlf/zw9JJRwc=,iv:C0kGqUDEooQkAqWYaXkN7yH+CMZwxDWTj0TrQTTePh4=,tag:V43AzCoZNlx3NlPKCieIZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
