apiVersion: v1
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:l/Skrzleou9JuOpssYaRs1g3ETj3NuRig3M3e+S5xWI2g7n18GTZkNR0aZUWLasXx2CRbqQs7H+H83Ec05qdh6P+cOjGftQ8A8FFpuocGnrumPsSCxW6msQ/QWXk/il0eXcwJisJ7Jt03sJ0tl6+blUZcUrJAW8YdA0kX/wJVufb5Ll9956w9/hxo4bAo/R2,iv:qpFrX7E/oMGL4lly9VrbycCAXydJU97j8ETGYkEwJZU=,tag:5WR3cGb1vEr6DkLtTxOekA==,type:str]
    ANTHROPIC_MODEL: ENC[AES256_GCM,data:xxCxOO+czWkfjnkYtyRX9ASMJtJFvr4Uk6SqvlL2DKA=,iv:IDQvvMbMb0BsBS2iXpW/d6FNUNvJsi+8UlkdOaWvJvI=,tag:FWqspNBPUkS+4jHH5V9cwg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-secrets
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY1dUaE5XcXpESTBRVFJQ
            MzNZb0taQWJQM08xNVdPM1dQT1JBRHNmdVFvCjJxM0VweXJCV3V4RUFSS0RuMmFO
            OVZ6NzBmZXUxZ2kwWnZXV1J3YXd5d2sKLS0tIGtDM0NYZS96bGFMVlY0aWtMbHhI
            SVRMWld2bk92VFNROXpnWEgyZjhkbmMKTo3R7oQ+QEauIbxMd/3tmVIYf4DocZP5
            nLmE+Nflk0Nu8j4opFdp/ZFhEuHC6j06gWzpyAHCk1fA/R/fZW8eSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QVVBUFZDeGQxdVBUYTFZ
            YmFGblQzNUFZL01mamVYMUowQk5tQ2R1ZEdzCmw3cmtlS3VHamNRMDY3dWVVdlZv
            YkxBVkg1SUE4c09BTTduWWdOOGZUU1UKLS0tIGdaMWd0eTVWOEtBelRXU2NERXgr
            N2lJTHFhUlVJOHY0b3lRWGpxa01OaTgKYRTxKmby8Rb3+fE1j+3DTAw8IS3qTl19
            oexCdeBEFGMj9IK263S+h9B/bCoqnLy1LhAuCzoqV53oGjJuWjkLLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Wkg2c0MzcGxCRG55bmZu
            V3VSUHhlM2tvTE9WRG1EZzc3WVdmd1ZXalJRCkFlNk5GTEJYVXAyL1lPWnRFbndJ
            bys2UTROVnozTGhVRVJvejFONzl3TFEKLS0tIG5CWmlhdnJXVzJaSTR4eVRWS2Q4
            d3JBb3haZys4ZDZLZmtVNDl4MnZFcWMKRtfGVBQRPVY+J26LjEzM5wzwYl0HIQhJ
            NNep8ac+l3n4y8UXIvrGcEvfozLoeKQPXmqFtGutRU33rxyN02RT4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T23:57:51Z"
    mac: ENC[AES256_GCM,data:pK5G9PXf8rxfbLPXc0ya05MydFbyhv3yu/bf3zRFMITcnFYf+0Nt4a1fzgin+z/jOoH2BwjqFg78tNHB0orrHODiY/H9xWfuog8eEki+nAJ2HIpbGYQwIkqfu/VbPfWSUKAv2HbgIHekugzr1gnrJQZc3ChO7ZbeRTZt44QsSx4=,iv:tOug2/wur9BKyKf7EeAOr2O0ySCjShARhuov5wR3iSM=,tag:LCk53xvEpLEFWVcAR0bcHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
