apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-db
    namespace: apps
stringData:
    uri: ENC[AES256_GCM,data:ELjSJu8qB6gjqRz0ycWDLMINO9jmgp1keF4vVIfljLLVdBDlL3sf7W/iGFWsCuDkvCFhGhHNOWW84kJDU9O8WhkhbpvigGO7Zv6eNqRBrY0=,iv:28VB0acta/THK1bhwpir28Dz0ZYpqm/g1nlkwqkSr6g=,tag:oCbreJT3T5EFTuRW/SuhsQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUVVEOUcrVWx1ZlBFcVNw
            MFArcGJvRE1taXRjVllRMFY3WjREK0JHblMwCk82MSt6eXVnck92TTBQSU95MVpr
            WkdLUkc1L0RsVXA0UWhkN2FMM0lkMkUKLS0tIEZ4akF2cDV1Rm9WcE1yVVFnRlNH
            clB6S0tIZVdOY1FZYjJWci9YV3cwQmcKq/5iId9cdFHPgIQbIkbsq2jTlANCvPRA
            I0raeScvECdXz4i9GuyqVVES6Dq0iH8IdJzA5yr+ysSIoJKbJLJKEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cVovQ0FGVm1udUxWdWhy
            UmdITnVUaDI3VnN5VDJUbkJPTGJsVnNwdWpFCkZKNFBzSXZFOFpnVW9NSCt1OGww
            Z01URU42bGc5VThiRmR0VDB1aGdZWXMKLS0tIHJsdWw5VzBtcFU0RkxDdjBBZDk4
            ajQ2RExFNFkxVWRUQ3lIZ2UyZVJFZ00KJSl9Rzq4EstFAY1naBa9ij2XJK/K2YxJ
            HbEY0yo9KVOzbwT96S0dR4Q9PbzWN2MiG2hyCfsMcU+wQLryl/Hl1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMVZ4V0NOU0R3RVZrVFE5
            dkdudmFhNXc3NDIrUit2ZHNVREJTVk82NDAwCkJEZ25DWVJ4dzRlS0R1aWJkRVQ5
            RHJwSFFiWGY0cVprSGpPU2E5TEZUSmMKLS0tIE94RE9VbGsraVZSNEZzUWwzaHdy
            OXhZYWFIaVVRbDBJQy9kOVFmNGhUTW8KFx5wG/2cZy9A1zZAJAyL93ESn0Pt704R
            /uP1NzDBAflcDjQr+XiN13R6bsx8bIfzakT0k6LS13EqE7KvnkPIrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T02:20:57Z"
    mac: ENC[AES256_GCM,data:jjNAxkDTwTT9ZHfZnYfBHcYBlBaftWHdDM2DGXHZzeWe/4ANIu1yRzAeXEwjan9CjYysB2v5Wr7ONxvr7RXM+3yZb59XGVMM3sME0SNralq/nNNLu4okWjAay81VNLhU0gNNYBKZBtklG7oOKYogA0IdV3qx5zGVHnnOJKvQLqA=,iv:hcqxUOXar04UZtbBpJDQwUb/ocIrJJzAff6MALQz8LA=,tag:cP5HjlK8VMCW9PQTxAqu4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:rRSrvK1PM4vhKsWg5AnQkUzpEQziyIOV7QF9NyME8+LAQ9BXqlnVi4QgDIeOYhRsT10vGjzd9/yOXhgs9EeYhgherEJDwd6dpKUny4h93hW4aerk2u8EPoq0d3cJiIu/lRM+Y3MoKlyn/ONYjkXzrDSMQI53ynePoIiL961fyP13KCrLpHDDrcPw981cBO3y,iv:kMtC0szX+wePC5VvZQPHV3Mx1zW49jFatxIWHKXCyHU=,tag:3Kou84h/nTJzsF/MJkf/fg==,type:str]
    ANTHROPIC_MODEL: ENC[AES256_GCM,data:z7Ier90lf7pmvhvNFrUez2m0ZzEWAqSy0T2MQ73+7tc=,iv:yY6vboSV5IKDBnwnxQTZGhwqE100JlL4c+IXH6oQQ8I=,tag:+bPomp9yhN2HG8bJdufgSQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-secrets
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUVVEOUcrVWx1ZlBFcVNw
            MFArcGJvRE1taXRjVllRMFY3WjREK0JHblMwCk82MSt6eXVnck92TTBQSU95MVpr
            WkdLUkc1L0RsVXA0UWhkN2FMM0lkMkUKLS0tIEZ4akF2cDV1Rm9WcE1yVVFnRlNH
            clB6S0tIZVdOY1FZYjJWci9YV3cwQmcKq/5iId9cdFHPgIQbIkbsq2jTlANCvPRA
            I0raeScvECdXz4i9GuyqVVES6Dq0iH8IdJzA5yr+ysSIoJKbJLJKEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cVovQ0FGVm1udUxWdWhy
            UmdITnVUaDI3VnN5VDJUbkJPTGJsVnNwdWpFCkZKNFBzSXZFOFpnVW9NSCt1OGww
            Z01URU42bGc5VThiRmR0VDB1aGdZWXMKLS0tIHJsdWw5VzBtcFU0RkxDdjBBZDk4
            ajQ2RExFNFkxVWRUQ3lIZ2UyZVJFZ00KJSl9Rzq4EstFAY1naBa9ij2XJK/K2YxJ
            HbEY0yo9KVOzbwT96S0dR4Q9PbzWN2MiG2hyCfsMcU+wQLryl/Hl1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMVZ4V0NOU0R3RVZrVFE5
            dkdudmFhNXc3NDIrUit2ZHNVREJTVk82NDAwCkJEZ25DWVJ4dzRlS0R1aWJkRVQ5
            RHJwSFFiWGY0cVprSGpPU2E5TEZUSmMKLS0tIE94RE9VbGsraVZSNEZzUWwzaHdy
            OXhZYWFIaVVRbDBJQy9kOVFmNGhUTW8KFx5wG/2cZy9A1zZAJAyL93ESn0Pt704R
            /uP1NzDBAflcDjQr+XiN13R6bsx8bIfzakT0k6LS13EqE7KvnkPIrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T02:20:57Z"
    mac: ENC[AES256_GCM,data:jjNAxkDTwTT9ZHfZnYfBHcYBlBaftWHdDM2DGXHZzeWe/4ANIu1yRzAeXEwjan9CjYysB2v5Wr7ONxvr7RXM+3yZb59XGVMM3sME0SNralq/nNNLu4okWjAay81VNLhU0gNNYBKZBtklG7oOKYogA0IdV3qx5zGVHnnOJKvQLqA=,iv:hcqxUOXar04UZtbBpJDQwUb/ocIrJJzAff6MALQz8LA=,tag:cP5HjlK8VMCW9PQTxAqu4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
