apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-db
    namespace: apps
stringData:
    uri: ENC[AES256_GCM,data:NiaE50AXUBV1peRYM4XDfKtsjY267CCc4me4dZCBfE4xbNE/mW2ciaBKg60bVoa1ZlI482mPXoiIInNhsIsYkSpIntUPmC0=,iv:uuSItm2VP6s1L2K2ROTUQ8rLRKMB6MEhMH/6w7RYX5U=,tag:o77o7mJsX0Sty2V36ZS9qQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RWRxM1hvZVBEU1FqV3lF
            aThWajBxK3JpOHhIYy95MDhTTjRITVNaVGowCmdKQjZMRjZUSXZvVjZDVXVIelc1
            M1JkTEIwTjhrQTFZeVRiNHNrcjBjQzAKLS0tICsybngwcThDbi9TZW1QK2ZXTlo4
            NTBKVCthUHRySHBHaUdNQWh1S1czWmsKA1M/lW+jQe1E43hw5vfi4ExsOPrZS5+q
            jKbsY0slPV2mrh90WWOsyLJc2g3w3QKOBOZuJvRlEzndw2SFzFSjYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMUN3TW9oWTBWUyt4ZUl2
            S3llNzdHM0tkVmVNeEtiais2U3BERnZqMHl3CjR1VDI3a0lwNnNwU2Z6b0k3RHJP
            Y2xkRSsyTy9WVi9zTVdTU2gremZkYncKLS0tIHpzalY3WlNzTnVIYXRBMCs3NzNX
            NXdLTWd4WTluMmlsZksycytPZzhabWMKZCLtB4fnvQpLRjfEPmN5vfPS12nBwYbx
            z5pcYeNr90+eF5a9gC9aboyeoJ5qZ9EoiIlYAj2n567H09U7CKBNdA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMb3RyZWpMTCtzRjZ4SW55
            VUcxMTV3OHoyTWRIUzhoeE9EN2hSeUdBUVVjClN0Wk1HT0Npdkg5cGVKTlJycFRM
            bmJjMUUxaUEwSEp4MW9vbUJmVU1UQTgKLS0tIDdyUDRVejJkQmlYOW5rY3ZVWkQz
            NnFvQnJGbzhYQzJFNHlaNzhSYmRBYm8KkeGYC5psneKBWrnZrUBe0s8ZWmGbQWNT
            QbbqDCqV6XsbDXzNPluYNbUNJX2nXdDyXhcMAF07lY8yytURJLN+VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T15:09:28Z"
    mac: ENC[AES256_GCM,data:YaR09nsf+sPBU3ToyTFoXMBbx49R8CaShsjV3YqZZbHxP1frDnqYbqI6EUtMnGvtw9fYACMINP39yUZO446HzXuNI+ne7CaZpiG16EztzIbQgroCXheq19BitXb/VSM2KUk7muIAGoChyiKaFZIAzLBYIQ5pvlExxC0rXEsHRGs=,iv:OZZ4h+JDUwTBY1BcVjtwJyZNAmSPBmdQ4xPSyXjEuPU=,tag:wbRaOZm7K+ee4/8/CrHOOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: linkwarden-secrets
    namespace: apps
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:q0/8wWv5hxDziyu1MwQsEJo89Il/tcqYOooR2xFuidwEh+ZKwOMcwkh4lIU=,iv:Ml+d3aVE875Cfs9d4cTZ8YNWuXCPNfvvJYHYOrKnkis=,tag:RvmlmHIR8hEVVw9UrxUnpg==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:O8R7utiq2sTVeX8Jb3cXdNHYWxE0Sva2mKQ3Ky7cd+ai0gSWe2VAbbMWv+5MBTHcDXoNMPQaerbOgaVd3njDRzOAm5u96MoG0g==,iv:gFSSGDEJTcCDuMB+NhVYZK1opllxj9MCejafk6y5U5M=,tag:gHgOgpwwTmLdwB9HKVBa5Q==,type:str]
    OPENROUTER_MODEL: ENC[AES256_GCM,data:HF4oyiZhqWE2jtXy/ZXkg40aa8oIVz0Hw+rnh/gDX3s=,iv:ecCXhA5e/lxikDdAXZ/R95gdfhCfnXEtlkfLV4kF4aY=,tag:tjw8xbXIx8iEBk7pKMfhtg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RWRxM1hvZVBEU1FqV3lF
            aThWajBxK3JpOHhIYy95MDhTTjRITVNaVGowCmdKQjZMRjZUSXZvVjZDVXVIelc1
            M1JkTEIwTjhrQTFZeVRiNHNrcjBjQzAKLS0tICsybngwcThDbi9TZW1QK2ZXTlo4
            NTBKVCthUHRySHBHaUdNQWh1S1czWmsKA1M/lW+jQe1E43hw5vfi4ExsOPrZS5+q
            jKbsY0slPV2mrh90WWOsyLJc2g3w3QKOBOZuJvRlEzndw2SFzFSjYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMUN3TW9oWTBWUyt4ZUl2
            S3llNzdHM0tkVmVNeEtiais2U3BERnZqMHl3CjR1VDI3a0lwNnNwU2Z6b0k3RHJP
            Y2xkRSsyTy9WVi9zTVdTU2gremZkYncKLS0tIHpzalY3WlNzTnVIYXRBMCs3NzNX
            NXdLTWd4WTluMmlsZksycytPZzhabWMKZCLtB4fnvQpLRjfEPmN5vfPS12nBwYbx
            z5pcYeNr90+eF5a9gC9aboyeoJ5qZ9EoiIlYAj2n567H09U7CKBNdA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMb3RyZWpMTCtzRjZ4SW55
            VUcxMTV3OHoyTWRIUzhoeE9EN2hSeUdBUVVjClN0Wk1HT0Npdkg5cGVKTlJycFRM
            bmJjMUUxaUEwSEp4MW9vbUJmVU1UQTgKLS0tIDdyUDRVejJkQmlYOW5rY3ZVWkQz
            NnFvQnJGbzhYQzJFNHlaNzhSYmRBYm8KkeGYC5psneKBWrnZrUBe0s8ZWmGbQWNT
            QbbqDCqV6XsbDXzNPluYNbUNJX2nXdDyXhcMAF07lY8yytURJLN+VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T15:09:28Z"
    mac: ENC[AES256_GCM,data:YaR09nsf+sPBU3ToyTFoXMBbx49R8CaShsjV3YqZZbHxP1frDnqYbqI6EUtMnGvtw9fYACMINP39yUZO446HzXuNI+ne7CaZpiG16EztzIbQgroCXheq19BitXb/VSM2KUk7muIAGoChyiKaFZIAzLBYIQ5pvlExxC0rXEsHRGs=,iv:OZZ4h+JDUwTBY1BcVjtwJyZNAmSPBmdQ4xPSyXjEuPU=,tag:wbRaOZm7K+ee4/8/CrHOOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
