apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ntfy
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: ntfy
  namespace: apps
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/instance: ntfy
      app.kubernetes.io/name: ntfy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/configMaps: 505df480598d6abaafff8f2e3ed77f08610202752ce08b494adcfb37322ef4bf
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: ntfy
        app.kubernetes.io/name: ntfy
    spec:
      automountServiceAccountToken: true
      containers:
        - command:
            - ntfy
            - serve
            - --config
            - /var/lib/ntfy/config.yml
          envFrom:
            - secretRef:
                name: ntfy-secrets
          image: docker.io/binwiederhier/ntfy:v2.14.0@sha256:5a051798d14138c3ecb12c038652558ab6a077e1aceeb867c151cbf5fa8451ef
          imagePullPolicy: IfNotPresent
          name: main
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/ntfy/config.yml
              name: config
              readOnly: true
              subPath: config.yml
            - mountPath: /data
              name: main
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: default
      volumes:
        - configMap:
            items:
              - key: config.yml
                path: config.yml
            name: ntfy
          name: config
        - name: main
          persistentVolumeClaim:
            claimName: ntfy
---
apiVersion: v1
data:
  config.yml: 'attachment-cache-dir: /data/attachments

    attachment-expiry-duration: 3h

    attachment-file-size-limit: 15M

    attachment-total-size-limit: 5G

    auth-default-access: deny-all

    base-url: https://ntfy.josevictor.me

    behind-proxy: true

    cache-file: /data/cache.db

    global-topic-limit: 15000

    listen-http: :80

    log-format: text

    log-level: info

    metrics-listen-http: :9090

    upstream-base-url: https://ntfy.sh

    visitor-attachment-daily-bandwidth-limit: 500M

    visitor-attachment-total-size-limit: 100M

    visitor-email-limit-burst: 16

    visitor-email-limit-replenish: 1h

    visitor-message-daily-limit: 15000

    visitor-request-limit-burst: 60

    visitor-request-limit-replenish: 5s

    visitor-subscription-limit: 30

    web-push-email-address: alerts@josevictor.me

    web-push-file: /data/webpush.db

    web-root: /

    '
kind: ConfigMap
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ntfy
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: ntfy
  namespace: apps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ntfy
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: ntfy
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
    lbipam.cilium.io/ips: 10.10.10.114
    lbipam.cilium.io/sharing-key: ntfy
  labels:
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/service: ntfy
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: ntfy
  namespace: apps
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/name: ntfy
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ntfy
    helm.sh/chart: app-template-4.2.0
    kubenix/module-name: release
    kubenix/module-version: 1.0.0
  name: ntfy
  namespace: apps
spec:
  ingressClassName: cilium
  rules:
    - host: ntfy.josevictor.me
      http:
        paths:
          - backend:
              service:
                name: ntfy
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - ntfy.josevictor.me
      secretName: wildcard-tls
