apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:oJqbztQB0l9tyBOo5JgHgkjXNP66/4PnTSp9H+CBSlXBNsjlnc+Nysu+YH3hSQKVhAvFNZ6GZdik0Zny8hXl/8pzY05baDY=,iv:h01IcIu30AzvT2nawVxaJltWztqmSeZEbpwftsemncc=,tag:4TVLYRLK2JerVkp1+O64zw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:3kHan9JCfP2cp82u4bTEpb371DWmjxDtWhqULFSqcqvO1igomreHzhFewQVu1djbpzIxacRd,iv:OE7AyGKbwfP1eMmv3vUWW4Ye/sDy++o0V3R3K8QYhes=,tag:MnosiYpTcrX3yw8xw4Dwsg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOTR1aWdGSjZSekhFVDNj
            ZGVEOTVSWWE4Mnd1WlA2dmc0c3Y5eE5yOURRCnJXc0pvSFVsajk3MS9TWlFsYU9F
            cFc2NlZzNUs2bHh2NTgzZEdBdFRzYncKLS0tIGQ4aHNTU2tyaVVUdk1qYmV0cWxL
            VDVFMDZkaWloMW5ncnF4T013TXRldW8Kkq0g/h0dE/1FLPi0C4AUr9+wMEvWuDc+
            lOnvHMdWgG7iS/fUAV+ikT5k1ri1Q8EdL91Xw968BeXiIkdpuSOIjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTktIN2o1dVZkWVQ3U3BT
            c1d4dU9RZlBiTDZJQzRueU1ZQm9XSUk0SmtrCkM3aTlCcEZYMTZoZUhSTm9PWmR6
            T3hYZHYwb0JTT2NlSG4zUmdhZExQaWsKLS0tIGNLRW9lb0daVmVDUGNXem5ZZi9X
            eU1MWHgxb3lBYmlzVUlCQXBncXdWSzQKtGA7LhnMdNGMwYDwGvjYaC+C5EhOjYZF
            mtsfeE/+ZTt8V2Tax1COZ7XJRukHJcEtwpXHh0XHSPa8IhgYdymSlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTFlFUzBRUWw2R0dnMG9v
            cGluckZhVjVNemR0L0VPa1FPZ3A2K1FpT0VJCit5eWY0Q0VDSStLcXhJRWswbXZt
            dGh5cUlUQW9pTmI4c09YTWJLcHZVT1EKLS0tIHlQVG9WR0Faa3pyTzY2R1ZLRDRD
            YnhVK1ZoVENzSU9mLzFONnA2UnBDWkEKwhU6kgsAKjQc10VrOKABVjr0OZHz6WUd
            rvCNxTKag44rSGcUNFS1NWFE5c06gRrwHT/d4/0GYNC1W5VKwddzZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T17:41:32Z"
    mac: ENC[AES256_GCM,data:R4lDBVzXVBQRIUZnTnIJ1bwzKfkuxvpS3aHtQ/QSpeDnouL4j4zddUX8zo3Op5g+IUJb+88zTEUCdxrBe/ssht1dTKrCndAu6YlVWeBxmVCPKDiYduQ761zM4HNFpB7yrgEtFBtI/t5g47kTiUSid2paCFETXRrZV4bj+WXLwhI=,iv:wbkvjeAbvJhIX0WjfilKSFSKAdSU2I1rFFw/2yA5O2U=,tag:uNRY/e6UOSe+Ld6+oCgeow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
