apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:PYHounhhSJY2t5ymc1pn2tLz,iv:oHDkuUonB26f/zuk1eEp8rVucWUYrQgUt5KI6HcSBpk=,tag:CZCQVYMCaAQCU8LloAikRw==,type:str]
    AUDIO_STT_ENGINE: ENC[AES256_GCM,data:QgRV8xpU,iv:IwePSJ7Ve0aArlbJeRDpspUK9ghOzod70dLNhnBVF1g=,tag:xRWgwA8BKhYARnBKjRtlng==,type:str]
    AUDIO_STT_MODEL: ENC[AES256_GCM,data:eHWrjx0Ip9NePJ7BM5zmlPG7vp/w6eJRrKGr,iv:0t+8DNzz6doqO9i2RP4l7k3pZkGnS77kXHSvnUcLqfE=,tag:RWKk9h96uoDfmsTB3pxzrw==,type:str]
    AUDIO_STT_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:CPV54ppDnJuvzSFG974AV9udYLdkErqZtB45iA==,iv:M8VYVwxXM+QDUOLWEbWneUrBemMRhYl5TZJDzM9LG64=,tag:tY168rpfQCO6p9jIzhczQA==,type:str]
    AUDIO_STT_OPENAI_API_KEY: ENC[AES256_GCM,data:59EykKmLBN0PEB+vSH7VlZ3m0JYv4qiLHsWs9D8yDH7lZZ9F2JtV4z7WYaT+YR1Ac1pL+8CpfPrbrw/io0nwEYfJh4721wtctQ==,iv:cm+EbWVm+2JuwsgYrWqOBjqwc6U9ttd0LTFbqjIWw5M=,tag:hep3O2P0vvnXf6qlhbJRgA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:/xlFUzRAi9HXlol7syhVWqvhEzhqszC8JC5zGUrP6nNmO/WE4sBp8NOIlUv71HU0UZ07x2uiZD4WmbASBNY1gURoVOmV4Q==,iv:CLmnQhLeRWucFvie1Ame0P1xDPZQZNNevaT2vEJGh34=,tag:h/EaI0hcc4mzqgoAkZoVfg==,type:str]
    ENABLE_IMAGE_GENERATION: ENC[AES256_GCM,data:+5SrNw==,iv:DxwpnNddbm3SrB6OCxYqEbTWPfUyws6/DemcQLRdh/Y=,tag:eyb63KC7r1Yk5FQl5ZRitQ==,type:str]
    ENABLE_RAG: ENC[AES256_GCM,data:HfxSbQ==,iv:SXwJqXz2y9rQcwvDi2fOK9X26K/1eg3eUgyi2c3apMA=,tag:itpZ6NhFZSZRR5FmfXY6xg==,type:str]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:FylaMQ==,iv:G5eCLF2uZqsPDviX1xeIr5lzLbQ5tqmTvoZmT0L2jyo=,tag:oq+ZbO/yn/s6IRUhPhKu5A==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:BifLLg==,iv:hVcqT1JYewKHaceOPNgHJH70q56U6zuUUFs7C3sGELw=,tag:BDDAccOeFSbQ48c+qWflow==,type:str]
    ENABLE_WEB_SEARCH: ENC[AES256_GCM,data:HGifng==,iv:OWOgIGZMwl+TLR9A4h2+DXUn0KZiSwnG+DW35DGnlY4=,tag:+LqghLfkEJzfUfupR9VeDQ==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:aq/a7g==,iv:RvRE7sysHVtpBsSPVExUd1DmDcTjp9m+8PUoG606FOQ=,tag:jaZGY+2+xU2OvZhChkjfug==,type:str]
    ENV: ENC[AES256_GCM,data:l9VAmA==,iv:lIkl8R+gYPhSRIOzEsmbEX2qzUx8WI8OpuC9Qr5p4IM=,tag:TDiIcqV9QRlV6lf7Egqxlg==,type:str]
    IMAGE_GENERATION_ENGINE: ENC[AES256_GCM,data:btSm+Tte,iv:mUGaVpqoF9m2v4E7pqKXaWjqBVLFRDL2rddkjtl1FgQ=,tag:Cc9z+18xD5uuEo/Y1pytbg==,type:str]
    IMAGE_GENERATION_MODEL: ENC[AES256_GCM,data:52JhKx0ky78B8qAPnNuvMJhjk0WQ4QYGXe8AFZk/BXLFY+Cs0A==,iv:zzALoraZhixwS7B61szF8X93Ub0Bka2KqMY+JDLscjY=,tag:q4QPodd02FpKYHTqNyTeqQ==,type:str]
    IMAGES_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:7jswL2fHXDTQdkFkAUpzxPuvIXw7vgbCQ0522w==,iv:YYyrTn+vnOFLtxzojNQUJQ/T6c+wl4u2Ze6KShtJC1c=,tag:awBS6G4cMuJba6GEwOyO2g==,type:str]
    IMAGES_OPENAI_API_KEY: ENC[AES256_GCM,data:JVzPqOBUfBZ/4Z3oNfXsewmtOtybhpVaGI9895lvx6n5c8AxfB+0pbDYLs5LT0KoOh08Io6Hb/02Xhw7KTkfqiIKB9eVzfQmBQ==,iv:XmIt4x+kCEHZbeDPdzVkLLOL1bh4vN+mvByYcsItK4Q=,tag:GWZ8d24qcrbT2ZRK5/BKdw==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:D4y5Yw==,iv:o0upiT3VnJ4G2g5Py2i67Tuab4JSTrSuAx3/k4c9AfA=,tag:xIGucxL9Omz3fB4fiLASww==,type:str]
    PDF_EXTRACT_IMAGES: ENC[AES256_GCM,data:FRj/wA==,iv:NjvzHD+eyTXg2ZRJkjz8lhDbE7hEO/fDvOgkoiwqRQY=,tag:Y4wkobCbYFd+Z69Jh6+DhQ==,type:str]
    RAG_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:ix61zSvVwWmVTyw3WO/GyDMfe0VvEsd1UxY+0A==,iv:KIc0m9yjSHALVBQBiTSrqvE7oiLJFF6PR2k9PFP+M+U=,tag:VxN0sIRE9dgA/Ga08pL3jw==,type:str]
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:mpBSvb2Tj4ZgMLNoTu33TLF5u0dcTZTya/EWNiZbGGog+6wQPjWQfhyw+oJNvUX6xh0+094s2Z7Abe2IfBYXIuBoeKqdXj7gNw==,iv:S9svTPhSkQ0rXv55IH8/gwC6FFnxFFr1t8kl7IP8eyE=,tag:WexUVyweLMN+zQ+iqQPr4g==,type:str]
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS: ENC[AES256_GCM,data:ZZg=,iv:S/GWb/sPy/aaTWCw4WAmqYQgVuIqEDqhcsZM4+4Ut3w=,tag:iJnwtuQQz697EstovlSlEA==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:dXqKP0PZbg==,iv:FxSXh13dEHx5QINeg+3nbU5aUiYoc/lHPGn9SlBXd/o=,tag:+STN2s4+N4LS9nJlTrzRiA==,type:str]
    RAG_WEB_SEARCH_RESULT_COUNT: ENC[AES256_GCM,data:vQ==,iv:j45DY7oXtGCqoCuzLev5g1Rb6LQm5jiFX8Dx0KVtoac=,tag:tidwyslxW47S15fDRu8UMg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:RymFSvwZEqTbRLTTPZ70O67r+iWx1tyu298LdIYoRkLVL8GmDNJizb6/x1WgGBv2nrAM3uNTiQ==,iv:jUSCBkPM19UDoUU6o48eXKBBdIneWxM5lM5sBIp9QrU=,tag:uo1WMQVndckaR5D8CLS66Q==,type:str]
    SEARXNG_QUERY_URL: ENC[AES256_GCM,data:p2X7zpFAsDYCr05SNde2bLjdrXpOl9M1OCLQk7u90e//8FpTBpsKRUm5BM22wWXZhWsBbbWz,iv:nXyDwcjcoWeQLFfiVQ/zfRnH2RVKQEONFvKAKfDk7jU=,tag:qyvPfrme6w09AiRzIf9gkw==,type:str]
    WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:NMVk9puGaA==,iv:E8VazjEr22/309QFDFXQiWQtq/yytbvEnrj/GC+hYQQ=,tag:W8twZfEsDeAE05hISxPJJQ==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:5StTRA==,iv:VNCfq5lXlHf1urLnF1DICBIJM3OrHWDe4MGO0/DlZCI=,tag:HfIXXwSzdqTT5DNDJHD9EA==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:mZfWRke/4flZDobbzMLnfQ==,iv:f0aGRDADZORxkXmXpgILNm912j03lVoKWRDIDM78OZY=,tag:U1veCTVJfNJj1K96+ZL5Dg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYREtrSWdySmJUSEtGVmtm
            TEc3d243Q0Nack5YZEpwNmtPRjBUcWlGS1JJCktIMktWMDRIQXltMGRmZTBDVlA3
            a0tSZnVVaHZ6c3VGWXExL2ZHSVpiTEkKLS0tIEVGc1lvQndSb2UzWi9MdHpnOVFO
            d1NKTlVTNGMzcW9WRHBYSzJOZlYzSW8KBvR2ZwFpa1R3nfiR1PuLjyZbrDivx2D4
            IjPIUndYwKGzdKpZYWZ1fckRZMg1WKJgqlOZjws7mEca9Td2IQdT8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL1JlVm84UkdDN3NYUVVs
            ZEhoRkIydlVVMnd6Y2YwZHIzMGRWcnloa2o0Citwa21ZV3M0ZFVqTENWY2R2clpL
            QnhHNDY3d3hUOG9aOVZUY1V3NS8zTGsKLS0tIFJyaDNlYjFqemZTQ05NT3R2V3l6
            R1NFRCtxY3Nhd3Z4Q2doOXVnUWRmS28KXPOVSFeZlIx8VRaybHiiyMMUTz002Zqs
            Tk9mvYkqaPSrDq6uxQCPQWbLDG+m49H2xpD3OGLdJM7oilmHKyYrCw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUmNUd3F1NWFTV1Z4cXk0
            ZkdLR2hUakFRampNeHYwUWtETGQ1VDJJYmc0CmJOalFuaFBKc3BZaFZCek95Qmgx
            UGpGVDlid2VaM29lYlI4MHFKQVhVZGMKLS0tIEhjVy94YWFOcys1eCtvNjJTRTEy
            Uk5TRHcxMGRQcDdYRzNJQlIraXFnTFUKEhDisvcTD86NR9QicPOjUfs4Xvko05MC
            BzqiO07Ktw5ZqZDpcnExZnpXodWwZ76GyqVxbA/eWmaxNIxFC40zPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T14:51:14Z"
    mac: ENC[AES256_GCM,data:83cxxjHIyPOfB/R4sz0Y1DabrkpCUI56UpH7Ii2nR5hYuVeqk9+gdpbZJmHi0rDU2S/I+DIQ5pIsMxd4fjLPjbDYEhOkpgoGDHMOW7jretkDFNxCZazosDI0m68CR+Lm+OXXPI+xYOmzEU1wJLyuHv97w6nY0pMAoP7H27oPoi8=,iv:3oDDF5KJayOk4pr5YXKlUuKibEueZNmRL51igkXFm0Q=,tag:idH2YRo2hOu7aXkYWHevJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
