apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:kUnIMHp1X4VbL9HtWt2gGxOt5LvQxU8yKWswxt8lW9Yfy3Nj6K4wuTLhOhj+tsj74KktDZMzk9IVuJuQjU5ACVcVN5M5/9w=,iv:W/1+Wl3DnXQJCoMJPaYewPfi4wPaermH3CGXkJpgQIc=,tag:OC3V5vzsTEeGf+EPgB32VQ==,type:str]
    WEBSOCKET_REDIS_URL: ENC[AES256_GCM,data:sLJDFXu73bKm3cYGzZf64AhIsWaw86YjvLza4AV+3E9Ko8LOG0bjUYti5rZ6KXqdbn6E4o3M,iv:kM74CI0pqgbOrBmVcYAA+tWjW5no/8AcNd8YghGXNY4=,tag:cSu85fZGXZSfpZ5YtoaM9g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaVduMm9MTUNVa0JGL2JE
            OWdFclVpZitOdFFJUDZCN3k2a2hIam5XRXdVCmR1T21yUmNadVNEODlYdGxwcnBU
            WDNxbkMzRU52aWcwaDMzMnNteHFPWk0KLS0tIE1oZzlXc2pacnl0Zk90NXNLZTJD
            NHFDR3Z0cDZ6a2hQWDIrT3F5cXRoeHcKTsf+tJLe7XGfw6MAapdopKKRniL9hcvy
            EJyHnBkjWcd1Vij6c4/4hFT4aoIkPG3wOkVNt4fQJr+CJYdXo/Zz/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS2xRUW0xZ2xPMWdqTzBE
            YnMyZnFEZEo3ejdhYnBzdWY1Z3pHbmlYdHgwCkxDMHAxTlFNVWZWbmhsd3M5aFdV
            UmdERnpQMTNXRGpvay9vL0pkUmFsNUkKLS0tICs3eU1VaTF3NzNESW5BUVg3Wmg4
            RW84TWFYVFpFUnRqb2NyNXArTDA4dGMK7Q+pLTRWcIggsPmDQ9uddmeaaU0aVVM+
            /LEXbt5gH/LWQ2tVYkAmjl6Xp7ubR6HJB+C88LsrxwM/u6/T1nfAEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YzVXNmljdURiYVZ3d0ZF
            eTFzdnBoNmdLNGlldVFiaS9tUGJ5VFNoZEd3CnFIWmh5bXdHZWlYbDJTdlVhZTVy
            cnRQN3psMEZSYWp0TTQ5K0hWUEE0NjgKLS0tIHBJVVpkV3l2WVRWazdYTENIQm95
            cDZyT2gzcGhtUGJPcEV6Z29HV0EwcVEKRy+AlB54x16nbtnt9MqheZbR8WBrOsHy
            V+PU/BQqCLj3bmdKe4ZXZgfVgU7KDVo+Ihr/mrYBzR9EUd9YhkDTEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T17:59:04Z"
    mac: ENC[AES256_GCM,data:vEcV69rZ6zGVVwgGAvQekiNN/oa5I/d7dREHtiWiFZDpeCAgu8zsSK5Brrijzh3Qddh3jXwSo7ehwKl92KSqIbuUmZuvkD0IlEar//a21T3jwXdbbVvB6om718JAhzeGoDIyq9I8QjMhC4HhFEhhWF1m1vFad75Dh1QD+3gaq38=,iv:OdRMj+AG2h/e4ngd0PKm6AoRD6DQjVj5RI7sbtV6e9c=,tag:cTM/Dxr40PTwNfVdpG5NtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
