apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:OlLx4EUtuCuXr/3CvjIc906q,iv:sB2KJI3c0ZhBFOEFnildigrzlLryR9cAQTyzK21UdSY=,tag:/Epe9C/2QG0h1/QeRAusgA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:rG+hbzkzRZ5AzfJjouBm9j+yIS5R+Y760BTBhOsfeWosofQhikLGrtybV1ewJJZliQ6+2FjJvV/n1ktTmrK6wHlmVyXNtw==,iv:59Av7kNQCQAzKRlOYCZw0H/1VpipStbxOJskbVq54e0=,tag:AGu0AOV6JQTTHuiM9Z+ACw==,type:str]
    ENABLE_RAG: ENC[AES256_GCM,data:e+GDkQ==,iv:d+VwBXPKZpZo/ylHZntmjvgasgfq5Ak/Au8+ksZ7WkA=,tag:ZdRql33rI37pTjsaBhdu5A==,type:str]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:RxLV3A==,iv:fFkkuqiM5hv3LweOF+pPx5rXELoczJ5Q17ktSJV2paQ=,tag:WQIDBAutVrjhJEfWpew6CA==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:TZNuKA==,iv:DD0BxhYkgTr9f8qmHImgUjdTwqFmuavpbSoZV3oKDI4=,tag:0HEFFyqLIBUBm92QeQ3rMw==,type:str]
    ENABLE_WEB_SEARCH: ENC[AES256_GCM,data:V13/gg==,iv:pj+q4+oXv7j5TWPj8Qbr8ShYMe/CjjtbF62y3ZQQ6RY=,tag:JDEC837HIDc4heH6824k+w==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:HIkk2Q==,iv:u1zDJd96oqpqL7fwfZx3lyFNg8buV7ASE0FhbAzbJrU=,tag:yiuAIMKpJDFCb7GBENJSUw==,type:str]
    ENV: ENC[AES256_GCM,data:cxXoXQ==,iv:pL0bzypeUdUpeUPurBjFPUdzien/4RKUV21GCETUCQA=,tag:1IWl7vuqSBccaPT4l1Ebhg==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:XWUTIw==,iv:uX9x8isnnoO0TsiEUdt8ACOxN6TYTb48MpBePetfpYo=,tag:8YAFB51wPUSLX0RFLmPkZw==,type:str]
    PDF_EXTRACT_IMAGES: ENC[AES256_GCM,data:My4cWw==,iv:8WNHdMQ/2OiKlS/Ha8OwBQRdbYZOOIczEicX2VQMIpA=,tag:LLXGTxbfwfWWuyyagmeuIg==,type:str]
    RAG_EMBEDDING_MODEL: ENC[AES256_GCM,data:Q8IXR1lPE13jlzr55AQLz51W+UlHdvWbysatXp+WjLHEoPoMF3c=,iv:z9C+buXSDXllCFr6mzJVerWJKth2soDgfdj89I992BQ=,tag:FJcKT9Vosr5pz7eV+f7BiQ==,type:str]
    RAG_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:TIm84sk41OAy/ti7doDRf/VO9DurhVThYd+YUA==,iv:p/jkX5c0QBiBVQOjrB4PwvHT/FqSF4Fh01MwYceHrQM=,tag:3L9OHn4uxQFMruj7CPWYbw==,type:str]
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:rBT4v4lxFF+IU5jLjEni+aV5Dfh11c3vc2YX9ujGTHWrlkdqlVXpBU8evv6W5jXL/FBh/yv/zLs8yqFb0kQVTfR7ExsELDwuCg==,iv:lqf8I/pJdAFXgaRkxMj/4x05fqxMANDj7CXpY549V5U=,tag:nKR3H83/X5m06tHDKSb/9Q==,type:str]
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS: ENC[AES256_GCM,data:ST4=,iv:xYYN3ywV4t7PInff6Zr64Hc41ZM/brb/wkVUR3pSBZ4=,tag:ZZwBjs/KGa9lg0IqahD2yQ==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:pPdqVmYyPA==,iv:6hGqiTYOEvI9hJ0oB/Pv3ih5IUf4O+do9p2QHdAcbig=,tag:CcttMPsb709nTeLXOVLwMw==,type:str]
    RAG_WEB_SEARCH_RESULT_COUNT: ENC[AES256_GCM,data:RA==,iv:gP/UQQBV1Vz1Ar3UnRDfZ6JWJOomyj6dYcSdLn5aHhE=,tag:sCoCdFq8gGcEqzHq3J+mQg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:L35ejN3T7gmPiCAVbnPp5pNSl9mp/tABkFvvSYMnQQqq8V+1ixtAYte6PhlZKg5iiog+I8fnWA==,iv:lhNdfy5NYRvP9qjPH1LpcYG69tL2dDM3YEPs14guF0M=,tag:/SybkpC4G7jkFa6EH7eLCg==,type:str]
    SEARXNG_QUERY_URL: ENC[AES256_GCM,data:QsoA7KTF11N09zJTdRkpth4xzonvx/6Wrd+KpalnzsXJqG/4tyiY6En7yd1UUkqgfr/amKyT,iv:OtlFioGrV750vqpUoiOuliWruWd0L0e67Xdc2Nz6m4I=,tag:rDBD70/A0RfDncDE4xD/1w==,type:str]
    WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:O9PRQVPU/w==,iv:5BUU/eJuNNCgYbegxnRrKp6rjwTh8NrKfVRNBrLoyfM=,tag:GfwsCw01LGNHbhgLYt05gg==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:pmH/mw==,iv:ZGPs4n/rkv3Mv94+ZcN4iTd7VYfwmCSQCis/Hxt8ti4=,tag:DYSHCVf/tZF21AJTrUEKmQ==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:1d7d9/y0zsEHapLIrNg4Ng==,iv:IGXK/ZhyVKZsPjEazTriVg7gxakR4nIC8f5W741/cg8=,tag:cZxX+9nEHaM81762cr4TvQ==,type:str]
    WHISPER_MODEL: ENC[AES256_GCM,data:Y84LQyNCCqtgxK1ZcRuME3BYKJbmqV2JWiy2,iv:07xUdsMnYLhZSnALHX7c6LXqIwpJGsUBOq/ibUef7u4=,tag:3QyNFrB5g2rcHi6LFZLaWA==,type:str]
    WHISPER_MODEL_DIR: ENC[AES256_GCM,data:KWW55UyHGjSEpCtOMF9IJX926ipN/kWCpjkxl3PQOvtm6qQB/Mo=,iv:zhJIvm0LhZc0GtIYl5ctnirySrbR8gnTQ7sBltloL00=,tag:6ARloHtmDlnwz+yB7Ya/7g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZXQ5NGxPRHBPY2Z5M01z
            cHhHOFNpeTlBM1l0elM0ZkJZVnBvSE05enhFCkZJb0JPMmpMV0hmdHE2TjhnLzcr
            Z1liVFlXS2U3RTVhemVud3V5TXEyeDAKLS0tIDcwQ0diQ1ZYR2wxYS9SVEVsRG9N
            bjFNdDBJTnhIWnRkWW03UlJTWkYvK3cKkb0ondGyQ3BsC8N85QY9jDSL6pCyWCAP
            2t1f1DddrS5wVBlSrrpqxiY/u3je9UdGlL1mXl9vGEuJhMTIRi5BIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZ1dRMjlWQWNJN0V1S2N0
            NzBrM0NvUVdCY1hUaXpqdXZpYllTbjZpY2tzCjcxTTlOTFM1cWQxT05UNnhRWlpG
            MzR4Q2NpSk5PMy9iTTFSUFJ1TkRuT2cKLS0tIGQ2NzdIdFRLSGNJVmQxMktYVHVm
            dU1vQ2xxT1VFNDMvYTJwdy9xeGZtbG8Kcvs4wgBTtDU9Sb/FKndimBgV4Yg6ikyX
            G0YMMCBO8G2Poh47LQoxyZKiP+NoeyS7zz5Tcru14yFe7GXQZh60ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y20xRndlajliRnA4Umx0
            MlNFU1ZkczloV09VaFYyVlErUXZxKzlyQjFJClBoeU5zYUczTlNiK1FVcnErV0Yz
            RlhpZFoySU5zdkpKbUtCK1RUQ1A3WjgKLS0tIFd1TzZNMmJkWnF2T1N1K3ZrWElS
            RWxXR21uZFBTS1JrQUZpUFU0eURhaFEKjRm2JeyGlOThZbALSsllvFUA6aNQ7/5e
            2+SjmRCvgQzL6iJVXYpAcZb5mmWmuO+dnPu13X0mPHXjHt6fCVpc/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-14T01:00:52Z"
    mac: ENC[AES256_GCM,data:XOWpYpCcuvQNV8uJaFGzWMtIwysuD20cjml44I8uBcCeC5y0C0VDTPbRoyd0gj5MVx88kKP2mImvf3CnZxxNrvbK661NbeTmtGHapau+tY0e3zKQpeXWMbqJQQhI+O8s1QPLuX+sMIk3Is8if8GfoeZtLlVHHvye+ZdWdELbe5c=,iv:bWV9PCxJUSDw/Rx+GktERBh50USmY1X8/jjvnA8r5Ys=,tag:IuAj6h3naxPMBR7EVUyN1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
