apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:cR/lLnVfkmPiWEJtiNR48mgs,iv:2zC8bYAiLiwvJGoDaUSY76DFyQ6RahxItUx+fKldGSw=,tag:cY1CRD1gtVaYgKr+XBftEg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:bZlreFprUm//bF0hZU5Zl19UWt+dz2FGz+AHh0bZuuapHBoZ2l1Vp+VS8zIUXjzAFnxwge1PT0+NX28iHFwvCuo3h2H+Lfg=,iv:FLZ9FMYogKw2WYcgo+jT3D/Bpo4ImQ+3b0fa/akOUmM=,tag:R3cDCOkmGIx++FuJMRS1eA==,type:str]
    ENABLE_OPENAI_API: ENC[AES256_GCM,data:RUVhag==,iv:rymK5A8/v5+4gXeBfaEM3lTbIJJwO7bkZn747PsQUI8=,tag:zfqUD0ObgfqJ6KIin4X/IQ==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:CRxKUg==,iv:i0sVbPmQvOkfmO/dWexwyjy8tVVHJm1JJ+c4I/Wg/cs=,tag:s15vJcjzB8f0XyyRuI/m4g==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:NzMRrg==,iv:cKIVXn5l7oR2KRzLCgR4cHINpo2I7DMPvtyyaWHVk3o=,tag:P2ej76emr4wuPSG/9BbY6A==,type:str]
    ENV: ENC[AES256_GCM,data:IhcKbg==,iv:DFJkjkCGiz95DEN9rnxmWyuh8R++ASfIk3bjp9F6uZc=,tag:IRWfdAuek+N1tZbRtGjR6w==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:8byQSA==,iv:K6c96rwHcuBhaJT3BR3efUUl8vTITJYVk8SpOybjxgg=,tag:BoI70AWLAJN6FMpZAaeydQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:tE2gVw0wdFZ4z88lYBvxU40gGcRJKyS6aTncT8yMBIyvO72WacNN3XkqI1WkL2iNA4xv7f87fA==,iv:+bnLZcPk1dTnCF1rGsQ5Ch6VQ4cOA4A27HC33QR8WcU=,tag:Q7fBoHpwHQxLBFgIR+KmGg==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:+ZTgcw==,iv:cm9JGSCk2M8N9EMQ72LwZWxjJJvr48Nvb7pC+Z7qAs0=,tag:uG9++N8kW3yWZ4ivFNPWvA==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:UeTt0ERkwtFdmjaW4ObyTA==,iv:CDN2lxTqpJxbr0PfX2Y2q6u00vWUPZrvFelUzpYcPbI=,tag:AvB/PerbLHEV2/Se9zBZ5A==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWk1XRjFWdTdUeWVMdmQ2
            d3hiVmovZkI3dkNBeDhzRVhwd1RldDg2cGlZCkplR3pIQUUwam1oVWpuM3lVSlZD
            Q1NSV0Ixc2dzbHJsVngrOWFaeUtsVTQKLS0tIHpaWGpEdXU2VVV1Qmo5TDBBZUJk
            bEFTV3BnY2lRMmFYTHdmNWxrU3JDMUkKQd7epUd15s+AYseVSnJJcZIoqSfM3XEU
            eNgnbcGjCv5NHP+XwvGT32ekAH1Tkc+kVZxHVLZG09GF/sMTkgSZXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFVLbWtUSWlJdUdHUTdJ
            clF1VlJoTzBQd0hCdEFjUExoM3gwVTA0UGxrCmxQclJ4UjV2VFZVaHNWQTlIMmtP
            dHJQbDZtcEJnN1NocmcxZ0ZTZ2ExSDAKLS0tIEN2Y2F6VGhlMm9rV2dQL1VmZk5G
            TEJoL0E5S1o3ZlZHQlRiRGpZUUVObG8KXrH9NkPF9mY8PYSeyqAI1+ipHRIAoDjc
            ZRpFq5Qi5gT4WBIyV8FXrneYU5IST2/39LRV+dgdkJGr0SRKCwzVdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMDk4WVQ5S0pvNGRzeUJP
            MkZPdmJjeGZBMnAwQVVSc00zREROdWNMdkd3ClZDVGIwVHhBNjBoZHZHT3BxWlRh
            YTRLSmlKUFd2WUR6N0VtYy83K1pQU28KLS0tIHF3OFMwOCtEb0pFaWQvem85RGtD
            NHR5aTRxTWZHd1hPVWNmc2gyckJkTkEKCxNYHVJcEMD1dIESB1uiR7TfWvdg9GPL
            XNj+/uX5o8C5pGcQ7KJIB+DOOxLJZmDpZrHSCJIND9XV66WsBbWNxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T01:12:39Z"
    mac: ENC[AES256_GCM,data:HJLv3CGeFI9G9hMlfLtVVJXfKTNuo9BosnlQ2igU0vx5yEu65cJzWXK0jZMx0fBmd6BhExaLwZAcUDhUUMp3ivi8UAvdppkUyHbeegQPzOFEjceuiOQF5ttZ5ySIXyF41WMyENnHHkxlfn1KYK0k1JIhtFwOmaX0Q+VZpQ0tLUE=,iv:3IPrnPLoqlOND9MkF3Vhgk5EEHY4En5lxc72enct/Bo=,tag:D33QYUb+r9qxeefL7ldAVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
