apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ai5BIkW94WWvoWsOg1/g7BXhbAFaBWKwNksTygzCDlCEAJvD9F4bzQSSA6Z/4vSmLbOT9MqXCxG5S4sgUhtuDD5U5ltXBhg=,iv:zubxOultuzF2MXwQTppUZ5RPjEuAww8MHGiU6rTQ0NE=,tag:GsUJu8hlGh5M+m7eg6+8Rw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Dv/LEGCEeZjJTp9fDVfkOlhWpvGGw4ThFt471JwEW9SZrkJ8lYAtwvcTQpQw0XoXo+oW1NGwMw==,iv:PtYRlHQKVn5umGy81rzK9v3FyXrlHFPdaRScXYqOl54=,tag:KUF7pi4DwScXNbyng2J+Aw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUTlJbDYyVDdJYlBoYkhw
            OTc0ZUR0ZFNtZkpwWENON1lpUkN1dU43YlJnCjFySXdRUFJvemliSjhUZG1tRUVN
            cFVJdXAvZGJidnpqSkJCN2NTS3Y4Y2cKLS0tIGdvLzBXVVFTciszSTVaSFp3Zjdy
            VDVFRkJhNzBhbzNOaGs4RjRVSU8vdFUK1NckACTslg2L88PC3iXEIe8z8gfJSwU0
            FVky1nB7MW18Te2mtjVhkMBVxhKGGSLbs1TQAoayIu/Pten7XoCw2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOWNtVE5SYlY3YmR2NUNM
            YXYraDhQclFrMHowVm1reEM1VGpETUM3NDJRCkVqYlMrMUFyOVNydHU5SlhxYWN3
            TkxrbGcwMENlU3Y3Zklpb2VQSENuQVEKLS0tIENCbmpINDducFZDSmtJdWlOd2VY
            SjFNdFprNHc4L2FMdFhLNEQ2MmxiSzQK1Z1JwiMF5IXqEVZySmNPraKcaQ/Gjqtk
            Zr40L/4GBbr1l474LqSlFCbJSWAa56vbZ2/qFelTIqbWVduCp1B3tA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcitBMzJyemwvWlQrVlhQ
            eXBzMk5XejVMQk11NkhXK3VhSTNsVlVJVkRRCjlQcW9LZllQYkpUSmZJeHRGbWJp
            ejI0SFFHQmFvZEFVVndVN2dBcmFSUUEKLS0tIDBtR3VTMTF6bTEvQ2JFTU9EQzRR
            akdKcllvcjFqbmJFOVBOcW5LQWNOa2MK2vKo0i8pKt3SLQniKUzD579ThdwUBRwr
            qTwnXgw51Z8GekW6JpNX1NLUj9cv3YPEch3c4hsT70Qlw5t+eIJdPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T18:38:46Z"
    mac: ENC[AES256_GCM,data:fFVoXk+LMHM1SYq9QBE+gUBJAKlx4MEUTgFcX4GKzo5d8Rm7HBMsdMTG9t3C2zQvrBen20RU4evGRYbgej1JnTwU670b/mVm0DODaYfNgIw9tSP+bCEVn2NE2JwiCL3QPx20qZek2bc8BK5XajdA/2anecFzxmjhTE1g+GIxyAU=,iv:LFb2LFzBVktJciUxY1ySLjwSD2yNlBtmT9/hGgaURPw=,tag:yYXFbA3UPllPPVGnFV497A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
