apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:MyANOrdkGT8xyUWBX/E/Ftzd,iv:ZQuL9LnKe3krhpLkB7EPklBAJ+N74ISUzX088jRwPI8=,tag:KProgXw64eZcnQgiDhXnSw==,type:str]
    AUDIO_STT_ENGINE: ENC[AES256_GCM,data:rP9Z878O,iv:nVLZDU8OYPrGqzOkGOAGUjm1f/0o1o26yt09cRGIjBA=,tag:+1DaVk1XvjJe543OmCRgdg==,type:str]
    AUDIO_STT_MODEL: ENC[AES256_GCM,data:TO1SvFIusHvDLnDcSHmAfU2sYzZq8IetnBrv,iv:tw62IHrgJxXektiSBaCCllic5UQxqu/pSgPYdpjN02U=,tag:j8cevxpEdnnfe2R08goiIA==,type:str]
    AUDIO_STT_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:sNJ4ToVVjhgG2sFp6IWd2g/POmuqp+DeBHKDoA==,iv:5Zc5x+w+Z/27vzmavsWWj1y1Yjj3nMiBitR+h5Gnric=,tag:dlvlkvh1RVlgslo5zwxiLg==,type:str]
    AUDIO_STT_OPENAI_API_KEY: ENC[AES256_GCM,data:vVF0tpDcV5PzTmAG5Rj7lYyeZgwzQH4Kfn9GRrvSI9St/2dUoIaAxz7CJMMbtVbMuyGDMd/cVrKipQpuN1yb4TvupvteJcrobQ==,iv:VJGtbdzbxL+PfT5tsi/HdjFswUVCoN5RvmV/4TDa1jQ=,tag:SQCrs3qlHbVD7/nITXcNTw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:HxBWASre4f95H8s7IXnhsYXvXpYEovxirlR//B1aorynGlNyJ5Yo4zqLkKSzuf9zfkyFGvfNEsQkIOon5Po7qvBwyatvXg==,iv:KbbgCk/qLpH4Qt5yMdvzkgo5tUN2Gm8oubeDlWLO3Q4=,tag:aPPtVsy6do2Gd6aXQsiM0g==,type:str]
    ENABLE_IMAGE_GENERATION: ENC[AES256_GCM,data:RysUNQ==,iv:xOFUSoResIrtfdwaGXwfiSTwnd2Sa0yJBcgMzgVZMok=,tag:n8QCYUOCS3XxR3U62eesVg==,type:str]
    ENABLE_RAG: ENC[AES256_GCM,data:QPnsEg==,iv:jlp7P2lkVBLB4WKmXZYF6bu1wrbDxjkPmwX5dSqMiIE=,tag:sgBffCEc4Y5UmdQ6WUPtLA==,type:str]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:Jb1zBw==,iv:j2tFeShSjFyisz6210LXHugH4f6Kte6yIn8Asp4Xr2A=,tag:j7cPyw09aD9lOL7+EmJHAA==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:WZdUSA==,iv:aW6uyDWSWef4lo5+zKg81s4HDMbAJQ2HUev3acu4788=,tag:79OvQnehX13qSFutcPsT9w==,type:str]
    ENABLE_WEB_SEARCH: ENC[AES256_GCM,data:BdY23w==,iv:PgNkR3lxpE+vPBs7XICHELnWczNXrp5aRjy8GrvJvCo=,tag:1hEjjeCAtS+7+KmriptyyA==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:avQ8iA==,iv:baWOEPCK7z0A/qA4ykZENNRujintkwONcx3wnSRWMMw=,tag:WcdU6P9zE2KHwsmpTs117w==,type:str]
    ENV: ENC[AES256_GCM,data:WEON/Q==,iv:CBfB2+iUKBZhQCs4/pbEsG3/a7Mc3lndNAPP7qHQybs=,tag:Qx2CYot4AiKz3h5tfs5yew==,type:str]
    GEMINI_API_BASE_URL: ENC[AES256_GCM,data:8LqkegPOTYay+Y2oE/Ck8KE4ymUcSViZnq91hrGK8k2xm3dFbF3HEGCf/iTO,iv:KdmqyhZvddsvQCj0JMOmAVPUSwc1PZCYm5zDvNF11wc=,tag:KMrZUkJGpxFmBCooSBB3QQ==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:KmyfMC9DuIZK5AL3tkDoefuCScbvK1EwUkDJv/FvZ0rlD5WCiLotzu8+8bW4mXN+O/aOu5PSWhB89z/1B/3xM9SNTaRegvcSlw==,iv:vpE9/OjoUCD4TAmchtUWMuzsBDau2awz5zXd8gqiDcc=,tag:ookZ6MN0Bmi2gDtfvodk9w==,type:str]
    IMAGE_GENERATION_ENGINE: ENC[AES256_GCM,data:LaSqPyEI,iv:vLg1MZBOSBa7QpdiqPRiIJNoMP1cqY47QDyKnkudPrA=,tag:A01sLxcAQbvZE/z0LfvYMA==,type:str]
    IMAGE_GENERATION_MODEL: ENC[AES256_GCM,data:Z9LvWgBY1BUEB3WNWBbFjAowDOcTbe9zwk6DS7+/reECHgFHhw==,iv:4dfaUhjR4haSN6QfkscAC4oQGjopTsJM+Hc8q486AW8=,tag:bSYGOfRFlpWq3BxinqhUdw==,type:str]
    IMAGES_GEMINI_API_BASE_URL: ENC[AES256_GCM,data:MnCznJDpGm/hU1+xovyoH0To19mCp+QktCfnkqUTGIq0P2M6SyWJbDUir1Ze,iv:/fSLqcJl/YrY1NaKSLFHvyNDC+qsqH4TZwzCRvoNeAM=,tag:19NmhJrxVUdfwTFGNNBV7g==,type:str]
    IMAGES_GEMINI_API_KEY: ENC[AES256_GCM,data:VE6qj4K2u0ql3QNnAe4gggNe5O/L2MNLmhuFV4Vim024DwZ7v/h9EKRTs+2i376qJzkcQwUlU/5h67kMedv0gTJKc96bN1rsLA==,iv:a8GLNCIoyxgmoMHuv/WjIHi7z6Db1NBC/t4oOYQP6Ao=,tag:Mn4CQaHFbUZLKpcbkLFbxA==,type:str]
    IMAGES_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:aox89lGYdHY8zu/3d+UIDvCojSB40ZB6FKbl+Q==,iv:doaxMmU9oSEDgcSB2NThnTHDxT1nppPqfdPuvfDB2M8=,tag:E5f5sJxNz9E7Rvez/E6+pQ==,type:str]
    IMAGES_OPENAI_API_KEY: ENC[AES256_GCM,data:Zxhw2GvoeM2OpULnKtncARio+6g0C8HFZEn15utrsNTpOpTIOniSpRxYMWaOQqNcPEcyF2v9S7yGW6Re109jHp6clDliurxSSQ==,iv:m+Z8WuQ57NDhviQBvRPOx771apA0x/G6nnaNQ/gC6i8=,tag:myHK+I9nXom9EjkuWP0u+g==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:fYM8QA==,iv:52nghY8Zbj5DSnX1x+eJCWHnUBduk8uDgdGXtzHF8Xg=,tag:sEmntBzmw8QWtPC4f7Rd4w==,type:str]
    PDF_EXTRACT_IMAGES: ENC[AES256_GCM,data:pIDeyQ==,iv:b/4BgKtdUhycvZdFeRtRVvEH1A+m3YPxjaeH/xRq1ws=,tag:zyMiRtqE46xs+rRYMlxUAw==,type:str]
    RAG_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:l0ox2SNTkEd3yJuIufKKkJFaAapY0UeqmrTPfw==,iv:AmwL1FAL/MjTDp5exkFp/yQaGZZg1bOnP8PQNhCgZp0=,tag:qjpIJXavvmeihCOXvEh/ww==,type:str]
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:aGLa+pfvhy2ft5h2qMRP9YpuqGG+81xd8hMdoe9riwiLLJqbXsDlyJtTjbIE8szNykL3DS8waT7JGIAkhIQysPNI94CxEmxDeg==,iv:OxAqVknbvBSdRnFLvIfWl4yBiLX3TzxHTri2cfbvH6M=,tag:IGaJyJjEuT+xAd6Oqbz1+g==,type:str]
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS: ENC[AES256_GCM,data:Ywc=,iv:KdPBQK9dNabh/Z+9hq0gIi1hHdLJNc3gqFSmVS3IzNI=,tag:H3qeu77o8jhsl9beMTBE0A==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:wazaZ7k1RQ==,iv:/GZb2DYmjPflRDcxEus4PzZQ3b+VLy0Cx0wkktb79Rc=,tag:fKN0ykeT2+XdrUCjM35WxQ==,type:str]
    RAG_WEB_SEARCH_RESULT_COUNT: ENC[AES256_GCM,data:lg==,iv:qKLppEk7y6d3My6Hq4gSJFyycZuglttRec9tFRT7zx8=,tag:xTpTK7QDCwm3ZKesxrNieg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:4my75VlQmacxfB+AcGEzZ6WPkZqg4ZigqUp97fyNDQLSbyrWQSpyHTSHsBSxbc5DRQPfKfImHQ==,iv:KbMsql6XgnIYJUzGn52mJTRBXuk0OFst5B8eVjrDs14=,tag:cCg0bV8ndkg/ZkyXUym4qA==,type:str]
    SEARXNG_QUERY_URL: ENC[AES256_GCM,data:Am08bY6Bn10zLwIBp08/ey0ypwZhZibhUsxXkbiNugHs8iQhwJvdHcNyMMcdGfuxBKNYVvGL,iv:4mxqr0fryzoklKbn9VwUJgSNMs5DIJ5PdY9ueerQaIY=,tag:UWGwL6C4wCYYbEUiz9g35g==,type:str]
    WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:zEmrqBFnKw==,iv:Q660thhCGyHXVJhx4Izc6ONZja70JkJccA2eep0VPCE=,tag:D5wWIkqFfKqkiaDvQqtuMQ==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:sHooHQ==,iv:h5/YnbaSbO9xKE098nhDoOS+3qXimIXRYIyqbWOmfqE=,tag:gtuUjoVqdNoRyuJVUp7HkQ==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:GW0JrZPzWnVR440hHo5kpA==,iv:hAcVS8zGOF866M0MyuouHMTEUBiRIY4MV//jJr0QJ8Y=,tag:VucdMaxGD4t5b0d+3jbHBA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ1BhbUhkWkk0eXBIaW8z
            dEhNYXRVaVNGTzFPMVI1ZzVZd3htSWd2RDJ3Ci9UeE9XSmo4VXdFSW1qNE9pUVRU
            OFVnVENhbjI5Mk1CY2haRlB5QjIrV0UKLS0tIEI4aG1ZR3pZenJSVTR0NHZUdzZY
            dS9TazhsS2U3Ym1VRm02YXRqRU94dzAKbJzNgbJD4IdBGd5I+HwkTerTuC065fQZ
            U/9Tfuiv89DCdbSqrCsOwDK2E1oKYB9gsYfTHh8tcXY/cxrl/T5Bxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGS2dUUHl3RlpJNkdIY0tj
            WjhuNHFCYThhRXNXTVpNdmpwWDNaVkNIU2lRCjg4T2hCR2dEM21va0FvVVAvT0p4
            Rmw5SVFkcldMdlpMVjUzMld4c1RZOFkKLS0tIENHcXRxNmhFRG01OWFmNEhCdy9K
            MzhmYVMrYXJjOGQ4MGJPcTRXSGdBSWsKLDNNwpQRwI+iwxehQbq7V0cpdauhnd35
            zl38PKqH9NWthNsNg0SAYzpW0OAWIXBPaiFJUk+Z9L20vnIqn2KdmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVXkrTXV2K0dRZFdmem9P
            a1dZb3NvQzVVQVdwcW5jbVF4Tzd3c3RRaWdrCnRqVE9TbWQzZ1FRN1NhN0p3d0l1
            eG5rZHFhWnlDOG9Rd2cxUFBTWG54bm8KLS0tIEJOdEFpekhoeVJ5a2hEMUJmZHFF
            anhCQkRJd2tBeEhBaHhReVZPRGZyR1EK0J49riRPOcnFtnoNnGP5CEO2/frpMPnb
            EcAGE8MX1rWUmbLhfd5drkKuwQOmwDO5kEKUVPUet+7xoKzYz5xMMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T16:19:03Z"
    mac: ENC[AES256_GCM,data:hFEcR4/sfu8Z4XFBFDs1rKL/l7bKL/U8OmlG8G7XuOER7TNWkJ7RXnWa4VVWEG0tQmVY70y0VQeIzqqjzH/erZRU+wgIPaDhCZKXw8V2TeA4wokx9ZnMNqLFkNUXNfrxaqZGvJ5L4G8VhZjnUlG4w91kSwHZsB0UGIKpdVa/LEw=,iv:WMEuta2I9oZ/fTj65FgnG+m0jSwgPHaUGYoCjjLiODk=,tag:/U4hH0og/4ARo+26T7pvCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
