apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openrouter-secrets
    namespace: apps
stringData:
    OPENROUTER_API_BASE_URL: ENC[AES256_GCM,data:AWnBh6DBe8h6A/tNwCj/U60DfxKaT0mz0rqJew==,iv:k8biXTmlbLxqejTY3GSB0QdhnEUw/HBCu/B2EYQ/jxM=,tag:8P+Mb26/MmUtxIuvjBK+yw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:KF8j4x4h0lH9LoqbzNOcetCEe3nTp1uw3eBNnZ5doU9iDle5SWRV965iUjoqdTct5DSDEZ+DulfkKOjfMhQi6kxfaJwinPPACg==,iv:n1ayEPnjSjZdK3pP3hhmB9WYPXZvT22bRt5cTo4Fu78=,tag:jEA6ZY3g4PXWjjwE8YZspg==,type:str]
    OPENROUTER_MODEL: ENC[AES256_GCM,data:yA5fbkoglUixR3dsKG79Jf5j7Q==,iv:FX2KyKVwVDco7uazKE4jc/pT0g/UjrE3LTZ1KgHvABk=,tag:bfuSYjodr0UtgTJbMEXURA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Z0N1WkZJM1NuUVNsRXhM
            dkdPV1hTckFoZjc1WEhaVDQ0U2cyS0hJM1VzCkpFVmRBNVRmQWJUdEZ4cXZ1OFYw
            VkxQVlhRQkVuekxGMEpJNzB6d2pDak0KLS0tIGV6UGJ2cTNWSW1LcnVpbWpJRS9L
            bXZ6VEptWlVScmR4bjkzeDlna29YbHcKdBAgPGLLMSk2QZuxQ/7YccFsQ3aqHQtC
            fz9p3cnKyd63Bfs6dZla9h0FrgFBar9M64pjDtZLupd+1dFtFMsJsQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybkU2UFM3NjFBZTJFSCtP
            eHlCRnplOUtwZ1RSRkllVENUbmppbEI0MUQ4ClhNQktVZW9tMEd5Z2dLSDYyU3Y5
            MHM5NTVCeFdNbFdqdURwSlFzUEFhZ0UKLS0tIHBXWWtUT0t5ZlFXOUgweUhDUllM
            cmUvV2MzTE80SGNYQisyN3MwdGRTUE0KdtuoNKGVDRXJ8Oqzpdkoo10XjVn2L+RR
            czzj7DZ7Bfh2qLZlMnU3Kba6Ta/+oKCOJJdV5+QJRVq4UJtcGQ4H3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxekY4SFNZb1pBZWVqOEVN
            clh2b2xnMTk5TFRLWHkzd2l3Yzk4dWxUL3lNCksycHExZEVuRTIzL1FhMUNIams3
            WEkwTmRDT0lPcE5pVnFqeTI4aTA1eWsKLS0tIE1nUkhleGt6WVFHemV4aE9aUi9x
            TmExSTZ5b1J3akQwakphZUppaFUvME0KnIIJf1+/sACPgarIvnYaMGYJ+Vrb1BFx
            tpp6REujKNK65jiNOKANnujAc/Y7VTRgSQEhkyvkvIcJziH5Nnin+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T16:26:50Z"
    mac: ENC[AES256_GCM,data:yn4gqY0AJynqgryqBBOLI0J19Cyv30N764Lm37GVJ8qUiHigWYR5nlHYUW9MCQhvcHhAju22WMVlhWKsTuUG7CHmTacfbX4MvCw3EP8SgHroh0AHExbyUITV/dCCIQWRLBfXU7f7MZj4AP75yXCJZ7BZoMGBqwF+cum/ILfHDC4=,iv:JZYqx6lUHQTKnaj0Uarcn8GgMgpw7pQk/cB1AygsOsE=,tag:Hqi1uBj6ntzjt/xaYL2leg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
