apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:TKpfNH4b3Dn1XNdd3u0FfgRT,iv:KoWsCY0flbUmlqClv5RNf2GTU+IjKSG39fL0AVdpBt4=,tag:NQlzLSN3ogrS403G7rFIMw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Yt7OCb9X5YbBxSke1+l4amDeLjFBjHYPIXYCdQi6adqvYXEfoMZp7ha82JuEHAB/4Vx5/hsLHRNY9hz9nuaoqdpZouVzL78=,iv:woVz7aLZ9wA4tC08mXHUxokEZ6n3yRzRetzEyDotG5g=,tag:0N1MisU3lpFlhu6xeHprBg==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:kv87rw==,iv:GT2j/KoeKk08uym9VY56kK+rPIN5wYRpKYm0vfLb+2Q=,tag:sCk5Sip0qpArUqya9KiCjg==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:CHU8Gw==,iv:w2vQsyeeLUH1tUA+KdTmThRpy6B0SZIqSSkIzCOnqoE=,tag:ex06uoIudYX38HirNOAz7Q==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:v2eozg==,iv:NWdkln3TTmt81cUb/TDPGGBj1INdXd2+ewKlBje7wag=,tag:fTfRZJOjz1TZ1XDZmt8dvg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Lq/8aVHiOij6FsKh3lo8efFfK2W7kTLLVuq1ZHvm2jjIpinuzlLpWH1KBgEVqkrL3yyIU0ypfw==,iv:2LZfqyiazPrWIvFU8v/ESWOf28v1JOzfkm2iLZpIFZM=,tag:3AsELXvBrI3hKt31JzwmeQ==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:TF9R0w==,iv:LjCfg1r4GulPrYyiIWX41hSI4meDDllV7uhjVwpNBGs=,tag:W7gCqD4ZV4VjArzJy6rEnA==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:NUdeht9J9DFn4+SKIbiZxA==,iv:sdbJ8C99Q2qOpb8PiG6dNp77JhvNLYLwLRwCSKT+LL8=,tag:bhI5NHFcqYJKxpdmRTO1zw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NklsNGo0dEJ1dkdJTTkw
            dnF4WXZWb2orM0lqSWtaQlh5UElVcE5vMlJVCk4yUk5TZFJQTm1WeTc0SENHRDQy
            QjFLNG5DcElVMWVHcGU0REVadnBYclUKLS0tIFVqT1g0Z1psT1dBc2pIK2pYRldI
            NWh3V2NzOFhSNXk3Y3U5YXMwRFF0MmMKpqoTRjWLkwiQkSG5Wr59/0gdVXmANywI
            tJXrMI56wNpWmmg4avXZU8WvjFiNNyAb89Ttr498mNlnLdRhBAxDKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcVdEYWhSWk4vZE1RZnNH
            ampZMHBKdk1aWXlmMDZLYUo1VVRVNXBXNTM4CnlZOGEvQ0ViTFBkWS9ER0IraGxH
            TmlOSWFRbEgzRElTRnNzWkcrM1hUak0KLS0tIEtBMEk0cWZ0eVF2cFdIaEtFZkpD
            ZlNRbU9hQmNoYnhOZmNVODV3Z2JTWFkK+MpY5h9QoYr7bUuAkO0ZL5VH8KT15b+O
            yd1hk4M3Q/Qa1eaPYD5OJqaJPtzge0ssZ1EnCUJVdIZVHqE37BueRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ21GMVJFRGdwSi9mTGpt
            QUdIOEptbVN6b3l6dS96eStWRkE2b2VUQ21RClhaR01vbFl2OW5qWGFBV2hXUTBD
            WGtzU2xldjg0NDlURHludXJYOUhyU0UKLS0tIGNYN3VqclE1SlNKSmhoa3RRSFFN
            WGRRbm52aVd3NnNxRFBsR2Q1QTBPOTgKf6s/7GemSITG+aEHc4ap79QvUHchHgr4
            RgTNI4pE+c608F9TDXXc6emppVFpMoKdaU/kNQmdOqEl7HZlN6bzjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T19:26:48Z"
    mac: ENC[AES256_GCM,data:AEvQLjmDQU5l3/YRVljJmzgBuqoYwWYUHXxxc/qXpJPLL+yTWKTzOS4Js6/Po05klgHThZusWy6QTB0Rd6xJuFaDXWbQ9lcbeq/whgjRsxyDCpy4WS7X6UIR7J6bCh4F0lqdnqRqMKirU9OU7Q3KCR+6OExbDbIILqIY+qg4B5g=,iv:Gs6LYaG2ITxzvmBFQBYD+/CdyZhALiESS3/rBm3HCoM=,tag:BHH1JcCweqkjoln5PEAEyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
