apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:MWf2csvkeGtYoDURvv3paNoG,iv:MOg1K1NDLSfLdSENIk+5zAIRhEmi5r+sRwP+gzcweUE=,tag:Ru45P4IOcwKx1uIiSjZ9iQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:vGvWjq7hKX+Ls2HqHhLy3zjYFB4tOo9kkC3w5PGQb6Wbzv+80n8ruJ+O7l4CSbw33rh43ar8vm1mhR+PGHxxeX75bquKmgo=,iv:jh7Wm41jv773v3lEkCAmt8AAUgW7fKvUohgU1S3ggPQ=,tag:4mDfLrKL8SARp3KHHWCqJQ==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:y64jMA==,iv:1OWzcIeWfyLKTMBNpWpsV83Y1w05QAp1lgN4Rm3HrdY=,tag:Tx/oQX6yypKKqdQSxDX09w==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:XSQ35Q==,iv:LH/AFnWtbSLAiJBADyQfduphRUHRDHGhCSPi0pYJveU=,tag:FiWGsCJrBbIicecDD5UAZA==,type:str]
    ENV: ENC[AES256_GCM,data:cVI14g==,iv:oJ2mNCbY36at2sEoGU0H0S0K/n31GypYImQoQjvKNG4=,tag:NxGZPDruRIAvfxDgLZCH8g==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:6jK7kw==,iv:Y1DpnXGSW2/i07Ptli8SNIEgAkc/WoH7gfuOzVP+RUQ=,tag:z+tFW+igx1MRDYiYWlF4oQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:62FjGGK4zAxJ9ieF4FPtHTXwPj31z+O2wit42gHzDsR+/ujnY5VmKAIMh62WM1LHPFE6Qsdv/A==,iv:VdlD3mnIdAVh1WOYFN6IczOFVY7XYsUTrFrJsXoOfBk=,tag:u5JVpBGcyQ5+iWKqY0W1Gg==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:ZQ/Lag==,iv:L7LPFvCwTvaGOTDd6Gd8hvWLGV4TEiqq/c1fcpxti5U=,tag:2hSYbW9POdQAp5X/o3Q/gQ==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:XDvTTBVy0hbic/QlogbZTA==,iv:XcpWPmdToDUv1aZZdEo2JVHQO3BDm3LLZ2cf32/LCCw=,tag:Y97KQKNtqVD9bAJhzSqDMw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoc1ZEVnlSODNGS2xnaWJ2
            by84K0Z5dWxxbWxra2RNUjlhSTd2NWdWTEhZCjFoT3ZGL1NWbEJkb0tRQWdvemtq
            eDdZakpqOUVYd211bGtSYWZhNUtpbXcKLS0tIHpBV1U0UUtTODZSSHFSNC9VaWto
            cE9XWnRXY2dnM0JOblovdDVudVRhUDgKByXuOCyWkGcpTfNqi51TCe+RRGIe0lFn
            ZqXI51+EoACAPMFy5FXuIpwRyxqMGbWDf6/XVLMRtsWbZqcs7TJBJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoa2FwWW5hVkxSNlJCbHhv
            NXFiNUhNNVM2SXVwSXM2ZURrMGVqZVQ2WW1vCkdDaVJ4aW40V2hFb3NyM21BQkd5
            UU9ZcTdTMGRLZTJ1VVhVakZNRTNmZUEKLS0tIHRaRlo2WW90ejE4bmJ2SkZZdGhY
            UzNZQmdBWDBvQ282UnFwZzB0SmNiNG8KTkZSshqphsjPCIlLf5w+Gcb/k60V3iki
            ZTBrNORBJD4kw1k10+WlCrQhvkbAiupCHDVq+5ycfn8KuLIWHFOyTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc1RLVjYzUnVQNXEzQTdu
            bEZURmJ3OWRYTWFYWmdvY2hrckxvaHZBVnlNCjc3Nkt3TjMxK3cxd20vTzZ6QVVs
            UDdwOHdQOG9oYWlmQkpvS3NZSWphbEUKLS0tIFY2TTZyQSsrdTlvQWhSeUJyRWVF
            c0w5c1l5QkNlYnU2M1VCWWthdW43M3cKmPx+YN2kIybjzynBmchge0ML+o03XKnY
            pZkCHYZwACQSd/FQbj+r3lgRTL9esmOq4Lgw9sC+vZHi3UP1nI3QAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T01:29:16Z"
    mac: ENC[AES256_GCM,data:lmAo6eW6WCMd8Q88FUSsRSy17YjCjt2DA7sucBinjGmj14CJUNrR6O5SuTgF6xCzTUoJEAQop4jlgO+tSBcDGWZv03mu7+OsYTANd/PxEk1VPnb3TZ9p1aHyX+Yfko1j7ZIVEkZbYkdphXqrhMLVsF3U7QD/J4ZNWaVpY6+nzYA=,iv:A7mYkv71xLneEW+9/F4ZBHed+12SS0fQLU9Loj6Y0C4=,tag:Edkp7wvynW5A1ZVvHQX4AA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
