apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:ekhTmVoldLigklvlR+nE/2OT,iv:SxlG1Jd3TV3Po2mjLq9Q+BH31rhFgXXUmrA17tDV8PM=,tag:+KKBPAZ50l/xCOtdDnGh3w==,type:str]
    AUDIO_STT_ENGINE: ENC[AES256_GCM,data:05Gfq+i5,iv:I5IqUSrc6Cqzu/cdjM8qQUGGyu23G8TbVy8saNIckg0=,tag:rJd3hau3sQcp1QcejNkHMg==,type:str]
    AUDIO_STT_MODEL: ENC[AES256_GCM,data:5fVVEaIzEjRoBeXzCp5SQ4jdI0jb9xXOD4pi,iv:fVyB5udNFxq0ctdXw673qfBvJ4FbPtmYxgKZB0lRmT8=,tag:V1P9KBpuVv9hZVlxA0jx+Q==,type:str]
    AUDIO_STT_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:fHtwACOb2/9pyNPvdkEw1HdhzPDs0TOKSP7gUw==,iv:T+J/Efy+BNsb1ETRFlA6pHpml4Rem/gtFMmhtv+IB/Q=,tag:tiU8BLXd3FuN32J9pHe7aQ==,type:str]
    AUDIO_STT_OPENAI_API_KEY: ENC[AES256_GCM,data:6AICiaXBVg3PRa05jbunOs123jrfOmQkQQy/jqJNf0DB5cm+KAHrBe3RV/IlTXwiwcSJpTIAcxJER/+h9vgwkM/XJe//FclcJw==,iv:2VA3cVmIOBBPgoiO9hXSk//+3hhVcCkODywOp05utiU=,tag:VPj1P7IfEh0mbctedcHsxg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:4b/DfxJEmOIcc3AgaksdiFRS9caAcpmuYW2qJZZhWp+C3f7+vO/JoMGuPwIFvMS2tyLjnoy5oZZk0nN9Vza69NXpekefTw==,iv:Lcm7VdUTbrSNChrcrg7kZKGqqiTLIOm20M7ImZPY7bQ=,tag:wSO4lDpCtFGBj5WAf/Qqqg==,type:str]
    ENABLE_IMAGE_GENERATION: ENC[AES256_GCM,data:kRtVoQ==,iv:PTVZzUxkIDHSOQJN2mKelH4JqxJDpYfzwi27dNaR+SQ=,tag:jxo2c4qjkGyHPTcgeoZkOA==,type:str]
    ENABLE_RAG: ENC[AES256_GCM,data:Vkg2hw==,iv:lr0Igp7aMpBilP1XkSjaeS82sfV3XqQApV8URGbZu6c=,tag:65o+QbnW7XvImZhIhHH7dg==,type:str]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:ZFmJYA==,iv:3qyX7LcoVo5sBLeJSd/kGD+2bAoEBMSmLflk6ohRjts=,tag:9BAZ+Zi3RnFwBmMps4JzBQ==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:pOgrXA==,iv:EsseOXLDfnArZaVRI+hX5fWT0ZwMbgD12R+um3mD1+Q=,tag:rvvzRLh8yY03JqFUGcanog==,type:str]
    ENABLE_WEB_SEARCH: ENC[AES256_GCM,data:6Bhd/Q==,iv:EfFqahAeqFObGl5YUKRYa66BbxRDNVwz/VqcmD6vik0=,tag:V0OCvAxejqq3m/An2VFQuA==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:+qGOXA==,iv:+lwWH/0ff+cpx1zwlhEavjuxwd/gQNyk9HaUYaIkgYQ=,tag:m+eGpJq+HkZYpMM8dcT0Fw==,type:str]
    ENV: ENC[AES256_GCM,data:dgAZ2w==,iv:kv/Uho/WNf+YSoniAk0a9sNC0n4557AIkly1wzTXFqI=,tag:Jw+1XYBmOU9nQnTxhLAoTA==,type:str]
    IMAGE_GENERATION_ENGINE: ENC[AES256_GCM,data:22SQN7Qj,iv:Q9XCV3uc2HQ0tSgGph+HGRklFCYJnML3CKVgsSmw3I4=,tag:BgUatpgQ4PefHDlnlfBwjg==,type:str]
    IMAGE_GENERATION_MODEL: ENC[AES256_GCM,data:ElyfGDMTbOyt6DXeUle3qIfGoH3L42QOXKve/QyuZnreqcn6Iw==,iv:vDc+WeUXyabPuaUKzdQyymOGcQRzM2Q7Yoebyn4FVyQ=,tag:jXjdV1tXqy2+1annRzoWMg==,type:str]
    IMAGES_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:eCTJeNQcghGLeSZzyBYXu9vWRRRK+vJJ7Ql31Q==,iv:3mVHzz98JuvLdvGFdnCbUcNY33L/lLCVsQRTyDFCCPc=,tag:qBnqv30b7E0VyQXyNX5dTA==,type:str]
    IMAGES_OPENAI_API_KEY: ENC[AES256_GCM,data:jIe52UncIAfpjSBMYp7ApYCmI1+40v1uZAyJSicBwGk6KlOc2AoNgx4Sj3xjfTcuHW55n0N9AX82Ik0NoxGJC91ju2mxj1Ta1A==,iv:0bEA/cP3sGoM4ok1WY6j0TKn3Dt0BiG+CVBa5Px0AP0=,tag:aa/iHhBlDXtUyNahEeD9zQ==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:AlUBzA==,iv:46NUQq5r0IH6WzLhHMYMNxWIRyE92GUeLqNG7dXgrrY=,tag:+2MRqav2GJbVcY63CvcQDw==,type:str]
    PDF_EXTRACT_IMAGES: ENC[AES256_GCM,data:zQh6+g==,iv:uV4qkzRJqMMSXZMesc3pwwreZ7cz5UVqN7SViiwzgxQ=,tag:YlvJsnsBlVLR9OLnoADR1g==,type:str]
    RAG_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:evp+kOrOHVC98PWuoEHOZfS5uwP9tow4xIoQaA==,iv:SInHcU3LhyEJ/Bv8aPezs3u0Ec3nHoh6+7oHwqMEU2o=,tag:tozzIksTPuNseilVVGisEA==,type:str]
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:IgsQr4Sq5GsZlLQzLMrcHH7aIBxVU6ad5pubID9F/PWOG8RJ+ChCkWT6VuOc6mv88tqvXsv/eM07hJgiZtvWQhh9bpbnHKRc2A==,iv:ddp8n3DO/vzcNdgg1DMy8FqHr+nT83AK2wmNKhc9sx4=,tag:zaGZdmdToArDmuj6Cxjt0Q==,type:str]
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS: ENC[AES256_GCM,data:Tig=,iv:M6jS/mqjvz2dltfrMj+kddn4YGPwDEY25IP5nEo1JIU=,tag:3Bb4jVrjxCsua7xwW3sYTQ==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:1lzCqM6WJg==,iv:0SinxX6etgqeoDoKP5aa7TRra8gadGkvQCfI2zIltzc=,tag:DzKBB+ppPr1yJEKcJ1zPhQ==,type:str]
    RAG_WEB_SEARCH_RESULT_COUNT: ENC[AES256_GCM,data:CQ==,iv:729/NTdnbl5tkSuKohs7Ce9oZHRhwQ3P2dhZD9KL/yk=,tag:skLNZyz/dZtls6WK1RHp1Q==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:w7dwUf5RPMRv07SvaVPHMMTQ8Ax4BhiCW8zJbQqvXRw7Zfocy1pAZPSLx7/0IT/+hruJlgETKw==,iv:t+UVszR8ne2gx6LcOW/ZAtaUEcNRxEh5jlFF0hlHag0=,tag:nhc1KRNueSUHulH1rBIybw==,type:str]
    SEARXNG_QUERY_URL: ENC[AES256_GCM,data:HK1IS5SzwoEYNZyZyzEFEyiJ9iBuwz0YR+FFtAeMbA==,iv:0913j7Ijv80V9wnvHNwGlBfLC1whVUKR1KkFfpsEe9k=,tag:arFbGMDwFfvmLiYKsNbXSA==,type:str]
    WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:DWB8XHCrBA==,iv:rzl8mNnWEEUYNKlH7q6DGanI/09n4yg1ygYP1deCuf0=,tag:M9z7adQZ87Jz5K2burvXaQ==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:EsO4Qw==,iv:Z1BV8ppNaPlcEgc8xZcknqFyYnvLvc8mmCLmqn8juOo=,tag:48SnRs8wy6t1RqGTWKtUoQ==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:ulUq8XtVQXRgy22THb8NNA==,iv:3AW7hcrpwt7rYcpInh2HIPNHJA2gsyKWF8Gef/U+nmA=,tag:OhYcKa04bSnsdEKfRAd1mQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRWlqUUJKVUpEMkY5OE5r
            Zkt6ekNjREVBTERMR2ovMFBLemJjQUlIS3k4ClZaYWhOc05WcExSNjNXSHlCcFgv
            MlpsdmNyZVBLNTZpczFCU2xvQk1XMWsKLS0tIHdIWnB1eWdJUWZ4SHZSN3dhNFlZ
            dzdKZEh0RVYzV1ZkTExDdEhDL2ZqSVEKrQ66pztqC0MVEsGe4MzlxC2jI7Z/oTdb
            ThOV7jKcn4+iwT81zHHjpw2a0LdwCAHK+VehFSL0i/wOvbgvq3ih7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcHBFbHRFcHI1Umx0L21t
            a3dnZGRPeXJVRG10K2dZSnJLb3ZWcFg3NW5nCnFuSnpIN2dNUzAyTGZuVUpETlNE
            WWhiZ1BxTjFDNjU5b3h0U1IvTjhMd3cKLS0tIDNoQ2JTQjlxNnRqU2c4UXpWc0lQ
            b3JtV0tBK1dGTkdMSjliem8xSmJRd0EKfhiuR8aJ41O64eIyttB6fQPJ5B4B9Wwn
            KkRIcuuwSX0kK95cLdpZmpLdoFPL07DGoZ12CdXtMDXwEnQGmcacuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTejdTWE1wWDlPNUJZQlRW
            a0FIM0pWbUtWYldVYlJIdDliUEtPUlBJRngwCm1nZGFPL0t1bldKQTZGU0p3VUdk
            U3N5UWt4cHROb2FSa2txcEZsVnJKclUKLS0tIDBWY0JMakRMZDNLT0doVTl0UWIv
            VUc1amlkUUJqREtnWjhpMUxMQTJ5MFkK9M9wuSe6y+8K75Bj8Pf3i11nbHF/9Q43
            RavcENHxR5tiiQPwfp1sc12vM8COYb/4AJcvP7sqwJYiJHtCQaOJ5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T00:15:21Z"
    mac: ENC[AES256_GCM,data:eUyUzFjdmYBZPzvLTDSapaAIqqSlnFwuR5VBXbyuruRqQYXQDPmCp/mDFhf7ONfG9UCvGGjSO8P7kgZVueE9ykIWUXRfYV+d2WBsYl4e9PrCgIBA+WdG1iYAePEsZyi8iRKj54sXbzeOOPpcrbyjDBKQZyh22hCnInrrd5Q263I=,iv:+1NG0pKjcjQReXnSyrCWGGRXUiG94J7jNwfZB/14UsU=,tag:FL9Zf+fpg6CmcoEwcUuq1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
