apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:5rScvCbyZ0Oa2Ws5N7xQIZoD,iv:fZmKCgnmsSUe2XzDXw89lm2HIrjoxOJ0r4d7GYYcydY=,tag:6QB0avf0JsvKTn/zDNCnpw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:kJLwnLy5B36Yn+VjPE1LIkbfyOnP3hJsc3YlBN/MaPkmnbtoI1XKqeWREb2IfVkd/P+Yd25mwSDmWWtinaC93BPB6G1wTg==,iv:JbPwAcV0NhGRv+Xki2Ix6QeHC5Tk4QKvdqx7w7tfqRA=,tag:r5YZWcjSQJ0Zis7yCs4njw==,type:str]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:Bt5OjA==,iv:Uzv4xZO1cbddJTcTlLiTjN9fQ7pZdz/SGCCENKPfPYQ=,tag:L//IkFRhV7/jG7cd6pa0Hg==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:VzGbgA==,iv:iYC2HBUOzRZstgRXoQTMz3mkURW+FiqcCNVumfPqqjI=,tag:ZaqA9uHmoQSdU524ac5IdQ==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:+aO5rQ==,iv:eTKlAUGuxQ/kw52f/p5K/5Pq/wNmyLMoOiw0NYoKMEA=,tag:NkucA9LlxKul7h0mLpLDmg==,type:str]
    ENV: ENC[AES256_GCM,data:JvmnsQ==,iv:pXrNYuw2fJtbHPAGeMr9UBnrMAta1ZG0T7jNZ11VCXQ=,tag:cm1gXkhtYC3kl5nSX3LDMQ==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:1MGDaQ==,iv:gYXdmI2rG0xwi3fwo5GNoo44tM9pFpGJd2HNFS7xM+s=,tag:Gfd0wXA/ayZo3A1QSBH6+w==,type:str]
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS: ENC[AES256_GCM,data:MDg=,iv:/ZdxoWwF3SkCb9SfWYXZqsm2HISmeJMZwriGrxPT3W4=,tag:e7vsiWl7aGJfcb63JmYXYQ==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:ch2zhul8Bg==,iv:C7JqsSMpF6WN9i2eSrv1MiZ3t5xZ26mTaYNDL4rixgc=,tag:e5u5eUa4YL39IodDLWGOLw==,type:str]
    RAG_WEB_SEARCH_RESULT_COUNT: ENC[AES256_GCM,data:QQ==,iv:3nyZ7VhJRCvHATihMnqID8WM/a2ldnUFwZDvT7ODHC8=,tag:gHP+csvdYgffqpvcmSBs+w==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:xhQni97vyngWVXZaN7kxt84qMNal3iP7NpWh9sDvQtJ1YzvY+Cxv5NiuU1+0+Txd96rlWOtuIA==,iv:bb+qmdVS7AKNQ7DIkYDwl65jv+agpewkzh3XLsKbXb0=,tag:WMF2rsjvzeVpzPf6aAck+g==,type:str]
    SEARXNG_QUERY_URL: ENC[AES256_GCM,data:PYCbO5HvtX3YeuU0yaD9F97C3HPGw0PfRbWKGUKYuw==,iv:kcL3klwzO8dwYenHxH75H3Cnt37eeh3x4R0sZ4JnWYM=,tag:Gsf1xLfSbFjBENkCqY17xQ==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:27F0tA==,iv:Dc3azCou8wF4DGDQmRXfeDRA7PkgvncTOMcRXX9p8bo=,tag:mVjcbVF02ouzwtKQD/YEhg==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:yU/iVT3uw7/OvpdSbDB+/Q==,iv:E+yGc2C2jfyBikdBcpARqnoCyrI6/esJkwgg6muTjS4=,tag:RhjpHZcU2DmOpeKkIeeuuw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUkNYZXJVdFV1TGIvMUdm
            T2Zpc1YyQkh1dnRMWVpObEw3NUFBTjREQmc0CnNVeUN4cWdlbmtZenR0UkJxQzFP
            U1k3V0w5M25hV0tzTlY0OWFoSUgveWMKLS0tIEphMlZ6aVlJdWcxQXh2R2lVTkcw
            WVlUMGJZemxYWmZaVUp1YUpoVWNjSFUKqJSouWvkjZlnzPQjUmqVwq6arsm8R+m7
            7TQOTUJxEAPtitcOoDCaM1smY9ZoHD3x0kpOt+ArDWWhCC4utT11+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UmdmWlV1dVpuMXF0MHlN
            bXZlRHpHSUpSYnR4QmR1WDNiSlp2aDRVOGlNCjB5cCtFbWx2WkVsdTl2NXk5WWt0
            djUydzFEVlRJeEUzRWl0SlAvR0pGYkUKLS0tIDNFZVdTa2JhVi9TdlZQTTNYbTRr
            MlIrdEZmMFg2TFBDTUMwSm9ZYUt3clUKdADlcUgJJvNp4Il7ahLKQ3MhHykfyWAp
            YyenFHvgZ0bzcuCTX6Srdr3yzL4dTzmqJl55ifg6i1ssVRkGA4yuiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZLyt4QkRMb0I3Zm5LZHhF
            U0FLZVVPY1E0RzFhby9uNjY1eFNpcDNxYUM4CjBBcFJJMS84WFRrVXBqdE1kWHpN
            NFhYZmhFclNNYk05SFA3UXM5b3BuVTgKLS0tIDc5Rk9KdW5pbWJKclFXK2J4NkhE
            Z2crcGlNMTArTGhoa1orSHk3a2xnLzgK5mj/eNtF0bt9OQjACfHw6+6oeyNGZLFl
            YASlg1FmOPHcr3+2ka7x1239Wzox5RCzGBZekfdcKhmHIiy9BM3cLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T21:58:40Z"
    mac: ENC[AES256_GCM,data:0C52ZNp9lehHsFUadjE2FCzMCPnFYFEn/gQJfAQ8+FahGgj+DKh0rKJ6F7+Pw1/qZ7xizFATrJpGhvcVz6xatQaMvTcx9UfDrLfJvOFKjvaSN/M7ZynNAoqJ/E2ON8HwuHoH11O0SMFHsZDE9nVtoWRB7vMTsLr4X26JHQKZaaI=,iv:0BS91EHvIOlUQWvGMBdewGnoDZxpS41mgI1IfW3S6zI=,tag:32zE6as77hqTfkX8mommnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
