apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:C7w4H3IV0gjEbeBx+zyJKVsiWnr4SG8FG3eymbJskcN3zF/fWdtvtXutj7s0AKANGQYha1aaCfC5AWKdNlV5E7hb1zkU5FE=,iv:/AjjR6UOc4/xwHRp5ciLTQHpAHP6jjvFvn6MNhrReZA=,tag:+AZbnzzMuULV0k7+ZRUF9A==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:M5V81ir7+trQaDVB5TawyYGFPcDx7lk5dgq3t5vDt51FMbn5rb617K8NdZ3880nGspdrDSo=,iv:MxAuFrhNObZ6f2QD5jQFOFRBTBBB9L3/ccZxWBfVgJk=,tag:0cixmMo/dezt88uQ/WOmSA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UytSRFJ2alBTNG01L0s5
            Vlh3SE1ja3N1M3FMVWQ3cG9tN0hCZ0tZZ0VrCjNqbjlGQjF5aUNVa0ZGN3RkTlhY
            akQraGk2bThjNE1zMzVtMHB6VU9EcW8KLS0tIDFoOTVsTDNLTnFwcWZPT2JjSkla
            YnhaSGs4MldYbWN2YU1CTlhKTGZ3NGcK6HewxQg+exY43SqsrlHmqy4zo3jHurrL
            aAqX4LC+XvsOVcJ0/L0ne1haT33CgxdhzgWi2oL1DNru+EhyRxcirg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWVZORHVOclQ1bnlWK1BH
            eFk3MG1DOGNCUkJZZGhsMjBaM0hHQ3h4NVRJCk9TUnlCbXdhYU1uem1rMEVyV2F1
            RWh6aDNlZXYyQ1FlMzN2TnRRTjd5OUEKLS0tIEprT0prWllZd201K3B2c0tYd0ww
            NzZ5NEZWUG83NGJ5N3BVb2pmUnJMTnMKGWa2asGUSoeh23bkClrTST2arjY7Cdpp
            1ard8ZMg5r2wOa645SOdxzwyh/yGbisMuAJ1AglhXrwfqbl54BLLfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTGNMYXFsRGZBcHZtYXI3
            ZVp6bmNQbGZjMU9HTkpzMDk3eXJYcVFMQW00CndXemRBT0wzdWFIbFUydk4wQi9r
            V0xxNVBKUVVnRmFuUEdCMTZHTDR5c1kKLS0tIGhWakJIN0ZvbVU1cEhlMWNFWHRm
            bUMyTTlZdDVQejBhYVFlL1hWYk5XMU0KxXzqfr/gmhqEYxKk3HFNViBcxjigoKK+
            ZSVZJCsoW+oGpsTQqVT/F38NJ5pOVWKhpc6fV2ymsQFscw5D0YqArg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T18:27:18Z"
    mac: ENC[AES256_GCM,data:+S43Og2K/YIthHrt+phnpRk1lBIWZ4jKhiDPVbfn5MRTI7uXdh0vvi0Usd3bVn3NLwqRVDLooDCU6NJPQ43dSGg0Y9+KNGiVTxlxrXAICDes7pJ4KaTsZZBzHL39C5FtnJ4bBDCOCFemS1E+4dYH26Dox2Lz6p+5LX40c5Amvo0=,iv:EAxY5x32liQvFur6Q1Jz9EWLzac289t3jopnJg+VTvc=,tag:y8d3fAncNkOeL6nMSuoszQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
