apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:soGCwG8TBwjmYvJO3l8VVxsi,iv:QiM0mbQ+6CdB8RdPLBHNu5Ffv5BhaVjALYTpyZ8gt2w=,tag:v6IEEsJEY867BHWsCv2vpA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:iyoZL9l1NZAX9MqZqvN9vvQkIn9OK0201WR8lZhHvDpDmQeXjPTsXT0FdRKa8p+GylUcpgOd86kJzR9mrPshjfP6dDOQuA==,iv:q6KCa+fPgngB2YqxVIMuwXKuH9uh2o9MyIb/S5fUXWk=,tag:zWudxZb1l5+qRieGNy2yKg==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:qj0mmw==,iv:VEHENiVpTkTobEMgnoh2kC8LWf/cdFC9XmrhDRY0Vvk=,tag:UYjxOBlauhdmVC1gko3Mcg==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:h74RkA==,iv:UwGfDUJGw5fjjgwQyEFFUN/OajaJs0Wxh35sMPHO7/4=,tag:6GVBg1J01omG5MBVMWv45g==,type:str]
    ENV: ENC[AES256_GCM,data:7QT2OQ==,iv:uTCbOUhtMStHw3qK7ls6OwLTV7bsk/9WgZQfZQAR6PA=,tag:s9e677SwqWfI8pHApu7Fgw==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:do0FlA==,iv:UL9w8cTdQux7Gza5oYqfUyNeJjLuXe/p8nxVDHu9B6Y=,tag:j6YJbE2eLGea1+iMedSAdA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:tGsEtFr3Wqd4570tQ1cpgchDZo/jtDUamsAhuOaWswN2CF1vy+fHOaDx3eIwby7KLExW5TuTsg==,iv:bo4LUUjLeJlHLrRLdi8M30+yvL1cRSW7ZQHYgQYMBlA=,tag:Xmz95Nncup2/Nvn8xQ41Xw==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:4Bczpg==,iv:bwa7XeG/XHFpz9Rx9bIW3tVRATQmhX3M7ns877yYHbE=,tag:pjj0FrkuSvvbpEodewYA9g==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:j9Oy3WPskY23MY3Ag4kxjQ==,iv:8DOLyk9NdGg5iIAWhnnSUdboabMnFFilsFBUk3jPpjY=,tag:m4hTtcw9Q8GFmt66FyEs7g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUm1qakU1ZU9HSVFQN2Ji
            Z0NPcDB0aG14V1Y2d3BYa0lLMXo0UEVJd0RvCnhUTEhaZk5WbTcybDNrNSttWCty
            L21mVi9xT0lYY0cxRzc1VGcvcDF0d1kKLS0tIHN5OVp0ZWZYQ0NRQk1tbGI5ZG1q
            cUtZVEUzZXgwVmRFRWhWdG1YYmVUbU0KUbQQ1vP/dYqe4JX9iOGFJeZle7e0gvdM
            zW0ORNiJu7JLHxNxmozzltNYUUjQpEo1OiBBINxyCS+d1EmetXVveg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWmNlSnpjRVRwamF6SG9m
            STVDQm5hU1Q2ZEFZQVljUndPTjc3bWw1akZZCmplVElLQ1Q5QUdMakxSNitMODhF
            ZGhla0E2dS9rZysxRzZDWWY1bTVndlEKLS0tIFljZkxta1d0MXF2am9IcEM2ZjUv
            OXcxRmZtbmNjUVVtNE1pOWE4dEhabk0KxXlQCFav07dehL3EQP9e0VEUsnvRwsXv
            b4nCaAUpm9o59cl/fSecHJgB0AWutuvcYKAJRx/5mghNjMdYK9PDhg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YkFob09VU1NFZk5oSFRJ
            b0xURHhTMm1vZVZETXhQM2JpN3VkVTRkeGdBClNLUUtTSVdUVDBqSEZPQitTMFBW
            ZG4zWTBsZUdTckVWSDQxUW1IcklNSE0KLS0tIHNBMzlNMXNjcld3MjAzOEtOait0
            alJUdENHTm41R0dJc3ZBRVhmeTNOMm8KeoSyg7g78bh0XHtC+FsiGLUgVkRQ/nDq
            /7yX+pKMfQOuNsmo2jj+CYU9m1G/RPltUaQ9Y4wpJvU0+HTxHA+Jjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T01:55:25Z"
    mac: ENC[AES256_GCM,data:tXB0p0ZBIcoR5o0+2eb0WHZnNW6WRsTW8d71JKShJB7Ft8pOoWWiY8ctKe9zgITjrfFRVP05hE4ybyCpx3LXHxXQdj7RhmNZgHSU47QponsQVPwvo28CgtYHVC5hNb4vgAtFalOS46HSWrxot2hXxvpCty/0GIjtlA3KWw4x7+w=,iv:zD/mAw/sOq15/aKH/moVq4aQJ3wLVzrZPfXFh9whgog=,tag:+BkcJKHvf2fryeUiXpgmXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
