apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:b9ceOD9Qon0Yi5vBpz5U9PRE,iv:zz44M21j0NCzm+bd1MCrT2BPIcmYKoakhMdnT/JNLWE=,tag:rzjJ5uxGW+56lcdKJXh7WQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:vjeyWmsP1BOZDrCmsqHO+SClWiMZk+ffLE/Psz0gLvyXB+RaTVWDvfKxSUHQUtcFC4N69kM7BHIG/A7eFWm06BMNA6yDUQ==,iv:AIEhu3VBm64DxYUhYzncvAycuRdMCJPdXR/czoboRQY=,tag:TtoknFEL3UEftJkmJsezlg==,type:str]
    ENABLE_RAG: ENC[AES256_GCM,data:uWartw==,iv:POJD/MZRk2kWfDd+SHW4PXscEMMD484Nv4YQ83JWtKw=,tag:p6fWIHvpBAYH9fXhqpFNzg==,type:str]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:7fPJTg==,iv:8TGJxC2RJyDpWz577xyjsk3C00wukBlfz4v1/C/5oAM=,tag:4pgVODxQq6txl3apMxU8Bg==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:OhLEMg==,iv:qWsnt/bgJ0iiqLbK3OAfiG+8TmPqNz+TFZPb/kolhfs=,tag:libMCx6pFIm1R9i+ARhGaQ==,type:str]
    ENABLE_WEB_SEARCH: ENC[AES256_GCM,data:rGCGUQ==,iv:vJR8RLtI8A5jlkZ+XJJETA44uocWk7x9NXjIAZStBTE=,tag:PIITBt1kj3UOHpihNOylYA==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:g6q4NA==,iv:SMNY39xzkZbPpm9Tixe7Ing4mE9XrSX/3H7MGff/FH0=,tag:weJdTJYN6RgKQkqy96y9og==,type:str]
    ENV: ENC[AES256_GCM,data:NEZzDA==,iv:eILnRWvHEBWzn2/sWyaytoEGNr7r9B3PqVoncJKUU6g=,tag:u0jvavNyewO0VsFlAGLopg==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:IuE5xg==,iv:R4Y46E9eb99ukvqAhyCiN46JaE9yV6jwHsmZ0WE4fjo=,tag:lewbA89T8hUEzHSrsVSA6g==,type:str]
    PDF_EXTRACT_IMAGES: ENC[AES256_GCM,data:ul++lg==,iv:J74kq9tznfT8Mc9AismC0hgaQw0Z09kU5fgtGvZWUWA=,tag:MKmr5ZVKqOJ0jZw8S8fZGA==,type:str]
    RAG_EMBEDDING_MODEL: ENC[AES256_GCM,data:gokXNfkVNtuenMByim0ZAnah0wHZaUyUB+BIFmNGAGaXiGXStAU=,iv:MmzrLWLXgxVivTbrusatP/IzmV4Jxm7aVs3FDQ3ELGY=,tag:TP7uOEVzd/FPZ/HY2LABSw==,type:str]
    RAG_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:6tdf4P4uWK/7y01Oz3+Q/Ei/Ef1teld+w2DHHQ==,iv:CWc0nQGdEwT6GJ+Khm3EUU/KpdoFQfAAagz8aBQ4dRE=,tag:FjYNLvUk5o0+8C2RDxWhWA==,type:str]
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:7SrSrHZ50VAkjVwTIp8MygbwWBdSBY5cMnmp3r80D7WP3gCjvfYsk+JA0EB9eoFPwtj630JWGF2QScb8eeWzqmBCR4QwF7crtw==,iv:YebwBSMeBjFd1tTFtC1dY32MN/gI/aP2ePdOWHBE514=,tag:UNiEs2X7X0o1KEMdQKu05Q==,type:str]
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS: ENC[AES256_GCM,data:zbY=,iv:bcAr9UDpgEusWW9Rvj9yqZjdlFqyn4EgX+20H5M5qaU=,tag:iEVs1073Vl0rq9vDtOHYSg==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:0cwDwZjPdA==,iv:r4EYUmFfj4bRWwNT3jvYSNB+Q1p+bMDs73fAWAfZKWE=,tag:bS+0YXK5MAVY/Q/13MHmqw==,type:str]
    RAG_WEB_SEARCH_RESULT_COUNT: ENC[AES256_GCM,data:Tg==,iv:dzxqnkBk7jgg8rSCMLw1Vcxo1VDYyqTwszGF1ZDJ9co=,tag:sP74+K4fTWTj6ocztHbuOg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Dp5kOaq6NGmoICZ/zosbzcbolgtMBOPqU71GGq904SI6tKZIyMl+yd0I3lf5mZo4CS0/cUQYcQ==,iv:a1eqxk9KgG5efPzIJHc0r7E/Aze5RuDnwwKe5t+IVrI=,tag:KKAa0eBa+Xho4oDqhFqv1A==,type:str]
    SEARXNG_QUERY_URL: ENC[AES256_GCM,data:iA0vNHTdljdWmZ17df7Mzb8l60WThHBpoJyOMsPlHI5v4RQRmvbG8GncnCTr3hq5qKksxIJr,iv:Haie4R+sRNLw5uwPFSVVfhp3YiEO2d+zyMrMBOtKldc=,tag:iP30r2X6QLImx1FMfPEd6w==,type:str]
    WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:Y/LJRRiUxQ==,iv:iCXLlDvRk4bRaJhZUHcB8oXV6FNs8Z9Q1B+nlDLfx5w=,tag:vPXy5lTl7Lq8hNciOBoUlw==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:88L2uQ==,iv:6TKtxyREXkf+3squ139nXtcL7QuOubCfeMrWaoy3ZS0=,tag:GfJG3lE/VBd7m59DsuzE0Q==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:4QT5FdeidmGclWWEAhnmXg==,iv:cgw/cEq/1Z7kHu8WgLyvvavlqISyB3Pl1CxVJgIe8lg=,tag:4STfvSKQWDHIF2wUQ2ubTw==,type:str]
    WHISPER_MODEL: ENC[AES256_GCM,data:KqvcRcVI29bSkwVNO08QQxtSOW8sKaFeeSG4CRxewQ==,iv:Ih5ropSplHx8FzJqLg96Pq938OXTxdZZaN/63JMr13I=,tag:K1MknCQ/njos6d1IuQOqrA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwamczOXhwVEVnQWJGSzFB
            anJ5QUFuL0ZydWpqcVZlejVFeDFhNnorSkY0CmZuem1RcEJlZnZqNWIxNkc0K2w0
            ZTFta1dGelhWQlFiMTZrQVBSQWh0UmMKLS0tIEtVQzRHMGdwNDRVbGN5dko3RlZQ
            LzFBaXN6bkgxL3NXcEo0QXNuTGt4UmcKKCvOjnXQGd41Re28TNDXbKFNcHbMmHf+
            3IcYBPd59KmbYaB5z07HV9D0QVaLAZbdgagSKyd5pLKAKCY4Q8wreQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaHdsTm1ySDI2NEhFNXdY
            VHJ3ZDJuMi91Tm1UYUJ1M2FZTE5GSmpPMlRjCjdPZThCcXVQRC95MVd3Snlqclpy
            eEZ0cFZpNUhpaG9JaFpSVG5mc2wxZ0EKLS0tIHl6dDRseHc1czRvUjY1WWhDMC9v
            cEJWenMzcGVFL1d5VW1URzl1US9JM3MK3qk66Idee75a5/fJlGEfFb0GpF7qklYt
            rs5UWKzdN8yVZLc/KyBooyDzFKwzE2MqVYQtRF5CGaV2eCs/f+W49Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR25ubFlNNnJaNTNVZ08z
            YVhCMjh2S1U1NWNtdnpGRGpXV3NVazkxZmdRCnRHL3Q3dUhnZHQvVWNmY2t6a25G
            cTAxdlN1bHFSdmtOMWd3TmFFdDFzNGMKLS0tIGhRZ1dVWWUwUExOOGFPUVF6dlpq
            K2h3dXhnSWd2MitWUWIrWWRKOElESjQK9mHlO3r2MLhRTR0hgmwHZBDMJ/MGqWSj
            ontgtedoIxnTB2FMGGHNDS5kYJIuGGMHvXSdLX9X9KGiNPAQpHi++w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T00:21:40Z"
    mac: ENC[AES256_GCM,data:aWQJEoQG71WrY7Q0QZOhvjSVC/4cc81Kb2ekySByee7omjCrQS/OkJVTxg1p3arMLv1IQOHzXyeiewbzvT+Uq5tzixGM4Ud6cjEJhFEzGvzqG/O45qNvssTgSgnYXHZglpAU/hPDL30zLNsXZqJlOSwFrMRdOka7HyPVl5PYFYU=,iv:nLRbfaWqsD04sBph0euo3K1tchMkZatT1yZXyjHf0T0=,tag:Lj4Rq/DSjUbAT1Uqyt3eeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
