apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:y4qDh0Hh7EqxXyMrxhpoAUavxBqu+1+UHuqQPsaLjuFg/ldfQH08RCD8h0oqFFxB4Jec7OVUawOBKKBwpl7Gf20B+GMrYb4=,iv:xfL0Na6xQc9FmQxCKMQztHGMRwLRQj1+BK1zK1ZtX1M=,tag:V0k47bcqpEf8waeGV/CUGw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:WDprUBOI/8Cu7khMCTW2elZwL5mq6Krz9fVd72V+OKh8bbq7aWmpdT0KlPgJwfLfu8eCCXt+qQ==,iv:FQXRZ2SGxCy3s8iMUr4Mh/jbPhfDRvTwYEDJllIDf7M=,tag:H8/D2rLqVPojIdPiUyUidQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SDZPRDZlNE1idVFyREVC
            VHdtTEVycTVQbGtCT1k3WkVvd3FISXQyV2hnCnhvRXJrOVR3WFFKSmJEYWN2UWxl
            TjlJTXZUNU5HeHpManFqb3NzMkNxb2cKLS0tIEJwbG4yZ1NxeWplWkNJcG1aMkZp
            a0JLci92NnZLREdUeFFyZ2F2NCtBU28KYqVYTeEUdXGWm2WW5KaXdkWKlmHzFu4b
            K06gIAJzaZrrY5OmZOuP8foWiggDFBwpJamJ5W64P6L63Z7UXXVWMQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWTJmK09VazZpMlVuQWRQ
            UXI2clJxK2JpK3V0TDlaaGtyOEZ3elFFcmp3CkpKamNFcXExSWYwS1pwempMYnNW
            N2xpM3pteC92NFpZUGlBTmJ1ODIyRGsKLS0tIDBCNjNJclhTaGRlRjlHVkRVeWNi
            WnZZRSt1dzNTZ1RYM1NWNnNrTmNOVkEKGd4rS5Vf94x+LbPAwUVm5D9FCfz5BvsN
            L1KkbVyx4CZ0CtklXThtBTr9azUc20EsKWfwaRh1AQ9chhCB1xM5Bg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVlFlSDlraGxxQ1NuRDBy
            WVM5NlFxU1c1bWtISU1vT2pZNW5vcFZ4UldVCnV6UTZaNS96ZnZNR0Y2VVNZTjQ5
            ZFplclFOR0VBdEN4K1Y4bG5UZUEvQTgKLS0tIHdYaUFCc3RwdXBFbFBqWUFSaEdD
            R0x0T0ZPRjF6L21QQWZyUG5hcWxBY28K/YI6Q8WrHKTY45mshNx14AE8gCEKaQPj
            jPSavOtn6/oUN52OXtQ5Sl24CYJJbELmVvkU9rHsK7ufk5KRGy1O+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T17:34:51Z"
    mac: ENC[AES256_GCM,data:M6Pt+ndqcnSF7sXZ7MKgLLI4hg9cRlfxygwMppbiWJLuUF+p+7bVWagn2YRbZ6NVEw2eGUggeLjLAs037aes37TlBo8fVJWpYguniitb45tm4jfV9Hp+pzUDCFgimF47vk7nfLb5UbqD6zHc4cpjzWbki9i3VfhSjc/GKHdidzQ=,iv:2W3zrpWXyx+/cWzsG4Fmh+x/U7puFDFAGwUkI8vm93w=,tag:pXDCZRQDR1ElOYgoqiIS7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
