apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openrouter-secrets
    namespace: apps
stringData:
    OPENROUTER_API_BASE_URL: ENC[AES256_GCM,data:TLpQCcMBmk6tWWft7vTl0dSqfOA3skvn8flVpQ==,iv:hMdcVFNXAGPBWwN/TTiNXSujBHo65a9vf6KvDbPyYS4=,tag:/nzgCVMRkX6sCLF5nkTZaw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:IuYLLklJwVafo02DJJ7p4Omj2eX95T4h3a/kt501R94UoRVcR13c9FSLBjmMm+ZIs4uAWDCyAJ4dn6lapUwtmz4PpfYWViEteg==,iv:buFdowsIXivuyKBFqTgGns2BTIOneMTRQ8KXx37t/FI=,tag:GCziVm/0mDrdgywrBJhP+A==,type:str]
    OPENROUTER_MODEL: ENC[AES256_GCM,data:ekIR9UbOxsAJm/uf986VVPvugVp+f0Age/GExU8KN3g=,iv:qtrgJ3C198wPU3SphB5Ev8ARugn6uSUtjSxP68uecZ4=,tag:LvMVY7ITdRGF2EjgunDkHg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVGxUNVZyN2VuS0ZBdUdq
            OVNhRWE3NHVRcE1ldlNoUEQ2RTNsRldXSEgwCnVvRzFQc0cxM0diZmNzMGU5VzdP
            R3VFQUd5MjZaWHlaSVNqT051YndtdUkKLS0tIEJFZlpVTmdZSi9tZTJJSW1oSnp5
            Rmd3MXZsUjJEVjcyR1QzNE5ocTVxL2MKQhLnm6NTbpRE/KgJl9GfaqhfsPgxQsLY
            N87pTw54+G7p8x479g7EFiJIWiJSidZikIui3KvWvCKYdWSJ+7Gjgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRFVJNE5zQmNUbU1ZM1E2
            a1cyeVl5cmRCVkNtdWh2cCtzaHYxemswNmk0CjBObDRiQ3pjeUU3THFjNi8wMUo0
            UVY0eGdMeEw0RE1UWEN2RTNnd0ViLzgKLS0tIGdNNklLbEtVNjVYZFRVUC8zQ0t2
            ZVdQK2w5a011cFhZTUhPbFB1c1g2ajQKLYfjgLnZAAyjFCCaVS2nJRMQK0ylSm8S
            enzlkhydJHlJ/tqyTZxZmS+TnpLMviM5xBmvJNMwsJWjfYYgMepygQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M0cybVdoaktKMThvYnpy
            ZUswKzhCdGVyK3dBLzQ5ZUtGZmFwWmJJYVE4Ck1lRnlMUk5JS2J1ZFFnUzNSdFNp
            OXAzd3MrekViVGVNUEkvcEdLQXFPQ00KLS0tIDFDektzTTd1WHBrTTBHaTUrcEsy
            dVJ2NmZ2OEZ1Vms1Zlg2Zm4weW03NnMKKhaV/eBASWQ/A98LH5C893dcPcqFjlca
            ksa3mkwEPCl2TQoteyTUiDUE83bC2rviZ9wRsrKK/ASMFQeCemMV2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-14T01:00:52Z"
    mac: ENC[AES256_GCM,data:n1/XQmrUb1TcxC+i4NSOFo6wm1l/OJzFWyNpJnUXc8xVzoFlHe5QItHxBJRt8vK93M2koIdq0n+nyOnm7LvIxgNszU2IFQrGCnkDX+iSSvkeZbKRpHhG+2fhCWJwr//vosNKT90nGdJFBpGIYpSguuahSOF7tYlliwBGLukQQdw=,iv:LrLIpFhjAwOiEsUQg147YqimytEaF2mQflgqkMnB0fs=,tag:8TU87vbA5UVD5AyRYl6iFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
