apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:z7vBsGbwFclsgrKr4ryxWbQcl9x0B8WcBZ/VbnumBw8hmlW+plYnuVRR1wMXysJd8MranQoCmYEdjn/X73qxxNq81EzzPlk=,iv:y/81jT8o6hBTLYmkgaDa7aGbYbqPyBdJUfqpDDUXbiQ=,tag:9Ah+jOEhh+10nIuJ28WcYg==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:QIWP/2g=,iv:PGDaxozg/bRcezbZhhG5ygbyiwNLcpLVInmId+BAYmU=,tag:1QTHdfd7TnEvrdPCL/O/zw==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:xQf7oQ==,iv:j1BLxr/wfxo7/QYaxhf+s4ihq85vvw7ydW5DXDyPccI=,tag:R19PAgdei9pBf30iOUSSaQ==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:+M0G/Q==,iv:0XPrkw+3AzzmowbVkHwVVbY0diIXEvdAub0N56Mw8sE=,tag:dcRTtX+UVQuK2eFG+hknjg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:z4paRJF4DK5/emjx3wwnat0Y/d7vvKcyiJeTauP/O0tLC3ET/GRaCsNDXUDPWbTSOF3aZp5v/w==,iv:UZF7vEI+sP0/wb9UyshktYMPdNaDfu9dnb3x/yAMrKQ=,tag:yAaEsB3lH1zbqgjjfs4LqQ==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:I+o2gQ==,iv:JL8+1hZZd6fH+caLWGdZ1PAqCLxIQ2FPYOnP8O3MQV4=,tag:StZIcXjMFYmhAQOEOnj9Wg==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:f4eETepYaGfzJQmLO2yE1A==,iv:lsBzX5RODqVBfTZ9q+1onMSrvq9Mf5nXLIFT2eTfFqM=,tag:b6nmr86Itoiv283qJO7cCA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSXo0M0ZFcDQ2bkIrS0JL
            VXZTaHlZRk5ka3N1T09lNG9SalFySjFXcXgwCmRYOXNsdXlONFdMSnlqT1ZpVGE4
            c0UrYlBSZEFCYmZ6K3BFS2RCMnhtVzAKLS0tIGJpT0h1TUF5WG1MWjIzdXNSYk1T
            THJGczhDRzNRbGdzSDcrTFZtbGlvSm8K8/ytvD1+YYSIIpntI8yeJ1wKpfLh61/z
            O9ZrvbslX9pMtBbfDFNq/7nG57CP7SFinnncia1lSPC5k5WJUDOvnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSzVoRGZEWW1rbGFpSFYy
            WnhwaDJNbG9hTm9WQ0dBajBOa2xqdDZGTFhjCkFSTTRjYk9zTTZ3Z2h2YmtxWU41
            b2RpSDFPN3REbHdBbU9mT1U4d05aM1kKLS0tIEU3d0lybm9BcFhGdUFzY2g4WTYw
            SWZ0WkhQNEFCVVFCeUEya3dxU3hIRm8KdRGPm6O9L7yGuknqEMC29AxlmxqJ2r6E
            XngUsx9TW+QDFaReeTBJIGpc87phWCwt/zlTlW9dkDQwjHMrhsDarg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TW1kRW5GVFJ2WFZqbzZ1
            QklWQjA0UXJlcmhJVTU0a2dPOTlNaytGTlFVCjFTaVJ6blpjZmVvNkhFRUUzUW5I
            cTBnaldkeTN6cWQ3K1lsUEcyNUlPc0kKLS0tIDRpejB5V0dQekUxengzazRYNlFy
            elM0akROQVUwc0phZ2lJaUVFVHVjTDQKyV2x2BFMCIUX6V5o9mkxuPrq1MKVTN1L
            onCrKuFJrFBrFq0xs50vzRWvAlG6pCv5VMWQunWKOE/PrW7gQcKooA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T18:50:20Z"
    mac: ENC[AES256_GCM,data:I7lz4IUBDWMrClItvWoru0OF+NKkY8FobBK50+TadLC1SAcsnczoc7I2hu/fh4zkpTgEiCxqhZEwdop5wjqYl/tiH0hmMc3YKu0fkIj9VeTvJWwiCy7s3psHtGEBSSqqFWqB3kfVafEDC3LIeOuE5qmvWDk1/68FazbvrHQIJBk=,iv:60NeswexRzSbihsUABWCnhavtyBG+3e3SDyo2F0v3pI=,tag:tpjgeVImPYQq42dfL+xfcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
