apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ZxWbLFQ2grC3fgmys4BBzh+BYm8Qo+QXGH5UlAWJTQwjoPXlCJv0FrTtNwhc9C8ftHKJDRkZr0+/KgBS6eFzoAmjCqV2k30=,iv:5pChWyJtNbIjIXr8syZutWUAM6uq7T6m+DIOaVj/jyw=,tag:5fLaoQxjU1XIJ/oTiC02TQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:SeMGToFT1lrQKUPRlrHVuhUjNhw+EgdAmbu30P7Cww2RB7HFsxFeXeaLmzyDI8qhnIA5dCVXfw==,iv:S8qOHqTq7VzdPwyx+Yne3T9z8GWxn8VmjXYN5FdjAOo=,tag:UE3QyRbUVjW7Eqca3vceYQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM0ZTYWR3V1A1K1Q1U1dh
            aU9zeWd4WGJ6ZDBoVmo1Z3h5OSsyTGMxdVY0CnhCS24xWEQ3LzNrVWZZNHBDTml2
            ekp5Z1pQazBQaFE1WDhJWmVRaDRBQ28KLS0tIHBaNmsxaUl1WTRJVkVhUEppMi92
            Q0hiTEpMMUFGQmRXQUIweGpCRWRoVXcKTEmNcLKG/3dhapaz0nU8ewx8vK+GgXOb
            HOCB6qyMFXMQIeEhwlFXeqcM6fyTUaPRNseTNs6HUAPkiAydhZtscw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOVQ0QnNxVzhKUE10UTdV
            dDJ4MEk2c09HbDQzQlNGc1JIaXlTNVA1YUhRCnczbEtEcVZEYmt0ZDFNTm40cUJJ
            cksyeWpYVzBPOXpuYVhsdXlrb1M1VjgKLS0tIDI3emdMdDdYOGtCNnRxdmVKdVdU
            Z2pSdjQ3Rm1rYXJITEFGeU9QNzdRVm8K0qYeeyil0QNtDMROHfR55T+tuDIg5ObI
            Zx3Bkmb6Lp0x9hM4gjeizjKYdNesKFo1IlgbLbP0ZvZOUhcjdV+L8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibjlvcEx4N0F4M1U3akhO
            WHpYZkl0L0F3dzdxMnhmN1V6TTFpTE5EMmtJCmFneTNDZDYzMEszaE9JQmlLN01R
            OUZxTU9GWmdMeDNnNTVnbkdnblpaQWcKLS0tIHMvaUM3T29DU2k3aHR0ZkNEa2Ro
            cEVONExHaEM5UUxLd29oVXNMU3NERXcKLZhJfD9OYyz+mmrsApV9wQtJWdjY1Yzg
            FLOHuR+6A1RUTJF1FyGAK5rUyaMd7tBZRpjxaiIJjslKgpZl0Sw+ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T18:17:34Z"
    mac: ENC[AES256_GCM,data:N7MbfCfbHBkl10lyy5wtx1dQ9uCjXED/0+ijlNz9kjvhe7xDmSG79bGINMSaB8BJuX1KJVH/YIJ1Tm2SOP71eZ2Md98IF0VB/mpSFe6sIS61znEjVN72JMaJwJnp32FQKzG7bb7p6jG1NliZEiS7QDIf53OlDU3MQOhSqd1UC04=,iv:04gU6YOJgtokOwDy8I7wFh1XCqlWsTuaBTWx7Ty8ZU8=,tag:Ty46AxWFKodpb5xqZwvbXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
