apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:RgPpcmem+5Ajh3zt3SpBJeYk,iv:PJuRjBl2JLB/My7lWsVqGSf7gWf9b+5UCdWeIw/BFI0=,tag:St0JrM4a5mKN7kxTdeXsTQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Aing5D958Latv+d10VRgJUitSe3lfjBjZD+tPf8QTcs51Ee3+51PjsYyBLKCQ5m82Q4nrGcO56HCln0B435X8KFZVHsQ/R8=,iv:v4iQXXBEgZpwksQ3FqNxHks35NdOfWVwMBTkECl7B9c=,tag:1tTlexp88BSM6UelUhHqPw==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:nUvM4P0=,iv:kMUtQs6MZS3srieC8MNHTFBV1QIZIxEIG+yVeLDClPA=,tag:jp01VOj4ijw3zHN04ie5Vw==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:/FtCow==,iv:DCNQsJPpdlTJPqJmBrPT2phuEqASpG3yqYFYvoT58JA=,tag:lXUYLus2aK8CxZx/Vp5OCQ==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:dT6eLg==,iv:dtDY2TNiXup/4c28JoEaEwvGkPx4dne3XDWKn9riJHc=,tag:64Qk9TO+hZrJIc1+csYboQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:S6AwWpYOmoWDQ/JyY/5UwqF4knSK6TR7rwTLucvYD+9eIleSCGk6C/dcGyNLZCOIyV/YOER0bQ==,iv:s4vxc4wBM6BehogonKbfukwV+O2quFNylL4EtjUBztk=,tag:4dFGlApgQgMzWvKc8/Il/Q==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:8xACSg==,iv:xYiG1pz5N/GTBiwSKH3bahFvJGd6EXDjC4pelFmVV0k=,tag:5RpTDySnKsRpeJBjfZ/ppw==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:4AhIP39o3vGalTwMtIzNXQ==,iv:UteLfml/kCqoWTshGwykm6rU9FQqXMyXwnBUseFHQSY=,tag:5IL75ojUILVZNOXi0yKekA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaGt3N0lzdUNWRytUazVB
            WEh6TWMweXh0c3ZJdHNJNTBlOGw1aFBJSEN3ClJucUJnUDkveHd2WkdnT2JHVzFX
            NDc1b0E2a0J6SiswcTY2ckJZVzd1T2sKLS0tIHFBTzlzVlp1MlYvenUwMDNNM1VF
            d1JSdjJXdG1sbnJpaGJhL2ducEF5SzAK1UP4FynskHXRnsfofQmxWhlz7T79kCjU
            QQr8mEQme/fcK/CYhNj+U5VmE30eUaw0vAVaxkWgWIx0wLyLCwLTuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WFkzTzlOaFVKVXVJbkJT
            cC8xaHY0MnJPVVdLeFVSQmgzS0llZ3FlYm1ZCjVNbTE2RFlZMzVTelRaM20wZXRW
            MlFDR2FFZ3RNNVFGNlFndWRkLy83VTQKLS0tIGdXYmVEdmE1YXRtMHp1OSt3QUln
            ZWJuRTNNUS9RVk5KRmV5SmpVMjYwZkkK0+X9dI77AMGWL7Zi7gIpYzGEdTU4zA+X
            rRm9tPp2GtStVpCQ/Shj596r5nSVWqUY+35amT9X9xIJLl3PvHDqeg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByY0pJWHJlYzh4Ump2RWpO
            d0JaendzTkptWkxXdkNobTg1ZUJseDYwRHhjCkx1Y1BwT3dycVRoNWI3Ui9mSUxx
            WkFQQkg5aXNqdUpyRjdqTk5RTnNNYWcKLS0tIExqeWtuZGJSM3ZpczBGdU9LMVJB
            dzk1dmIvU2prYWxiaVdNbHBNVVNJVm8KQAperDTdbZ9UXpChcz72yOn/or4yaJt3
            s3slK/PQG2dtqUpm/n164K+2JP1rHR11vPO/3byprhxDE4/WU/XGyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-06T19:17:46Z"
    mac: ENC[AES256_GCM,data:f1+FkFpQW3SfCldFEGV+XojCkMeWz5MsYkQdNDraKnzGoErMqAw5XoYzfrKILc5O6nBTu3571c1KmEwZgEFhXrvpkZCu2jomU7RcZdsX/EplN+aKbzs4pPXaQVNBn4S6ZU9qYqMVf1DRBVvZS4ExwX2mSd5RqNPDMnj8zWRdmgI=,iv:3GOPumOvON54f4urzK7mQ5KHI9Zv+IKDHnVVZxS3qUo=,tag:cNSPoLzvIBnGxYL6tj/ZdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
