apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:1w3gUnxSBgeg2wv+pTzPHUbE,iv:mTEakFEKDVSt6G60oPXQoNIZBu9ws1i3vQNFydzx+rg=,tag:DY6iBDX2Zl7O41JvCTgDKQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:BBaloSOx7RNDA4+GQFMbFvm71k3aX2OQD+X/DvD9v3ckLcf1awcYQ0YZAvkq9Svy/MSwDByec+bitz5gpPIoJJDXBtZ+Jw==,iv:kIjorEc7xl6diDUJESMnVIrAdAF6kpEC144KAXvR8fw=,tag:K1Ds0ysklPXR08fU0JoMkQ==,type:str]
    ENABLE_RAG: ENC[AES256_GCM,data:h8h2Lg==,iv:wBpYQUD9lWIc6mEIzaZoQpm7s1zZ6tZegjrGerXHyuM=,tag:PuncWTdqPiP2QEykQlpGsg==,type:str]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:ZHbHIw==,iv:/MnRKUM4Zn5xrMRXZQvbt/MjH0jXqrB59Yke3MVShZk=,tag:QxsgC510zkPluGKpFq69Pw==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:79bjjQ==,iv:ZKtAbLdH/lIHXEZQ5BbMPKuhXlPvhZcjGOkLtlkkX5k=,tag:92KfDhmI1VrZbbDDbEx1jA==,type:str]
    ENABLE_WEB_SEARCH: ENC[AES256_GCM,data:yk5+1A==,iv:+bf3JUIp3dbAdNnmjwC/5INF71IRI4wrifSLNpvM460=,tag:fXQliAShAxtrFytQk2T/aA==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:/2gHxw==,iv:xcY/AgxqVUVrZ4dHel6jqIjcLcq1eMWieS+WlA5gdzg=,tag:SJbBGm9zHLXm+wamaD3GLA==,type:str]
    ENV: ENC[AES256_GCM,data:km69qw==,iv:kI1jw4K313Brjn/Njy/D9aKbdTLS3tYcGM7sME3sl7I=,tag:zBcjDcXBKcdtjzrmhibJyw==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:u9E2oA==,iv:O8+NxhOF0a2SJy/imjCpvRWbnKQvSLu5ADAGwr4Y2E8=,tag:dMDtV9jQKOeeIz0UTpYtcA==,type:str]
    PDF_EXTRACT_IMAGES: ENC[AES256_GCM,data:XPgUhw==,iv:l1oMmoK2yghPyZ7trhDTsHkNPrNDkszUJNqC6sJOp/k=,tag:+uPZNPK65aKh/3jyvpw0fA==,type:str]
    RAG_EMBEDDING_MODEL: ENC[AES256_GCM,data:Mgf3FtSIRQZrYMg8JEdC0UdZ24NKBi7eCCjuMWiPMIESzkj9hM8=,iv:2kYws4+LqrV/sHJk6dyOlGYh7RULXpCKGVCr/MTiBqE=,tag:mr2dfsQrz9lI3OzBQk6Deg==,type:str]
    RAG_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:Qx5TC1pfYNhQBJHpDvgjWy5RwMG8BHHC50WbmQ==,iv:sMvRcVm90qV4Fx78fdPGN0I94NImBE7ib9C8ZFLlecE=,tag:FVTQMMzHZ1mNKYdySHR1Tg==,type:str]
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:cTWgszJdRuY74t5YWTp9iCO2P+TUO20Yqrt4BhZDKXPAKtXFE3JH+siJ306D2IC1hJaVriAWuL8vQyFcwEZaYm5IRnghB+BbqQ==,iv:+CboH7L+G8YZ0uzucl0z1GHGZ9U+NKsd6XIcM7+Uz0M=,tag:LgOu3waovFCA+bldPEQmCA==,type:str]
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS: ENC[AES256_GCM,data:+QM=,iv:YQEWrX+fv7xqqJCYRfadsEDuf5uum44ee/fm1fndEfw=,tag:IvpNrau1A9/cURfiMw/wlw==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:kqEsjAj5iQ==,iv:4nzjd5nOTgL6dHawUvb5zyondR5jRpCtnYpWvGeU/ZE=,tag:VZfSavDdj+I2DBgYAln2tw==,type:str]
    RAG_WEB_SEARCH_RESULT_COUNT: ENC[AES256_GCM,data:AQ==,iv:Dmm12jNz8MrP9LEH3bTm77jDTGvOuqyfPX5MHN9m3+Q=,tag:eZmxjgDnK2xE+GpKbPVanA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:PD3GCZcpxPvAH8PKKAizyh/RScKfcUzowF+oJUof+WGZLMjEsc7AocuxHoZACxW4gSIZoVh2kw==,iv:POXuc4tp7kPx2gIWQPevK7NlA6ILTaDIln3yx6eOAhc=,tag:+cr7RGtcXcKEBFa66qTuMA==,type:str]
    SEARXNG_QUERY_URL: ENC[AES256_GCM,data:NPinlI1hWwReCQmH12TgzTeBHrh4zzSecrC7fExQO29SWgvXGS1VHX0Ir4qw2xgUxGcKgzNs,iv:TT970IIxh3GU/rgaMCZf2MweosNmUwWYAKX2/MuDnv0=,tag:fXbvbMz3ziLokGJxcWsDTg==,type:str]
    WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:YIWer+JFIg==,iv:Y/VzDupc5Ewxv17IidZoE22wEEKZwmbAyWuHWFg9/qA=,tag:6H9evOC8MUt3APxcsHyguA==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:trxH+w==,iv:3PdNeZQLbE3IEVPqyEfHkOJzJpcxIhZtrp8YceEbev8=,tag:O6w/uwsXhKhQs5zkR8tE1g==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:lSRoes87CfD3ZMRWRnk0/A==,iv:fJiP9HCrG9ZhA8Tsb7qU6Zb3U4Z16t87AKaIa1YCUPs=,tag:MK8duAPYXruV/0w/CP9eyg==,type:str]
    WHISPER_MODEL: ENC[AES256_GCM,data:OorFqUMz/3AWAyKziNqlOkyxUqdL/YhnfSpN,iv:1tzreriWnq8T7ukEYbNi9+WMtXAZnS67t5Hg7rL+HZQ=,tag:vdssWl3vN0gLVVY45q5aUw==,type:str]
    WHISPER_MODEL_DIR: ENC[AES256_GCM,data:Tq4CH9PnQzIqzckKS0Ii/nBxaCJpHXh0vc9gijjqSkp9RJ500J8=,iv:Vlc2EcTFm1DsqObpSKmK1hksgYIezh3zDoFzmfAQycY=,tag:xvv1kXg4zDcH4W9abRIzNQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdkFiZmVEczBHWjNFaVVa
            T3R0WW0wRllrYzVVSHE1ejRQVGU0Lyt3QTMwCkRFVklBenRFSEdqSnFwYitCN25O
            azF0WEQrQzZjeW1qODJWd1dsbms3SzQKLS0tIDZjZ1IvWWpSeWJ4c0ZEQktyL2sv
            RmVVbTkzTjAwUG9OQm1SQldBTEliVVEK50F3ydIkAAo5TaflvgNmdtwpyjY9zubd
            T393pB4xOA3/e9HQiwPCFimQhTJr4E9k2z6xCGJX/6K18hsmaPp4fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d2s2UDdUVkRFdFFJckdB
            eXkrNGVDYTVlcXBQdWxLczQ1UVNyTTNZdUJBCnFOVnhmT1p1T3BZUWFvc0RuaW56
            a25HRkZyY3ZCYTFSTmZ3RkpYb1ROZ2sKLS0tIHo2UVJQV2FCRGNxaVNJV292ZE9G
            N3pIRS9zeXdvUW1MZ2lteENKdzZPWTAKp1ltYJM6ikPrBB2aDnACqFJrbAtbWAEw
            5ijaIK+2pwxWbVFkNZuzl+vFjVvQvlhInUJcEUdeHxlaZbjDksJL8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWmtobW9xZXE2TTdCZ2hi
            TzhTTVBQYVZvR2hDbzBiS3hISFVKZ2x5aFdnCnRRZm5kK3VldHgrS0ZlK0t2VTNX
            TDJMMXIyT0NUUzZwSE1pdTk1MTFLancKLS0tICswWDZweEF1WXhWK3MzZXl6VUNi
            MnpQdjFCem1ZVGVhbXhqWG1jSVRSc2MKGXwHiDL+Qf+5PvX14vDnb0FYQMWMBau6
            z6cyydG0h6sULRF4Qbum++lJpsEIkL1ALDteo7LDkORKHH0vtXc9tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T00:36:12Z"
    mac: ENC[AES256_GCM,data:IpevUa7SaQghrRlG+GJ0DfmCsRc30cCMzXUjBOVyRNL0Bo2SGE6jkFVouv4adp3Ly/uYi05QtukNkNSbuugEgKuV67bm5WVetn7EVRolcr8yaeXIWzoEJBN24Xi4jdkniUZNXModxRIoSXSVxmAjjsN3AP2C782UKBRHYgcKkH0=,iv:BhfadyBBeulxx1ULnNyGP/1pZNxA+b/tXG4KNl85uHM=,tag:JKY1oJ96r3AbHgpMOLnbNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
