apiVersion: v1
data:
    password: ENC[AES256_GCM,data:+zXR5RNinksA2O1n/M9+H1jRQl3o4nQj,iv:LgKU09gr8Pzg+lgshe0ZhjS/y0x3SyPB0Qn3Ak0Oczk=,tag:5qcNQlEMtaFXRBR1zZkNFg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUlZ5S0FKK2U2aWNNdTcv
            WlQyRVBTbWNINEpaSFluQnBkMlN0dlBjRXlNCmpSYnVZY3N0UWh2Q3JTUzA2eVEw
            UVExdU1EdnBIL3hrQzkvOTZnT0ZtdlkKLS0tIHYwL05uUmVNUXdjSWxmaTZDSTVO
            dnFDcWV1TkJ0QmZGSmJWRUJjclZtdHMKZwIUXK6McVy8Ah17XNHhnxxr6OmYdYbF
            AAv7aPdPNWt7KhtDSjfuGgtp5j4R70GOFWiDXH+orth0KwkTt2lUVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d2pJTDc3UmZrQTM2MmhD
            SDRvYWFzKzcvdGUvL3RaWDZWNWg2cXV2UEJFCjZ4YWhnNnpEd1Ftdk5vclFwSFBv
            R0gwWkpRelVVWm9kUnBGcTBDeDV6VmsKLS0tIEg3WVFhbDZGWG5MMU9XcEVvdVRC
            ajkzZnhsS3RxQUpPcHVlOEhPT2VyMm8K1X3zk0siiZcosYYYnqJY9M5HSWwGz+tR
            8aeJEslb4L+UvCN7mz2+8eb2skKKxEHDlxyaEaFw8ybMYuUZSNqHgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZkhRSDUzLzd6blMvMEhW
            OGNWSTQydHo3TnpXU1BkRXVWQWswYmluMnowCnV2cWxNQ3lzcXphUW53MGJIWGEx
            YURJZHpPMXVUZmRwTHlyQnVGRm5WLzgKLS0tIFc2WVRVY1hBR2FEWVFCUVJPY2VB
            VWhETytwL0gxSStrWlVuUVZPNG96NlUKa+4huuuiLwvAszKa6qDRG9yorD4q01O4
            KaidXPIgIqHRL80Wv1xhCidNv/Gojzces1R7Zay0TxYvap066QLaeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T15:17:29Z"
    mac: ENC[AES256_GCM,data:kdZmKMjle1wizci3zKUhSqoqE36ZyLxWk5VmS75jEs4CHyJw7TN1KNARjMKWkI2k/37nryHNuQtZMb+iNfMy8pOijvlgTIw17xW1Yai0fQrbyuNgxm+AEstz9bM2N8BjMJ1rW5K4imqNynNksYX9HdQvGTEVsEURveOIhK4MOnI=,iv:s3S+RgDhpXeVeneX1SyvNQO2fWgemLMhdfzRWRq61C8=,tag:aLxEOOJub+xbGI+00QCGIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
