apiVersion: v1
data:
    password: ENC[AES256_GCM,data:IR6sW1wssyO7Wsr4JKizqXzjwjiWNTdw,iv:55l22xh9964oOiy7crFWi3y8DmNfj98G/muUZrG2x1A=,tag:1G5/hQfQcVDnsM8MxTPeCA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeXpacWVGeFJVMldtRlYv
            Nnl0dU1ML2psY1dybVRzU3FaNHBRK09wK2hRCnNSWTRHNzh4bDlOL2lsakp1SlQ4
            QTE2NFVuWndMNWFvVDhRajM5MktkejgKLS0tIFRIYWZETnVuS0hVbnFXZHd2ZmRL
            ZmJyeFhaS0szMHozYzZpRjVlM3R1eHcKmYlXJifKnw5hZ/tccE7TO3lcAUZMv/F5
            vU1NIaGBQ8ZmGK+n7QpZCOiCZKy1hGvVV0tDKlCf+idTbaH7rq46Ug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dXZjM3g0cWdadFhDaWFX
            NHR1a1BNUDZDWTZSMHpyU0RINVpjblVPZUhFCmxLL1c2dHhhMVFFMzNJSG54RXl1
            d3N0RUpibWswSmN3T2Riellvc1RsbkUKLS0tIFVSRG5IRDZYQ29SelNUUjVscUJs
            cEM3blBlZWdiQ29JRURCeFZzRVFpVVUK+NgIds3bmOJ3iP6kdy7nQw3J5VVD+Wa/
            ZPW17ZqULnJpsCTI8FTulHl3m24ZeM0Nj9Xvxlly9wD8o+jeyoqzXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaEVCVVV6Z3g3ZjF1cDNw
            WTBiL2tlWU1ZdW5uU3RaT1A5RFFKenFoenowCmJZN0xoVFVJdkFXV3lNQ0ErWTlt
            V2FnanFFWWlvZ25oOGJZVjVxblNuMTAKLS0tIGNKRTk3dDJES1VpYmwvNDZ4eHY1
            d2ZWU25jVzU5endqUWpsdkxoYk95MWcKRRSoiA5rdHKuVZyzGIprtlIQLk1AINAq
            JgJHP3TFuXYASJ5EhIu/CEEnX2rXPcEKgFPOws4ngikrgQ8P+zCAGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-21T14:31:48Z"
    mac: ENC[AES256_GCM,data:bMM/5X6Xh5c+H93mUVN9aWcOacChUxFcZ5UbIEiFzUIpLtyOyF9WQ4EHe+1465u4CNaJMFyMaDPSzt4XmrYbOg0kxJwy3sRc8DsnPUs/oBN7tTI+NfIhAtewwrflDd5NieEk9Mh5MrHspmO+zXlkr8aKhYEP+JjlxAHfcr85J7U=,iv:D4QyCSukca0bsG2he8BDJZ5ZfpbQR/89axxq8Koabfo=,tag:QeasFXzLwSRdj3KwklH7Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
