apiVersion: v1
data:
    password: ENC[AES256_GCM,data:AK+Ur/z66Yjop6/fQT/3/USSw3vNVU4y,iv:cr8GRk6ioPWulXhykgxcOMpNmDyX3prjKsCLh7HSbKA=,tag:voQWL7HDACR8IY4K3rLT2Q==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWU13MWFkS3M5dmZGNkJJ
            U2JZR3V6QTY3NHpwcWdWMUtGWkg3bUFremxRCjFKclo4V2VUYU5qWFcwNUFzMExV
            WVBJcEZ1T0hzVURMZEJYTGxmSTJFYmMKLS0tIGVOR0dOMkhnSFZweDhCeXR4SzNs
            VE5ydEkzMngySHh5bFB1bHdSNGNjeEEKveABQY7rXH0eMLPBKcpIvt/sv4qJZp5q
            RJJhFcjxtgcgZBldHMhXhiEO/vVCwItQlgLf4wZ+rt9nC2F3pwKfjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUDVnMWtnSy9QbC9xL05o
            YWV1QXhPNWpwdDQ1T3hvUC8vRWlrOWY0YWgwCmN4eUMvMzgwNVlhbWo4YWIwYTZo
            cGMvTU82L1VoQWNkTTQ5TWk0aURCT2sKLS0tIHB5SmFOV29yYXF5eHR5SmQ4ajRL
            eEtPRHZoNnZuNVhjam1lRDRjUjVQZnMKvU1cKIAoB3Xb6EaIJ0rq1GaSCim0ABVA
            NWTfv1133UYnIxP66fec5s2Cw6NhnFC79u3w1LnIgX/R+w95OV1b/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYzFKeGZMMzFybG9FMTAz
            dWE5VTV1TUNQRks0Y3FHNFo3RUl4NFl5V0FBCjFyNHc1OEFuMjUrbllaNStIaE1I
            WE9kZEtCYlRvRnkxYWV1UUJnZ0dUVFUKLS0tICtUMW40eTJFV3E4R1JCSXlEbnBS
            L0hNSnlyYW1pV2drenE0emcvcFQzbncKzEX19xsE7pUpVVeLphqzWXwWHPfy97Uv
            Ry2WnejSV3wY3kbRfErxHajS0ESfZXL8q/HOgOIKC/m6dRdESYlJPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:25:39Z"
    mac: ENC[AES256_GCM,data:xwW5xMyL7BN6ldD44Rx9b/r7SA++moHQvHSVYYksn1KUw1ksyDQd2UPFgJr4DFx7meLeye/HcZ3X3z83odyslizVwEDXCuDyIwZPQAq1MoPI2FsVQB+J8Ny8ETMKY0DT4ENidd8bj3zoAj6xOoQjHjr2pLtAzkdiwVvaf1gOb6Y=,iv:ZKlSMlTFS9uRNG/KIXXxoLtjPQq5VxKptsp4oLIpz2Y=,tag:uy+s9yZcLwXrZm6a5gxQHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
