apiVersion: v1
data:
    password: ENC[AES256_GCM,data:iiujjhlxzgXNbO++xQamaeyMn7flVU6f,iv:cUUduI1oAplVTnZppDTvLpuwSIkErj4qFI2xfWUcsK8=,tag:i2QKVley5CjkiCdPEfoa/Q==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArS3pVNWVvRlFkcGJ0R3RZ
            Sm55a1RBNGhFNXlZejdtVXB6K3pWV3BKSkd3CmNyaHRxNzZMeWJUV1ZUemNLVlVu
            WVNPMTM3STZESEZZSDYyZDdDRktzRjAKLS0tIFExRHhQZ1pFUjVVMld1NGlsbDZQ
            RjM0RmhhZHgzKy9pTmwxODhoeWJHeVUK2+gsztukqrP+ZpQ0D5nMFKJG442JpQqN
            bkPiHTy+N1nBfLmZW89vwNMzh9CCLfVVMzt9v4kocjJ5FfhzEffgfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd2pqQy9UdFBNc0lBTFgx
            MnQrTklTY0FYMzhIeUlJWTNaRVVQVk9oVGlFCnQyZThLb0JXUnAyTGFGNFZFL1h0
            V2NhUG9vSis3S1RZY1dGYXFyVHdqN3cKLS0tIHFacTF4Q0Y5c3JWeUYyRUtSMGdL
            M0pvRHJxQUNLMW9wZXMyYzlxY1dHTzQKrBrI4KuAFF8nmtfFy/Fedwizp0zYo7kG
            cv8etO5R0LbHqGlZr13b1xEZqHEa7tXIfO7fEFVKZxa3DIYYEnlCNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSWRtN3hEQ0VnZ0ZvazNB
            SlJFMzRLZndPVnB5aEtNbzZrTlNOdEFqMUhnCmV3dVBENEx3N04vS1VJN3hNclVy
            UFFUa2NYaE1pWGZhUmE5OG1oOWhnYXcKLS0tIGJWa3J5VUtaMXJYUEQ2Qlo3TmJV
            NmhYc0xOUmlrcW9XT3pTU1hkQWYxdE0KEFvVv+/F+xhjMpirPToAe7T3lMXbM2R3
            jT/5nrataSKWwHEqJnnW4hc2x02NxqfPuimSSq/oOmRWKg7imzW0gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T17:22:02Z"
    mac: ENC[AES256_GCM,data:ZfcdqxUXJiTYLu1nUcCcPZfms7nBnGXKnDj8G2bxKdrusDDaOh8tgVlIzm3/SVSD/ez4vNkQqlE+tWhCbaQCavb/pyXyYnqpRD52wN1T9o/5pcy1ebkkmxAsCQNeK6xl38T7YpX+/DtsWiKSnv/V2qn234AKxYOKyxmdDxiIZ8w=,iv:zxRh6od38jx+ppbADsDb4tMXvQT615U8YXYLq/fmTUo=,tag:rEE84o5bYQpJmmPZwU7gmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
