apiVersion: v1
data:
    password: ENC[AES256_GCM,data:puaXm1soTtvwEZzaWK4PXYgJ2AStm54k,iv:QMBCIvB2uovAJ6D9Mvpj/gLCA5YSB60fdjCb7hGD9a4=,tag:bcC/B4oBM36KHqa1IQ8COA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvc2lYVGJZV1FMMnpPbVps
            OFJvWmhaRitCRk9UandiVU5pSUxRRGxhVER3CjU0UHVUbjZCTzk0MnFIYTB3dDN1
            Sy8yanphZjc0RlhvVW1CekJIRC9POWcKLS0tIDZlN2lJL2pYTzhtcGRHaExtU2RC
            Y2NvZnpaQWdzVFlPZm9uMC9idGkrbEkKK2Nx+LhsUAU+o6ZLpIilhGArIUiJmKgE
            jAd9d9EU9Ib3tKe4UqQgE5Q876sn6veQdw3K7vl7uOx61LoIg0hZOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TlpKaENJUFR5Wjc3SUd5
            U3RGZGZLZ05UWmlnY0ZlR2VFbElwU2pVNUFjClI3eXZVK0FKc1M1VkYzTVQ4Wm1w
            UmV1OXFzczFlK0NJYzNTWm8zSkpUdjgKLS0tIGl3Z2hrV1QzM2NEaFVVdkZ1Wm1v
            NVE1M1I1cFN4U1p0Um5zRXplUlFLTmsKVdRUSXIbOr7IlhPJUmdexKlQyLHWHzrx
            XCgCjLElIpCEHTs9ZXuvh2RBWtXd4gTE8kJ3cbKuJjqTlrOxUitElA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZXhpQUNiSUljYVpiSTRr
            cnQxOTYyNXV3TnlwN0RLR3hrUzJVLzg1Y1ZzCkV4OXk4allha0FnTUVzNFVmRUJS
            aHUwTzdSSUZJcTlweGtCeGpiUG9sdncKLS0tIEVTSE12NEsyOEsrT2JXR1oyRkhz
            UFVJNTFmZ3hqbk9xV3pnV1NQTWlPc28Kf4mRHaPMa/V5jasq7vGP1eAo2tUm3xjO
            NL8ZepAmt/H2y6QUx2DoyWEW5Z+yHzsFAw9GeTyVZBZbwVrqc6t7gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T15:35:35Z"
    mac: ENC[AES256_GCM,data:sBpz2esa0pMZJK3EZ+qStsbEzbXd/XeV8LT9Do6cOPsTf5PCwlgoYKj7GyzJCimfpWJ5DBHitjXcgDVqA3TEbLHG8aLO7aCcA4IKTuqNsNb+yfcAXhum7F0RRE1fG5u6UT2v0egoZuULZrBpK5k12zIJmaJJhH1FRPb27SS3D0A=,iv:IrgJXfos85YsvirCPDkWZ4OXAoLouS+Y0GLz8BpNf1w=,tag:akn0oOhPEVhGJugvL3ZPQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
