apiVersion: v1
data:
    password: ENC[AES256_GCM,data:samhqnyrn0tYR+ML65F5ZYOHu3INlyCH,iv:WtDOZ6eqgRH/SO5cMl7lIRnQx/TstX7PwJnlRERn8Lk=,tag:smrJqf8DYCnpXmdCGhbd7A==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmelVvWnlpY2dDN3l0blVz
            b1dMQk9pUnhEUTFZTWFrd2hBK0FRaUxoVW5JClhxaDRlMVRjSVVpRzJ0M0xCa2Y3
            SXNPSktoZWRCMTJlR1FVeWRndG9pR0UKLS0tIExjYmMrY1JUWENGL3BhVWNFUWFl
            UWFRRUhQdVo5RHMvL2laQ1lJWGc0cGsKwyk3dkaQXa0fAL9gvu9GlaOOPGuxH7zu
            r2nfTCDCetok0OUIfxjrfNDSGhbNIsxagT9+LmwrUHI5yS8geV4j+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVitWbkM3ZHNVREt4OVZ6
            MXVsQkRmekswVE02WXdiK2lZaVVrRXhGQ1ZnCm45MVJZUkpaaGgzNmlaeEtjcThs
            d3pEaTVHVzZQbDMrNEFXbERMZXI1MDAKLS0tIGdIMS8vRTY0di9wVTZXTVZweXBr
            UDRlcmF6UkU4RVB5cWJtUjJiNG8yTGMK0YQVOTq5+bGoP7sUvB0dmrw8LeaYE5nY
            WnKz2G0J6p/vo1/Rscd6cp+b/tdbrZkruU//ua7zjAXM+5ZkC4uNMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UGFEUzZxSzBwVldBd0kz
            VmhGNnA4Z050L3FCeDMxSXBtbDlkZEg5YXhvCkJsSG41WTRRRGxxZlBuWUo0eGVR
            SVpQVVRNY2IrbFlYOGcxOUlLbjZyN0kKLS0tIFlkUjdkRFJvYitoNlpLMDN6OVdZ
            aFhTWmx0TkJZTmlraFRMZUg0dS9oem8KJNZFLArUuitmPDicf/XLQWsH5mf1g/TS
            Hn8t/v5U8avoWASVkbgY2fnctjz6U4uQ9reNSeHe0QkNXMjOKrY5zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T14:03:00Z"
    mac: ENC[AES256_GCM,data:lvqiWOJQX68ygMvIPUlMcCK5SdxD7fBhwIFfs1EoNQ0yOdhe065B2Yf4hCrqjHW/wnuM8enF7EvT68zoX0nHG0Zlv6FEj08QyZmMU+L0/wyhc90DG6Rm+uZizGZODl8ULTEgSPkMnnYaATM6f+Kf9q41SEfrvKcYo9SwxNY2nwE=,iv:pmRad9qR8YogGzmMrhW74revF9RhPanm8B5oyl66ahY=,tag:dQ6l9JvgrVtki1g123dwsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
