apiVersion: v1
data:
    password: ENC[AES256_GCM,data:YREBWaySWtJdkthivhD9HybGPzW7ivl0,iv:GNSesrEX2kOR6EguGWq9Xx4QMpskpx6hkHQ8Jt4BQpM=,tag:ztQZiinaAPstmsAHJQCmCw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L0JPMnFwbW1vSldxTE5y
            NW5Yd2RKS0JGdUU1OUhkUS85a3h5OTIxVFY4Ckw1V281aUEyNSsrTXlvbHJuaXkx
            aXhaVHJwUWtmLzFONzRnK094TEdYK0EKLS0tIExlM205RERzNWRaRmZneUNSclM5
            OVgxVDhTMG95NHVxRjloNzNkSEx5Sm8KPKkco7ALrjLbA9tF5xSyt3hgJkWzRyqi
            EtTOG+UmMWS8NlocrSh0YMZNtcXPVoHz55LHbWUeO+UYratzNnHC3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMkkrbExoZ0szN1I0RTVF
            dG9Lc0xHUU9WeHpGOFJCNGtiWTd1bEF1b0JZCnlocFdGMSs0eGdqbXBEUUZvUXkr
            L29JZ0ZaV1l5Y2VsQkZtUkpXdGNMSWcKLS0tIEVCakQ5TFZPelAvQ2c0N1pCTmk3
            RWdHUDc1Z0IxdisvWEgrQVdZNmk1cmMKe90HHY0kaPvStYfD2dumFbrtITkbIu2L
            kvIRHBzZyz3qYuZdl1x5ytZ2hgcmjDPGuNkOM4aJx1M4oBuYuT0xkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NFFtR2dOVDgzV25JY0Y0
            a0dES2dBN0tUN3lzWVlWVCtlb0RNaW1DVVhjCkFSTkZvUG1ES2IxZm84UmZWQndt
            Y0h1aGJIdVJtRUJvN0c0cWtjaXpnWncKLS0tIG1wN1dEZzROM0RFaVlKNDMxZW8y
            cEt4Umk0VDlacy92VHd2U2NFRDdIdHcKDTYwLZkkTh9wyuB5v2cWX01q+kkT5LfH
            xnccK2Bs5b/SiIwUX2llPb7SO4zX2Bzw5wlZPh+2yBmCgFYx41V3gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T03:10:13Z"
    mac: ENC[AES256_GCM,data:i4LvpcVb0rMdAo2SkW2zsNdjm5aDMyIZk8H5J4p+4RjzN8Hkp+vaL9YSqmcrRikY1EXukqz7fVUgfODDU9FLWlwlcJ+6DaQbiAKj74l+QQpQBLdsAyV40cwsSpgXH7l7NbylEC7Fe0/WVuNJ+TJmqhGwrNkiWH/H4xRTmjSVX1M=,iv:xIsQtoFPfn2nCwNOBRTJbiCFThrfqLVGUfRADUOWWMo=,tag:pY/DVRU6lwKJMU6XuQJzPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
