apiVersion: v1
data:
    password: ENC[AES256_GCM,data:bFWiGNCekFOOwktBq7ryxXsez1klCnvv,iv:IgHFP1JLFZ1WW22avP0QSZmn2DuI4/uql/8zB31aZk8=,tag:AlXQ6T5iAl9fpJuLI8zTcQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ2FQSjZvZU1Yc0VQN2Ix
            UENEb0pMRmZnTDJvSzhzWUVzN1FJNWJyTUhVCldmYjMxTUZ4L0RCS3JqUGt6anNT
            YkpUZTJnNGZxMlVCdFRsSVVOTzM1bVEKLS0tIDlxN3g1bHUwa2p5dGtxS2NHVjZr
            UTB1WVRTMGFXMFB2L3NmcFpZSzNFQTAKOKNU8bSdX/QkG0wQMnN4wPFkiEwIpgpz
            W/PpBJk+dJK7SJUIQHc3FVh7FcLeORssWGxcW++Nm7E+qawy35rOyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaVRQRHFTM3F3YXN5UHRR
            OEd6bDZVZHNReTZVZFE2YlllTGNXYXZUd1Q4CjJNay9ocmdwMSs4dEdsdnJpaUZT
            NUoxR243dndCaTZrYUdweTdmSW9ueDgKLS0tIFUxczdHb2NOeXpVRk1DK1B2Yjl4
            djVuNlhkdE5XSXNoZHZLZml4QmllTXMK2vw+th8Aqj1yRuLCDGa+UQ0kAjOuq8C5
            oZq1E7BifcP6Qh8v81WyKkQThH7hLASzrTU5uH2Eb63TLWkP9IUxZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTk5nQlk4N2Q3QzRDZTRi
            NkZkS1p2T3NUTTU4RVpGRjZleGJHZkV6ekJNCmYzcmtIdExvdjlUendncDhKTG01
            ak5YUEp0eWZSZU16RmlVVm9lTHdXSE0KLS0tIDRIT253V0JLVGhmbmhIY0JkWkVY
            QVFBeWkycHJXUytNeXB6MzVhaVo0d0kKbHpDcbnjIVm8zoxbZ0LwFJsIl89k9aZ/
            4ciPq0tubivyi8ctZ+5ta2Gi+zU0X1ietyeSlRyDSkxZs+pzgpuW6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T17:57:19Z"
    mac: ENC[AES256_GCM,data:BVG2fdW4OuMl86SElf1znYBxyQTw91CBeI5GIIp3yN37OOZhp/cxr5cE3uNd3u3NBZB9BzHXLjT8QdqhiRm5ZH7nivJwDu3XCJBEP2MIjcgJ4BH6NdGN7hCexB+0UqV7alenZ0lYoyqjCpdgcvuqcjLGdxhP6N19uzvw82FEmaY=,iv:0v7eyInFwcZ1LTZxj9IKwhOnCIiZx4dp2mbjrtYl9nQ=,tag:PBloW2TxZvE9phEMaMBbxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
