apiVersion: v1
data:
    password: ENC[AES256_GCM,data:BR03aokIAAxeJUmA57LeRKlUEX2c/E5O,iv:9FGN3udWc01k1/jn9g1yIWs4LMLNmUwia2uNr2LlXh8=,tag:pDNPIkjDlKuz+uucmRj0rA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z1hWZ1gvUjdnUitSL3NL
            THlqblhYQTBmY01Ka3FkUVBYS256c0JQWlhzCm9RMlFmZjI1MFJWY0dlN051TE1R
            Snk4Mk9uT01YV1RiVzZkOG9VNC9kdWsKLS0tIForY1lMd04wTkJNNi81eDZidU5N
            aVdYY3RaSFBKSFF3WVRmbTJ3NDY0RzAKqYz1iVadypPtiIjKyZtJ6afeG+209dwr
            cQAYBm469dox0x6z6FP6Qp87Z8Z1WaCPW3ky8+SUKU+vSmR7EBUZvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eHUxKy9kd2hHWTdoZEFG
            N0QrcWlkL3RONEFrdVlaREp6UGRrWERsdXdNCkNSNFFQNlZWYWNicytnU2xMbkZy
            WEhic3U2dUYzYTFRMHdDeTA2NEZrd1kKLS0tIDZHbU5kSHdkQXczMldVblJoN255
            c2plOW5OcjZHNHFENnFiZlA0cHBOZEUK4NBNZFII4R6XPzRbwbE0u+zuSxcUFBMl
            829VxOY5UacprNUml21F6RmtBggG6VCWE/qUI/dSR8Sl3NYCIDoBzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN3BDZ0xWdTV2aGxPOFVC
            TWxOUXpBN3cyZEg5aXBJQXJsS2VENnpiV244CjkrNDZnZzM4bWV3dDE3bGxLNWx3
            STEwdGpPeC83ZkdSelVQTzhQQXFXZ1kKLS0tIEh3VEtxbDl3LzdYbWZBV3JhN3FX
            REM4MzN1RlFEck5BT3JmcFloYTBpcHMKQdb35nikpFJlA19flrYtnGz6L5VPq5ud
            umtrqOGReiKd+ttXba4QzJ/0NiNiZ+7jNdNNG2lNNsQWEa6Nb5mUHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T15:56:24Z"
    mac: ENC[AES256_GCM,data:wtiTjrYW7uNAtjvYJSN5UStYa2tBDmAw12C1K0tD3XDJMLf+3VTwSPDjhySTc6msZyHGBFO86tI8XSpgmWUF3SSVFUEdL3KVjzR5sDZBfyB+r4nZSJwkuKzSLOAeAivnx9qEr4v9HWNR7QmQkVi9/psewsqR0eW+vjgeV0RXG0g=,iv:8fHx+p/wuO5G2i6iV/bvriRAXDKJmww1qm7l/P/RS1k=,tag:DQMa/MDajHzCS0oVoGVuDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
