apiVersion: v1
data:
    password: ENC[AES256_GCM,data:W8zRi821d97pB4oN/4VJGyDGnN1qBoAh,iv:ACx9EYieZB7twc/qd9bhereAb7+3sXAGfXFznixL6kQ=,tag:P15fv3D71L8sy8TOEf3/cg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSkhHeTVLWjhmVlNDdkh5
            VmNqd2ZySjBnbFV0SldsS1BZNUtSdU9DNmtJCnBMbUd1eTZlVkJUNVpmOEJ4VzN4
            QUhjV1M1WlpsV1pOU0NtMVpmL3dXbEUKLS0tIE9nNGZOckpJM3luZzJybHJTSytQ
            bzdkaFpVUWdrc1JxL1phaWVkdnJ0alEKIxozdaBUps6fBN5WB3CKWNYkXlB5xsJc
            ING+ltfY74qAaQ6gLQprDccYFOmj7vsVYtwDRekYOD5XQfuF5g1TXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZXR6dC9IL2xFUWRYdFJW
            OG1lbDdxMzcraFdMNVpvMnpRWXpFdC9tUjI0ClVIam80YWZMR3NyRVYvTXhNanIw
            OVlocy9heTMwRFdwd05pa2pjeUc1cU0KLS0tIGNCbi9jWEhjWE8rdjBDNjUwN24w
            YVNheEwzdVVnVlpTMjdBRHlpWXJhdWsKkYrDZz9S2jVe8RsC0j/pTi6P0a4oYHV6
            IlW1H4NsF9y2/xYcuU+v8iPJ+zZS1NTAvVJkchcm9OyxONH8qIGtPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMEk0U2JFc0YzRDRuRmFi
            a2F1VFZ0SXNsb2dKODRnTFBqTXZMeTN2VERFCk5SSitqNVIvaDVia0hyazhTcnV3
            Y1lldWxpK0YrTkdNdWJxZlp2amlMZzgKLS0tIForZXk2SDVlQUVyTGowdTI0VldR
            WHN3V3NiVG9FVGQwVVBPOTY3NURvd3MKT41KJ05lbAnybIi7O3gW+BV4A0YsndGn
            jd2hOn20MtMHVgTmpVg3oVw+ttpvPQhPhsuSnpySZ/ISTfxrdnQhFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T17:50:35Z"
    mac: ENC[AES256_GCM,data:SivH322Dfg4U0TJW+gcVe5Sn5zQcrAtCzJ4BicD4umjwNrosNJz0geCP1KcbWyl6clJUKH0Wi8voJRA456RhOR/wT1sioH5BA+ppepyQkLX1ky3/ew7d3gJbJuTYjNOA5vPVh1VMtn6VH3100mjVmGn7v3I8/g8amrhhJlcgBa8=,iv:ox+XWp1S8XH1bdIF/6yd/dcO7glNwFlyGAhtt2wmATg=,tag:b+X+AwWo/H8jbSJAov2EBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
