apiVersion: v1
data:
    password: ENC[AES256_GCM,data:H7mjB4IjEY2UKEXABmDNdBdR5nMbWtw/,iv:ETq6vh5sC2uhJP3Jdh/DiwcdP4jeoQAlnMyFa6a0c1s=,tag:ObLUHB2eo/wvj/2dd0P31w==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OHZyUG91NXYxb2RtbnpH
            UlRhTXUzamNuRWttb2k5OXNsVFZXbzQzNGtnCnZEY0lGbVIyQ3NqN0w3TmFhWis1
            T2UyMlpDMnZCSEc4V1VtNGZGNVBOOGMKLS0tIHJ6T25xUzBKKzFoMnpTLytEVWVM
            QzlaMUdzNzZzWEVKZEVnK2czMEdNZ0UKuF/tXb9t1NNntAtfpAagFP9mcuTAn5hK
            24+bWEkYLUSk91XhNAoVMrsHJyOqRgoQKwKJgbtzr2E0wJ0CZeAwbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ3BNYU1oRHBwVThMVVFo
            Nk1DcENBT1hSZ0VEK3kzWHd2RDlVVDYydkFVCmd1ODdIdW5rYXVnYUR0czVEZjlt
            SFpjOXpjZ0ZadVlsTHpSQ3o0bG8rNWcKLS0tIFZ5bFRMaFlzdG5NWUZpa3YwQytG
            SGtkZlJNblEvKzBqOWZ3MWpKNUpZS28Kb5aI7WXaKqLSYDESiKAFS5lnxwvgsvJ7
            z82HGXSHNrK5gQ63myeymXf3DxWYmMlrP7IY5V5nFvkx5ypSJfNZxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVzBFRXNxV3BYZ0szRTd6
            TCt2ZXplckJOSTk5dVJMTEgxbnpVcGhvNENRCk5GQUsrOFV4czVjWk52Sy9kV2RM
            bHRTSnU0eitNVWh6Ynlmb0M2ZFF1VDAKLS0tIFl6NHFpRDU4QlVIekMzdlFWWE5l
            dEd6ZFdVZWpuUERCc2JLSTRPV0dhRmcKCpufLAB6HfMAdmYDmMtKnXaz880E/4M4
            8xjhIs2CPhcGPr2JnVfF0OFtApvHINZfLFkConti3Hh2bLMBEIWsXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T13:29:25Z"
    mac: ENC[AES256_GCM,data:DBPYpxeCkhjLlnXEmkkOpMnMUMBrwxgmPR7kpuPhYh3vHYmG7dcZT1MIwHbKbBJ37wnAUN1n+bMOGAORaZns5wRxKrUUqV8oESDDwwe+Ybj7nRm0WlAwz2rXz0o8kVRBq43Z+TpCnmWn7NSVnFbQUCs7/0aE1qhKAZDgx79ehT8=,iv:PLNqL+Qi4mxxKWqaZxtACf2ykx9tRscuHMD6c1L0j+M=,tag:VXfTotXVz/kLOM6nQnBm3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
