apiVersion: v1
data:
    password: ENC[AES256_GCM,data:sYtlscaubl0BhfGscZzY5O5ui2B1bDam,iv:NsnpGcJqk95JFTVrc3f69ZJxfD6aMclhHDeBy8s1Kc0=,tag:wv4ZlY39pmFmELsV4Qk55Q==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZlVZdmpGTXR4bEphaDV5
            U0REanlQaDQzTEdaS2ZEZ2NWbzV1UnErNjJVCmhxTlNnaWR1YW94STNwNzBaMnpI
            TGZkT0VGMHFyUk9nVUZ6SDVsV3JXOWMKLS0tIDBhMHl6WUdoQjJmZmhLUGpydzVL
            aExEazZHbGtlT0ZQM3I0TUpGaU54NmMKFsEjStdDAh/qJxWTXlXo0MfRGRvFq3Zw
            qvxIikc5JGIEvoTjRNZubg8SokFJxxDvJ691mvyAZTcyBhEG4jJEVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGLy9mTXpaZnZtN2ZxREVC
            RVFMcFVsQnVKeGdYR2pGbWk4WmJvRVV5dG5jClk3MG80T202MUM3S0xuclZFQmI4
            RXEyek9ENnYySWxwWk5WcW05ZmR5T0UKLS0tIHZ2d0VwR1F0MzdGWC9IUmZJSVBN
            K3RyVDhOM0F6T0duSnBCNW1FQTdUZUkKH2f0d05+3/i/6Qc4USiPK6yq++T6yiTn
            m+Fx7sbptowL2JyeOz2Q7CFnaXjteAavt0tOayfCAhdhtD1G52rPHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQVZzeEMyS3pib2dqbGtk
            YnN4QkFHWkptbDJBejB2YWtUUUdURFlCOEQ0ClRmVHR6R1R0WVAwWXhIaERwbHpI
            bFZ2V3lxN29XWlNUR1lSci85WXlXblUKLS0tIFNnRmt0TVh0S202ZUg0elBOS0dI
            M2d5bDlMRWQ3ZGVYQmRqeU12OWlCQjgKnDtKYh6Bb8DlysUzPEUbqKx0nf5hfhFU
            aRyipCxDQBIFORwgysxjjAIEchQwmkmHj42h7X6ab/WJNU93dW/XDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:56:10Z"
    mac: ENC[AES256_GCM,data:LyDRLm1n/kqZFMhL/Yj3nO6gDyh7sR+6cajOBFWSICphBWIXtLzAeFilb84NA98OkR2rJCL80EA0ROwD1nYOO4Emg7lx0TP9uwqNlsM9UiBOhkEQhN7jMgoCppOUIZntbmQLCDO7e0jVE32w8XVH+xWFpQ1C4043rw58OJEPiQ4=,iv:JX21IsATIorn2VJn2JlOrbSHcIoT+hRv1I9/4/9Z4pw=,tag:CP6kpYhKzebCSb6Ml1vTAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
