apiVersion: v1
data:
    password: ENC[AES256_GCM,data:/WztwYfHeYvoVcRcBlKaIzDWjQn8pNsm,iv:mb8wnYGCzHHBFF0eVjqWym2WqhqBjkRuoSR2SoTbHrY=,tag:7kbtIr+QZ/EbtlsETSVeTQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OE5rV1gxMVlya3F1bllo
            d1JoMHYyUUZWUXFCbmlVbmtnbHo0MXVLR1FrCndJUTFjTEhxRWM2TFhvSTVHbTNN
            WjVwdWxERHpaU2ZTdjBKaEhtdFlxb3cKLS0tIEQ1SVAyOEdmckNkRCtILzlVSUlm
            OVhMRUpXVDM4MUllMG9CVlpDUXFwT2MKdmq/Srv/GXwGn2R0e4uVhVoycfVap66I
            v8/emdYk+0hRueeC32ZRbhLaV/FBg+5hCL5B6Pjx+yigUTKXTzxPvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cDVsU01YYnozMXB4YXZY
            RXY4b3JCbDU5UnlUN1MrQUZ0WHg0QkcvQkFBCkFhSGM1bDdzTWpYY0tCYlUrQ0Z6
            RDhNdW80cWcrNWpZWkUxU2pmWjBWUUkKLS0tIHZkU2lYNzRxMkpta0MzVGRLRlAr
            dWhSV04zbllLbVBvSDErdTlKdXY5b0UK7awa+kSuj4+bA9bjBBUt7v29F0rlDUn2
            SffF97MO6DWDzmmWRNRUAfnQiUz9A82ehdizowCgrI6J9f8wgVjGsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cmFoZnIvWHh0MFRXSUQ5
            V0sxb1M3blpLbnZRa0NZUkJmK2dYc1VKSGxJCmJQenhnZ0RqRmxKc3VNUnZ0N09Q
            WDBWYVdwa2IrZGczT1VhaHlTQ0FqbWMKLS0tIGNTd1M2MTlXMTJxK0NybE9GenN5
            RkkrbWxCWElaNUVIQmtpK0UxOFgrQncKya9MEzlovux8woNZs215R2xBdRFWQjlD
            7a2ot5Hxlc6GNzpthTvAm1cpt/B8YFimKv37rTAVg5nzzCdWdR+67Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T17:38:04Z"
    mac: ENC[AES256_GCM,data:H3/k87eFWmdqL6Y0eXMLWNkfge2QR8oqNclw+M0NnsFK3a8DOcZdIMInapcRC28J8Hx+F5QL+tYxXlNP0gyl11jnb3pTAFOI2Oua/XEzjPLIh7soiLZQ4i4XI1UdYKC4ZIIT08kkIGabLY41AFRHL5EE1P5OHf75epSQA+9Psuo=,iv:Y0NFDcRNwjNrLQUbain+AHf6gCDQSEekJ8LYvEAwylM=,tag:1feyaQwxEDDyuQxRyq4y1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
