apiVersion: v1
data:
    password: ENC[AES256_GCM,data:exIBVvjzFZSALw28tJLGMGMXGtk6g4f3,iv:sOcmbSuW/Rk4lz6c+/sg7oGKA0VUoW1HT99+tT+mYDU=,tag:WcPN/PMZTuCEbZc02+q+Pg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRGpOeHptWWJTS1ZmNUhR
            RTRHYWx4c3JvODZCUkd3OUtOeEpOOXd3ZW5FCkpJWlZRV3BOVkFPNnRyTFhZWmta
            YWdqMVJBNzFNdkgvaklLTWVEKytKYjAKLS0tIFdVVUhtVGRCVjAySkJSZ3U1eElY
            enoyd1plVDdNQkFTMXRXWlE4MUkvRTAKchKaELO5+FUYVFsJQ1NC+O1PDxs5dYsD
            rGpcuYdHAsn0FsaBY9DJ1YB1Hkmx+90EhUZi17QE8CwNNPE6ke3GDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb2t4Q253MGN1WVJocW5k
            ZEs4YnN5Y3pZL2ozME5zaERoWVJESDhqUFRNClRueXh0N2d5RTMwNzZHQlpKa2tl
            REYxZVBwWEppb0pPQ0k4cHJpUWtPWVkKLS0tIG92S0JHTkpjUkd6Q05LeElKWGU5
            c3l2K29VTUx3bzhGeklKTGhYSXpKem8K9v6j/xUeL0Zkar622XP0LJTEeiwKusBS
            EoKvDGq4HhZmn+mANgthsVNeX/8utkg6OmvKMK+k5obsmmailJHLig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMXN3dE9HcmhzT2xCaS84
            d1M1ZFVZOWpEMEtsOGRVMld0VFV2a0ZFOVFRCnBuN0xNVzIyTW1UYWE3T2liZWxF
            dE9ySGFLL2lKOUljaTVmMDNIRW9oMmMKLS0tIFVITXBGZ01IK04xNklmUGRwdG1t
            blV2a0U3OUYxY1RZMU9mUmdaS29CL28Kk5CXmYaTa10SFfV6EdCNZslydc2eRvmc
            S2Ws7zCjbQ+GHwOL0S9h6/40z1Ni4bjL+bsQA0PQ/cyz0FRHLOjJ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T03:27:44Z"
    mac: ENC[AES256_GCM,data:xgFVwQIk5Q4cOtN9T5luLdgXwQ9SZL4VXpI1QaEwwWYSR+KQ/dX9c2Lzw95/km2p+8v4+sTaI9N6YxUnh+0UOvuzQPjrN+mKBSIs/8rDIz03JmLfQprFLbGVzU4pCWogCLBBAnMy8ajvign3qPpHsqtEM6c4B2NcIxDpgRUFGWQ=,iv:vY2PStrJtD3qcsxYZvZZ6UrG847bmUSd69WdozATWYs=,tag:i3ZKkjKYPXKkFO17UNN8OA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
