apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ovTT02SuTEoGbp1OocKfMbXwYUq/mBI4,iv:Hsega0gDfbscdZhfdFEuQganpvjWkw9KGAVvq6n4ECs=,tag:WTr6owJLuIAx5Tn7oeNt1Q==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT2RUa1BqSTRsT2xYMXR0
            Tm80dmVQVTJMNmhycGNVcVcvRmQxN0NYMGpZCmwxcTZJd3E0eXN5eGdYcHZiT2dF
            ajZyUVMxelpyYXRUcWd1RUZGU3ZaSWsKLS0tIE1QbUVlcmFSQmNJc0ZES1Y3K1Ex
            anBaY3lwWHgrQ2FFUnJ6NkdhaVlaOU0KaffDQXKbsGvgzrbYJRt5pgHXW+ELLPFp
            JH1+9teNxiu+TSaf04N7aJdXhUWJhUZp+YTB5DB6jqr+Rdz9UesF5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbXgzTlkrS1VLOCtoZjB0
            MkpzQ0Jpa2ZVMHlkK0E2M2xKZWtPOFFBQncwCis4SlJlTWFOQndyaUtxSFkzSzVT
            QjdTenBoRjM2RDlCWmZ3Z1IzWWkyLzgKLS0tIHZmdnFUR0NVOEpJOUZUQXE1TitB
            SkFwS2ZDL2NETmdwSHV4V1MzbGRocWMKKSn4eHlgT44co7DpSqO4/sHjd5au8RAw
            kUakMXZ+5E491hAx0KxkAx+r1/SFYu9aXLIAO1kgWksXFqLMo/X8ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSkpjaUFyTldNM2xaZXJo
            WTJUdysvV2ppdUN6bXNQZnowajl2NndyQjAwCjRjRG5HRjR3Y01BdGVLeERXWkRP
            Zjlqci85cUV2VzJvZGZ3aVBnYlcyQWcKLS0tIGNGOEJEUVU1MzFiTko5TmdrenJ4
            aFplZndjVkdBNkRZVDBQbDBoaWlEdmcKvyBGrltynCL9RFgEYldCcT09nKdMw73T
            3RvzbinOzd9Jt5F0iWtkKmH8xMpOxnanHCoQyQeWSDv77fvDt69w6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T15:51:06Z"
    mac: ENC[AES256_GCM,data:+y8oara3zSfasLnLXIbIBX+ga266Faf6/yU41BdNzvEvwSSKpPUH/dJn9jeKAV8NjVeEVl+nUvXYI/NEhRcdXLD/uMy9vLj/DtAO+T12iaRW26ndE/6dM+jf/6uJLtTuziBn61A+imyBGjkQaIQdAoBsrYFDyEGRiFaRhugGmEg=,iv:TlHOwpLpIa3sTF1bOt5HFaob4OBn5O50TKrUuu65y2I=,tag:Zvg0NJ455oJ8bBENdLcXSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
