apiVersion: v1
data:
    password: ENC[AES256_GCM,data:9mFdWUcahtBl7SsgXo0L0zrghk/8GmaV,iv:eIZ5UWiMmWkwSEMDMoAKkAG5oTlIr8H9hItkjYbbKyw=,tag:odUyO5vjgmogXJwWnS//1A==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ekFuY2hxSEx4bHEwMElp
            Y1pUcHZNcElab3ZLU1BqaWJVcnFLWTZwR1NJCndUV29HWnY3YXhTRWVHK2pkN3lq
            eTRJSmJKZTgvZVRQeDhwZWJNaUVLbmsKLS0tIFJETDBSSkZQNCs5a1MzRFVwZXBU
            K3Jaek8zbEE2WEk1MlFqMnBKNjdkaEEK61jiyrCY5h1rwCYCvfg33WmoM9Zrp5Tb
            p+j8SfRoDsMh6qTUAYFl6dC1zMwT465BA4uXJ51DiyZXGnRgCeQFow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eDRYS1BqWmlZQzdqeFRa
            b0k5MUJwaUVQeEJERjRFK09WbU5HeFVKSVhrCk1ZRER2VE8vMjRmZ2dRZ0w3bWZu
            c25EbnRWeDlGTWVISzkxRWpKWWR0M00KLS0tIHJXaWlTUDZEVFNEOHpoMnJBTnpP
            Nndlall6UGFkNnFBbE51b1p2YjVkL2sKuOGUXF/y6lNHYBjSTBLUlBZNwLOsCqx1
            ZQjNbOl47Eb4UwJfOvQXL3EWCfSBrhFvrHO4JBHQSRmNVjvMyfsm2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGM1RBY3huYmNkYlpGcFBR
            UHN0TGQxYXRpRVVtcUZ1SWxxZFIxb3dteGdJCmcxTWtDMStmKzVBMnkxWlBKbVdH
            TG1FMmNtL2U2NE9Xa04rOUwwblBvS2sKLS0tIEp2TFVTNHdyWjdkTnk0Y28rTWNP
            MDdtSUxhZVpRRzQrZ0JZU0tMU2dqbWcKULTEZKPZMGjXCyt8V1cg3SxpDVE7ToAZ
            JckgHe2EHlS41evUkySVt9mguEOp1Ko0hZUUSbdqISmSiFJ93AJWhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T14:31:11Z"
    mac: ENC[AES256_GCM,data:ZdZ/B01iypAFWPKJaHjTQqHwg33v2inw2YVCDRB3LWYim83ewaAoY8TlECqr9IVxRyySscoxbNGuPr0qz86crdO/ONlza74VvdwfjlvUoQI1KSyupffCRjdBuSGUtyuLZjscGxerfrgw3MrNX4kaXoBsn1FLv0gOMWbzAyetSkw=,iv:kfU9jqoBs79gTsg2cYoGcDJSn9jQX0kc2ENztIPAR78=,tag:3FyXUkWxLSzWJAkJqa53NA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
