apiVersion: v1
data:
    password: ENC[AES256_GCM,data:6YsxmXl3KovtePJjsWt2t1nUkYHnD9ff,iv:3jJQCAuPvZOYUrv/0APCke0t7yY+rTlmcTIaNDKBYJE=,tag:ZaH4lMaKTDzv9CXYB46ajw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbmJ2eHI2cHVRekluVWVI
            UlNSc0ROSnJ6bjNJREhycEdYUitqdE83K1JvClUvSlZFUWVWYWVyZHJNay9JN3Ji
            eDZWYy95Zit0eXVjSEdQYmdjWFdoVjAKLS0tIHpiTjcrYWJoN0hXclRLR3doL3JK
            NWFRYTdDd0lEeDNneFlERUlTdTZSQ3cKrbFowLV5gf5tMnSNXGuhEuXOZ3qnCykx
            7aVhKGthU+nNE4B+i7ht9fbVv6CFIMOAKq55efmnGU28aFjDexKWMQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WUl0c2FzZ3VqL2s3RlVv
            alF2bHBPK3Y0U1pGZzkyZEt0RndWQXVyMkJFCnR2NjdyenhBRlBqd2kzZFdwd0NS
            VzJKOFNSVHQrSnpwbFFxcFE5WWhiVkUKLS0tIDVwemZrcG1rbDBZbk1mbS85SVpi
            NDNEYTdnNVhnRjRLNmFGRFpjcFR6aTAKAENQjueGN3FK0H4JLh9mTCn2FDtId6Od
            jbCWYD2iBPBgs2E8AER87D/7ry2d0HR+EuEdt3juYcF+jkoHvnrTVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWEtzd3NLeWlxWGN5QzNl
            UjFWZEtsMzlYSEFNbC9qRVlDcWVQcENhU21rClVaTEd6NGhMbHVneDNsV09ZSWgr
            dUNUWEZBV2luNE0wdmh3OCtFbzlQZ1kKLS0tIFd3SHYrV2tQeVB4UDR4ZXdkTk5r
            bDFsZi9ra2cwN3c3MUJQTytmRTFDZVkKwGAlDmq4oLTZ/eE2NRRCKPZvN5i8PfR0
            uJ7uXCjgeja4x+zwZ+JYXz6kfC5AMuKZwfJ9+9PfAknOCPjthJv/Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T16:11:13Z"
    mac: ENC[AES256_GCM,data:GMi2oi+4DSkqF+i7PnBDduyS5+cCtl4QzLl8Gyea5sxVN8EFQ+wbYE73ENikB/bkomh5CpZ2jk8EW63NanrzX7GCI6khuhFpZsdsGYmaKthrniG7+UJ1PBM9SoX2BTXfNx/UkC0Hjpd5oqC/wsJt92woEZ/CfcSeXEQ/gOlTgYQ=,iv:SWot9a22FqyoH42t+9BQMlck/0O9FaTEAavWwqDjn6o=,tag:Q6PB+WzoFD4kgdhumOEWRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
