apiVersion: v1
data:
    password: ENC[AES256_GCM,data:GTKT2wGKEJ46z6/a7OosuTiDq95w9uWB,iv:o7VcLenqDt26SICVzZlXECDBE5+uWkp1BrZjV7S/hV8=,tag:lv3+rz+qX+VBM63CHUameA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWamYwNDVhOWVIVmgzTUU3
            TjlpZVIxampGWGZnZG0yVEljZGxqWVZlWlZvCm9kZTFlMUFFODBOaUN4NTltbmNU
            eW45UjNheElOMUdXZDlYeDdTNlg0NmMKLS0tIDlpTmQ4VGdZREVCSU81VDRwcUxm
            UjBDZjVEaU1vNEQxeXFvMVM3RDY4cmcKckaYOKNAZiTpckMjSDlNDG2Svt9tfART
            fer81m4B0EDflpyUmtVr6fQ935I1cSDiO6X76g0zay70RgAM/BO5Dg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdFJ3MTd1cnNyUGVFR3FF
            UzZ1aXJ2dUthazRFNEpyY3c5UVFLdTRzd1NvCkYvUGFXUTdYZHV0YmdZN2FzR2JE
            NFNUbEUzclMxTUl0TUJCSkZtbk8wZGsKLS0tIHcwWjhLT25WRVk3ZG5tMjhpY0c0
            amN6Ukh6KzVTUGQ4NU81cWg0clBROGMKuOPmnt0e4kjTcdtFG1QaxOysOgsja5Tf
            gfeR24+O7ZYDMoV5zKSdgiVXh74Twa226ZEQtpW/CBaCWaDnRYQxTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUWgzSGthS0FkR3YxMStm
            c2w0TkVjVnBoZnlmajh0UHV3K2Jkd2pGYUJVCjNESzl5bWVpWGkxOTgvMGVWellL
            MDJPNnlseExRUzladEdGN0IvcmZSeUEKLS0tIEFwVnF0amZRaHNDbTQ5bDhtMHRR
            RUJXSStVOWpBdzZnZDJkZE50NktBclkKZLof1dSv4lWjkfCOVwAjtFZBbK6SDH49
            yEEdiaBZFZwL0uY33dGISZTgERHr5sU3ZVlBB5snM82fUtzJEIuqjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-19T13:45:07Z"
    mac: ENC[AES256_GCM,data:7sypFyJnESOdxMRXbA8sCihVuSeL50vy4wrj+/1ikCmDYo9G1nu0t3wp4Xdvz4mIVAqIDtgPz+U09FlKswIO7SfMyFr6oGOevoCVCMcbPJ8uM0JUIdvZ4GLO7jUSsNmAZoBYsDJdG/pWLYzn9LlNNCbdWRScaWgC/9tFmkSgtF4=,iv:rXKzcPquQbzxa+xq+HREhTskNvyKula5ZTm9/hMXta8=,tag:xHy7brYsFxL6DsOvBepOpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
