apiVersion: v1
data:
    password: ENC[AES256_GCM,data:1rORkkNA2yoB3EkwzmuUQcnjWo4BC8RQ,iv:27e7aoZtXmUokmlhlY9PJXPDm0p205I83XfifI39sM4=,tag:9AtVNatAw032qbRXEbjhFA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SVl0ZmNiNnpnaGRJSUoy
            L0NqbWNYNVZlNnpTYVQ1VGZoNGlYOFhEZ204CnBFT2hWLzdjSlg1akdOWWxpRFB1
            QlhRdjB4RllRWWRIMzg2RVFnRmFqdHMKLS0tIGhrbHgxL1ZNenFLc2hDd3N2amhI
            L2g5K3IvV2pXeVFNQm5leXU3VDR4YmMKet4gJa5kbucdifJnASHAJAKI6rWBgA94
            soTqEaJIP+qQ9j7QcS8BJTiFPxEhcACrxDLxY7+1XfhYXFQlFFbAjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ODhEa2NFWExvVEs0QTRp
            SW9xaHArWWZTdExDdWNtc2lrNDNxYUlHUzBjCk50VlZ3bXlISHpSb0FGZG5zTUxZ
            S01ZbC9WSndkQkVpK0tpQ3ZYRE8vYW8KLS0tIEZ4YlZZeVJNWkFNUXJodE5Ya0xE
            WEx3NnN5Q2lpYVNidXlkQU5ISlBmK0UKfN33T7heE/Sx+XDzts2WA3YsRKV1mUC4
            rjsSPl3wikviQZS2h7FgHwExOhBKS6Cja4dOIHBYmkvH8rBNFMegng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuS1JTc0RQKzl2RFk5QWlo
            WWlDbml6RkZuTmVJWXdTV0hxeEVEQytBa2dZCjFNZEtDd2VJbThaNGFRM2loOWFa
            cHlKcGxvbVRwSHF4bE9NUjFSZVowUmsKLS0tIFVmQXMzMlNyOE1LQ1YzclkreUJF
            OXM1cnV4N215WDhYUkhxdXc1RzljTFkKWMxkOH1OHfed0bVZEHsrTlAniT6DNAgD
            koX2QSb5h2R0TOtfQ5vDjSLvsnwKc3k9Uwy/qfCu4i1JGVRqPfJbaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:46:16Z"
    mac: ENC[AES256_GCM,data:M0LUhxXgjeLKtxr75ATdvsJiAuSbXuRa9rIwYOb+FppLQY/giUNKOpjnqC1QAnRrCYPq97R6mB1aWUwIigj7VbgvGYcPMT3+MuA7cz25PjlGj4WQ3Mlb5jMh4gz5gqfMfYNhP8X8BsgbzdYojqVgOJtygC+mozO9WYliYpEanvQ=,iv:5hYwE4TrpIJ5JVmv/h63/GJ8/ZDdCrBaERUjpjb/IyM=,tag:gF8uPsR4uCU63/kMwxFLBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
