apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ia2cHAPv7KlIFc/b9pmaaxg9ko+sXsFL,iv:GBN/y4HDTySIO+KNsTeu/8JLk9sEtwktEjF/0T84LTA=,tag:F5zPZn4doo3pS5mh51koCg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMnF6N01ScUp3ZTg1ZVRS
            RTZheC90UTF5TldBL2FJNmZYQnkyWUxmejBFClY0eHVNVnZQMHJFYW5rUTY1Skhk
            L2VBREoxU0krUEN2d2ZzUXBkbWcyVGMKLS0tIGVuS2hZVUNxalBGaXUwQm9ZU2xB
            RFBpZTBkd3lBb0JyeHNmbzBNaXdvKzgKPZGBKgWkbteWm56WpgCb8qbumOCRhr8A
            /Id3eLVtTj/eAgD6MuQjTenIUiS21dXH2mW05cAyyGR5KaPYqJ3mrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOW1TeTU0dkpLWGZyYWEw
            TEdoNmZ3U0w0RkRaSmZKcTBMT0tMU1JjMUIwCnJMMUU4NmQ1RG00d2svMFRza0JR
            TUgxSlBlQy90YVhiWVBrME9OUUR1MnMKLS0tIEdLSmx1S0JxZnk5RElYNGYvVTIw
            bHM3VSsvWHJnejVZQlRlazVjeUNtVTAK0pQIli46uLN5iMls90Xysj8BnGIVP2Ey
            tl/lYPuC8oLmB3uwLDQ/dVHi3qKo0Yyh8WZxGueWWDrIEYohTj2pGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ214Rkg1MGxBOGUzT2l4
            dW1YZXh2dEQ5Qm9Kbk5Oc09UWGprU2ppZUhJCi8rMlFUWDNBWVRvMlJVbXUydllL
            RUptcmJEYkdqQVUybytLSUMzak5TalkKLS0tIHh5S0t4ZnBXNHFxUGwwd2hVR1Jt
            b1hVNVR2Q29jK3hLNWRJNmZXZWlOYUUKZoXWfVDA2zTtmi35MQ2SUwlzlqeQ0JO+
            YTXmuCNnYazhHbdjgmAhIbLfofrwVwT+Di2VrfuWeHYEudADUr0EqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:22:33Z"
    mac: ENC[AES256_GCM,data:ThipmpBTCz691+aOke4bRjReAqG/Yi8ijzscGnyhxtfvjGbRWhQIVOPy5F5m4qxNwAoyuOuZtrjxqq15/TJrpFuEUH62rXEeRRaLARGs+HsC0BwScnv98prjsYbhrqGEvhFPpD7FD4PFPjOBhahfYyZUcRm+fGVKT4nvQs8cLIc=,iv:mdnjSvm5ukXvZ6nobrYzqJffTJ1OkXftfAVL+nRuHro=,tag:gbxA385fuVdn75ovHPBOwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
