apiVersion: v1
data:
    password: ENC[AES256_GCM,data:3Lc9IqqHwt7jGTUkv3RiJhsQaAIWzN4x,iv:bPdDbBCbERLxrTs8nk9eqKsepEamVa3xqhSIB9zTi0E=,tag:mlZNivyDtuAv25iyEJCiVQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyL2RNcGNYOU9ybzlTQ3dP
            TStTNldhaE92cTZNSm9UUUxiSnNtWXhaaVRvCndWV2twVjA0cGtENm10MkxtTDBF
            UUVnNCtnbmhJbS9HdFR5M3JoRklyczAKLS0tIFpReVRoNXpXdkhZYitseitHYllL
            ZzcrbGEyV1Jndm5jOGptRGdoRkZjREEKb3BGtgid0fAQxNJyV6/T6FQL+J+v5d3c
            rnYazAnD/VDFRYxw/tMAL1VjQmmbT2Zw1wEwEEocMHFAuf9FPSLGFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RkJTcHZKVENMMkErWm00
            ajRaakZHL3N5T3cyYlVqNk1aUmh1Q1RlTEFNCklBRlVnN054VVhyVUNFSHh1cjg0
            cS9JY1pucDF4c29aN3F5ZmZNVnBFSEEKLS0tIFkrNFhKcjVZVGNzNGl2OHNiaHY4
            bnZ2MkxISUZzWmRVRkJIVDA1Y05OWXMKgbq+AMq1kDztQOLdKSrapLywBJpk1Bhu
            GJodO1od4gLeJbNfYcZaFyGUbgJ+DkUcOC42yeBUFZmqXTrVBEk4oQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QkUwT0lPdUZIZjZjaVFI
            eFZZN0lhNXdWM29QNjFGQzY2ZTl3aHFzWHkwCjM4YTdWbm5qajh2ZTNTNzRTTVlo
            TXZudXZEdDVMYk11R29vczRDbFJNRXcKLS0tIHpiVUdvK2NlWDJ0NnE2c3dzTFli
            Z1NheG5ZWDFZMXZlcnBjRU5HeGR3MXcKQrDvnyjU3b+326/lUtn7EiP8eIqr3Dl2
            GgVc46/DN7WhDNfNHuE5dgCuw08C5uxDr/wrJtEZXeVSuBy9CTdIfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T13:25:10Z"
    mac: ENC[AES256_GCM,data:OyB28DFLwwqie9nP32ITAvjqmLjlMBMfV8Iz+InusOMIKNSTcJdJMOCWP6QAhreCs2K4k/G+oRgJgkRmyIojFggeEcV/zDgsnwflG5eT2sYhx4NAW+0lJchOGaOQfogtreftv4gGi0yxRJYU/2uqfIaveEvVeBj8wbDl/wZJWPY=,iv:cWTNcdn7nCU/8+JAQl/tyAhC9sqw0ZnUeZidXW57QOU=,tag:9zcpyNr8o6OYnIzqSEXayA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
