apiVersion: v1
data:
    password: ENC[AES256_GCM,data:xQl/QZyxEm6pqZFB1ZLkHjdqrQ+JlrCw,iv:26UQhSeAjW831EPL/5FTVpyHV/4AIp5f7FgWkdsI9YQ=,tag:IMdytcekJ4MZNh4c+GKONw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRb0hFcVBTNzJhODhncVI1
            WnNrT3E5YklUVlQ3dHY1QytadmtDYjY4V0FBCkdHcXZSeGhwS1NZUVhkMTJGU3dU
            RmNhaUNIMFFjazZ1WlFiSlpUT28za2sKLS0tIGpqNVQ2NVdUbW4zVzVFZ29JL0Q4
            eWcwTVBsK2RveERlTGhoREdET3FHbVkKDwo7f+Dij2Xye4QrUxAgVDj0uMkl1/Jq
            BJ/vgQhJuqBF/8jXoAZlPFprw46dyZ0ppPelacRN+bkmRqNtubbWMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBId1FnSW9EeS9HRnRqKzMz
            WmNrZDEvUjNUZEtSM1V3WXRSOC9iWlJMZWpVCk13QXMxR2x1bFlsa2w2UktIamtX
            cnlIOUhoZ3FZMUhPY2dvWENhQWsxdDgKLS0tIDdBY3hPaldlTEhsZGNHYzZsNEVw
            dWNhcnh5L0U2bXdKaE4wd0tkTGMyZkUKpCCJcGL+H80ua5HxrePk56bK34w5gKyi
            rwFqbKOshNmoiuOTGnAM4GpWtnpS2ES3Vs+Z9cprfz5chT5VpgfIAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOCt2YUlXdGRMTWZhMkJD
            b0VScXNRQzcwbm5ZYVVHRHpDWmp5NEhJa0JZCmc0d085Rzg5bHBUVE9tYU5NOEpP
            eXBkSUliajMwQVh5TmxFUE1UazFCL0UKLS0tIDhZbEcyOXVVZjcrZ3pZSUdndDl3
            ZDBFZlNvVkdtVm40RGtLWDJ3VjZXdmcKKic/VdZfKMD6xcD4lEf+W3VwKJPaI6Pz
            Ii3v4tIIFcdMoHR86FHHd6KSnEddvkbhdgmwyXNkq3NMNKyJrbhZXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-18T03:37:19Z"
    mac: ENC[AES256_GCM,data:9wyG7AprWYnAdRkjusE6ETSLUrvSbzm1gBKPtnVy8BSvZ70uD5ExEQs4j/WdWTDxOiUC+lWYwBYvAdYi2PzTfMWMmjcldOBcYRnBRBbLNCwB9sHGn71jM7WhBPW567xpZzp5w7ORki9Iu8Brw/COAfjbXPfqqykE+a4aB7K1RoY=,iv:R2BYYy4GErt8T+Oy7mItlZFV74j9YOelKEwTINRhrHs=,tag:/OdWOA4WCn2q6wDII9KtmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
