apiVersion: v1
data:
    password: ENC[AES256_GCM,data:QVQtn7FSKVA7LQyNgOyNK8AcdG4wuv+S,iv:dqjdUuZfpkQGuqNCwQvcVRdaiYve2cyWodf0cdXMSHU=,tag:JutK+t4qTSe0YfDfh7JH4w==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocytpWFBGZVFhWFZ0eHQr
            cmRIQmVnTUxvcG0wM3VUMys1QVVQR3JybFcwCjNneHNVcEV2VWRBenJyMWxyYms4
            ZnVKbWpsUVcxR0pCUGJheVltTTJqQWsKLS0tIG83bmVGSkdIbFBSaFBHd3h0bTdh
            SHVpUWlwdFR2SXBKOStyWld6b1ZWRHcKzp5nJHlEL2+x00RPqhN+tehCldIVFDT+
            uZQKPeXHEQ08MRwC5QipuHC7CE+LzlFSvd+HaP1YS6fhsKdVNqSbOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaGpIRURGZDJHL1dvdkZR
            SCs1MThlTG95cFhEaGtodEozRlBwNWV2a3lrCkl2YkpaNjdQek5MV1RxSThvZ3p5
            cjFMR29BaWRqVkUzRktXUmI1Nzc1ckkKLS0tIGJkTWpvdjJ5YU1idm9nV0ZKRnBl
            dlh4ZlFkbUVSaFl2aktpc01ldXZRM1EKp1PJ8h3P04n3L1F+L0n7SYeiR6JzOYMY
            Yz8jPz3fALdwTHAlmt7FeoFPbQkXJW2r2sZ7a+n/AhohjYIhENa5ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRHNwbWhNM05zTFNJeTB5
            L3YrZk5vYTBuM0Z3UnEvZStPSWZjYXVSTVE4Ck5YUncwSUR6em8yZ3oxSUcxK1lI
            TEVmSE5MUnM4WEtmaUxNdmdIWW1XOEUKLS0tIGs0cXV4VndxT0lOR0RPUjVLOFlW
            czZpWTJLNEs1MWVaWG41aCtCeGM5Z1EK89GdrMhVoaC9mOTn/52yFwBCU/1YiyRs
            ayBhs4AP2V4IYyUQewhvLq12dDk7gjG9R9EsGaIo31v5AAVoRtJBLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T03:48:33Z"
    mac: ENC[AES256_GCM,data:hedIDUMyBnLtPYkxDEuQCnzYk0ml2om+UuPj1BhyDI3YLyJEQDetaRZvScpoLFOhuZwN08hmtMbDKzqQMuSE6e3+ocamusZDJBc7MDph0wq1tMZ2bMJ9vQovoWmwUXXYsfNaJj5HsGeDDEQRKklot14Q9tOiRBJj/bkMqK8/vac=,iv:cyqe1v66tTsGamqL+BEXlrBFctGc501nFSHCDIOOQw4=,tag:nQmEY2zS/21eWe0DQyNkeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
