apiVersion: v1
data:
    password: ENC[AES256_GCM,data:jdy7AbhYe8aGdoD9blHDlJi3Ke2227u0,iv:ApYWCjdkAz5/oB8i+g/cXWlh2NwoWZEK8Cqr4FMk0cU=,tag:hWifnzekQHUNDaDVa21ZEQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvanhOSFM3YW41T0ZqQkov
            MFdyTkVSVkJMM09WRTFKSFQ0aXZOemt1SjNZClcydHpTMW54ZXQwcXZzUklJSWIx
            TnV6cHpNb3dXaFAzeHloYlc3YjFnbU0KLS0tIGxLQXltY3RZbmI4R1JyREhraE1W
            WmViZ09MNEd0WjBCZDlreTN3OGZLQkEKvl6e80Z74u+Qp4vgU3thB+VNcMh4xUeJ
            eLU2WjRlTLJM9MKxpW/tMybpe+E1+toY+UQrtus72aLkHfjTTa71EA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d2xyV0h4Tk1rOStnYURu
            cFJvQ2ZHQkFFUFVTT09sTkhTT2pZOVlQNEdFCmdIZU1FczZkelVkM3ZpNGxTLzFF
            QTdINFBHMlYxNG0xZDc3YTFORVhTYm8KLS0tIFNqNWtUd1dlcERXeHZnWXlGeDdM
            YXZvUUswNUVKMFZtdWFyQk9iSGx6Qk0KcmUKXOEWwkoWF2kRp3niSICfMS157CJl
            yYYMfUFDrFLqODC2ZipomSDutLqILa6TwZBN6xRRUhDp+HmPRl67gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aHRXMmNhR0JmYkFSZ3Ix
            T1FoSHR5K0o2clpkR3BYaGlvUW8vVm9MUmpjCkhQQ3lWbzlXK0tIdFhtTWROcTlT
            blhCMFBHVXQ3SkF0WUFmWXdjWHlVY3MKLS0tIEVBVU4wcnRTaTNWMlhxTHAwdjBp
            Ti9uOE1hc3dEMjhFa3pJMmpnb2RrR28KvPmDe9f4do7z/1egPCrW6u6+2rVRE0p0
            /s5AbxQpdZXe7kgqLl9BunG6y6ve/jVixFIUYFFJIpbt7Sy0w02U/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T16:29:37Z"
    mac: ENC[AES256_GCM,data:hUbiKV+eGAWuJzzuLSudCYMH5cRcybh5+cSmakvpS/mav4zdOIKzNA8nLjMzl33kfKN8IxTGIdw8q1G8PDt+PaObqJkY76ve8ZZz+XW50vLFFgNPi/ReDbylUKBbdVYcczjjs4MPdDUbHtieBETkThdfP/S7tMV11BR/x8iLDN4=,iv:PDHnyIbf++Wzr0jlqR2bQOh6bhb+c8Rdst0PK7NwWt8=,tag:P0/ULywNWQKylWzFPlRFwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
