apiVersion: v1
data:
    password: ENC[AES256_GCM,data:tjibZMQkcHyeNAEWfg1Pabe3wlMSTs68,iv:J+7JsGNfMb0lA2o3WUjtT7yW4TF9XAvDrVJtF4KIJ2w=,tag:vAfP/Z7Pa7oD84j5M1R92g==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: pihole-admin
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaGFGUnkydy9XYTJ0djM5
            aksraGRMYmo5ZFc1RlB0a1JmSjhRY1NCRHhBCkJhWUJtbEppTHVDcFRjL3lhMmh3
            TGhrREx5anloK21vdzl6UllDUVI2YzAKLS0tIEZqRExKczZDMkdsdWJJZTdIU3Zj
            YVhvT1VjZ2g1bGJaeXJYUm9VRHpQUzAKDge/Et7KDrAdEzBEER1Pluh2FGatoxU0
            EyS9Q1zT9wTH7wr8mpNTYttVkBTTkNnRaI/3gW2sGo4jcVcpp86y6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcGN1WmRrdFpHd3VQdGpv
            S2JJREZiU0lmM29LZURMdDF5TWNuYUt2dVY4Cm03NDZjNWcxMzA2WWJqUWsxNmVm
            YWxQdkkxM21kdUttcFJxLytHOFNaNk0KLS0tIEdIU05hWnRLbisxLzhDc0RTak9B
            cXovNXZ2ZFhUN2dmZ2FucGsydmJpaEkKgIgU493HAR4xAfaLeeoxoN5tgvnd7i0H
            BHXMwzO4mMpq7txFssfkBD43zLgXr82lx0FqYbgV5kYb391nyaX+5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SFJ1SldKVmN5aEE4cy9R
            KzRQeGVybitjeEc5RkFHL1dpcHdqMmVxcVhjCmdwcGlqaU9iQ1VxTjRrSnhWck8x
            N1FkQXdNTHdNMVExdTVqSENFbnBTOGsKLS0tIFZVYklqV3BtSVEyNFlGQ2h2cVl5
            bU5rL2swMlFTSUdzOTNZQmYrNWdmeUkKRZwwe43zeKktqXu1UVkpj42bal2d49F7
            Xum3cpURxDCwCb7gaXO/8Og1Hl95O/w1yIfNklmV5rRbuOw33znVdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T03:04:30Z"
    mac: ENC[AES256_GCM,data:nqUZ6tyGF253VEfFVxJ/qVhV79F66KuGqfe4dtyeWHIaq6kLofwmYLA7JuVXEc+PRK3aiXwnvf1quxvlEB8XJJUacU1ht1PiGYwhJ/No9phqO9UsnS4cwctXCwEjamhjyMoaP0NElhp7RLBjGZFt/+XS4G6v2QDV3x4AK5P6cM4=,iv:jNOI7tO7S8bHNIKGZcugUvg1GRXj+6063CadfzPHC5w=,tag:QUkm9XGslsC1Mv+MWXy9xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
