apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        grafana_datasource: "1"
    name: grafana-ds-postgres
    namespace: monitoring
stringData:
    postgresql-datasource.yaml: ENC[AES256_GCM,data:IM+XqF0xZ7XAfTua5OB/XWm2GGhucNvhHZAClcOqiCwPQQuV+pS896c/708qHV0zXgM3XbRe7jFlTs5wqXhOqrGcaM6iZwb11MStD//AvB++4ZcG6zM92kFNvZBYZNTAGajlnjEBi4d7QH6CWn6uHDAxGIYbA8moiKtIWlxQimqa1evKrxH1ujjpp00+zLdGYmEjahgA6cftR4Zvlnf+jx/VGk6x5v424TwDyeZpspkRvMnG4NAV1HC98b+x140+LV+RVY/d1DkaCe327YC4tGQjbQ+YwzhV+GTPb78SQj9kRWVKCKPnqyk/ojf+wzN2xj89FbHpELOYV5hWfK2OmqjoHRvL9nRAlGkMvUyfzSlKgL0emd3z89p2kv8+Wb9kDMAiqGslHuHdvWv4GXoWXHh3jqChaxRCA9bzWz3WpWZlTwwiT8ItOhlkzzDB5LX6kIT5ICN0c9lPG7gQvAt+FIrFA80rk8J7jo3ESHseiDobrYfP9wabjnivhG3Al5zPwbJcoD+7GzBvGgJeJ6EeIXxaiNuzTX/GXToN8xknQP+TIIOXViV4KSAOq1hZCuTQou7r/hsmFh1yVJy1F9IWxDBOKAq8/MxAAB9d/w65M/Ivh4eQ8hbo0CPRfH/Xhc0N5Nv4jdKodi+eV7DTCSqKxyBFBowzSyD3CnsYr+hTCaXKU5f14Tl29kr1qRNBCwP2plsPoFDnjTcZQqGqBFWsv4nfcDCUWmXqnHFBLhQopZaIORInInxV1sMDaxE4nQceq1JRZe4qImGpilMhadDU3nU2tFJ9PztTz02xSs0AIYf3hDa2bvkJRkLBqNnXqi2ys6yExQUTvpw27mgy0s0uSdnoVlUi68w3dw2MKS1AcdHz4WAt/v74HmYt4pNjL6C2jofzt6kThkfj39AfBQo0opQr3gJKZ2lfVs+RTd1ncsiMwUtkFX+0kLH+BbYEjWIxqTLDDSlQZi8oTjAoPiUmf3Wp1pUTQMUuD8BGB477G5ZPvKNx8bggETTlVbwI5OLIOA1isRN1ljCijgftqKuoSeBVEZXacPpjmAQfzQOGDwbZFCICDWrEiNhT/L94jYHAF0KmwOABQcLrwIhCocb7fmEi/RgNtOxnlZRm1n+1sV605OugYyMNKG/lPSmAaMDsfyUSoUy842bwSHQJ2ODE8bNwiW1RLUm9O+6fLs5BwMl4NcGGpI85awqMKiO1dQ4DCQA76OrAeVoOhXpVTzoM97XyjhioB407H1wMkNBXEcx53zVQoeXrBMFPiYIWmw93+1S4LvQdkdUwwn5IZrDZ42QvKA==,iv:VOFa09NP2lQ8CdX0HPVtcepuZlK3zizK+PA6dBIVw4U=,tag:uPVZ94nqumkKQ6iXBNZRjw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aUsxTHBNOXJXekJjNXR2
            aDBNUG9sTkk5Y0x1MzFnVDVPTEtMa3pwNDMwCkN1L2t0L2pmMHlVa0dDMm1pdS9E
            MUlOTktPL2drNFhYYlFkMUNwNUZrdXcKLS0tIDRiUjBPWDdBN3dwbDhTa0dvT05C
            QjlhS255ejBQM1F4NTdxYkxRTzgxSVkK6ATSr3+sT2UOOwKSHVUBhl2V9Xl9xHD9
            2s+ZHwHjpNmISn/Iy7DGbtnVD6mtEIGuPTOR9xDXZ6QIoPFhlEngew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiL09XNXpjQS9pbk5XZW52
            cm1pMVQwVUpva0R0L3Urb200UTJ4aUMvL0U0ClRLd0hBeXZucDdQZTY0eGNzTFhR
            eUxyeU0za0JMTWFDcVR3Y2ViS3hlNW8KLS0tIGM0WDhXZmZXbU5haHFGTGE4N1Ja
            WGhzVFZFMnhIbnhQTktOTlhHelhhQ3MK3RI6jJf1pXRpX/mKy27qZr/wRNl1TM5/
            ThXswNDHr8j9Yt6Fs3Ke36jqDIaA/pZZKGU6tjoFRpXVuRp5qozU0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTzk2SEVJcTlXMHM1dmdy
            ek5hRk44Y2t0cEdaanB0S0lDMlFia2ZXUmcwCnRmRXQvb3JHUUFrUUJRV0FXRGtm
            eE1UWmZxOU9HbkxaQ21raW5PL0Z6eTAKLS0tIFV6emJWdmw5b1Y3TFhDUjBEYk8v
            b0tkRk5ONWgrT2g1NUYxbWtCSmpvMm8K/CPZc4oBv/iTuOCnKzfSbYrKBuCtaBVr
            XUxXN2m26FbzD2Ozl/QSgsdw26H7DCZzMzpo841GuhAZC52j/KSvfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T20:04:09Z"
    mac: ENC[AES256_GCM,data:NnOXHdIkIewoU9Kosgch/KPrV3jsgLTMuuVKWnMStESQ3Kolc00V3YsBpIYxEiTWKoFApG5IttqQJ/chJF6p1AnglXzsnNoi7kp+W8+mp5HBRhkOpwpX1YgniM2nhhD/r3cAXnUaQ2qAxVopT19/zXFoJY2BlV8yQ6KLBki7Tu4=,iv:AeBdWn/f39PCoTCXmtB6SXfc/HQzmpa9nP9jRU30jfM=,tag:ZFzsuUtRj6K6rpyRNDWkeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: postgresql-auth
    namespace: apps
stringData:
    admin-password: ENC[AES256_GCM,data:KHY69hbJU/YFSrHoICLgh8ATAQ==,iv:fgJ4rd8tq7qdtKAolb0L7QjEzH4qyVaUuGTjL5UC4sw=,tag:XExh2VMmsSS/H6Y/KTp4DQ==,type:str]
    replication-password: ENC[AES256_GCM,data:FpPeaaqZh+Kp9WQQJiFZHucgzDM=,iv:+JsAqzMsFcK+8P4OPVTtR3njD6pGceUo0ejzbfrWxRY=,tag:G3YbZfN+q6X+SVtfqCryAQ==,type:str]
    user-password: ENC[AES256_GCM,data:Dz/hb9e3iIKRm0LlqFyPZX5j7RwhOTE=,iv:RpekXC2HD/8hdS0XjrOjiPNyEepBWY2QOvBozzrjVg4=,tag:7VAjVjXNbT7u9JsMxrLGOw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aUsxTHBNOXJXekJjNXR2
            aDBNUG9sTkk5Y0x1MzFnVDVPTEtMa3pwNDMwCkN1L2t0L2pmMHlVa0dDMm1pdS9E
            MUlOTktPL2drNFhYYlFkMUNwNUZrdXcKLS0tIDRiUjBPWDdBN3dwbDhTa0dvT05C
            QjlhS255ejBQM1F4NTdxYkxRTzgxSVkK6ATSr3+sT2UOOwKSHVUBhl2V9Xl9xHD9
            2s+ZHwHjpNmISn/Iy7DGbtnVD6mtEIGuPTOR9xDXZ6QIoPFhlEngew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiL09XNXpjQS9pbk5XZW52
            cm1pMVQwVUpva0R0L3Urb200UTJ4aUMvL0U0ClRLd0hBeXZucDdQZTY0eGNzTFhR
            eUxyeU0za0JMTWFDcVR3Y2ViS3hlNW8KLS0tIGM0WDhXZmZXbU5haHFGTGE4N1Ja
            WGhzVFZFMnhIbnhQTktOTlhHelhhQ3MK3RI6jJf1pXRpX/mKy27qZr/wRNl1TM5/
            ThXswNDHr8j9Yt6Fs3Ke36jqDIaA/pZZKGU6tjoFRpXVuRp5qozU0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTzk2SEVJcTlXMHM1dmdy
            ek5hRk44Y2t0cEdaanB0S0lDMlFia2ZXUmcwCnRmRXQvb3JHUUFrUUJRV0FXRGtm
            eE1UWmZxOU9HbkxaQ21raW5PL0Z6eTAKLS0tIFV6emJWdmw5b1Y3TFhDUjBEYk8v
            b0tkRk5ONWgrT2g1NUYxbWtCSmpvMm8K/CPZc4oBv/iTuOCnKzfSbYrKBuCtaBVr
            XUxXN2m26FbzD2Ozl/QSgsdw26H7DCZzMzpo841GuhAZC52j/KSvfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T20:04:09Z"
    mac: ENC[AES256_GCM,data:NnOXHdIkIewoU9Kosgch/KPrV3jsgLTMuuVKWnMStESQ3Kolc00V3YsBpIYxEiTWKoFApG5IttqQJ/chJF6p1AnglXzsnNoi7kp+W8+mp5HBRhkOpwpX1YgniM2nhhD/r3cAXnUaQ2qAxVopT19/zXFoJY2BlV8yQ6KLBki7Tu4=,iv:AeBdWn/f39PCoTCXmtB6SXfc/HQzmpa9nP9jRU30jfM=,tag:ZFzsuUtRj6K6rpyRNDWkeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
