apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        grafana_datasource: "1"
    name: grafana-ds-postgres
    namespace: monitoring
stringData:
    postgresql-datasource.yaml: ENC[AES256_GCM,data:UM1e/m7QmYS4asRisRXADYeYx9tdThVS8ofZdT7AFpdafsu6Ym7cQqT51YKzFXo9Mf1zXXVZ0O4ZHdJAlCoXZi/wY+8XJtvcJj7V0Y+i6BcSH2U1W85nY7ld2I+xisg3hvToAF7MV3tY+X31jo7EjU8ObifYYQOBY6DzAjJ3mvyMAlkxF2gTwA/5IE8uRjhGhLg4GCFDAADaqxlhNuBddS3nZ1lk+V9P7DfLcizgVXW2IJPyLLV1dxKVtQcS9tN63CeClIuxN7fku3XRuZNcx5BJQl3JqCZGomS0ARqlw1r1lrNa6hk9hGF3mIwWObT0Sa+uIA83NP/0XI6Sz6sfltyjhWiPjPvG0R+YZCEWPtRt5UWrIGiaAuwYNkQQ80gI1HmIa21yuGKdyo2w+RzCgpeVnTbX9kg5XkDBMdT6Ss7WXJ9AOzFv+XcqODZQDGs20Qp+19dQhkRlsGPwuH9RIXEVOFLAeJPEvyDyK53jVBZuFXjPyXfk5eydkExTXUcpgVIGC7pMXtFOw3ng0WGVHClYC0KcrinMDNzJGnZcpQ7qGgNhsQLlE3O0RxjbDGjkHgyGKKyz+YoiZdtaJiYEZdlU209puPWjOHMSP6x/WSikFvVTZ/Gu/5Fqk/2vPP4QO2/KYVx2+qqCAPMzBqRqdYax6sew9C6xepJYXhgnbWbLGAiX7iCa3U2arB5aXl3EXv1czIalAyhcp6K3t/1wfJLAlOnzniw3S+NPcwY22XJLp1LkECuHJ4891wV7f91f1EER3RuTv9k95pfHKXrsMDc5MFuOgAHyK0TWnpH3JUj52INoVZm2c7l0T6JLbF5JDUD6vcZCRfF3oHgH2hj+uZunjVIEJOGox47fbLbFh+9rJZb2OTwrC2qkU03IZZIHU61sOiGICT7jDsjhxkJr5TS0dNDNmFuQMyI+pdlWgzIwsmBuwk1RaWyuF++I5VD++6itkbwKo1VoS1uq/U0BrYv+Ua9Vv7OU4thhTfRjq27r6pcj78Rrs91iHRvir3/jOMZD7b3EIYPG0VUnD8pna7m7Qw5Jfr88FNNx9m5m+Tm2E9UGRlEQR+7j2nOhJmeE1Ofwlz4M5LXjC0big8V/6KaTImWcAfS/L7WmIKD+2SN2UZCt84Fa/1j7qpK50K9LRdewNeOGhU7suAVvObW1NQ/zpTD78Vwr0x4V6r+Qh6/50hF4IWTvWHw428KtHRmEbAUo1pbo/Z9cvHOJprZklOAZfIPZG3DSnyyZ23ppvOMCjQ1W9FK2ZJWVQOTzDEyfKMbEtEDMjNAcOJl3URbCUSyhEjDhE5wNn9qGi139Wn5kjqY4wZo/DG//E/ozj6s6xzHG+5RwX3iEUMtjAE3AEPLNsj/cOVKZ/sKNOCqNxre9h6k1b/nHG7c6CdoDOijyY4Gv4IvzGC6sANAIQlQQAFFKvF/YGet+WAbytehAGro43Jwc7guMlyPTSkt5ewCkAyaodCotPfbYnQ==,iv:JvBNmm/Uz4tO32khdff0o209DT+pEyKTYc//xrqvQfU=,tag:SKmK275LRDn+JoKyVdRAfg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNy9pZTFqOHhLakZrMnds
            QUZWc2d4ZzcvcklDOGZ5MUJjemppUnhDU3lVCnJJS0ptNmZYVk5XSXlqL2h1VTQy
            NDBoRXFrRE5OMFJwU1hsNnB1eGJ2aUUKLS0tICtOSDdRMjV5ZGNvS2VjdXdHc2dv
            ZlJIQ3puRnRzZjlxM3FFOGpuS1BhTU0KzBUc1mESPNjBS8GB2U64kwSU1adUzyAt
            RHhadd7imnlQHSpIDsPisn0HqsBkCWSqaB3oDLZu5JQJB62t6y+aBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUnJJcllxRW9CT3RDMWRv
            d2NKODBUNDZiTkM0R0cxcWFIdStqVDJ3WmpjCkQ0VXJwT1IyZEFJeEY3SW53NFBl
            OElHTHVjenFFZXUzMmdnTmpydVllNlkKLS0tIGN1SzUzUEo1TWozdVl3OW5ydFN0
            ZUU4TVNEMEYyWE4vcVFiOExNditFSFUKMiaBrotRdW24HOj5vv/ZMQmqcA2Q8kTW
            0+Bd89lNUMYYU1cpPLJD//q7EYGq/S2fbsmvI0pBCVL28fyDlSacdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZmF4V2xQZTg3R1dBTXlG
            YXZQZEEwY1h2cVl5M0pDMEIxL1pSZDRacVNRCm9sZ1djRW1XaitLQW1tVkNMS1NT
            cnNyOG5HSitUUDk0WWV1enNZNEplT0kKLS0tICt4dk9KNW9QQmpkSnZiSFpkY05y
            VGZHTGFNMzVhdHpRSWdCMjVrSXVXY3cKY9QThWaKB4mRD4VRapbko4czG3imLZDw
            MY/UzO8RKwbj3mvxDsNBDO1iEswZSnNdb15aoIH075WWlJVv2sy5fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T20:20:13Z"
    mac: ENC[AES256_GCM,data:upQ6lWyUq4vfWKtwHx2hDZX22aJlpT2q/h1TiyAlc4CxurgZf54AZqc60eCUqb3iDQJ/d8sb5jB8G/9Ook82v92oFG7+xd7z2Si7L7djb+Rm+NBkYS+50bopjrumVMB7Fx2VmKf0uGXaY91iB6CiVriwXfix0WgdXqWCO3ppCTs=,iv:JyCHyGdOSxczuqS7x82lCFxTjMBgb2jma8YG9mR68G4=,tag:UpD6+k5TkRefSvniZu+AVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: postgresql-auth
    namespace: apps
stringData:
    admin-password: ENC[AES256_GCM,data:i79nqk3aAdFjuDOrHVhnD3RAPw==,iv:alyupaMRWfPGhfXRpKQEL702cIf1I4ciFEZK92YimrA=,tag:0PJuEMWpg01DiAvMQnquAw==,type:str]
    replication-password: ENC[AES256_GCM,data:bxVavO8PJM7MA0TZwt3VwGtZbAc=,iv:WXpRshtsfUAFV6hljUNVhacz6zj4LfqtbTmCvhCc2s4=,tag:RtoeCI97SnaoRLNiWUynLQ==,type:str]
    user-password: ENC[AES256_GCM,data:aK0p9zfuK7Kja+bafDX5u8IxE8ZgHM8=,iv:gb05WMUgcGt8/wYJPaA7A73r3xglABT9BKkKb8i73vk=,tag:9gGdMEKAsP2l7HE+iKJGrw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNy9pZTFqOHhLakZrMnds
            QUZWc2d4ZzcvcklDOGZ5MUJjemppUnhDU3lVCnJJS0ptNmZYVk5XSXlqL2h1VTQy
            NDBoRXFrRE5OMFJwU1hsNnB1eGJ2aUUKLS0tICtOSDdRMjV5ZGNvS2VjdXdHc2dv
            ZlJIQ3puRnRzZjlxM3FFOGpuS1BhTU0KzBUc1mESPNjBS8GB2U64kwSU1adUzyAt
            RHhadd7imnlQHSpIDsPisn0HqsBkCWSqaB3oDLZu5JQJB62t6y+aBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUnJJcllxRW9CT3RDMWRv
            d2NKODBUNDZiTkM0R0cxcWFIdStqVDJ3WmpjCkQ0VXJwT1IyZEFJeEY3SW53NFBl
            OElHTHVjenFFZXUzMmdnTmpydVllNlkKLS0tIGN1SzUzUEo1TWozdVl3OW5ydFN0
            ZUU4TVNEMEYyWE4vcVFiOExNditFSFUKMiaBrotRdW24HOj5vv/ZMQmqcA2Q8kTW
            0+Bd89lNUMYYU1cpPLJD//q7EYGq/S2fbsmvI0pBCVL28fyDlSacdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZmF4V2xQZTg3R1dBTXlG
            YXZQZEEwY1h2cVl5M0pDMEIxL1pSZDRacVNRCm9sZ1djRW1XaitLQW1tVkNMS1NT
            cnNyOG5HSitUUDk0WWV1enNZNEplT0kKLS0tICt4dk9KNW9QQmpkSnZiSFpkY05y
            VGZHTGFNMzVhdHpRSWdCMjVrSXVXY3cKY9QThWaKB4mRD4VRapbko4czG3imLZDw
            MY/UzO8RKwbj3mvxDsNBDO1iEswZSnNdb15aoIH075WWlJVv2sy5fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T20:20:13Z"
    mac: ENC[AES256_GCM,data:upQ6lWyUq4vfWKtwHx2hDZX22aJlpT2q/h1TiyAlc4CxurgZf54AZqc60eCUqb3iDQJ/d8sb5jB8G/9Ook82v92oFG7+xd7z2Si7L7djb+Rm+NBkYS+50bopjrumVMB7Fx2VmKf0uGXaY91iB6CiVriwXfix0WgdXqWCO3ppCTs=,iv:JyCHyGdOSxczuqS7x82lCFxTjMBgb2jma8YG9mR68G4=,tag:UpD6+k5TkRefSvniZu+AVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
