apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        grafana_datasource: "1"
    name: grafana-ds-postgres
    namespace: monitoring
stringData:
    postgresql-datasource.yaml: ENC[AES256_GCM,data:ZE1ixuz37O8E+Pgl5to2qRdNKK0uYOu+K4JNji+UVUfpnG/xLYKCrFbRDbWLTve6r0E/wDiuPkPhNnHpG1eAONQYEYJPMt5p/YvV8+2zJt+qUWtTCLrW8V+W00Voag2o6MTaEx7rwYpnKF088GE8iS8gPQfrX3t0GSO6h9IzVwAwyALMwhzq+B80GxU70jCUpt4dfGM6aljR0IyLH88q5IzINQVgNH3sVz/X0XnfcRB33Y23L7WjKGbQgCyq+h8ng/H87R/mkayTZCvGPgDYa3kLKY1MgMUDS6rSbDsDb0QcZhTC5MzchihENPeGiLv0XKeLBqvfAyl7u9XpAA/TydX2WhGy3fqPCvxzjuuj1QZyCTXjYqIarRTMNllQM5xc8A5TNfnqQ53LgNRQKT5RkU3SoQI1m6uZQTcO/bjOjO52JvX/c6WIudancenIA+TZ6+cIM3byAdDyWGIZoS9Ibeur2/Dor+S9/u00EY0f2TKWt+U4MoiEuW3y9+8DdSrWO1S+DesyYAGrtI82GBtCnVqru41EeUgeHZYmV4mzLVKp8dDQvjLfAPBZWytd0681X4gmTDiZK6XYvFAUNgBAM+pXBqHVZLPAp9dXYD3ZZet56U8VKNOO3VDP2IEzETGAXjT2Op2i/0mMNcJvBhvNNxbfegj3W3ZCTNHjmZXLy+Ci8b6S99+K1uSARqQVN0Z5ME/3/4gbhbQF3aLAoOeJ20vlusVrevYHpAb1IQ6svlRu7xmnxRElPRjrUVfKGzDtCkba1XA18XEbfIgmIM7lz45/sSQrnUq/jV4chuFoOmsXnFDKyRWaCx9SuwvKViPWlEiMBHj6WHAQ7u7OtCtt8kBAoGTFwZAu+9Ksaqvd7QLLsA8JERrCk2622dGJd0NC7d288ZhQaTmzk1TOS+RfJrpdbJPdwKuvnzT+KosqWS6JiPrrSN4VQ+MimoFbQTy1Wov7tC0ItvfPFAq5tEwAq4JD8pmdNoI9TmIOUoIYudSSh7WChlHM+wwANtCUCsJ68EhrcXjMN2YzrVBlEafa0ikDZyus4EbVCHgrpHOerk7OjYjEOucj/JJkd/AC0d3xZyOyrL33dJAaFf12qhpEQ7WFS+CzG7KtlaovIljAlbJICvCrVdVChZpdMU5awc9B6FFnJwpLEMc7R+0Hi3P4yd8WOCj9HE6KdVQhmBbBr8XOLNBmD1seGihVMmAoZS22zmNy6LsfqjFvY5nmDuSnO4qCIWJuMmnFsFFYcmfypYx7kd8vfbRL3qjgFF8RDyLDFVXWatdmwW7TY4JDPbH5N7Vtp6mYKa3keKzajH9qyJeQ3jle88v08ECnBgSFmFFKKLCSWlN5z8mSVQpS0SyxKc1hLvrPCDryon+d/UTLdEBQxFrQqgg5WZCQZz7PhWHRsVAV+Mnv2gv0hsrSo2KbnuyU7RAh5lWoNRcTYMQyfp4E1XZTVjDWmnH85q7i+XXVYEa0DImqLE2bLr6iDRzJy0SGQI7ru45ntXYBOmZbKcry9ro6O8w/t6YLruWvUerxFfvWTMyXRzXAwvMKMGGx25x4+O73ax3LedPvBnRtvk/7gq6BKUHCnZPF+lluknv4uHkTJTML5UehjqCA+c5VNmIMrssW3aeW7iKVr0+MKqlJpFKlHVV0qB+W9ykJOaDQ63ZTgxMajo0wT785skW6NwJV5Wzukd+03gdyUObzMGHSOLomE+FQJ9dEoqVECv9YRTyBDeNi6Nn+VPSrdX7zZY0LG/oBiOqlpHGor5C5GaTef7S20aaxE4uqOc7JWawfu7ca4O/BxUi9Qg3qrTX8hq1l2i0s+8CMJ3Onl9fD5AQqgLYMQUY/RQQW4yAnks3sKo4OVHprRiZDgAHECwBw7cQH5ZcONJFjNaIGwhRwdQyG53boCW9OgiXOukivmPDexjBRYETTrQGKQJQ+VqKNtfl/5k++DToaLB3HwI6tCtVRLNh/ARo94Zhd5XjRNfLX5m9KFE/V4/m4RAkqBLCyMjBBm2g98sIWnTIlTihlZbMBvhgYZkFwpTgZ0VB80Vyo3cMNkfVltAaa54I7osjI/Lkap/M6fAg2KM3dfe+NNTkBF5z72/Uk0Ry1wCoHJZTLYzw3HahMLgp9XMZoE7DlbOpBCWPy+Lgxbq7QZDOpMTo1/jqjHhMu2NWJHbR2HUkC/YKiMyZG1mpB+djN7vhQMo9qsSNCtZAx0SbnEzvZq42Nu4xraQj2p3paGt3wdEWqWc1D/+DevTDY8s1U5dqhMhTOr0jkQab/EpdfQKlytloF+LCrGBu+7ATuSyJamPs7HN6YOffdXuTYp3qo303u3PxjTq4KRRLDZXUNeCIb0UYpXKqbq9DESEji2iNZTXr38bGkaEjPlDB6wZQQjFgzTyDPMxp4foWcSQQ2D6tB+ZhTB7V5cKa1ezXkJEPchyuYH3+O1xRmsRHcQp4TfIIY31inrU8GQWkhwTrQlbjQ66Ny142aAdOrjAmer8cUF614uRe8rw/6m1evLmUPz9ZIdQp8yGAHrzdjWJ++cUcNtp6AHKqPtzbDLp2QFr4IlBpA17/IhCW5cWEzzGZUNJkAIyyTN++YyUd0HMfwtZow2GpkphQ8nb2tH0JmwLD2iiswz+Ec8Z0bt9g/3lsvMeHQCPzq1f/AYFh7Yz/4DrdwK5TpibVDMBK0jzgOEH926YAfiyPo9dnoCxVGA0FKFwt5lFCgLnvGvbCDpXD8y2GQ37Zken1mRkunCz3ezrzQiZ4rN08sUWZLIZLqSmZD2iUyNTyIdD4IH0BJVBoc4TSvqR/4E75QoAkOXC3baOktRkfpz4tWSI9AXk5acaXLa0O8is3FIu7YxTVS+/TeBYNEm/YmrYYRMylUI9vpTuZ1+GM8BTTuPGYwdRqCMm+7nWsnT6jWGGkAaBgOjBU/cdHHwLuMXe0XtMk4mN3f2Z7NQhiWVSRMOVt+48i4+bGAFrIazKBkQkN8KxW4cNr42gydYR9TvuhnnIjN+LtWGhcE,iv:NMX74zWZPRXBimS47gcgImhMfl2Y9HYoGxhXbwVGS9E=,tag:gR/+f9FQGxjoe59SfYWlvQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZDc4K3AzVnZGU3dTZkJ6
            aGpuZG5PQXU0S2lhd2U0dUh3cFpYL1FjSENjCjdYRlJoZW42a2dIQ3p3dVhxRlpi
            cjZMR0hvRDByak9zalZXdHFkOVRQMGsKLS0tIHgzOHhmK0U4M2x0ZmE3WlphaG0x
            UzJqb01BbEczT3NuY1NUU3VJdU41TUEKpsNAOW/uE9Z7ZUgEv+ZYFosPZShN3MBd
            eTfawRhB1qkPA6wiXXzt022PayTyhmGAUiIb/Q8C92KG+2CDH9DqTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdjVuYzYzTXo1RnprcG5E
            YlZPUklGb3RWODUyMFp2R0ZuL1QvTnhXcnk4ClBOcWZzd0d2TWd3eHlUbUZGdVV5
            SytDWUc0dlBhWjluTEtIQ3M5U3dVQmcKLS0tIEphTmppaTRtaVh6QVJOVkREdFFS
            VWlFOG94aHVTVm1nNy9CUEl3L3dwencKlkxLOf/0MhHCWy3cVLotFFQUqVD3Qvq/
            vPIN43JSEYlOsuIZzPcqqC10roOL9DFaqIMbrO2iNAVN4UopgXjaVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bXp0TDRDb3BXdkVQUm1h
            c2R5WlF0TzcrTDNiTDljVWRIQU1LNU40VEhZClg2Q3RxTHhTM3pVMklNL0grV3Zm
            REVVOVo3UWJXMU94cmtTaEMrZ2JmWFUKLS0tIFRtWkVzNTJuNVBoVUN0THdMZlNE
            anRVMFJlRWMxbXM2b1hpbDh3TkJTQ1UKEYGS2PWyk1aI8SKhxwSIcBUZIQdWD2dH
            TJargTJt8qKpfZZi2IBTjXvxJLSsNB0/sl/qCzXJJb9uMnbwXnS5kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T17:59:24Z"
    mac: ENC[AES256_GCM,data:DDikpBc3ieVWpzp2d9gWTl0aoCPIDOWfyjjW0g42V+YFeCzjTH11Nx/2doA8CI9ofeJxPKYJdVIWpsPrjzfuJjp4PLo5VOrs90WxwmMSMyIcwlqWkl8J1FlBM8vWBgsHcAMG+ZBjOqzOFddf7S53s9D23UYQGNiIX7qk62CoBhQ=,iv:BVhVbteokBcYvJHz1k7rQP1eoFD/+1g9G4xKW/klHiY=,tag:rhe15EA37efdGFf2jT2hvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: postgresql-auth
    namespace: apps
stringData:
    admin-password: ENC[AES256_GCM,data:Fq6ZolwhDkQ7Ff85ZLUc94f7wQ==,iv:WvLGjpWyGTVUufHU6pLypxHAy12HgwpXe8Dm+zcOUxw=,tag:UApZquZCy+HEXITNSZrb8w==,type:str]
    replication-password: ENC[AES256_GCM,data:RP50YWgZmQLqEmgGQ0CBvoXj0hE=,iv:kiZ+vogAA3BVEhBOhpXhV7SVrC7UfJAh9nehr2da+DY=,tag:GJOfIW2aW/PvPcsqylX3IA==,type:str]
    user-password: ENC[AES256_GCM,data:lJgQR24Kl+H1+YSqyCs64dLqp2f5JLk=,iv:SMbXhS594Cv/5gXRxDpekTeMT6r76WfIR0hQer5dabI=,tag:ZxrFObu0DP7dDL+rgNZjjg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZDc4K3AzVnZGU3dTZkJ6
            aGpuZG5PQXU0S2lhd2U0dUh3cFpYL1FjSENjCjdYRlJoZW42a2dIQ3p3dVhxRlpi
            cjZMR0hvRDByak9zalZXdHFkOVRQMGsKLS0tIHgzOHhmK0U4M2x0ZmE3WlphaG0x
            UzJqb01BbEczT3NuY1NUU3VJdU41TUEKpsNAOW/uE9Z7ZUgEv+ZYFosPZShN3MBd
            eTfawRhB1qkPA6wiXXzt022PayTyhmGAUiIb/Q8C92KG+2CDH9DqTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdjVuYzYzTXo1RnprcG5E
            YlZPUklGb3RWODUyMFp2R0ZuL1QvTnhXcnk4ClBOcWZzd0d2TWd3eHlUbUZGdVV5
            SytDWUc0dlBhWjluTEtIQ3M5U3dVQmcKLS0tIEphTmppaTRtaVh6QVJOVkREdFFS
            VWlFOG94aHVTVm1nNy9CUEl3L3dwencKlkxLOf/0MhHCWy3cVLotFFQUqVD3Qvq/
            vPIN43JSEYlOsuIZzPcqqC10roOL9DFaqIMbrO2iNAVN4UopgXjaVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bXp0TDRDb3BXdkVQUm1h
            c2R5WlF0TzcrTDNiTDljVWRIQU1LNU40VEhZClg2Q3RxTHhTM3pVMklNL0grV3Zm
            REVVOVo3UWJXMU94cmtTaEMrZ2JmWFUKLS0tIFRtWkVzNTJuNVBoVUN0THdMZlNE
            anRVMFJlRWMxbXM2b1hpbDh3TkJTQ1UKEYGS2PWyk1aI8SKhxwSIcBUZIQdWD2dH
            TJargTJt8qKpfZZi2IBTjXvxJLSsNB0/sl/qCzXJJb9uMnbwXnS5kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T17:59:24Z"
    mac: ENC[AES256_GCM,data:DDikpBc3ieVWpzp2d9gWTl0aoCPIDOWfyjjW0g42V+YFeCzjTH11Nx/2doA8CI9ofeJxPKYJdVIWpsPrjzfuJjp4PLo5VOrs90WxwmMSMyIcwlqWkl8J1FlBM8vWBgsHcAMG+ZBjOqzOFddf7S53s9D23UYQGNiIX7qk62CoBhQ=,iv:BVhVbteokBcYvJHz1k7rQP1eoFD/+1g9G4xKW/klHiY=,tag:rhe15EA37efdGFf2jT2hvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
