apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:zlp6+WlV5qPnyoFbEK0ZdP4yB35mrHe9z6cL+Q==,iv:EyBPGBTrwkomctXEJITt4Qf3+nwlH5gRYWaA7DYjPlc=,tag:oGdFIMDqQGPdQYOwAHINsg==,type:str]
    replication-password: ENC[AES256_GCM,data:vyi9nw02XOorwbLbvkKhIHZYZXZMJKg64j6/gA==,iv:T+wCBwldmWbRRN1SbwpkJVrNoYHD5ixXHtCF6dpiRpw=,tag:A8gjXNjzGh7XdfwWYrknfA==,type:str]
    user-password: ENC[AES256_GCM,data:CV7mMiR6B4mjvcP7R2UD0YP3vYcAVHq7QYqQb3i7yiE=,iv:8lhLwFOPKxRhOT1lINxsR+jUQzQmTok0hTmzn22w0a0=,tag:1dk4tNfqp56aEKvFfyWHGA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: postgresql-auth
    namespace: apps
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSXlJVFVkTTFUZ2crWGhz
            b2VNZUZSQ214THVWRzVlWmpVK3d3QkJ0T2x3Ck9EM3MyWlZpV0FxSTVyZEREZWNG
            TnBLSEpPelJ2RTJ3K1o0QVlsaWtzKzgKLS0tIEsvbDhES2pYTk5CSzB4aEswSWRq
            dHFjV2JObzZlSjdYYkNLc3ltbzN4eEEKOTs7IRUySWy0DNHup4sjk66uBZjAKAsF
            Nit4Ex0pGwGk+heiT7xyT0JBzyZpcrv9sBq8j+RfBRGD1qnu3Ii8ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TnY1cW5WUWVtUlJpSlFI
            UWdKZkV0bUJOeEFQR3BzRTZ0OGVsQ1J4MzFJClFvWmVRYml2cTNxdjh3OU96K3Nr
            NDMwYjQvZkxwWVNoTTIxSjlaYjNVcEkKLS0tIHR2d0piN0tFRjBTOG14c3ZRbXhh
            SGtmUDliY244UnA1ZVMyV2k3TFlIaWMKlCbXzqQI2WLaizP3xAEi99/b/6sfWah3
            g9JLBEY+TfVUrLE2EfcAjz1MHy5e0ThCIynyIVIdAj6O1vQa83ORHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOVJCa1NsQmMzZFBjUWcx
            a1Jxb3hTZkErZGZJWG5obTJPdGxybHRvanhRCi9yclBBVDBnUnlhVWRsNVJVQ2hk
            UUVwRktjeHcyY0lCRllHZVBLWm5uYm8KLS0tIFQ2R1J6Sk85Z0NnMUo2cmx4Rjk4
            ZXdMOHhPUGVyM2xtRk9rT0c3elNkQWcKdIJ57gE3Ct5bnRKWJBWDzOBz4TebWfhM
            RfHriC2L32/Q19gG5B8MafE+03mZ7hJSTRtxvg3Tho7huk1J9/HIPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T16:22:25Z"
    mac: ENC[AES256_GCM,data:2hFJaizf7Bt68jXy36rxh+YirAfCP7R/HkqMihwTDvtrRR+3yaxTwrxtynWWWppPnTbrUAlR3zza7HHNMJFPQsGYWMEVNaeD9bNJj1+8/GCWlRt4HswIpu+8msf1puwvOqm3D8XlMzHdAExQ8/xtXqPgTMqnrsvujfVJ0FDCgkA=,iv:YlAOlKCdeeR8n3HcZemorVTgr7RYNuBLYEdYK3RuJek=,tag:e/4g2tSNeknVGUhkB/JzjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
