apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: postgresql-auth
    namespace: apps
stringData:
    admin-password: ENC[AES256_GCM,data:OKB6NBmsKyC3LgOQ8ysO+GcipA==,iv:OjFudPk6wih7xvbb6AuLVTAJJpk1VCwZ9jbpDzSobXA=,tag:gF4L8s/6t28xn5sUzAFlzg==,type:str]
    replication-password: ENC[AES256_GCM,data:tyTLJoJbdCiWmfcb4pJv7Hgx1Ns=,iv:M4SvVKyJY1G8hzPhlRp9y0fShQZy2mmJFDhFRWJXPO0=,tag:2pUNHNA/4mcPfLmh7xGe5Q==,type:str]
    user-password: ENC[AES256_GCM,data:XA0flLgVQUcpxjKRAN5Yrf4F96aaW6U=,iv:1+X3cVKiCMFTyBe6yJisMwab5xJjlQSH724aEw4hjlE=,tag:iJNMpAvNC/Vu5g8dOqlsjw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcm1xUXprOWZyWERsRmVC
            d2FuVGJlUkxPREdCcEd2cTNXeE9oa1ZoS1FZCjl3bFJKMXpDZEo0OCtkaVRBbXpu
            R2s3UnVYTlJFOXpDbXRCK3dzd0plN2cKLS0tIEpNVVVaWWhqMzRpTmgySFRrblpH
            VXczUjlVb3dRUHhsd0J1dTdGR1hPMVkK12/4P6w2J1IvQzHklG1vXRRvAZKkcv4m
            QFziLViSQDqDM4NFTYRVWlMeJM6zRfH3Xlrv4Li5OM5++wkLvvDsEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NHBMVEZ6cWY4MkZIbjVn
            YmxWaU96am55WlE1RThUT3ZCTXlSVTJJRUU0Ckh2eVNndWJPQVkwaWhDamNJS0Nn
            Nm5XaHVEM3JOK0pFdVdzTnNGQXA0ZlEKLS0tIGs3alJoQTI0UWpTZVdkdEdZaTdJ
            VDdPRjhyRDB6R3ovSTgwNmx0eC9MU28KvQhmVuA/9idGZp4BRo1uVb3dOcNEMKcx
            cFjmOfJQaF+lKXzoHqKC+NpWQzmtsVS6aS0XrG7jREll153YYB5Z7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOXBaM3pETHowUWt2Y3Vq
            R1pnSGZHZVZUN2g3dEcyeXlvWEozRktrU1djCkkzTGo5T3hvLyt3cjRtMDVucFcv
            blFhVUVRem1YM0NFdUxJNEJGVzhSbVkKLS0tIGFIdExuMU50Z2JXMUxTbHN6WEJW
            ZkJ0cHJ0SGRjaGhVSmltRVBaZEkyckEKgpFNfhszzZCpb7zOeROWoEVPnwvnRZ1w
            MrlHgqvSXqVjSOL+j5Qdh6jpSYeyY0XbNTQ7GpBvnm1BIScwbkOHLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-04T02:40:45Z"
    mac: ENC[AES256_GCM,data:V882Gc06XrByTN/iiAahn2jMtuRd3aGo+EKyB90Qv99rwhFnHEGGsy08Nw0JHOQbt04B6QAMNGG63oDFAmocJwU2amtPJauqsoByZGLwckiOIVFPMhYZgEI/lRfFb/FByzjnkeOgnk0eLplUMn7O2vSuk2DI5mRiFdWuBukVqd0=,iv:ODqFkm+Qcyu5Z9TXfmxAwh8tvImt0tRiSJeoaV9/VNg=,tag:4DZPtpuCQbt5/wUmpJzUSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
