apiVersion: v1
data:
    QBT_PASSWORD: ENC[AES256_GCM,data:5iQNZz3ZJfROsUlEaVv6D/NiyLjp589g7ZF77T7pcOIrgF3J,iv:MRy+IlPZ5ACyGbFAvtzG4kYRGL3lru6zO2SdBv1CBP4=,tag:YiS2hkWl8s7UGSWVV4gunQ==,type:str]
    QBT_USERNAME: ENC[AES256_GCM,data:Qb1551wLnGPPXOmS9dHmZg==,iv:LjD1l+PQwxOfAqmKKIawSBMMMRPmE31KvwmHXH//Mrg=,tag:Ec0SkHUDcPpKlnjUUaMgnw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: qbittorrent-credentials
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RGNrQXdkczlKVXYrQmd0
            QkZvdzhtaXdQRlZDY25xSFlBOFJnR282Y3lJCnJUZzhxR1IrWlVvYkcrTGgxbnNC
            eXh6L1ZjOUdGSDM0djFjQlFNWTdPV28KLS0tIHB4N2szS2ZCckFTM1VEYU1MNmMz
            M1lmaEY0Qld3Y1hqY3RLTDVNWGVYOE0KQCJP/ljuFTpAOM5kIcPqzoIxPANU3mNX
            pHnpp3c8NtSHnGvaWb4BDp+L0PLXXTzPRK4/Q7z+tG5WRk5yb2xXAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWVZqSWZOOGlBNlp2Ujgr
            Zk9zZ1o0UEZtYzdSaDZQVDNtNnUzd2tSVENnCnJ1WDlrbzhqcE5MaVB5dk9iS0Qr
            TTFsbVlNZDFzTkZLV0pGcDAzSU9vUXcKLS0tIENsdFBzS1VCdlNucnZSb0FHeUVi
            SnpwcXVrbmszK21YbXBUMnFXZm96VTAKiD3aaExCyXxHxY8MSUEJXHZcth7Q6fJO
            k3cBe6jkEuEnkHnat8S5qBSydcaIP6x7uL38TALOt09KgJA5BbWIFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK28rc1ZQQ2Q0ZDJsUHFW
            UkRPR2V5RVlPYUdubFVocE96OE93Q1czanpVCnJNL1NYem1xZjRRSVlMUUlaVEgx
            Ty92U0dKWjFWcmZsNS9YUmhGNkdLZ1kKLS0tIGMxZUpsZ05VWWsrWGFVdGQ2NEdD
            cTNCYVR3elBqTWIwa1FmUWVNa00yaWsKQG4L65hzJblBWC9Qtlm0Xh5NGCCF7fuR
            widShCNGyqkvrWwdcJpwkwqxuLjXDOUOv/1cdiUAixuKUVbSfREvtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T19:37:24Z"
    mac: ENC[AES256_GCM,data:931kjripThWvgnu2rozs3b9WNWdMh4jwTusnmC25EBFB5RSduCmwGnQ7FvXMmPVKqIl1PTbDi7s/G3vyAzYOprXFZ9LhIqRDpPqtVf93YPAOV4+iRVuBdBypShFzauJ6ncNWWnl42cDmU0B3jN6qeQcUS7OZ+Nl87ApnZ6L17bU=,iv:dTIjAENDsENfpr5SvGjIv4uNHH9hQcW1X0Vph4FwBcU=,tag:wxNGL3rD4j4ZrBbYC+pqcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
