apiVersion: v1
data:
    qBittorrent.conf: ENC[AES256_GCM,data:MlfqJ3PPHHYl3fA7g6SZFlEhROdy/4nu4ZW5P46T9yx08sJvScV9MuYD5diQIMLMrWp2XgZiFTBGn/DB3GUHx7xQroU1s2cQ/hQDcBvAlZSRrBBcncG7NW2l8FEolpN3bv3u/bXiEeheuUFHMyPzolbKyYi4T3l9lofNkvJRSZAqF1Y5H8ZczBohS3cwENDv/dNaBrW+wHFZAg9vBJ/CJ3syw7ASfib3Fs08t89q6ZbHCRZRAB3P0CfrHMkDE0KZFdNLOp5ky1ESurP5tPEuXwQtCEAhkFnq/Uwn4nGn617MLwapO8Wonm/mJy00rseRYcezsqJF1FEoYXpoe2B5G5YoiZRvfCnXpndaC/Vwxz5Es8V5FYBFkRvexn4X+s6F0W5F/YSy0nUV7PDLc+VMK9KxLxiUTV0U/PcKAO2CxlB9ul+HvYYHurON3NXWti6zjwYe6gZGFzCcCpTKW+VN1qWSYUw6OqLy1V4XI+7KpUTQO7vPmQCQRckZOlS4n+lEdEcRTkRbawsVs858v3C5+N9oJJuB5nyeWQTHdhgtWVg7yiOdGoevmQ2x8iRbG0KjAujL6gRziqKv6T4SbLvbQHO4nD20BtqUZQXDvTdw0Gc+bxJlNl6/lR6nEEXVJ4OOEORFRUEutsOD9G7mj6fPbBBMtbO6sY96Od1B6UunO3jTAQzA+bO0LDU5Rmsl6E2PADpYRX8NMY91O1T9v0XzP1fzou6GGa+TlhIY4jeOP/1e28uLLwcBCur4D++OIKvXUsiwRNFMKxhA9sLqPbPwB5SwfAnUUF4rzNQZWRw5Hg47n4Kpfilnfz0Bllf2LwDGeidTeoHHQsxzrjCCZkzt+iEgpRAqq+BuVNQEVN2o46kqR1DbJyxRdTc5t6kVXNfaydnkDrjw33aRG7qApcfCnaTi0tkT5II139A5TLA49H1qFtejkFJvy8FhQPydpGbkkHPFivCS4FCFO6yhyoztJibsgnXeytFMRBaQByrNUKHs2COrQiizXXsCg19v3gmBlHO9G1Mr3qnDenMCNcbN95jda13s0GpDRZkDKiD17xu9ApCuEKBVkKyQpjI/pnFropA1bBNMswu99UptXmflJBMhX9jpAMB3TkSrXtEJNGVYPPtnCLPn1ZOlpeTu7tKn8WdaZzdqFVBUWwAmrHW0dsyVeEUI3wtJ425sOYhxPu1HszGtz+PayMbpjdiFZdQIGqFVYlLLIbpofIv6n/YMcZmr/bEAQThluSfLTAHyqG5BZEFxYcRncmGaUCQEQJLVmYiaO0ga0yr5lisFIvaIQ+AMymtDGYOoVrR6Xzc71QUhNrIzc7gKeEZgBjvmNpgYBRfCWBv0Cym8YsiUvGJ/b1H7O+g+IMgfVz3RCn+CA0gN0dS+6rbJceepCkWL4/WDEM6QOSVdNhzBYErzLSuWChKNy34/suku4wGWlp5RJaNPD3gXRKSbFespD08b+9u1wgojeKC4aQtxGuFfvKE5WIbJb4wlCH8jSA1uE91ZET3ydoDh8B0FJd7ijOuBkgtgm8rLqhnFVcqaTDDY7NEwOoM5k4bFVpNLJN6llQquJxbJEcR8V5HzJ6Q4oeMxYmzUhxzjFX5T6QBMl7MpNELtv585L5cQp9XEPbD0/wojRxYnvnuzarLCeC/zuzPN,iv:mybcc5y4pFGrqw9YnFhbEz4voSBBU91QLtGClH9vNO0=,tag:0yIP0TEF96NKQQrX1ZGhyA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: qbittorrent-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcWdVZ0F6NWNDQ2dmemtV
            UDZzUnFyZldvdmNxRThxUGd6aTZMRXRxVGh3CitLanZWVGdZRmdKclpOV2NwdzU2
            bTR0NGUzQTRPSWdWVHV6YkpxeHVnUE0KLS0tIEhMWkx1aVh1dDBhT2JyeGhnU2Y3
            V2dQa1ZoMmRMcmVQNHVybllTcjd3M2MKHlLZHrRZ7uxbe6paK0qbNHoBBZ/mUzV8
            R1Fy1Hd9kMXXliqafFBCAY7Pg+1TknJuHWAkduZd+OVHYe0yPugp+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeDNSUDdieExWczVWN21O
            ZjF0RFlGQ05ZN3BZSnJ3ekNsK001NTRrSlNjCkpWOG5Fcmc0QWxiUHBsZzczdXZn
            aWo5TGF6RnAvR09LZHhVcFZ5MDZUd3MKLS0tIFhURk5teDdzbmRDWStGZzVySmdv
            enNzM0JFTHMrdWplcDJCTVlGN1ZhamMKznU9FSy2rzbuPQHcBUue6bnAxrh+ZGQC
            80hLYIqafHXE3P+wMja562TRuJYhXCImdOckNGGG4B3r8EhF6jMDLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUVhKS3p3VGhvd0kwOE5C
            VSt5OGdOenRjeXJROUw1WW5vNnlFYzNaUzBZCi9zOW8xVndYYzI3ODRISDd0em91
            a1F0Y1VKbjZUazVXeHB2b3VHR2JQTEkKLS0tIFJ2OWlFUm1PclpKV3RUWTluUUJv
            emYvSXp4eTNjVkFmY2VyOUVXdkZhYUUKMozs/HKKZOr+XduoHQN6d4lSNjS4hz5r
            ae7TFR86g91YO/HMUOlvrcKkwuCmY5KL/waDS6VM+zWi1AlvGp7wTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T00:51:01Z"
    mac: ENC[AES256_GCM,data:8XV+EInYrbH906uN+uAKl2Iyf1aWGh0d7RhwIz0/V6Y2OazLA8az6U6209ILaSs4JCxkZhIwFbwmls8noh5QzHpVgnAUeeggVEgLny4rYgGe1BrvRFSL0PwroZdR76cfZIU16QJxVIBRc39mSXsOpqgK+dT8BkslTPAetIhW1g8=,iv:72m2zxcV9PEAY0xpQCnmDF0uSFZ8rQRLKsOPekRXrJE=,tag:rZeVXv2IJ7d2sKUeTKDeRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
