apiVersion: v1
data:
    limiter.toml: ENC[AES256_GCM,data:GgPW0jY4siUpeDmmQ9HLo/9aHct1HMQ3jOAq+P8psrrLiJ3JArt0nFdRQX7L791CAF3JcSw/EcvimI9jvfOwowoMV+aba5hx88ibZRxv+l3ivr/ISIpr5oacm136zgPpZrN4NqBhVbSM6yDeTtDkNF/rCVKqeDCiYNvLlSem19nbUr7VCG+i1bntehM6J5T229hzY+NDx115JH/T69GRb1EPEZ4uQog3XkrHNbvwoPTE6ANtyKVZjRmOfI4gacRO0SqL5Mi3GJD0e5btd60jvIQriYuJncZ4bZZ5ZXPiXWz5qJM1iM1zFANEEYrXULitSdFoPV/7PjCDrPpqu/wYjUlF4u4+vxk1SGFKQ2IT+wZGKzNe1ernR1lH1SGAUEs=,iv:AEoloQUOg8QfEzRq4p5cpV1Fxs6u//1n29d6wKwKnF8=,tag:2zFdh4TXj7k/Yk+bJq7g+Q==,type:str]
    settings.yml: ENC[AES256_GCM,data:tf/1IVs2ng9V2oNgwUYnXVflJn1+eAU33WXwI+5YVKCSyQmXm0mgMs4tmTvcHpmIm/YTFI4BAWH4wGWZ695MuCUblZHLU6GoCdG1AP1GsTtEWxyRLhV9nI371G17GHMO2ZGIhVrhk8xDaON/4kLd/hHfBOWXCCvi7dg+gZ9qH9hvqw4IfcHOYR7wuZjtCO4uQ/kt4RYpXONmh6nbs+8q2CYuehvlvG58E/kP4CmQ6NaE3jSxXu6y5maRWaBoY9FCO9UIoAeXBgu0u7BG+3FseT6EUt9wJBZwCbH8tjDYkhhBb+EdAhYUbu63TOy7qJNZZfIvEQFqmoLYeYk6fLdy3UdGnFZwu6FxbSVhMNKgTl9leto6yGgg4DZWwrmlodW8N+T2F0xO9T8+pqWhKlXPqKjt/WgPe6wAgWc6w3KLvZ68OOu9dSE1yrLTW+MtCAff0BImooZgHmX7XtfhqJaEpZ/8rB9hJeYfWLxZkZCV4sd94qaHVg==,iv:zsH9Y2p8H7rWboKgOVzXhVDQHdOZmJSMGiypls/1EH8=,tag:mRf7wzPsyfffO5Yv7L66NA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbnNEdzRKSEk2YVRoaVUy
            K0pjRGtRU3dFQUFqQjBWS3AwYjBKL0V6R1RVCnVZNzB0TStvaEhJVWlKT3c0Rld3
            bURtNnFudEdwZW9LR2pyVTdrSlBXeGMKLS0tIE5kako4N3FGK2tTUkI2MW1xbUtV
            ZUhtcHpqcndzWWpVTHoyMUVJWUxiY1UKSzdytgBGn9+eplyeg5L+0Vb2LDNgEwSr
            SoZhtGcZ1uiRCzvf4CQmok31XbhAc372EyEkY+OCQ5J56J+movjJeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ1R4ZzNwOVhiSmNsWlpi
            TDVNeXFLNVhIMit0TzhFL3prNXVMUGk1bzNnCk53eWNOTkZxUjh5SDRMOFdkdkg4
            eUZWa1BDTkZBcDhCdkp1dmpyVTZpenMKLS0tIDBpSm56UXJlemFVYWtmK0EvNGJj
            QXNBWEtWcnl2RnlrTzhtV293OFZwaTAKzMJLvsjl32yKXCn9S27mhwSTPHnD8PCu
            AVlW48H4X/i2miXEPDVy5ZnEEoeZbWhdbgYHBGU49RpjIqJVv9Jk8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ2hWeExXRGtwT004ZFlU
            c1dnRHZkNjRjUktOTkVzbmwyZFJXR0xiTWxFClltb2FidDA5TnRRc0RQZFRPUDJ2
            R0t3a1paOVkxa0dMdkJraHFOVE9pdFkKLS0tIHF1aExweVZzRGF6TG1LNTBEemda
            KzIxcllqRFVHeXVPSDFKZVliMmw0dW8KMX1E9ozMae7+PBDOyrvr+6Tin9tpqHtg
            yfTcAv9pbL+7BImlvNjr1dBStVht5E1RkIxk+9p4na42tTA2FqiaZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T15:32:49Z"
    mac: ENC[AES256_GCM,data:zIn5f2huCLQiVDoyyvqJe58CXfCZQwwm6bfxtFhNBdNG+WjjqtYnwCAEh3bD4vBJFjkHgQrI9eWjweDyNFyct0Z7Y5RYuV5Ven9zpooHHhd0t1L02yR+iezPNEutBhiKpiZSH1g0eMAy2yHRAKavFHamOrtLzAYpaEyNhr9Rygg=,iv:8QL4WuTLZfZZAmKdbB+euR+8Zg5eKW69/G8e49Ywm/8=,tag:3fE9RF8My/AdSkhxY3k3aw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
