apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    LOG_LEVEL: ENC[AES256_GCM,data:qPWYV5A=,iv:n3MEpdsaD6XtwPbptnViXZyb4J0tcd0qzUnJzHAfzmg=,tag:j6DxeoyLuqjGVaeITMwrBw==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:O32QIesnI93zuA==,iv:EL2wNXD+Qwl5mE/BaJeG4HzJ+saWlfEot18mH6KazZk=,tag:5h9/5DFqIE4QMGqtQ8Crdg==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:G1mlvw==,iv:4fW+9qBLJbvCXFbVrYt0vPPiDSz6/Dgz7q8MKa1Ji5c=,tag:+LaN5ivbhTkutB6ykjHQLg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:TcTTFzwtQotQQxGOX0WTVGutUgv/bLFM7wng/+Q46eeFOtimnatzF4tRz3oX2A1t4RDN5aEcYlVk/uOBXVQaaHtpRRuplBgykUO15cnuL9iieEn3kXHoR0avbwrquT2Navmg4QPPzfbdDIMcThyNY+EkNP9qXrO6KEAk8auihnk=,iv:TVeZblShCvugx83FOglQUB3/D1za/ijBVXSroF3YCqE=,tag:lRY+8W2ayHmBFWHe+VHYUA==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:as2edpYq82yVQ5kKiA==,iv:jKCTCsX5X4yEvqzJBxrby3Or2yWa10o3Myoj+BcsBRU=,tag:cLmmCxISWifEe+SyM1xOeQ==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:6nCA9G/x4bUmBAAtCrVQ0rKhyQ==,iv:Yixly65DSpsVTbvNE9HgWi0uTSoMhIy23DjjfljNUdM=,tag:CS0yRUszR08SCKaH8b/n2A==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:N769g3exObx7vjYr8MdQbHjkAvpTfRf2ARvGLRqfelPbilSf/IRx+PM=,iv:MR2w2CmVHXxfZww74qWVQNQJJ6UbHUhsJx2Qa7IyfQo=,tag:1MMgRMLidEjEy5Tx+9dKrw==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:N353mWqPCd5nLMiGjAx7yaK0,iv:2Uu9G8Q7DcZG8+mx1wreF0CTmGzQ1g5znp8kjVI11JI=,tag:l0yqGvSwD28sGI1yUm9llA==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:PbK6mWTr9GRToWMnpFiI5zgFKEVI55leLbvkToRarMAArro+OgRp12A=,iv:6A4LWYx0UQtIudPeFWh3/KYjJR8LF1iuStkJMnkT+Oc=,tag:SmFJsMQtDYCekLl1ipkeGw==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:oIchJoKQ50uiqtjnUqdR7WGQ,iv:rmJUU1nAyiQ2m6EolehKIxRkwG6Qj1ALp+G1B7wnUrE=,tag:hbS6Ru5Ck4WvGvowpvGXvg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a3pZYmN5b3RRRXZoWFNx
            KzRtNkxDSGM4UldreHY1bnJoY2gxcWViOHo4CkZ1REdac0hTUm15a0RpM2p0UFdo
            L3I5NmdTdkxCWEhKbm92akcweHdRVGcKLS0tICtEeW5FSXBlMEFiUHZpMHRnN21u
            eUN5TFovVEh3MVJXclFTV2hTQWpoaFUKJxHrZGdwETY/0M+akVlPG5mOTjmBIgwJ
            iheUl5n6YO9KQx9iufgA2eXgPtWtgLELDQ5P3mYT2AJJi4quR8743w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZmpJZzFaNG04SU5lcVls
            Vk5kaS8xeDN0bDM4SHRKMWVQQVRYT1NOM2pzCjV6bnJTOFhqMitpaWh2WkZwN3FX
            MG1IbWlYYjBhd2c2SEEzZjIrMGJKYWMKLS0tIDlYRFhJWnNaK1dOTW1PWkcvMlVk
            UEx4UXV4NjNtOHNrSmFYQVJxQkY1M1kKYPZuAGDmWWjsThCowM4oEyguEpLRNINO
            wfeOlvZdqjG4/0WEmz4iqoFq3mJLrXG5/gZqaNEaVFZECTxHgrF7fA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZkZ0blM1ckJmdC9EeUZv
            WTNaWFNwZ2lITGxSUFNHSXFpQ2VOcHJHdFVrCjRMQ3Z4S1BpOXFnTXkrdklKTVls
            Y0d3dGdXNFhUQnhCUkdXVWg4VENTNlEKLS0tIHI3UUI0cUlKNkVqSXJ0TnJwV0hp
            N1NJZ3Q4dDJNUGFKZWhCNlpoei8rWmcKzN1SNwIogKzLeyUGlNIMc8mEEruR9LrN
            HZhSk1iQipC2SQrWu9Om4eNBWVN1cWeL36swsZ8FKsWjO/7KQzQW4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T19:35:02Z"
    mac: ENC[AES256_GCM,data:Xe+1kbyqZIMBd8ibA12q3x2o7PpKO6dCD7mnez1v9+raiDtnBAP2UjQZ17nAHbybElrH8Iif1RzUgEiR/x6iZ6a4ovXw9wF4872PtuLzG+10+f/Cu9wLBs/6FbQArm//7WCFaT92RiOEXmPloyN6h4E0YC+SQbe1pzihEh/YwE0=,iv:T88ytJCbWfbxBKdJb3eMhtDojBW8eBRbAr63iDwCiqE=,tag:3FU86X4E56MvcKj/b7T3OA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
