apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    RAILS_ENV: ENC[AES256_GCM,data:1O2lnPgIBrJYUg==,iv:lgTcY7i+SoeF3SDDpWOtwV6qjE1gKpPUy+kAFaPeDJ8=,tag:RPKOjcbLBCwMA46qiNFo0g==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:eK+VOw==,iv:jksin7Etf44JM9wbugtQWtfNm5wYDO0OmqAsfZwmOhM=,tag:gNSx58VSxiU1hA8CdusUxw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:HChSo3cwN0MMxXJBleX1K74sv656zqKrj0FmvbcuRUXk/nlPR1ts+5x/mXGYpYI75zNLqbbwW3GifiVmZJ3MNevM55XKehgfxSffXaX8euSVRGxJgZ+MbBrypaFyA1+NoSL4lbyHO4chWjsasNix5WKCVIhPW+8y/grb1yo4mwo=,iv:aNqSTOxlQN1W8S0lrP+xDHcoUwkAgwIag/YpFRM+PmU=,tag:f0BXlH+IGevbl7oXDv9NFg==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:kPTINT9lSt8sg5nNlQ==,iv:Om7kLoikmD1x/23LJL0DTpgU2yLeGH62scMGw6AybyI=,tag:IVCspiDQzlL69n9iwKBZrg==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:SdjhkXv5FtCC6D1kyFTA+pJVbQ==,iv:pmPHWlijvft6HQJSXolXhfbXZWotP4xtRtoEK+HBc9A=,tag:yYWhNFtz/kHJeeETLoI/Xw==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:wvH08ybcrQtKlRoBvXcsYfgBN6pmjPq5g4JBM8BxEHPe6XUJnQY0MoI=,iv:4LSTeBFUV8W289m3nJff9n44IN7Pu0J38AlDMgye81Y=,tag:dGsat0QkF8ll+TlEZiEqcQ==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:GFWYl3WF9O6ltLy+TPFGNtz5,iv:ji4MgaUObNXY2gzj3ynAfot/a6FTZlbXZktUoBsSnOg=,tag:pDw89Int/roAQLhtrHCUNg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU2F3MzU0d3JCeTZKajMw
            YlhueDdGUEhNSTdTNGQwVk83azFZN3FGL0hFCkdJaCsrUkl6SVppQ2Zsc0NvSU1s
            VHNiVit6YkQxenJ5bHVucjNKWWk3RWcKLS0tIDVsZlJ1U2gwVVZaWnRxdzhMMFND
            aW5LRUo3c0lEaERqRFNNM1diWnJjVU0Kb/4yZlXnqBnzm67YaG+sqFet7SYY1Px/
            onuAprNnueDBtSty7G5L5ZTLnhNj8WnVPGj872j8g5wykCA4S/H69g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSWRjSkRqdjB3Rm8yQTA4
            c3RtQW5raTlBWjZsYmRIL280T3pVaFJsbkRBClRycVlITnFoY0sxbmZVQ3N0Zy9B
            ZWtuR2xSKzNndjJNbVVkWm0wUnV2dFkKLS0tIE1VcHZiU0QxeVJERzIrSHpRZUxV
            TitUMUtpNVJhdFBFbVJMMVVQYmZ6dEEK331iMtYA3Fe/6g44QqH0fyakHnJ+FNCZ
            gF4Nbk9c+FLyhrYGJf9wSG7XcSZSJvaYoVon0Shh0/SUTOFjUm6fBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVzdJa1RoZk5USENRbHgv
            bHBwVXJHWTJOSkU0VzZua01ET3ZGM1oxNUVjCnJsV3lZOTlxWFhpZ0RYVnplNkNT
            WjhQNm82b3FvRkJtZDJBdTFla1kzY3cKLS0tIGo2SkdJMi9QZDByU3ZmRytOSnUy
            ZXA5eEtWWno2N0Q2NEJmczByNVY3TmMKSoHF5XmjVaiD5BWgKfoliGmzkRlFlOYT
            xeRS5SDPC45oquATro8jr7nQu3r62ZttRZl5d2UWGyQU90LYFom9vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T22:51:35Z"
    mac: ENC[AES256_GCM,data:q8ArLnD9BnW4zJOu2OJZFvK9N8sb+3Tn9Xwf+124oQhDzJ/cSU4Nnwnsh6ZygGP9bGdwxFnAp9ZOzi7vFtEx+vebCjwPw9LA/+gXoCY+T07PsrvAwcBOCgo0NbzChNs2NqXXSS5I92xzonN2pHMqgyJzDiJxqqDU7RA7fJErtto=,iv:aNZi9R2op46SQFokMuzDDWGhLSLB0qmdfhL6pr9QHzU=,tag:ji7uxzs7EyFjk6VDq17gNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
