apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    RAILS_ENV: ENC[AES256_GCM,data:7rYdQK8V2sz+Ng==,iv:edt1poa+5eEyCvhbwvYs1WPFoTTKgBbk4yfmQXzuT4E=,tag:EZ0WGyjxXXk+mu5wXwePpw==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:BNFqvQ==,iv:aN8q7Ky0JGTzIUGRpVVdRE1VeIyE0hePxIK+uzOldw4=,tag:2tPQUb3INTf6cJG71cRe5g==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:FQTdWKtnEQIsPVW18q7PsvsrMjiVvoK8zxI6KJArDmiGaFmnyvm2DV9LSHFqKOuANI13bjG8SwXgy8ueRyLM3DXfuHvLC3nR055eni9Qb+QiqQTdIK2clwgZowIWmbPxTnTfmaD7yxBqkeJ89gfFPPehVVElu5a9KQZeldrHajY=,iv:InI2oxGqa04uSsBNS6SMeaieqYxMGjR6nsTPiSOjNak=,tag:6D/ThxSaSGqYh/FmZBR6og==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:8w0CwC4i0QyxHLZWBg==,iv:sBPIbJLMh1xRuSDj+VapJFQu6beZNjdOSpzu0M+9Fq0=,tag:wLGvy+nZE4e6/2G2NEEiDg==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:xRZaxm5GlPwTSv1uqZHY3kDgNw==,iv:BNNIODhEeBYvqxZzwwYIth+NJtGbn76l3dr3QtpvXlU=,tag:skVLhCbhP6QH82iqoAaaow==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:OBZtF5BXBT+V6Xf+h9C13UpzErmuagglIcS0Qz//BMDN6pbpzgA6G3c=,iv:JUkhEhk7z7knKeuzgUwBBJixl68Ily8foCw7jlKmbfk=,tag:8xCPh+xEn2Q7LGjb754eew==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:UC9vk9Gg9CWXt5init4IunlC,iv:aqL9ljySz95HCfkZY8b7qahEDnfMEaJvmJUE5v4E7dY=,tag:Y3cmi/lUgz1swL4OdotTyQ==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:6lwBm/jClF1KNC1CWNzVy9VgAyrmrqI8OVeWL8Q4lTuLVaRpQoirwBc=,iv:77YjyFOYOnYginO7ehHZVVZtuRpj1JePjt0vbpYqHw4=,tag:T5AFuE4Fc05e0CkJFDXL4w==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:RHPKdGP3PSxc0GM1bbIiXymj,iv:KpG/fIr82clTbOtNorXhXZLqvATi+XO0VPGtthT6Fds=,tag:TPz2a3Jqv9lkxmPZ7bfrZA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOTJKcGxMM2NVWXd4MDJF
            a3FaMWRsdFVTK0ZoYlN2YW1CL09tbU5sbFhRCk1sb00yQzliYmZFR1pqOWRORzFi
            QmRqQnNGQlI0OWprMUlHNVRIVTJ2ZW8KLS0tIHdBbGg2bG02V1psS2d6V2NKVlJ2
            R281NlRVQ0J6KzgzdDUxblJqNkpiMTQKNVc+KPAwTh56y0DXYWEJhamrzXGc+Uot
            lVQVRXROg+wKh1adrxMBQOb2OMzKxXW0jZJ1Trdzy8LER4rQulzkAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVTNNZUtTeU8wVk9JVCtW
            dWs1a05rY0xGQUdVZWJrTkQwUmhqQlA1Tm5FCjBuRmtXYXZpRGJybUFvTmgrZnR1
            aWFETjJrMXRsSGhManRmeDRNalE5UVkKLS0tIEd1cDh6cjdIbUpza1YwMElBcENl
            RVV6d1lkeGFYbDlFbEJHL0R6aE04SmcKrU/6LexDuNz6Cly27Fw1uvaCCmXyxpNO
            cxDmQThNz9tjxqccOhFC+tK2GYfqLheIWqVK6wQXvVopZCVevR9fQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZmMvVkZnK1gyYWZPUWk5
            Z3MrQnBxQUR6M3BVV1VZamhuaTRkR0xjaVM4CmhnUyswUi9FWFY0V0U4T240M0JD
            Q1hMQ1NlWURycmNlZFVOZkVQd1VsMGMKLS0tIGtqZVVwWUxQRHlCT3U3dEhqcUFx
            SC9qaU9Na2xGeWNwSTN1TG1TNFo3Y00KNRFe0anPI3DSCy124HeqNHtH8IX+SSzh
            iTOg+cMyaJyV/pkg/NeInRFlA8pdh6sBZmnhjDRDlbZ6XDOR5gKKyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T00:10:41Z"
    mac: ENC[AES256_GCM,data:u4lRGrvVV+PJuT58MJ8QeeGTpVKJNphiV4KygmM5ThQqcP8GLzgmiWLScD/OgS1M6VslEKgJ/3PRbx1vQoTuPDAtMWzXCHSvopvQ8vifTYCEatECYzic1B8uLKhrvPfc4T1BML+qr2OCXjaEmRkp2dlKG8E2ADWk27LEc5PKFgY=,iv:9Z/JgK7otu/kxNHpW5xtUdBmkeC8KU1JAQg8E+XWlHo=,tag:mGtPtVHLVDJrfHQ2ejhe+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
