apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:9omQeGmPfsLAmDWboHzl2GHlzsIQHQsLNhrLp3fdZ4rGI8T+1Z2yOXktHGozA/h+g80Gv8m4ql26b8TYLjqICMIoFQo3sqPw+075OSaML2yOKMf90h2Dy9qGtmpid649rv7sEhzdGjQlQH6i7aorGuv60ixaUiB/m0WESoG0fK24arDjNX86uXXLqMVR9khp+kvVUQUcbF6ci91bCCbSiFsXEymyhyMjvG2A+xPuWxmXMYhvLz/MZI0CZBEctX+AhSAd6dk41gZ0ELnDsT3kQTbDOLof5jp8h4cTNVU2V04a/li7sma2Nnave5m7aSK0pslGKjqqw/6WBZlU10jaISY/fHiel8LKhFW25vthQTgbBUjGs+bWC43Qoi1Epov0SKG72hjJFUizXiTI0aIfl8mQzrm6/EGBvI6tC/mRjon/Go8i754/5Gp6tNbf/jrySCauQd876EI1HQ9rEM6nIVpDD6c/Z6C+2Lprq25pDydnNbXbDYGt+qfvKpJLz4Pm7Y0B6KR2jUUzP65QRBwR8KMklgXWU6Wvo5iUrzcH7Mz2o6IB3zYzM5eAdleNH57XxDAhxzdQI0AN+RB9TwkjtrK2RRWIAVx6alNjpp9+le8oChltgKfCaIXBVgGwwBLKRmBOY4hUmg9mMOG4Uz4cBlW16ly2h0KSONfasqePvyvqAQ6sbW9NIT9eszCaMvCCpNanGg7ZL3hualr2t+3JfVurF0HTwo40g6IF/Mcb8E1t3pvAYgEN505xx85FvhZYVnSbLQodf4pZqHTuOOxXBj/bcRbuBo2DxEhVWmW5jQPKBtOtXmkh2DNOcFuGhEWXtI78qBqMa2iohE05UEw7wwCDm5FqcJR7DFoC9xirfO0kscPuF12X1ME+sCxNnsFBKb2A3ghOssDUKEnefYP2/mY2SwsyrGelzJ4HiE8xQhNRD1amNejZJr3QNcBsgrp5W+tzmfUDrB0OqG9N1yCkAVLOLYVM40BQrpe8vcpIwYc7WOhECT04H2Lrv7z6m3DhYYDHKIYuMIJ1q4kFSbN17t8GxhP17PNLcKVfuXuY05WVbaAJhO09p7pm/vF/S/Hz8HRbBujTRzBN2Gy4JGOwY+1lgm0RLVhs2u23cwD0qgIwbMPHXKqv5b4xXFMPWWotGGRqc/7gNdEsKN+UteD5VkLHPpRvtjgSmnVMgfLj0q2CmUV4zW/D30CunbVWPXbw3SOnPGewbtO8XBq8KsDJE5of72FD2CUn2Gnuf+1wwcPEwBgNgQ0ESxgC3DWyK/S7PpweiUjikh2wsNxfTVI8ppipGS2M+vIfB9L7b9Gb/N43xDhHMYjmY4id8+ba6nJCM/BU7wEUA1dp27IFjN/j627qYdtAFsOZFJBUj2Lk3Pcoiowde2tQTE0Kp0i9B+3VkgUMX4YO1Qv+P7p5kYZSE3xHDAAnoGP393++Jw3KvOWDk29G9veKlOwBlE1piRXl4TaOQApeY+eXSXXnbYOhYPStWauWIjuCHkIfOYSoUvKvVFXXnyyAe/1Z0CmwMsq7AWaqSt4fOC82NyL4Jb5koifqzGqNODp/cIKQsKh60Fz4JHdT4UInf04vOO1H/m1o4ycLPqFy+bgd9kGY5B8vpzdAxYf3g/Gw85j7GcXD9v65K4Io4wXR9t2OaAQEbWxX474SHjpi+YjQDoy82ZgwE9MSGvQKQ4pqiSvgNDayDyJobGL+0nrImI9/zSrn6qlvW4LdSotlYmMF1/kMkWcgm9+gOFQ1mwKRCm0ZEsLd+llw0GeEpcNpRVqOtxZ/xmQxnWl9OFc14RuQGDG96NOYGfqEZ4rONedF1HL5zDTkMJF/GX5xoN7k/5Yxk4OzUSYhWT3odbNxn9PRZi5igoOwJkQznC2tn9k37MP9WZDnCLf9l55zz+IzEr+R5AL9IPTdVWGqtMc1mXq2whu8BseAoMI2jPARcVkWuaDM35RyntHoxbPEZgAeCuwaX9MyFMafkayNNFuzJtkvH8XHcalqYIRPZV40UGbRAJ4ZcQjplNYxias3lbfI7zFib9s1SVV+7s1bmPZ4z4f77YLcyPSrhi1DDv3xJ7nAc57aoOm4g732+uh0+P2i1/g8cTagYpH3Ia9y4dOsuNCc8PVjz5RmvROei49WGqh4+cK5YBz/BJuHrCn0qcP+N+DOxha5HNJU9PENaRPSKWZGCwAMOubcY/u/zdOWazZU1mFA2DHETgtqPotERSgtRx8O2Tn0++kSmgvaLAeiDcrlnE6XO4Pj0DBIhuduZoCeYpBsQjUoC1LfM8LEmhKZcKworryfCHSt/zPSVKhUaT4IZKtoR3P0kFSDB3AaimH0n+au9CszJQjgAtk30D5qTqJD71q1aGCO/Cl2uHRUK1SW0NADHEDWKzEdtnUo87Uy66a5d3MbUkqK94EqR4rG1pnMIqniMonlJFfxR3bqBL+9FQN7qJYbFLlAJ3aY07x6lbpu1BsHVTBoOtegt50p0wbiSwKpdH+u6n0JxSBVK36LbMHvwttIBnJBD5xwGl/ylZw4MrSOvEqOvgHQXoKruDLVy3bF9hLKVXmZnxtUwcPg+r0gW9y3VdvEgc813SwYlpH5qYQ5KhLfR1Bp1kUhWiB60nw+MNbOuzCwi/pMSF5vlnAO9l3uZlwDVrxZuw92pSe0YwckrwObkqRn,iv:zcFzRXcnAnbipyyI5QD7yacZeGv7U4NO7y/4YdSBy7s=,tag:AviOB/Mr56ZPeS6BujxN4w==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: blocky
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib2hrQkhYeFpLL243eWh6
            dk4xWWZwbmhzZUcvTTQ5RWIwSnJURktOS1NnCmg5OXhGZmJtV1JtamFMOTFPLzd1
            ZmV4QlR6NitJcThxcU9WTU1lUTZTdDgKLS0tIExZanR0eXlTMm1haW1vNnZManlT
            eXhVaS9oc2p3anpDNHR6dHhsNU1Zc00KYxhfwDVOZRqHcoVJ4x+YibIcZW28Z8YJ
            ehFOIU2VQ1E8mqHcEP1i0j79jr5e2lgN3JZGVxRmVRMC8IjC+b5nCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNmIxL3VGbFlNcEhGSlJT
            SGs4QU5Ndjd6TExJK2xqUUg5YmxiTnN5V2owCm5JajJHM0NPTDB6RkpEMlpiVnNs
            cFhucTJuTUdTdDBFL24yblJaUnl4WTQKLS0tIFgrZU44Y2tGdVB5YkUxTjdvcUF5
            MTZYY1ptTzFseTNNUVQreHUwRFU0bVUKmUNX9ytycYm2YwJl4lXoLGYN8EnIJ8hG
            iJ5mGeNFyB6S0YVsSF9Sa33uEUoXNQl3hbR2M3aDvtoN1Ppq7kxeUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbFRoWVMyK1NIOWFyVis2
            YVdoMi8zLzAvNlVuNFltYXZYMmEyVU9NcW1vClA0Rk5jYnJVVXUvTVpoT3Jwdjhv
            SHdEZEJmREx1VGgvdmd4UjMzeVdPYzQKLS0tIHRlUE12ZGtCZ1V2RjE4d2JwTUxw
            N29TMmgvOGQyN1JKVmRxWkxIYjkvN1kKrRG6Q+BFuWpxToQNgvRSfYRkenP70bIX
            DX1Ii3fwuCw2LxjOCJ4PAseimcAP8CLDg8gB9UijWewine3Fpb0joA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T15:46:29Z"
    mac: ENC[AES256_GCM,data:BZpaJQPeHvkDqxjdBvUyuxZ27PoBh4z6XiiB0qy43Z6TD6KR75eknzfXos62S7+PVRiXOryJnLW7gObd+H5Qjng9hz1Y6onRE72pi5mT16eGZcgXSwoWVfGmY1JRwwsLVbVhi+f9+kUjzu6/QBg6HmGvoPVwr+LM0VB2k5NgfZY=,iv:peNOKgIGWsmYpRkoLvH6UWcEVb11MsY8i/Ca3FXqm9w=,tag:wG6GK4P/mzxv9c2xx/XvuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
