apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: docling-config
    namespace: apps
stringData:
    DOCLING_SERVE_ENG_RQ_REDIS_URL: ENC[AES256_GCM,data:5aEwnlbDeoENJ4Mz2Z1EEADwEW6LYt9ulaIEX1evE+pfC7xxCUHvLY15Qy53oIEEb42o6Zw7vg==,iv:4ZfmusPldoUsCxuuHOaEP/IQ6xzmEFZQFC085uaSrt0=,tag:VWAXyMRa9HEoD0qVOJuTiw==,type:str]
    DOCLING_SERVE_MAX_SYNC_WAIT: ENC[AES256_GCM,data:S3Dv,iv:snoAlH72ousZtIZ88vO6WNFiL6kYR5BenwV1wSlJQOc=,tag:IRt4JGbVzOgKv9pHWmvrJQ==,type:str]
    DOCLING_SERVE_UNABLE_UI: ENC[AES256_GCM,data:PIcCGg==,iv:pMRl30dyTfyiU4sYeYCO5mnpjg3RnGk60t1+rhhDlj4=,tag:y839SbWZH3IGuMcPGtTXfw==,type:str]
    UVICORN_TIMEOUT_KEEP_ALIVE: ENC[AES256_GCM,data:r1uW,iv:QLLoyYj5/pIctp6OAi71roiHDqgNLQOwpv6jo53jTKo=,tag:yzL3eY8hfuoFNriLffbLag==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZk1lVWk0eDJZaXhDWEJq
            ejNCbmd4OEdEYllRY0hDSktXM0NtYUdDMTBVClJaMlFkR2xrbEhLSjltVUNSWkpp
            aXVsd214ekxlMi9iaExMbTFkR1dVREUKLS0tIHlnU1dGSy9PejhVWUlTcGdpUVlu
            K0JVY050My9rbVJHdjZzQ3BWdHp4ZTQK57QKjujjpdlKIxBkdWxoh/E/NckRYICd
            2kF8TpQU9FQJpnnCLvvAnRs3xk7PhQMYHb8FXYRqVfQmrgZppm7Nyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MFF4dnBBSGs1dEYrZmVn
            SjdyeUF6RG5RaFk2b2NFbmEySU0wM0JVMFNnCk1yS2FXS3E5V1lMQmY2cHgxMXg1
            TkFDSStiZUxobGpUZjBDYXE2UnA4ak0KLS0tIGI1YVE5TmJ3emx5UnFsTzVocWph
            cUlYNXdpUXR5K253ekZDMHJGaW9Ha28KiP87sKkojv2AFtY1fxEXsZxQ6Tk763VV
            EZM+nrHoMSNvXrawA+U/psjc81ndrCaroWSX8GUKOuEoqCePISea0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBb0d6bkplMVREU1FaWlpF
            NVdPMTBpZU1Wb2k0Qk9VMjNVamtMRWhvcDBZClNVaXNnQ09kMHByd3JQWnFmL1hl
            MThuMVJkTFNxTWZ5SGYvZDdETlVaOWsKLS0tIHhNd3hDL3hPRHRSdGZhRWtzeG9v
            M1F6czE3bUhPTko0RmQ3L2c1NGx6K28KJItE1LMywEtK5PKq0O/jneBD+Ojvd6fZ
            DcNakyojmF7I1mApDXO8J5QE4/GsM8PTrRhcK3GqRMjVQzMEmmlHYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T17:05:55Z"
    mac: ENC[AES256_GCM,data:BWtWvCnLhHtqh6uzx2ICFIrlK7ZeraOgc2AT6P3zp9rNsGN5QAaHBbLlkShTdYKT3UDY4rC5NaLpndBHJ/yrYBCvLDNHQiAjCBPqB0CeMSZgES2sZmDzYtaY/258lkmYDwRNnEjK+7rpXU/qVb1KM55RFGgFCKXaPtG9C4tHi/I=,iv:onHugFl0ZQo4zqpZ4rlqD6Doezxm1hKY1rLU/m6ZXVE=,tag:kxQYeyXusjcsjyEykTwfZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
