apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    LOG_LEVEL: ENC[AES256_GCM,data:0kgYkJg=,iv:0gZ7qRML6ccXsy60qoq33cb4RGbgqlKpFjpySVxl2cs=,tag:k4rzzQ6MxJRczLwmYL9q+w==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:NVuMRcnze4LRmg==,iv:DqJWGCR4qyKQ2q7NpSYC4EZF9oTDo7mfM6k8VliZi0E=,tag:ypHERCUj4E9UNFLX2QDV+g==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:WEjo0g==,iv:f6Ki1PEGqjRVvmUUZGkS6O/AbEZgWTbAcAxr02KfstE=,tag:ttClXygzESsmt26Ui3aS4Q==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:SI8DQflqhKjGsA==,iv:ggsgQsw+mXqv6a+2mk/kTxubvYmiAjdBPHBWilsoGG8=,tag:xlGO2vYIxc4EY1UDOiJGPw==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:7lzeXf3MGgpIf7c8J2+OaxZalTwP8RZXHcUsrE4Z5RlqNUsABfWDbtnk5sREm2r4eH+pWH8771HlsbthpuT7LIg=,iv:uBC7S+WGenT4WkEgyJeQQw1prNisnjDhz5wxIIh57s4=,tag:NGE/89TgqE9CsTMYYdt/HQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:AZTif9zcOt6aRdRqtnQ/i92tuZylFa1T5e/gJssq9WxOalupaQGH3Kf87MpNfoFOEuKxIQVpbSV5EjwYeZccl2UjxvWCxT+JXJQK8tuUh/FjV1DPfK7uVoYyykf4nUGTV5FgNFJl3HZHIB6OOg8q/7PsQJYYV+4Pmia5KzzKs/Q=,iv:nyBIk2MwC+FUnEfzfLm+dpYGegNlGO+k/ecfsTeD/AY=,tag:nVuXpFqMw/NgpL5JCxfrQA==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:TZoP8qZt3++BFLB5cWIeQw==,iv:gfP0RkLPIxGV0QxdY24AV8xnVvEFdNPC6Ru50wQix28=,tag:vsjy0SBtzsjBmw58mVdNXQ==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:nppI8i8I2KaCEPvI6//YEbEqpQ==,iv:EVBXIKkO61kWNTlRxX1Kiz//VCMWy+Wec5aiHTU2MLA=,tag:jX7T7KMFtgOOnPZRyWPrmw==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:P6j5ccEcWiZY1zt8jq+1pPkV8CEWprLKiISYeLah58+G5hTY7GD6kuk=,iv:QXXRAXBG2ih9jtUYCabkHBQBTnVsv2HncTsntW7iDB8=,tag:9/fc90CJDedmoxAe9187WQ==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:Q5cN8kjyqapBswAIi2rJNqUL,iv:8f0i5v00raYFhwUvanopeGlY+ljzWi/RTOdWiu7ia7E=,tag:lEJDZCvnSupkv4rfzT6hXQ==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:J0IZKYFY0BGgH1iyt836FULwk40WIrRrPpI+JVauAWrpmO3RVwh0pz4=,iv:QyUJxejZdGlcEOikHopus/eCGxqb/GntPVm/XBDbuZk=,tag:R8Jv/vT/5A81UdDD87qHZw==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:p3p41T/9I+ySfDs6VlXuip8s,iv:7KabTfLaz3xa6YFhHh0M3C8YppITFFYliZfp7VUKBog=,tag:VN0GE8Wk9EJu3iCJYFkmxQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdUhFOHNrc0NOQ0J4MTVj
            OWlYR2xMbUNYM25lSklWd2I3YUxvaGVNV3lzCkllWERlMy93a09TZmEvcElidFpo
            RzRXRHVRa202M0wrUmNIbjZSckRBSGsKLS0tIFo2ZkgwcDgxT3ZwVzVrVko4VVN4
            ZzBEbFFVUDBTOTNKZ3VsR0t5dG5KeUUKjM1Nvz+E1qBZoph2owqjIoVFi2xGUJF0
            GYMb0eQ2U6ALoVcEBNHAzxPh4EyFlwy9wjv7m/7OykjwKjTMANrX3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUmh1bFd6RW00NkViUXRi
            TWlFV1AxM2dMdVZHa0QvcklEK3RWTFVIU0hjCnlxMmJHak1UUVFNKzdPNUtReGNQ
            MTg2MmZNSXh6VDJsSTd1T2VkYUVwSkEKLS0tIFlHbXVEREZKZGMxWmIwK2dORjUr
            Wm1EbDJHRmh2bnM0WnBpWFdtWHZPTW8KFCi1q8gGkTzuDf0KGgeafN+dVPR1WShP
            mcMnRNu7xk1tC+tghY5DzB97OTX7kMuS5lw0tnpyjjX0HZWFINzHkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbWhIQ1UxY3kyNm5LREtp
            VWM2SzU3Z1pkNjhGVkExQnVhaVRYU204SkY0CmRlQlRVSy9OWHNnU2t5RDQ5TjZp
            OVZkZ1dZcWlaVkpka1dFMEROWGE2c2MKLS0tIGNVOGkrSEVPTHh1TFRMeHNsYUh1
            OUh5L2RCUHJsQ2lrQlFkaEVFMUNCQ0kKg1FAia+/Uf3nXk2QYGMHd6nHEareI9xk
            jsYWWJao4YsOHK6NROs8J/QLGK505yOG96mqG/XyBq7lhP1DtGC8CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T12:59:10Z"
    mac: ENC[AES256_GCM,data:i4g59nXUIoLT+iDRvQ7a5Tp0/3CPEeCalcSRh+o0Y6994kLQsCAev6ge3yudoiJICd21c1zJfU/Mu1kYo0f+WS8SSDDz5p6ZZfwBhP7fNhEcxEqRxRsfkg5s4IXvY3JnpyNOsp4Z4L++/eXS3DIHb7noDrgeVl8eqZtiO2hzTq8=,iv:XuEZ5dAg1j/v7gCUiOXCJVSCCCLjGDgLtGA7BKqQ7wo=,tag:cJQz6BdKFge++1q1kmoZYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
